# Uses the query for ETM sector LULUCF, which matches klimaattafel category Landgebruik.
# This is done since using the klimaattafel mapping could not distinguish between
# emissions and removals for CO2.

- unit = MT
- query = Q(direct_emissions_lulucf_co2_1990)
