# Uses the ETM sector LULUCF query, which matches Klimaattafel Landgebruik.
# This is done since using the klimaattafel mapping could not distinguish between CO2
# emissions and removals.

- unit = MT
- query = Q(direct_emissions_lulucf_co2_1990)
