# Uses the query for ETM sector bunkers, which matches klimaattafel category Internationaal
# transport.
# This is done since using the klimaattafel mapping could not distinguish between
# aviation and navigation for CO2.

- unit = MT
- query = Q(direct_emissions_bunkers_co2_1990)
