# As the klimaattafel mapping does not distinguish between aviation and navigation
# and the emissions of aviation and navigation are dependent on seperate ETM inputs,
# the calculation of the ETM is queried.
# The category Bunkers of the ETM matches category Internationaal transport of the klimaattafel.

- unit = MT
- query = Q(direct_emissions_bunkers_co2_1990)
