# No separate handling is required for emissions and removals since per definition, other GHG in
# the Landgebruik category can only be emissions.

- unit = MT
- query =
    DIVIDE(
        EMISSIONS(klimaattafel, "Landgebruik", co2, 1990),
        THOUSANDS
    )
