# 

- unit = pj

DIVIDE(SUM(V(co_firing_coal_energy,co_firing_gas_energy,biomass_chp_industry_energetic,bio_oil_chp_industry_energetic,collective_biomass_chp_households_energetic,biomass_chp_buildings_energetic;output_of_electricity)),BILLIONS)