# 

- unit = pj

DIVIDE(SUM(V(solar_csp_energy,solar_pv_central_production_energy_energetic,local_solar_pv_grid_connected_energy_energetic,local_solar_pv_not_grid_connected_households_energetic,solar_panels_buildings_energetic;output_of_electricity)),BILLIONS)