# The share of gas in the primary demand (excluding imported_electricity), multiplied by the total costs as calculated in the model

- unit = factor

PRODUCT( 
 DIVIDE(
  SUM(
    V(INTERSECTION(V(SECTOR(industry)),G(final_demand_cbs)); primary_demand_of_natural_gas),
    V(INTERSECTION(V(SECTOR(industry)),G(final_demand_cbs)); primary_demand_of_lng),
    V(INTERSECTION(V(SECTOR(industry)),G(final_demand_cbs)); primary_demand_of_cng)
     )
  ,
  SUM(
    V(G(final_demand_cbs); primary_demand),
    NEG(SUM(
        V(G(final_demand_cbs); primary_demand_of_imported_electricity)
        ))
     )
  ),
 Q(cost_total)
)