# The share of wind in the primary demand (excluding imported_electricity), multiplied by the total costs as calculated in the model

- unit = factor

PRODUCT( 
 DIVIDE(
  Q(primary_demand_of_electricity_assigned_to_wind)
  ,
  SUM(
    V(G(final_demand_cbs); primary_demand),
    NEG(SUM(
        V(G(final_demand_cbs); primary_demand_of_imported_electricity)
        ))
     )
  ),
 Q(cost_total)
)