# The share of sustainable_agriculture in the primary demand (excluding imported_electricity)

- unit = factor

DIVIDE(
  SUM(
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_waste),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_ambient_heat),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_ambient_cold),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_biomass),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_biofuel),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_greengas),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_biodiesel),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_bio_ethanol),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_bio_oil),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_biogas),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_algae_diesel),
    V(INTERSECTION(V(SECTOR(agriculture),SECTOR(other)),G(final_demand_cbs)); primary_demand_of_electricity)
     )
  ,
  SUM(
    V(G(final_demand_cbs); primary_demand),
    NEG(SUM(
        V(G(final_demand_cbs); primary_demand_of_imported_electricity)
        ))
     )
  )