- query =
    MAX(SUM_CURVES(
      Q(merit_industry_chemical_demand),
      Q(merit_industry_metals_demand),
      Q(merit_industry_other_demand),
      Q(merit_industry_transformation_demand)
    ))
- unit = MW