# Capital costs of distribution pipelines for households.
# The capital costs of the distribution network (based on distribution and connection pipelines) 
# are allocated to households by share of heat demand in the distribution network.

- unit = euro
- query =
  share_of_households_in_district_heating_demand = 
    DIVIDE(
      V(households_final_demand_lt_steam_hot_water,demand),
      V(energy_distribution_lt_steam_hot_water,demand)
    );
    
    PRODUCT(
      Q(heat_infrastructure_lt_distribution_pipelines_capital_costs),
      share_of_households_in_district_heating_demand
    )
