# Export of uranium_oxide

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            uranium_oxide
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
