# Export of electricity

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            electricity
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
