# Export of hydrogen (liquid)

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            liquid_hydrogen
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
