# Export of biomass products

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            wood_pellets,
            bio_oil,
            bio_kerosene,
            biodiesel,
            bio_ethanol,
            biomethanol,
            bio_lng, 
            bionaphtha, 
            bio_pyrolysis_oil
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
