# Export of natural gas

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            natural_gas
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
