# Annual maintenance costs of heat exchanger stations and substations for households,
# by share of household heat demand in the total district heating network.

- unit = euro
- query =
  share_of_households_in_district_heating_demand = 
    DIVIDE(
      V(households_final_demand_mt_steam_hot_water,demand),
      V(energy_distribution_mt_steam_hot_water,demand)
    );

    mt_distribution_station_fixed_operation_and_maintenance_costs =
      SUM(
        Q(heat_infrastructure_mt_exchanger_station_fixed_operation_and_maintenance_costs),
        Q(heat_infrastructure_mt_sub_station_fixed_operation_and_maintenance_costs),
      );
    
    PRODUCT(
      mt_distribution_station_fixed_operation_and_maintenance_costs,
      share_of_households_in_district_heating_demand
    )
