# Annual maintenance costs of primary pipelines for households,
# by share of household heat demand in the total district heating network.

- unit = euro
- query =
  share_of_households_in_district_heating_demand = 
    DIVIDE(
      V(households_final_demand_mt_steam_hot_water,demand),
      V(energy_distribution_mt_steam_hot_water,demand)
    );
    
    PRODUCT(
      SUM(
        Q(heat_infrastructure_mt_distribution_stations_depreciation_costs),
        Q(heat_infrastructure_mt_distribution_stations_capital_costs)
      ),
      share_of_households_in_district_heating_demand
    )
