# Capex for distribution pipelines for households, consisting of capital costs and depreciation costs.

- unit = euro
- query =
    SUM(
      Q(households_mt_distribution_pipelines_capital_costs),
      Q(households_mt_distribution_pipelines_depreciation_costs)
    )
