# Final consumption from industry ex. ict and refineries - fertilizers, all carriers (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     All carriers
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_from_industry_fertilizers_total)
