# Calculates the delta in capacity of decentral electiricy production technologies

- query =
    QUERY_DELTA( -> { 
        SUM(V(Q(network_hv_mv_trafo_converters),delta_in_capacity_in_mw))   
    })
- unit = MW
- deprecated_key = pl_hv_net_delta_capacity_decentral
