- deprecated_key = pl_hv_net_delta_capacity_decentral
# According to John Zwaal local solar PV should not be added to decentral capacity. The impact of it on the HS net is minimal, even when introduced on a very large scale.

- unit = MW

SUM(
    V(Q(network_hv_mv_net_converters),delta_in_capacity_in_mw)
)

