- deprecated_key = pl_hv_net_delta_capacity_total
# Sum of deltas of decentral and central production capacity

- unit = MW

SUM(
    Q(hv_net_delta_capacity_decentral),
    Q(hv_net_delta_capacity_central)
)