# Final consumption of renewable waste, all sectors (non-energetic use only).
#
# Sector:      All sectors
# Carrier:     Renewable waste
# Use type:    Non-energetic -- !energetic?
#
# Exception: includes the share of renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_renewable_waste_non_energetic)
