# Returns the share of hydrogen trucks in truck technology split

- query =
    DIVIDE(
      V(transport_truck_using_hydrogen,output_of_freight_tonne_kms),
      V(transport_useful_demand_trucks,demand)
    )
- unit = %
