# Returns the share of diesel mix trucks in truck technology split

- query =
    DIVIDE(
      V(transport_truck_using_diesel_mix,output_of_freight_tonne_kms),
      V(transport_useful_demand_trucks,demand)
    )
- unit = %
