# Returns the share of electricity cars in car technology split

- query =
    DIVIDE(
      V(transport_car_using_electricity,output_of_passenger_kms),
      V(transport_useful_demand_cars,demand)
    )
- unit = %
