# Returns the share of hydrogen cars in car technology split

- query =
    DIVIDE(
      V(transport_car_using_hydrogen,output_of_passenger_kms),
      V(transport_useful_demand_cars,demand)
    )
- unit = %
