- unit = PJ
- query =
          SUM(V(
            buildings_final_demand_for_cooling_network_gas,
            buildings_final_demand_for_cooling_electricity,
            demand
            ))
            / BILLIONS