- unit = PJ
- query =
    DIVIDE(
    	SUM(
    		V(buildings_final_demand_for_lighting_electricity,demand),
    		V(buildings_final_demand_for_appliances_electricity,demand)
    	),
    	BILLIONS
    )
