- deprecated_key = chart_electricity_demand_68_heat_and_electricity_demand_610
#

- unit = pj

DIVIDE(
	SUM(
		V(buildings_final_demand_for_lighting_electricity,demand),
		V(buildings_final_demand_for_appliances_electricity,demand)
	),
	BILLIONS
)
