# Query for Biomass Sankey diagram: connection between biofuels and losses

- unit = PJ
- query =
      DIVIDE(
        SUM(
          V(
            Q(liquid_biofuels_producers),
            output_of_loss
          ),
          V(
            G(industry_transformation),
            "output_of_bio_oil / (1 - loss_output_conversion) * loss_output_conversion"
          ),
          V(
            G(industry_transformation),
            "output_of_bio_kerosene / (1 - loss_output_conversion) * loss_output_conversion"
          ),
          V(
            G(industry_transformation),
            "output_of_biodiesel / (1 - loss_output_conversion) * loss_output_conversion"
          )
        ),
      BILLIONS
    )
