# Query for Biomass Sankey diagram: connection between biogas and electricity (incl. chp)

- unit = PJ
- query =
     DIVIDE(
      SUM(V(G(electricity_production), input_of_biogas)),
      BILLIONS
      )
