# Query for Biomass Sankey diagram: connection between biogas and losses

- unit = PJ
- query =
    DIVIDE(
      PRODUCT(
         V(energy_biogas_fermentation_wet_biomass, output_of_loss),
         (1.0 - V(EDGE(energy_greengas_upgrade_biogas, energy_distribution_biogas), parent_share))
      ),
      BILLIONS
    )
