# Query for Biomass Sankey diagram: connection between biogenic waste and electricity (incl. chp)

- unit = PJ
- query =
     DIVIDE(
      SUM(V(G(electricity_production), input_of_waste_mix)) * V(energy_distribution_biogenic_waste, share_of_energy_distribution_waste_mix),
      BILLIONS
      )
