# Query for Biomass Sankey diagram: connection between central heat production and heat demand

- unit = PJ
- query =
     DIVIDE(
      SUM(
      SUM(V(Q(central_heat_producing_converters_sankey), "input_of_biogas * steam_hot_water_output_conversion")),
      SUM(V(Q(central_heat_producing_converters_sankey), "input_of_gas_power_fuelmix * steam_hot_water_output_conversion")) * V(energy_mixer_for_gas_power_fuel, bio_oil_input_conversion),
      SUM(V(Q(central_heat_producing_converters_sankey), "input_of_waste_mix * steam_hot_water_output_conversion")) * V(energy_distribution_biogenic_waste, share_of_energy_distribution_waste_mix),
      SUM(V(Q(central_heat_producing_converters_sankey), "input_of_wood_pellets * steam_hot_water_output_conversion")),
      SUM(V(Q(central_heat_producing_converters_sankey), "input_of_torrefied_biomass_pellets * steam_hot_water_output_conversion")),
      SUM(V(Q(central_heat_producing_converters_sankey), "input_of_network_gas * steam_hot_water_output_conversion")) * Q(share_of_sustainable_gas_in_gas_network)),
      BILLIONS
      )
