# Query for Biomass Sankey diagram: connection between dry biomass and hydrogen

- unit = PJ
- query =
     DIVIDE(
      SUM(V(Q(hydrogen_producing_converters_sankey), input_of(wood_pellets, torrefied_biomass_pellets))),
      BILLIONS
      )
