# Query for Biomass Sankey diagram: connection between dry biomass and central heat

- unit = PJ
- query =
     DIVIDE(
      SUM(V(Q(central_heat_producing_converters_sankey), input_of(wood_pellets, torrefied_biomass_pellets))),
      BILLIONS
      )
