# Query for Biomass Sankey diagram: connection between dry biomass and greengas

- unit = PJ
- query =
    SUM(
        DIVIDE(
        V(energy_greengas_gasification_dry_biomass, input_of_dry_biomass),
        BILLIONS
        ),
       Q(wood_pellets_to_greengas_industry_transformation_in_sankey)
    )
    