# Query for Biomass Sankey diagram: connection between hydrogen production and losses

- unit = PJ
- query =
     DIVIDE(
      SUM(
      SUM(V(Q(hydrogen_producing_converters_sankey), "input_of_biogas * loss_output_conversion")),
      SUM(V(Q(hydrogen_producing_converters_sankey), "input_of_gas_power_fuelmix * loss_output_conversion")) * V(energy_mixer_for_gas_power_fuel, bio_oil_input_conversion),
      SUM(V(Q(hydrogen_producing_converters_sankey), "input_of_waste_mix * loss_output_conversion")) * V(energy_distribution_biogenic_waste, share_of_energy_distribution_waste_mix),
      SUM(V(Q(hydrogen_producing_converters_sankey), "input_of_wood_pellets * loss_output_conversion")),
      SUM(V(Q(hydrogen_producing_converters_sankey), "input_of_torrefied_biomass_pellets * loss_output_conversion")),
      SUM(V(Q(hydrogen_producing_converters_sankey), "input_of_network_gas * loss_output_conversion")) * Q(share_of_sustainable_gas_in_gas_network)),
      BILLIONS
      )
