# Query for Biomass Sankey diagram: connection between non biogenic carriers and greengas
# The biofuels to greengas flows are subtracted from these flows, since these are accounted for in other flows within the sankey.

- query = 
    SUM(
      DIVIDE(
        SUM(
          V(
            G(industry_transformation),
            "output_of_greengas  / (1 - loss_output_conversion - residual_heat_input_conversion)"
          )
        ), 
        BILLIONS
      ),
      NEG(
        SUM(
          Q(biofuels_to_greengas_in_biomass_sankey),
          Q(wood_pellets_to_greengas_industry_transformation_in_sankey),
          Q(greengas_to_greengas_industry_transformation_in_sankey)
        )
      )
    )

- unit = PJ