# Query for Biomass Sankey diagram: connection between wet biomass and biogas

- unit = PJ
- query =
    DIVIDE(
       PRODUCT(
          V(energy_biogas_fermentation_wet_biomass, input_of_wet_biomass),
          (1.0 - V(EDGE(energy_greengas_upgrade_biogas, energy_distribution_biogas), parent_share))
        ),
       BILLIONS
    )
