# Query for Biomass Sankey diagram: connection between wet biomass and greengas

- unit = PJ
- query =
    DIVIDE(
      SUM(
       V(energy_greengas_gasification_wet_biomass, input_of_wet_biomass),
       PRODUCT(
          V(energy_biogas_fermentation_wet_biomass, input_of_wet_biomass),
          V(EDGE(energy_greengas_upgrade_biogas, energy_distribution_biogas), parent_share)
       )
      ),
      BILLIONS
    )
