- query =
  SUM(
      Q(co2_sheet_transport_total_domestic_aviation_co2_emissions),
      Q(co2_sheet_transport_total_domestic_freight_co2_emissions),
      Q(co2_sheet_transport_total_private_transport_co2_emissions),
      Q(co2_sheet_transport_total_public_transport_co2_emissions),
      Q(co2_sheet_transport_other_ghg_emissions)
  )

- unit = T
