- query =
  SUM(
      Q(co2_sheet_industry_chemical_all_emissions),
      Q(co2_sheet_industry_waste_management_all_emissions),
      Q(co2_sheet_industry_other_all_emissions),
      Q(co2_sheet_industry_energy_sector_all_emissions),
  )

- unit = T
