- query =
  SUM(
      Q(co2_sheet_agriculture_energy_all_emissions),
      Q(co2_sheet_agriculture_manure_all_emissions),
      Q(co2_sheet_agriculture_fermentation_other_ghg),
      Q(co2_sheet_agriculture_soil_cultivation_all_emissions),
      Q(co2_sheet_agriculture_other_ghg_other.gql)
  )

- unit = T
