- query =
          SUM(
              Q(co2_sheet_transport_car_co2_emissions),
              Q(co2_sheet_transport_busses_co2_emissions),
              Q(co2_sheet_transport_trains_co2_emissions),
              Q(co2_sheet_transport_trucks_co2_emissions),
              Q(co2_sheet_transport_ships_co2_emissions)
              )

- unit = T
