- query =
  SUM(
      Q(co2_sheet_buildings_households_appliances_light_co2_emissions),
      Q(co2_sheet_buildings_households_cooking_co2_emissions),
      Q(co2_sheet_buildings_households_hot_water_co2_emissions),
      Q(co2_sheet_buildings_households_space_heating_cooling_co2_emissions),
      Q(co2_sheet_buildings_households_other_co2_emissions)
  )

- unit = T
