- query =
          SUM(
              AREA(other_emission_agriculture),
              AREA(other_emission_built_environment),
              AREA(other_emission_industry_energy),
              AREA(other_emission_transport)
              ) * MILLIONS

- unit = T
