- unit = MT
- query =
    DIVIDE(
      SUM(
        V(
          SECTOR(klimaatsector, "Mobiliteit"),
          "direct_reporting_emissions_co2_production - direct_reporting_emissions_co2_capture"
        ),
        MV(
          MSECTOR(klimaatsector, "Mobiliteit"),
          "direct_reporting_emissions_co2_production - direct_reporting_emissions_co2_capture"
        )
      ),
      BILLIONS
    )
