# Use of carrier group 'biomass_products' in chemical industry heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(industry_useful_demand_for_chemical_refineries_useable_heat)),input_of_biodiesel),
      V(CHILDREN(V(industry_useful_demand_for_chemical_refineries_useable_heat)),input_of_bio_ethanol),
      V(CHILDREN(V(industry_useful_demand_for_chemical_refineries_useable_heat)),input_of_wood_pellets),
      V(CHILDREN(V(industry_useful_demand_for_chemical_refineries_useable_heat)),input_of_bio_lng)
    ) / BILLIONS
