# Use of carrier group 'geothermal' in chemical industry heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(industry_useful_demand_for_chemical_refineries_useable_heat)),input_of_geothermal)
    ) / BILLIONS
