# Sum of all energy input flows of the industry node in the biomass sankey

- unit = PJ
- query =
    SUM(
      Q(dry_biomass_to_industry_in_biomass_sankey),
      Q(greengas_to_industry_in_biomass_sankey),
      Q(biofuels_to_industry_in_biomass_sankey)
    )
