# Sum of all energy output flows of the wet node in the biomass sankey

- unit = PJ
- query =
    SUM(
      Q(wet_biomass_to_biogas_in_biomass_sankey),
      Q(wet_biomass_to_biofuels_in_biomass_sankey),
      Q(wet_biomass_to_greengas_in_biomass_sankey)
    )
