# Sum of all energy input flows into bio_pyrolysis_oil_secondary node in the biomass sankey

- unit = PJ
- query =
    SUM(
      Q(biogenic_waste_to_bio_pyrolysis_oil_in_biomass_sankey),
      Q(bio_pyrolysis_oil_to_bio_pyrolysis_oil_in_biomass_sankey)
    )
