# Sum of all energy input flows of the biofuels node in the biomass sankey

- unit = PJ
- query =
    SUM(
      Q(wet_biomass_to_biofuels_in_biomass_sankey),
      Q(oily_biomass_to_biofuels_in_biomass_sankey),
      Q(dry_biomass_to_biofuels_in_biomass_sankey),
      Q(biogenic_waste_to_biofuels_in_biomass_sankey),
      Q(import_biofuels_in_biomass_sankey),
      Q(non_biogenic_carriers_to_biofuels_in_biomass_sankey),
      Q(greengas_to_biofuels_in_biomass_sankey)
    )
