# Total demand of oily biomass input in all nodes in which either:
#   - a bio carrier is converted into a non-bio carrier; i.e. all nodes that
#     produce electricity, heat, hydrogen or gas power fuelmix using a bio carrier (including
#     network gas as this can consist of greengas)
#   - a bio carrier is used as final demand

- unit = PJ
- query =
    SUM(
      Q(bio_fuels_from_oily_biomass),
      Q(export_of_oily_biomass),
      Q(conversion_from_oily_biomass_to_gas_power_fuelmix)
    )
