# Total demand of dry biomass input in all nodes in which either:
#   - a bio carrier is converted into a non-bio carrier; i.e. all nodes that
#     produce electricity, heat or hydrogen using a bio carrier (including
#     network gas as this can consist of greengas)
#   - a bio carrier is used as final demand

- unit = PJ
- query =
    SUM(
      Q(chp_heat_and_electricity_from_dry_biomass),
      Q(electricity_from_dry_biomass),
      Q(export_of_dry_biomass),
      Q(greengas_from_dry_biomass),
      Q(heat_from_dry_biomass),
      Q(hydrogen_from_dry_biomass),
      Q(wood_from_dry_biomass)
    )
