# Since some plants have efficiencies > 100%, the inflows and outflows of the electricity/CHP production nodes
# need not be equal. This query calculates the mismatch caused by wood pellet plants with efficiencies > 100%

- unit = PJ
- query =
      DIVIDE(
        SUM(
          V(
            FILTER(
              G(electricity_production),
              "(steam_hot_water_output_conversion + electricity_output_conversion) > 1.0"
              ),
              "input_of_wood_pellets * (steam_hot_water_output_conversion + electricity_output_conversion - 1)")
              ),
        BILLIONS)