# Sum of all energy output flows (column: 4) in the biomass sankey

- unit = PJ
- query =
    SUM(
      Q(turk_input_of_buildings_in_biomass_sankey),
      Q(turk_input_of_agriculture_in_biomass_sankey),
      Q(turk_input_of_industry_in_biomass_sankey),
      Q(turk_input_of_transport_in_biomass_sankey),
      Q(turk_input_of_households_in_biomass_sankey),
      Q(turk_input_of_bunkers_in_biomass_sankey),
      Q(turk_input_of_other_in_biomass_sankey),
      Q(turk_input_of_export_in_biomass_sankey),
      Q(turk_input_of_losses_in_biomass_sankey),
      Q(turk_input_of_non_biogenic_carriers_in_biomass_sankey)
    )
