# Sum of all energy input flows (column: 0) in the biomass sankey

- unit = PJ
- query =
    SUM(
      Q(greengas_to_greengas_in_biomass_sankey),
      Q(biogas_to_greengas_in_biomass_sankey),
      Q(biogas_to_electricity_production_in_biomass_sankey),
      Q(biogas_to_heat_production_in_biomass_sankey)
    )
