# Sum of all energy output flows of the import node in the biomass sankey 

- unit = PJ
- query =
    SUM(
      Q(import_biogenic_waste_in_biomass_sankey),
      Q(import_wet_biomass_in_biomass_sankey),
      Q(import_oily_biomass_in_biomass_sankey),
      Q(import_dry_biomass_in_biomass_sankey),
      Q(import_biofuels_in_biomass_sankey)
    )
