# Sum of all energy input flows of the dry node in the biomass sankey

- unit = PJ
- query =
    SUM(
      Q(import_dry_biomass_in_biomass_sankey),
      Q(local_dry_biomass_in_biomass_sankey)
    )
