# Since some heaters have efficiencies > 100%, the inflows and outflows of the heat production nodes
# need not be equal. This query calculates the mismatch caused by these heaters

- unit = PJ
- query =
    SUM(
      Q(turk_input_of_central_heat_prod_in_biomass_sankey_efficiency_correction_greengas),
      Q(turk_input_of_central_heat_prod_in_biomass_sankey_efficiency_correction_biogenic_waste)
    )