# Sum of all energy output flows (column: 3) in the biomass sankey with industry transformation correction
# This query corrects for the unbalanced industry_transformation node by subtracting its outputs to column 2.
#

- unit = PJ
- query =
    SUM(
      NEG(Q(industry_transformation_to_greengas_in_biomass_sankey)),
      NEG(Q(industry_transformation_to_bio_kerosene_in_biomass_sankey)),
      NEG(Q(industry_transformation_to_biodiesel_in_biomass_sankey)),
      NEG(Q(industry_transformation_to_bionaphtha_in_biomass_sankey)),
      Q(greengas_to_final_demand_households_in_biomass_sankey),
      Q(greengas_to_final_demand_buildings_in_biomass_sankey),
      Q(greengas_to_final_demand_transport_in_biomass_sankey),
      Q(greengas_to_final_demand_bunkers_in_biomass_sankey),
      Q(greengas_to_final_demand_industry_in_biomass_sankey),
      Q(greengas_to_final_demand_agriculture_in_biomass_sankey),
      Q(greengas_to_final_demand_energy_in_biomass_sankey),
      Q(greengas_to_final_demand_other_in_biomass_sankey),
      Q(greengas_to_export_in_biomass_sankey),
      Q(greengas_to_electricity_production_in_biomass_sankey),
      Q(greengas_to_heat_production_in_biomass_sankey),
      Q(greengas_to_hydrogen_production_in_biomass_sankey),
      Q(greengas_to_loss_in_biomass_sankey),
      Q(bio_kerosene_to_final_demand_households_in_biomass_sankey),
      Q(bio_kerosene_to_final_demand_buildings_in_biomass_sankey),
      Q(bio_kerosene_to_final_demand_transport_in_biomass_sankey),
      Q(bio_kerosene_to_final_demand_bunkers_in_biomass_sankey),
      Q(bio_kerosene_to_final_demand_industry_in_biomass_sankey),
      Q(bio_kerosene_to_final_demand_agriculture_in_biomass_sankey),
      Q(bio_kerosene_to_final_demand_energy_in_biomass_sankey),
      Q(bio_kerosene_to_final_demand_other_in_biomass_sankey),
      Q(bio_kerosene_to_export_in_biomass_sankey),
      Q(bio_kerosene_to_loss_in_biomass_sankey),
      Q(biodiesel_to_final_demand_households_in_biomass_sankey),
      Q(biodiesel_to_final_demand_buildings_in_biomass_sankey),
      Q(biodiesel_to_final_demand_transport_in_biomass_sankey),
      Q(biodiesel_to_final_demand_bunkers_in_biomass_sankey),
      Q(biodiesel_to_final_demand_industry_in_biomass_sankey),
      Q(biodiesel_to_final_demand_agriculture_in_biomass_sankey),
      Q(biodiesel_to_final_demand_energy_in_biomass_sankey),
      Q(biodiesel_to_final_demand_other_in_biomass_sankey),
      Q(biodiesel_to_export_in_biomass_sankey),
      Q(biodiesel_to_loss_in_biomass_sankey),
      Q(bionaphtha_to_final_demand_industry_in_biomass_sankey),
      Q(bionaphtha_to_export_in_biomass_sankey),
      Q(bionaphtha_to_loss_in_biomass_sankey),
      Q(biomethanol_to_final_demand_transport_in_biomass_sankey),
      Q(biomethanol_to_final_demand_bunkers_in_biomass_sankey),
      Q(biomethanol_to_final_demand_industry_in_biomass_sankey),
      Q(biomethanol_to_export_in_biomass_sankey),
      Q(biomethanol_to_loss_in_biomass_sankey),
      Q(bio_pyrolysis_oil_to_export_in_biomass_sankey),
      Q(bio_pyrolysis_oil_to_loss_in_biomass_sankey),
      Q(biogas_to_electricity_production_in_biomass_sankey),
      Q(biogas_to_heat_production_in_biomass_sankey),
      Q(wood_pellets_to_final_demand_households_in_biomass_sankey),
      Q(wood_pellets_to_final_demand_buildings_in_biomass_sankey),
      Q(wood_pellets_to_final_demand_transport_in_biomass_sankey),
      Q(wood_pellets_to_final_demand_bunkers_in_biomass_sankey),
      Q(wood_pellets_to_final_demand_industry_in_biomass_sankey),
      Q(wood_pellets_to_final_demand_agriculture_in_biomass_sankey),
      Q(wood_pellets_to_final_demand_energy_in_biomass_sankey),
      Q(wood_pellets_to_final_demand_other_in_biomass_sankey),
      Q(wood_pellets_to_electricity_production_in_biomass_sankey),
      Q(wood_pellets_to_heat_production_in_biomass_sankey),
      Q(torrefied_biomass_pellets_to_electricity_production_in_biomass_sankey),
      Q(torrefied_biomass_pellets_to_heat_production_in_biomass_sankey),
      Q(torrefied_biomass_pellets_to_hydrogen_production_in_biomass_sankey),
      Q(biogenic_waste_to_final_demand_industry_in_biomass_sankey),
      Q(biogenic_waste_to_electricity_production_in_biomass_sankey),
      Q(biogenic_waste_to_heat_production_in_biomass_sankey),
      Q(bio_ethanol_to_final_demand_transport_in_biomass_sankey),
      Q(bio_ethanol_to_export_in_biomass_sankey),
      Q(bio_lng_to_final_demand_transport_in_biomass_sankey),
      Q(bio_lng_to_final_demand_bunkers_in_biomass_sankey),
      Q(bio_oil_to_final_demand_households_in_biomass_sankey),
      Q(bio_oil_to_final_demand_buildings_in_biomass_sankey),
      Q(bio_oil_to_final_demand_transport_in_biomass_sankey),
      Q(bio_oil_to_final_demand_bunkers_in_biomass_sankey),
      Q(bio_oil_to_final_demand_industry_in_biomass_sankey),
      Q(bio_oil_to_final_demand_agriculture_in_biomass_sankey),
      Q(bio_oil_to_final_demand_energy_in_biomass_sankey),
      Q(bio_oil_to_final_demand_other_in_biomass_sankey),
      Q(bio_oil_to_electricity_production_in_biomass_sankey),
      Q(bio_oil_to_heat_production_in_biomass_sankey)
    )
