# Sum of all energy input flows into bio_kerosene_secondary node in the biomass sankey

- unit = PJ
- query =
    SUM(
      Q(bio_kerosene_to_bio_kerosene_in_biomass_sankey),
      Q(bio_ethanol_to_bio_kerosene_in_biomass_sankey),
      Q(biomethanol_to_bio_kerosene_in_biomass_sankey),
      Q(bio_pyrolysis_oil_to_bio_kerosene_in_biomass_sankey),
      Q(hydrogen_to_bio_kerosene_in_biomass_sankey),
      Q(steam_hot_water_to_bio_kerosene_in_biomass_sankey)
    )
