# Total demand of biogenic waste input in all nodes in which either:
#   - a bio carrier is converted into a non-bio carrier; i.e. all nodes that
#     produce electricity, heat or hydrogen using a bio carrier (including
#     network gas as this can consist of greengas)
#   - a bio carrier is used as final demand

- unit = PJ
- query =
    SUM(
      Q(chp_heat_and_electricity_from_biogenic_waste),
      Q(electricity_from_biogenic_waste),
      Q(heat_from_biogenic_waste)
    )
