# Since some heaters have efficiencies > 100%, the inflows and outflows of the heat production nodes
# need not be equal. This query calculates the mismatch caused by waste heaters with efficiencies > 100%

- unit = PJ
- query =
      DIVIDE(
        PRODUCT(
          SUM(
            V(
              FILTER(
                Q(central_heat_producing_converters_sankey),
                "steam_hot_water_output_conversion > 1.0"
                ),
                "input_of_waste_mix * (steam_hot_water_output_conversion - 1)")
                ),
          V(energy_distribution_biogenic_waste, share_of_energy_distribution_waste_mix)),
        BILLIONS)