- query =
    SUM(
      Q(conversion_loss_crude_oil_to_steam_hot_water),
      PRODUCT(
        Q(conversion_loss_gas_power_fuelmix_to_steam_hot_water),
        V(energy_mixer_for_gas_power_fuel, crude_oil_input_conversion)
      )
    )
- unit = PJ
