- query =
    DIVIDE(
      SUM(
        V(
          FILTER(G(sankey_conversion_group),"gasoline_output_conversion > 0.0 && crude_oil_input_conversion > 0.0"),
          "gasoline_output_conversion * crude_oil_input_conversion / (1 - loss_output_conversion) * output_of_loss"
        )
      ), 
      BILLIONS
    )
- unit = PJ
