- query =
    DIVIDE(
      SUM(
        V(
          FILTER(G(sankey_conversion_group),"electricity_output_conversion > 0.0 && diesel_input_conversion > 0.0"),
          "electricity_output_conversion * diesel_input_conversion / (1 - loss_output_conversion) * output_of_loss"
        )
      ), 
      BILLIONS
    )
- unit = PJ
