# Final consumption of coal and coal products, all sectors (non-energetic use only).
#
# Sector:      All sectors
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_coal_and_coal_products_non_energetic)
