# The delta (difference) between the present and the future costs of the low voltage net.

- query = QUERY_FUTURE(lv_net_total_costs_future) - QUERY_PRESENT(lv_net_total_costs_present)

- unit = euro
