# The costs of the the addition of extra capacity to the low voltage net. The average step size of added capacity can be found in the area file.

- query = AREA(lv_net_costs_per_capacity_step)

- unit = euro
