# The depreciation costs of the future interconnection net

- query =
          SUM(
              QUERY_FUTURE(interconnection_net_costs_delta_present_future_investment_costs) / Q(interconnection_net_costs_delta_present_future_technical_lifetime)
          )

- unit = euro
