# The delta (difference) between the present and the future costs of the interconnection net.

- query =
          SUM(
              QUERY_FUTURE(interconnection_net_capex),
              QUERY_FUTURE(interconnection_net_opex)
          )
- unit = euro
