# The CAPEX of the future interconnection net

- query =
          SUM(
              QUERY_FUTURE(interconnection_net_capital_costs),
              QUERY_FUTURE(interconnection_net_depreciation_costs)
          )

- unit = euro
