# The capital costs of the future interconnection net

- query =
          SUM(
              QUERY_FUTURE(interconnection_net_investment_costs) / 2.0 * V(energy_power_hv_network_electricity,wacc)
          )

- unit = euro
