- deprecated_key = chart_with_im_export_20xx_54_power_plants_787
# 

- unit = mt

future:DIVIDE(SUM(Q(co2_emissions_within_area),Q(co2_emissions_of_imported_electricity_minus_exported_electricty)),BILLIONS)