# Selects the gas input capacity of dispatchable gas heat source using the heat network producing gas converters query. Capacity of demand technologies is considered negative for the installed flexible capacities chart.

- query =
    PRODUCT(
      -1,
      SUM(
        V(
          Q(
            heat_network_flexible_producing_gas_converters
          ),
          "input_capacity * number_of_units"
        )
      )
    )
- unit = MW