# Total CO2 emissions for 1990 incl. LULUCF (4), excl indirect emissions (ind_co2) and international
# transport (1.D.1)

- unit = MT
- query =
    SUM(
      Q(direct_emissions_ipcc_co2_incl_indirect_emissions_lulucf_bunkers_1990),
      NEG(Q(direct_emissions_ipcc_ind_co2_co2_1990)),
      NEG(Q(direct_emissions_ipcc_1d1_co2_1990))
    )
