
- query =
    DIVIDE(
      PRODUCT(
        SUM(
          V(
            G(industry_transformation),
            input_of_waste_mix
          )
        ),
        Q(share_of_biogenic_waste_in_waste_mix)
      ),
      BILLIONS
    )
- unit = PJ
