# Final consumption from agriculture, all carriers (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_agriculture_energetic)
