- query =
  {
    capacity:        Q(heat_cost_capacity_chart_energy_heat_heatpump_waste_water_water_ts_lt_electricity_capacity),
    availability:    Q(heat_cost_capacity_chart_energy_heat_heatpump_waste_water_water_ts_lt_electricity_availability),
    full_load_hours: Q(heat_cost_capacity_chart_energy_heat_heatpump_waste_water_water_ts_lt_electricity_full_load_hours),
    load_factor:     Q(heat_cost_capacity_chart_energy_heat_heatpump_waste_water_water_ts_lt_electricity_load_factor),
    operating_costs: Q(heat_cost_capacity_chart_energy_heat_heatpump_waste_water_water_ts_lt_electricity_operating_costs)
  }
