- query =
  {
    capacity:        Q(heat_cost_capacity_chart_energy_heat_network_storage_mt_steam_hot_water_capacity),
    operating_costs: Q(heat_cost_capacity_chart_energy_heat_network_storage_mt_steam_hot_water_operating_costs)
  }