- query =
  {
    capacity:        Q(heat_cost_capacity_chart_energy_heat_burner_ht_crude_oil_capacity),
    availability:    Q(heat_cost_capacity_chart_energy_heat_burner_ht_crude_oil_availability),
    full_load_hours: Q(heat_cost_capacity_chart_energy_heat_burner_ht_crude_oil_full_load_hours),
    load_factor:     Q(heat_cost_capacity_chart_energy_heat_burner_ht_crude_oil_load_factor),
    operating_costs: Q(heat_cost_capacity_chart_energy_heat_burner_ht_crude_oil_operating_costs)
  }
