- query =
  {
    capacity:        Q(heat_cost_capacity_chart_energy_heat_burner_mt_coal_capacity),
    availability:    Q(heat_cost_capacity_chart_energy_heat_burner_mt_coal_availability),
    full_load_hours: Q(heat_cost_capacity_chart_energy_heat_burner_mt_coal_full_load_hours),
    load_factor:     Q(heat_cost_capacity_chart_energy_heat_burner_mt_coal_load_factor),
    operating_costs: Q(heat_cost_capacity_chart_energy_heat_burner_mt_coal_operating_costs)
  }
