- query =
  {
    capacity:        Q(heat_cost_capacity_chart_energy_heat_burner_mt_waste_mix_capacity),
    availability:    Q(heat_cost_capacity_chart_energy_heat_burner_mt_waste_mix_availability),
    full_load_hours: Q(heat_cost_capacity_chart_energy_heat_burner_mt_waste_mix_full_load_hours),
    load_factor:     Q(heat_cost_capacity_chart_energy_heat_burner_mt_waste_mix_load_factor),
    operating_costs: Q(heat_cost_capacity_chart_energy_heat_burner_mt_waste_mix_operating_costs)
  }
