- query =
  {
    capacity:        Q(heat_cost_capacity_chart_energy_heat_burner_ht_wood_pellets_capacity),
    availability:    Q(heat_cost_capacity_chart_energy_heat_burner_ht_wood_pellets_availability),
    full_load_hours: Q(heat_cost_capacity_chart_energy_heat_burner_ht_wood_pellets_full_load_hours),
    load_factor:     Q(heat_cost_capacity_chart_energy_heat_burner_ht_wood_pellets_load_factor),
    operating_costs: Q(heat_cost_capacity_chart_energy_heat_burner_ht_wood_pellets_operating_costs)
  }
