- query =
  {
    capacity:        Q(heat_cost_capacity_chart_energy_heat_burner_mt_hydrogen_capacity),
    availability:    Q(heat_cost_capacity_chart_energy_heat_burner_mt_hydrogen_availability),
    full_load_hours: Q(heat_cost_capacity_chart_energy_heat_burner_mt_hydrogen_full_load_hours),
    load_factor:     Q(heat_cost_capacity_chart_energy_heat_burner_mt_hydrogen_load_factor),
    operating_costs: Q(heat_cost_capacity_chart_energy_heat_burner_mt_hydrogen_operating_costs)
  }
