- query =
  {
    capacity:        Q(heat_cost_capacity_chart_energy_heat_backup_burner_ht_network_gas_capacity),
    availability:    Q(heat_cost_capacity_chart_energy_heat_backup_burner_ht_network_gas_availability),
    full_load_hours: Q(heat_cost_capacity_chart_energy_heat_backup_burner_ht_network_gas_full_load_hours),
    load_factor:     Q(heat_cost_capacity_chart_energy_heat_backup_burner_ht_network_gas_load_factor),
    operating_costs: Q(heat_cost_capacity_chart_energy_heat_backup_burner_ht_network_gas_operating_costs)
  }
