# As fuel cost are zero for electricity, we calculate marginal cost by taking the average electricity price per year
# to calculate fuel costs per MWh heat output
# We also add variable O&M per MWh heat output to get total marginal costs per MWh heat

- query =
        SUM(
            DIVIDE(SUM(Q(merit_order_price_curve)), HOURS_PER_YEAR) * V(energy_heat_boiler_electricity,electricity_input_conversion),
            V(energy_heat_boiler_electricity,"variable_operation_and_maintenance_costs_per_full_load_hour / heat_output_capacity")
        )
- unit = EUR
