- query = 
    SUM(
      V(energy_power_hybrid_from_offshore_network_electricity, output_of_loss),
      V(energy_power_hybrid_from_offshore_network_electricity, output_of_loss)
    ) / BILLIONS
- unit = PJ
