# This query calculates the share of the produced hot water that is heated
# with electricity.
- query = 100.0 - Q(households_water_heater_hybrid_heatpump_heat_output_share_network_gas)
- unit = factor
