- query =
    DIVIDE(
      SUM(
        V(
          G(electricity_production),
          "steam_hot_water_output_conversion / (1 - loss_output_conversion) * input_of_biogas"
        )
      ),
      BILLIONS
    )
- unit = PJ
