# This query consists of losses allocated from biomass to biomass product
# This query is used for the Sankey chart
# Losses related to green gas share in network gas are not included here, since these are
# accounted for in network gas to loss flow in the chart.
#
# The following structure is maintained:
# - Distribution losses
# - Losses from biofuel to other biofuel
# - Losses from primaire biomass carrier to biofuel

- query =
    SUM(
      Q(conversion_loss_greengas_to_greengas),
      Q(conversion_loss_biodiesel_to_biodiesel),
      Q(conversion_loss_bio_kerosene_to_bio_kerosene),
      Q(conversion_loss_bio_ethanol_to_bio_ethanol),

      Q(conversion_loss_bio_ethanol_to_bio_kerosene),
      Q(conversion_loss_bio_ethanol_to_biodiesel),
      Q(conversion_loss_biomethanol_to_bio_ethanol),
      Q(conversion_loss_biomethanol_to_bio_kerosene),
      Q(conversion_loss_biogas_to_greengas),
      Q(conversion_loss_not_defined_to_biomass_products),
      Q(conversion_loss_bio_pyrolysis_oil_to_biodiesel),
      Q(conversion_loss_bio_pyrolysis_oil_to_bio_ethanol),

      Q(conversion_loss_biogenic_waste_to_bio_kerosene),
      Q(conversion_loss_biogenic_waste_to_bio_pyrolysis_oil),
      Q(conversion_loss_biogenic_waste_to_heat_in_pyrolysis_production),
      Q(conversion_loss_biogenic_waste_to_biodiesel),
      Q(conversion_loss_biogenic_waste_to_biomethanol),
      Q(conversion_loss_biogenic_waste_to_bionaphtha),

      Q(conversion_loss_dry_biomass_to_bio_kerosene),
      Q(conversion_loss_dry_biomass_to_bio_pyrolysis_oil),
      Q(conversion_loss_dry_biomass_to_biodiesel),
      Q(conversion_loss_dry_biomass_to_biomethanol),
      Q(conversion_loss_dry_biomass_to_bionaphtha),
      Q(conversion_loss_dry_biomass_to_greengas),
      Q(conversion_loss_dry_biomass_to_torrefied_biomass_pellets),
      Q(conversion_loss_dry_biomass_to_heat_in_pyrolysis_production),
      Q(conversion_loss_dry_biomass_to_wood_pellets),

      Q(conversion_loss_oily_biomass_to_bio_kerosene),
      Q(conversion_loss_oily_biomass_to_biodiesel),
      Q(conversion_loss_oily_biomass_to_bionaphtha),
      Q(conversion_loss_oily_biomass_to_bio_oil),

      Q(conversion_loss_wet_biomass_to_bio_ethanol),
      Q(conversion_loss_wet_biomass_to_greengas),
      Q(conversion_loss_wet_biomass_to_biogas),
      Q(conversion_loss_wet_biomass_to_bio_lng)
    )
- unit = PJ
