- unit = PJ
- query =
    SUM(
        V(
        energy_upgrade_biogas,
        energy_production_bio_oil,
        energy_production_biodiesel,
        energy_production_bio_ethanol,
        energy_production_bio_kerosene,
        energy_production_biogas,
        energy_production_wood_pellets,
        energy_torrefaction_wood,
        output_of_loss
        )
    ) / BILLIONS
