# same nodes as domestic biofuel production nodes, expect for
# wood pellets (no foreign node) and bio lng (no domestic node)

- unit = PJ
- query =
    SUM(
        V(
        foreign_energy_upgrade_biogas,
        foreign_energy_production_bio_oil,
        foreign_energy_production_biodiesel,
        foreign_energy_production_bio_ethanol,
        foreign_energy_production_bio_kerosene,
        foreign_energy_production_biogas,
        foreign_energy_production_bio_lng,
        foreign_energy_torrefaction_wood,
        output_of_loss
        )
    ) / BILLIONS
