# Final demand of the 'coal_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          EG(final_demand), "coal? || coal_gas? || cokes? || lignite?"
        ),
        value
      )
    ) / BILLIONS
