# Final demand of renewable hydrogen in the 'hydrogen' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          EG(final_demand), hydrogen?
        ),
        "sustainability_share * value"
      )
    ) / BILLIONS
