# Import of coal and derivatives

- query =
    present:DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            crude_oil
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
