- query = 
		SUM(
			Q(network_to_households_in_sankey),
			Q(network_to_buildings_in_sankey),
			Q(network_to_transport_in_sankey),
			Q(network_to_industry_in_sankey),
			Q(network_to_agriculture_in_sankey),
			Q(network_to_p2g_in_sankey),
			Q(network_to_curtailment_in_sankey),
			Q(network_to_other_in_sankey),
			Q(network_to_export1_in_sankey),
			Q(network_to_export2_in_sankey),
			Q(network_to_export3_in_sankey),
			Q(network_to_export4_in_sankey),
			Q(network_to_export5_in_sankey),
			Q(network_to_export6_in_sankey),
			Q(network_to_export7_in_sankey),
			Q(network_to_export8_in_sankey),
			Q(network_to_export9_in_sankey),
			Q(network_to_export10_in_sankey),
			Q(network_to_export11_in_sankey),
			Q(network_to_export12_in_sankey),
			Q(network_to_loss_in_sankey)
		)