# The absolute value of the electricity export/import divided by the the inland electricity production

- unit = factor

DIVIDE(SUM(Q(net_electricity_import),Q(net_electricity_export)),Q(electricity_production))