# The total use of all ambient heat in the model 'left' of final demand

- query =
    SUM(
      V(
        FILTER(G(application_group),"ambient_heat_input_conversion > 0"),
    	input_of_ambient_heat
      )
    )
- unit = MJ
