# The wood_pellets used in for cooking, including the green gas used in the gas_power_fuelmix.

- query =
    SUM(
      V(households_cooker_wood_pellets,input_of_wood_pellets),
      V(households_cooker_network_gas,"input_of_network_gas * sustainability_share")
    )
- unit = mj
- deprecated_key = cooking_biomass_households
