- deprecated_key = cooling_from_electricity
# should be checked with: Q: households_cooling_electricity

- unit = mj

PRODUCT(
  DIVIDE(
    Q(electricity_used_for_cooling_in_households),
    SUM(V(Q(cooling_converters_in_households);demand))
  ),
  V(cooling_demand_households_energetic;input_of_cooling)
)