# Returns the produced electricity using geothermal heat.
# 
# It works by looking to geothermal converters.

- unit = mj

V(
  Q(electricity_producing_geothermal_converters),
  output_of_electricity
).sum


