# Returns the produced electricity using solar.
#
# It works by looking to converters directly fed by the "sun" converter that have output of electricity.

- unit = MJ
- query = V(Q(electricity_producing_solar_converters),output_of_electricity).sum
