# 

- unit = mj

PRODUCT(
 Q(share_of_greengas_in_gas_network)
 ,
 SUM(
   V(G(electricity_production);output_of_electricity * network_gas_input_conversion ),
   V(G(electricity_production);output_of_electricity * gasmix_input_conversion )
  )
 )