- unit = PJ
- query =
    SUM(
      V(
        G(cost_chps),
        output_of_electricity
      ),
      - V(energy_chp_ultra_supercritical_coal, output_of_electricity),
      - V(energy_chp_ultra_supercritical_cofiring_coal, output_of_electricity),
      - V(energy_chp_combined_cycle_network_gas, output_of_electricity),
    ) / BILLIONS
