# Returns the produced electricity using uranium.
#
# It works by looking to converters directly fed by the "uranium distribution" converter that have output of electricity.

- unit = MJ
- query = V(Q(electricity_producing_uranium_converters),output_of_electricity).sum
