# Returns the produced electricity of hybrid offshore wind that enters the onshore network.

- unit = PJ
- query =
    DIVIDE(
      V(energy_power_hybrid_from_offshore_network_electricity, output_of_electricity),
      BILLIONS
    )
