# This returns the imbalance between production and demand, as a percentage of demand.

- query =
    SUM(
      1,
      NEG(
        Q(share_of_electricity_generated_domestically)    
      )
    )
- unit = %
