# Returns the produced electricity using lignite.
#
# It works by looking to converters directly fed by the "lignite distribution" converter that have output of electricity.

- unit = MJ
- query =
    V(
      Q(electricity_producing_lignite_converters),
      "output_of_electricity * lignite_input_conversion"
    ).sum
