# The electricity from the gas CHP in industry, excluding the part from the sustainable green gas.

- query =
    DIVIDE(
      SUM(
        V(
          industry_chp_combined_cycle_gas_power_fuelmix,
          industry_chp_engine_gas_power_fuelmix,
          industry_chp_turbine_gas_power_fuelmix,
          "output_of_electricity * (1.0 - sustainability_share)"
        )
      ),
      BILLIONS
    )
- unit = pj
- deprecated_key = industy_chp_fossil_electricity
