- deprecated_key = fossil_heat_agriculture
# The fossil fuels, minus the sustainable part of the fuels.

- unit = mj

SUM(
  V(
    oil_burner_agri_agriculture_energetic,
    gas_burner_agri_agriculture_energetic,
    steam_hot_water_agriculture_energetic;
      output_of_heat_carriers
  ),

NEG(
SUM(
  V(
    oil_burner_agri_agriculture_energetic,
    gas_burner_agri_agriculture_energetic,
    steam_hot_water_agriculture_energetic;
      output_of_heat_carriers * sustainability_share
  ))))