- deprecated_key = fossil_heat_other
# The fossil fuels, minus the sustainable part of the fuels.

- unit = mj

SUM(
  V(
    gas_burner_other_other_energetic, 
    oil_burner_other_other_energetic, 
    coal_burner_other_other_energetic,
    steam_hot_water_other_energetic;
      output_of_heat_carriers)
  
,NEG(

SUM(
  V(
    gas_burner_other_other_energetic, 
    oil_burner_other_other_energetic, 
    coal_burner_other_other_energetic,
    steam_hot_water_other_energetic;
      output_of_heat_carriers * sustainability_share )
  )
))