# This determines the amount of heat from gas, minus which is produced with greengas

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            G(heat_production),
            SECTOR(industry)
            ),
          "input_of_network_gas > 0.0"),
        "output_of_heat_carriers"
        ),
      NEG(
        V(
          FILTER(
          INTERSECTION(
            G(heat_production),
            SECTOR(industry)
            ),
          "input_of_network_gas > 0.0"),
          "output_of_heat_carriers * sustainability_share"
        )
      )
    )
- deprecated_key = heat_from_gas_industry
