# Heat produced from biomass, including the heat from greengas in the gas burner.

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            G(heat_production),
            SECTOR(industry)
            ),
          "input_of_network_gas > 0.0"),
        "output_of_heat_carriers * sustainability_share"
        ),
       V(
        FILTER(
          INTERSECTION(
            G(heat_production),
            SECTOR(industry)
            ),
          "input_of_wood_pellets > 0.0"),
        "output_of_heat_carriers"
        )  
    )

- deprecated_key = heat_from_biomass_industry
