# The % biomass * the total usable heat.

- unit = MJ
- query =
    PRODUCT(
      DIVIDE(
        Q(biomass_derivatives_used_for_heating_in_buildings),
        Q(energy_used_for_heating_in_buildings)
      ),
      V(buildings_useful_demand_for_space_heating_after_insulation,input_of_useable_heat)
    )
- deprecated_key = heat_from_biomass_buildings
