# This determines the amount of heat from gas, minus which is produced with greengas

- unit = MJ
- query =
    SUM(
      V(industry_burner_network_gas,output_of_heat_carriers),
      NEG(
        V(
          industry_burner_network_gas,
          "output_of_heat_carriers * sustainability_share"
        )
      )
    )
- deprecated_key = heat_from_gas_industry
