- query =
    V(
      agriculture_geothermal,
      energy_heater_for_heat_network_geothermal,
      households_collective_geothermal,
      buildings_collective_geothermal,
      "output_of_useable_heat + output_of_steam_hot_water"
    ).sum
- unit = mj
- deprecated_key = geothermal_supply
