# 

- deprecated_key = fossil_heat
- unit = mj

SUM(
  V(
    micro_CHP_production_households,
    central_heating_households_energetic,
    heater_on_coal_households_energetic,
    heater_on_oil_households_energetic,
    cv_hot_water_households_energetic,
    cooking_energy_demand_households_energetic,
    cooling_demand_households_energetic,
    heatpump_boiler_using_city_heat_households_energetic,
    hot_water_demand_households_energetic,
    gasheatpump_households_energetic;
      output_of_heat_carriers
  ),
  NEG(
  V(
    micro_CHP_production_households,
    central_heating_households_energetic,
    heater_on_coal_households_energetic,
    heater_on_oil_households_energetic,
    cv_hot_water_households_energetic,
    cooking_energy_demand_households_energetic,
    cooling_demand_households_energetic,
    heatpump_boiler_using_city_heat_households_energetic,
    hot_water_demand_households_energetic,
    gasheatpump_households_energetic;
      input_of_electricity
   )
 )
)     