- deprecated_key = ambient_heat
# 

- unit = mj

SUM(V(
  households_water_heater_heatpump_air_water_electricity,
  households_space_heater_collective_heatpump_water_water_ts_electricity,
  households_space_heater_heatpump_ground_water_electricity,
  heatpump_using_city_heat_households_energetic,
  households_space_heater_solar_thermal,
  households_water_heater_solar_thermal,
    output_of_heat_carriers
))    
