- query =
    V(
      households_water_heater_heatpump_ground_water_electricity,
      households_water_heater_heatpump_air_water_electricity,
      households_space_heater_heatpump_air_water_electricity,
      households_space_heater_heatpump_ground_water_electricity,
      households_water_heater_solar_thermal,
      output_of_heat_carriers
    ).sum
- unit = mj
- deprecated_key = ambient_heat
