- query =
    V(
      households_space_heater_micro_chp_network_gas,
      households_collective_chp_network_gas,
      "steam_hot_water_output_conversion * demand * sustainability_share"
    ).sum
- unit = mj
