# 

- unit = mj

SUM(V(micro_chp_space_heating_households,
            collective_gas_chp_households_energetic,"
           steam_hot_water_output_conversion * demand * sustainability_share
           "))