- deprecated_key = industy_chp_renewable_electricity
# The electricity from the sustainable CHPs in industry, including the part from the sustainable green gas in the gas CHP.

- unit = pj

DIVIDE(SUM(V(biomass_chp_industry_energetic;output_of_electricity),
V(small_chp_industry_energetic;"output_of_electricity*sustainability_share")
),BILLIONS)