# Use of 'ambient' carrier group in 'heat_production'

- unit = PJ
- query =
    SUM(
      V(G(heat_production),"input_of_ambient_heat * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_ambient_cold * heat_and_cold_output_conversion")
    ) / BILLIONS
