# Use of 'solar' carrier group in 'heat_production'

- unit = PJ
- query =
    SUM(
      V(G(heat_production),"input_of_solar_radiation * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_solar_thermal * heat_and_cold_output_conversion")
    ) / BILLIONS
