# Use of 'ambient' carrier group in 'heat_production' in the buildings sector

- unit = PJ
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(buildings)
        ),
        input_of_ambient_heat
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(buildings)
        ),
        input_of_ambient_cold
      )      
    ) / BILLIONS
