# Use of 'heat' carrier group in 'heat_production' in the agriculture sector

- unit = PJ
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(agriculture)
        ),
        input_of_steam_hot_water
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(agriculture)
        ),
        input_of_useable_heat
      )      
    ) / BILLIONS
