# Use of 'coal_and_derivatives' carrier group in 'heat_production'

- unit = PJ
- query =
    SUM(
      V(G(heat_production),"input_of_coal * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_lignite * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_coal_gas * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_cokes * heat_and_cold_output_conversion")
    ) / BILLIONS
