# Use of 'oil_and_derivatives' carrier group in 'heat_production' in the households sector

- unit = PJ
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(households)
        ),
        input_of_crude_oil
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(households)
        ),
        input_of_gasoline
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(households)
        ),
        input_of_diesel
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(households)
        ),
        input_of_lpg
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(households)
        ),
        input_of_kerosene
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(households)
        ),
        input_of_heavy_fuel_oil
      )      
    ) / BILLIONS
