# Use of 'heat' carrier group in 'heat_production'

- unit = PJ
- query =
    SUM(
      V(G(heat_production),"input_of_imported_heat * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_residual_heat * heat_and_cold_output_conversion")
    ) / BILLIONS
