# CAPEX and OPEX of the costs in industry ex fuels ex CCUS.

- query =
          SUM(
              V(G(costs_building_and_installations_industry), capital_expenditures_excluding_ccs_per(:node)),
              V(G(costs_building_and_installations_industry), operating_expenses_excluding_ccs_per(:node))
              )

- unit = euro
