# CAPEX and OPEX of the costs in agriculture ex fuels ex CCUS.

- query =
          SUM(
              V(G(costs_building_and_installations_agriculture), capital_expenditures_excluding_ccs_per(:node)),
              V(G(costs_building_and_installations_agriculture), operating_expenses_excluding_ccs_per(:node))
              )

- unit = euro
