# CAPEX and OPEX of the costs in transport ex fuels ex CCUS.

- query =
          SUM(
              V(G(costs_building_and_installations_transport), capital_expenditures_excluding_ccs),
              V(G(costs_building_and_installations_transport), operating_expenses_excluding_ccs)
              )


- unit = euro
