# CAPEX and OPEX of the costs in households ex fuels ex CCUS.

- query =
          SUM(
              V(G(costs_building_and_installations_households), capital_expenditures_excluding_ccs_per(:node)),
              V(G(costs_building_and_installations_households), operating_expenses_excluding_ccs_per(:node))
              )
              +
              Q(costs_building_and_installations_households_insulation)


- unit = euro
