# Import of uranium oxide

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            coal,
            coal_gas,
            lignite,
            cokes
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
