# Import of crude oil

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            naphtha
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
