# Import of heat

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            imported_heat
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
