# Import of hydrogen (LOHC)

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            imported_lohc
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
