# Import of electricity

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            imported_electricity
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
