# Import of non-biogenic waste

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            non_biogenic_waste
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
