# Import of biomass products

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            biogenic_waste,
            oily_biomass,
            wet_biomass,
            dry_biomass,
            bio_kerosene, 
            bio_ethanol, 
            biodiesel, 
            bionaphtha, 
            biomethanol,
            bio_pyrolysis_oil
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
