# Import of biomethanol

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            biomethanol
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
