# Import of methanol

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            methanol
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
