# Returns the capacity of batteries for wind electricity for the sector energy.
- query = 
        PRODUCT(
  		V(energy_battery_wind_electricity,number_of_units),
  		V(energy_battery_wind_electricity,electricity_output_capacity)	
  		)
- unit = MW
