# Import of coal and derivatives

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            biogenic_waste
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
