# Final consumption of heat in national transport (energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_heat_in_national_transport_energetic)
