# Final consumption of heat in industry ex. ict and refineries - aluminium (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Aluminium -- EG(aluminium_industry)
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_heat_in_industry_aluminium_energetic)
