# This query calculates the heat production of all CHPs that is used
# as final demand in the agriculture sector.

- unit = MJ
- query = Q(agriculture_demand_local_steam_hot_water) - Q(backup_heater_to_local_steam_hot_water_in_sankey_agriculture)