# This query calculates the electricity production of all CHPs that is delivered
# to the MV grid, because the final demand in agriculture is already met.

- unit = MJ
- query = V(EDGE(energy_power_mv_distribution_network_electricity, agriculture_locally_available_electricity),value)