# This query calculates the total biomass demand of agricultural CHPs

- unit = MJ
- query = 
    SUM(
        V(
            EXCLUDE(
                FILTER(
                    ALL(),
                    "agriculture_heat && (agriculture_heat.type == :producer)"
                ),
                V(agriculture_heat_backup_burner_network_gas)
            ),
            input_of_wood_pellets
        )
    )