- unit = PJ
- query =
      SUM(
        PRODUCT(
          Q(input_of_crude_oil_in_industry_transformation_refineries),
          V(energy_import_crude_oil, share_of_energy_distribution_crude_oil)
          )
        )

