# Query for refinery sankey: connection between distribution and export of gasoline

- unit = PJ
- query = SUM(
            DIVIDE(V(energy_export_gasoline_backup, demand), BILLIONS),
            DIVIDE(V(energy_export_gasoline_baseload, demand), BILLIONS) 
            )
    
