# Query for refinery sankey: connection between refeinry and distribution of heavy fuel oil

- unit = PJ
- query = DIVIDE(V(industry_refinery_transformation_crude_oil, output_of_heavy_fuel_oil), BILLIONS)
