- unit = PJ
- query =
    SUM(
      Q(output_of_ammonia_in_industry_transformation_chemical_refineries),
      Q(output_of_greengas_in_industry_transformation_chemical_refineries),
      Q(output_of_hydrogen_in_industry_transformation_chemical_refineries),
      Q(output_of_natural_gas_in_industry_transformation_chemical_refineries),
      Q(output_of_methanol_in_industry_transformation_chemical_refineries),
      Q(output_of_not_defined_in_industry_transformation_chemical_refineries),
      Q(output_of_bio_kerosene_in_industry_transformation_chemical_refineries),
      Q(output_of_bio_oil_in_industry_transformation_chemical_refineries),
      Q(output_of_biodiesel_in_industry_transformation_chemical_refineries)
    )
