# Query for refinery sankey: connection between synthetic production and distribution of kerosene

- unit = PJ
- query =
    DIVIDE(
      SUM(V(Q(synthetic_fuels_kerosene_converters), output_of_kerosene)), 
      BILLIONS
    )

