# Query for refinery sankey: connection between distribution and use of lpg in industry

- unit = PJ
- query = 
      SUM(
      DIVIDE(V(industry_final_demand_lpg, demand), BILLIONS),
      DIVIDE(V(industry_final_demand_lpg_non_energetic, demand), BILLIONS)
      )