# Query for refinery sankey: connection between distribution and export of lpg

- unit = PJ
- query = 
        SUM( 
            DIVIDE(V(energy_export_lpg_backup, demand), BILLIONS),
            DIVIDE(V(energy_export_lpg_baseload, demand), BILLIONS)
            )   
