# Query for refinery sankey: connection between refinery and distribution of oil products

- unit = PJ
- query = DIVIDE(V(industry_refinery_transformation_crude_oil, output_of_oil_products), BILLIONS)