# Query for refinery sankey: connection between refinery and loss

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(industry_refinery_transformation_crude_oil, output_of_loss),
        V(industry_useful_demand_for_chemical_refineries_useable_heat,output_of_useable_heat),
        V(industry_useful_demand_for_chemical_refineries_useable_heat,output_of_residual_heat)
      ),
      BILLIONS
    )
