# Query for refinery sankey: connection between distribution and use of refinery gas in industry

- unit = PJ
- query = DIVIDE(V(industry_locally_available_refinery_gas_for_chemical, demand), BILLIONS) 