- query =
    SUM(
      Q(heat_infrastructure_mt_indoor_depreciation_costs),
      Q(heat_infrastructure_mt_indoor_capital_costs),
      Q(heat_infrastructure_households_mt_indoor_yearly_maintenance_costs),
      Q(heat_infrastructure_buildings_mt_indoor_yearly_maintenance_costs)
      )
- unit = euro