# Returns the capacity of nuclear generation 3 power plants.
- query = 
        PRODUCT(
  		V(energy_power_nuclear_gen3_uranium_oxide,number_of_units),
  		V(energy_power_nuclear_gen3_uranium_oxide,electricity_output_capacity)	
  		)
- unit = MW

