# Returns the capacity of nuclear generation 2 power plants.
- query = 
        PRODUCT(
  		V(energy_power_nuclear_gen2_uranium_oxide,number_of_units),
  		V(energy_power_nuclear_gen2_uranium_oxide,electricity_output_capacity)	
  		)
- unit = MW


