# The interconnection capacity of the area

- query =
    QUERY_FUTURE(->{
      MAX(
        MAX(V(energy_interconnector_imported_electricity, electricity_output_curve)),
        MAX(V(energy_export_electricity, electricity_input_curve)))
      )
    })
- unit = MW
