- deprecated_key = chart_lighting_51_centrally_produced_electricity_demand_366
# 

- unit = pj

QUERY_DELTA( -> { DIVIDE(SUM(V(households_final_demand_for_lighting_electricity,buildings_useful_demand_after_motion_detection_daylight_control_light,demand)),BILLIONS) } )