# Electricity production from biogenic waste

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(FILTER(
          G(electricity_production),
          "input_of_bio_resources > 0 &&
          electricity_output_conversion > 0 &&
          heat_output_conversion == 0"),
        demand_of_bio_resources_including_abroad_of(biogenic_waste))),
      BILLIONS
    )
