# Final demand of greengas (energetic + non-energetic) from dry biomass

- query =
    SUM(
      V(FILTER(
        G(final_demand_group),
        "(input_of_network_gas + input_of_compressed_network_gas) > 0"),
      demand_of_bio_resources_including_abroad_of(dry_biomass)))
- unit = MJ
