- query =
    SUM(
      V(G(costs_storage_and_conversion_h2), capital_expenditures_excluding_ccs_per(:node)),
      V(G(costs_storage_and_conversion_h2), operating_expenses_excluding_ccs_per(:node))
    )

- unit = euro
