- query =
    SUM(
      Q(heat_infrastructure_ht_storage_annualised_costs),
      Q(heat_infrastructure_mt_storage_annualised_costs),
      Q(heat_infrastructure_lt_storage_annualised_costs)
    )

- unit = euro
