- query =
    SUM(
      Q(heat_infrastructure_storage_annualised_costs),
      PRODUCT(V(energy_hydrogen_storage, "storage.cost_per_mwh"),V(energy_hydrogen_storage,demand)
      V(energy_hydrogen_storage,"storage.cost_per_mwh"*demand), 
    )

- unit = euro