#convert MJ to MWh with 1/3600

- query =
    SUM(
      SUM(
        Q(heat_infrastructure_ht_storage_annualised_costs),
        Q(heat_infrastructure_mt_storage_annualised_costs),
        Q(heat_infrastructure_lt_storage_annualised_costs)
      ),
      PRODUCT(
          V(energy_hydrogen_storage, "storage.cost_per_mwh"),
          V(energy_hydrogen_storage, "storage.volume")
      )
    )

- unit = euro
