- query =
    SUM(
      Q(costs_storage_and_conversion_p2p),
      Q(costs_storage_and_conversion_p2g),
      Q(costs_storage_and_conversion_p2h),
      Q(costs_storage_and_conversion_heat_storage),
      Q(costs_storage_and_conversion_hydrogen_storage)
    )

- unit = euro
