# Score calculated for etflex.
# The basis of the score is 1000, minus 5 times the costs in billions, minus the CO2 emissions in Mton,
# plus 5x the percentage renewability of the scenario, minus 10x the number of nuclear power plants (because of nuclear waste).
# This number is multiplied by 2 factors:
# - the reliability of the electricity production squared,
# - the balance in electricity production.

- unit = #

PRODUCT(
    SUM (
      1000,
      PRODUCT(5,NEG( DIVIDE( Q(total_costs), BILLIONS ))),
      NEG( DIVIDE( Q(total_co2_emissions), BILLIONS )),
      PRODUCT(500,Q(renewability),
      PRODUCT(10,NEG(V(nuclear_iii_energy;number_of_units)))
      )
    )
,
PRODUCT(Q(security_of_supply_reliability),Q(security_of_supply_reliability))
,
SUM(
  1,
  NEG(ABS(Q(electricity_imbalance)))
  )
)