# - (0.03 points for each percentage of electric car or heatpump)^2

- unit = #

((3*V(households_space_heater_heatpump_ground_water_electricity,share_of_households_useful_demand_for_space_heating_after_insulation_and_solar_heater_and_add_on)**2)) * -1
