# - (0.011 points for each percentage of air heatpump)^2

- query =
    -11*V(households_space_heater_hybrid_heatpump_air_water_electricity,share_of_households_useful_demand_for_space_heating_after_insulation_and_solar_heater)**2
- unit = #
