# We have defined a scenario that should be the ideal candidate for this
# for every slider that is away from its reference scenario counterpart, 
# maximally ONE (extra) penalty point is given
#
# Reference values:
#
# DEMAND
# * Isolation:         2.8
# * Electric cars:      75%
# * LED:                90%
# * Fuel cell:           5%
# * heat pump:          50%
# * solar water heater: 25%
#
# SUPPLY
# * coal plants:         0
# * gas plants:          6
# * nuclear:             0
# * wind mills:       1600
# * solar:              41%
# * green gas:           3%

- unit = #

- [
  0.111111 * (INPUT_VALUE(households_insulation_level_old_houses) - 2.8)**2,
  1.0e-4 * (INPUT_VALUE(transport_cars_electric_share) - 75.0)**2,
  1.0e-4 * (INPUT_VALUE(households_lighting_light_emitting_diode_share) - 90.0)**2,
  1.0e-4 * (INPUT_VALUE(households_heating_micro_chp_share) - 5.0)**2,
  1.0e-4 * (INPUT_VALUE(households_heating_heat_pump_ground_share) - 50.0)**2,
  1.0e-4 * (INPUT_VALUE(households_hot_water_solar_water_heater_share) - 25.0)**2,

  0.01 * (INPUT_VALUE(number_of_pulverized_coal) - 0.0)**2,
  0.027778 * (INPUT_VALUE(number_of_gas_ccgt_ccs) - 6.0)**2,
  0.25 * (INPUT_VALUE(number_of_nuclear_3rd_gen) - 0.0)**2,
  3.90625e-7 * (INPUT_VALUE(number_of_wind_offshore) - 1600.0)**2,
  1.0e-4 * (INPUT_VALUE(households_market_penetration_solar_panels) - 41.0)**2,
  1.0e-4 * (INPUT_VALUE(green_gas_total_share) - 3.0)**2
].sum
