# Score calculated for etflex.
# The basis of the score is 1000, minus 10 times the costs in billions, minus the CO2 emissions in Mton,
# plus 10x the percentage renewability of the scenario
# This number is multiplied by 2 factors:
# the reliability of the electricity production squared,
# the percentage of imbalance in electricity production,

- unit = #

PRODUCT(
    SUM (
      1000,
      PRODUCT(10,NEG( DIVIDE( Q(total_costs), BILLIONS ))),
      NEG( DIVIDE( Q(total_co2_emissions), BILLIONS )),
      PRODUCT(1000,Q(renewability))
    )
,
PRODUCT(Q(security_of_supply_reliability),Q(security_of_supply_reliability))
,
SUM(
  1,
  NEG(ABS(Q(electricity_imbalance)))
  )
)