# We have defined a scenario that should be the ideal candidate for this
# for every slider that is away from its reference scenario counterpart,
# maximally ONE (extra) penalty point is given
#
# Reference values:
#
# DEMAND
# * Isolation:          67%
# * Electric cars:      75%
# * LED:                90%
# * Electric trucks:    75%
# * Heat pump:          50%
# * Solar water heater: 25%
#
# SUPPLY
# * Coal plants:         0
# * Gas plants:          6
# * Nuclear:             0
# * Wind mills:       1600
# * Solar:              41%
# * Green gas:           3%

- query =
    - [
      1.0e-4 * (INPUT_VALUE(households_insulation_level_terraced_houses) - 67.0)**2,
      1.0e-4 * (INPUT_VALUE(transport_car_using_electricity_share) - 75.0)**2,
      1.0e-4 * (INPUT_VALUE(households_lighting_led_electricity_share) - 90.0)**2,
      1.0e-4 * (INPUT_VALUE(transport_truck_using_electricity_share) - 75.0)**2,
      1.0e-4 * (INPUT_VALUE(households_heater_heatpump_ground_water_electricity_share) - 50.0)**2,
      1.0e-4 * (INPUT_VALUE(households_water_heater_solar_thermal_share) - 25.0)**2,
      0.01 * (INPUT_VALUE(number_of_energy_power_ultra_supercritical_coal) - 0.0)**2,
      0.027778 * (INPUT_VALUE(number_of_energy_power_combined_cycle_ccs_network_gas) - 6.0)**2,
      0.25 * (INPUT_VALUE(number_of_energy_power_nuclear_gen3_uranium_oxide) - 0.0)**2,
      3.90625e-7 * (INPUT_VALUE(number_of_energy_power_wind_turbine_offshore) - 1600.0)**2,
      1.0e-4 * (INPUT_VALUE(households_solar_pv_solar_radiation_market_penetration) - 41.0)**2,
      1.0e-4 * (INPUT_VALUE(green_gas_total_share) - 3.0)**2
    ].sum
- unit = #
