# Total score calculated for ETFlex.
# We start of with ~1000 points (see base) and give penalties
#
# * cost:          penalty
# * co2:           penalty
# * imbalance:     penalty
# * reliability:   penalty
# * renewability:  penalty


- query =
      MIN(
          MAX(0,
            SUM(
              Q(etflex_score_base),
              Q(etflex_score_cost),
              Q(etflex_score_co2),
              Q(etflex_score_imbalance),
              Q(etflex_score_reliability),
              Q(etflex_score_renewability)
            )
          ),
          1000
          )
- unit = #
