# - (0.01 points for each percentage of add-on heatpump)^2

- unit = #

 -V(households_space_heater_heatpump_add_on_electricity,share_of_households_useful_demand_for_space_heating_after_insulation_for_houses_with_add_on)**2
