# Final consumption, all sectors and all carriers (non-energetic use only).
#
# Sector:      All sectors
# Carrier:     All carriers
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_non_energetic)
