- query =
    SUM(
      V(G(primary_energy_demand),primary_demand_of_coal),
      V(G(primary_energy_demand),primary_demand_of_coal_gas),
      V(G(primary_energy_demand),primary_demand_of_lignite),
      V(G(primary_energy_demand),primary_demand_of_cokes)
    ) / BILLIONS
- unit = PJ
