- query =
    SUM(
      V(G(primary_energy_demand),primary_demand_of_crude_oil),
      V(G(primary_energy_demand),primary_demand_of_diesel),
      V(G(primary_energy_demand),primary_demand_of_gasoline),
      V(G(primary_energy_demand),primary_demand_of_lpg),
      V(G(primary_energy_demand),primary_demand_of_kerosene),
      V(G(primary_energy_demand),primary_demand_of_heavy_fuel_oil)
    ) / BILLIONS
- unit = PJ
