- query =
    SUM(
      Q(total_primary_demand_of_wood_pellets),
      Q(total_primary_demand_of_torrefied_biomass_pellets),
      Q(total_primary_demand_of_biogas),
      Q(total_primary_demand_of_biodiesel),
      Q(total_primary_demand_of_bio_ethanol),
      Q(total_primary_demand_of_bio_kerosene),
      Q(total_primary_demand_of_bio_lng),
      Q(total_primary_demand_of_bio_oil),
      Q(total_primary_demand_of_greengas),
      Q(total_primary_demand_of_biogenic_waste),
      Q(total_primary_demand_of_non_biogenic_waste)
    )
- unit = PJ
