- query =
    SUM(
      V(G(primary_energy_demand),primary_demand_of_wood_pellets),
      V(G(primary_energy_demand),primary_demand_of_torrefied_biomass_pellets),
      V(G(primary_energy_demand),primary_demand_of_biogas),
      V(G(primary_energy_demand),primary_demand_of_biodiesel),
      V(G(primary_energy_demand),primary_demand_of_bio_ethanol),
      V(G(primary_energy_demand),primary_demand_of_bio_kerosene),
      V(G(primary_energy_demand),primary_demand_of_bio_lng),
      V(G(primary_energy_demand),primary_demand_of_bio_oil),
      V(G(primary_energy_demand),primary_demand_of_greengas),
      V(G(primary_energy_demand),primary_demand_of_biogenic_waste),
      V(G(primary_energy_demand),primary_demand_of_non_biogenic_waste)
    ) / BILLIONS
- unit = PJ
