- query =
    SUM(
      V(G(primary_energy_demand),primary_demand_of_natural_gas),
      V(G(primary_energy_demand),primary_demand_of_network_gas),
      V(G(primary_energy_demand),primary_demand_of_lng)
    ) / BILLIONS
- unit = PJ
