# Output of loss from bio_ethanol_to_jet transformation processes

- unit = PJ
- query = 
    SUM(
      V(
        energy_production_bio_ethanol_to_jet,
        output_of_loss
      )
    ) / BILLIONS