# Bio kerosene to Industry

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(industry_final_demand_bio_kerosene, demand),
        V(industry_final_demand_bio_kerosene_non_energetic, demand)
      ),
      BILLIONS
    )