# biomethanol to Transport

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :transport"
          ),
          bio_ethanol?
        ),
        value
      )
    ) / BILLIONS
