# Input of bio_ethanol to bio_ethanol to jet transformation

- unit = PJ
- query = 
    SUM(
      V(
        energy_production_bio_ethanol_to_jet,
        input_of_bio_ethanol)
      )
      / BILLIONS