# Biodiesel to Export

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            biodiesel
          )
        )
      ),
      BILLIONS
    )
