# Biodiesel to Industry

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(industry_final_demand_biodiesel, demand),
        V(industry_final_demand_biodiesel_non_energetic, demand)
      ),
      BILLIONS
    )
