# Import of bio pyrolysis oil

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            bio_pyrolysis_oil
          )
        )
      ),
      BILLIONS
    )