# Biofuel Import to Bionaphtha

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            bionaphtha
          )
        )
      ),
      BILLIONS
    )
