# Output of bio_kerosene from biomethanol_to_jet transformation processes

- unit = PJ
- query = 
    SUM(
      V(
        energy_production_biomethanol_to_jet,
        output_of_bio_kerosene
      )
    ) / BILLIONS