# Input of crude oil to fossil refinery transformation

- unit = PJ
- query = 
    DIVIDE(
      SUM(
        V(
          industry_refinery_transformation_crude_oil,
          industry_chemicals_refineries_burner_crude_oil,
          energy_chemical_refineries_transformation_external_coupling_node,
          input_of_crude_oil
          )
        ),
        BILLIONS
    )


