# Final demand of diesel in transport sector

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :transport"
          ),
          diesel?
        ),
        value
      )
    ) / BILLIONS