# Diesel to Industry

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(industry_final_demand_diesel, demand),
        V(industry_final_demand_diesel_non_energetic, demand)
      ),
      BILLIONS
    )
