# Input of electricity to Fischer-Tropsch transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          energy_production_fischer_tropsch_synthetic_must_run,
          energy_production_fischer_tropsch_synthetic_dispatchable,
          input_of_electricity
        )
      ),
      BILLIONS
    )
