# Output of biodiesel from Fischer-Tropsch dry biomass transformation processes

- unit = PJ
- query =
    DIVIDE(
      V(
        energy_production_fischer_tropsch_dry_biomass_ccs,
        output_of_biodiesel
      ),
      BILLIONS
    )
