# Output of biodiesel from Fischer-Tropsch transformation processes

- unit = PJ
- query = 
    SUM(
      V(
        energy_production_fischer_tropsch_synthetic_must_run,
        energy_production_fischer_tropsch_dry_biomass_ccs,
        energy_production_fischer_tropsch_non_biogenic_waste_ccs,
        energy_production_fischer_tropsch_biogenic_waste_ccs,
        output_of_biodiesel
      )
    ) / BILLIONS