# Output of oil products from Fischer-Tropsch transformation processes

- unit = PJ
- query =
    SUM(
      Q(fischer_tropsch_to_diesel),
      Q(fischer_tropsch_to_kerosene),
      Q(fischer_tropsch_to_naphtha),
      Q(fischer_tropsch_to_gasoline)
    )
