# Loss output from fossil refinery transformation

- unit = PJ
- query = 
    DIVIDE(
      SUM(
       V(
        industry_refinery_transformation_crude_oil,
        "output_of_loss"
        )
      ),
      BILLIONS
    )