# Import of pyrolysis oil

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            pyrolysis_oil
          )
        )
      ),
      BILLIONS
    )