# Import of heavy fuel oil

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            heavy_fuel_oil
          )
        )
      ),
      BILLIONS
    )