# Export of gasoline (baseload and backup)

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            gasoline
          )
        )
      ),
      BILLIONS
    )