# Kerosene to Industry

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(industry_final_demand_kerosene, demand),
        V(industry_final_demand_kerosene_non_energetic, demand)
      ),
      BILLIONS
    )
