# Output of methanol from methanol synthesis transformation

- unit = PJ
- query = 
    SUM(
      V(
        energy_production_methanol_synthesis_biogenic_waste_ccs,
        energy_production_methanol_synthesis_dry_biomass_ccs,
        energy_production_methanol_synthesis_synthetic,
        energy_production_methanol_synthesis_non_biogenic_waste_ccs,
        output_of_loss),
    ) / BILLIONS