# Input of crude oil to fossil refinery transformation

- unit = PJ
- query = 
    DIVIDE(
      SUM(
        V(
          industry_chemicals_refineries_network_gas_hybrid_heat,
          industry_chemicals_refineries_burner_network_gas,
          energy_chemical_refineries_transformation_external_coupling_node,
          input_of_network_gas
          )
        ),
        BILLIONS
    )


