# Output of loss from pyrolysis fractionation transformation

- unit = PJ
- query = 
    DIVIDE(
      SUM(
        V(
          energy_production_fractionation_pyrolysis_oil,
          energy_production_fractionation_bio_pyrolysis_oil,
          output_of_loss
        )
      ),
      BILLIONS
    )