# Output of gasoline from pyrolysis fractionation transformation

- unit = PJ
- query =
    DIVIDE(
        V(energy_production_fractionation_pyrolysis_oil,
         output_of_gasoline
        ),
        BILLIONS
    )