# Output of bio_pyrolysis_oil from pyrolysis dry biomass transformation

- unit = PJ
- query =
    DIVIDE(
      V(
        energy_production_pyrolysis_dry_biomass,
        output_of_bio_pyrolysis_oil
      ),
      BILLIONS
    )
