# Net flow of bio pyrolysis oil from pyrolysis for export (therefore not used for fractionation)
# Zero if input of bio pyrolysis oil to fractionation is higher

- unit = PJ
- query =
    MAX(
      DIVIDE(
        SUM(
          V(
            energy_production_pyrolysis_biogenic_waste,
            energy_production_pyrolysis_dry_biomass,
            output_of_bio_pyrolysis_oil
          ),
          NEG(
            V(energy_production_fractionation_bio_pyrolysis_oil, input_of_bio_pyrolysis_oil)
          )
        ),
        BILLIONS
      ),
      0.0
    )
