# Output of pyrolysis oil from pyrolysis transformation

- unit = PJ
- query = 
    DIVIDE(
        V(energy_production_pyrolysis_non_biogenic_waste,
         output_of_pyrolysis_oil
        ),
        BILLIONS
    )