# Output of bio_ethanol from pyrolysis fractionation transformation

- unit = PJ
- query =
    DIVIDE(
        V(energy_production_fractionation_bio_pyrolysis_oil,
         output_of_bio_ethanol
        ),
        BILLIONS
    )