# Refinery gas used by the refineries themselves (own use). In the liquid fuels sankey
# this is part of the fossil refinery: it does not leave the refinery as refinery gas
# and its heat is counted as refinery loss (see fossil_refinery_to_loss).

- unit = PJ
- query = Q(final_demand_of_refinery_gas_in_refineries_industry_energetic)
