- query =
    PRODUCT(
      SUM(
        CLAMP_CURVE(
          Q(network_gas_imbalance_inflexible_smoothed_delta_curve),
          -INFINITY,
          0
        )
      ),
      -1,
      MJ_PER_MWH
    ) / BILLIONS
- unit = PJ
