- unit = MT
- query =
    DIVIDE(
      SUM(
        V(
          SECTOR(klimaattafel, "Indirecte emissies"),
          direct_reporting_emissions_total_ghg_emissions
        ),
        MV(
          MSECTOR(klimaattafel, "Indirecte emissies"),
          direct_reporting_emissions_total_ghg_emissions
        )
      ),
      BILLIONS
    )
