- query =
    DIVIDE(
      SUM(
        V(industry_burner_coal, industry_other_metals_burner_network_gas, industry_steel_blastfurnace_burner_coal_gas, output_of_useable_heat)
      )
      ,BILLIONS
    )
- unit = pj
