# Final consumption of geothermal in industry refineries (non-energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Geothermal -- geothermal?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_geothermal_in_industry_refineries_non_energetic)
