# The final demand in the other sector.

- unit = MJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            EG(final_demand),"sector == :other"
          ),
          value
        )
      ),
    BILLIONS
    )
