# Final demand of the 'households' sector

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            EG(final_demand),"sector == :households"
          ),
          value
        )
      ),
    BILLIONS
    )
