# Final demand of the 'buildings' sector

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            EG(final_demand),"sector == :buildings" 
          ),
          value
        )
      ),
    BILLIONS
    )
