# Final demand of the 'transport' sector

- unit = MJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            EG(final_demand),"sector == :transport"
          ),
          value
        )
      ),
    BILLIONS
    )
