
# Returns the capacity of turbine fuelmix chp's in the industry sector.
- query = 
        PRODUCT(
  		V(industry_turbine_gas_power_fuelmix,number_of_units),
  		V(industry_turbine_gas_power_fuelmix,electricity_output_capacity)	
  		)
- unit = MW


