# Final consumption from international transport - international aviation, all carriers (energetic use only).
#
# Sector:      International transport - International aviation -- EG(bunkers_international_aviation)
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_bunkers_international_aviation_energetic)
