# Query for Sankey diagram: connection between greengas from ammonia in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_greengas * ammonia_input_conversion"
        )
      ),
      BILLIONS
    )
