# Query for Sankey diagram: connection between ammonia and oil and oil products industry transformation

- unit = PJ
- query =
    SUM(
      Q(ammonia_to_crude_oil_industry_transformation_in_sankey),
      Q(ammonia_to_diesel_industry_transformation_in_sankey),
      Q(ammonia_to_gasoline_industry_transformation_in_sankey),
      Q(ammonia_to_heavy_fuel_oil_industry_transformation_in_sankey),
      Q(ammonia_to_kerosene_industry_transformation_in_sankey),
      Q(ammonia_to_lpg_industry_transformation_in_sankey)
    )
