# Query for Sankey diagram: connection between gasoline from bio_oil in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_gasoline * bio_oil_input_conversion"
        )
      ),
      BILLIONS
    )
