# Query for Sankey diagram: connection between biomass products from biomass products in industry transformation

- unit = PJ
- query =
    SUM(
      Q(greengas_in_source_of_biomass_products_industry_transformation_in_sankey),
      Q(wood_pellets_in_source_of_biomass_products_industry_transformation_in_sankey),
      Q(bio_oil_in_source_of_biomass_products_industry_transformation_in_sankey)
    )
