# Query for Sankey diagram: connection between biomass_products and chps

- unit = PJ
- query = DIVIDE(SUM(V(Q(heat_producing_converters_sankey), primary_demand_of(non_biogenic_waste, greengas , biodiesel , bio_ethanol , bio_lng , bio_oil , biogas , torrified_biomass_pellets , wood_pellets , corn , manure , wood , biogenic_waste , woody_biomass , waste_mix))),BILLIONS)
