# Query for Sankey diagram: connection between biomass products and methanol industry transformation

- unit = PJ
- query =
    SUM(
      Q(greengas_to_methanol_industry_transformation_in_sankey),
      Q(wood_pellets_to_methanol_industry_transformation_in_sankey)
    )
