# Query for Sankey diagram: connection between biomass products and biomass products industry transformation

- unit = PJ
- query =
    SUM(
      Q(greengas_to_greengas_industry_transformation_in_sankey),
      Q(bio_oil_to_greengas_industry_transformation_in_sankey),
      Q(wood_pellets_to_greengas_industry_transformation_in_sankey)
    )
