# Query for Sankey diagram: connection between biomass_products and electricity

- unit = pj

future:DIVIDE(V(Q(electricity_producing_converters), primary_demand_of(Q(carrier_group_biomass_products))),BILLIONS)
		