# Query for Sankey diagram: connection between biomass_products and other

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(other),G(final_demand_group)),"input_of_non_biogenic_waste + input_of_greengas + input_of_biodiesel + input_of_bio_ethanol + input_of_bio_lng + input_of_bio_oil + input_of_biogas + input_of_torrified_biomass_pellets + input_of_wood_pellets + input_of_corn + input_of_manure + input_of_wood + input_of_biogenic_waste + input_of_woody_biomass + input_of_waste_mix")),BILLIONS)
