# Query for Sankey diagram: connection between biomass products and oil and oil products industry transformation

- unit = PJ
- query =
    SUM(
      Q(greengas_to_crude_oil_industry_transformation_in_sankey),
      Q(wood_pellets_to_oil_and_derivatives_industry_transformation_in_sankey)
    )
