# Query for Sankey diagram: connection between biomass products and ammonia industry transformation

- unit = PJ
- query =
    SUM(
      Q(greengas_to_ammonia_industry_transformation_in_sankey),
      Q(wood_pellets_to_ammonia_industry_transformation_in_sankey)
    )
