# Query for Sankey diagram: connection between ammonia from biomass products in industry transformation

- unit = PJ
- query =
    SUM(
      Q(greengas_in_source_of_ammonia_industry_transformation_in_sankey),
      Q(wood_pellets_in_source_of_ammonia_industry_transformation_in_sankey)
    )
