# Query for Sankey diagram: connection between biomass_products and central heat production

- query = 
    DIVIDE(
      V(
        EDGE(
          energy_production_bio_pyrolysis_locally_available_steam_hot_water,industry_locally_available_steam_hot_water
        ),
        demand
      ),
      BILLIONS
    )
- unit = PJ