# Query for Sankey diagram: connection between biomass products and natural_gas industry transformation

- unit = PJ
- query =
    SUM(
      Q(greengas_to_natural_gas_industry_transformation_in_sankey),
      Q(wood_pellets_to_natural_gas_industry_transformation_in_sankey)
    )
