# Query for Sankey diagram: connection between biomass_products and industry transformation

- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          input_of(
            wood_pellets,
            greengas
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
