# Query for Sankey diagram: connection between coal_and_derivatives and export

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(G(energy_export), "input_of_wood_pellets + input_of_biodiesel + input_of_bio_ethanol + input_of_bio_lng + input_of_bio_kerosene + input_of_greengas + input_of_dry_biomass + input_of_wet_biomass + input_of_oily_biomass + input_of_biogenic_waste + input_of_non_biogenic_waste"),
        (V(G(energy_export), input_of(network_gas, compressed_network_gas)) * Q(share_of_sustainable_gas_in_gas_network))
        ),
        BILLIONS)