# Query for Sankey diagram: connection between central heat and transport loss

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(energy_distribution_steam_hot_water, output_of_loss) * Q(fraction_of_central_heaters_in_central_heat_sankey)),
        BILLIONS)
