# Query for Sankey diagram: connection between chp heat and feedstock

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(G(final_demand_group),USE(non_energetic)),"input_of_steam_hot_water")),BILLIONS) * Q(fraction_of_chps_in_central_heat_sankey)
