# Query for Sankey diagram: connection between chps (heat) and agriculture

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(agriculture),G(final_demand_group)),"input_of_steam_hot_water")),BILLIONS)
