# Query for Sankey diagram: connection between chps (electricity) and households

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(final_demand_group)),"input_of_electricity")),BILLIONS)*(Q(fraction_of_electricity_chps_in_sankey))
