# Query for Sankey diagram: connection between chps (heat) and buildings

- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(buildings),G(final_demand_group)),"input_of_steam_hot_water")),BILLIONS)
- unit = pj
