# Query for Sankey diagram: connection between chps and loss

- query =
    DIVIDE(SUM(V(Q(heat_producing_converters_sankey), "demand + - output_of_coal - output_of_coal_gas - output_of_cokes - output_of_lignite - output_of_crude_oil - output_of_gasoline - output_of_diesel - output_of_lpg - output_of_kerosene - output_of_heavy_fuel_oil - output_of_hot_water - 
    output_of_useable_heat - output_of_cooling - output_of_car_kms - output_of_truck_kms - output_of_light - output_of_not_defined - output_of_non_biogenic_waste -
    output_of_geothermal - output_of_wind - output_of_solar_radiation - output_of_solar_thermal - output_of_water - output_of_ambient_heat - output_of_ambient_cold -
    output_of_natural_gas - output_of_lng - output_of_compressed_network_gas - output_of_gas_power_fuelmix - output_of_network_gas - output_of_uranium_oxide - output_of_greengas - 
    output_of_biodiesel - output_of_bio_ethanol - output_of_bio_oil - output_of_biogas - output_of_torrified_biomass_pellets - output_of_wood_pellets - output_of_corn - output_of_manure - 
    output_of_wood - output_of_biogenic_waste - output_of_bio_residues_for_firing - output_of_waste_mix - output_of_electricity - output_of_steam_hot_water" )),BILLIONS)
- unit = pj
