# Query for Sankey diagram: connection between coal_and_derivatives and transport

- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(transport),G(final_demand_cbs)),"input_of_coal + input_of_lignite + input_of_cokes + input_of_coal_gas")),BILLIONS)
- unit = pj
