# Query for Sankey diagram: connection between coal_and_derivatives and agriculture

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(agriculture),G(final_demand_group)),"input_of_coal + input_of_lignite + input_of_cokes + input_of_coal_gas")),BILLIONS)
