# Query for Sankey diagram: connection between coal_and_derivatives and chps

- unit = pj

future:DIVIDE(SUM(V(Q(electricity_producing_chp_converters_sankey), "input_of_coal + input_of_lignite")),BILLIONS)
		