# Query for Sankey diagram: connection between coal_and_derivatives and other

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(other),G(final_demand_group)),"input_of_coal + input_of_lignite + input_of_cokes + input_of_coal_gas")),BILLIONS)
