# Group for Sankey: all electricity producing converters including CHPs
# micro CHPs and fuel cells are excluded

- query =
    FILTER(G(electricity_production),"useable_heat_output_conversion == 0")
- unit = nodes
