# Query for Sankey diagram: connection between electricity and transport

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(transport),G(final_demand_group)),"input_of_electricity")),BILLIONS)*(1.0-Q(fraction_of_electricity_chps_in_sankey))
