# Query for Sankey diagram: connection between hydrogen from electricity in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_hydrogen * electricity_input_conversion"
        )
      ),
      BILLIONS
    )
