# Group for Sankey: all electricity producing converters that only produce electricity and no heat
# - excluding all chps
# - including local solar panels in households and buildings

- query =
    FILTER(G(electricity_production),"steam_hot_water_output_conversion && useable_heat_output_conversion == 0")
- unit = converters
