# Query for Sankey diagram: connection between electricity and energy

- unit = PJ
- query =
    DIVIDE(
      SUM(
        SUM(V(INTERSECTION(INTERSECTION(SECTOR(energy),G(final_demand_group)), USE(energetic)),"input_of_electricity")),
        V(energy_production_synthetic_kerosene_electricity, demand)
        ),
      BILLIONS)
