# Query for Sankey diagram: connection between electricity_prod and agriculture

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(agriculture),G(final_demand_cbs)),"input_of_electricity")),BILLIONS)
			