# Query for Sankey diagram: connection between electricity_prod and loss

- unit = PJ
- query =
    SUM(
        Q(biomass_products_to_electricity_prod_in_sankey),
        Q(coal_and_derivatives_to_electricity_prod_in_sankey),
        Q(geo_ambient_to_electricity_prod_in_sankey),
        Q(hydrogen_prod_to_electricity_prod_in_sankey),
        Q(natural_gas_to_electricity_prod_in_sankey),
        Q(nuclear_to_electricity_prod_in_sankey),
        Q(oil_and_derivatives_to_electricity_prod_in_sankey),
        Q(solar_to_electricity_prod_in_sankey),
        Q(water_to_electricity_prod_in_sankey),
        Q(wind_to_electricity_prod_in_sankey),
        NEG(
            SUM(Q(electricity_prod_to_agriculture_in_sankey),
                Q(electricity_prod_to_buildings_in_sankey),
                Q(electricity_prod_to_bunkers_in_sankey),
                Q(electricity_prod_to_export_in_sankey),
                Q(electricity_prod_to_households_in_sankey),
                Q(electricity_prod_to_hydrogen_prod_in_sankey),
                Q(electricity_prod_to_industry_in_sankey),
                Q(electricity_prod_to_other_in_sankey),
                Q(electricity_prod_to_transport_in_sankey)
            )
        )
    )
