# Query for Sankey diagram: connection between electricity and central heat corrected for p2h central heat which is shown explicitly

- unit = PJ
- query = Q(electricity_prod_to_central_heat_prod_in_sankey) - Q(electricity_prod_to_p2h_central_heat_in_sankey)
