# Query for Sankey diagram: connection between electricity and electricity

- unit = pj

future:DIVIDE(V(Q(electricity_producing_converters), primary_demand_of(Q(carrier_group_electricity))),BILLIONS)
		