# Query for Sankey diagram: connection between refinery_gas from electricity in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_refinery_gas * electricity_input_conversion"
        )
      ),
      BILLIONS
    )
