# Query for Sankey diagram: connection between electricity and households

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(final_demand_cbs)),"input_of_electricity")),BILLIONS)*Q(electricity_scale_factor_in_sankey)*(1.0-Q(fraction_of_electricity_chps_in_sankey))
			