# Query for Sankey diagram: connection between biomass products from electricity in industry transformation

- unit = PJ
- query = Q(electricity_in_source_of_greengas_industry_transformation_in_sankey)
