# Query for Sankey diagram: connection between electricity_prod and transport

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(transport),G(final_demand_cbs)),"input_of_electricity + input_of_imported_electricity")),BILLIONS)
			