# Query for Sankey diagram: connection between lpg from electricity in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_lpg * electricity_input_conversion"
        )
      ),
      BILLIONS
    )
