# Fraction of electricity production from chps relative to non-chp e-producing converters in Sankey

- unit = 

SUM(V(Q(electricity_producing_chp_converters_sankey), output_of_electricity))/
SUM(V(CHILDREN(V(energy_power_hv_network_electricity)), output_of_electricity))