# Fraction of electricity production from chps relative to non-chp e-producing converters in Sankey

- unit = 

SUM(V(Q(electricity_producing_chp_converters_sankey), output_of_steam_hot_water))/
SUM(V(CHILDREN(V(energy_heat_network_steam_hot_water)), output_of_steam_hot_water))