# Query for Sankey diagram: connection between geo_ambient and industry

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(final_demand_group)),"input_of_geothermal + input_of_ambient_heat + input_of_ambient_cold")),BILLIONS)
