# Query for Sankey diagram: connection between geo_solar_wind_water_ambient and agriculture

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(agriculture),G(final_demand_group)),"input_of_geothermal + input_of_wind + input_of_solar_radiation + input_of_solar_thermal + input_of_water + input_of_ambient_heat + input_of_ambient_cold")),BILLIONS)
