# Query for Sankey diagram: connection between geo_ambient and hydrogen_production

- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(Q(hydrogen_producing_converters_sankey).select {|node| node.input_slots.detect { |slot| slot.carrier.geothermal? }}, "input_of_geothermal + input_of_ambient_heat + input_of_ambient_cold"),
            V(Q(hydrogen_producing_converters_sankey).select {|node| node.input_slots.detect { |slot| slot.carrier.ambient_heat? }}, "input_of_geothermal + input_of_ambient_heat + input_of_ambient_cold"),
            V(Q(hydrogen_producing_converters_sankey).select {|node| node.input_slots.detect { |slot| slot.carrier.ambient_cold? }}, "input_of_geothermal + input_of_ambient_heat + input_of_ambient_cold")
        ),
    BILLIONS)
