# Query for Sankey diagram: connection between geo_solar_wind_water_ambient and heat

- query = DIVIDE(SUM(V(Q(heat_producing_converters_sankey), primary_demand_of(geothermal , wind , solar_radiation , solar_thermal , water , ambient_heat , ambient_cold, electricity))),BILLIONS)
- unit = pj
