# Query for Sankey diagram: connection between methanol from greengas in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_methanol * greengas_input_conversion"
        )
      ),
      BILLIONS
    )
