# Query for Sankey diagram: connection between greengas and diesel industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "diesel_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_greengas"
        )
      ),
      BILLIONS
    )
