# GroupforSankey

- query =
    V(
    buildings_collective_geothermal,
    buildings_collective_burner_network_gas,
    buildings_collective_burner_hydrogen,
    buildings_collective_heatpump_water_water_electricity,
    energy_heater_for_heat_network_coal,
    energy_heater_for_heat_network_crude_oil,
    energy_heater_for_heat_network_geothermal,
    energy_heater_for_heat_network_lignite,
    energy_heater_for_heat_network_network_gas,
    energy_heater_for_heat_network_waste_mix,
    energy_heater_for_heat_network_wood_pellets,
    households_collective_geothermal,
    households_collective_burner_network_gas,
    households_collective_burner_hydrogen,
    households_collective_heatpump_water_water_electricity,
    households_water_heater_solar_thermal
    )
- unit = converters
