#GroupforSankey

-unit=converters

V(
energy_power_supercritical_waste_mix, 
energy_heater_for_heat_network_geothermal, 
energy_heat_remainder_from_heat_network_used_steam_hot_water, 
energy_heater_for_heat_network_coal, 
energy_heater_for_heat_network_lignite, 
energy_heater_for_heat_network_crude_oil, 
energy_heater_for_heat_network_network_gas, 
energy_heater_for_heat_network_waste_mix, 
energy_heater_for_heat_network_wood_pellets, 
energy_import_steam_hot_water
)