# GroupforSankey: all central heat producing nodes plus three local chps in
# households that are connected to the central gas network

- query =
    V(
      G(heat_production).select {|node| node.output_slots.detect { |slot| slot.carrier.steam_hot_water? }},
      households_space_heater_micro_chp_network_gas,
      households_water_heater_micro_chp_network_gas,
      households_water_heater_fuel_cell_chp_network_gas
    )
- unit = converters
