# Query for Sankey diagram: connection between hybrid offshore electrolyser and hydrogen_production

- unit = PJ
- query = DIVIDE(V(energy_hydrogen_hybrid_electrolysis_wind_electricity, output_of_hydrogen),BILLIONS)
