# Total of hydrogen to oil products in methanol-to-jet and pyrolysis oil and fractionation

- query =
    SUM(
      Q(hydrogen_in_source_of_methanol_to_jet_products_in_sankey),
      Q(hydrogen_in_source_of_pyrolysis_oil_fractionation_products_in_sankey)
    )
- unit = PJ
