# Query for Sankey diagram: connection between hydrogen_production and bunkers

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(bunkers),G(final_demand_group)), USE(energetic)), "input_of_hydrogen")), BILLIONS)
