# Direct conversion input of hydrogen for biomass_products
# The function is broken down due to limited allowed inputs in V() function

- query =
    DIVIDE(
      SUM(
        V(
          Q(liquid_biofuels_producers),
          "output_of_greengas * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_wood_pellets * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_torrefied_biomass_pellets * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_biodiesel * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_bio_ethanol * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_bio_lng * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_bio_kerosene * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_bio_oil * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_biomethanol * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_bionaphtha * hydrogen_input_conversion"
        ),
        V(
          Q(liquid_biofuels_producers),
          "output_of_bio_pyrolysis_oil * hydrogen_input_conversion"
        )
      ),
      BILLIONS
    )
- unit = PJ
