# Query for Sankey diagram: connection between hydrogen_production and other

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(other),G(final_demand_group)), USE(energetic)), "input_of_hydrogen")), BILLIONS)
