# Query for Sankey diagram: connection between hydrogen_production and export

- query =
    DIVIDE(
      SUM(
        V(energy_export_hydrogen_backup,demand),
        V(energy_export_hydrogen_baseload,demand)
      ),
      BILLIONS
    )
- unit = PJ

