# Query for Sankey diagram: connection between kerosene from hydrogen in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_kerosene * hydrogen_input_conversion"
        )
      ),
      BILLIONS
    )
