# Query for Sankey diagram: connection between hydrogen_import and hydrogen_prodcution

- unit = PJ
- query = DIVIDE(SUM(V(Q(hydrogen_producing_converters_sankey), input_of_imported_hydrogen)),BILLIONS)
