# Query for Sankey diagram: connection between hydrogen_production and industry

- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(INTERSECTION(INTERSECTION(SECTOR(industry),G(final_demand_group)),USE(energetic)),"input_of_hydrogen")
        ),
    BILLIONS)
