# GroupforSankey

- query =
    V(
    energy_hydrogen_biomass_gasification_ccs,
    energy_hydrogen_biomass_gasification,
    energy_hydrogen_steam_methane_reformer_ccs,
    energy_hydrogen_steam_methane_reformer,
    energy_imported_hydrogen_distribution,
    energy_hydrogen_electrolysis_solar_electricity,
    energy_hydrogen_electrolysis_wind_electricity,
    energy_hydrogen_flexibility_p2g_electricity
    )
- unit = converters
