# Query for Sankey diagram: connection between hydrogen_production and transport loss

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
        energy_hydrogen_distribution_compressed_trucks,
        energy_hydrogen_after_transport,
        output_of_loss)),
        BILLIONS)
