# Query for Sankey diagram: connection between ammonia and agriculture

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(agriculture),G(final_demand_group)), USE(energetic)), "input_of_ammonia")), BILLIONS)
