# Query for Sankey diagram: connection between ammonia and transport

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(transport),G(final_demand_group)), USE(energetic)), "input_of_ammonia")), BILLIONS)
