# Query for Sankey diagram: connection between import and electricity_prod

- unit = PJ
- query = DIVIDE(SUM(V(Q(electricity_producing_converters_sankey), primary_demand_of(imported_hydrogen))),BILLIONS)
