# Query for Sankey diagram: connection between imported lohc and export

- query =
    DIVIDE(
      SUM(
        V(energy_export_lohc_backup,demand),
        V(energy_export_lohc_baseload,demand)
      ),
      BILLIONS
    )
- unit = PJ
