# Query for Sankey diagram: connection between industry transformation and biomass_products

- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          output_of_greengas
        )
      ),
      BILLIONS
    )
- unit = PJ
