# Query for Sankey diagram: connection between transformation nodes and oil and derivatives

- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          output_of(
            crude_oil,
            diesel,
            gasoline,
            lpg,
            kerosene,
            heavy_fuel_oil
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
