# Query for Sankey diagram: connection between refinery_gas from methanol in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_refinery_gas * methanol_input_conversion"
        )
      ),
      BILLIONS
    )
