# Query for Sankey diagram: connection between methanol and industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          input_of_methanol
        )
      ),
      BILLIONS
    )
