# Query for Sankey diagram: connection between distribution and other

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(other),G(final_demand_cbs)),"input_of_waste_mix + input_of_compressed_network_gas + input_of_gas_power_fuelmix + input_of_network_gas ")),BILLIONS)
			