# Query for Sankey diagram: connection between natural_gas and households

- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(final_demand_cbs)),"input_of_natural_gas + input_of_lng + input_of_compressed_network_gas + input_of_gas_power_fuelmix + input_of_network_gas")),BILLIONS)
- unit = pj
