# Query for Sankey download: connection between natural_gas and electricity
# Second query accounts for share of fossil network gas in torrefied wood pellets conversion for electricity

- unit = PJ
- query = 
    SUM(
      Q(gas_for_electricity_conversion),
      PRODUCT(
        DIVIDE(
          Q(torrefied_biomass_pellets_for_electricity_conversion),
          1 - V(energy_torrefaction_wood, loss_output_conversion)
        ),
        V(energy_torrefaction_wood, network_gas_input_conversion)
      ) * Q(share_of_fossil_gas_in_gas_network)
    )
