# Query for Sankey diagram: connection between natural_gas and electricity

- unit = pj

future:DIVIDE(SUM(V(Q(electricity_producing_converters), "input_of_natural_gas + input_of_lng + input_of_compressed_network_gas + input_of_gas_power_fuelmix + input_of_network_gas")),BILLIONS)
		