# Query for Sankey diagram: connection between natural_gas and biomass products industry transformation

- unit = PJ
- query = 
    SUM(
      Q(natural_gas_to_greengas_industry_transformation_in_sankey),
      Q(natural_gas_to_biodiesel_industry_transformation_in_sankey),
      Q(natural_gas_to_bio_kerosene_industry_transformation_in_sankey),
      Q(natural_gas_to_bio_oil_industry_transformation_in_sankey)
    )
