# Query for Sankey diagram: connection between natural_gas and heavy_fuel_oil industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "heavy_fuel_oil_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_natural_gas"
        )
      ),
      BILLIONS
    )
