# Query for Sankey diagram: connection between natural_gas and feedstock

- unit = PJ
- query =
    DIVIDE(
      SUM(
        SUM(
          V(INTERSECTION(G(final_demand_group),USE(non_energetic)),"input_of_natural_gas + input_of_lng + input_of_propane")
        ),
        SUM( 
          V(INTERSECTION(G(final_demand_group),USE(non_energetic)),"input_of_compressed_network_gas + input_of_network_gas")
        ) * Q(share_of__in_gas_network)
      ),
      BILLIONS
    )
