# Query for Sankey diagram: connection between greengas from natural_gas in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_biodiesel * natural_gas_input_conversion"
        )
      ),
      BILLIONS
    )
