# Query for Sankey diagram: connection between natural_gas and export

- unit = PJ
- query =
    DIVIDE(
      SUM(
        SUM(
          V(G(energy_export),"input_of_natural_gas + input_of_lng + input_of_propane")
        ),
        SUM(
          V(G(energy_export),"input_of_network_gas").sum,
          PRODUCT(
            V(G(energy_export),"input_of_compressed_network_gas").sum,
            Q(share_of_network_gas_in_compressed_network_gas)
          )
        ) * Q(share_of_fossil_gas_in_gas_network)
      ),
      BILLIONS
    )
