# Query for Sankey diagram: connection between natural_gas and electricity

- unit = pj

future:DIVIDE(V(Q(electricity_producing_converters), primary_demand_of(Q(carrier_group_natural_gas))),BILLIONS)
		