# Direct conversion input of natural gas for industry transformation

- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          input_of_natural_gas
        )
      ),
      BILLIONS
    )
- unit = PJ
