# Query for Sankey diagram: connection between natural_gas and transport
# The last query accounts for share of network gas in compressed network gas

- unit = PJ
- query = Q(final_demand_of_natural_gas_and_derivatives_in_transport_energetic)
