# Query for Sankey diagram: connection between distribution and transport

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(transport),G(final_demand_cbs)),"input_of_natural_gas + input_of_lng")),BILLIONS)
			