# Query for Sankey diagram: connection between kerosene from natural_gas in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_kerosene * natural_gas_input_conversion"
        )
      ),
      BILLIONS
    )
