# Query for Sankey diagram: connection between non_renewable_waste and heat

- unit = pj

future:DIVIDE(SUM(V(G(heat_production), primary_demand_of(Q(carrier_group_non_renewable_waste)))),BILLIONS)
		