# Query for Sankey diagram: connection between non_renewable_waste and households

- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(final_demand_cbs)),"input_of_non_biogenic_waste")),BILLIONS)
- unit = pj
