# Query for Sankey diagram: connection between distribution and households

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(final_demand_cbs)),"input_of_non_biogenic_waste")),BILLIONS)
			