# Query for Sankey diagram: connection between non_renewable_waste and electricity

- unit = pj

future:DIVIDE(V(Q(electricity_producing_converters), primary_demand_of(Q(carrier_group_non_renewable_waste))),BILLIONS)
		