# Query for Sankey diagram: connection between biomass products from not_defined in industry transformation

- unit = PJ
- query = Q(not_defined_in_source_of_greengas_industry_transformation_in_sankey)
