# Query for Sankey diagram: connection between nuclear and agriculture

- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(agriculture),G(final_demand_group)),"input_of_uranium_oxide")),BILLIONS)
- unit = pj
