# Query for Sankey diagram: connection between oil_and_derivatives and export

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            crude_oil,
            gasoline,
            diesel,
            lng,
            kerosene,
            heavy_fuel_oil,
            naphtha,
            pyrolysis_oil
          )
        )
      ),
      BILLIONS
    )
