# Query for Sankey diagram: connection between oil_and_derivatives and chps

- unit = pj

future:DIVIDE(SUM(V(Q(electricity_producing_chp_converters_sankey), "input_of_crude_oil + input_of_gasoline + input_of_diesel + input_of_lpg + input_of_kerosene + input_of_heavy_fuel_oil")),BILLIONS)
		