# Query for Sankey diagram: connection between oil_and_derivatives and heat

- unit = pj

future:DIVIDE(SUM(V(G(heat_production), primary_demand_of(Q(carrier_group_oil_and_derivatives)))),BILLIONS)
		