# Query for Sankey diagram: connection between oil_and_derivatives and transport

- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(transport),G(final_demand_cbs)),"input_of_crude_oil + input_of_gasoline + input_of_diesel + input_of_lpg + input_of_kerosene + input_of_heavy_fuel_oil")),BILLIONS)
- unit = pj
