# Query for Sankey diagram: connection between oil and derivatives and biomass products industry transformation

- unit = PJ
- query =
    SUM(
      Q(crude_oil_to_greengas_industry_transformation_in_sankey),
      Q(diesel_to_greengas_industry_transformation_in_sankey),
      Q(gasoline_to_greengas_industry_transformation_in_sankey),
      Q(heavy_fuel_oil_to_greengas_industry_transformation_in_sankey),
      Q(kerosene_to_greengas_industry_transformation_in_sankey),
      Q(lpg_to_greengas_industry_transformation_in_sankey)
    )
