# Query for Sankey diagram: connection between oil and derivatives and oil and derivatives industry transformation

- unit = PJ
- query =
    SUM(
      Q(crude_oil_to_crude_oil_industry_transformation_in_sankey),
      Q(crude_oil_to_diesel_industry_transformation_in_sankey),
      Q(crude_oil_to_gasoline_industry_transformation_in_sankey),
      Q(crude_oil_to_heavy_fuel_oil_industry_transformation_in_sankey),
      Q(crude_oil_to_kerosene_industry_transformation_in_sankey),
      Q(crude_oil_to_lpg_industry_transformation_in_sankey),
      Q(crude_oil_to_naphtha_industry_transformation_in_sankey),
      Q(crude_oil_to_refinery_gas_industry_transformation_in_sankey)
    )
