# Query for Sankey diagram: connection between oil_and_derivatives and electricity

- unit = PJ
- query = DIVIDE(SUM(V(Q(electricity_producing_converters_sankey), primary_demand_of(crude_oil , gasoline , diesel , lpg , kerosene , heavy_fuel_oil))),BILLIONS)
