# Query for Sankey diagram: connection between oil_and_derivatives and chps

- query = DIVIDE(SUM(V(Q(heat_producing_converters_sankey), primary_demand_of(crude_oil , gasoline , diesel , lpg , kerosene , heavy_fuel_oil))),BILLIONS)
- unit = pj
