# Group for Sankey: p2g to hydrogen production
# p2g for bunkers goes directly to p2l node, so we filter on energy sector

- query =
    DIVIDE(V(INTERSECTION(Q(p2g_producing_converters_sankey), SECTOR(energy)), "output_of_hydrogen"), BILLIONS)
- unit = PJ
