# Group for Sankey: all p2l converters

- query =
    V(FILTER(G(cost_flexibility),"kerosene_output_conversion > 0.0"),
    bunkers_p2l_point_source_CO2,
    bunkers_p2l_point_source_CO,
    bunkers_p2l_direct_air_capture,
    bunkers_p2l_burner_network_gas
    )
- unit = converters
