# Group for Sankey: p2p to electricity production

- query =
    DIVIDE(SUM(V(Q(p2p_producing_converters_sankey), "input_of_electricity - demand * electricity_output_conversion")), BILLIONS)
- unit = MJ
