# Query for Sankey diagram: connection between solar and transport

- unit = MJ
- query = SUM(V(INTERSECTION(SECTOR(transport),G(final_demand_group)),"input_of_solar_radiation + input_of_solar_thermal"))
