# Query for Sankey diagram: connection between geo_solar_wind_water_ambient and bunkers

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(bunkers),G(final_demand_group)),"input_of_solar_radiation + input_of_solar_thermal")),BILLIONS)
