# Query for Sankey diagram: connection between steam_hot_water and biomass products industry transformation

- unit = PJ
- query = 
    SUM(
      Q(steam_hot_water_to_greengas_industry_transformation_in_sankey),
      Q(steam_hot_water_to_biodiesel_industry_transformation_in_sankey),
      Q(steam_hot_water_to_bio_kerosene_industry_transformation_in_sankey),
      Q(steam_hot_water_to_bio_oil_industry_transformation_in_sankey)
    )
