# Query for Sankey diagram: connection between greengas from steam_hot_water in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_biodiesel * steam_hot_water_input_conversion"
        )
      ),
      BILLIONS
    )
