# Query for Sankey diagram: connection between steam_hot_water and oil and oil products industry transformation

- unit = PJ
- query =
    SUM(
      Q(steam_hot_water_to_crude_oil_industry_transformation_in_sankey),
      Q(steam_hot_water_to_diesel_industry_transformation_in_sankey),
      Q(steam_hot_water_to_gasoline_industry_transformation_in_sankey),
      Q(steam_hot_water_to_heavy_fuel_oil_industry_transformation_in_sankey),
      Q(steam_hot_water_to_kerosene_industry_transformation_in_sankey),
      Q(steam_hot_water_to_lpg_industry_transformation_in_sankey),
      Q(steam_hot_water_to_naphtha_industry_transformation_in_sankey)
    )
