# Sum of electricity from non-chp e-producing converters in Sankey

- query = SUM(V(energy_power_hv_network_electricity, output_of_electricity),-V(energy_power_hv_network_loss, output_of_electricity))
- unit = pj
