# Sum of electricity into sectors including export

- query =
    SUM(
    V(G(final_demand_cbs),"input_of_electricity"),
    V(energy_export_electricity, primary_demand_of(Q(carrier_group_electricity)))
    )
- unit = pj
