# Sum of electricity into sectors including export

- unit = PJ
- query =
    SUM(
    V(G(final_demand_group),"input_of_electricity"),
    V(energy_export_electricity, primary_demand_of(Q(carrier_group_electricity)))
    )
