# Query for Sankey diagram: connection between useful_demand and electricity

- unit = pj

future:DIVIDE(SUM(V(Q(electricity_producing_converters), primary_demand_of(Q(carrier_group_useful_demand)))),BILLIONS)
		