# Query for Sankey diagram: connection between waste mix and industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          input_of_waste_mix
        )
      ),
      BILLIONS
    )
