# Query for Sankey diagram: connection between biomass products from waste_mix in industry transformation

- unit = PJ
- query = 
    SUM(
      Q(waste_mix_in_source_of_greengas_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_bio_oil_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_biodiesel_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_bio_kerosene_industry_transformation_in_sankey)
    )

