# Query for Sankey diagram: connection between oil and derivativs from waste_mix in industry transformation

- unit = PJ
- query =
    SUM(
      Q(waste_mix_in_source_of_crude_oil_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_diesel_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_gasoline_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_heavy_fuel_oil_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_kerosene_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_lpg_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_naphtha_industry_transformation_in_sankey),
      Q(waste_mix_in_source_of_refinery_gas_industry_transformation_in_sankey)
    )
