# Query for Sankey diagram: connection between lpg from waste_mix in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_lpg * waste_mix_input_conversion"
        )
      ),
      BILLIONS
    )
