# Query for Sankey diagram: connection between waste_mix and biomass products industry transformation

- unit = PJ
- query = 
    SUM(
      Q(waste_mix_to_greengas_industry_transformation_in_sankey),
      Q(waste_mix_to_biodiesel_industry_transformation_in_sankey),
      Q(waste_mix_to_bio_kerosene_industry_transformation_in_sankey),
      Q(waste_mix_to_bio_oil_industry_transformation_in_sankey)
    )
