# Query for Sankey diagram: connection between water and heat & CHPs

- unit = PJ
- query = DIVIDE(V(Q(central_heat_producing_converters_sankey).select {|node| node.input_slots.detect { |slot| slot.carrier.water? }}, primary_demand_of(electricity)),BILLIONS)
