# Query for Sankey diagram: connection between water and electricity

- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(Q(electricity_producing_converters_sankey).select {|node| node.input_slots.detect { |slot| slot.carrier.water? }}, primary_demand_of(electricity))
        ),
        BILLIONS
    )
