# Query for Sankey diagram: connection between wood_pellets and oil and derivatives products industry transformation

- unit = PJ
- query =
    SUM(
      Q(wood_pellets_to_crude_oil_industry_transformation_in_sankey),
      Q(wood_pellets_to_diesel_industry_transformation_in_sankey),
      Q(wood_pellets_to_gasoline_industry_transformation_in_sankey),
      Q(wood_pellets_to_heavy_fuel_oil_industry_transformation_in_sankey),
      Q(wood_pellets_to_kerosene_industry_transformation_in_sankey),
      Q(wood_pellets_to_lpg_industry_transformation_in_sankey)
    )
