# Query for Sankey diagram: connection between naphtha from wood_pellets in industry transformation

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_naphtha * wood_pellets_input_conversion"
        )
      ),
      BILLIONS
    )
