# Electricity production costs per MWh electricity is the same for CHP HT and MT
# For convenience, only the HT node is used to determine electricity production costs per MWh

- query = future:V(energy_chp_supercritical_ccs_ht_waste_mix,total_costs_per(:mwh_electricity))
- unit = euro
