# Electricity production costs per MWh electricity is the same for biomass CHP HT and MT
# For convenience, only the HT node is used to determine electricity production costs per MWh

- query = V(energy_chp_local_ht_wood_pellets_dispatchable,total_costs_per(:mwh_electricity))
- unit = euro
- deprecated_key = cost_chart_biomass_cost
