- deprecated_key = cost_chart_ccgt_investment
#

- unit = mln_euro

future:PRODUCT(SUM(V(energy_power_combined_cycle_gas_power_fuelmix,initial_investment_costs_per(:mw_electricity))),DIVIDE(1,MILLIONS))
