- deprecated_key = cost_chart_oxyfuel_investment
#

- unit = mln_euro

future:PRODUCT(SUM(V(energy_power_ultra_supercritical_oxyfuel_ccs_lignite,initial_investment_costs_per(mw_electricity))),DIVIDE(1,MILLIONS))
