- query = future:PRODUCT(SUM(V(energy_power_nuclear_gen2_uranium_oxide,total_investment_over_lifetime_per(:mw_electricity))),DIVIDE(1,MILLIONS))
- unit = mln_euro
- deprecated_key = cost_chart_nuclear_conv_investment
