- query = future:PRODUCT(SUM(V(energy_chp_ultra_supercritical_coal,total_investment_over_lifetime_per(:mw_electricity))),DIVIDE(1,MILLIONS))
- unit = mln_euro
- deprecated_key = cost_chart_coal_chp_investment
