# Final consumption from industry refineries, all carriers (energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_industry_refineries_energetic)
