- unit = PJ
- query =
      present:DIVIDE(
    V(G(energy_import),"output_of_natural_gas + output_of_network_gas + output_of_lng").sum - 
    V(G(energy_export),"input_of_natural_gas + input_of_network_gas + input_of_lng ").sum
      ,BILLIONS)
