# Capital costs of the ht heat delivery systems for households.
# The ht heat delivery system is assumed to have the same wacc as the ht heating network.

- unit = euro
- query =
    ht_heat_delivery_system_households_investment_costs = 
        SUM(
            Q(households_ht_heat_delivery_system_costs_ground_level_houses),
            Q(households_ht_heat_delivery_system_costs_apartments)
        );
    
    PRODUCT(
        DIVIDE(
        ht_heat_delivery_system_households_investment_costs,
        2
        ),
        V(energy_distribution_ht_steam_hot_water,wacc)
    )