# Capital costs of the mt heat delivery systems for households.
# The mt heat delivery system is assumed to have the same wacc as the mt heating network.

- unit = euro
- query =
    mt_heat_delivery_system_households_investment_costs = 
        SUM(
            Q(households_mt_heat_delivery_system_costs_ground_level_houses),
            Q(households_mt_heat_delivery_system_costs_apartments)
        );
    
    PRODUCT(
        DIVIDE(
        mt_heat_delivery_system_households_investment_costs,
        2
        ),
        V(energy_distribution_mt_steam_hot_water,wacc)
    )