# LULUCF removals should be handled as negative CO2 emissions

- unit = MT
- query =
    DIVIDE(
      SUM(
        EMISSIONS(emissions_sector, "LULUCF", co2, 1990),
        NEG(EMISSIONS(emissions_subsector, "Removals", co2, 1990))
      ),
      THOUSANDS
    )
