- unit = mt
- query =
    DIVIDE(
      SUM(
        EMISSIONS(other_indirect_emissions, non_energetic, co2, 1990),
        EMISSIONS(other_non_specified, energetic, co2, 1990),
        EMISSIONS(other_other_transportation, energetic, co2, 1990)
      ),
      THOUSANDS
    )
