# Demand of bio fuels from oily biomass

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(FILTER(
          G(final_demand_group),
          "input_of_bio_fuels > 0"),
        demand_of_bio_resources_including_abroad_of(oily_biomass))),
      BILLIONS
    )
