# Demand of export of oily biomass

- unit = PJ
- query = 
      DIVIDE(
        SUM(
          V(energy_export_oily_biomass, demand),
          V(energy_export_bio_oil_products, demand)
          ),
          BILLIONS
        )
