# Demand of export of biogenic waste

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(FILTER(
          G(energy_export),
          "input_of_bio_fuels > 0"),
        demand_of_bio_resources_including_abroad_of(biogenic_waste))),
      BILLIONS
    )