# Demand of export of biogenic waste

- unit = PJ
- query = 
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            biogenic_waste
          )
        )
      ),
      BILLIONS
    )
