# Industry transformation from biogenic waste

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          demand_of_bio_resources_including_abroad_of(biogenic_waste))),
      BILLIONS
    )
