# Industry transformation from wet biomass

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
        demand_of_bio_resources_including_abroad_of(wet_biomass))),
      BILLIONS
    )
