# Final consumption of gaseous biofuels in international transport - international aviation (energetic use only).
#
# Sector:      International transport - International aviation -- EG(bunkers_international_aviation)
# Carrier:     Gaseous biofuels
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of gaseous biofuels in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_gaseous_biofuels_in_bunkers_international_aviation_energetic)
