# Total CO2 emissions for 1990 incl. indirect emissions (indirecte emissies), land use
# (landgebruik), excl. international transport

- unit = MT
- query =
    SUM(
      Q(direct_emissions_klimaattafel_co2_incl_indirecte_emissies_landgebruik_internationaal_transport_1990),
      NEG(Q(direct_emissions_klimaattafel_internationaal_transport_co2_1990))
    )
