# This query serves to determine the share of heat produced from coal in the aggregated chemical industry

- unit = PJ
- query = (V(industry_chemicals_other_burner_coal,output_of_heat_carriers) + V(industry_chemicals_fertilizers_burner_coal,output_of_heat_carriers)) / (V(industry_useful_demand_for_chemical_other_useable_heat,preset_demand) + V(industry_useful_demand_for_chemical_fertilizers_useable_heat,preset_demand))