# 

- unit = #

SUM(
V(
households_space_heater_heatpump_ground_water_electricity,
households_water_heater_district_heating_steam_hot_water,
heatpump_using_city_heat_households_energetic,
households_water_heater_heatpump_air_water_electricity,
agriculture_heatpump_water_water_ts_electricity,
households_space_heater_collective_heatpump_water_water_ts_electricity
,number_of_units))
