- query =
    SUM(
    V(
    households_space_heater_heatpump_ground_water_electricity,
    households_water_heater_heatpump_air_water_electricity,
    households_water_heater_heatpump_ground_water_electricity,
    agriculture_heatpump_water_water_ts_electricity,
    households_space_heater_heatpump_air_water_electricity
    ,number_of_units))
- unit = #
