- deprecated_key = hot_water_share_condensing_gas_heater
# 

- unit = factor

V(households_water_heater_combined_network_gas,households_useful_demand_for_hot_water_after_insulation_and_solar_heater_and_add_on)
