- query =
    Q(share_of_heatpump_air_in_space_heating_production_in_households) +
    Q(share_of_heatpump_ground_in_space_heating_production_in_households) +
    Q(share_of_heatpump_pvt_in_space_heating_production_in_households)
- unit = factor
