- query = V(households_water_heater_district_heating_steam_hot_water_aggregator,share_of_households_useful_demand_for_hot_water_after_solar_heater_and_p2h)
- unit = factor
- deprecated_key = hot_water_share_heat_network
