# returns number of semi detached houses per building year

- unit = #
- query =
    SUM(
      Q(number_of_semi_detached_houses_1945_1964),
      Q(number_of_semi_detached_houses_1965_1974),
      Q(number_of_semi_detached_houses_1985_2004),
      Q(number_of_semi_detached_houses_2005_present),
      Q(number_of_semi_detached_houses_before_1945),
      Q(number_of_semi_detached_houses_future)
    )

