- query = 
    V(INTERSECTION(USE(energetic),G(final_demand_group)),"input_of_network_gas + input_of_hydrogen + input_of_lng + input_of_bio_lng").sum - Q(factsheet_energetic_final_demand_gas_households)

- unit = MJ