- query = 
    SUM(
        Q(factsheet_energetic_final_demand_bio_fuels),
        Q(factsheet_energetic_final_demand_coal_products),
        Q(factsheet_energetic_final_demand_collective_heat),
        Q(factsheet_energetic_final_demand_electricity),
        Q(factsheet_energetic_final_demand_gas_households),
        Q(factsheet_energetic_final_demand_gas_other),
        Q(factsheet_energetic_final_demand_oil_products),
        Q(factsheet_energetic_final_demand_renewable_heat)
    )

- unit = MJ