# Sum of heat production from backup burners HT, MT, LT
- query =
    SUM(
      Q(heat_production_from_backup_burner_ht_network_gas),
      Q(heat_production_from_backup_burner_mt_network_gas),
      Q(heat_production_from_backup_burner_lt_network_gas)
    )
- unit = MJ
