# Assuming linear depreciation, in line with ETM cost calculation

- query =
    DIVIDE(
      Q(heat_infrastructure_mt_distribution_stations_investment_costs),
      Q(heat_infrastructure_mt_distribution_stations_technical_lifetime)
      )
- unit = euro
