
# Returns the capacity of solar pv in the households sector.
- query = 
        PRODUCT(
  		V(households_solar_pv_solar_radiation,number_of_units),
  		V(households_solar_pv_solar_radiation,electricity_output_capacity)	
  		)
- unit = MW


