- deprecated_key = chart_medium_voltage_network_60_annual_cost_of_infrastructure_551
# Q(yearly_investment_costs_of_mv_grid) returns costs in millions, here we convert to base units

- unit = euro

Q(yearly_investment_costs_of_mv_grid)
