- query =
    SUM(
    DIVIDE(
      SUM(
        V(
          G(hydrogen_production),
          input_of(
            torrefied_biomass_pellets,
            wood_pellets,
            bio_oil
          )
        )
      ),
      BILLIONS
    ),
    Q(gas_power_fuelmix_for_hydrogen_conversion) * V(energy_mixer_for_gas_power_fuel, bio_oil_input_conversion)
    )
- unit = PJ
