# Direct conversion output of hydrogen from hydrogen production through biomass gasification with CCS

- query =
    DIVIDE(
      V(
        energy_hydrogen_biomass_gasification_ccs,
        output_of_hydrogen
      ),
      BILLIONS
    )
- unit = PJ
