# Direct conversion input of biomass products for biomass gasification without CCS


- query =
    DIVIDE(
      V(
        energy_hydrogen_biomass_gasification,
        input_of_torrefied_biomass_pellets
      ),
      BILLIONS
    )+ Q(greengas_for_biomass_gasification_conversion)
- unit = PJ
