# Direct conversion output of hydrogen from hydrogen production through SMR without CCS

- query =
    DIVIDE(
      V(
        energy_hydrogen_steam_methane_reformer,
        output_of_hydrogen
      ),
      BILLIONS
    )
- unit = PJ
