# Special conversion for heat to biomass_products

- query = 
    SUM(
      Q(conversion_from_steam_hot_water_to_biomass_products),
      Q(conversion_from_ambient_heat_to_biomass_products),
      Q(conversion_from_residual_heat_to_biomass_products)
    )
- unit = PJ
