# Direct conversion input of heavy fuel oil for central electricity production

- query =
    DIVIDE(
      SUM(
        V(
          G(greengas_production),
          "greengas_output_conversion +  wood_pellets_output_conversion + biodiesel_output_conversion + bio_ethanol_output_conversion + bio_lng_output_conversion / (1 - loss_output_conversion) * input_of_heavy_fuel_oil"
        )
      ), 
      BILLIONS
    )
- unit = PJ
