# Direct conversion input of torrefied_biomass_pellets for biomass products production

- query = 
    DIVIDE(
      SUM(
        V(
          G(biomass_products_production),
          "greengas_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_torrefied_biomass_pellets"
        ),
        V(
          G(biomass_products_production),
          "wood_pellets_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_torrefied_biomass_pellets"
        ),
        V(
          G(biomass_products_production),
          "biodiesel_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_torrefied_biomass_pellets"
        ),
        V(
          G(biomass_products_production),
          "bio_ethanol_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_torrefied_biomass_pellets"
        ),
        V(
          G(biomass_products_production),
          "bio_lng_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_torrefied_biomass_pellets"
        )
      ), 
      BILLIONS
    )
- unit = PJ