# Direct conversion input of wood_pellets for biomass_products
# The function is broken down due to limited allowed inputs in V() function

- query =
    DIVIDE(
      SUM(
        V(
          G(biomass_products_production),
          "greengas_output_conversion / (1 - loss_output_conversion) * input_of_wood_pellets"
        ),
        V(
          G(biomass_products_production),
          "wood_pellets_output_conversion / (1 - loss_output_conversion) * input_of_wood_pellets"
        ),
        V(
          G(biomass_products_production),
          "torrefied_biomass_pellets_output_conversion / (1 - loss_output_conversion) * input_of_wood_pellets"
        ),
        V(
          G(biomass_products_production),
          "biodiesel_output_conversion / (1 - loss_output_conversion) * input_of_wood_pellets"
        ),
        V(
          G(biomass_products_production),
          "bio_ethanol_output_conversion / (1 - loss_output_conversion) * input_of_wood_pellets"
        ),
        V(
          G(biomass_products_production),
          "bio_lng_output_conversion / (1 - loss_output_conversion) * input_of_wood_pellets"
        ),
        V(
          G(biomass_products_production),
          "bio_kerosene_output_conversion / (1 - loss_output_conversion) * input_of_wood_pellets"
        ),
        V(
          G(biomass_products_production),
          "bio_oil_output_conversion / (1 - loss_output_conversion) * input_of_wood_pellets"
        )
      ),
      BILLIONS
    )
- unit = PJ
