# Final consumption of heat in industry refineries (non-energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_heat_in_industry_refineries_non_energetic)
