# Final consumption of heat in national transport (non-energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_heat_in_national_transport_non_energetic)
