# The average cost per MJ electricity produced by oil plants, given in euro per MJ. This value can be used to determine the attribute of foreign_oil_electricity if exported or imported.

- unit = euro

DIVIDE(
   SUM(V(Q(electricity_producing_converters_oil);total_costs)),
   SUM(V(Q(electricity_producing_converters_oil);output_of_electricity))
)