# The average cost per MJ electricity produced by waste plants, given in euro per MJ. This value can be used to determine the attribute of foreign_waste_electricity if exported or imported.

- unit = euro

DIVIDE(
   SUM(V(Q(electricity_producing_converters_waste);total_costs)),
   SUM(V(Q(electricity_producing_converters_waste);output_of_electricity))
)