# The average cost per MJ electricity produced by nuclear plants, given in euro per MJ. This value can be used to determine the attribute of foreign_nuclear_electricity if exported or imported.

- unit = euro

DIVIDE(
   SUM(V(Q(electricity_producing_converters_uranium);total_costs)),
   SUM(V(Q(electricity_producing_converters_uranium);output_of_electricity))
)
