- query = 
    DIVIDE(
      PRODUCT(
        Q(land_use_solar_wind_wind_inland_large_electricity_output),
        THOUSANDS
      ),
      Q(land_use_solar_wind_wind_inland_large_full_load_hours)
    )
- unit = MW