- query =  
    DIVIDE(
      Q(land_use_solar_wind_wind_inland_large_installed_capacity),
      DIVIDE(
        Q(land_use_solar_wind_wind_inland_large_capacity_per_unit),
        THOUSANDS
      )
    )
- unit = number