# Extraction of oil and derivatives

- query =
    DIVIDE(
      SUM(
        V(
          G(mining_and_extraction),
          output_of(
            crude_oil
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
