# Extraction of natural gas

- query =
    DIVIDE(
      SUM(
        V(
          G(mining_and_extraction),
          output_of(
            natural_gas
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
