# Final demand of electricity from solar
# The final demand of renewable electricity is multiplied with the share of
# solar in the total renewable electricity produced. In this way electricity
# network losses are not included.

- unit = MJ
- query =
    PRODUCT(
        Q(final_demand_of_renewable_electricity),
        DIVIDE(
            Q(electricity_produced_from_solar),
            Q(total_renewable_electricity_produced)
        )
    )
