# Final demand of heat from biomass products
# The final demand of heat is multiplied with the share of heat from biomass in the total heat produced for heat networks.
# In this way network losses are not included.

- unit = MJ
- query =
    SUM(
        Q(final_demand_of_renewable_heat),
        NEG(Q(final_demand_of_renewable_heat_from_geothermal_and_ambient))
    )
