# Final demand of all renewables

- unit = MJ
- query =
    SUM(
        Q(final_demand_of_renewable_electricity),
        Q(final_demand_of_renewable_heat),
        Q(final_demand_of_renewable_hydrogen),
        Q(final_demand_of_green_gas),
        Q(final_demand_of_liquid_biofuels),
        Q(final_demand_of_solid_biofuels)
    )
