- query = 
		SUM(
			Q(sankey_0_to_1_crude_oil_to_oil_and_oil_products),
			Q(sankey_0_to_1_imported_oil_and_oil_products_to_oil_and_oil_products),
			Q(sankey_1_to_1_electricity_to_oil_and_oil_products),
			Q(sankey_1_to_1_hydrogen_to_oil_and_oil_products)
		)