- query = 
		SUM(
			Q(sankey_1_to_1_methanol_to_hydrogen),
			Q(sankey_1_to_1_methanol_to_oil_and_oil_products),
			Q(sankey_1_to_1_methanol_to_network_gas),
			Q(sankey_1_to_1_methanol_to_ammonia),
			Q(sankey_1_to_0_methanol_to_biomass_products),
			Q(sankey_1_to_0_methanol_to_natural_gas),
			Q(sankey_1_to_2_methanol_to_feedstock),
			Q(sankey_1_to_2_methanol_to_export),
			Q(sankey_1_to_2_methanol_to_loss)
		)