- query = 
		SUM(
			Q(sankey_0_to_0_biomass_products_to_natural_gas),
			Q(sankey_0_to_1_biomass_products_to_electricity),
			Q(sankey_0_to_1_biomass_products_to_heat),
			Q(sankey_0_to_1_biomass_products_to_hydrogen),
			Q(sankey_0_to_1_biomass_products_to_oil_and_oil_products),
			Q(sankey_0_to_1_biomass_products_to_waste_mix),
			Q(sankey_0_to_1_biomass_products_to_methanol),
			Q(sankey_0_to_1_biomass_products_to_network_gas),
			Q(sankey_0_to_1_biomass_products_to_ammonia),
			Q(sankey_0_to_2_biomass_products_to_agriculture),
			Q(sankey_0_to_2_biomass_products_to_households),
			Q(sankey_0_to_2_biomass_products_to_buildings),
			Q(sankey_0_to_2_biomass_products_to_transport),
			Q(sankey_0_to_2_biomass_products_to_industry),
			Q(sankey_0_to_2_biomass_products_to_energy),
			Q(sankey_0_to_2_biomass_products_to_other),
			Q(sankey_0_to_2_biomass_products_to_bunkers),
			Q(sankey_0_to_2_biomass_products_to_feedstock),
			Q(sankey_0_to_2_biomass_products_to_export),
			Q(sankey_0_to_2_biomass_products_to_loss)
		)