- query = 
		SUM(
			Q(sankey_0_to_1_imported_ammonia_to_ammonia),
			Q(sankey_0_to_1_biomass_products_to_ammonia),
			Q(sankey_0_to_1_natural_gas_to_ammonia),
			Q(sankey_0_to_1_not_defined_to_ammonia),
			Q(sankey_1_to_1_electricity_to_ammonia),
			Q(sankey_1_to_1_heat_to_ammonia),
			Q(sankey_1_to_1_hydrogen_to_ammonia),
			Q(sankey_1_to_1_oil_and_oil_products_to_ammonia),
			Q(sankey_1_to_1_waste_mix_to_ammonia),
			Q(sankey_1_to_1_methanol_to_ammonia)
		)