- query = 
		SUM(
			Q(sankey_1_to_1_electricity_to_heat),
			Q(sankey_1_to_1_electricity_to_hydrogen),
			Q(sankey_1_to_1_electricity_to_oil_and_oil_products),
			Q(sankey_1_to_2_electricity_to_agriculture),
			Q(sankey_1_to_2_electricity_to_households),
			Q(sankey_1_to_2_electricity_to_buildings),
			Q(sankey_1_to_2_electricity_to_transport),
			Q(sankey_1_to_2_electricity_to_industry),
			Q(sankey_1_to_2_electricity_to_energy),
			Q(sankey_1_to_2_electricity_to_other),
			Q(sankey_1_to_2_electricity_to_bunkers),
			Q(sankey_1_to_2_electricity_to_feedstock),
			Q(sankey_1_to_2_electricity_to_export),
			Q(sankey_1_to_2_electricity_to_loss)
		)