- query = 
		SUM(
			Q(sankey_0_to_1_hydro_electricity_to_electricity),
			Q(sankey_0_to_1_imported_electricity_to_electricity),
			Q(sankey_0_to_1_solar_electricity_to_electricity),
			Q(sankey_0_to_1_wind_electricity_to_electricity),
			Q(sankey_0_to_1_uranium_to_electricity),
			Q(sankey_0_to_1_biomass_products_to_electricity),
			Q(sankey_0_to_1_coal_and_coal_products_to_electricity),
			Q(sankey_0_to_1_natural_gas_to_electricity),
			Q(sankey_0_to_1_geothermal_to_electricity),
			Q(sankey_1_to_1_hydrogen_to_electricity),
			Q(sankey_1_to_1_oil_and_oil_products_to_electricity)
		)