- query = 
		SUM(
			Q(sankey_0_to_1_imported_methanol_to_methanol),
			Q(sankey_0_to_1_biomass_products_to_methanol),
			Q(sankey_0_to_1_natural_gas_to_methanol),
			Q(sankey_0_to_1_not_defined_to_methanol),
			Q(sankey_1_to_1_electricity_to_methanol),
			Q(sankey_1_to_1_heat_to_methanol),
			Q(sankey_1_to_1_hydrogen_to_methanol),
			Q(sankey_1_to_1_oil_and_oil_products_to_methanol),
			Q(sankey_1_to_1_waste_mix_to_methanol),
			Q(sankey_1_to_1_ammonia_to_methanol),
			Q(sankey_1_to_1_network_gas_to_methanol)
		)