- query = 
		SUM(
			Q(sankey_1_to_1_oil_and_oil_products_to_electricity),
			Q(sankey_1_to_1_oil_and_oil_products_to_hydrogen),
			Q(sankey_1_to_2_oil_and_oil_products_to_agriculture),
			Q(sankey_1_to_2_oil_and_oil_products_to_households),
			Q(sankey_1_to_2_oil_and_oil_products_to_buildings),
			Q(sankey_1_to_2_oil_and_oil_products_to_transport),
			Q(sankey_1_to_2_oil_and_oil_products_to_industry),
			Q(sankey_1_to_2_oil_and_oil_products_to_energy),
			Q(sankey_1_to_2_oil_and_oil_products_to_other),
			Q(sankey_1_to_2_oil_and_oil_products_to_bunkers),
			Q(sankey_1_to_2_oil_and_oil_products_to_feedstock),
			Q(sankey_1_to_2_oil_and_oil_products_to_export),
			Q(sankey_1_to_2_oil_and_oil_products_to_loss)
		)