- query = 
		SUM(
			Q(sankey_0_to_0_natural_gas_to_biomass_products),
			Q(sankey_0_to_0_not_defined_to_biomass_products),
			Q(sankey_1_to_0_electricity_to_biomass_products),
			Q(sankey_1_to_0_heat_to_biomass_products),
			Q(sankey_1_to_0_hydrogen_to_biomass_products),
			Q(sankey_1_to_0_oil_and_oil_products_to_biomass_products),
			Q(sankey_1_to_0_waste_mix_to_biomass_products),
			Q(sankey_1_to_0_methanol_to_biomass_products),
			Q(sankey_1_to_0_ammonia_to_biomass_products)
		)