- query = 
		SUM(
			Q(sankey_1_to_2_heat_to_agriculture),
			Q(sankey_1_to_2_heat_to_households),
			Q(sankey_1_to_2_heat_to_buildings),
			Q(sankey_1_to_2_heat_to_transport),
			Q(sankey_1_to_2_heat_to_industry),
			Q(sankey_1_to_2_heat_to_energy),
			Q(sankey_1_to_2_heat_to_other),
			Q(sankey_1_to_2_heat_to_bunkers),
			Q(sankey_1_to_2_heat_to_feedstock),
			Q(sankey_1_to_2_heat_to_loss)
		)