- query = 
		SUM(
			Q(sankey_0_to_0_biomass_products_to_natural_gas),
			Q(sankey_0_to_0_not_defined_to_natural_gas),
			Q(sankey_1_to_0_electricity_to_natural_gas),
			Q(sankey_1_to_0_heat_to_natural_gas),
			Q(sankey_1_to_0_hydrogen_to_natural_gas),
			Q(sankey_1_to_0_oil_and_oil_products_to_natural_gas),
			Q(sankey_1_to_0_waste_mix_to_natural_gas),
			Q(sankey_1_to_0_methanol_to_natural_gas),
			Q(sankey_1_to_0_ammonia_to_natural_gas)
		)