- query = 
		SUM(
			Q(sankey_0_to_1_biomass_products_to_heat),
			Q(sankey_0_to_1_natural_gas_to_heat),
			Q(sankey_0_to_1_coal_and_coal_products_to_heat),
			Q(sankey_0_to_1_solar_thermal_to_heat),
			Q(sankey_0_to_1_uranium_to_heat),
			Q(sankey_0_to_1_ambient_heat_to_heat),
			Q(sankey_0_to_1_residual_heat_to_heat),
			Q(sankey_0_to_1_imported_heat_to_heat),
			Q(sankey_0_to_1_geothermal_to_heat),
			Q(sankey_1_to_1_electricity_to_heat),
			Q(sankey_1_to_1_hydrogen_to_heat)
		)