- query = 
		SUM(
			Q(sankey_0_to_0_natural_gas_to_biomass_products),
			Q(sankey_0_to_1_natural_gas_to_hydrogen),
			Q(sankey_0_to_1_natural_gas_to_oil_and_oil_products),
			Q(sankey_0_to_1_natural_gas_to_methanol),
			Q(sankey_0_to_1_natural_gas_to_network_gas),
			Q(sankey_0_to_1_natural_gas_to_ammonia),
			Q(sankey_0_to_2_natural_gas_to_export),
			Q(sankey_0_to_2_natural_gas_to_loss)
		)