- query = 
		SUM(
			Q(sankey_1_to_1_ammonia_to_hydrogen),
			Q(sankey_1_to_1_ammonia_to_oil_and_oil_products),
			Q(sankey_1_to_1_ammonia_to_methanol),
			Q(sankey_1_to_1_ammonia_to_network_gas),
			Q(sankey_1_to_0_ammonia_to_biomass_products),
			Q(sankey_1_to_0_ammonia_to_natural_gas),
			Q(sankey_1_to_2_ammonia_to_agriculture),
			Q(sankey_1_to_2_ammonia_to_households),
			Q(sankey_1_to_2_ammonia_to_buildings),
			Q(sankey_1_to_2_ammonia_to_transport),
			Q(sankey_1_to_2_ammonia_to_industry),
			Q(sankey_1_to_2_ammonia_to_energy),
			Q(sankey_1_to_2_ammonia_to_other),
			Q(sankey_1_to_2_ammonia_to_bunkers),
			Q(sankey_1_to_2_ammonia_to_feedstock),
			Q(sankey_1_to_2_ammonia_to_export),
			Q(sankey_1_to_2_ammonia_to_loss)
		)