# Direct conversion input of electricity for hydrogen production through SMR with CCS

- query =
    DIVIDE(
      V(
        energy_hydrogen_steam_methane_reformer_ccs_must_run,
        energy_hydrogen_steam_methane_reformer_ccs_dispatchable,
        input_of_electricity
      ),
      BILLIONS
    )
- unit = PJ
