# Query for scenario tools regional overview: direct conversion demand of electricity for synthetic kerosene production

- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            Q(synthetic_fuels_from_hydrogen_converters),
            "kerosene_output_conversion > 0"
          )
        input_of_electricity        
        )
      ),
      BILLIONS
    )
- unit = PJ
