# Query for scenario tools regional overview: direct conversion demand of electricity for synthetic kerosene production

- query =
    DIVIDE(
      V(energy_production_synthetic_kerosene, input_of_electricity),
      BILLIONS
    )
- unit = PJ
