# Query for scenario tools regional overview: direct conversion demand of green gas for electricity production

- query =
    Q(network_gas_for_electricity_conversion) * Q(share_of_renewable_gas_in_gas_network)
- unit = PJ
