# Query for scenario tools regional overview: direct conversion demand of oil for electricity production

- query =
    SUM(
    DIVIDE(
      SUM(
        V(
          Q(electricity_producing_converters_sankey),
          input_of(
            crude_oil,
            diesel
          )
        )
      ),
      BILLIONS
    ),
    Q(gas_power_fuelmix_for_electricity_conversion) * V(energy_mixer_for_gas_power_fuel, crude_oil_input_conversion)
    )
- unit = PJ
