# 

- deprecated_key = chart_fuel_trucks_b_23_final_energy_demand_205
- unit = pj

DIVIDE(SUM(V(V(transport_truck_using_compressed_natural_gas),V(transport_truck_using_diesel_mix),V(transport_truck_using_gasoline_mix),V(lpg_trucks_transport_energetic),final_demand)),BILLIONS)
