# Returns the capacity of wood pellets chp mt local engine's for the sector energy.
- query = 
        PRODUCT(
  		V(energy_chp_local_engine_mt_wood_pellets,number_of_units),
  		V(energy_chp_local_engine_mt_wood_pellets,electricity_output_capacity)	
  		)
- unit = MW

