# This used to be a stored policy. Now it makes use of the new MIXED function
# It's used by the energy imports goal chart
# stored:policy_net_energy_import

- query = MIXED(Q(net_import_of_energy),Q(policy_goal_net_energy_import_target_value))
- unit = factor
