- query =
    DIVIDE(
    	MAX(
    		SUM(
    			V(agriculture_final_demand_electricity,demand),
    			NEG(
    				V(agriculture_chp_engine_network_gas,output_of_electricity)
    			),
    			NEG(	
    				V(agriculture_chp_engine_biogas,output_of_electricity)
    			),
    			NEG(	
    				V(agriculture_chp_supercritical_wood_pellets,output_of_electricity)
    			)
    		),
    		0
    	),
    	BILLIONS
    )
- unit = pj
