- unit = PJ
- query =
    MAX(
      SUM(
        V(agriculture_final_demand_electricity,demand) / BILLIONS,
        - Q(chp_electricity_in_source_of_heat_and_electricity_in_agriculture)
      ),
      0
    )
