- query =
    DIVIDE(
      V(agriculture_chp_engine_network_gas, 
        agriculture_chp_engine_biogas,
        agriculture_chp_supercritical_wood_pellets,
        output_of_electricity).sum, 
      BILLIONS
    )
- unit = pj
