- query =
    DIVIDE(
        MAX(
            SUM(
                V(agriculture_useful_demand_useable_heat,demand),
                NEG(
                    V(agriculture_chp_engine_network_gas,output_of_heat_carriers)
                ),
                NEG(
                    V(agriculture_chp_engine_biogas,output_of_heat_carriers)
                ),    
                NEG(
                    V(agriculture_chp_supercritical_wood_pellets,output_of_heat_carriers)
                ),
            ),
            0
        ),
        BILLIONS
    )
- unit = pj
