# Returns the capacity of biogas chp's for the sector agriculture.
- query = 
        PRODUCT(
  		V(agriculture_chp_engine_biogas,number_of_units),
  		V(agriculture_chp_engine_biogas,electricity_output_capacity)	
  		)
- unit = MW

