- query =
    DIVIDE(
      V(energy_distribution_hydrogen_before_transport, demand) - V(energy_export_hydrogen_backup, demand) - V(energy_export_hydrogen_baseload, demand),
      Q(factsheet_supply_of_gas_total)
      ) * 100
- unit = %
