# Output of steam_hot_water from energy_chp_local_engine_ht_network_gas

- query =
    DIVIDE(
      V(energy_chp_local_engine_ht_network_gas, output_of_steam_hot_water),
      BILLIONS
    )
- unit = PJ
