- unit = mt
- query =
    DIVIDE(
      SUM(
        V(
          G(emissions_bunkers),
          direct_reporting_emissions_total_ghg_emissions
        ),
        MV(
          MG(emissions_bunkers),
          direct_reporting_emissions_total_ghg_emissions
        )
      ),
      BILLIONS
    )
