# Returns the capacity of batteries for solar electricity for the sector energy.
- query = 
        PRODUCT(
  		V(energy_battery_solar_electricity,number_of_units),
  		V(energy_battery_solar_electricity,electricity_output_capacity)	
  		)
- unit = MW
