- unit = MT
- query =
    DIVIDE(
      SUM(
        V(
          SECTOR(klimaattafel, "Gebouwde omgeving"),
          direct_reporting_emissions_other_ghg_emissions
        ),
        MV(
          MSECTOR(klimaattafel, "Gebouwde omgeving"),
          direct_reporting_emissions_other_ghg_emissions
        )
      ),
      BILLIONS
    )
