- query = 
		SUM(
			Q(diesel_refinery_to_distribution_in_sankey),
			Q(gasoline_refinery_to_distribution_in_sankey),
			Q(lpg_refinery_to_distribution_in_sankey),
			Q(hfo_refinery_to_distribution_in_sankey),
			Q(kerosene_refinery_to_distribution_in_sankey),
			Q(oil_products_refinery_to_distribution_in_sankey),
			Q(refinery_gas_refinery_to_distribution_in_sankey),
			Q(refinery_loss_in_sankey)
		)