- query = 
		SUM(
			Q(diesel_distribution_to_households_in_sankey),
			Q(diesel_distribution_to_buildings_in_sankey),
			Q(diesel_distribution_to_agriculture_in_sankey),
			Q(diesel_distribution_to_industry_in_sankey),
			Q(diesel_distribution_to_transport_in_sankey),
			Q(diesel_distribution_to_energy_in_sankey),
			Q(diesel_distribution_to_export_in_sankey)
		)