# Only households require 'additional' secondary distribution pipelines
# These are pipelines from street level to the front door

- query =
    AREA(heat_yearly_outdoor_infrastructure_maintenance_costs_factor) * Q(heat_infrastructure_mt_connection_pipelines_investment_costs)
- unit = euro