# Final demand of electricity in trams and metros, based on final demand for rail and share to trams
# and metros

- query =
    PRODUCT(
      V(transport_final_demand_for_rail_electricity, demand),
      V(EDGE(transport_final_demand_for_rail_electricity, transport_tram_using_electricity), parent_share)
    )
- unit = MJ
