# Share of households in total electricity demand of households, industry and transport

- unit = factor
- query =
    DIVIDE(
      V(households_final_demand_electricity, demand),
      Q(dbdm_electricity_demand_for_households_transport_industry)
    )
