# Total final electricity demand of households, industry and transport

- unit = MJ
- query =
    SUM(
      V(households_final_demand_electricity, demand),
      V(transport_final_demand_electricity, demand),
      V(industry_final_demand_electricity, demand)
    )
