# Progress share of households; when the progress share of transport is greater
# than 1 (meaning that the progress bar of this sector is filled), the
# electricity "excess" is used to fill the households progress bar.

- unit = factor
- query =
    DIVIDE(
      IF(
        Q(dbdm_progress_share_of_transport) > 1.0,
        SUM(
          Q(dbdm_electricity_supply_for_households),
          PRODUCT(
            Q(dbdm_progress_share_of_transport) - 1,
            V(transport_final_demand_electricity, demand)
          )
        ),
        Q(dbdm_electricity_supply_for_households)
      ),
      V(households_final_demand_electricity, demand)
    )
