# Progress share of industry; when the progress share of households is greater
# than 1 (meaning that the progress bar of this sector is filled), the
# electricity "excess" is used to fill the industry progress bar.

- unit = factor
- query =
    DIVIDE(
      IF(
        Q(dbdm_progress_share_of_households) > 1.0,
        SUM(
          Q(dbdm_electricity_supply_for_industry),
          PRODUCT(
            Q(dbdm_progress_share_of_households) - 1,
            V(households_final_demand_electricity, demand)
          )
        ),
        Q(dbdm_electricity_supply_for_industry)
      ),
      V(industry_final_demand_electricity, demand)
    )
