# Share of electricity supply by wind and solar for households

- unit = factor
- query =
    DIVIDE(
      V(households_final_demand_electricity, demand),
      Q(dbdm_total_electricity_demand)
    )
