# Share of electricity supply by wind and solar for industry

- unit = factor
- query =
    SUM(
      1,
      NEG(Q(dbdm_share_of_electricity_supply_for_households)),
      NEG(Q(dbdm_share_of_electricity_supply_for_transport))
    )
