# Divides the electricity output of solar parks and wind turbines among the different sectors
# defined by the Daar Bij Die Molen (DBDM) project: households, transport and industry.

# Returns the following array:
# [ electricity supply for households, electricity supply for transport, electricity supply for industry ]

- unit = MJ
- query =
    [
      Q(dbdm_households_share),
      Q(dbdm_transport_share),
      Q(dbdm_industry_share),
    ].map{ |x| x * Q(dbdm_electricity_supply_by_wind_and_solar) }
