# Progress shares for households, transport and industry:
# To what extent does the electricity supply (by wind and solar) meet the
# electricity demand of each of the sectors?

- unit = factor
- query =
    [
      MIN(1, Q(dbdm_progress_share_of_households)),
      MIN(1, Q(dbdm_progress_share_of_transport)),
      MIN(1, Q(dbdm_progress_share_of_industry))
    ].map{ |x| x * 1 }
