# Final consumption from energy, all carriers (energetic use only).
#
# Sector:      Energy -- sector == :energy
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_energy_energetic)
