# Assuming linear depreciation, in line with ETM cost calculation

- query =
    DIVIDE(
      Q(heat_infrastructure_lt_distribution_pipelines_investment_costs),
      Q(heat_infrastructure_lt_distribution_pipelines_technical_lifetime)
      )
- unit = euro
