# This query retrieves the technical lifetime used in calculating the depreciation costs. The query is used in the ETM costs export.

- query =
    V(energy_distribution_lt_steam_hot_water, technical_lifetime)
- unit = year
