- query =
    residences_with_district_heating = Q(number_of_residences) * DIVIDE(INPUT_VALUE(households_heater_district_heating_lt_steam_hot_water_share),100.0);
    buildings_with_district_heating = Q(number_of_buildings) * DIVIDE(INPUT_VALUE(buildings_space_heater_district_heating_lt_steam_hot_water_share),100.0);
    total_number_of_residence_objects_with_district_heating = residences_with_district_heating + buildings_with_district_heating;

    total_number_of_residence_objects_with_district_heating * Q(heat_length_of_distribution_pipelines_in_meter_per_residence_object) * AREA(heat_lt_distribution_pipelines_investment_costs_eur_per_meter)
- unit = euro
