# Total cost of all carbon capture, carbon sequestration and carbon utilisation technologies in the energy GRAPH

- query =
        SUM(
        V(G(costs_building_and_installations), capital_expenditures_ccs_per(:node)),
        V(G(costs_building_and_installations), operating_expenses_ccs_per(:node)),
        V(G(costs_storage_and_conversion), capital_expenditures_ccs_per(:node)),
        V(G(costs_storage_and_conversion), operating_expenses_ccs_per(:node)),
        V(G(costs_production), capital_expenditures_ccs_per(:node)),
        V(G(costs_production), operating_expenses_ccs_per(:node))
        )

- unit = euro
