# Total cost of all carbon capture, carbon sequestration and carbon utilisation technologies

- query =
    SUM(
      Q(costs_co2_energy_graph_ccus),
      Q(costs_molecule_graph)
    )
- unit = euro
