# Total cost of all carbon capture, carbon sequestration and carbon utilisation technologies in the molecule graph

- query =
    SUM(
      V(MG(costs_co2_ccus), capital_expenditures_excluding_ccs_per(:node)),
      V(MG(costs_co2_ccus), operating_expenses_excluding_ccs_per(:node))
    )
- unit = euro
