# Total cost of all carbon capture, carbon sequestration and carbon utilisation technologies in the molecule graph

- query =
        SUM(
        V(MG(cost_ccus), capital_expenditures_excluding_ccs_per(:node)),
        V(MG(cost_ccus), operating_expenses_excluding_ccs_per(:node))
        )

- unit = euro
