# Sum of all carbon output flows (column: 2) in the CCUS sankey

- unit = MT
- query =
    SUM(
      Q(captured_co2_offshore_sequestration_total_in_ccus_sankey),
      Q(captured_co2_synthetic_methanol_total_in_ccus_sankey),
      Q(captured_co2_synthetic_kerosene_total_in_ccus_sankey),
      Q(captured_co2_other_utilisation_total_in_ccus_sankey),
      Q(captured_co2_export_total_in_ccus_sankey)
    )
