# Final consumption of liquid biofuels in international transport - international navigation (energetic use only).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Liquid biofuels -- biodiesel? || bio_ethanol? || bio_kerosene? || bio_oil? || bionaphtha? || biomethanol? || bio_pyrolysis_oil? || oily_biomass?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_liquid_biofuels_in_bunkers_international_navigation_energetic)
