# 

- deprecated_key = demand_plants_connected_to_mv_distribution_net
- unit = converters

V(
  heat_pump_with_CHS_agri_agriculture_energetic,
  heat_pump_with_chs_households_energetic,
  heatpump_ts_cooling_households_energetic,
  heatpump_ts_buildings_energetic,
  heatpump_ts_cooling_buildings_energetic,
  airco_buildings_energetic,
  electric_heater_buildings_energetic
)