- deprecated_key = pl_lv_net_delta_capacity_we
# 

- unit = mw

SUM(
  Q(peak_load_delta_we_electric_cars),
  Q(peak_load_delta_we_electric_trucks),
  Q(peak_load_delta_hh_heaters),
  Q(peak_load_delta_electric_boiler)
)