- deprecated_key = pl_lv_net_delta_capacity_supply
# This is the peak load on transformer level based on the household technologies that produce electricity

- unit = mw

SUM(
  Q(peak_load_delta_hh_micro_chp),
  Q(peak_load_delta_local_solar_pv_grid_connected)
)