- deprecated_key = number_of_electric_cars
# 

- unit = #

DIVIDE(
  PRODUCT(
    VALUE( cars_kms_demand_transport_energetic; demand ),
    VALUE( electric_cars_transport_energetic ; car_kms_output_link_share )
  ),
  AREA( km_per_car )
)