
# 

- unit = #

DIVIDE(
  PRODUCT(
    VALUE( truck_kms_demand_transport_energetic; demand ),
    VALUE( electric_trucks_transport_energetic ; truck_kms_output_link_share )
  ),
  AREA(km_per_truck)
)