# 109718/1000000 is the current share of electric boilers. It is entered like this since decimals apparently can't be entered in the query.

- unit = mw

PRODUCT(
  SUM(
PRODUCT(  
    SUM(
      V(electric_boiler_households_energetic;
        simult_we*
        electricity_input_conversion*
        typical_input_capacity_in_mw*
        share_of_hot_water_devices_households_energetic
       )
     ),
     V(hot_water_devices_households_energetic;share_of_hot_water_demand_households_energetic)
    ),
    NEG(
      V(electric_boiler_households_energetic;
        simult_we*
        electricity_input_conversion*
        typical_input_capacity_in_mw*
        109718/1000000)
    )
  ),
  AREA(number_households)
)