# OLD query:
# 
# PRODUCT (
#    
#                    Q(peak_load_per_unit_hh_micro_chp),
#     
#                    Q(peak_load_units_delta_hh_micro_chp)
# )

- deprecated_key = peak_load_delta_hh_micro_chp
- unit = mw

PRODUCT(
    V(micro_CHP_production_households;simult_we* 1/1000 * share_of_heating_demand_households_energetic),
    AREA(number_households)
)