
# No simultaneousness considered for local solar pv grid connected.
# Typical gross capacity of local solar pv is equal to the peak load per unit.

- unit = mw

PRODUCT (
   
                    V (local_solar_pv_grid_connected_energy_energetic; typical_input_capacity_in_mw),
    
                   Q(peak_load_units_delta_local_solar_pv_grid_connected)
)