- deprecated_key = peak_load_per_unit_electric_truck
# 

- unit = mw

PRODUCT (

              V (electric_trucks_transport_energetic; typical_input_capacity_in_mw),   
              V (electric_trucks_transport_energetic; electricity_input_conversion)

               )