- deprecated_key = peak_load_delta_demand_plants_connected_to_mv_distribution_net
# This is the delta in the peak load due to technologies connected directly to the MV distribution net. I.e. it does not take into account demands by technologies connected at lower levels, this is done in the next query: peak_load_delta_demand_mv_distribution_net
# 
# OLD QUERY:
# PRODUCT(
#   SUM(
#     V(Q(demand_units_connected_to_mv_distribution_net) ; 
#            simult_we*
#            electricity_input_conversion*
#            typical_capacity_gross_in_mj_s*
#            [number_of_heat_plants_future-peak_load_units_present])
#     ),
#   1
# )

- unit = mw

SUM(
  MAX(
    PRODUCT(
      SUM(
        V(
          INTERSECTION(
            GROUP(heat_production), Q(demand_units_connected_to_mv_distribution_net));
             simult_we*
             electricity_input_conversion*
             typical_input_capacity*
             [number_of_units-peak_load_units_present])
        ),
      1
    ),
    PRODUCT(
      SUM(
        V(
          INTERSECTION(
            GROUP(heat_production), Q(demand_units_connected_to_mv_distribution_net));
             simult_sd*
             electricity_input_conversion*
             typical_input_capacity*
             [number_of_units-peak_load_units_present])
        ),
      1
    )
  ),
  PRODUCT(
    SUM(
      V(
        INTERSECTION(
          GROUP(electricity_production), Q(demand_units_connected_to_mv_distribution_net));
           simult_we*
           electricity_input_conversion*
           typical_input_capacity*
           [number_of_units-peak_load_units_present])
      ),
    1
  )
)