
# peak_load_capacity_delta_for_mv_hv calculates delta unit number of plants (future - present) and multiplies this by the simultaneousness and typical gross capacity for each plant. Simultaneousness needs to be added to simult_sd

- unit = mw

PRODUCT(
  SUM(
    V(Q(plants_connected_to_mv_hv_transformer); peak_load_capacity_delta_for_mv_hv)
  ),
  0.75
)