
# 

- unit = mw

SUM(
  PRODUCT(
    Q(peak_load_delta_demand_lv_total),
    V(lv_electricity_network_energy_energetic ; simult_wd),
    V(lv_mv_transformer_energy ; simult_wd)
    ),
  Q(peak_load_delta_demand_plants_connected_to_mv_distribution_net)
)