- deprecated_key = peak_load_delta_supply_plants_connected_to_mv_distribution_net
# What this query does:
# - Sums peak loads of HEAT and POWER plants that SUPPLY electricity at the MV Distribution net
# - INTERSECTION is used to check if it a heat or power plant
# Right now it is possible to remove plants to create extra space on the net (i.e. negative peak load)..If this shouldn't be possible then the query should be:
# 
# SUM(
#   PRODUCT(
#     SUM(
#       PRODUCT(
#         V(
#           INTERSECTION(
#             GROUP(heat_production), Q(supply_units_connected_to_mv_distribution_net));
#              simult_we*
#              electricity_output_conversion*
#              typical_capacity_gross_in_mj_s)
#         ),
#         MAX(
#           V(
#             INTERSECTION(
#               GROUP(heat_production), Q(supply_units_connected_to_mv_distribution_net));
#            number_of_heat_plants_future-peak_load_units_present),
#           0
#         )
#       ),
#     1
#   ),
#   PRODUCT(
#     SUM(
#       PRODUCT(
#         V(
#           INTERSECTION(
#             GROUP(electricity_production), Q(supply_units_connected_to_mv_distribution_net));
#              simult_we*
#              electricity_output_conversion*
#              typical_capacity_gross_in_mj_s)
#         ),
#         MAX(
#           V(
#             INTERSECTION(
#               GROUP(electricity_production), Q(supply_units_connected_to_mv_distribution_net));
#            number_of_plants_future-peak_load_units_present),
#           0
#         )
#       ),
#     1
#   )
# )

- unit = mw

SUM(
  PRODUCT(
    SUM(
      V(
        INTERSECTION(
          GROUP(heat_production), Q(supply_units_connected_to_mv_distribution_net));
           simult_we*
           electricity_output_conversion*
           typical_input_capacity_in_mw*
           [number_of_units-peak_load_units_present])
      ),
    1
  ),
  PRODUCT(
    SUM(
      V(
        INTERSECTION(
          GROUP(electricity_production), Q(supply_units_connected_to_mv_distribution_net));
           simult_we*
           electricity_output_conversion*
           typical_input_capacity_in_mw*
           [number_of_units-peak_load_units_present])
      ),
    1
  )
)