# Systematic way to determine the peak load per energy converter unit. This is the number to multiply with the 'simult_wd' etc attributes.

- unit = mw

PRODUCT (

              V (electric_cars_transport_energetic; typical_input_capacity_in_mw),   
              V (electric_cars_transport_energetic; electricity_input_conversion)

               )