- deprecated_key = peak_load_delta_supply_hv_mv_transformer
# 

- unit = mw

SUM(
  PRODUCT(
    Q(peak_load_delta_supply_mv_distribution_net),
    V(mv_distribution_network_energy_energetic ; simult_wd),
    V(mv_transport_network_energy ; simult_wd)
    ),
  Q(peak_load_delta_on_mv_hv_transformer)
)