- deprecated_key = peak_load_delta_demand_lv_total
# 

- unit = mw

MAX(
  Q(pl_lv_net_delta_capacity_we),
  Q(pl_lv_net_delta_capacity_wd),
  Q(pl_lv_net_delta_capacity_se),
  Q(pl_lv_net_delta_capacity_sd)
  )
