- deprecated_key = pl_mv_d_net_investment_costs_total
# 

- unit = euro

PRODUCT(
  Q(pl_mv_d_net_capacity_needed),
V(mv_distribution_network_energy_energetic;network_expansion_costs_in_euro_per_mw)
)