- deprecated_key = plants_connected_to_mv_hv_transformer
# This is the query that will be used once the graph is updated with the new converter attributes
# 
# 
# 
# old
# V(
#   solar_pv_central_production_energy_energetic,
#   central_gas_chp_energy_energetic,
#   biomass_chp_industry_energetic,
#   waste_incinerator_energy_energetic,
#   wind_inland_energy,
#   wind_coastal_energy,
#   solar_csp_energy,
#   hydro_river_energy,
#   geothermal_electricity_energy
# )

- unit = converters

V(
  solar_pv_central_production_energy_energetic,
  biomass_chp_industry_energetic,
  waste_incinerator_energy_energetic,
  wind_inland_energy,
  wind_coastal_energy,
  solar_csp_energy,
  hydro_river_energy,
  geothermal_electricity_energy,
  collective_gas_chp_households_energetic,
  collective_biomass_chp_households_energetic,
  gas_chp_buildings_energetic,
  biomass_chp_buildings_energetic
)