- deprecated_key = pl_network_investment_costs_per_year
# 

- unit = mln_euro

 SUM(
  Q(pl_lv_grid_investment_costs_per_year),
  Q(pl_mv_grid_investment_costs_per_year),
  Q(pl_hv_grid_investment_costs_per_year)
 )