- deprecated_key = pl_network_investment_costs_per_year
# 

- unit = mln_euro

 SUM(
  Q(yearly_investment_costs_of_lv_grid),
  Q(yearly_investment_costs_of_mv_grid),
  Q(yearly_investment_costs_of_hv_grid)
 )