- deprecated_key = pl_hv_grid_investment_costs_per_year
# First checks if the country is set to NL before it does the calculation.

- unit = mln_euro

IF(EQUALS(AREA(area),nl),
   SUM(
    DIVIDE(
      Q(pl_hv_net_investment_costs_total),V(hv_electricity_network_energy;technical_lifetime)
     ),
     PRODUCT(
     DIVIDE(
       Q(pl_hv_net_investment_costs_total),2
       ),
       V(hv_electricity_network_energy;wacc)
       ),
    DIVIDE(Q(pl_hv_net_operational_costs_total),MILLIONS)
     ),
  0)

