- deprecated_key = pl_mv_d_net_investment_costs_per_year
# 

- unit = euro

SUM(
 DIVIDE(
  Q(pl_mv_d_net_investment_costs_total),V(mv_distribution_network_energy_energetic;technical_lifetime)
 ),
 PRODUCT(
  DIVIDE(
   Q(pl_mv_d_net_investment_costs_total),2
  ),
  V(mv_distribution_network_energy_energetic;wacc)
 ),
 Q(pl_mv_d_net_operational_costs_total)
 )