- deprecated_key = pl_mv_t_net_investment_costs_per_year
# 

- unit = euro

SUM(
 DIVIDE(
  Q(total_investment_costs_of_mv_t_net),V(mv_transport_network_energy;technical_lifetime)
 ),
 PRODUCT(
  DIVIDE(
   Q(total_investment_costs_of_mv_t_net),2
  ),
  V(mv_transport_network_energy;wacc)
 ),
 Q(operational_costs_of_mv_t_net)
 )

