# Used to be this
# stored:policy_onshore_coast

- query =
    MIXED(
      Q(share_of_designated_area_used_for_coastal_wind),
      PRODUCT(
      DIVIDE(
        V(GOAL(onshore_coast),user_value),
        AREA(coast_line)
       ),100)
    )
- unit = km2
