- query =
    Q(batteries_opac_revenue_in_power_plant_economic_performance_table)
    - Q(batteries_opac_capex_in_power_plant_economic_performance_table)
    - Q(batteries_opac_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
