- query =
    IF(
      V(energy_flexibility_hv_opac_electricity, "merit_order.subtype") == :optimizing_storage ||
      V(energy_flexibility_hv_opac_electricity, "merit_order.subtype") == :optimizing_storage_households,
      -> { 0.0 },
      -> { V(energy_flexibility_hv_opac_electricity, max_consumption_price) }
    )
- unit = number
