- query =
    Q(batteries_electric_buses_revenue_in_storage_economic_performance_table)
    - Q(batteries_electric_buses_capex_in_storage_economic_performance_table)
    - Q(batteries_electric_buses_opex_in_storage_economic_performance_table)
- unit = EUR/MWh
