# Currently hard-coded to zero since the cost attributes of electric vehicle nodes
# are zero. Moreover, with the current node setup where costs are defined on the regular
# electric vehicle node (and not the p2p node), it is not yet possible to properly
# account for the costs related to deployment of the electric vehicles for storage.

- query = 0.0
- unit = EUR/MWh
