- query =
    Q(batteries_electric_cars_revenue_in_power_plant_economic_performance_table)
    - Q(batteries_electric_cars_capex_in_power_plant_economic_performance_table)
    - Q(batteries_electric_cars_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
