# The OPEX of storage in electric vehicles is calculated manually due to a different
# node setup. OPEX is defined here as the hourly electricity input multiplied
# with the hourly electricity price, and expressed in € per MWh output.

- query =
    DIVIDE(
      SUM(
        PRODUCT_CURVES(
          Q(merit_order_price_curve),
          V(transport_bus_flexibility_p2p_electricity, electricity_input_curve)
        )
      ),
      DIVIDE(V(transport_bus_flexibility_p2p_electricity, output_of_electricity), MJ_PER_MWH)
    )
- unit = €/MWh
