- query =
    Q(batteries_mv_revenue_in_storage_economic_performance_table)
    - Q(batteries_mv_capex_in_storage_economic_performance_table)
    - Q(batteries_mv_opex_in_storage_economic_performance_table)
- unit = EUR/MWh
