- query =
    IF(
      V(transport_car_flexibility_p2p_electricity, "merit_order.subtype") == :optimizing_storage ||
      V(transport_car_flexibility_p2p_electricity, "merit_order.subtype") == :optimizing_storage_households,
      -> { 0.0 },
      -> { V(transport_car_flexibility_p2p_electricity, max_consumption_price) }
    )
- unit = number
