- query =
    Q(pumped_storage_revenue_in_power_plant_economic_performance_table)
    - Q(pumped_storage_capex_in_power_plant_economic_performance_table)
    - Q(pumped_storage_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
