- deprecated_key = pl_lv_net_delta_capacity_supply
# Calculates the total peak load of household supply technologies for the 4 periods of the year and takes the maximum.

- unit = mw

MAX(
    ABS(SUM(
        PRODUCT( Q(peak_load_delta_household_micro_chp), V(micro_chp_space_heating_households ; simult_sd) ), 
        PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(local_solar_pv_grid_connected_energy_energetic ; simult_sd) )
    )),
    ABS(SUM(
        PRODUCT( Q(peak_load_delta_household_micro_chp), V(micro_chp_space_heating_households ; simult_se) ),
        PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(local_solar_pv_grid_connected_energy_energetic ; simult_se) )
    )),
    ABS(SUM(
        PRODUCT( Q(peak_load_delta_household_micro_chp), V(micro_chp_space_heating_households ; simult_wd) ),
        PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(local_solar_pv_grid_connected_energy_energetic ; simult_wd) )
    )),
    ABS(SUM(
        PRODUCT( Q(peak_load_delta_household_micro_chp), V(micro_chp_space_heating_households ; simult_we) ),
        PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(local_solar_pv_grid_connected_energy_energetic ; simult_we) )
    ))
)