- deprecated_key = pl_lv_net_delta_capacity_sd
# In theory peak load delta heaters needs to be taken into account but they have no demand in the summer
# 
# SUM(
#   Q(peak_load_delta_electric_cars_sd),
#   Q(peak_load_delta_electric_trucks_sd),
#   Q(peak_load_delta_household_coolers)
# )

- unit = mw

ABS(SUM(
  Q(peak_load_delta_electric_cars_sd),
  Q(peak_load_delta_electric_trucks_sd),
  Q(peak_load_delta_household_coolers),
  Q(peak_load_delta_electric_boiler),
  SUM(
      PRODUCT( Q(peak_load_delta_household_micro_chp), V(micro_chp_space_heating_households ; simult_sd) ), 
      PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(local_solar_pv_grid_connected_energy_energetic ; simult_sd) )
  )
))