- deprecated_key = pl_lv_net_delta_capacity_wd
# 

- unit = mw

SUM(
  Q(peak_load_delta_electric_cars_wd),
  Q(peak_load_delta_electric_trucks_wd),
  Q(peak_load_delta_household_heaters),
  Q(peak_load_delta_electric_boiler)
)