- deprecated_key = pl_lv_net_delta_capacity_supply
# Calculates the total peak load of household supply technologies for the 4 periods of the year and takes the maximum.

- unit = mw

MAX(
    ABS(SUM(
        PRODUCT( Q(peak_load_delta_household_micro_chp), V(households_space_heater_micro_chp_network_gas , simult_sd) ), 
        PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(households_solar_pv_solar_radiation , simult_sd) )
    )),
    ABS(SUM(
        PRODUCT( Q(peak_load_delta_household_micro_chp), V(households_space_heater_micro_chp_network_gas , simult_se) ),
        PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(households_solar_pv_solar_radiation , simult_se) )
    )),
    ABS(SUM(
        PRODUCT( Q(peak_load_delta_household_micro_chp), V(households_space_heater_micro_chp_network_gas , simult_wd) ),
        PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(households_solar_pv_solar_radiation , simult_wd) )
    )),
    ABS(SUM(
        PRODUCT( Q(peak_load_delta_household_micro_chp), V(households_space_heater_micro_chp_network_gas , simult_we) ),
        PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(households_solar_pv_solar_radiation , simult_we) )
    ))
)
