- deprecated_key = pl_lv_net_delta_capacity_we
# 

- unit = mw

ABS(SUM(
  Q(peak_load_delta_electric_cars_we),
  Q(peak_load_delta_electric_trucks_we),
  Q(peak_load_delta_household_heaters),
  Q(peak_load_delta_electric_boiler),
  SUM(
      PRODUCT( Q(peak_load_delta_household_micro_chp), V(households_space_heater_micro_chp_network_gas , simult_we) ),
      PRODUCT( Q(peak_load_delta_local_solar_pv_grid_connected), V(households_solar_pv_solar_radiation , simult_we) )
  )
))
