- deprecated_key = peak_load_delta_sd_electric_trucks
# 

- unit = mw

V( electric_trucks_transport_energetic ;" simult_sd*typical_input_capacity_in_mw*electricity_input_conversion * (number_of_units - peak_load_units_present) ")
