# This query is the maximum possible peak load of a single converter, without taking the simultaneousness into account (that is in another query)

- deprecated_key = peak_load_delta_hh_micro_chp
- unit = mw

PRODUCT(
    V(households_space_heater_micro_chp_network_gas ," typical_input_capacity * electricity_output_conversion * share_of_heating_demand_households_energetic"),
    AREA(number_households)
)
