# This query is the maximum possible peak load of a single converter, without taking the simultaneousness into account (that is in another query)

- unit = mw

V(households_space_heater_micro_chp_network_gas ," typical_input_capacity * electricity_output_conversion * number_of_units ")
