- deprecated_key = peak_load_delta_se_electric_cars
# 

- unit = mw

V( electric_cars_transport_energetic ;" simult_se*typical_input_capacity_in_mw*electricity_input_conversion * [number_of_units - peak_load_units_present] ")
