- deprecated_key = peak_load_delta_hh_heaters
# This query gives the peak load delta due to heater technologies using electricity.
# 
# In theory the query needs to be written for all 4 time periods: we, wd, se, sd. And then take the max value. However the simultaneousness of the technologies is 1,and the peak is during the winter evening for hh_heaters
# Future fix
# SUM(
#    V(Q(household_heaters_in_network_calculation),"
#          simult_we*
#          electricity_input_conversion*
#          typical_input_capacity_in_mw*(number_of_units - peak_load_units_present)")
#)

- unit = mw

PRODUCT (
     SUM(
        V(Q(household_heaters_in_network_calculation),"
          simult_we*
          electricity_input_conversion*
          typical_input_capacity_in_mw*
          share_of_households_useful_demand_for_space_heating_after_insulation")
        )
     ,
    AREA(number_households)
)
