# investment costs of buildings_collective_geothermal IF newly built (green field approach)

- query =
    QUERY_DELTA( -> { 
       V(buildings_collective_geothermal,total_investment_over_lifetime_per(:converter)) 
    }) / BILLIONS
- unit = euro
