# investment costs of buildings_collective_heatpump_water_water_electricity IF newly built (green field approach)

- query =
    QUERY_DELTA( -> { 
       V(buildings_collective_heatpump_water_water_electricity,total_investment_over_lifetime_per(:converter)) 
    }) / BILLIONS
- unit = euro
