# investment costs of buildings_space_heater_crude_oil IF newly built (green field approach)

- query = present:V(buildings_space_heater_crude_oil, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
