# investment costs of energy_heater_for_heat_network_coal IF newly built (green field approach)

- query =
    QUERY_DELTA( -> { 
       V(energy_heater_for_heat_network_coal,total_investment_over_lifetime_per(:converter)) 
    }) / BILLIONS
- unit = euro
