# investment costs of energy_flexibility_p2g_electricity IF newly built (green field approach)

- query = future:V(energy_flexibility_p2g_electricity, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
