# investment costs of energy_power_ultra_supercritical_crude_oil IF newly built (green field approach)

- query = present:V(energy_power_ultra_supercritical_crude_oil, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
