# investment costs of energy_power_turbine_network_gas IF newly built (green field approach)

- query =
    QUERY_DELTA( -> { 
       V(energy_power_turbine_network_gas,total_investment_over_lifetime_per(:converter)) 
    }) / BILLIONS
- unit = euro
