# investment costs of energy_power_hydro_river IF newly built (green field approach)

- query = future:V(energy_power_hydro_river, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
