# investment costs of energy_heater_for_heat_network_waste_mix IF newly built (green field approach)

- query = present:V(energy_heater_for_heat_network_waste_mix, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
