# investment costs of energy_power_nuclear_gen2_uranium_oxide IF newly built (green field approach)

- query =
    QUERY_DELTA( -> { 
       V(energy_power_nuclear_gen2_uranium_oxide,total_investment_over_lifetime_per(:converter)) 
    }) / BILLIONS
- unit = euro
