# investment costs of households_space_heater_district_heating_steam_hot_water 
# and households_water_heater_district_heating_steam_hot_water
# IF newly built (green field approach)
# Corrected for double counting

- query =
    future:IF(
        QUERY_FUTURE(households_space_heater_district_heating_steam_hot_water_future_in_investment_cost_table) > 
        QUERY_FUTURE(households_water_heater_district_heating_steam_hot_water_future_in_investment_cost_table),
        Q(households_space_heater_district_heating_steam_hot_water_future_in_investment_cost_table),
        Q(households_water_heater_district_heating_steam_hot_water_future_in_investment_cost_table)
    )
- unit = euro