# investment costs of households_collective_burner_hydrogen IF newly built (green field approach)

- query =
    QUERY_DELTA( -> {
       V(households_collective_burner_hydrogen,total_investment_over_lifetime_per(:converter))
    }) / BILLIONS
- unit = euro
