# investment costs of households_water_heater_network_gas IF newly built (green field approach)

- query = present:V(households_water_heater_network_gas, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
