# investment costs of households_space_heater_heatpump_air_water_electricity,
# households_water_heater_heatpump_air_water_electricity
# and households_cooling_heatpump_air_water_electricity
# IF newly built (green field approach)
# Corrected for double counting:
# IFF both the space heating and water heating pumps are zero, the cost of the cooling pump is used
# ELSE the maximum of space heating and water heating is used

- query =
    future:IF(
        QUERY_FUTURE(households_space_heater_heatpump_air_water_electricity_future_in_investment_cost_table) +
        QUERY_FUTURE(households_water_heater_heatpump_air_water_electricity_future_in_investment_cost_table) > 0.0,

        IF(
            QUERY_FUTURE(households_space_heater_heatpump_air_water_electricity_future_in_investment_cost_table) > 
            QUERY_FUTURE(households_water_heater_heatpump_air_water_electricity_future_in_investment_cost_table),
            Q(households_space_heater_heatpump_air_water_electricity_future_in_investment_cost_table),
            Q(households_water_heater_heatpump_air_water_electricity_future_in_investment_cost_table)
        ),
        Q(households_cooling_heatpump_air_water_electricity_future_in_investment_cost_table)
    )
- unit = euro
