# investment costs of households_water_heater_hybrid_hydrogen_heatpump_air_water_heater_electricity IF newly built (green field approach)

- query =
    QUERY_DELTA( -> {
       V(households_water_heater_hybrid_hydrogen_heatpump_air_water_heater_electricity,total_investment_over_lifetime_per(:converter))
    }) / BILLIONS
- unit = euro
