# investment costs of industry_chemicals_other_heater_electricity IF newly built (green field approach)

- query = future:V(industry_chemicals_other_heater_electricity, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
