# investment costs of industry_other_paper_burner_crude_oil IF newly built (green field approach)

- query =
    QUERY_DELTA( -> { 
       V(industry_other_paper_burner_crude_oil,total_investment_over_lifetime_per(:converter)) 
    }) / BILLIONS
- unit = euro
