# investment costs of households_flexibility_p2h_electricity IF newly built (green field approach)

- query = present: SUM(V(industry_chemicals_other_flexibility_p2h_electricity,total_investment_over_lifetime_per(:converter)),V(industry_chemicals_refineries_flexibility_p2h_electricity,total_investment_over_lifetime_per(:converter)),V(industry_other_food_flexibility_p2h_electricity,total_investment_over_lifetime_per(:converter)),V(industry_other_paper_flexibility_p2h_electricity,total_investment_over_lifetime_per(:converter))) / BILLIONS
- unit = euro
