# investment costs of industry_chemicals_refineries_burner_network_gas IF newly built (green field approach)

- query = present:V(industry_chemicals_refineries_burner_network_gas, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
