- query =
    DIVIDE(
      SUM(
        V(
          FILTER(G(sankey_conversion_group),"network_gas_output_conversion > 0.0 && natural_gas_input_conversion > 0.0"),
          "network_gas_output_conversion * natural_gas_input_conversion / (1 - loss_output_conversion) * output_of_loss"
        )
      ), 
      BILLIONS
    )
- unit = PJ
