- query =
    SUM(
      DIVIDE(
        SUM(
          V(
            FILTER(G(sankey_conversion_group),"electricity_output_conversion > 0.0 && network_gas_input_conversion > 0.0"),
            "electricity_output_conversion * network_gas_input_conversion / (1 - loss_output_conversion) * output_of_loss"
          )
        ), 
        BILLIONS
      ),
      PRODUCT(
        Q(conversion_loss_gas_power_fuelmix_to_electricity),
        V(energy_mixer_for_gas_power_fuel, network_gas_input_conversion)
      )
    )
- unit = PJ
