# Final consumption of natural gas and gas products in energy (energetic and non-energetic use combined).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Natural gas and gas products
# Use type:    Total
#
# Exception: includes the share of natural gas and gas products in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_natural_gas_and_gas_products_in_energy_total)
