# The extra needed capacity is the delta (difference) between the present capacity of the net and the peak load in the future scenario. The difference is the extra needed capacity.

- query = QUERY_FUTURE(hv_net_peak_load_future) - QUERY_PRESENT(hv_net_capacity_present)

- unit = MW
