# The capacity of the the low voltage net in the present.

- query =
          IF(
              AREA(hv_net_spare_capacity) >= 1.0,
              0.0,
              QUERY_PRESENT(hv_net_peak_load_present) / (1.0 - AREA(hv_net_spare_capacity))
            )

- unit = MW
