# Combined demand peak of households and buildings sector
- query =
      SUM_CURVES(
        V(
          households_space_heater_district_heating_lt_steam_hot_water,
          households_water_heater_district_heating_lt_steam_hot_water,
          buildings_space_heater_district_heating_lt_steam_hot_water, steam_hot_water_input_curve)).max
- unit = MW

