# 

- deprecated_key = centrally_produced_electricity_households
- unit = mj

SUM(
  V(electricity_households_energetic;demand),
  NEG( SUM(V(local_solar_pv_grid_connected_energy_energetic,collective_coal_chp_households_energetic,collective_gas_chp_households_energetic,collective_biomass_chp_households_energetic,local_wind_turbines_energy;output_of_electricity)
  )
 ),
NEG(V(electricity_households_energetic;electricity_inversedflexible_output_link_value))
)