
- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(
                Q(converter_group_power_plant_per_plant_type_hydrogen), 
                input_of_hydrogen
            )
        ),
        BILLIONS
    )