- query =
    SUM_CURVES(
      V(
        FILTER(
          INTERSECTION(
            G(heat_production),
            SECTOR(industry)
          ),
          "steam_hot_water_output_conversion > 0.0 || electricity_output_conversion > 0.0"
        ), hydrogen_input_curve
      )
    )
- unit = curve
