# Direct conversion output of steam hot water from central heating through ambient heaters

- query =
    DIVIDE(
      SUM(
        V(
          Q(central_heat_producing_converters_sankey),
          "output_of_steam_hot_water * ambient_heat_input_conversion"
        )
      ),
      BILLIONS
    )
- unit = PJ
