# Direct conversion output of steam hot water from central heating through ambient heaters excluding power-to-heat which is represented as a separate flow

- query =
    Q(ambient_heat_in_source_of_central_heat_production) -
    Q(ambient_heat_p2h_in_source_of_central_heat_production)
- unit = PJ
