# Direct conversion input of biomass products for central heat production

- query =
    SUM(
    DIVIDE(
      SUM(
        V(
          Q(central_heat_producing_converters_sankey),
          input_of(
            non_biogenic_waste,
            greengas,
            biodiesel,
            bio_ethanol,
            bio_lng,
            bio_oil,
            biogas,
            bio_kerosene,
            torrefied_biomass_pellets,
            wood_pellets,
            biogenic_waste,
            waste_mix
          )
        )
      ),
      BILLIONS
    ),
    Q(gas_power_fuelmix_for_central_heat_conversion) * V(energy_mixer_for_gas_power_fuel, bio_oil_input_conversion),
    Q(network_gas_for_central_heat_conversion) * Q(share_of_sustainable_gas_in_gas_network)
    )
- unit = PJ
