# Direct conversion output of steam hot water from central heating through coal derivatives heaters

- query =
    SUM(
      Q(coal_in_source_of_central_heat_production),
      Q(lignite_in_source_of_central_heat_production)
    )
- unit = PJ
