# Direct conversion output of steam hot water from central heating through network gas heaters

- query =
    SUM(
      DIVIDE(
        SUM(
          V(
            Q(central_heat_producing_converters_sankey),
            "output_of_steam_hot_water * network_gas_input_conversion"
          )
        ),
        BILLIONS
      ),
      Q(gas_power_fuelmix_in_source_of_central_heat_conversion) * V(energy_mixer_for_gas_power_fuel, network_gas_input_conversion)
    )
- unit = PJ
