# Query for scenario tools regional overview: direct conversion demand of gas power fuelmix for electricity production

- query =
    DIVIDE(
      SUM(
        V(
          Q(central_heat_producing_converters_sankey),
          input_of(
            torrefied_biomass_pellets
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
