# Total unused heat in HT, MT and LT network

- query =
    SUM(
      Q(unused_heat_in_ht_heat_network),
      Q(unused_heat_in_mt_heat_network),
      Q(unused_heat_in_lt_heat_network)
    )
- unit = PJ
