# Energetic final demand of the 'electricity' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(fertilizers_industry)
            ),
            energetic?
          ),
          electricity?
        ),
        value
      )
    ) / BILLIONS
