- query =
    SUM(
      PRODUCT(
        Q(conversion_loss_network_gas_to_natural_gas_and_derivatives),
        Q(share_of_propane_in_gas_network)
      ),
      PRODUCT(
        Q(conversion_loss_natural_gas_to_network_gas),
        Q(share_of_propane_in_gas_network)
      ),
      Q(conversion_loss_natural_gas_to_natural_gas),
      Q(conversion_loss_lng_to_natural_gas)
    )
- unit = PJ
