- query =
    DIVIDE(
      SUM(
        V(
          energy_hydrogen_ammonia_reformer,
          primary_co2_emission
        )
      ),
      SUM(
        Q(energy_hydrogen_ammonia_reformer_hydrogen_output_curve)
      )
    )
- unit = kg/MWh
