- query =
    PRODUCT(
      V(energy_flexibility_flow_batteries_electricity, "number_of_units * input_capacity"),
      V(energy_flexibility_flow_batteries_electricity, availability)
    )

- unit = MW
