# Returns the produced electricity of hydrogen dedicated offshore wind to hydrogen production

- unit = PJ
- query =
    DIVIDE(
      V(energy_hydrogen_electrolysis_wind_electricity, input_of_electricity),
      BILLIONS
    )
