# Returns the produced electricity from hybrid offshore wind that goes to dedicated hydrogen production.

- unit = PJ
- query =
    DIVIDE(
      V(energy_hydrogen_hybrid_electrolysis_wind_electricity, input_of_electricity),
      BILLIONS
    )
