# Total other GHG emissions incl. LULUCF, excl indirect emissions and international transport
# Only indirect CO2 emissions are modelled, therefore there is no query for indirect other GHG

- unit = MT
- query =
    SUM(
      Q(direct_emissions_other_ghg_incl_indirect_emissions_lulucf_bunkers),
      NEG(Q(direct_emissions_bunkers_other_ghg))
    )
