# The delta (difference) between the present and the future costs of the low voltage net.

- query =
          SUM(
              QUERY_FUTURE(hv_net_additional_capital_costs),
              QUERY_FUTURE(hv_net_additional_operation_and_maintenance_costs)
          )

- unit = euro
