# Non-energetic final demand of the 'electricity' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(other_industry)
            ),
            "! energetic?"
          ),
          electricity?
        ),
        value
      )
    ) / BILLIONS
