# Final demand of the 'coal_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            EG(final_demand),EG(metal_industry)
          ),
          coal?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            EG(final_demand),EG(metal_industry)
          ),
          coal_gas?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            EG(final_demand),EG(metal_industry)
          ),
          cokes?
        ),
        value
      )
    ) / BILLIONS
