# times 100 to convert km2 to hectare
- query = 
    SUM(
      V(
        energy_power_solar_pv_solar_radiation, 
        energy_power_solar_pv_offshore,
        energy_hydrogen_solar_pv_solar_radiation, 
        energy_battery_solar_pv_solar_radiation,
        "number_of_units * land_use_per_unit"
      )
    ) * 100
- unit = #
