- query =
    SUM(
      PRODUCT(
        SUM(
          V(
            households_water_heater_solar_thermal,
            buildings_space_heater_solar_thermal,
            number_of_units
          )
        ),
        Q(factsheet_OM_solar_thermal_number_of_units_correction)
      )
    )
- unit = #
