- query =
    SUM(
      V(
        EXCLUDE(
          Q(electricity_producing_solar_converters),
          V(energy_battery_solar_electricity)
        ),
        energy_battery_solar_pv_solar_radiation,
        energy_hydrogen_solar_pv_solar_radiation,
        "electricity_output_capacity * number_of_units"
      )
    )
- unit = MW
