# A query which returns an array of node keys which are omitted from the calculation of excess
# hours events.
- query =
    FLATTEN(
      V(
        energy_flexibility_pumped_storage_electricity,
        households_flexibility_p2p_electricity,
        transport_car_flexibility_p2p_electricity,
        power_to_heat_industry,
        households_flexibility_p2h_electricity,
        energy_hydrogen_flexibility_p2g_electricity,
        energy_flexibility_curtailment_electricity,
        key
      ),
      V(G(electricity_interconnectors_export), key)
    )
