# The total man-hours spent in NL on preparation, production, placement, maintenance and removal.

- unit = hours

SUM(
V(Q(total_fte_preparation_NL)),
V(Q(total_fte_production_NL)),
V(Q(total_fte_placement_NL)),
V(Q(total_fte_maintenance_NL)),
V(Q(total_fte_removal_NL)),
V(Q(total_fte_insulation_NL))
)