# The total man-year spent in NL on removal.

- unit = man_years

PRODUCT(
	DIVIDE(
		PRODUCT(
			SUM(
				V(Q(employment_converters);hours_remov_nl*number_of_units/technical_lifetime)),
				V(Q(scenario_duration)
			)
		),
		MAN_HOURS_PER_MAN_YEAR
	),
	AREA(economic_multiplier)
)
