# The total man-years spent in NL on insulation.

- unit = man_years

PRODUCT(
	PRODUCT(V(extra_insulation_savings_households_energetic;demand), MAN_YEAR_PER_MJ_INSULATION_PER_YEAR),
	AREA(economic_multiplier)
)