# The total man-year spent in NL on maintenance.

- unit = man_years

PRODUCT(
	DIVIDE(
		SUM(
			V(Q(employment_converters);"hours_maint_nl*number_of_units")
		),
		MAN_HOURS_PER_MAN_YEAR
	),
	AREA(economic_multiplier)
)
