# The total man-hours spent in NL on preparation, production, placement, maintenance and removal.

- unit = hours

SUM(
V(Q(total_man_hours_preparation)),
V(Q(total_man_hours_production)),
V(Q(total_man_hours_placement)),
V(Q(total_man_hours_maintenance)),
V(Q(total_man_hours_removal)),
man_hoursV(Q(total_man_hours_insulation))
)