# The total man-hours spent in NL on preparation, production, placement, maintenance and removal.

- unit = hours

SUM(
V(Q(total_man_hours_preparation_NL)),
V(Q(total_man_hours_production_NL)),
V(Q(total_man_hours_placement_NL)),
V(Q(total_man_hours_maintenance_NL)),
V(Q(total_man_hours_removal_NL)),
man_hoursV(Q(total_man_hours_insulation_NL))
)