# The total man-years spent in NL on insulation.
# The number 0.00002777 is a dirty hack to translate cost (euro) to man-years
# I assume 20 euro per man-hour and 1800 man-hours per man-year

- unit = man_years

PRODUCT(V(extra_insulation_savings_households_energetic);demand * costs_per_mj), 0.00002777)