# The total man-years spent in NL on preparation, production, placement, maintenance and removal.

- unit = man_years

SUM(
V(Q(total_man_years_preparation_NL)),
V(Q(total_man_years_production_NL)),
V(Q(total_man_years_placement_NL)),
V(Q(total_man_years_maintenance_NL)),
V(Q(total_man_years_removal_NL)),
V(Q(total_man_years_insulation_NL))
)