- deprecated_key = chart_media_2_electricity_demand_8
# 

- unit = pj

DIVIDE(SUM(V(households_appliances_television_electricity,stereo_households_energetic,households_appliances_computer_media_electricity,input_of_electricity)),BILLIONS)
