# Final consumption of gaseous biofuels in other (non-energetic use only).
#
# Sector:      Other -- sector == :other
# Carrier:     Gaseous biofuels
# Use type:    Non-energetic -- !energetic?
#
# Exception: includes the share of gaseous biofuels in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_gaseous_biofuels_in_other_non_energetic)
