- query = 
    DIVIDE_CURVES(
          SUM_CURVES(
            Q(hourly_supply_electricity_from_biogas),
            Q(hourly_supply_electricity_from_biomass),
            Q(hourly_supply_electricity_from_geothermal),
            Q(hourly_supply_electricity_from_greengas),
            Q(hourly_supply_electricity_from_hydro),
            Q(hourly_supply_electricity_from_hydrogen),
            Q(hourly_supply_electricity_from_solar),
            Q(hourly_supply_electricity_from_uranium),
            Q(hourly_supply_electricity_from_waste),
            Q(hourly_supply_electricity_from_wind)
            ),
      Q(hourly_production_electricity)
    )
- unit = curve
