- query =
    DIVIDE(
      SUM(
        V(
          energy_hydrogen_flexibility_p2g_electricity,
          energy_hydrogen_hybrid_electrolysis_wind_electricity,
          energy_hydrogen_electrolysis_solar_electricity,
          energy_hydrogen_electrolysis_wind_electricity,
          energy_hydrogen_electrolysis_solar_electricity,
          input_of_electricity
        )
      ),
      BILLIONS
    )
- unit = PJ
