- query =
  DIVIDE(
    SUM(
      V(
        energy_flexibility_curtailment_electricity,
        energy_hydrogen_curtailed_electricity,
        energy_power_hybrid_curtailed_electricity,
        energy_battery_curtailed_solar_electricity,
        energy_battery_curtailed_wind_electricity,
        demand
      )
    ),
    BILLIONS
  )
- unit = PJ
