- query =
  DIVIDE(
    SUM(
      V(
        INTERSECTION(
          G(heat_production),
          G(central_production),
          SECTOR(energy)
          ),
        input_of_electricity
        )
      )
    )
- unit = PJ