- query = 
    DIVIDE(
      SUM(
        V(
          Q(powerplants_biogas),
          Q(powerplants_wood_pellets),
          output_of_electricity
        )
      ),
      BILLIONS
    )
- unit = PJ
