# Electricity output curve is queried instead of the output of electricity
# The electricity output curve shows the actual electricity supplied to the grid
# The output of electricity does not take unused and decayed electricity into account
# See https://github.com/quintel/mechanical_turk/issues/152#issuecomment-1060882609

- query =
    V(energy_flexibility_pumped_storage_electricity, input_of_electricity) -
    PRODUCT(SUM(V(energy_flexibility_pumped_storage_electricity, electricity_output_curve)),MJ_PER_MWH)
- unit = MJ
