- query =
    SUM(
      V(EDGE(energy_flexibility_wind_batteries_electricity,energy_battery_unused_electricity),demand),
      V(energy_flexibility_wind_batteries_electricity,output_of_loss)
    )
- unit = MJ
