# Direct conversion input of biogenic_waste to biodiesel

- query =
    DIVIDE(
      SUM(
        V(
          Q(biofuels_producers),
          "biodiesel_output_conversion / (1 - loss_output_conversion) * input_of_biogenic_waste"
        )
      ),
      BILLIONS
    )
- unit = PJ
