# Direct conversion input of bio_pyrolysis_oil to bionaphtha

- query =
    DIVIDE(
      SUM(
        V(
          Q(biofuels_producers),
          "bionaphtha_output_conversion / (1 - loss_output_conversion) * input_of_bio_pyrolysis_oil"
        )
      ),
      BILLIONS
    )
- unit = PJ
