# Direct conversion input of hydrogen to bionaphtha in fractionation of bio_pyrolysis_oil

- query =
    DIVIDE(
      SUM(
        V(
          energy_production_fractionation_bio_pyrolysis_oil,
          "bionaphtha_output_conversion / (1 - loss_output_conversion) * input_of_hydrogen"
        )
      ),
      BILLIONS
    )
- unit = PJ
