# Direct conversion input of steam_hot_water to bionaphtha

- query =
    DIVIDE(
      SUM(
        V(
          Q(biofuels_producers),
          "bionaphtha_output_conversion / (1 - loss_output_conversion) * input_of_steam_hot_water"
        )
      ),
      BILLIONS
    )
- unit = PJ
