# Direct conversion input of biomethanol to bionaphtha

- query =
    DIVIDE(
      SUM(
        V(
          Q(biofuels_producers),
          "bionaphtha_output_conversion / (1 - loss_output_conversion) * input_of_biomethanol"
        )
      ),
      BILLIONS
    )
- unit = PJ
