- query =
    DIVIDE(
      SUM(
        V(
          Q(biofuels_producers),
          "greengas_output_conversion / (1 - loss_output_conversion) * input_of_biogas"
        )
      ),
      BILLIONS
    )
- unit = PJ
