# Direct conversion input of steam_hot_water to bio_kerosene

- query =
    DIVIDE(
      SUM(
        V(
          Q(biofuels_producers),
          "bio_kerosene_output_conversion / (1 - loss_output_conversion) * input_of_steam_hot_water"
        )
      ),
      BILLIONS
    )
- unit = PJ
