# Direct conversion input of hydrogen to bio_kerosene in biomethanol_to_jet specifically

- query =
    DIVIDE(
      SUM(
        V(
          V(energy_production_biomethanol_to_jet),
          "bio_kerosene_output_conversion / (1 - loss_output_conversion) * input_of_hydrogen"
        )
      ),
      BILLIONS
    )
- unit = PJ
