# The CAPEX of the future lv-mv transformers

- query =
          SUM(
              QUERY_FUTURE(lv_mv_trafo_capital_costs),
              QUERY_FUTURE(lv_mv_trafo_depreciation_costs)
          )

- unit = euro
