# The costs of the future hv net

- query = V(energy_power_transformer_lv_mv_electricity,fixed_operation_and_maintenance_costs_per(:mw_input)) * QUERY_FUTURE(lv_mv_trafo_capacity_delta_present_future)

- unit = euro
