# The OPEX of the future lv-mv transformers, consisting of operation and maintenance costs

- query =
          SUM(
              QUERY_FUTURE(lv_mv_trafo_operation_and_maintenance_costs)
          )

- unit = euro
