# This query retrieves the technical lifetime used in calculating the depreciation costs. The query is used in the ETM costs export.

- query =
        V(energy_power_transformer_lv_mv_electricity,technical_lifetime)

- unit = year
