# The capital costs of the future lv-mv transformers

- query =
          SUM(
              QUERY_FUTURE(lv_mv_trafo_investment_costs) / 2.0 * V(energy_power_transformer_lv_mv_electricity,wacc)
          )

- unit = euro
