# The CAPEX of the future lv-mv transformers

- query =
          SUM(
              QUERY_FUTURE(lv_mv_trafo_additional_capital_costs),
              QUERY_FUTURE(lv_mv_trafo_additional_depreciation_costs)
          )

- unit = euro
