# Uses the query for ETM sector LULUCF, which exactly matches IPCC category 5 LULUCF.
# This is done since using the IPCC columns of the mapping file in a query could not distinguish
# between emissions and removals for CO2.

- unit = MT
- query = Q(direct_emissions_lulucf_co2_1990)
