# Energetic final demand of network gas in industry excluding ict

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_natural_gas_and_derivatives_in_industry_energetic),
      Q(final_demand_of_greengas_in_industry_energetic)
    )
