# The total costs of the network calculation

- query =
          SUM(
              Q(interconnection_net_costs_present),
              Q(interconnection_net_capacity_delta_present_future) * 2
          )

- unit = euro
