# The total costs of the network calculation

- query =
          IF(
              Q(interconnection_net_capacity_delta_present_future) >= 0,
              Q(interconnection_net_capacity_delta_present_future) * INPUT_VALUE(number_of_energy_power_ultra_supercritical_coal),
              0
            )


- unit = euro
