# The total costs of the network calculation

- query = QUERY_FUTURE(interconnection_net_capacity_delta_present_future) * INPUT_VALUE(costs_infrastructure_electricity_interconnector_net) * THOUSANDS

- unit = euro
