# Total CO2 emissions incl. indirect emissions, LULUCF and international transport

- unit = MT
- query =
    SUM(
      Q(direct_emissions_energy_co2),
      Q(direct_emissions_industry_co2),
      Q(direct_emissions_transport_co2),
      Q(direct_emissions_buildings_co2),
      Q(direct_emissions_households_co2),
      Q(direct_emissions_agriculture_co2),
      Q(direct_emissions_other_co2),
      Q(direct_emissions_lulucf_co2),
      Q(direct_emissions_waste_co2),
      Q(direct_emissions_bunkers_co2)
    )
