# Final demand of the 'ambient' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :households"
            ),
            energetic?
          ),
          ambient_heat?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :households"
            ),
            energetic?
          ),
          ambient_cold?
        ),
        value
      )
    ) / BILLIONS
