# Final demand of the 'methanol' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          methanol?
        ),
        value
      )
    ) / BILLIONS
