# Final demand of the 'ammonia' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          ammonia?
        ),
        value
      )
    ) / BILLIONS
