# Final demand of the 'hydrogen' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :bunkers"
            ),
            energetic?
          ),
          hydrogen?
        ),
        value
      )
    ) / BILLIONS
