# Final demand of the 'biomass_products' carrier group

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_buildings_space_heating_energetic),
      Q(final_demand_of_biomass_products_in_buildings_lighting_energetic),
      Q(final_demand_of_biomass_products_in_buildings_cooling_energetic),
      Q(final_demand_of_biomass_products_in_buildings_appliances_energetic)
    )
      