# Final demand of the 'heat' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :bunkers"
            ),
            energetic?
          ),
          steam_hot_water?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :bunkers"
            ),
            energetic?
          ),
          useable_heat?
        ),
        value
      )
    ) / BILLIONS
