# Energetic final demand of the 'greengas' carrier group in industry (excl. ICT)

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_greengas_in_households_space_heating_energetic),
      Q(final_demand_of_greengas_in_households_hot_water_energetic),
      Q(final_demand_of_greengas_in_households_lighting_energetic),
      Q(final_demand_of_greengas_in_households_cooling_energetic),
      Q(final_demand_of_greengas_in_households_cooking_energetic),
      Q(final_demand_of_greengas_in_households_appliances_energetic)
    )