# Final demand of the 'natural_gas_and_derivatives' carrier group
- unit = PJ
- query =
    SSUM(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(
                EG(final_demand),"sector == :buildings"), "natural_gas? || lng? || propane?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      PRODUCT(
        SUM(
          V(
            FILTER(
              FILTER(
                FILTER(
                  EG(final_demand),"sector == :buildings"), "network_gas? || compressed_network_gas?"
              ),
              "energetic?"
            ),
            value
          )
        ),
        Q(share_of_fossil_gas_in_gas_network)
      )
    ) / BILLIONS