# Final demand of the 'oil_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          crude_oil?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          gasoline?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          diesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          lpg?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          kerosene?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          heavy_fuel_oil?
        ),
        value
      )
    ) / BILLIONS
