# Final demand of the 'natural_gas_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_natural_gas_in_households_space_heating_energetic),
      Q(final_demand_of_natural_gas_in_households_hot_water_energetic),
      Q(final_demand_of_natural_gas_in_households_appliances_energetic),
      Q(final_demand_of_natural_gas_in_households_cooking_energetic),
      Q(final_demand_of_natural_gas_in_households_cooling_energetic),
      Q(final_demand_of_natural_gas_in_households_lighting_energetic),
      Q(final_demand_of_lng_in_households_space_heating_energetic),
      Q(final_demand_of_lng_in_households_hot_water_energetic),
      Q(final_demand_of_lng_in_households_appliances_energetic),
      Q(final_demand_of_lng_in_households_cooking_energetic),
      Q(final_demand_of_lng_in_households_cooling_energetic),
      Q(final_demand_of_lng_in_households_lighting_energetic)
    )