# Final demand of the 'natural_gas_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :industry"
            ),
            energetic?
          ),
          network_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :industry"
            ),
            energetic?
          ),
          compressed_network_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :industry"
            ),
            energetic?
          ),
          lng?
        ),
        value
      )
    ) / BILLIONS
