# Final demand of the 'coal_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
          FILTER(
            FILTER(
              FILTER(
            EG(final_demand),"sector == :households"), "coal? || coal_gas? || cokes? || lignite?"
          ),
          "energetic?"
        ),
        value
      )
    )
     / BILLIONS