# The final demand in the buildings sector.

- unit = PJ
- query =
  SUM(
    V(
      FILTER(
          FILTER(
            EG(final_demand),"sector == :buildings"
          ),
          energetic?
        ),
      value
    )
  ) / BILLIONS
