# The final demand in the agriculture sector.

- unit = PJ
- query =
  SUM(
    V(
      FILTER(
          FILTER(
            EG(final_demand),"sector == :agriculture"
          ),
          energetic?
        ),
      value
    )
  ) / BILLIONS
