# Final demand of the 'natural_gas_and_derivatives' carrier group
# The last query accounts for the share of network gas in compressed network gas

- unit = PJ
- query = 
    SUM(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(
                EG(final_demand),"sector == :bunkers"), "natural_gas? || lng? || propane?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      PRODUCT(
        SUM(
          SUM(
            V(
              FILTER(
                FILTER( 
                  FILTER(
                    EG(final_demand),"sector == :bunkers"), "network_gas?"
                ),
                "energetic?"
              ),
              value
            )
          ),
          PRODUCT(
            SUM(
              V(
                FILTER(
                  FILTER(
                    FILTER(
                      EG(final_demand),"sector == :bunkers"), "compressed_network_gas?"
                  ),
                  "energetic?"
                ),
                value
              )
            ),
            Q(share_of_network_gas_in_compressed_network_gas)
          )
        ),
        Q(share_of_fossil_gas_in_gas_network)
      )
    ) / BILLIONS