# Final demand of the 'natural_gas_and_derivatives' carrier group
# The last query accounts for the share of network gas in compressed network gas

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :transport"), "network_gas? || compressed_network_gas? || natural_gas? || lng? || propane?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
