# Final demand of the 'solar' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          solar_radiation?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          solar_thermal?
        ),
        value
      )      
    ) / BILLIONS
