# Energetic final demand of the 'biomass_products' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              EG(final_demand), EG(ict_industry)
            ),
            energetic?
          ),
          "biodiesel? || bio_ethanol? || wood_pellets? || bio_lng? || bio_kerosene? || bio_oil?"
        ),
        value
      )
    ) / BILLIONS
    