# Final demand of the 'biomass_products' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          biodiesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          bio_ethanol?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          wood_pellets?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          bio_lng?
        ),
        value
      ),
      PRODUCT(
        SUM(
          V(
            FILTER(
              FILTER(
                FILTER(
                  EG(final_demand),"sector == :buildings"),"network_gas? || compressed_network_gas?"
                ),
              "energetic?"
              ),
            "value"
            )
          ) 
            ,
          Q(share_of_sustainable_gas_in_gas_network)
      )
    ) / BILLIONS
