# Selects the hydrogen input capacity of the hydrogen storage by taking the maximum value of the hourly input curve. Capacity of demand technologies is considered negative for the installed flexible capacities chart.

- query =
    PRODUCT(
      -1,
      MAX(
        V(
          FILTER(
            ALL(),
            "hydrogen && (hydrogen.type == :storage)"
          ),
          hydrogen_input_curve
        )
      )
    )
- unit = MW