# Selects the maximum value of the hourly hydrogen imbalance if it's a positive value, which indicates a shortage, else it returns 0.

- query =
    MAX(
      0,
      Q(
        hydrogen_imbalance_inflexible_curve
      )
    )
- unit = MW