# Selects the hydrogen output capacity of the hydrogen storage by taking the maximum value of the hourly output curve.

- query = V(energy_hydrogen_ammonia_reformer_dispatchable, "number_of_units * typical_input_capacity")
- unit = MW