# Final consumption of ammonia, all sectors (energetic use only).
#
# Sector:      All sectors
# Carrier:     Ammonia -- ammonia?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_energetic)
