# Final consumption from national transport, all carriers (non-energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     All carriers
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_from_national_transport_non_energetic)
