- deprecated_key = coal_in_dollar_per_tonne
# Price of coal in USD per tonne

- unit = $

PRODUCT(
              V(CARRIER(coal),"cost_per_mj * mj_per_kg"),
             KG_PER_TONNE,
             Q(dollar_per_euro)
             )