# Relative price of Biomass

- query =
    100.0 * DIVIDE(
      SUM(QUERY_FUTURE(-> {Q(price_of_wood_pellets)}), PRODUCT(-1,QUERY_PRESENT(-> {Q(price_of_wood_pellets)}))),
      QUERY_PRESENT(-> {Q(price_of_wood_pellets)}))

- unit = %
