# Relative price of oil

- query =
    100.0 * DIVIDE(
      SUM(QUERY_FUTURE(-> {Q(price_of_oil)}), PRODUCT(-1,QUERY_PRESENT(-> {Q(price_of_oil)}))),
      QUERY_PRESENT(-> {Q(price_of_oil)}))

- unit = %
