- query = 
		SUM(
			Q(agriculture_supply_chp_engine_biogas),
			Q(agriculture_supply_chp_wood_pellets),
			Q(agriculture_supply_chp_engine_dispatchable_network_gas),
			Q(agriculture_supply_chp_engine_must_run_network_gas),
			Q(agriculture_supply_backup_network_gas)
		)
