# Carrier costs based on net flows (imports - backup export - baseload export) of all related carriers
- query =
    SUM(
      PRODUCT(V(CARRIER(natural_gas), cost_per_mj), V(energy_extraction_natural_gas, demand)),
      PRODUCT(V(CARRIER(natural_gas), cost_per_mj), V(energy_import_natural_gas, demand)),
      PRODUCT(V(CARRIER(lng), cost_per_mj), V(energy_import_lng, demand)),
      PRODUCT(V(CARRIER(propane), cost_per_mj), V(energy_import_propane, demand))
    )
    -
    PRODUCT(V(CARRIER(natural_gas), cost_per_mj), V(energy_export_natural_gas_backup, demand))
    -
    SUM(
      PRODUCT(V(CARRIER(natural_gas), cost_per_mj), V(energy_export_natural_gas_baseload, demand)),
      PRODUCT(V(CARRIER(lng), cost_per_mj), V(energy_export_lng_baseload, demand))
    )

- unit = euro
