- query =
    SUM(
      PRODUCT(V(CARRIER(natural_gas), cost_per_mj), V(energy_export_network_gas, demand)),
      PRODUCT(V(CARRIER(lng), cost_per_mj), V(energy_export_lng, demand))
    )

- unit = euro
