- query =
    SUM(
      Q(costs_carriers_biomass),
      Q(costs_carriers_oil_and_products),
      Q(costs_carriers_coal_and_products),
      Q(costs_carriers_uranium),
      Q(costs_carriers_heat),
      Q(costs_carriers_natural_gas),
      Q(costs_carriers_waste),
      Q(costs_carriers_electricity),
      Q(costs_carriers_hydrogen_carriers),
      Q(costs_carriers_ammonia)
    )

- unit = euro
