- query =
    SUM(
      PRODUCT(V(CARRIER(dry_biomass), cost_per_mj), V(energy_production_dry_biomass, demand)),
      PRODUCT(V(CARRIER(wet_biomass), cost_per_mj), V(energy_production_wet_biomass, demand)),
      PRODUCT(V(CARRIER(oily_biomass), cost_per_mj), V(energy_production_oily_biomass, demand)),
      PRODUCT(V(CARRIER(wet_biomass), cost_per_mj), V(energy_import_wet_biomass, demand)),
      PRODUCT(V(CARRIER(dry_biomass), cost_per_mj), V(energy_import_dry_biomass, demand)),
      PRODUCT(V(CARRIER(oily_biomass), cost_per_mj), V(energy_import_oily_biomass, demand)),
      PRODUCT(V(CARRIER(bio_ethanol), cost_per_mj), V(energy_import_bio_ethanol, demand)),
      PRODUCT(V(CARRIER(bio_pyrolysis_oil), cost_per_mj), V(energy_import_bio_pyrolysis_oil, demand)),
      PRODUCT(V(CARRIER(bio_kerosene), cost_per_mj), V(energy_import_bio_kerosene, demand)),
      PRODUCT(V(CARRIER(biodiesel), cost_per_mj), V(energy_import_biodiesel, demand)),
      PRODUCT(V(CARRIER(biomethanol), cost_per_mj), V(energy_import_biomethanol, demand)),
      PRODUCT(V(CARRIER(bionaphtha), cost_per_mj), V(energy_import_bionaphtha, demand)),
    )
  - SUM(
      PRODUCT(V(CARRIER(greengas), cost_per_mj), V(energy_export_greengas_baseload, demand)),
      PRODUCT(V(CARRIER(greengas), cost_per_mj), V(energy_export_greengas_backup, demand)),
      PRODUCT(V(CARRIER(bio_kerosene), cost_per_mj), V(energy_export_bio_kerosene_baseload, demand)),
      PRODUCT(V(CARRIER(bio_kerosene), cost_per_mj), V(energy_export_bio_kerosene_backup, demand)),
      PRODUCT(V(CARRIER(biodiesel), cost_per_mj), V(energy_export_biodiesel_baseload, demand)),
      PRODUCT(V(CARRIER(biodiesel), cost_per_mj), V(energy_export_biodiesel_backup, demand)),
      PRODUCT(V(CARRIER(bio_ethanol), cost_per_mj), V(energy_export_bio_ethanol_baseload, demand)),
      PRODUCT(V(CARRIER(bio_ethanol), cost_per_mj), V(energy_export_bio_ethanol_backup, demand)),
      PRODUCT(V(CARRIER(bio_pyrolysis_oil), cost_per_mj), V(energy_export_bio_pyrolysis_oil_baseload, demand)),
      PRODUCT(V(CARRIER(bio_pyrolysis_oil), cost_per_mj), V(energy_export_bio_pyrolysis_oil_backup, demand)),
      PRODUCT(V(CARRIER(biomethanol), cost_per_mj), V(energy_export_biomethanol_baseload, demand)),
      PRODUCT(V(CARRIER(biomethanol), cost_per_mj), V(energy_export_biomethanol_backup, demand)),
      PRODUCT(V(CARRIER(bionaphtha), cost_per_mj), V(energy_export_bionaphtha_baseload, demand)),
      PRODUCT(V(CARRIER(bionaphtha), cost_per_mj), V(energy_export_bionaphtha_backup, demand)),
      )

- unit = euro
