- query =
    future:SUM(
      PRODUCT_CURVES(
        SUM_CURVES(
          INVERT_CURVE(V(energy_interconnector_1_exported_electricity, electricity_input_curve))
        ),
        Q(interconnector_1_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        SUM_CURVES(
          INVERT_CURVE(V(energy_interconnector_2_exported_electricity, electricity_input_curve))
        ),
        Q(interconnector_2_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        SUM_CURVES(
          INVERT_CURVE(V(energy_interconnector_3_exported_electricity, electricity_input_curve))
        ),
        Q(interconnector_3_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        SUM_CURVES(
          INVERT_CURVE(V(energy_interconnector_4_exported_electricity, electricity_input_curve))
        ),
        Q(interconnector_4_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        SUM_CURVES(
          INVERT_CURVE(V(energy_interconnector_5_exported_electricity, electricity_input_curve))
        ),
        Q(interconnector_5_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        SUM_CURVES(
          INVERT_CURVE(V(energy_interconnector_6_exported_electricity, electricity_input_curve))
        ),
        Q(interconnector_6_marginal_cost_curve)
      )
    )

- unit = euro
