- query =
    SUM(
      PRODUCT(V(CARRIER(hydrogen), cost_per_mj), V(energy_import_hydrogen, demand))
    )-
    SUM(
      PRODUCT(V(CARRIER(hydrogen), cost_per_mj), V(energy_export_hydrogen, demand))
    )

- unit = euro