# Carrier costs based on net flows (imports - backup export - baseload export)

- query =
    PRODUCT(V(CARRIER(ammonia), cost_per_mj), V(energy_import_ammonia, demand))
    -
    PRODUCT(V(CARRIER(ammonia), cost_per_mj), V(energy_export_ammonia_backup, demand))
    -
    PRODUCT(V(CARRIER(ammonia), cost_per_mj), V(energy_export_ammonia_baseload, demand))
- unit = euro
