- query =
    SUM(
      PRODUCT(V(CARRIER(natural_gas), cost_per_mj), V(energy_extraction_natural_gas, demand)),
      PRODUCT(V(CARRIER(natural_gas), cost_per_mj), V(energy_import_natural_gas, demand)),
      PRODUCT(V(CARRIER(lng), cost_per_mj), V(energy_import_lng, demand))
    )-
    SUM(
      PRODUCT(V(CARRIER(natural_gas), cost_per_mj), V(energy_export_natural_gas_backup, demand)),
      PRODUCT(V(CARRIER(lng), cost_per_mj), V(energy_export_lng_backup, demand))
    )

- unit = euro
