# Without electricity and heat

- query =
    SUM(
      PRODUCT(V(CARRIER(wet_biomass), cost_per_mj), V(energy_export_greengas, primary_demand_of_wet_biomass)),
      PRODUCT(V(CARRIER(dry_biomass), cost_per_mj), V(energy_export_greengas, primary_demand_of_dry_biomass)),
      PRODUCT(V(CARRIER(coal), cost_per_mj), V(energy_export_coal, demand)),
      PRODUCT(V(CARRIER(lignite), cost_per_mj), V(energy_export_lignite, demand)),
      PRODUCT(V(CARRIER(coal_gas), cost_per_mj), V(energy_export_coal_gas, demand)),
      PRODUCT(V(CARRIER(cokes), cost_per_mj), V(energy_export_cokes, demand)),
      PRODUCT(V(CARRIER(hydrogen), cost_per_mj), V(energy_export_hydrogen, demand)),
      PRODUCT(V(CARRIER(natural_gas), cost_per_mj), V(energy_export_network_gas, demand)),
      PRODUCT(V(CARRIER(lng), cost_per_mj), V(energy_export_lng, demand)),
      PRODUCT(V(CARRIER(crude_oil), cost_per_mj),V(energy_export_crude_oil, demand)),
      PRODUCT(V(CARRIER(crude_oil), cost_per_mj),V(energy_export_kerosene,primary_demand_of_crude_oil)),
      PRODUCT(V(CARRIER(crude_oil), cost_per_mj),V(energy_export_oil_products,primary_demand_of_crude_oil)),
      PRODUCT(V(CARRIER(crude_oil), cost_per_mj),V(energy_export_gasoline,primary_demand_of_crude_oil)),
      PRODUCT(V(CARRIER(crude_oil), cost_per_mj),V(energy_export_diesel,primary_demand_of_crude_oil)),
      PRODUCT(V(CARRIER(crude_oil), cost_per_mj),V(energy_export_lpg,primary_demand_of_crude_oil)),
      PRODUCT(V(CARRIER(crude_oil), cost_per_mj),V(energy_export_heavy_fuel_oil, primary_demand_of_crude_oil)),
      PRODUCT(V(CARRIER(uranium_oxide), cost_per_mj), V(energy_export_uranium_oxide, demand)),
      PRODUCT(V(CARRIER(non_biogenic_waste), cost_per_mj), V(energy_export_non_biogenic_waste, demand))
    )

- unit = euro
