- query =
    future:SUM(
      PRODUCT_CURVES(
        V(energy_interconnector_1_imported_electricity, electricity_output_curve),
        Q(interconnector_1_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        V(energy_interconnector_2_imported_electricity, electricity_output_curve),
        Q(interconnector_2_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        V(energy_interconnector_3_imported_electricity, electricity_output_curve),
        Q(interconnector_3_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        V(energy_interconnector_4_imported_electricity, electricity_output_curve),
        Q(interconnector_4_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        V(energy_interconnector_5_imported_electricity, electricity_output_curve),
        Q(interconnector_5_marginal_cost_curve)
      ),
      PRODUCT_CURVES(
        V(energy_interconnector_6_imported_electricity, electricity_output_curve),
        Q(interconnector_6_marginal_cost_curve)
      )
    )-
    PRODUCT(
      V(energy_export_electricity, weighted_carrier_cost_per_mj),
      V(energy_export_electricity, demand)
    )

- unit = euro
