- query =
    SUM(
      PRODUCT(V(CARRIER(wet_biomass), cost_per_mj), V(energy_export_greengas, primary_demand_of_wet_biomass)),
      PRODUCT(V(CARRIER(dry_biomass), cost_per_mj), V(energy_export_greengas, primary_demand_of_dry_biomass))
    )

- unit = euro
