# Carrier costs based on net flows (imports - backup export)

- query =
    PRODUCT(V(CARRIER(methanol), cost_per_mj), V(energy_import_methanol, demand))
    -
    SUM(
        PRODUCT(V(CARRIER(methanol), cost_per_mj), V(energy_export_methanol_backup, demand)),
        PRODUCT(V(CARRIER(methanol), cost_per_mj), V(energy_export_methanol_baseload, demand))
    )    
- unit = euro
