- query =
    SUM(
      PRODUCT(V(CARRIER(imported_liquid_hydrogen), cost_per_mj), V(energy_import_liquid_hydrogen, demand)),
      Q(costs_carriers_export_liquid_hydrogen_baseload)
    )
- unit = euro