- query =
    SUM(
      V(
        energy_hydrogen_flexibility_p2g_electricity,
        energy_hydrogen_electrolysis_wind_electricity,
        energy_hydrogen_electrolysis_solar_electricity,
        "number_of_units * typical_input_capacity"
      )
    )

- unit = MW
