- query =
  {
    capacity:        Q(merit_order_battery_wind_inland_capacity_in_merit_order_table),
    availability:    Q(merit_order_battery_wind_inland_availability_in_merit_order_table),
    full_load_hours: Q(merit_order_battery_wind_inland_full_load_hours_in_merit_order_table),
    load_factor:     Q(merit_order_battery_wind_inland_load_factor_in_merit_order_table),
    operating_costs: Q(merit_order_battery_wind_inland_operating_costs_in_merit_order_table),
    position:        Q(merit_order_battery_wind_inland_position_in_merit_order_table)
  }