- query =
  {
    capacity:        Q(merit_order_coal_chp_capacity_in_merit_order_table),
    full_load_hours: Q(merit_order_coal_chp_full_load_hours_in_merit_order_table),
    load_factor:     Q(merit_order_coal_chp_load_factor_in_merit_order_table),
    operating_costs: Q(merit_order_coal_chp_operating_costs_in_merit_order_table),
    position:        Q(merit_order_coal_chp_position_in_merit_order_table)
  }
