- query =
  {
    capacity:        Q(merit_order_lignite_oxy_capacity_in_merit_order_table),
    full_load_hours: Q(merit_order_lignite_oxy_full_load_hours_in_merit_order_table),
    load_factor:     Q(merit_order_lignite_oxy_load_factor_in_merit_order_table),
    operating_costs: Q(merit_order_lignite_oxy_operating_costs_in_merit_order_table),
    position:        Q(merit_order_lignite_oxy_position_in_merit_order_table)
  }
