# Availability of 'energy_interconnector_9_imported_electricity' in merit order table

- unit = Percentage
- query =
    V(
      energy_interconnector_9_imported_electricity,
      "availability * 100"
    )
