# Full load hours of 'energy_interconnector_1_imported_electricity' in merit order table

- unit = hours
- query =
    V(
      energy_interconnector_1_imported_electricity,
      "demand / electricity_output_capacity / MJ_PER_MWH"
    )

