# Capacity factor of 'energy_interconnector_1_imported_electricity' in merit order table

- unit = factor
- query =
    AVG(
      V(
        GROUP(electricity_interconnectors_import),
        "full_load_hours / HOURS_PER_YEAR"
      )
    )
