# Hmmmm....

- query =
    DIVIDE(
      SUM(V(households_solar_pv_solar_radiation, energy_power_solar_pv_solar_radiation, energy_power_solar_csp_solar_radiation, buildings_solar_pv_solar_radiation," installed_production_capacity_in_mw_electricity * full_load_hours / HOURS_PER_YEAR")),
      SUM(V(households_solar_pv_solar_radiation, energy_power_solar_pv_solar_radiation, energy_power_solar_csp_solar_radiation, buildings_solar_pv_solar_radiation," installed_production_capacity_in_mw_electricity"))
    )
- unit = factor
