#


- unit = EUR

DIVIDE(
    SUM(V(G(must_run_electricity_production)," variable_costs_per(mwh_input)/electricity_output_conversion*installed_production_capacity_in_mw_electricity")),
    SUM(V(G(must_run_electricity_production), installed_production_capacity_in_mw_electricity))
)