- query =
    DIVIDE(
        SUM(V(energy_power_wind_turbine_inland, energy_power_wind_turbine_coastal, energy_power_wind_turbine_offshore," full_load_hours*installed_production_capacity_in_mw_electricity")),
        SUM(V(energy_power_wind_turbine_inland, energy_power_wind_turbine_coastal, energy_power_wind_turbine_offshore, installed_production_capacity_in_mw_electricity))
    )
- unit = hours
