# Full load hours of 'energy_interconnector_7_imported_electricity' in merit order table

- unit = hours
- query =
    V(
      energy_interconnector_7_imported_electricity,
      "full_load_hours"
    )
