# Capacity factor of 'energy_interconnector_11_imported_electricity' in merit order table

- unit = factor
- query =
    V(
      energy_interconnector_11_imported_electricity,
      "full_load_hours / HOURS_PER_YEAR"
    )
