# Hmmmm....

- query =
    DIVIDE(
      SUM(V(energy_power_wind_turbine_inland, energy_power_wind_turbine_coastal, energy_power_wind_turbine_offshore," installed_production_capacity_in_mw_electricity * full_load_hours / HOURS_PER_YEAR")),
      SUM(V(energy_power_wind_turbine_inland, energy_power_wind_turbine_coastal, energy_power_wind_turbine_offshore," installed_production_capacity_in_mw_electricity"))
    )
- unit = factor
