- query =
    DIVIDE(
        SUM(V(G(must_run_electricity_production)," full_load_hours*installed_production_capacity_in_mw_electricity")),
        SUM(V(G(must_run_electricity_production), installed_production_capacity_in_mw_electricity))
    )
- unit = hours
