# Installed capacity of 'energy_interconnector_11_imported_electricity' in merit order table

- unit = MW
- query =
    V(
      energy_interconnector_11_imported_electricity,
      installed_production_capacity_in_mw_electricity
    )
