- query =
  {
    capacity:        Q(merit_order_nuclear_iii_capacity_in_merit_order_table),
    full_load_hours: Q(merit_order_nuclear_iii_full_load_hours_in_merit_order_table),
    load_factor:     Q(merit_order_nuclear_iii_load_factor_in_merit_order_table),
    operating_costs: Q(merit_order_nuclear_iii_operating_costs_in_merit_order_table),
    position:        Q(merit_order_nuclear_iii_position_in_merit_order_table)
  }
