- query =
    SUM(
      Q(central_heat_prod_to_households_in_sankey),
      Q(central_heat_prod_to_buildings_in_sankey),
      Q(central_heat_prod_to_transport_in_sankey),
      Q(central_heat_prod_to_industry_in_sankey),
      Q(central_heat_prod_to_feedstock_in_sankey),
      Q(central_heat_prod_to_agriculture_in_sankey),
      Q(central_heat_prod_to_energy_in_sankey),
      Q(central_heat_prod_to_other_in_sankey),
      Q(central_heat_prod_excl_p2h_to_conversion_loss_in_sankey),
      Q(central_heat_prod_to_transport_loss_in_sankey)
    )
- unit = PJ
