# Excluded are Q(geothermal_for_central_heat_conversion) and Q(ambient_for_central_heat_conversion), see quintel/etmodel#3641

- query =
    SUM(
      Q(import_for_central_heat_conversion),
      Q(solar_for_central_heat_conversion)
    )
- unit = PJ
