- query =
    SUM(
      Q(import_for_central_heat_conversion),
      Q(geothermal_for_central_heat_conversion),
      Q(ambient_for_central_heat_conversion),
      Q(solar_for_central_heat_conversion)
    )
- unit = PJ
