- query =
    SUM(
      Q(coal_and_derivatives_to_central_heat_prod_in_sankey),
      Q(oil_and_derivatives_to_central_heat_prod_in_sankey),
      Q(natural_gas_to_central_heat_prod_in_sankey),
      Q(solar_to_central_heat_prod_in_sankey),
      Q(wind_to_central_heat_prod_in_sankey),
      Q(biomass_products_to_central_heat_prod_in_sankey),
      Q(geo_ambient_to_central_heat_prod_excl_p2h_in_sankey),
      Q(imported_heat_to_central_heat_prod_in_sankey),
      Q(nuclear_to_central_heat_prod_in_sankey),
      Q(water_to_central_heat_prod_in_sankey),
      Q(solar_to_central_heat_prod_in_sankey),
      Q(electricity_prod_to_central_heat_prod_excl_p2h_in_sankey),
      Q(hydrogen_prod_to_central_heat_prod_in_sankey),
      Q(p2h_central_heat_to_central_heat_in_sankey)
    )
