- query =
    SUM(
      V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater, demand),
      V(households_useful_demand_for_hot_water_after_solar_heater, demand)
    ) / BILLIONS
- unit = PJ
