- query =
    V(
      LINK(
        households_water_heater_hybrid_heatpump_air_water_electricity_aggregator,
        households_water_heater_deficit
      ),
      value
    ) / BILLIONS
- unit = PJ
