# The order in which the producers in buildings space heating are solved
- buildings_space_heater_district_heating_lt_steam_hot_water
- buildings_space_heater_heatpump_surface_water_water_ts_electricity
- buildings_space_heater_heatpump_air_water_electricity
- buildings_space_heater_heatpump_air_water_network_gas
- buildings_space_heater_district_heating_mt_steam_hot_water
- buildings_space_heater_collective_heatpump_water_water_ts_electricity
- buildings_space_heater_hybrid_heatpump_air_water_electricity
- buildings_space_heater_hybrid_hydrogen_heatpump_air_water_electricity
- buildings_space_heater_district_heating_ht_steam_hot_water
- buildings_space_heater_electricity
- buildings_space_heater_network_gas
- buildings_space_heater_combined_hydrogen
- buildings_space_heater_wood_pellets
- buildings_space_heater_coal
- buildings_space_heater_crude_oil
