# The order in which the consumers in buidlings space heating are solved
- buildings_useful_demand_for_space_heating_buildings_future_after_solar_thermal
- buildings_useful_demand_for_space_heating_buildings_present_after_solar_thermal
