# The order in which the producers in household hot water are solved
- households_water_heater_district_heating_lt_steam_hot_water
- households_water_heater_heatpump_air_water_electricity
- households_water_heater_heatpump_ground_water_electricity
- households_water_heater_heatpump_pvt_electricity
- households_water_heater_district_heating_mt_steam_hot_water
- households_water_heater_hybrid_heatpump_air_water_electricity
- households_water_heater_hybrid_hydrogen_heatpump_air_water_electricity
- households_water_heater_district_heating_ht_steam_hot_water
- households_water_heater_resistive_electricity
- households_water_heater_combined_network_gas
- households_water_heater_combined_hydrogen
- households_water_heater_wood_pellets
- households_water_heater_network_gas
- households_water_heater_coal
- households_water_heater_crude_oil
