# The order in which the producers in household space heating are solved
- households_space_heater_district_heating_lt_steam_hot_water
- households_space_heater_heatpump_surface_water_water_ts_electricity
- households_space_heater_heatpump_air_water_electricity
- households_space_heater_heatpump_ground_water_electricity
- households_space_heater_heatpump_pvt_electricity
- households_space_heater_district_heating_mt_steam_hot_water
- households_space_heater_hybrid_heatpump_air_water_electricity
- households_space_heater_hybrid_hydrogen_heatpump_air_water_electricity
- households_space_heater_district_heating_ht_steam_hot_water
- households_space_heater_electricity
- households_space_heater_combined_network_gas
- households_space_heater_combined_hydrogen
- households_space_heater_wood_pellets
- households_space_heater_network_gas
- households_space_heater_coal
- households_space_heater_crude_oil
