# The order in which the consumers in household space heating are solved
- households_useful_demand_for_space_heating_apartments_future
- households_useful_demand_for_space_heating_terraced_houses_future
- households_useful_demand_for_space_heating_semi_detached_houses_future
- households_useful_demand_for_space_heating_detached_houses_future
- households_useful_demand_for_space_heating_apartments_2005_present
- households_useful_demand_for_space_heating_terraced_houses_2005_present
- households_useful_demand_for_space_heating_semi_detached_houses_2005_present
- households_useful_demand_for_space_heating_detached_houses_2005_present
- households_useful_demand_for_space_heating_apartments_1985_2004
- households_useful_demand_for_space_heating_terraced_houses_1985_2004
- households_useful_demand_for_space_heating_semi_detached_houses_1985_2004
- households_useful_demand_for_space_heating_detached_houses_1985_2004
- households_useful_demand_for_space_heating_apartments_1965_1984
- households_useful_demand_for_space_heating_terraced_houses_1965_1984
- households_useful_demand_for_space_heating_semi_detached_houses_1965_1984
- households_useful_demand_for_space_heating_detached_houses_1965_1984
- households_useful_demand_for_space_heating_apartments_1945_1964
- households_useful_demand_for_space_heating_terraced_houses_1945_1964
- households_useful_demand_for_space_heating_semi_detached_houses_1945_1964
- households_useful_demand_for_space_heating_detached_houses_1945_1964
- households_useful_demand_for_space_heating_apartments_before_1945
- households_useful_demand_for_space_heating_terraced_houses_before_1945
- households_useful_demand_for_space_heating_semi_detached_houses_before_1945
- households_useful_demand_for_space_heating_detached_houses_before_1945
