# The capacity of the the low voltage net in the present. The 0.000001 is to prevent it from breaking, when spare capacity is 100%.

- query =
          IF(
              AREA(lv_mv_trafo_spare_capacity) >= 1.0,
              0.0,
              QUERY_PRESENT(lv_mv_trafo_peak_load_present) / (1.0 - AREA(lv_mv_trafo_spare_capacity))
            )

- unit = MW
