# The extra needed capacity is the delta (difference) between the present capacity of the net and the peak load in the future scenario. The difference is the extra needed capacity.

- query = Q(lv_mv_trafo_peak_load_future) - Q(lv_mv_trafo_capacity_present)

- unit = MW
