- query =
    SUM(
      Q(heat_infrastructure_households_ht_indoor_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_buildings_ht_indoor_fixed_operation_and_maintenance_costs)
    )
- unit = euro