# 

- deprecated_key = ambient_heat_in_source_of_heat_used_in_households
- unit = pj

DIVIDE(PRODUCT(Q(share_of_ambient_heat_in_heat_produced_in_households),V(heating_demand_households_energetic,demand)),BILLIONS)