# 

- deprecated_key = ambient_heat_used_for_hot_water_in_households
- unit = mj

SUM(
V(Q(hot_water_converters_in_households);"input_of_ambient_heat + input_of_solar_thermal + input_of_solar_radiation")
)
