# 

- deprecated_key = buildings_primary_demand_without_gas
- unit = mj

SUM(
Q(buildings_biomass_primary_demand),
Q(buildings_oil_primary_demand),
Q(buildings_uranium_primary_demand),
Q(buildings_coal_primary_demand),
Q(buildings_lignite_primary_demand),
Q(buildings_waste_primary_demand),
Q(buildings_non_e_primary_demand),
Q(buildings_imported_e_primary_demand)
)