# 

- deprecated_key = centrally_produced_electricity_households
- unit = mj

SUM(
  V(households_final_demand_electricity,demand),
  NEG( SUM(V(households_solar_pv_solar_radiation,households_collective_chp_network_gas,households_collective_chp_wood_pellets,output_of_electricity)
  )
 ),
NEG(V(households_final_demand_electricity,electricity_inversedflexible_output_link_value))
)
