- deprecated_key = co2_emission_industry
# 

- unit = kg

   SUM(V (
   INTERSECTION(
        USE(energetic),
        INTERSECTION(SECTOR(industry),GROUP(final_demand_cbs) )
        )
       ;primary_co2_emission)
   )