- deprecated_key = costs_per_mj_electricity_from_coal
# This returns the costs in euro per MJ electricity produced by coal plants

- unit = euro

IF(
   EQUALS(
    SUM(V( Q(electricity_producing_converters_coal), output_of_electricity)),0,),
    0,
    DIVIDE(
     SUM(V( Q(electricity_producing_converters_coal), total_costs_per(converter) )),
     SUM(V( Q(electricity_producing_converters_coal), output_of_electricity ))
     )
  )
