- deprecated_key = cost_motion_detection
# Cost of extra motion detection, compared to the position now. This query has to be updated when the current situation changes.

- unit = euro

PRODUCT(MAX(SUM(V(motion_detection_savings_buildings_energetic;light_output_link_share),NEG(V(0.039))),0),
V(motion_detection_savings_buildings_energetic;"total_cost_per_mj * demand"))