- deprecated_key = cost_daylight_control
# cost of extra daylight saving, compared to the position now.
# THis query has to be updated when the current situation changes.

- unit = euro

PRODUCT(MAX(SUM(V(daylight_control_savings_buildings_energetic;light_output_link_share),NEG(V(0.0529669))),0),
V(daylight_control_savings_buildings_energetic;total_cost_per_mj * demand))