- deprecated_key = costs_heating_households
# The total costs for household heating. Only electricity costs and steam/hot water costs are excluded.

- unit = euro

SUM(V(INTERSECTION(SECTOR(households), V( G(heat_production),G(decentral_production))),total_costs))