- deprecated_key = cost_daylight_control
# cost of extra daylight saving, compared to the position now.
# THis query has to be updated when the current situation changes.

- unit = euro

PRODUCT(MAX(SUM(V(buildings_lighting_savings_from_daylight_control_light,light_output_link_share),NEG(V(0.0529669))),0),
V(buildings_lighting_savings_from_daylight_control_light,"total_cost_per_mj * demand"))
