# 

- deprecated_key = decentral_electricity_production
- unit = converters

V(
  local_solar_pv_grid_connected_energy_energetic,
  chp_other_other_energetic,
  chp_agri_agriculture_energetic,
  solar_pv_central_production_energy_energetic,
  biomass_chp_industry_energetic,
  waste_incinerator_energy_energetic,
  bio_oil_chp_industry_energetic,
  wind_inland_energy,
  wind_coastal_energy,
  solar_csp_energy,
  hydro_river_energy,
  geothermal_electricity_energy,
  solar_panels_buildings_energetic,
  gas_chp_buildings_energetic,
  coal_chp_buildings_energetic,
  biomass_chp_buildings_energetic,
  micro_CHP_production_households,
  small_chp_industry_energetic
)


  



