# 

- unit = factor

DIVIDE(  
            SUM(            
                    V(energy_import_electricity,demand)
                  , V(energy_export_electricity,demand)),
             SUM(V(G(primary_energy_demand),demand)))
