- deprecated_key = electricity_from_wind
# All electricity made by wind turbines in the area.
# 
# not dynamic!

- unit = mj

SUM
(
 V(
  wind_inland_energy,
  wind_coastal_energy,
  wind_offshore_energy,
   output_of_electricity
  )
)