- deprecated_key = electricity_produced_from_waste
# Returns the produced electricity using waste.
# 
# It works by looking to waste converters.

- unit = mj

SUM(
  V(
     Q(electricity_producing_converters_waste)
     ;output_of_electricity    )
   )


