- deprecated_key = electricity_produced_from_geothermal
# Returns the produced electricity using geothermal heat.
# 
# It works by looking to geothermal converters.

- unit = mj

SUM(
  V(
     Q(electricity_producing_converters_geothermal)
     ;output_of_electricity    )
   )


