# 

- deprecated_key = electric_heatpumps
- unit = converters

V(
buildings_space_heater_collective_heatpump_water_water_ts_electricity,
agriculture_heatpump_water_water_ts_electricity,
households_space_heater_heatpump_air_water_electricity,
households_space_heater_heatpump_ground_water_electricity,
households_water_heater_heatpump_ground_water_electricity,
households_space_heater_heatpump_add_on_electricity,
households_cooling_heatpump_ground_water_electricity,
households_cooling_heatpump_air_water_electricity,
buildings_cooling_collective_heatpump_water_water_ts_electricity
)
