- deprecated_key = electricity_producing_converters_coalbiomasslignite
# Returns the converters which produce electricity using coal, lignite, or biomass.
# 
# It works by looking to converters directly fed by the "Coal distribution", "Lignite distribution" and "Biomass distribution" converters that have output of electricity.

- unit = converters

V(
  FILTER(
    V(
      PARENTS(V(coal_distribution_energy)),
      PARENTS(V(biomass_distribution_energy)),
      PARENTS(V(lignite_distribution_energy))
      )
   ;electricity_output_conversion && electricity_output_conversion > 0)
  )