- deprecated_key = electricity_from_solar
# All electricity made by solar panels in the area.
# 
# These panels are defined in electricity_producing_converters_solar

- unit = mj

SUM
(
 V(Q(electricity_producing_converters_solar);
   output_of_electricity
  )
)