- deprecated_key = final_sustainable_demand
# Total final demand sustainable fuels
# 
# *update 28-10-2010: This is now only calculated over the energetic final demand.

- unit = mj

SUM(
         V(
             INTERSECTION(G(final_demand_cbs),USE(energetic));
                 output_of_wood_pellets +
output_of_greengas +
output_of_biodiesel +
output_of_bio_ethanol +
output_of_bio_oil +
output_of_water +
output_of_algae_diesel +
output_of_biogas 
))