- deprecated_key = final_sustainable_steam
# The total amount of steam hot water that is produced sustainably. This is used in the renewables percentage.

- unit = mj

SUM(INVALID_TO_ZERO(V(INTERSECTION(G(final_demand_cbs),USE(energetic));" input_of_steam_hot_water * primary_demand_of_sustainable / primary_demand")))