# 

- deprecated_key = fossil_heat_old
- unit = mj

SUM(
  V(
    micro_chp_space_heating_households,
    central_heating_households_energetic,
    heater_on_coal_households_energetic,
    heater_on_oil_households_energetic,
    cv_hot_water_households_energetic,
    heatpump_boiler_using_city_heat_households_energetic;output_of_heat_carriers
  ),
  NEG(V(heatpump_boiler_using_city_heat_households_energetic;input_of_electricity))
)