- deprecated_key = gas_plants_temporary_withouth_chp
# small_chp_industry_energetic removed so that it works with the supply table

- unit = converters

V(
  gas_conv_energy_energetic,
  gas_ccgt_energy,
  large_chp_industry_energetic,
  micro_chp_households_energetic
)
  