- deprecated_key = hot_water_from_biomass_in_source_of_hot_water_in_households
# 

- unit = pj

DIVIDE(PRODUCT(DIVIDE(Q(biomass_derivatives_used_for_hot_water_in_households),Q(energy_used_for_hot_water_in_households)),V(hot_water_demand_households_energetic;input_of_hot_water)),BILLIONS)