- deprecated_key = households_m3_gas_use_per_household
# This returns the household gas use in m3 per year, including that of the micro-CHP.

- unit = m3

DIVIDE(SUM(V(V(INTERSECTION(G(final_demand_cbs),SECTOR(households))), V(V(micro_chp_hot_water_households_energetic),V(micro_CHP_production_households));input_of_network_gas / 3517 * 100 )),AREA(number_households))