- deprecated_key = households_other_energy_use_per_households
# The household energy use besides gas and electricity, in GJ per year per household. Energy used by the micro-CHP is deducted, as this is added with gas use.

- unit = 

DIVIDE(DIVIDE(
     SUM(V(EXCLUDE(INTERSECTION(G(final_demand_cbs),SECTOR(households)),

    V(local_solar_pv_not_grid_connected_households_energetic,            electricity_households_energetic,gas_households_energetic ));demand),NEG(SUM(

    V(Q(micro_chp);output_of_steam_hot_water))

))

,AREA(number_households)),1000)