- deprecated_key = industry_percentage_energy_use_of_total
# 

- unit = factor

DIVIDE(
SUM(V(INTERSECTION(G(final_demand_cbs),SECTOR(industry)),final_demand)),
SUM(V(G(final_demand_cbs),final_demand))
)