- deprecated_key = max_percentage_heat_network_industry
# The maximum share the heat network can supply of the industry heat demand, capped by 100%
# 
# OLD:
# MIN(
#   1,
#   DIVIDE(
#      V(steam_hot_water_industry_energetic,demand)
#      ,
#      V(heating_demand_industry_energetic,demand)
#      )
#    )

- unit = factor

MIN(
  1,
  DIVIDE(
     SUM(V(small_chp_industry_energetic,central_gas_chp_energy_energetic,biomass_chp_industry_energetic,output_of_steam_hot_water))
     ,
     V(heating_demand_industry_energetic,demand)
     )
   )