- deprecated_key = other_share_of_heating_demand_households_energetic
# gets the combined share of the converters that are not a slider

- unit = factor

SUM(V(heater_on_oil_households_energetic,heater_on_coal_households_energetic,heater_on_oil_households_energetic,share_of_heating_demand_households_energetic))
