- deprecated_key = other_share_of_households_useful_demand_for_space_heating_after_insulation_solar_heater_and_add_on
# gets the combined share of the converters that are not a slider

- unit = factor

SUM(V(households_space_heater_crude_oil,households_space_heater_coal,households_space_heater_crude_oil,share_of_households_useful_demand_for_space_heating_after_insulation_solar_heater_and_add_on))
