- deprecated_key = percentage_sustainable_electricity_of_final_demand
# Not looking at production, but at the final demand, showing the percentage of sustainable electricity. (the difference being is that sustainability of electricity import is considered here)

- unit = factor

DIVIDE(
       SUM(V(G(final_demand_cbs);output_of_electricity * sustainability_share))
       ,
       SUM(V(G(final_demand_cbs);output_of_electricity))
      )