# Score calculated for etflex.
# It is 1000, minus costs in billions, minus CO2 emissions in Mton. This number is divided by 2 if there is 100% loss_of_load, and multiplied the % imbalance in electricity production
#
# Old name still used in old maintenance_nls

- deprecated_key = score
- unit = #

Q(etflex_score)