# Score calculated for et
# TODO: make it dependent on Security of Supply and Electricity Balance
# 
# Still used in old scenarios

- deprecated_key = score
- unit = #

SUM (
  1000,
  NEG( DIVIDE( Q(total_costs), BILLIONS )),
  NEG( DIVIDE( Q(total_co2_emissions), BILLIONS ))
)