- deprecated_key = share_domestic_electrity_production
# 

- unit = factor

MIN(1,
 SUM(
   1,
   NEG(
     DIVIDE( 
     V(interconnection_energy,demand),
     V(hv_electricity_network_energy,demand))
     )
  ))