- deprecated_key = share_of_ambient_heat_in_heat_produced_in_households
# The share of ambient heat (+geothermal) in the supply of household heat demand

- unit = factor

DIVIDE(
SUM(V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation)),"input_of_ambient_heat + input_of_solar_radiation"),V(households_collective_geothermal,demand))
,
SUM(V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation)),demand))
)
