# 

- deprecated_key = share_of_combi_hot_water_options
- unit = factor

SUM(
	V(households_water_heater_combined_network_gas,
	households_water_heater_heatpump_air_water_electricity,
	households_water_heater_micro_chp_network_gas,
	households_water_heater_district_heating_steam_hot_water
	,
	share_of_households_water_heater_excluding_solar_panel_hot_water)
)
