- deprecated_key = share_of_heaters_with_combi
# Removed the collective and coal/oil heaters

- unit = factor

SUM(
V(
households_space_heater_wood_pellets,
households_space_heater_combined_network_gas,
households_space_heater_heatpump_ground_water_electricity,
share_of_heating_demand_households_energetic
),
SUM(
PRODUCT(
V(households_space_heater_micro_chp_network_gas,share_of_heat_from_steam_hot_water_households_energetic),
V(households_space_heater_district_heating_steam_hot_water,share_of_heating_demand_households_energetic)),
PRODUCT(
V(households_heat_network_connection_steam_hot_water,share_of_heat_from_steam_hot_water_households_energetic),
V(households_space_heater_district_heating_steam_hot_water,share_of_heating_demand_households_energetic)
)
)
)
