- deprecated_key = share_of_heaters_with_combi
# Removed the collective and coal/oil heaters

- unit = factor

SUM(
V(
heater_on_biomass_households_energetic,
central_heating_households_energetic,
heatpump_households_energetic;
share_of_heating_demand_households_energetic
),
SUM(
PRODUCT(
V(micro_chp_space_heating_households;share_of_heat_from_steam_hot_water_households_energetic),
V(heat_from_steam_hot_water_households_energetic;share_of_heating_demand_households_energetic)),
PRODUCT(
V(city_heating_network_energy_energetic;share_of_heat_from_steam_hot_water_households_energetic),
V(heat_from_steam_hot_water_households_energetic;share_of_heating_demand_households_energetic)
)
)
)
