# 

- deprecated_key = share_of_combi_hot_water_options
- unit = factor

SUM(
	V(cv_hot_water_households_energetic,
	heatpump_boiler_households_energetic,
	micro_chp_hot_water_households_energetic,
	heatpump_boiler_using_city_heat_households_energetic
	;
	share_of_hot_water_devices_households_energetic)
)
