# 

- deprecated_key = start_value_small_chp_industry
- unit = factor

PRODUCT(DIVIDE(V(small_chp_industry_energetic;share_of_steam_hot_water_industry_energetic),Q(total_share_industry_chps)),V(steam_hot_water_demand_industry;share_of_heating_demand_industry_energetic))
