# 
- deprecated_key = start_value_large_chp_industry
- unit = factor

PRODUCT(DIVIDE(V(energy_chp_combined_cycle_bio_oil,share_of_industry_final_demand_steam_hot_water),Q(total_share_industry_chps)),V(steam_hot_water_demand_industry,share_of_industry_useful_demand_useable_heat))
