- deprecated_key = sustainability_heat_production
# 

- unit = mj

DIVIDE(
  SUM(V( G(heat_production)," useful_output * demand * sustainable_input_factor")),
  SUM(V( G(heat_production)," useful_output * demand"))
)