# The biomass used in the agriculture sector, plus the sustainable part of the fossil fuels.

- deprecated_key = sustainable_heat_agri
- unit = mj

SUM(
V(agriculture_burner_wood_pellets,output_of_useable_heat),
V(agriculture_burner_network_gas,"output_of_heat_carriers * sustainability_share")
)
