# The biomass used in the agriculture sector, plus the sustainable part of the fossil fuels.

- deprecated_key = sustainable_heat_agri
- unit = mj

SUM(
V(biomass_burner_agri_agriculture_energetic;output_of_useable_heat),
V(gas_burner_agri_agriculture_energetic;"output_of_heat_carriers * sustainability_share")
)