# Added sustainable to allow future deviations of 1

- deprecated_key = total_cost_of_primary_bio_oil
- unit = euro

PRODUCT(
  SUM(
    V(G(final_demand_cbs); primary_demand_of_bio_oil)
  )
  ,
  V(CARRIER(bio_oil);cost_per_mj * sustainable)
)