# 

- deprecated_key = total_cost_of_primary_renewable
- unit = euro

SUM(
  Q(total_cost_of_primary_biomass),
  Q(total_cost_of_primary_greengas),
  Q(total_cost_of_primary_biodiesel),
  Q(total_cost_of_primary_bio_ethanol),
  Q(total_cost_of_primary_waste),
  Q(total_cost_of_primary_bio_oil),
  Q(total_cost_of_primary_algae_diesel),
  Q(total_cost_of_primary_biogas)
)


