# Added sustainable to allow future deviations of 1

- deprecated_key = total_cost_of_primary_greengas
- unit = euro

PRODUCT(
  SUM(
    V(G(final_demand_cbs); primary_demand_of_greengas)
  )
  ,
  V(CARRIER(greengas);cost_per_mj * sustainable)
)