# used in hack for inversed flexible bug

- deprecated_key = total_share_industry_chps
- unit = factor

SUM(
V(small_chp_industry_energetic,share_of_steam_hot_water_industry_energetic),
V(central_gas_chp_energy_energetic,share_of_steam_hot_water_industry_energetic),
V(biomass_chp_industry_energetic,share_of_steam_hot_water_industry_energetic),
)