- unit = MT
- query =
    DIVIDE(
      SUM(
        V(
          SECTOR(emissions_sector, "Energy"),
          direct_reporting_emissions_total_ghg_emissions
        ),
        MV(
          MSECTOR(emissions_sector, "Energy"),
          direct_reporting_emissions_total_ghg_emissions
        )
      ),
      BILLIONS
    )
