# peak_load_capacity_delta_for_mv_hv calculates delta unit number of plants (future - present)

- unit = mw

SUM(
    V(Q(units_connected_to_mv_hv_transformer)," peak_load_capacity_delta_for_mv_hv * simult_sd")
)