
# 

- unit = mw

SUM(
  PRODUCT(
    Q(peak_load_delta_supply_mv_distribution_net),
    V(energy_power_mv_distribution_network_electricity , simult_wd),
    V(energy_power_mv_transport_network_electricity , simult_wd)
    ),
  Q(peak_load_delta_on_mv_hv_transformer)
)
