- query = 
    SUM(
        Q(emissions_captured_industry_chemicals_fertilizers),
        Q(emissions_captured_industry_other),
        Q(emissions_captured_industry_other_food),
        Q(emissions_captured_industry_other_paper),
        Q(emissions_captured_industry_chemicals_refineries),
        Q(emissions_captured_industry_chemicals_other),
        Q(emissions_captured_industry_steel)
    )
- unit = tonne