- query =
    IF(
      GRAPH().future?,
      -> {
        GROUP(dispatchable_production).each_with_object({}){ |c,h|
          h[c.key] = {
            :profitability => c.node_api.profitability,
            :full_load_hours => c.node_api.full_load_hours,
            :position => c.node_api.merit_order_position,
            :capacity => c.node_api.input_capacity *
                        c.node_api.electricity_output_conversion *
                        c.node_api.number_of_units,
            :availability=> c.node_api.availability * 100,
            :profit_per_mwh_electricity => c.node_api.profit_per_mwh_electricity
          }
        }
      },
      -> { {} }
    )

- unit = hash
