- query =
    GROUP(merit_order_converters_for_dashboard).each_with_object({}){ |c,h|
      h[c.key] = {
        :profitability => c.converter_api.profitability,
        :full_load_hours => c.converter_api.full_load_hours,
        :position => c.converter_api.merit_order_position,
        :capacity => c.converter_api.input_capacity *
                     c.converter_api.electricity_output_conversion *
                     c.converter_api.number_of_units,
        :availability=> c.converter_api.availability * 100,
        :profit_per_mwh_electricity => c.converter_api.profit_per_mwh_electricity
      }
    }
- unit = hash
