# The total costs divided by the number of households. This calculates the yearly energy cost per household (so including energy costs for transport and industry!)

- query = DIVIDE(Q(total_costs),AREA(number_of_residences))
- unit = euro
