# Share of foreign and imported biomass demand (in total biomass demand)
#
# (import of biomass - export of biomass) / final demand of biomass

- unit = factor
- query =
    DIVIDE(
      SUM(
        Q(import_of_biomass_products),
        NEG(
          Q(export_of_biomass_products)
        )
      ),
      SUM(
        Q(final_demand_of_biomass_products)
      )
    )
