# Sum of all primary biomass demand (including foreign demand)

- unit = PJ
- query =
    IF(
      GRAPH().future?,
      -> {
        SUM(
          V(G(final_demand_group), demand_of_bio_resources_including_abroad)
        ) / BILLIONS
      },
      -> { 0 }
    )
