# This query calculates the share of foreign and imported biomass demand (in total biomass demand)
# It does so by subtracting the export from the import, and dividing this by the demand of the distribution nodes 
# of the primary biomass carriers + the import of biomass fuels.
# This ensures there is no double counting.

- unit = factor
- query =
    DIVIDE(
      SUM(
        Q(import_of_biomass_products),
        NEG(
          Q(export_of_biomass_products),
          Q(export_of_greengas)
        )
      ),
      DIVIDE(
        SUM(
          V(
            energy_distribution_biogenic_waste,
            energy_distribution_dry_biomass, 
            energy_distribution_oily_biomass,
            energy_distribution_wet_biomass,
            demand
          ),
          V(
            G(energy_import),
            output_of(
            bio_kerosene,
            bionaphtha,
            bio_pyrolysis_oil,
            bio_ethanol,
            biodiesel, 
            biomethanol,         
            )
          )
        ),
        BILLIONS
      ) 
    )
