# investment costs of households_space_heater_heatpump_ground_water_electricity,
# households_water_heater_heatpump_ground_water_electricity (has no costs)
# and households_cooling_heatpump_ground_water_electricity
# IF newly built (green field approach)
# Corrected for double counting

- query =
    IF(
        QUERY_FUTURE(households_space_heater_heatpump_ground_water_electricity_future_in_investment_cost_table) >
        (V(households_cooling_heatpump_ground_water_electricity, total_investment_over_lifetime_per(:node)) / BILLIONS),
        V(households_space_heater_heatpump_ground_water_electricity,fixed_costs_per(:node)),
        V(households_cooling_heatpump_ground_water_electricity,fixed_costs_per(:node))
    )
- unit = euro
