# Correction for the fact that CCU technologies can use hydrogen and
# the cost of this hydrogen is taken into account in the total_costs_per(:node) methods.
# The total costs for hydrogen production and transport are already explicitly taken into
# account in the dashboard.
# Costs for production and transport are included in the hydrogen cost/price and are counted
# twice.
# Here we subtract the cost for the hydrogen used in CCUS technologies.

- query =
    - SUM(V(G(cost_ccus),input_of_hydrogen)) * V(CARRIER(hydrogen),cost_per_mj)
- unit = euro
