- query =
    SUM(
      Q(costs_building_and_installations_agriculture),
      Q(costs_building_and_installations_buildings),
      Q(costs_building_and_installations_households),
      Q(costs_building_and_installations_transport),
      Q(costs_building_and_installations_industry)
    )

- unit = euro