# Costs of insulation in buildings

- query =
    SUM(
      DIVIDE(Q(costs_of_insulation_buildings_present), V(buildings_useful_demand_for_space_heating_buildings_present,technical_lifetime)),
      DIVIDE(Q(costs_of_insulation_buildings_future),  V(buildings_useful_demand_for_space_heating_buildings_future,technical_lifetime))
    )
- unit = euro
