# Initial investment costs for insulation in households

- query =
    SUM(
      Q(costs_of_insulation_apartments_before_1945),
      Q(costs_of_insulation_apartments_1945_1964),
      Q(costs_of_insulation_apartments_1965_1984),
      Q(costs_of_insulation_apartments_1985_2004),
      Q(costs_of_insulation_apartments_2005_present),
      Q(costs_of_insulation_apartments_future),
      Q(costs_of_insulation_detached_houses_before_1945),
      Q(costs_of_insulation_detached_houses_1945_1964),
      Q(costs_of_insulation_detached_houses_1965_1984),
      Q(costs_of_insulation_detached_houses_1985_2004),
      Q(costs_of_insulation_detached_houses_2005_present),
      Q(costs_of_insulation_detached_houses_future),
      Q(costs_of_insulation_semi_detached_houses_before_1945),
      Q(costs_of_insulation_semi_detached_houses_1945_1964),
      Q(costs_of_insulation_semi_detached_houses_1965_1984),
      Q(costs_of_insulation_semi_detached_houses_1985_2004),
      Q(costs_of_insulation_semi_detached_houses_2005_present),
      Q(costs_of_insulation_semi_detached_houses_future),
      Q(costs_of_insulation_terraced_houses_before_1945),
      Q(costs_of_insulation_terraced_houses_1945_1964),
      Q(costs_of_insulation_terraced_houses_1965_1984),
      Q(costs_of_insulation_terraced_houses_1985_2004),
      Q(costs_of_insulation_terraced_houses_2005_present),
      Q(costs_of_insulation_terraced_houses_future),
    )
- unit = euro
