# CAPEX and OPEX of the costs in buildings ex fuels ex CCUS.

- query =
    SUM(
        SUM(
            V(G(costs_building_and_installations_buildings), capital_expenditures_excluding_ccs_per(:node)),
            V(G(costs_building_and_installations_buildings), operating_expenses_excluding_ccs_per(:node))
        ),
        Q(costs_building_and_installations_buildings_insulation),
        Q(costs_building_and_installations_buildings_heat_delivery_system)
    )
- unit = euro
