# bcm = billion cubic meters
# In ETM all energy flows are in lower heating value (LHV), therefore we have to use the LHV caloric value
# to calculate the volume
# LHV caloric values = 31.65 MJ / m3

- unit = bcm
- query = V(energy_extraction_natural_gas, demand) / BILLIONS / 31.65
