# Final consumption of coal and coal products in energy (energetic and non-energetic use combined).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_coal_and_coal_products_in_energy_total)
