# heat production of agriculture_chp_engine_network_gas_must_run

- unit = PJ
- query = future:UNIT(V(agriculture_chp_engine_network_gas_must_run, "output_of_useable_heat + output_of_steam_hot_water"),billions)
