# capacity of agriculture_chp_supercritical_wood_pellets

- query = future:DIVIDE(V(agriculture_chp_supercritical_wood_pellets,"nominal_capacity_electricity_output_per_unit * number_of_units"),1000)
- unit = gw
