# capacity of agriculture_chp_engine_network_gas_must_run

- query = future:DIVIDE(V(agriculture_chp_engine_network_gas_must_run,"nominal_capacity_electricity_output_per_unit * number_of_units"),1000)
- unit = gw
