# capacity of energy_chp_ultra_supercritical_cofiring_coal

- query = future:DIVIDE(V(energy_chp_ultra_supercritical_cofiring_coal,"nominal_capacity_electricity_output_per_unit * number_of_units"),1000)
- unit = gw
