# capacity of energy_chp_combined_cycle_mt_hydrogen

- query = future:DIVIDE(V(energy_chp_combined_cycle_mt_hydrogen,"nominal_capacity_electricity_output_per_unit * number_of_units"), THOUSANDS)
- unit = gw
