# capacity of industry_chp_engine_gas_power_fuelmix

- query = future:DIVIDE(V(industry_chp_engine_gas_power_fuelmix,"nominal_capacity_electricity_output_per_unit * number_of_units"),1000)
- unit = gw
