# heat production of industry_chp_ultra_supercritical_coal
# accounts for CHP heat component (industry_heat_xxx) when external coupling is activated

- unit = PJ
- query =
    future:DIVIDE(
      SUM(
        V(
          industry_chp_ultra_supercritical_coal,
          industry_heat_ultra_supercritical_coal,
          "output_of_useable_heat + output_of_steam_hot_water"
        )
      ),
      BILLIONS
    )
