- unit = MT
- query =
    DIVIDE(
      SUM(
        (INPUT_VALUE(bunkers_allocated_percentage_shipping) / 100.0)
          * EMISSIONS(emissions_subsector, "International navigation", other_ghg, 1990),
        (INPUT_VALUE(bunkers_allocated_percentage_aviation) / 100.0)
          * EMISSIONS(emissions_subsector, "International aviation", other_ghg, 1990)
      ),
      THOUSANDS
    )
