- unit = mt
- query =
    DIVIDE(
      SUM(
        EMISSIONS(agriculture_non_specified, energetic, other_ghg, 1990),
        EMISSIONS(agriculture_non_specified, non_energetic, other_ghg, 1990)
      ),
      THOUSANDS
    )
