# Uses the query for ETM sector bunkers, which matches klimaattafel category Internationaal
# transport.
# This is done since using the klimaattafel mapping could not distinguish between
# aviation and navigation for other GHG.

- unit = MT
- query = Q(direct_emissions_bunkers_other_ghg_1990)
