# Uses the query for ETM sector LULUCF, which matches klimaattafel category Landgebruik.
# No separate handling is required for emissions and removals since per definition, other GHG in
# the Landgebruik category can only be emissions.

- unit = MT
- query = Q(direct_emissions_lulucf_other_ghg_1990)
