# No separate handling is required for emissions and removals since per definition, other GHG in
# the Landgebruik category can only be emissions. For the CO2 query
# direct_emissions_klimaattafel_landgebruik_co2_1990, removals and emissions are handled separately.

- unit = MT
- query =
    DIVIDE(
      EMISSIONS(klimaattafel, "Landgebruik", other_ghg, 1990),
      THOUSANDS
    )
