- deprecated_key = chart_other_transport_55_gas_vs_other_primary_energy_511
# 

- unit = pj

SUM(
    Q(primary_demand_of_biofuels_from_transport),
    Q(primary_demand_of_biomass_and_bio_oil_from_transport),
    Q(primary_demand_of_coal_from_transport),
    Q(primary_demand_of_imported_electricity_from_transport),
    Q(primary_demand_of_lignite_from_transport),
    Q(primary_demand_of_crude_oil_from_transport),
    Q(primary_demand_of_electricity_from_transport),
    Q(primary_demand_of_uranium_from_transport),
    Q(primary_demand_of_waste_from_transport)
)