- query =
    IF(
      GOAL_IS_SET(land_for_solar_panels),
      LESS_OR_EQUAL(
        V(energy_power_solar_pv_solar_radiation,total_land_use),
        GOAL_USER_VALUE(land_for_solar_panels)
      ),
      nil
    )
- unit = boolean
