# Max newly required capacity for the MV-distribution network
# Compares the required capacity for 4 periods of the year

- unit = MW

MAX(
    Q(network_mv_d_net_delta_peak_load_we),
    Q(network_mv_d_net_delta_peak_load_wd),
    Q(network_mv_d_net_delta_peak_load_se),
    Q(network_mv_d_net_delta_peak_load_sd)
)