# This Gquery calculates the additional peak load as a result of the electrical technologies that are installed in a scenario for a winter evening
# Required new MV-distribution network capacity during
# If the additional peak load in the future scenario is lower than in the present scenario, this Gquery returns 0.0
- query =
    MAX(
        SUM(
            QUERY_DELTA( -> {SUM(V(Q(network_lv_net_converters),"simult_we*peak_load_in_mw")) })
                    *V(energy_power_lv_network_electricity,simult_we)
                    *V(energy_power_transformer_lv_mv_electricity,simult_we)
            ,
            QUERY_DELTA( -> {SUM(V(Q(network_mv_d_net_converters),"simult_we*peak_load_in_mw")) })
        ),
        0.0
    )
- unit = MW
