# Returns the capacity of combined cycle coal gas power plants sector energy.
- query = 
        PRODUCT(
  		V(energy_chp_power_combined_cycle_coal_gas,number_of_units),
  		V(energy_chp_power_combined_cycle_coal_gas,electricity_output_capacity)	
  		)
- unit = MW

