# Primary demand of carrier group 'torrified_biomass_pellets' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(primary_demand_of_torrified_biomass_pellets_from_curtailment) + Q(primary_demand_of_torrified_biomass_pellets_from_export)
