# Use of torrified_biomass_pellets in energy sector

- unit = PJ
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(energy)), primary_demand_of_torrified_biomass_pellets
    ).sum / BILLIONS
