# Primary demand of carrier group 'torrified_biomass_pellets' for the curtailment converter

- unit = PJ
- query =
    V(energy_flexibility_curtailment_electricity, primary_demand_of_torrified_biomass_pellets) / BILLIONS
