# Primary demand of carrier group 'torrefied_biomass_pellets' for the export converter group

- unit = PJ
- query =
    V(G(energy_export), primary_demand_of_torrefied_biomass_pellets).sum / BILLIONS
