# Primary demand of carrier group 'wood_pellets' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(primary_demand_of_wood_pellets_from_curtailment) + Q(primary_demand_of_wood_pellets_from_export)
