# Primary demand of carrier group 'wood' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(primary_demand_of_wood_from_curtailment) + Q(primary_demand_of_wood_from_export)
