# Use of torrified_biomass_pellets in other sector

- unit = PJ
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(other)), primary_demand_of_torrified_biomass_pellets
    ).sum / BILLIONS
