# Primary demand of carrier group 'biodiesel' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(primary_demand_of_biodiesel_from_curtailment) + Q(primary_demand_of_biodiesel_from_export)
