# Primary demand of carrier group 'biogas' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(primary_demand_of_biogas_from_curtailment) + Q(primary_demand_of_biogas_from_export)
