# Final consumption of electricity in industry ex. ict and refineries - other (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Other -- EG(other_non_specified_industry)
# Carrier:     Electricity -- electricity?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_electricity_in_industry_other_non_specified_non_energetic)
