# The total costs of the network calculation

- query =
          SUM(
              Q(lv_net_total_costs_future),
              Q(lv_mv_trafo_total_costs_future),
              Q(mv_net_total_costs_future),
              Q(mv_hv_trafo_total_costs_future),
              Q(hv_net_total_costs_future),
              Q(interconnection_net_costs_future),
              Q(offshore_net_costs_future)
          )

- unit = euro
