- query =
		SUM(
			Q(final_demand_of_natural_gas_and_derivatives_in_households),
		  Q(final_demand_of_natural_gas_and_derivatives_in_buildings),
		  Q(final_demand_of_natural_gas_and_derivatives_in_agriculture),
		  Q(final_demand_of_natural_gas_and_derivatives_in_industry),
		  Q(final_demand_of_natural_gas_and_derivatives_in_other),
		  Q(final_demand_of_natural_gas_and_derivatives_in_transport)
		)
- unit = PJ
