- query =
    SUM(
      Q(heat_used_for_district_heating_in_residences),
      Q(coal_and_derivatives_used_for_district_heating_in_residences),
      Q(natural_gas_and_derivatives_used_for_district_heating_in_residences),
      Q(oil_and_derivatives_used_for_district_heating_in_residences),
      Q(electricity_used_for_district_heating_in_residences),
      Q(biomass_products_used_for_district_heating_in_residences),
      Q(solar_used_for_district_heating_in_residences),
      Q(ambient_used_for_district_heating_in_residences),
      Q(geothermal_used_for_district_heating_in_residences)
    )
- unit = PJ
