- query =
      SUM(V(
            agriculture_final_demand_wood_pellets,
            other_final_demand_wood_pellets,
            industry_final_demand_wood_pellets,
            bunkers_final_demand_bio_kerosene,
            demand
          )
      )

- unit = MJ
