- query =
    SUM(
      V(
        FILTER(
          Q(heating_converters_in_households),
          "input_of_electricity != 0"
        ),
        output_of_useable_heat
      ),

      V(
        FILTER(
          CHILDREN(
            V(buildings_useful_demand_for_space_heating_after_insulation_and_solar_heater)
          ),
          "input_of_electricity != 0"
        ),
        output_of_useable_heat
      ),

      V(households_useful_demand_for_cooling_after_insulation, input_of_cooling),
      V(buildings_useful_demand_after_insulation_cooling, input_of_cooling)
    )

- unit = MJ
