- query =
    SUM(
      QUERY_PRESENT(factsheet_demand_of_gasoline_diesel_lpg),
      QUERY_PRESENT(factsheet_demand_of_gas_in_industry_agriculture_other),
      QUERY_PRESENT(factsheet_demand_of_gas_in_households_and_buildings),
      QUERY_PRESENT(factsheet_demand_of_collective_heat),
      QUERY_PRESENT(final_demand_of_electricity)
    )

- unit = MJ
