- query =
    SUM(
      V(buildings_collective_geothermal,
        households_collective_geothermal,
        energy_heater_for_heat_network_geothermal,
        energy_heater_for_heat_network_wood_pellets,
        energy_heater_for_heat_network_network_gas,
        energy_heater_for_heat_network_waste_mix,
        energy_chp_combined_cycle_network_gas,
        energy_chp_supercritical_waste_mix
        buildings_collective_chp_wood_pellets,
        buildings_chp_engine_biogas,
        buildings_collective_chp_network_gas,
        households_collective_chp_network_gas,
        households_collective_chp_wood_pellets,
        households_collective_chp_biogas,
        "heat_output_capacity*number_of_units"
        ))

- unit = MW
