- query =
    SUM(
      V(
        transport_final_demand_gasoline,
        transport_final_demand_diesel,
        transport_final_demand_lpg,
        transport_final_demand_bio_diesel,
        transport_final_demand_bio_ethanol,
        demand
      )
    )
- unit = MJ
