- query =
    SUM(
      Q(factsheet_demand_of_gasoline_diesel_lpg),
      Q(factsheet_demand_of_gas_in_industry_agriculture_other),
      Q(factsheet_demand_of_gas_in_households_and_buildings),
      Q(factsheet_demand_of_collective_heat),
      Q(total_electricity_produced)
    )

- unit = MJ
