- query =
        SUM(
            V(
              buildings_collective_geothermal,
              households_collective_geothermal,
              energy_heater_for_heat_network_geothermal,
              energy_heater_for_heat_network_wood_pellets,
              buildings_collective_chp_wood_pellets,
              buildings_chp_engine_biogas,
              households_collective_chp_wood_pellets,
              households_collective_chp_biogas,
              "heat_output_capacity*number_of_units"
            )
        )

- unit = MW
