- query =
    SUM(
      Q(factsheet_demand_of_biomass_in_households_and_buildings),
      Q(factsheet_demand_of_individual_heat_all_electric),
      Q(factsheet_demand_of_individual_heat_other_sources),
      Q(factsheet_supply_heat_from_solar_thermal)
    )

- unit = MJ
