- query =
    SUM(
      Q(factsheet_supply_heat_from_other),
      Q(factsheet_supply_heat_collective),
      Q(factsheet_supply_heat_from_biomass),
      Q(factsheet_supply_heat_from_solar_thermal),

      Q(factsheet_supply_gas_from_synthetic_gas),
      Q(factsheet_supply_gas_from_biogas),
      Q(factsheet_supply_gas_from_fossil),

      Q(factsheet_supply_fossil_other),

      Q(factsheet_supply_electricity_from_other),
      Q(factsheet_supply_electricity_from_wind),
      Q(factsheet_supply_electricity_from_solar),

      Q(factsheet_supply_biofuels)
    )

- unit = MJ
