- query =
    SUM(
      Q(factsheet_demand_of_biomass_transport),
      Q(factsheet_demand_of_gas_total),
      Q(factsheet_demand_of_heat_total),
      Q(final_demand_of_electricity)
    )

- unit = MJ
