- query =
      SUM(V(
            industry_final_demand_network_gas,
            transport_final_demand_hydrogen,
            agriculture_final_demand_network_gas,
            demand
          )
      )


- unit = MJ
