- query =
    SUM(
      QUERY_FUTURE(factsheet_demand_of_biomass_transport),
      QUERY_FUTURE(factsheet_demand_of_gas_total) * BILLIONS,
      QUERY_FUTURE(factsheet_demand_of_heat_total),
      QUERY_FUTURE(factsheet_demand_of_electricity_future)
    )

- unit = MJ
