- query =
    SUM(

      Q(factsheet_supply_heat_from_rest_and_geothermal),
      Q(factsheet_supply_heat_from_solar_thermal),
      Q(factsheet_supply_heat_from_ambient),

      Q(factsheet_supply_gas_from_biogas),
      Q(factsheet_supply_gas_from_fossil),
      Q(factsheet_supply_gas_from_synthetic_gas),

      Q(factsheet_supply_fossil_other),

      Q(factsheet_supply_electricity_from_wind),
      Q(factsheet_supply_electricity_from_solar),

      Q(factsheet_supply_biofuels),
      Q(factsheet_supply_dry_biomass)
    )

- unit = MJ
