- query =
      SUM(
          V(
              households_final_demand_for_cooling_electricity,
              households_final_demand_for_space_heating_electricity,
              households_final_demand_for_hot_water_electricity,
              households_final_demand_for_cooking_electricity,
              buildings_final_demand_for_space_heating_electricity,
              buildings_final_demand_for_cooling_electricity,
              demand
          ),
          V(
              households_cooling_heatpump_ground_water_electricity,
              households_cooling_heatpump_air_water_electricity,
              buildings_cooling_collective_heatpump_water_water_ts_electricity,
              buildings_cooling_heatpump_air_water_network_gas,
              input_of_ambient_cold
          ),
          V(
              households_space_heater_heatpump_air_water_electricity,
              households_space_heater_heatpump_ground_water_electricity,
              households_water_heater_heatpump_ground_water_electricity,
              households_water_heater_heatpump_air_water_electricity,
              buildings_space_heater_collective_heatpump_water_water_ts_electricity,
              buildings_space_heater_heatpump_air_water_network_gas,
              input_of_ambient_heat
          )
      )

- unit = MJ
