- unit = PJ
- query =
   DIVIDE(
       V(bunkers_flexibility_p2l_electricity,output_of_kerosene) -
       V(EDGE(bunkers_locally_available_kerosene_after_p2l, energy_export_kerosene), value),
   BILLIONS)

