- query = 
    SUM_CURVES(
      V(
        FILTER(
          G(primary_heat_infrastructure), 
          "heat_network_lt"
        ), 
      steam_hot_water_output_curve
      )
    ).max
- unit = MW

