- query =
    SUM(
      PRODUCT(V(CARRIER(imported_electricity), cost_per_mj), V(energy_import_electricity, demand)),
      PRODUCT(V(CARRIER(electricity), cost_per_mj), V(energy_production_excess_electricity, demand))
    )-
    SUM(
      PRODUCT(V(CARRIER(electricity), cost_per_mj), V(energy_export_electricity, demand))
    )

- unit = euro

