# Returns the capacity of chp coal gas plants sector energy.
- query = 
        PRODUCT(
  		V(energy_chp_coal_gas,number_of_units),
  		V(energy_chp_coal_gas,electricity_output_capacity)	
  		)
- unit = MW

