- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          transport_plane_using_bio_ethanol,
          transport_plane_using_gasoline,
          transport_plane_using_kerosene,
          final_demand
        )
      ),
      BILLIONS
    )