#

- deprecated_key = chart_fuel_trains_b_23_final_energy_demand_206
- unit = pj

SUM(DIVIDE(V(transport_useful_demand_trains,final_demand),BILLIONS),
NEG(Q(electricity_trains_in_use_of_final_demand_in_transport)))
