- unit = PJ
- query =
    SUM(
      DIVIDE(
        V(transport_useful_demand_trains,final_demand),
        BILLIONS
      ),
        NEG(Q(electricity_trains_in_use_of_final_demand_in_transport)
      )
    )
