- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          transport_ship_using_diesel_mix,
          transport_ship_using_lng_mix,
          final_demand
        )
      ),
      BILLIONS
    )
