- query = 
    DIVIDE(
      SUM(
        V(
          transport_truck_using_compressed_natural_gas,
          transport_truck_using_diesel_mix,
          transport_truck_using_gasoline_mix,
          final_demand)
      ),
    BILLIONS
    )
- unit = pj
