- query =
    SUM(
      Q(heat_infrastructure_households_lt_indoor_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_buildings_lt_indoor_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_lt_exchanger_station_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_lt_sub_station_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_lt_distribution_pipelines_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_lt_connection_pipelines_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_lt_primary_pipelines_fixed_operation_and_maintenance_costs)
    )
- unit = euro