- query =
    SUM(
      Q(heat_infrastructure_lt_indoor_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_lt_distribution_stations_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_lt_distribution_pipelines_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_lt_primary_pipelines_fixed_operation_and_maintenance_costs)
    )
- unit = euro