# Final consumption from industry ex. ict and refineries - other, all carriers (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Other -- EG(other_non_specified_industry)
# Carrier:     All carriers
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_from_industry_other_non_specified_non_energetic)
