# Direct conversion output of steam hot water on MT heat network through greengas

- query =
    DIVIDE(
      SUM(
        V(
          FILTER(G(heat_production),"heat_network_mt"),
          "output_of_steam_hot_water * greengas_input_conversion"
        )
      ),
      BILLIONS
    )
- unit = PJ
