# Direct conversion output of steam hot water on MT heat network through import

- query =
    DIVIDE(
      V(
        energy_distribution_mt_imported_heat,
        "output_of_steam_hot_water * imported_heat_input_conversion"
      ),
      BILLIONS
    )
- unit = PJ
