# The flexible capacity in other ict industry load shifting 

- unit = MW
- query = 
    PRODUCT(
      MAX(
        SUM_CURVES(
          V(
            FILTER(ALL()
            ,"merit_order && (merit_order.group == :industry_ict)"),electricity_input_curve)
          )
          ),
       INPUT_VALUE(input_capacity_of_industry_other_ict_flexibility_load_shifting_electricity)
      )
