# The flexible capacity in energy heat flexibility p2h boiler electricity

- query =
    SUM(
      Q(energy_heat_flexibility_p2h_boiler_ht_electricity_capacity),
      Q(energy_heat_flexibility_p2h_boiler_mt_electricity_capacity)
    )
- unit = MW
