# The flexible capacity in energy interconnectors exported electricity

- query =
    SUM(
      Q(energy_interconnector_1_exported_electricity_capacity),
      Q(energy_interconnector_2_exported_electricity_capacity),
      Q(energy_interconnector_3_exported_electricity_capacity),
      Q(energy_interconnector_4_exported_electricity_capacity),
      Q(energy_interconnector_5_exported_electricity_capacity),
      Q(energy_interconnector_6_exported_electricity_capacity),
      Q(energy_interconnector_7_exported_electricity_capacity),
      Q(energy_interconnector_8_exported_electricity_capacity),
      Q(energy_interconnector_9_exported_electricity_capacity),
      Q(energy_interconnector_10_exported_electricity_capacity),
      Q(energy_interconnector_11_exported_electricity_capacity),
      Q(energy_interconnector_12_exported_electricity_capacity)
    )
- unit = MW
