# Final demand of the 'geothermal' carrier group 

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :buildings"
          ),
          geothermal?
        ),
        value
      )      
    ) / BILLIONS
