# Final demand of the 'liquid biofuels' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          biodiesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          bio_ethanol?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          bio_oil?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          bio_lng?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          bio_kerosene?
        ),
        value
      )
    ) / BILLIONS
