# Final demand of the 'bio_oil' carrier group for households
# Input of bio_oil in crude_oil final demand is accounted for

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :households"
            ),
            bio_oil?
          ),
          value
        ),
        PRODUCT(
          SUM(
            V(
              FILTER(
                FILTER(
                  FILTER(
                    EG(final_demand),"sector == :households"
                  ),
                  energetic?
                ),
                crude_oil?
              ),
              value
            )
          ),
          V(households_final_demand_crude_oil, bio_oil_input_conversion)
        )
      ),
      BILLIONS
    )
