# Final demand of the 'ammonia' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :agriculture"
          ),
          ammonia?
        ),
        value
      )
    ) / BILLIONS
