# Final demand of the 'coal_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :agriculture"
          ),
          coal?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :agriculture"
          ),
          coal_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :agriculture"
          ),
          cokes?
        ),
        value
      )
    ) / BILLIONS
