# Final demand of the 'bio_ethanol' carrier group

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :transport"
            ),
            bio_ethanol?
          ),
          value
        )
      ),
      BILLIONS
    )
