# Final demand of the 'geothermal' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :industry"
          ),
          geothermal?
        ),
        value
      )      
    ) / BILLIONS
