# Final demand of the 'natural_gas_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          network_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          compressed_network_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          lng?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          propane?
        ),
        value
      )
    ) / BILLIONS
