# Final demand of fossil heat in the 'heat' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :energy"
          ),
          steam_hot_water?
        ),
        "(1 - sustainability_share) * value"
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :energy"
          ),
          useable_heat?
        ),
        "(1 - sustainability_share) * value"
      )
    ) / BILLIONS
