# Final demand of the 'natural_gas_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :households"
          ),
          network_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :households"
          ),
          lng?
        ),
        value
      )        
    ) / BILLIONS
