# Final demand of the 'greengas' carrier group
# Demand for compressed network gas is corrected for network_gas_input_conversion to correct
# for network gas input only (electricity is also an input to the compressor)

- unit = PJ
- query =
    DIVIDE(
      PRODUCT(
        SUM(
          V(
            FILTER(
              FILTER(EG(final_demand),"sector == :transport"),
              network_gas?
            ),
            value
          ),
          PRODUCT(
            V(
              FILTER(
                FILTER(EG(final_demand),"sector == :transport"),
                compressed_network_gas?
              ),
              value
            ),
            V(energy_compressor_network_gas, network_gas_input_conversion)
          )
        ),
        Q(share_of_sustainable_gas_in_gas_network)
      ),
      BILLIONS
    )
