# Final demand of the 'coal_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :households"
          ),
          coal?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :households"
          ),
          coal_gas?
        ),
        value
      )      
    ) / BILLIONS
