# Final demand of the 'greengas' carrier group

- unit = PJ
- query =
    DIVIDE(
      PRODUCT(
        SUM(
          V(
            FILTER(
              FILTER(EG(final_demand),"sector == :transport"),
              network_gas?
            ),
            value
          ),
          V(
            FILTER(
              FILTER(EG(final_demand),"sector == :transport"),
              compressed_network_gas?
            ),
            value
          )
        ),
        Q(share_of_sustainable_gas_in_gas_network)
      ),
      BILLIONS
    )
