# Final demand of the 'solar' carrier group 

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :agriculture"
          ),
          solar_radiation?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :agriculture"
          ),
          solar_thermal?
        ),
        value
      )      
    ) / BILLIONS
