# Final demand of the 'greengas' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :other"
          ),
          network_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :other"
          ),
          compressed_network_gas?
        ),
        value
      )
    ) * V(energy_national_gas_network_natural_gas,greengas_input_conversion) / BILLIONS
