# Final demand of the 'solar_thermal' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :energy"
          ),
          solar_thermal?
        ),
        value
      )
    ) / BILLIONS
