# Final demand of the 'solid_biofuels' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          wood_pellets?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          torrefied_biomass_pellets?
        ),
        value
      )
    ) / BILLIONS
