# Final demand of the 'biodiesel' carrier group for industry
# Input of biodiesel in crude_oil final demand is accounted for

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :industry"
            ),
            biodiesel?
          ),
          value
        ),
        PRODUCT(
          SUM(
            V(
              FILTER(
                FILTER(
                  FILTER(
                    EG(final_demand),"sector == :industry"
                  ),
                  energetic?
                ),
                crude_oil?
              ),
              value
            )
          ),
          V(industry_final_demand_crude_oil, biodiesel_input_conversion)
        ),
        PRODUCT(
          SUM(
            V(
              FILTER(
                FILTER(
                  FILTER(
                    EG(final_demand),"sector == :industry"
                  ),
                  "!energetic?"
                ),
                crude_oil?
              ),
              value
            )
          ),
          V(industry_final_demand_crude_oil_non_energetic, biodiesel_input_conversion)
        )
      ),
      BILLIONS
    )
