# Final demand of the 'heat' carrier group 

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :industry"
          ),
          steam_hot_water?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :industry"
          ),
          useable_heat?
        ),
        value
      )      
    ) / BILLIONS
