# Final demand of the 'heat' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :other"
          ),
          steam_hot_water?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :other"
          ),
          useable_heat?
        ),
        value
      )
    ) / BILLIONS
