# Final demand of the 'biodiesel' carrier group

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :bunkers"
            ),
            biodiesel?
          ),
          value
        )
      ),
      BILLIONS
    )
