# Final demand of the 'hydrogen' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :transport"
          ),
          hydrogen?
        ),
        value
      )
    ) / BILLIONS
