# Final demand of the 'oil_and_derivatives' carrier group 

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :agriculture"
          ),
          crude_oil?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :agriculture"
          ),
          gasoline?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :agriculture"
          ),
          diesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :agriculture"
          ),
          lpg?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :agriculture"
          ),
          kerosene?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :agriculture"
          ),
          heavy_fuel_oil?
        ),
        value
      )      
    ) / BILLIONS
