# Final demand of the 'ambient' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          ambient_heat?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :bunkers"
          ),
          ambient_cold?
        ),
        value
      )
    ) / BILLIONS
