# Final demand of the 'waste_mix' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :other"
          ),
          waste_mix?
        ),
        value
      )
    ) / BILLIONS
