# Final demand of the 'biomass_products' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :other"
          ),
          biodiesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :other"
          ),
          bio_ethanol?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :other"
          ),
          wood_pellets?
        ),
        value
      )      
    ) / BILLIONS
