# Final demand of the 'biomass_products' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :households"
          ),
          biodiesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :households"
          ),
          bio_ethanol?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :households"
          ),
          wood_pellets?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :households"
          ),
          bio_lng?
        ),
        value
      )         
    ) / BILLIONS
