# Final demand of the 'wood_pellets' carrier group

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :other"
            ),
            wood_pellets?
          ),
          value
        )
      ),
      BILLIONS
    )
