# Final demand of the 'ambient' carrier group 

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :other"
          ),
          ambient_heat?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :other"
          ),
          ambient_cold?
        ),
        value
      )      
    ) / BILLIONS
