# Final demand of the 'solar' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :agriculture"
          ),
          solar_radiation?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :agriculture"
          ),
          solar_thermal?
        ),
        value
      )
    ) / BILLIONS
