# Final demand of the 'bio_oil' carrier group

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :energy"
            ),
            bio_oil?
          ),
          value
        )
      ),
      BILLIONS
    )
