# Total GHG emissions incl. indirect emissions (ind_co2), excl. LULUCF (4) and international
# transport (1.D.1)

- unit = MT
- query =
    SUM(
      Q(direct_emissions_ipcc_total_ghg_incl_indirect_emissions_lulucf_bunkers),
      NEG(Q(direct_emissions_ipcc_4_total_ghg)),
      NEG(Q(direct_emissions_ipcc_1d1_total_ghg))
    )
