# Energetic final demand in the aggregated_other_industry_nl sub-sector

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_aggregated_other_industry_nl_energetic),
      Q(final_demand_of_coal_and_derivatives_in_aggregated_other_industry_nl_energetic),
      Q(final_demand_of_electricity_in_aggregated_other_industry_nl_energetic),
      Q(final_demand_of_ambient_in_aggregated_other_industry_nl_energetic),
      Q(final_demand_of_solar_in_aggregated_other_industry_nl_energetic),
      Q(final_demand_of_geothermal_in_aggregated_other_industry_nl_energetic),
      Q(final_demand_of_heat_in_aggregated_other_industry_nl_energetic),
      Q(final_demand_of_hydrogen_in_aggregated_other_industry_nl_energetic),
      Q(final_demand_of_natural_gas_and_derivatives_in_aggregated_other_industry_nl_energetic),
      Q(final_demand_of_oil_and_derivatives_in_aggregated_other_industry_nl_energetic)
    )
