# The peak electricity demand in present year

- query =
    present:SUM(
        Q(peak_electricity_demand),
        PRODUCT(
          Q(total_supply_and_demand_variability),
          3
        )
    )
- unit = MW
