# Calculates the increase in spinning reserve capacity required due to the addition of volatile energy technologies

- unit = MW

PRODUCT(
    3,
    SUM(
        SQRT(
            SUM(
                V(G(final_demand_electricity) ; mw_input_capacity**2*variability**2),
                V(G(volatile_production) ; mw_input_capacity**2*25/10000)
            )
        ),
        NEG(
            SQRT(
                SUM(
                    V(G(final_demand_electricity) ; mw_input_capacity**2*variability**2)
                )
            )
        )
    )
)
