# Calculates the increase in spinning reserve capacity required due to the addition of volatile energy technologies

- query =
    PRODUCT(
        3,
        SUM(
            SQRT(
                SUM(
                    V(G(final_demand_electricity) ," mw_input_capacity**2*variability**2"),
                    V(G(volatile_production) ," installed_production_capacity_in_mw_electricity**2*forecasting_error**2")
                )
            ),
            NEG(
                SQRT(
                    SUM(
                        V(G(final_demand_electricity) ," mw_input_capacity**2*variability**2")
                    )
                )
            )
        )
    )
- unit = MW
