# Available electricity production capacity in MW
# Query is the sum product of installed production capacity and the availability factor for all electricity production

- query =
    SUM(
      V(G(electricity_production),"installed_production_capacity_in_mw_electricity*availability*capacity_credit")
    )
- unit = mw
