# The full load hours of the backup capacity is the weighted average based on capacity factor - capacity credit

- query =
    PRODUCT(
      DIVIDE(
        Q(additional_backup_capacity_required_in_mw),
        SUM(V(G(volatile_production) , installed_production_capacity_in_mw_electricity))
      ),
      HOURS_PER_YEAR
    )
- unit = hours
