# Query is using dummy attributes for the moment
# total_land_use attribute will become part_load_operating_point
# land_use_per_unit attribute will become part_load_efficiency

- unit = euro

future:DIVIDE(
    SUM(
        PRODUCT(
            Q(additional_backup_capacity_required_in_mw),
            V(gas_ccgt_energy ; fixed_costs_per_mw_input / availability)
        ),
        PRODUCT(
            Q(additional_spinning_reserve_required_in_mw),
            V(gas_ccgt_energy ; total_land_use * HOURS_PER_YEAR / [1 - total_land_use] * fuel_costs_per_mwh_input * [FLOAT_HACK/land_use_per_unit-FLOAT_HACK/electricity_output_conversion])
        )
    ),
    Q(volatile_electricity_production)
)