# Returns the number of hours per year where the production capacity cannot meet the demand

- query = V(GRAPH(), loss_of_load_expectation(Q(lole_demand), Q(reliable_electricity_production_capacity)))
- unit = hours
