# Returns the peak electricity demand by using the demand_curve method. This method returns an array of the hourly demand.
# The peak electricity demand is taken to be the maximum of this array.

- query = MAX(V(GRAPH(), demand_curve))
- unit = mw
