# calculates the % chance of a blackout: that supply is less than demand

- unit = %

PRODUCT(
    NORMCDF(Q(peak_electricity_demand),Q(available_electricity_production_capacity),Q(total_supply_and_demand_variability)),
    100
)