# 20120130 - Dummy query to calculate CO2 emissions of backup capacity for the flexibility of electricity production scatter plot

- unit = kt

PRODUCT(
  DIVIDE(
    PRODUCT(
      SUM(
        V(wind_offshore_energy, wind_inland_energy, wind_coastal_energy, local_solar_pv_grid_connected_energy_energetic ; installed_production_capacity_in_mw_electricity * [full_load_seconds / SECS_PER_YEAR])
      ),
      V(gas_ccgt_energy; primary_co2_emission / production_based_on_number_of_units * MJ_PER_MWH / availability),
      4500,
      0.001
    ),
    SUM(
      V(wind_offshore_energy, wind_inland_energy, wind_coastal_energy, local_solar_pv_grid_connected_energy_energetic ; production_based_on_number_of_units)
    )
  ),
  MJ_PER_MWH
)