# Total variability in both supply and demand
# Variability is calculated as the root of the sum of squares of individual variabilities
# 2011-12-13: The variability is only of demand. The effect of supply variability is taken into account in the available production capacity

- query =
    SQRT(
        SUM(
          V(G(final_demand_electricity),"mw_input_capacity**2*variability**2")
        )
    )
- unit = mw
