- unit = MJ
- query =
    SUM(
      V(G(energy_import),output_of(Q(carrier_group_biomass_products_import))),
      NEG(V(G(energy_export),input_of(Q(carrier_group_biomass_products_import))).sum)
    )
