- query =
    DIVIDE(
      V(energy_interconnector_imported_electricity,demand),
      SUM(
        Q(total_electricity_produced),
        V(energy_interconnector_imported_electricity,demand)
      )
    )
- unit = factor
- deprecated_key = electricity_dependence
