# bio ethanol and bio diesel are use energetic!

- deprecated_key = import_of_biomassa_group
- unit = mj

 SUM(
  V(
   bio_residues_import_energy,
   bio_diesel_import_export_energy_energetic,
   bio_ethanol_import_export_energy_energetic, 
   waste_import_export_environment, 
   bio_oil_import_export_energy,
   biocoal_import_energy,
   wood_pellets_import_energy,
   greengas_import_export_energy,
   algue_diesel_import_export_energy_energetic, demand
  )
,
NEG(
  SUM(V(
bio_residues_export_energy, 
bio_oil_export_energy,
waste_export_energy,
bio_diesel_export_energy,
bio_ethanol_export_energy,
greengas_export_energy,
algue_diesel_export_energy 
, demand
)  )
)


 )
