# Netto import divided by (primary) territorial energy use
#
# X =         Import – Export
# Y =         Primaire consumptie = Winning + Import – Export

- query =
    DIVIDE(
      SUM(
        V(G(energy_import),demand).sum,
        NEG(V(G(energy_export),demand).sum)
      ),
      Q(primary_demand_caused_by_final_demand)
    )
- unit = factor
- deprecated_key = energy_dependence
