# This Gquery calculates the additional peak load as a result of the electrical technologies that are installed in a scenario for a winter day
# This Gquery takes into account all technologies attached below the MV-transport network (i.e. MV-distribution network and LV-network)
# If the additional peak load in the future scenario is lower than in the present scenario, this Gquery returns 0.0

- query =
    MAX(
        SUM(
            QUERY_DELTA( -> {SUM(V(Q(network_lv_net_converters),"simult_wd*peak_load_in_mw")) })
                    *V(energy_power_lv_network_electricity,simult_wd)
                    *V(energy_power_transformer_lv_mv_electricity,simult_wd)
                    *V(energy_power_mv_distribution_network_electricity, simult_wd)
            ,
            QUERY_DELTA( -> {SUM(V(Q(network_mv_d_net_converters),"simult_wd*peak_load_in_mw")) })
                    *V(energy_power_mv_distribution_network_electricity, simult_wd)
        ),
        0.0
    )
- unit = MW
