# Required new MV-transport network capacity during a summer evening.
# Query takes into account all technologies attached below the MV-transport network (i.e. MV-distribution network and LV-network)
# Query sums the newly required capacities per technology (peak_laod_in_mw) and adds these to the currently used capacity on the network (network_capacity_used_in_mw)

- query =
    ABS(
        SUM(
            QUERY_DELTA( -> {SUM(V(Q(network_lv_net_converters),"simult_se*peak_load_in_mw")) })
                    *V(energy_power_lv_network_electricity,simult_se)
                    *V(energy_power_transformer_lv_mv_electricity,simult_se)
                    *V(energy_power_mv_distribution_network_electricity, simult_se)
            ,
            QUERY_DELTA( -> {SUM(V(Q(network_mv_d_net_converters),"simult_se*peak_load_in_mw")) })
                    *V(energy_power_mv_distribution_network_electricity, simult_se)
            ,
            V(energy_power_mv_transport_network_electricity, network_capacity_used_in_mw)
        )
    )
- unit = MW
