#

- unit = MW

SUM(
    MAX(
        ABS(
            SUM(
                SUM(V(Q(network_lv_net_converters),"simult_supply*peak_load_in_mw"))
                        *V(energy_power_lv_network_electricity,simult_supply)
                        *V(energy_power_transformer_lv_mv_electricity,simult_supply)
                        *V(energy_power_mv_distribution_network_electricity, simult_supply)
                ,
                SUM(V(Q(network_mv_d_net_converters),"simult_supply*peak_load_in_mw"))
                        *V(energy_power_mv_distribution_network_electricity, simult_supply)
                ,
                V(energy_power_mv_transport_network_electricity, network_capacity_used_in_mw)
            )
        ),
        V(energy_power_mv_transport_network_electricity, network_capacity_available_in_mw)
    ),
    NEG(V(energy_power_mv_transport_network_electricity, network_capacity_available_in_mw))
)