# Max newly required capacity for the MV-transport network
# Compares the required capacity for 4 periods of the year

- query =
    MAX(
        V(energy_power_mv_transport_network_electricity, required_additional_network_capacity_in_mw(Q(network_mv_t_net_peak_load_sd))),
        V(energy_power_mv_transport_network_electricity, required_additional_network_capacity_in_mw(Q(network_mv_t_net_peak_load_se))),
        V(energy_power_mv_transport_network_electricity, required_additional_network_capacity_in_mw(Q(network_mv_t_net_peak_load_wd))),
        V(energy_power_mv_transport_network_electricity, required_additional_network_capacity_in_mw(Q(network_mv_t_net_peak_load_we)))
    )
- unit = MW
