- unit = PJ
- query =
    (
    V(energy_steel_blastfurnace_current_transformation_cokes, "output_of_loss*sustainability_share")
    +V(energy_steel_blastfurnace_bat_transformation_cokes, "output_of_loss*sustainability_share")
    +V(energy_steel_hisarna_transformation_coal, "output_of_loss*sustainability_share")
    )/BILLIONS
