- unit = MJ
- query =
        SUM(
            V(
                industry_final_demand_for_metal_steel_coal,
                input_of_coal
            ),
            Q(coal_transformation_losses_in_industry_steel)
        )
