- unit = MJ
- query =
        SUM(
            V(
                industry_final_demand_for_metal_steel_wood_pellets,
                energy_blastfurnace_own_use,
                energy_cokesoven_own_use,
                input_of_wood_pellets
            )
        )
