# Total other ghg emissions for 1990 including all IPCC categories

- unit = MT
- query =
    SUM(
      Q(direct_emissions_ipcc_1a1_other_ghg_1990),
      Q(direct_emissions_ipcc_1a2_other_ghg_1990),
      Q(direct_emissions_ipcc_1a3_other_ghg_1990),
      Q(direct_emissions_ipcc_1a4a_other_ghg_1990),
      Q(direct_emissions_ipcc_1a4b_other_ghg_1990),
      Q(direct_emissions_ipcc_1a4c_other_ghg_1990),
      Q(direct_emissions_ipcc_1a5_other_ghg_1990),
      Q(direct_emissions_ipcc_1b_other_ghg_1990),
      Q(direct_emissions_ipcc_1c_other_ghg_1990),
      Q(direct_emissions_ipcc_1d1_other_ghg_1990),
      Q(direct_emissions_ipcc_2_other_ghg_1990),
      Q(direct_emissions_ipcc_3_other_ghg_1990),
      Q(direct_emissions_ipcc_4_other_ghg_1990),
      Q(direct_emissions_ipcc_5_other_ghg_1990),
      Q(direct_emissions_ipcc_ind_other_ghg_1990)
    )