# Total emissions for 1990 including all IPCC categories

- unit = MT
- query =
    SUM(
      Q(direct_emissions_ipcc_1a1_total_ghg_1990),
      Q(direct_emissions_ipcc_1a2_total_ghg_1990),
      Q(direct_emissions_ipcc_1a3_total_ghg_1990),
      Q(direct_emissions_ipcc_1a4a_total_ghg_1990),
      Q(direct_emissions_ipcc_1a4b_total_ghg_1990),
      Q(direct_emissions_ipcc_1a4c_total_ghg_1990),
      Q(direct_emissions_ipcc_1a5_total_ghg_1990),
      Q(direct_emissions_ipcc_1b_total_ghg_1990),
      Q(direct_emissions_ipcc_1c_total_ghg_1990),
      Q(direct_emissions_ipcc_1d1_total_ghg_1990),
      Q(direct_emissions_ipcc_2_total_ghg_1990),
      Q(direct_emissions_ipcc_3_total_ghg_1990),
      Q(direct_emissions_ipcc_4_total_ghg_1990),
      Q(direct_emissions_ipcc_5_total_ghg_1990),
      Q(direct_emissions_ipcc_ind_total_ghg_1990)
    )