
- query =
    SUM(
      Q(output_of_ammonia_in_industry_transformation_chemical_fertilizers),
      Q(output_of_greengas_in_industry_transformation_chemical_fertilizers),
      Q(output_of_hydrogen_in_industry_transformation_chemical_fertilizers),
      Q(output_of_natural_gas_in_industry_transformation_chemical_fertilizers),
      Q(output_of_not_defined_in_industry_transformation_chemical_fertilizers),
      Q(output_of_ammonia_in_industry_transformation_chemical_other),
      Q(output_of_greengas_in_industry_transformation_chemical_other),
      Q(output_of_hydrogen_in_industry_transformation_chemical_other),
      Q(output_of_natural_gas_in_industry_transformation_chemical_other),
      Q(output_of_not_defined_in_industry_transformation_chemical_other)
    )
- unit = PJ
