- query =
    SUM(
      Q(input_of_ammonia_in_industry_transformation_chemical_refineries),
      Q(input_of_electricity_in_industry_transformation_chemical_refineries),
      Q(input_of_greengas_in_industry_transformation_chemical_refineries),
      Q(input_of_hydrogen_in_industry_transformation_chemical_refineries),
      Q(input_of_methanol_in_industry_transformation_chemical_refineries),
      Q(input_of_natural_gas_in_industry_transformation_chemical_refineries),
      Q(input_of_not_defined_in_industry_transformation_chemical_refineries),
      Q(input_of_waste_mix_in_industry_transformation_chemical_refineries),
      Q(input_of_wood_pellets_in_industry_transformation_chemical_refineries),
      Q(input_of_bio_oil_in_industry_transformation_chemical_refineries)
    )
- unit = PJ
