# CAPEX and OPEX of the costs in power plants ex fuels ex CCUS.

- query =
          SUM(
              V(G(costs_production_power_plants), capital_expenditures_excluding_ccs_per(:node)),
              V(G(costs_production_power_plants), operating_expenses_excluding_ccs_per(:node))
              )


- unit = euro
