- query =
    SUM(
        V(energy_distribution_crude_oil, demand) - V(energy_export_crude_oil, demand),
        V(energy_distribution_coal, demand) - V(energy_export_coal, demand),
        V(energy_distribution_lignite, demand) - V(energy_export_lignite, demand),
        V(energy_distribution_uranium_oxide, demand) - V(energy_export_uranium_oxide, demand),
        V(energy_distribution_non_biogenic_waste, demand) - V(energy_export_non_biogenic_waste, demand),
        V(energy_import_gasoline, demand),
        V(energy_import_kerosene, demand),
        V(energy_import_diesel, demand),
        V(energy_import_heavy_fuel_oil, demand),
        Q(factsheet_supply_electricity_from_import_except_imbalance)
    ) -
    SUM(
        V(INTERSECTION(G(final_demand_group), USE(non_energetic)),
        "input_of_crude_oil +
        input_of_coal +
        input_of_lignite +
        input_of_uranium_oxide +
        input_of_non_biogenic_waste +
        input_of_gasoline +
        input_of_kerosene +
        input_of_diesel +
        input_of_heavy_fuel_oil")
    )

- unit = MJ