- query =
    SUM(
        V(G(heat_production), "output_of_useable_heat*ambient_heat_input_conversion"),
        V(G(heat_production), "output_of_steam_hot_water*ambient_heat_input_conversion")        
    )

- unit = MJ
