- query =
    SUM(
        V(energy_distribution_crude_oil, demand) - V(energy_export_crude_oil, demand),
        V(energy_distribution_coal, demand) - V(energy_export_coal, demand),
        V(energy_distribution_lignite, demand) - V(energy_export_lignite, demand),
        V(energy_distribution_uranium_oxide, demand) - V(energy_export_uranium_oxide, demand),
        V(energy_distribution_lng, demand) - V(energy_export_lng, demand),
        V(energy_distribution_non_biogenic_waste, demand) - V(energy_export_non_biogenic_waste, demand),
        V(energy_import_gasoline, demand),
        V(energy_import_kerosene, demand),
        V(energy_import_diesel, demand),
        V(energy_import_heavy_fuel_oil, demand),
        Q(factsheet_supply_electricity_from_import_except_imbalance)

    )

- unit = MJ