- query =
    SUM(V(G(heat_production), "output_of_useable_heat*network_gas_input_conversion").sum,
        V(G(heat_production), "output_of_cooling*network_gas_input_conversion").sum,
        V(G(heat_production), "output_of_useable_heat*coal_input_conversion").sum,
        V(G(heat_production), "output_of_useable_heat*crude_oil_input_conversion").sum,
        V(G(heat_production), "output_of_useable_heat*lignite_input_conversion").sum,
        SUM(V(G(heat_production), "output_of_useable_heat*coal_gas_input_conversion"))
    )

- unit = MJ
