- query =
    SUM(V(energy_distribution_wood_pellets, demand),
        V(energy_distribution_torrified_biomass_pellets, demand),
        - V(energy_export_wood_pellets, demand),
        - V(energy_export_torrified_biomass_pellets, demand)
        )

- unit = MJ
