- query =
    SUM(
        V(G(heat_production), "output_of_useable_heat*electricity_input_conversion").sum,
        - V(FILTER(G(heat_production), "ambient_heat_input_conversion > 0"), "output_of_useable_heat*electricity_input_conversion").sum,
        - V(agriculture_geothermal, "output_of_useable_heat*electricity_input_conversion")
    )

- unit = MJ
