- query =
    SUM(
        V(energy_distribution_crude_oil, demand) - V(energy_export_crude_oil, demand),
        V(energy_distribution_coal, demand) - V(energy_export_coal, demand),
        V(energy_distribution_lignite, demand) - V(energy_export_lignite, demand),
        V(energy_distribution_uranium_oxide, demand) - V(energy_export_uranium_oxide, demand),
        V(energy_distribution_non_biogenic_waste, demand) - V(energy_export_non_biogenic_waste, demand)
    )

- unit = MJ