# Energetic final demand of the 'hydrogen' carrier group in buildings appliances

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(appliances_buildings)), "hydrogen?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
