# Energetic final demand of the 'waste_mix' carrier group in buildings appliances

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(appliances_buildings)), "waste_mix?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
