- query =
      SUM(V(
            transport_final_demand_bio_ethanol,
            transport_final_demand_biodiesel,
            transport_final_demand_bio_lng,
            transport_final_demand_biomethanol,
            transport_final_demand_bio_kerosene,
            demand
          )
      )

- unit = MJ
