
- unit = PJ
- query =
    SUM(
      Q(output_of_methanol_synthesis_biogenic_waste),
      Q(output_of_methanol_synthesis_dry_biomass),
      Q(output_of_methanol_synthesis_non_biogenic_waste),
      Q(output_of_methanol_synthesis_synthetic)
    )
