- query =
    SUM_CURVES(V(
      INTERSECTION(
        FILTER(ALL(),"network_gas && (network_gas.type == :consumer || network_gas.type == :export)"),
        EXCLUDE(INTERSECTION(G(heat_production),SECTOR(energy)),G(electricity_production))
      ),
      network_gas_input_curve
    ))
- unit = curve
