- query =
        SUM(
            V(agriculture_useful_demand_useable_heat,
              agriculture_useful_demand_electricity,
              primary_co2_emission
              )
            )

- unit = T
