- query =
		SUM(
			SUM(
		    V(
					agriculture_useful_demand_electricity,
					agriculture_useful_demand_useable_heat,
					primary_co2_emission
				)) / THOUSANDS,
				AREA(energetic_emissions_other_ghg_agriculture) * MILLIONS
		)

- unit = T
