# Returns the capacity of chp local engine ht network gas power plants
- query = 
        PRODUCT(
  		V(energy_chp_local_engine_ht_network_gas,number_of_units),
  		V(energy_chp_local_engine_ht_network_gas,electricity_output_capacity)	
  		)
- unit = MW
