# Returns the capacity of combined cycle network gas power plants with ccs.
- query = 
        PRODUCT(
  		V(energy_power_combined_cycle_css_network_gas,number_of_units),
  		V(energy_power_combined_cycle_css_network_gas,electricity_output_capacity)	
  		)
- unit = MW

