# Final consumption from households, all carriers (energetic use only).
#
# Sector:      Households -- sector == :households
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_households_energetic)
