- deprecated_key = chart_natural_gas_buildings_55_gas_vs_other_primary_energy_504
#

- unit = pj

DIVIDE(SUM(V(INTERSECTION(SECTOR(buildings),G(final_demand_cbs)),primary_demand_of_natural_gas)),BILLIONS)