# OM wants to use 350 wp pv panels. In the ETM panels are 272 wp. We increase roof surface potential by 350/272 to reflect the energy production of 350 wp panels. We decrease the factsheet number of units calculation by 350/272 to get the correct number of units.
- query = 1.286764706
- unit = #
