# Production nodes for liquid fuels production

- query =
    V(
      G(costs_production_liquid_fuels),
      energy_production_bio_lng,
      energy_production_bio_oil,
      industry_refinery_transformation_crude_oil
    )
- unit = nodes
