# Production nodes for liquid biofuels production

- query =
    V(
      INTERSECTION(G(costs_production_liquid_fuels),G(biomass_products_production)),
      energy_production_bio_lng,
      energy_production_bio_oil
    )
- unit = nodes
