# Final consumption of methanol in industry ict (energetic and non-energetic use combined).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Methanol -- methanol?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_methanol_in_industry_ict_total)
