# Final consumption of methanol in other (energetic and non-energetic use combined).
#
# Sector:      Other -- sector == :other
# Carrier:     Methanol -- methanol?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_methanol_in_other_total)
