# Final consumption of methanol in buildings (energetic and non-energetic use combined).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     Methanol -- methanol?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_methanol_in_buildings_total)
