# Use of 'biomass_products' carrier group in 'heat_production'

- unit = PJ
- query =
    SUM(
      V(G(heat_production),"input_of_biodiesel * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_bio_ethanol * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_bio_lng * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_bio_oil * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_biogas * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_torrefied_biomass_pellets * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_wood_pellets * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_bio_kerosene * heat_and_cold_output_conversion")
    ) / BILLIONS
