# Use of 'useful_demand' carrier group in 'heat_production'

- unit = PJ
- query =
    SUM(
      V(G(heat_production),"input_of_useable_heat * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_cooling * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_passenger_kms * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_freight_tonne_kms * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_light * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_not_defined * heat_and_cold_output_conversion"),
      V(G(heat_production),"input_of_savings * heat_and_cold_output_conversion")
    ) / BILLIONS
