# Use of 'solar' carrier group in 'heat_production' in the energy sector

- unit = PJ
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(energy)
        ),
        input_of_solar_radiation
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(energy)
        ),
        input_of_solar_thermal
      )      
    ) / BILLIONS
