# Final consumption of non-renewable waste in industry ex. ict and refineries - paper (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Paper -- EG(paper_industry)
# Carrier:     Non-renewable waste
# Use type:    Total
#
# Exception: includes the share of non-renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_non_renewable_waste_in_industry_paper_total)
