# Final consumption of heat in industry ex. ict and refineries - paper (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Paper -- EG(paper_industry)
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_heat_in_industry_paper_total)
