# Energetic final demand of the 'biomass_products' carrier group in the other_non_specified industry

- unit = PJ
- query = Q(final_demand_of_biomass_products_in_other_non_specified_industry_energetic)
