# CO2 of network gas (green + fossil) in agriculture

- unit = tonne
- query =
    PRODUCT(
        V(agriculture_final_demand_network_gas, demand),
        V(CARRIER(network_gas), co2_conversion_per_mj)
    ) / THOUSANDS
