# CO2 of network gas in buildings

- unit = tonne
- query =
    PRODUCT(
        V(buildings_final_demand_network_gas, demand),
        V(CARRIER(network_gas), co2_conversion_per_mj)
    ) / THOUSANDS
