# CO2 of biomass in buildings

- unit = tonne
- query =
    PRODUCT(
        V(buildings_final_demand_wood_pellets, demand),
        V(CARRIER(wood_pellets), potential_co2_conversion_per_mj)
    ) / THOUSANDS
