# CO2 of biomass in buildings

- unit = tonne
- query =
    SUM(
      PRODUCT(
        V(buildings_final_demand_wood_pellets, demand),
        V(CARRIER(wood_pellets), potential_co2_conversion_per_mj)) / THOUSANDS,
      PRODUCT(
        Q(buildings_network_gas_total_in_co2_sankey),
        Q(share_of_greengas_in_gas_network))
    )
