# CO2 emissions in buildings

- unit = tonne
- query = 
    SUM(
        Q(buildings_gas_total_in_co2_sankey),
        Q(buildings_oil_total_in_co2_sankey),
        Q(buildings_coal_total_in_co2_sankey)
    )
