# CO2 emissions in bunkers

- unit = tonne
- query =
    SUM(
        Q(bunkers_network_gas_total_in_co2_sankey),
        Q(bunkers_oil_total_in_co2_sankey),
        Q(bunkers_biomass_total_in_co2_sankey)
    )
