# CO2 of biomass in bunkers

- unit = tonne
- query =
    SUM(
      PRODUCT(
        V(bunkers_final_demand_bio_kerosene, demand),
        V(CARRIER(bio_kerosene), potential_co2_conversion_per_mj)) / THOUSANDS,
      PRODUCT(
        Q(bunkers_network_gas_total_in_co2_sankey),
        Q(share_of_sustainable_gas_in_gas_network))
    )
