# CO2 captured in energy sector

- unit = tonne
- query =
    SUM(
        MV(energy_power_captured_co2, demand),
        MV(energy_hydrogen_captured_co2, demand),
        MV(molecules_direct_air_capture_co2, demand)
    ) / THOUSANDS
