# CO2 of network gas in energy

- unit = tonne
- query =
    DIVIDE(
        PRODUCT(
            SUM(
                V(CHILDREN(V(energy_power_hv_network_electricity)), input_of_network_gas),
                V(
                    energy_heat_burner_network_gas,
                    energy_heat_backup_burner_network_gas,
                    energy_torrefaction_wood,
                    energy_biomass_gasification_ccs_hydrogen,
                    energy_biomass_gasification_hydrogen,
                    input_of_network_gas
                )
            ),
            V(CARRIER(natural_gas), co2_conversion_per_mj)),
        THOUSANDS)
