# CO2 of solid biomass and biogas in energy (NOTE: biogenic waste
# is not included)

- unit = tonne
- query =
    SUM(
        V(CHILDREN(V(energy_power_hv_network_electricity)), input_of_torrefied_biomass_pellets).sum * V(CARRIER(torrefied_biomass_pellets), potential_co2_conversion_per_mj),
        SUM(
            V(CHILDREN(V(energy_power_hv_network_electricity)), input_of_wood_pellets).sum,
            V(
                energy_heat_burner_wood_pellets,
                energy_chp_local_wood_pellets,
                input_of_wood_pellets
            )
        ) * V(CARRIER(wood_pellets), potential_co2_conversion_per_mj),
        V(energy_chp_local_engine_biogas, input_of_biogas) *  V(CARRIER(biogas), potential_co2_conversion_per_mj)
    ) / THOUSANDS
