# CO2 of coal in energy

- unit = tonne
- query =
    SUM(
        Q(energy_coal_total_in_co2_sankey),
        Q(energy_network_gas_total_in_co2_sankey),
        Q(energy_oil_total_in_co2_sankey),
        Q(energy_biomass_total_in_co2_sankey),
        Q(energy_non_biogenic_waste_total_in_co2_sankey),
        Q(energy_dac_total_in_co2_sankey),
        NEG(Q(energy_captured_in_co2_sankey))
    )
