# CO2 of coal in energy

- unit = tonne
- query =
    SUM(
        V(CHILDREN(V(energy_power_hv_network_electricity)).select {|node| node.input_slots.detect { |slot| slot.carrier.coal? }}, "weighted_carrier_co2_per_mj * demand"),
        V(CHILDREN(V(energy_power_hv_network_electricity)).select {|node| node.input_slots.detect { |slot| slot.carrier.lignite? }}, "weighted_carrier_co2_per_mj * demand"),
        V(
            energy_heat_burner_coal,
            "weighted_carrier_co2_per_mj * demand"
        )
    ) / THOUSANDS
