# CO2 of coal in energy

- unit = tonne
- query = 
    SUM(
        Q(energy_coal_captured_in_co2_sankey),
        Q(energy_gas_captured_in_co2_sankey),
        Q(energy_oil_captured_in_co2_sankey)
    )
