# CO2 emissions in households

- unit = tonne
- query =
    SUM(
        Q(households_natural_gas_total_in_co2_sankey),
        Q(households_oil_total_in_co2_sankey),
        Q(households_coal_total_in_co2_sankey),
        Q(households_biomass_total_in_co2_sankey)
    )
