# CO2 emissions in households

- unit = tonne
- query = 
    SUM(
        Q(households_gas_total_in_co2_sankey),
        Q(households_oil_total_in_co2_sankey),
        Q(households_coal_total_in_co2_sankey)
    )
