# CO2 of network gas in households

- unit = tonne
- query =
    PRODUCT(
        V(households_final_demand_network_gas, demand),
        V(CARRIER(natural_gas), co2_conversion_per_mj)
    ) / THOUSANDS
