# CO2 of network gas in industry

- unit = tonne
- query =
    SUM(
        V(
            industry_final_demand_network_gas,
            industry_heat_backup_burner_network_gas,
            industry_final_demand_for_chemical_fertilizers_network_gas_non_energetic_co2,
            input_of_network_gas
        ) * V(CARRIER(network_gas), co2_conversion_per_mj)) / THOUSANDS
    + Q(industry_fuelmix_network_gas_in_co2_sankey)
