# CO2 of coal in industry

- unit = tonne
- query =
    SUM(
      SUM(
        V(
          industry_final_demand_coal,
          industry_heat_burner_coal,
          industry_heat_burner_lignite,
          industry_chp_ultra_supercritical_coal,
          energy_import_cokes,
          "weighted_carrier_co2_per_mj * demand"
          )
      ),
      SUM(
        V(energy_blastfurnace_transformation_cokes,
          energy_cokesoven_transformation_coal,
          input_of_coal)
        ) * V(CARRIER(coal), co2_per_mj)
    ) / THOUSANDS
