# CO2 emissions in industry

- unit = tonne
- query =
    SUM(
        MV(MG(captured_energetic_emissions_industry), demand),
        MV(MG(captured_non_energetic_emissions_industry), demand)
    ) / THOUSANDS
