# CO2 of biomass in industry

- unit = tonne
- query =
    SUM(
        V(
            industry_final_demand_wood_pellets,
            industry_chp_wood_pellets,
            input_of_wood_pellets
        ) * V(CARRIER(wood_pellets), potential_co2_conversion_per_mj)
    ) / THOUSANDS
