# CO2 of gas in fuel mix in industry

- unit = tonne
- query =
    DIVIDE(
      SUM(
        V(
          industry_chp_combined_cycle_gas_power_fuelmix,
          industry_chp_turbine_gas_power_fuelmix,
          industry_chp_engine_gas_power_fuelmix,
          demand
        )) * (1 - Q(oil_fraction_of_fuelmix)) * V(CARRIER(network_gas), co2_conversion_per_mj),
      THOUSANDS)

