# CO2 emissions in industry

- unit = tonne
- query = 
    SUM(
        Q(industry_gas_total_in_co2_sankey),
        Q(industry_oil_total_in_co2_sankey),
        Q(industry_coal_total_in_co2_sankey)
    )
