# CO2 of oil in industry

- unit = tonne
- query =
    SUM(
        V(
          industry_final_demand_crude_oil,
          industry_heat_burner_crude_oil,
          energy_cokesoven_own_use,
          energy_blastfurnace_own_use,
          "weighted_carrier_co2_per_mj * demand"
        )
    ) / THOUSANDS
    + Q(industry_fuelmix_oil_in_co2_sankey) * Q(crude_oil_fraction_of_fuelmix)
