# CO2 of biomass in industry

- unit = tonne
- query =
    SUM(
      SUM(
        V(
            industry_final_demand_wood_pellets,
            industry_chp_wood_pellets,
            input_of_wood_pellets
        ) * V(CARRIER(wood_pellets), potential_co2_conversion_per_mj)
      ) / THOUSANDS,
      PRODUCT(
        Q(industry_network_gas_total_in_co2_sankey),
        Q(share_of_sustainable_gas_in_gas_network)),
      Q(industry_fuelmix_oil_in_co2_sankey) * Q(bio_oil_fraction_of_fuelmix)
    )
