# CO2 of biomass in transport

- unit = tonne
- query =
    SUM(
        V(transport_final_demand_bio_ethanol, demand) * V(CARRIER(bio_ethanol), potential_co2_conversion_per_mj),
        V(transport_final_demand_biodiesel, demand) * V(CARRIER(biodiesel), potential_co2_conversion_per_mj),
        V(transport_final_demand_bio_lng, demand) * V(CARRIER(bio_lng), potential_co2_conversion_per_mj)
    ) / THOUSANDS
    + PRODUCT(
        Q(transport_network_gas_total_in_co2_sankey),
        Q(share_of_sustainable_gas_in_gas_network))
