# CO2 of natural gas and LNG in transport

- unit = tonne
- query =
    PRODUCT(
      SUM(
        V(transport_final_demand_compressed_network_gas,
          transport_final_demand_lng,
          demand
          )),
        V(CARRIER(network_gas), co2_conversion_per_mj)
    ) / THOUSANDS
