# CO2 of gas in transport

- unit = tonne
- query =
    V(
        transport_final_demand_compressed_network_gas,
        transport_final_demand_lng,
        "weighted_carrier_co2_per_mj * demand"
    ).sum / THOUSANDS
