# CO2 emissions in transport

- unit = tonne
- query = 
    SUM(
        Q(transport_gas_total_in_co2_sankey),
        Q(transport_oil_total_in_co2_sankey),
        Q(transport_coal_total_in_co2_sankey)
    )
