# Return total cost of total_cost_of_buildings_collective_heatpump_water_water_electricity

- unit = euro
- query = V(total_cost_of_buildings_collective_heatpump_water_water_electricity, total_costs_per(:plant))

