# Return total cost of industry_chemicals_other_flexibility_p2h_network_gas_electricity

- unit = euro
- query = V(industry_chemicals_other_flexibility_p2h_network_gas_electricity, total_costs_per(:plant))
