# This query returns the climate relevant CO2-emissions of biomass which is the product
# of the primary demand for biomass times the potential CO2-emissions of this biomass times
# the percentage of this CO2-emissions that is deemed relevant for climate change as set by
# the user through a slider. We distinguish three types of biomass: solid, gas and liquid,
# which can be seperately changed by the user. The user can set different values of this slider
# for present and future.

- unit = PJ
- query =
    SUM(
      PRODUCT(
        SUM(V(G(final_demand_group), key, primary_demand_of_biogenic_waste)),
        V(CARRIER(biogenic_waste), potential_co2_conversion_per_mj)
      ),
      PRODUCT(
        SUM(V(G(final_demand_group), key, primary_demand_of_torrefied_biomass_pellets)),
        V(CARRIER(torrefied_biomass_pellets), potential_co2_conversion_per_mj)
      ),
      PRODUCT(
        SUM(V(G(final_demand_group), key, primary_demand_of_wood_pellets)),
        V(CARRIER(torrefied_wood_pellets), potential_co2_conversion_per_mj)
      ),
      PRODUCT(
        SUM(V(G(final_demand_group), key, primary_demand_of_dry_biomass)),
        V(CARRIER(dry_biomass), potential_co2_conversion_per_mj)
      ),
      PRODUCT(
        SUM(V(G(final_demand_group), key, primary_demand_of_wet_biomass)),
        V(CARRIER(wet_biomass), potential_co2_conversion_per_mj)
      )
    ) *
    INPUT_VALUE(
      IF(
        scope.graph.future?,
        climate_relevant_co2_biomass_solid_future,
        climate_relevant_co2_biomass_solid_present
      )
    ) / 100.0 / BILLIONS
