- query =
    SUM(
      Q(conversion_loss_coal_to_coal),
      Q(conversion_loss_cokes_to_coal_gas),
      Q(conversion_loss_coal_to_coal_gas),
      Q(conversion_loss_coal_to_cokes)
    )
- unit = PJ
