- unit = PJ
- query =
    SUM(
      Q(total_primary_demand_of_biodiesel),
      Q(total_primary_demand_of_bio_ethanol),
      Q(total_primary_demand_of_bio_lng),
      Q(total_primary_demand_of_bio_oil),
      Q(total_primary_demand_of_bio_kerosene),
      Q(total_primary_demand_of_bionaphtha),
      Q(total_primary_demand_of_biomethanol),
      Q(total_primary_demand_of_bio_pyrolysis_oil),
      Q(total_primary_demand_of_oily_biomass)
    )
