- unit = PJ
- query = 
    SUM(
      Q(total_primary_demand_of_wood_pellets),
      Q(total_primary_demand_of_torrefied_biomass_pellets),
      Q(total_primary_demand_of_wet_biomass),
      Q(total_primary_demand_of_dry_biomass)
    )
