- unit = PJ
- query =
    SUM(
      Q(total_primary_demand_of_crude_oil),
      Q(total_primary_demand_of_gasoline),
      Q(total_primary_demand_of_diesel),
      Q(total_primary_demand_of_kerosene),
      Q(total_primary_demand_of_lpg),
      Q(total_primary_demand_of_heavy_fuel_oil),
      Q(total_primary_demand_of_naphtha)
    )
