# Energetic final demand of the 'lng' carrier group in industry

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(EG(final_demand),"sector == :industry"), "lng?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
