# Energetic final demand of the 'natural_gas' carrier group in industry excl. ict

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_natural_gas_in_industry_energetic),
      - Q(final_demand_of_natural_gas_in_ict_industry_energetic),
      Q(final_demand_of_lng_in_industry_energetic),
      - Q(final_demand_of_lng_in_ict_industry_energetic)
    )
