# Final consumption from industry ex. ict and refineries - paper, all carriers (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Paper -- EG(paper_industry)
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_industry_paper_energetic)
