# Calculates the fixed costs per MWh produced heat for power-to-heat for the agriculture.

- query =
    IF(
        SUM(V(INTERSECTION(G(p2h),SECTOR(agriculture)), output_of_useable_heat)) == 0,
        0.0,
        -> {
            DIVIDE(
                SUM(V(INTERSECTION(G(p2h),SECTOR(agriculture)), fixed_costs_per(:node))),
                DIVIDE(
                    SUM(V(INTERSECTION(G(p2h),SECTOR(agriculture)), output_of_useable_heat)),
                    3600
                )
            )
        }
    )
- unit = euro/MWh