# Calculates the variable costs per MWh produced heat for power-to-heat for the industry.

- query =
    IF(
        SUM(V(INTERSECTION(G(p2h),SECTOR(industry)), output_of_useable_heat)) == 0,
        0.0,
        -> {
            DIVIDE(
                SUM(V(INTERSECTION(G(p2h),SECTOR(industry)), variable_costs_per(:node))),
                DIVIDE(
                    SUM(V(INTERSECTION(G(p2h),SECTOR(industry)), output_of_useable_heat)),
                    3600
                )
            )
        }
    )
