# Calculates the electricity input costs per MWh produced heat for power-to-heat for the agriculture.

- query =
    IF(
        SUM(V(INTERSECTION(G(p2h),SECTOR(agriculture)), output_of_useable_heat)) == 0,
        0.0,
        -> {
            DIVIDE(
                Q(total_electricity_input_cost_power_to_heat_agriculture),
                DIVIDE(
                    SUM(V(INTERSECTION(G(p2h),SECTOR(agriculture)), output_of_useable_heat)),
                    3600
                )
            )
        }
    )
- unit = euro/MWh