# Calculates the future total costs of electricity input for power-to-heat for the district heating network.

- query =
    SUM(
      PRODUCT_CURVES(
        SUM_CURVES(V(INTERSECTION(G(p2h),SECTOR(energy)), electricity_input_curve)),
        V(CARRIER(electricity), cost_curve)
      )
    )
- unit = EUR