# Calculates the future total revenue of electricity output for power-to-power.

- query =
    SUM(
      PRODUCT_CURVES(
        SUM_CURVES(V(G(p2p), electricity_output_curve)),
        V(CARRIER(electricity), cost_curve)
      )
    )
- unit = EUR