- query = 
    V(
      energy_power_wind_turbine_inland, 
      energy_power_wind_turbine_coastal, 
      energy_battery_wind_turbine_inland,
      "number_of_units * electricity_output_capacity"
    ).sum

- unit = MW
