# Final consumption of electricity in national transport (non-energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Electricity -- electricity?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_electricity_in_national_transport_non_energetic)
