- deprecated_key = chart_electricity_27_final_energy_demand_237
# 

- unit = pj

DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),USE(energetic)),output_of_electricity)),BILLIONS)