- deprecated_key = chart_heat_from_chp_27_final_energy_demand_729
# 

- unit = pj

DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),USE(energetic)),input_of_steam_hot_water)),BILLIONS)