- query =
    buildings_peak_demand_in_kw = Q(buildings_district_heating_demand_peak) * 1000.0;

    buildings_peak_demand_in_kw * AREA(heat_buildings_indoor_investment_costs_eur_per_kw)
- unit = euro