- query =
    SUM(
      Q(heat_infrastructure_households_indoor_pipelines_investment_costs),
      Q(heat_infrastructure_buildings_indoor_pipelines_investment_costs),
      Q(heat_infrastructure_buildings_indoor_heat_meter_investment_costs),
      Q(heat_infrastructure_exchanger_station_investment_costs),
      Q(heat_infrastructure_sub_station_investment_costs),
      Q(heat_infrastructure_distribution_pipelines_investment_costs),
      Q(heat_infrastructure_connection_pipelines_investment_costs),
      Q(heat_infrastructure_primary_pipelines_investment_costs)
    )
- unit = euro