# Multiply the peak demand (= assumed to be the input capacity) of the hydrogen
# final demand curve of the entire transport sector with the share of the hydrogen
# demand of vans in respect to the total hydrogen demand of the transport sector
#
# This query is used in the ESDL app

- unit = MW
- query =
    PRODUCT(
      MAX(V(transport_final_demand_hydrogen, hydrogen_input_curve)),
      DIVIDE(
        V(transport_van_using_hydrogen, demand),
        V(transport_final_demand_hydrogen, demand)
      )
    )
