# Energetic final demand of the 'waste_mix' carrier group in households hot_water

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(hot_water_households)), "waste_mix?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
