# Energetic final demand of the 'natural_gas' carrier group in households hot_water

- unit = PJ
- query =
    PRODUCT(
      SUM(
        V(
          FILTER(
            FILTER(
              INTERSECTION(EG(final_demand),EG(hot_water_households)), "network_gas? || compressed_network_gas?"
            ),
            "energetic?"
          ),
          value
        ),
      ),
      Q(share_of_natural_gas_in_gas_network)
    ) / BILLIONS
