- query = 
		SUM(
			Q(ammonia_supply_import_baseload),
			Q(ammonia_supply_import_backup),
			Q(ammonia_supply_transformation_chemical_fertilizers_industry),
			Q(ammonia_supply_transformation_chemical_other_industry),
			Q(ammonia_supply_transformation_chemical_refineries_industry)
		)
