- query = 
		SUM(
			Q(ammonia_demand_domestic_navigation),
			Q(ammonia_demand_international_navigation),
			Q(ammonia_demand_fertilizer_industry),
			Q(ammonia_demand_other_industry),
			Q(ammonia_demand_hydrogen_ammonia_reformer_must_run),
			Q(ammonia_demand_hydrogen_ammonia_reformer_dispatchable),
			Q(ammonia_demand_export),
			Q(ammonia_demand_transformation_chemical_fertilizers_industry),
			Q(ammonia_demand_transformation_chemical_other_industry),
			Q(ammonia_demand_transformation_chemical_refineries_industry)
		)
