# Sum of all primary demand from curtailment

- unit = PJ
- query =
  SUM(
    V(energy_power_sector_own_use_electricity, primary_demand),
    V(energy_heat_network_unused_steam_hot_water, primary_demand)
  ) / BILLIONS
