# Returns the capacity of hydro water power plants.
- query = 
        PRODUCT(
  		V(energy_power_hydro_water,number_of_units),
  		V(energy_power_hydro_water,electricity_output_capacity)	
  		)
- unit = MW

