# Returns the capacity of hydro mountain power plants.
- query = 
        PRODUCT(
  		V(energy_power_hydro_mountain,number_of_units),
  		V(energy_power_hydro_mountain,electricity_output_capacity)	
  		)
- unit = MW




