- unit = MT
- query =
    DIVIDE(
      SUM(
        V(
          SECTOR(klimaatsector, "Industrie"),
          direct_reporting_emissions_other_ghg_emissions
        ),
        MV(
          MSECTOR(klimaatsector, "Industrie"),
          direct_reporting_emissions_other_ghg_emissions
        )
      ),
      BILLIONS
    )
