# Direct conversion input of heat from CHPs for central heat production

- query =
    DIVIDE(
      SUM(
        V(
          INTERSECTION(G(heat_production),G(electricity_production)),
          output_of_steam_hot_water
        ),
      ),
      BILLIONS
    )
- unit = PJ
