# Direct conversion output of steam hot water from central heating through green gas heaters

- query =
    Q(network_gas_in_source_of_central_heat_production) * Q(share_of_greengas_in_gas_network)
- unit = PJ
