
# Returns the capacity of turbine hydrogen chp's in the industry sector.
- query = 
        PRODUCT(
  		V(industry_chp_turbine_hydrogen,number_of_units),
  		V(industry_chp_turbine_hydrogen,electricity_output_capacity)	
  		)
- unit = MW

