- unit = PJ
- query =
    SUM(
      Q(conversion_loss_bio_ethanol_to_bio_kerosene),
      Q(conversion_loss_biomethanol_to_bio_kerosene),
      Q(conversion_loss_hydrogen_to_bio_kerosene_in_bio_ethanol_to_jet),
      Q(conversion_loss_hydrogen_to_bio_kerosene_in_biomethanol_to_jet),
      Q(conversion_loss_hydrogen_to_bio_kerosene_in_fractionation_bio_pyrolysis_oil),
      Q(conversion_loss_bio_pyrolysis_oil_to_bio_kerosene_in_fractionation_bio_pyrolysis_oil),
      Q(conversion_loss_steam_hot_water_to_bio_kerosene_in_fractionation_bio_pyrolysis_oil)
    )
