- unit = PJ
- query =
    SUM(
      Q(conversion_loss_biogenic_waste_to_biodiesel),
      Q(conversion_loss_bio_ethanol_to_biodiesel),
      Q(conversion_loss_hydrogen_to_biodiesel_in_bio_ethanol_to_jet)
    )
