# Query for Biomass Sankey diagram: connection between biofuels and households

- unit = PJ
- query =
    DIVIDE(
      SUM(
       V(INTERSECTION(G(final_demand_group), SECTOR(households)),
       input_of(bio_oil, bio_kerosene, bio_ethanol, biodiesel, bio_lng))),
       BILLIONS
       )
