# Query for Biomass Sankey diagram: connection between biofuels and electricity production

- unit = PJ
- query =
    DIVIDE(
      SUM(V(G(electricity_production), input_of_gas_power_fuelmix)) * V(energy_mixer_for_gas_power_fuel, bio_oil_input_conversion),
      BILLIONS
      )