# Query for Biomass Sankey diagram: connection between dry biomass and industry transformation. Used as an intermediate query; not used in the sankey file.

- unit = PJ
- query =
    SUM(
      DIVIDE(
        SUM(V(G(industry_transformation), input_of(bio_oil))),
        BILLIONS
        ),
      NEG(
        SUM(
          Q(bio_oil_to_greengas_industry_transformation_in_sankey),
          Q(bio_oil_to_bio_kerosene_industry_transformation_in_sankey),
          Q(bio_oil_to_bio_oil_industry_transformation_in_sankey),
          Q(bio_oil_to_biodiesel_industry_transformation_in_sankey)
        )
      )
    )  
