# Query for Biomass Sankey diagram: connection between biogenic waste and waste mix

- unit = PJ
- query =
    DIVIDE(
      V(energy_distribution_waste_mix, input_of_biogenic_waste),
      BILLIONS
    )