# Query for Biomass Sankey diagram: connection between biogenic waste and electricity (incl. chp)

- unit = PJ
- query =
     DIVIDE(
      V(energy_export_biogenic_waste, demand),
      BILLIONS
      )
