# Query for Biomass Sankey diagram: connection between biogenic waste and industry

- query =
    DIVIDE(
      SUM(
        V(industry_final_demand_waste_mix_non_energetic,primary_demand_of_sustainable)
      ),
      BILLIONS
    )
- unit = PJ
