# Query for Biomass Sankey diagram: connection between biogenic waste and electricity (incl. chp)

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          input_of(
            biogenic_waste
          )
        )
      ),
      BILLIONS
    )
