# Query for Biomass Sankey diagram: connection between dry biomass and biofuels

- unit = PJ
- query =
    SUM(
      DIVIDE(
        SUM(
          V(
            Q(liquid_biofuels_producers),
            input_of_dry_biomass
          )
        ),
        BILLIONS
      ),
      Q(wood_pellets_to_bio_oil_industry_transformation_in_sankey),
      Q(wood_pellets_to_biodiesel_industry_transformation_in_sankey),
      Q(wood_pellets_to_bio_kerosene_industry_transformation_in_sankey)
    )
