# Query for Biomass Sankey diagram: connection between dry biomass and greengas

- unit = PJ
- query =
    DIVIDE(
       V(energy_greengas_dry_biomass_gasification, input_of_dry_biomass),
       BILLIONS
       )