# Query for Biomass Sankey diagram: connection between dry biomass and buildings

- unit = PJ
- query =
     DIVIDE(
      SUM(V(INTERSECTION(G(final_demand_group), SECTOR(buildings)), input_of(wood_pellets, torrefied_biomass_pellets))),
      BILLIONS
      )
