# Query for Biomass Sankey diagram: connection between dry biomass and industry

- unit = PJ
- query =
     DIVIDE(
      SUM(V(INTERSECTION(G(final_demand_group), SECTOR(industry)), energy_steel_cyclonefurnace_transformation_coal, input_of(wood_pellets, torrefied_biomass_pellets))),
      BILLIONS
      )
