# Query for Biomass Sankey diagram: connection between dry biomass and losses. The torrefaction nodes has both dry biomass and network gas (which includes greengas) as inputs. It is assumed that 100% of network_gas input is lost and that the remaining loss is dry biomass. The dry biomass losses are taken into account here, the network_gas loss is taken into account in the greengas_to_loss_in_biomass_sankey query

- unit = PJ
- query =
    MAX(
      DIVIDE(
        SUM(
          V(
            energy_production_wood_pellets,
            output_of_loss
          ),
          V(
            energy_torrefaction_wood,
            "input_of_dry_biomass - output_of_torrefied_biomass_pellets"
          ),
          V(
            G(industry_transformation),
            "input_of_wood_pellets * loss_output_conversion"
          )
        ),
        BILLIONS
      ),
      0
    )
