# Losses consist of biogas to greengas converison loss, distribution losses in the central
# gas network and conversion loss to compressed network gas

- unit = PJ
- query =
    SUM(
      Q(conversion_loss_biogas_to_greengas),
      Q(conversion_loss_greengas_to_network_gas),
      Q(conversion_loss_greengas_to_compressed_network_gas)
    )
