# Query for Biomass Sankey diagram: connection between greengas and heat production

- unit = PJ
- query =
     DIVIDE(
      SUM(V(Q(central_heat_producing_converters_sankey), input_of(network_gas, compressed_network_gas))) * Q(share_of_sustainable_gas_in_gas_network),
      BILLIONS
      )
