# Query for Biomass Sankey diagram: connection between greengas and electricity (incl. chp)

- unit = PJ
- query =
     DIVIDE(
      SUM(
      SUM(V(G(electricity_production), input_of(network_gas, compressed_network_gas))) * Q(share_of_sustainable_gas_in_gas_network),
      SUM(V(G(electricity_production), input_of_gas_power_fuelmix)) * V(energy_mixer_for_gas_power_fuel, network_gas_input_conversion) * Q(share_of_sustainable_gas_in_gas_network)
      ),
      BILLIONS
      )
