# Query for Biomass Sankey diagram: connection between greengas and bunkers

- unit = PJ
- query =
          DIVIDE(
          V(energy_export_greengas_baseload, demand),
          BILLIONS
          )
     
