- unit = PJ
- query =
    SUM(
      Q(conversion_loss_biogas_to_greengas),
      Q(conversion_loss_greengas_to_network_gas),
      Q(conversion_loss_greengas_to_electricity),
      Q(conversion_loss_greengas_to_steam_hot_water),
      Q(conversion_loss_greengas_to_hydrogen_excl_industry_transformation),
      Q(conversion_loss_greengas_to_compressed_network_gas)
    )
