# Query for Biomass Sankey diagram: connection between greengas and losses. Includes greengas used for torrefaction of wood pellets

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(energy_greengas_upgrade_biogas,
          energy_greengas_gasification_dry_biomass,
          energy_greengas_gasification_wet_biomass,
          output_of_loss),
        PRODUCT(
           V(energy_biogas_fermentation_wet_biomass, output_of_loss),
           V(EDGE(energy_greengas_upgrade_biogas, energy_distribution_biogas), parent_share)
        ),
        V(energy_national_gas_network_natural_gas,
          output_of_loss) * Q(share_of_sustainable_gas_in_gas_network),
        V(energy_torrefaction_wood,
          input_of_network_gas) * Q(share_of_sustainable_gas_in_gas_network)),
      BILLIONS
    )
