# Query for Biomass Sankey diagram: connection between greengas and bunkers

- unit = PJ
- query =
     SUM(
          DIVIDE(
          V(energy_export_greengas_backup, demand),
          BILLIONS
          ),
          DIVIDE(
          V(energy_export_greengas_baseload, demand),
          BILLIONS
          )
     )
