# Query for Biomass Sankey diagram: connection between greengas and industry transformation. This query is not directly used in the sankey, but used in the flows from non biogenic carriers to 

- unit = PJ
- query =
     SUM(
			DIVIDE(
				SUM(V(G(industry_transformation), input_of(greengas))),
				BILLIONS
				)
			,
      	NEG(
					SUM(	
          	Q(greengas_to_biomass_products_industry_transformation_in_sankey),
						Q(greengas_to_greengas_industry_transformation_in_sankey)
					)
      	)
     	)
     
