# Flow from greengas_primary to greengas_secondary in biomass sankey
# This query consists of the following flows:
# 1. Greengas production from dry and wet biomass
# 2. Reduced with greengas production to bio_ethanol, bio_kerosene and torrefied_biomass_pellets
# (via network gas). A correction in this part is done to only account for greengas produced
# from wet and dry biomass (so not from biogas)

- unit = PJ
- query =
    SUM(
      Q(conversion_dry_biomass_in_source_of_greengas),
      Q(conversion_wet_biomass_in_source_of_greengas),
      NEG(
        PRODUCT(
          SUM(
            Q(conversion_from_greengas_to_bio_ethanol),
            Q(conversion_from_greengas_to_bio_kerosene),
            Q(conversion_from_greengas_to_torrefied_biomass_pellets)
          ),
          (1 - V(EDGE(energy_greengas_upgrade_biogas, energy_greengas_production), share))
        )
      )
    )
