# Hydrogen to bionaphtha flows consist of hydrogen to biomethanol to jet and fractionation of
# bio_pyrolysis_oil

- unit = PJ
- query =
    SUM(
      Q(conversion_from_hydrogen_to_bionaphtha_in_biomethanol_to_jet),
      Q(conversion_from_hydrogen_to_bionaphtha_in_fractionation_bio_pyrolysis_oil)
    )
