# Hydrogen to bio_kerosene flows consist of hydrogen to bio_ethanol to jet and biomethanol to jet

- unit = PJ
- query =
    SUM(
      Q(conversion_from_hydrogen_to_bio_kerosene_in_bio_ethanol_to_jet),
      Q(conversion_from_hydrogen_to_bio_kerosene_in_biomethanol_to_jet)
    )
