# Query for Biomass Sankey diagram: connection between local production and biogenic waste

- unit = PJ
- query =
    DIVIDE(
       V(energy_production_biogenic_waste, demand),
       BILLIONS
       )