# Query for Biomass Sankey diagram: connection between non biogenic carriers and biofuels
# All bio to bio transformations within the transformation nodes are subtracted, since these are accounted for elsewhere.
- query =
    SUM(
      DIVIDE(
        SUM(
          V(
            G(industry_transformation),
            "output_of_bio_kerosene  / (1 - loss_output_conversion - residual_heat_input_conversion)"
          ),
          V(
            G(industry_transformation),
            "output_of_biodiesel  / (1 - loss_output_conversion - residual_heat_input_conversion)"
          ),
          V(
            G(industry_transformation),
            "output_of_bio_oil  / (1 - loss_output_conversion - residual_heat_input_conversion)"
          ),
          V(energy_production_fractionation_bio_pyrolysis_oil, "input_of_steam_hot_water + input_of_hydrogen"),
          V(
            energy_production_hvo_bio_kerosene,
            energy_production_hvo_biodiesel,
            energy_production_bio_ethanol_to_jet,
            input_of_hydrogen
          ),
          PRODUCT(
            SUM(
              V(
                energy_production_hvo_bio_kerosene,
                energy_production_bio_ethanol,
                input_of_network_gas
              )
            ),
            Q(share_of_fossil_gas_in_gas_network)
          )
        ),
        BILLIONS
      ),
      NEG(
        SUM(
          Q(greengas_to_biodiesel_industry_transformation_in_sankey),
          Q(greengas_to_bio_kerosene_industry_transformation_in_sankey),
          Q(greengas_to_bio_oil_industry_transformation_in_sankey),
          Q(wood_pellets_to_bio_oil_industry_transformation_in_sankey),
          Q(wood_pellets_to_biodiesel_industry_transformation_in_sankey),
          Q(wood_pellets_to_bio_kerosene_industry_transformation_in_sankey),
          Q(bio_oil_to_bio_kerosene_industry_transformation_in_sankey),
          Q(bio_oil_to_biodiesel_industry_transformation_in_sankey),
          Q(bio_oil_to_bionaphtha_industry_transformation_in_sankey)
      	)
      )
    )
- unit = PJ
