# Query for Biomass Sankey diagram: connection between non biogenic carriers and biofuels
# input_of_bio_oil from transformation nodes subtracted since these are accounted for in oily biomass to biofuels flow

- query =
    DIVIDE(
      SUM(
        V(
          G(industry_transformation),
          "output_of_bio_kerosene  / (1 - loss_output_conversion - residual_heat_input_conversion)"
        ),
        V(
          G(industry_transformation),
          "output_of_biodiesel  / (1 - loss_output_conversion - residual_heat_input_conversion)"
        ),
         V(
          G(industry_transformation),
          "output_of_bio_oil  / (1 - loss_output_conversion - residual_heat_input_conversion)"
        )
      ) -
      SUM(
        V(
          G(industry_transformation),
          input_of_bio_oil
        )
      ),
      BILLIONS
    )
- unit = PJ