# Query for Biomass Sankey diagram: connection between oily biomass and biofuels

- unit = PJ
- query =
    DIVIDE(
      SUM(
       V(energy_production_hvo_bio_kerosene,
       energy_production_bio_oil,
       energy_production_bio_ethanol,
       energy_production_hvo_biodiesel,
       energy_production_bio_lng,
       energy_production_fischer_tropsch_dry_biomass_ccs,
       energy_production_methanol_synthesis_dry_biomass_ccs,
       energy_production_pyrolysis_dry_biomass,
       input_of_oily_biomass)),
       BILLIONS
       )
