# Query for Biomass Sankey diagram: connection between wet biomass and greengas

- unit = PJ
- query =
    DIVIDE(
       V(energy_greengas_wet_biomass_gasification, input_of_wet_biomass),
       BILLIONS
       )