# Query for Biomass Sankey diagram: connection between wet biomass and biofuels

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          Q(liquid_biofuels_producers),
          input_of_wet_biomass
        )
      ),
      BILLIONS
    )
