# Query for Biomass Sankey diagram: connection between wet biomass and greengas

- unit = PJ
- query =
    DIVIDE(
       V(energy_greengas_gasification_wet_biomass, input_of_wet_biomass),
       BILLIONS
       )