# Query for Biomass Sankey diagram: connection between wet biomass and biofuels

- unit = PJ
- query =
    DIVIDE(
      SUM(
       V(energy_production_hvo_bio_kerosene,
       energy_production_bio_oil,
       energy_production_bio_ethanol,
       energy_production_hvo_biodiesel,
       energy_production_bio_lng,
       input_of_wet_biomass)),
       BILLIONS
       )