# Query for Biomass Sankey diagram: connection between wet biomass and loss

- unit = PJ
- query =
    DIVIDE(
       V(energy_greengas_gasification_wet_biomass, output_of_loss),
       BILLIONS
       )