- query =
    FILTER(
      FILTER(
        G(heat_production),"heat_network_ht"
      ),
      "network_gas_input_conversion > 0.0 || compressed_network_gas_input_conversion > 0.0"
    )
- unit = nodes
