- query =
    SUM(
      Q(factsheet_supply_heat_from_biomass),
      Q(factsheet_supply_heat_from_electricity),
      Q(factsheet_supply_heat_from_other),
      Q(factsheet_supply_heat_from_solar_thermal)
    )

- unit = MJ
