- query =
    SUM(
      Q(factsheet_supply_heat_from_biomass),
      Q(factsheet_supply_heat_from_ambient_individual),
      Q(factsheet_supply_heat_from_electricity_heatpump_individual),
      Q(factsheet_supply_heat_from_electricity_except_heatpump_individual),
      Q(factsheet_supply_heat_fossil_heating),
      Q(factsheet_supply_heat_from_solar_thermal)
    )

- unit = MJ
