- query =
    DIVIDE(
      Q(factsheet_supply_heat_from_ambient_individual)+Q(factsheet_supply_heat_from_electricity_heatpump_individual),
      Q(factsheet_supply_of_individual_heat_total)
      ) * 100
- unit = %
