- query =
      SUM(
          V(industry_final_demand_for_metal_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_construction_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_machinery_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_minerals_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_mining_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_non_specified_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_textile_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_transport_equipment_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_wood_products_wood_pellets, input_of_wood_pellets),
          V(other_final_demand_wood_pellets, input_of_wood_pellets),
          V(industry_chp_wood_pellets, input_of_wood_pellets)
          )

- unit = MJ
