- query =
          SUM(
             V(
               households_collective_chp_network_gas,
               households_collective_chp_wood_pellets,
               households_collective_chp_biogas,
               agriculture_chp_engine_network_gas,
               agriculture_chp_engine_biogas,
               agriculture_chp_supercritical_wood_pellets,
               buildings_collective_chp_network_gas,
               buildings_collective_chp_wood_pellets,
               buildings_chp_engine_biogas,
               energy_chp_supercritical_waste_mix,
               energy_chp_combined_cycle_network_gas,
               energy_chp_ultra_supercritical_coal,
               energy_chp_ultra_supercritical_lignite,
               energy_distribution_imported_heat,
               output_of_steam_hot_water)
               )

- unit = MJ
