- query =
      SUM(
          V(households_final_demand_for_space_heating_electricity, demand),
          V(households_final_demand_for_hot_water_electricity, demand),
          V(buildings_final_demand_for_space_heating_electricity, demand),
          V(agriculture_geothermal, input_of_electricity),
          V(agriculture_heatpump_water_water_ts_electricity, input_of_electricity)
          )

- unit = MJ
