- query =
          SUM(
              V(buildings_final_demand_electricity, demand),
              V(households_final_demand_electricity, demand),
              V(agriculture_final_demand_electricity, demand)
              )
              - Q(factsheet_demand_electricity_of_individual_heating)
- unit = MJ
