- query =
      SUM(V(agriculture_chp_supercritical_wood_pellets, input_of_wood_pellets),
          V(buildings_collective_chp_wood_pellets, input_of_wood_pellets),
          V(energy_chp_ultra_supercritical_cofiring_coal, input_of_wood_pellets),
          V(energy_heater_for_heat_network_wood_pellets, input_of_wood_pellets),
          V(households_collective_chp_wood_pellets, input_of_wood_pellets),
          V(energy_distribution_torrefied_biomass_pellets, demand)
          ) - V(energy_export_torrefied_biomass_pellets, demand)

- unit = MJ
