#What share of the imported hydrogen goes to collective heat?
- query =
            DIVIDE(
                    SUM(
                        V(buildings_collective_burner_hydrogen, demand),
                        V(households_collective_burner_hydrogen,demand)
                        ),
                    V(energy_distribution_hydrogen_after_transport,demand))
                    *     V(energy_import_hydrogen, demand)


- unit = %
