- query =
          SUM(
              Q(factsheet_demand_fossil_in_households_buildings_agriculture),
              Q(factsheet_demand_fossil_in_industry),
              Q(factsheet_demand_fossil_in_mobility),
              Q(factsheet_demand_fossil_in_electricity)
              )

- unit = MJ
