- query =
          SUM(
              V(buildings_final_demand_for_appliances_wood_pellets, input_of_wood_pellets),
              V(households_final_demand_for_cooking_wood_pellets, input_of_wood_pellets),
              )

- unit = MJ
