- query =
      SUM(
          V(industry_final_demand_for_metal_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_non_specified_wood_pellets, input_of_wood_pellets),
          V(other_final_demand_wood_pellets, input_of_wood_pellets),
          )

- unit = MJ
