- query =
      SUM(
          V(buildings_final_demand_for_appliances_wood_pellets, input_of_wood_pellets),
          V(energy_chp_ultra_supercritical_cofiring_coal, input_of_wood_pellets),
          V(energy_heat_burner_wood_pellets, input_of_wood_pellets),
          V(energy_power_ultra_supercritical_cofiring_coal, input_of_wood_pellets),
          V(energy_chp_local_wood_pellets, input_of_wood_pellets),
          V(households_final_demand_for_cooking_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_metal_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_construction_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_machinery_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_minerals_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_mining_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_non_specified_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_textile_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_transport_equipment_wood_pellets, input_of_wood_pellets),
          V(industry_final_demand_for_other_wood_products_wood_pellets, input_of_wood_pellets),
          V(other_final_demand_wood_pellets, input_of_wood_pellets),
          V(industry_chp_wood_pellets, input_of_wood_pellets),
          V(energy_distribution_torrefied_biomass_pellets, demand),
          - V(energy_export_torrefied_biomass_pellets, demand)
          )

- unit = MJ
