# Depreciation costs of the ht heat delivery systems for buildings.
# The ht heat delivery system is assumed to have the same technical lifetime as the ht heating network.

- unit = euro
- query =
    number_of_buildings_in_ht_heating_network = V(buildings_space_heater_district_heating_ht_steam_hot_water,number_of_units);
    ht_heat_delivery_system_buildings_investment_costs = 
        PRODUCT(
            number_of_buildings_in_ht_heating_network,
            AREA(buildings_ht_heat_delivery_system_costs_eur_per_connection)
        );
    
    DIVIDE(
        ht_heat_delivery_system_buildings_investment_costs,
        V(energy_distribution_ht_steam_hot_water,technical_lifetime)
    )