# Depreciation costs of the mt heat delivery systems for buildings.
# The mt heat delivery system is assumed to have the same technical lifetime as the mt heating network.

- unit = euro
- query =
    number_of_buildings_in_mt_heating_network = V(buildings_space_heater_district_heating_mt_steam_hot_water,number_of_units);
    mt_heat_delivery_system_buildings_investment_costs = 
        PRODUCT(
            number_of_buildings_in_mt_heating_network,
            AREA(buildings_mt_heat_delivery_system_costs_eur_per_connection)
        );
    
    DIVIDE(
        mt_heat_delivery_system_buildings_investment_costs,
        V(energy_distribution_mt_steam_hot_water,technical_lifetime)
    )