# Special conversion for gas_and_gas_derivatives to oil_and_oil_products

- query = 
    SUM(
      Q(conversion_from_natural_gas_to_oil_and_oil_products),
      Q(conversion_from_compressed_network_gas_to_oil_and_oil_products),
      Q(conversion_from_lng_to_oil_and_oil_products)
    )
- unit = PJ
