# Direct conversion input of hydrogen for oil_products in liquid fuel processes (methanol-to-jet 
# and pyrolysis oil fractionation).

- query =
    SUM(
      Q(conversion_from_hydrogen_to_methanol_to_jet_products),
      Q(conversion_from_hydrogen_to_pyrolysis_oil_fractionation_products)
    )
- unit = PJ
