# Direct conversion input of hydrogen for oil production
# Input of hydrogen in hydrogen heater for pyrolysis_oil fractionation process
# is queried manually, otherwise this flow is ignored

- query =
    DIVIDE(
      SUM(
        V(
          energy_production_fractionation_pyrolysis_oil,
          "kerosene_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_hydrogen"
        ),
        V(
          energy_production_fractionation_pyrolysis_oil,
          "naphtha_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_hydrogen"
        ),
        V(energy_production_fractionation_pyrolysis_oil_burner_hydrogen, input_of_hydrogen)
      ),
      BILLIONS
    )
- unit = PJ
