# This is based on the energy_production_bio_oil node since for the sankey it is asssumed all oil to go in the oil mix, similar to the network gas mix.
# This is not explicitly modelled in the ETM this way, since all oil flows come together after the final demand nodes. 
# Therefore, we simply use the production node of bio kerosene to calculate the flows from bio kerosene to crude oil

- query =
    DIVIDE(
      V(energy_production_bio_oil, demand)
      ,
      BILLIONS
    )
- unit = PJ