# Direct conversion input of bio_lng for oil production

- query =
    DIVIDE(
      SUM(
        V(
          G(oil_and_oil_products_production),
          "diesel_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_bio_lng"
        ),
        V(
          G(oil_and_oil_products_production),
          "kerosene_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_bio_lng"
        ),
        V(
          G(oil_and_oil_products_production),
          "heavy_fuel_oil_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_bio_lng"
        ),
        V(
          G(oil_and_oil_products_production),
          "lpg_output_conversion  / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_bio_lng"
        ),
        V(
          G(oil_and_oil_products_production),
          "gasoline_output_conversion  / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_bio_lng"
        ),
        V(
          G(oil_and_oil_products_production),
          "crude_oil_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_bio_lng"
        ),
        V(
          G(oil_and_oil_products_production),
          "naphtha_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_bio_lng"
        ),
        V(
          G(oil_and_oil_products_production),
          "refinery_gas_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_bio_lng"
        )
      ),
      BILLIONS
    )
- unit = PJ
