- deprecated_key = chart_natural_gas_households_55_gas_vs_other_primary_energy_503
# 

- unit = pj

DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(final_demand_cbs)),primary_demand_of_natural_gas)),BILLIONS)