- query =
    SUM(
            V(
                other_final_demand_coal,
                other_final_demand_crude_oil,
                other_final_demand_network_gas,
                other_final_demand_wood_pellets,
                other_final_demand_steam_hot_water,
                other_final_demand_electricity,
                primary_co2_emission
            )
        ) / THOUSANDS

- unit = T

