- query =
        SUM(
            V(
              households_final_demand_for_cooking_electricity,
              households_final_demand_for_cooking_wood_pellets,
              households_final_demand_for_cooking_network_gas,
              primary_co2_emission
              )
            ) / THOUSANDS


- unit = T
