- query =
          SUM(V(
                households_useful_demand_light,
                households_final_demand_for_appliances_electricity,
                buildings_useful_demand_light,
                buildings_useful_demand_for_appliances,
                primary_co2_emission
                )) / THOUSANDS


- unit = T
