# Required new LV-network capacity during a winter day.
# Query takes into account all technologies attached to the LV-network
# Query sums the newly required capacities per technology (peak_laod_in_mw) and adds these to the currently used capacity on the network (network_capacity_used_in_mw)

- query =
    MAX(
        QUERY_DELTA( -> {SUM(V(Q(network_lv_net_converters),"simult_wd*peak_load_in_mw")) }),
        0
    )
- unit = MW
