# Max newly required capacity for the LV-network
# Compares the required capacity for 4 periods of the year

- unit = MW

MAX(
    Q(network_lv_net_delta_peak_load_we),
    Q(network_lv_net_delta_peak_load_wd),
    Q(network_lv_net_delta_peak_load_se),
    Q(network_lv_net_delta_peak_load_sd)
)