- query =
    SUM(
      Q(heat_infrastructure_ht_distribution_stations_depreciation_costs),
      Q(heat_infrastructure_ht_distribution_stations_capital_costs),
      Q(heat_infrastructure_ht_sub_station_yearly_maintenance_costs),
      Q(heat_infrastructure_ht_exchanger_station_yearly_maintenance_costs)
      )
- unit = euro