# Final consumption from industry refineries, all carriers (energetic and non-energetic use combined).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     All carriers
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_from_industry_refineries_total)
