# Query for Sankey diagram: connection between agriculture and useful_demand_non_energetic

- unit = PJ
- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(agriculture),G(useful_demand_non_energetic)),primary_demand)),BILLIONS)
