# Query for Sankey diagram: connection between biomass_products and transport

- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(transport),G(final_demand_group)),primary_demand_of(Q(carrier_group_biomass_products)))),BILLIONS)
- unit = pj
