# Query for Sankey diagram: connection between coal_and_derivatives and other

- unit = PJ
- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(other),G(final_demand_group)),primary_demand_of(Q(carrier_group_coal_and_derivatives)))),BILLIONS)
