# Query for Sankey diagram: connection between electricity and exported_electricity

- unit = PJ
- query = future:DIVIDE(V(energy_export_electricity, primary_demand_of(Q(carrier_group_electricity))),BILLIONS)
