# Query for Sankey diagram: connection between households and useful_demand_electric

- unit = pj

DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(useful_demand_electric)),primary_demand)),BILLIONS)
		