# Query for Sankey diagram: connection between households and useful_demand_transport

- unit = PJ
- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(useful_demand_transport)),primary_demand)),BILLIONS)
