# Query for Sankey diagram: connection between imported_electricity and buildings

- unit = PJ
- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(buildings),G(final_demand_group)),primary_demand_of(Q(carrier_group_imported_electricity)))),BILLIONS)
