# Query for Sankey diagram: connection between industry and useful_demand_transport

- unit = PJ
- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(useful_demand_transport)),primary_demand)),BILLIONS)
