# Query for Sankey diagram: connection between industry and useful_demand_non_energetic

- unit = PJ
- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(useful_demand_non_energetic)),primary_demand)),BILLIONS)
