# Query for Sankey diagram: connection between natural_gas and agriculture

- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(agriculture),G(final_demand_cbs)),primary_demand_of(Q(carrier_group_natural_gas)))),BILLIONS)
- unit = pj
