# Query for Sankey diagram: connection between natural_gas and agriculture

- unit = PJ
- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(agriculture),G(final_demand_group)),primary_demand_of(Q(carrier_group_natural_gas)))),BILLIONS)
