# Query for Sankey diagram: connection between nuclear and buildings

- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(buildings),G(final_demand_group)),primary_demand_of(Q(carrier_group_nuclear)))),BILLIONS)
- unit = pj
