# Query for Sankey diagram: connection between nuclear and exported_electricity

- unit = PJ
- query = future:DIVIDE(V(energy_export_electricity, primary_demand_of(Q(carrier_group_nuclear))),BILLIONS)
