# Query for Sankey diagram: connection between oil_and_derivatives and exported_electricity

- query = future:DIVIDE(V(energy_export_electricity, primary_demand_of(Q(carrier_group_oil_and_derivatives))),BILLIONS)
- unit = pj
