# Query for Sankey diagram: connection between other and useful_demand_non_energetic

- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(other),G(useful_demand_non_energetic)),primary_demand)),BILLIONS)
- unit = pj
