# Query for Sankey diagram: connection between other and useful_demand_electric

- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(other),G(useful_demand_electric)),primary_demand)),BILLIONS)
- unit = pj
