# Query for Sankey diagram: connection between transport and useful_demand_non_energetic

- unit = PJ
- query = future:DIVIDE(SUM(V(INTERSECTION(SECTOR(transport),G(useful_demand_non_energetic)),primary_demand)),BILLIONS)
