# Use of 'biomass_products' carrier group in 'heat_production'

- unit = pj
- query =
    SUM(
      V(G(heat_production),input_of_greengas),
      V(G(heat_production),input_of_biodiesel),
      V(G(heat_production),input_of_bio_ethanol),
      V(G(heat_production),input_of_bio_oil),
      V(G(heat_production),input_of_biogas),
      V(G(heat_production),input_of_torrified_biomass_pellets),
      V(G(heat_production),input_of_wood_pellets),
      V(G(heat_production),input_of_corn),
      V(G(heat_production),input_of_manure),
      V(G(heat_production),input_of_wood),
      V(G(heat_production),input_of_woody_biomass)
    ) / BILLIONS
