# Use of carrier group 'monetized_heat' in 'heat_production' converter group

- unit = pj
- query =
    SUM(
      V(G(heat_production),input_of_steam_hot_water),
      V(G(heat_production),input_of_useable_heat)      
    ) / BILLIONS
