# Use of 'solar' carrier group in 'heat_production'

- unit = pj
- query =
    SUM(
      V(G(heat_production),input_of_solar_radiation),
      V(G(heat_production),input_of_solar_thermal)
    ) / BILLIONS
