# Use of carrier group 'coal_and_derivatives' in 'heat_production' converter group

- unit = pj
- query =
    SUM(
      V(G(heat_production),input_of_coal),
      V(G(heat_production),input_of_coal_gas)      
    ) / BILLIONS
