# Use of 'coal_and_derivatives' carrier group in 'heat_production' in the energy sector

- unit = pj
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(energy)
        ),
        input_of_coal
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(energy)
        ),
        input_of_coal_gas
      )      
    ) / BILLIONS
