# Use of carrier group 'oil_and_derivatives' in 'heat_production' converter group

- unit = pj
- query =
    SUM(
      V(G(heat_production),input_of_crude_oil),
      V(G(heat_production),input_of_gasoline),
      V(G(heat_production),input_of_diesel),
      V(G(heat_production),input_of_lpg),
      V(G(heat_production),input_of_kerosene),
      V(G(heat_production),input_of_heavy_fuel_oil)      
    ) / BILLIONS
