# Use of 'solar' carrier group in 'heat_production' in the transport sector

- unit = pj
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(transport)
        ),
        input_of_solar_radiation
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(transport)
        ),
        input_of_solar_thermal
      )      
    ) / BILLIONS
