# Use of 'biomass_products' carrier group in 'heat_production' in the buildings sector

- unit = PJ
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(buildings)
        ),
        input_of_biodiesel
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(buildings)
        ),
        input_of_bio_ethanol
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(buildings)
        ),
        input_of_wood_pellets
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(buildings)
        ),
        input_of_bio_lng
      )        
    ) / BILLIONS
