# Use of 'natural_gas_and_derivatives' carrier group in 'heat_production' in the households sector

- unit = pj
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(households)
        ),
        input_of_network_gas
      )      
    ) / BILLIONS
