# Use of 'monetized_heat' carrier group in 'heat_production' in the buildings sector

- unit = pj
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(buildings)
        ),
        input_of_steam_hot_water
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(buildings)
        ),
        input_of_useable_heat
      )      
    ) / BILLIONS
