# Use of 'geothermal' carrier group in 'heat_production' in the agriculture sector

- unit = pj
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(agriculture)
        ),
        input_of_geothermal
      )      
    ) / BILLIONS
