# Use of 'ambient' carrier group in 'heat_production'

- unit = PJ
- query =
    SUM(
      V(G(heat_production),input_of_ambient_heat),
      V(G(heat_production),input_of_ambient_cold),
      V(G(heat_production),input_of_wind),
      V(G(heat_production),input_of_water)
    ) / BILLIONS
