# Use of 'natural_gas_and_derivatives' carrier group in 'heat_production' in the transport sector

- unit = PJ
- query =
    SUM(
      V(
        INTERSECTION(
          G(heat_production),SECTOR(transport)
        ),
        input_of_network_gas
      ),
      V(
        INTERSECTION(
          G(heat_production),SECTOR(transport)
        ),
        input_of_lng
      )      
    ) / BILLIONS
