# Use of 'natural_gas_and_derivatives' carrier group in 'heat_production'

- unit = pj
- query =
    SUM(
      V(G(heat_production),input_of_natural_gas),
      V(G(heat_production),input_of_lng),
      V(G(heat_production),input_of_network_gas),
      V(G(heat_production),input_of_gas_power_fuelmix),
      V(G(heat_production),input_of_compressed_network_gas)
    ) / BILLIONS
