# Use of 'heat' carrier group in 'heat_production'

- unit = PJ
- query =
    SUM(
      V(G(heat_production),input_of_steam_hot_water),
      V(G(heat_production),input_of_useable_heat)
    ) / BILLIONS
