# Use of 'useful_demand' carrier group in 'heat_production'

- unit = PJ
- query =
    SUM(
      V(G(heat_production),input_of_useable_heat),
      V(G(heat_production),input_of_cooling),
      V(G(heat_production),input_of_car_kms),
      V(G(heat_production),input_of_truck_kms),
      V(G(heat_production),input_of_light),
      V(G(heat_production),input_of_not_defined),
      V(G(heat_production),input_of_savings)
    ) / BILLIONS
