# Use of 'natural_gas_and_derivatives' carrier group in 'heat_production'

- unit = pj
- query =
    SUM(
      V(G(heat_production),input_of_natural_gas),
      V(G(heat_production),input_of_low_caloric_gas),
      V(G(heat_production),input_of_high_caloric_gas),
      V(G(heat_production),input_of_lng)
    ) / BILLIONS
