# Query for scenario tools regional overview: direct conversion demand of electricity for synthetic methanol production

- query =
    DIVIDE(
      V(energy_production_methanol_synthesis_synthetic, output_of_methanol),
      BILLIONS
    )
- unit = PJ
