- unit = PJ
- query =
    SUM(
      Q(conversion_loss_methanol_to_crude_oil),
      Q(conversion_loss_methanol_to_diesel),
      Q(conversion_loss_methanol_to_gasoline),
      Q(conversion_loss_methanol_to_heavy_fuel_oil),
      Q(conversion_loss_methanol_to_kerosene),
      Q(conversion_loss_methanol_to_lpg)
    )
