- deprecated_key = chart_co2_emission_rights_103_split_converter_costs_842
# 

- unit = bln_euro

DIVIDE(
SUM(
  V(households_heat_network_connection_steam_hot_water , cost_of_co2_emission_credits)
),BILLIONS)
