# Includes non_energetic emissions from the fertilizer industry (SMR) and
# 'delayed' emissions in molecules_other_utilisation_co2 node
# More non_energetic emissions may be added in the future

- unit = tonne
- query = Q(primary_co2_of_non_energetic_and_delayed_emissions) * MILLIONS
