- unit = PJ
- query =
    import_share = V(EDGE(energy_distribution_kerosene, energy_import_kerosene), share);
    refinery_share = V(EDGE(energy_distribution_kerosene, industry_refinery_transformation_crude_oil), share);
    total_fossil_share = import_share + refinery_share;
    DIVIDE(
      PRODUCT(
        V(bunkers_final_demand_kerosene,output_of_kerosene),
        total_fossil_share),
    BILLIONS)
