# 

- unit = $

PRODUCT(
              V(CARRIER(crude_oil);cost_per_mj),
              Q(caloric_value_crude_oil_mj_per_liter),
             Q(liter_per_barrel),
             Q(dollar_per_euro)
             )