# For lack of better measurement-based data, 
# a small-scale wind turbine is assumed to have the same number of full load hours as a large-scale wind turbine.

- query = V(energy_power_wind_turbine_inland, full_load_hours)
- unit = hours