# A small-scale wind turbine is assumed to have 2400 full load hours
# Source: based on EAZ as mentioned in this source: https://refman.energytransitionmodel.com/publications/2187. 
# Full load hours calculated by dividing the annual electricity production in table 2 (p. 15) by the capacity in table 1 (p. 14)

- query = 2400
- unit = hours