# A typical small-scale wind turbine is assumed to have 15 kW capacity
# Source: based on EAZ as mentioned in this source on p. 12: https://refman.energytransitionmodel.com/publications/2187

- query = 15
- unit = kW