- query = 
    DIVIDE(
        PRODUCT(
            Q(land_use_solar_wind_wind_inland_small_installed_capacity),
            Q(land_use_solar_wind_wind_inland_small_full_load_hours)
        ),
        1000
    )
- unit = GWh