- query = 
    PRODUCT(
        V(energy_power_wind_turbine_inland, 'electricity_output_capacity * number_of_units'),
        DIVIDE(
            Q(land_use_solar_wind_wind_inland_small_capacity_share),
            100
        )
    )
- unit = MW