# Land use per unit is calculated based on a rotor diameter of 12 m 
# and a separating distance of 5x the rotor diameter (square area)
# Sources:
# Rotor diameter: based on EAZ as mentioned in this source on p. 12: https://refman.energytransitionmodel.com/publications/2187
# Separating distance: https://refman.energytransitionmodel.com/publications/2186, p. 10

- query = 
    DIVIDE(
        (12.0 * 5)**2,
        MILLIONS
    )
- unit = km2