# 

- unit = mj

SUM(V(
  heatpump_boiler_households_energetic,
  heat_pump_with_chs_households_energetic,
  heatpump_households_energetic,
  heatpump_using_city_heat_households_energetic,
  solar_panel_for_heating_households_energetic,
  solar_panel_for_hot_water_households_energetic;
    output_of_heat_carriers
))    