# Fixed. Before the costs per MWh were calculated.
# 
# Deleted this :
# 
# PRODUCT(
#   SECS_PER_HOUR,

- unit = euro

  DIVIDE(
    SUM(V(G(electricity_production);total_costs)),
    SUM(V(G(electricity_production);output_of_electricity))
  )
