# 

- unit = pj

future:DIVIDE(SUM(V(electricity_excl_heating_demand_households_energetic;demand),Q(electricity_for_heat),NEG(V(electricity_households_energetic;electricity_inversedflexible_input_link_value))),BILLIONS)