# 

- unit = bln_euro

DIVIDE(SUM(
  V(city_heating_network_energy_energetic ; operation_and_maintenance_cost_fixed),  V(city_heating_network_energy_energetic ; operation_and_maintenance_cost_variable_total)
),BILLIONS)