# Price of coal in USD per tonne

- unit = $

PRODUCT(
              V(CARRIER(coal);cost_per_mj),
              Q(caloric_value_coal_mj_per_kg),
             Q(kg_per_tonne),
             Q(dollar_per_euro)
             )