# 

- unit = converters

V(
halogen_stove_households_energetic,
induction_stove_households_energetic,
electric_stove_households_energetic,
gas_stove_households_energetic,
biomass_cooking_households_energetic
)