# As of may 4, the costs are now minimum 0, so the query cannot return a negative value.

- unit = euro

MAX(
 SUM(
  PRODUCT( V(CARRIER(lpg); cost_per_mj), V(lpg_production_transport; output_of_lpg) ),
  PRODUCT( V(CARRIER(diesel); cost_per_mj), V(diesel_production_transport; output_of_diesel) ),
  PRODUCT( V(CARRIER(gasoline); cost_per_mj), V(gasoline_production_transport; output_of_gasoline) ),
  NEG( PRODUCT( V(CARRIER(crude_oil); cost_per_mj), Q(oil_use_refinery) ) )
 ),
 0
)