# Returns the converters which produce electricity using coal.
# 
# It works by looking to converters directly fed by the "Coal distribution" converter that have output of electricity.

- unit = converters

V(
  FILTER(
    V(
      PARENTS(V(coal_distribution_energy))
      )
   ;electricity_output_conversion && electricity_output_conversion > 0)
  )