# All the converters of which for example the number is shown in supply/fossil heat

- unit = converters

V(central_heating_households_energetic,gas_burner_agri_agriculture_energetic, gas_burner_other_other_energetic, gas_fired_heater_buildings_energetic,gas_burner_industry_industry_energetic,gas_fired_heater_households_energetic)