# 

- unit = pj

SUM(
Q(households_biomass_primary_demand),
Q(households_oil_primary_demand),
Q(households_uranium_primary_demand),
Q(households_coal_primary_demand),
Q(households_lignite_primary_demand),
Q(households_waste_primary_demand),
Q(households_non_e_primary_demand),
Q(all_biofuels_households_primary),
Q(households_imported_e_primary_demand)
)