# 

- unit = converters

V(
solar_panel_for_hot_water_households_energetic,
gas_boiler_households_energetic,
electric_boiler_households_energetic,
heatpump_boiler_households_energetic,
cv_hot_water_households_energetic,
biomass_boiler_households_energetic,
coal_boiler_households_energetic,
oil_boiler_households_energetic,
heatpump_boiler_using_city_heat_households_energetic
)