# 

- unit = mw

SUM(
  MAX(
    SUM(
      Q(pl_hv_mv_trafo_delta_capacity_max), 
      V(mv_hv_transformer_energy; network_capacity_used_in_mw)
    ),
    V(mv_hv_transformer_energy; network_capacity_available_in_mw)
  ),
  NEG(
    V(mv_hv_transformer_energy; network_capacity_available_in_mw)
  )
)