# This returns the number of kwh electricity used in households per year, without the local production of electricity.

- unit = 

DIVIDE(DIVIDE(SUM(V(available_electricity_households;electricity_flexible_input_link_value - electricity_inversedflexible_output_link_value)
),3.6),AREA(number_households))