# For the investment costs HV MV transformer, an extra 'if' statement is added (Q(peak_load_delta_on_mv_hv_transformer) ). For this transformer it is important to check which value is the largest:
# 1. Impact from demand technologies from LV grid
# 2. Impact from supply technologies attached to the HV MV transformer

- unit = euro

PRODUCT(
 Q(pl_hv_mv_trafo_capacity_needed),
V(mv_hv_transformer_energy;network_expansion_costs_in_euro_per_mw)
)