# The share of steam/hot water in the supply of household heat demand, excluding geothermal

- unit = factor

DIVIDE(
SUM(V(CHILDREN(V(heating_demand_households_energetic));input_of_steam_hot_water),NEG(V(collective_geothermal_households_energetic;demand)))
,
SUM(V(CHILDREN(V(heating_demand_households_energetic));demand))
)