# 

- unit = pj

SUM(
Q(transport_biomass_primary_demand),
Q(transport_oil_primary_demand),
Q(transport_uranium_primary_demand),
Q(transport_coal_primary_demand),
Q(transport_lignite_primary_demand),
Q(transport_non_e_primary_demand),
Q(transport_waste_primary_demand),
Q(all_biofuels_transport_primary),
Q(transport_imported_e_primary_demand)
)