#

- deprecated_key = chart_ambient_heat_42_heat_production_329
- unit = pj

DIVIDE(PRODUCT(DIVIDE(SUM(V(G(heat_production),input_of_ambient_carriers)),SUM(V(G(heat_production),output_of_heat_and_cooling_carriers))),SUM(V(G(heat_production),output_of_heat_and_cooling_carriers))),BILLIONS)