# Final consumption of oil and oil products in international transport - international navigation (energetic use only).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Oil and oil products -- crude_oil? || gasoline? || diesel? || lpg? || kerosene? || heavy_fuel_oil? || naphtha? || refinery_gas? || pyrolysis_oil?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_oil_and_oil_products_in_bunkers_international_navigation_energetic)
