# Final consumption of oil and oil products in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Oil and oil products -- gasoline? || diesel? || lpg? || kerosene? || heavy_fuel_oil? || naphtha? || refinery_gas? || pyrolysis_oil? + crude_oil? x Q(share_of_non_biogenic_in_industry_final_demand_crude_oil_energetic)
# Use type:    Energetic -- energetic?
#
# Exception: includes the non-biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    Q(final_consumption_of_oil_and_oil_products_in_industry_ict_energetic)
