- query = 
    DIVIDE(
      DIVIDE(
        PRODUCT(Q(energy_flexibility_hv_opac_annual_input),BILLIONS),
        MJ_PER_MWH
      ),
      Q(energy_flexibility_hv_opac_storage_volume)
    )
- unit = number
