- query = 
    DIVIDE(
      DIVIDE(
        PRODUCT(Q(energy_flexibility_pumped_storage_annual_input),BILLIONS),
        MJ_PER_MWH
      ),
      Q(energy_flexibility_pumped_storage_storage_volume)
    )
- unit = number
