- query = 
    DIVIDE(
      DIVIDE(
        PRODUCT(Q(energy_flexibility_mv_batteries_annual_input),BILLIONS),
        MJ_PER_MWH
      ),
      Q(energy_flexibility_mv_batteries_storage_volume)
    )
- unit = number
