- query = 
    DIVIDE(
      DIVIDE(
        PRODUCT(Q(transport_truck_flexibility_p2p_electricity_annual_input),BILLIONS),
        MJ_PER_MWH
      ),
      Q(transport_truck_flexibility_p2p_electricity_storage_volume)
    )
- unit = number
