# The CAPEX of the future offshore net

- query =
          SUM(
              QUERY_FUTURE(offshore_net_additional_capital_costs),
              QUERY_FUTURE(offshore_net_additional_depreciation_costs)
          )


- unit = euro
