# The delta (difference) between the present and the future costs of the offshore net.

- query =
          SUM(
              QUERY_FUTURE(offshore_net_capex),
              QUERY_FUTURE(offshore_net_opex)
          )

- unit = euro
