# The total costs of the network calculation

- query =
          SUM(
              QUERY_FUTURE(offshore_net_additional_capital_costs),
              QUERY_FUTURE(offshore_net_additional_operation_and_maintenance_costs)
          )

- unit = euro
