# The total costs of the network calculation

- query = QUERY_FUTURE(offshore_net_capacity_delta_present_future) * INPUT_VALUE(costs_infrastructure_electricity_offshore_net) * THOUSANDS
- unit = euro
