# The depreciation costs of the future offshore net

- query =
          SUM(
              QUERY_FUTURE(offshore_net_total_investment_costs) / V(energy_power_hv_network_electricity,technical_lifetime)
          )


- unit = euro
