# The OPEX of the future offshore net, consisting of operation and maintenance costs

- query =
          SUM(
              QUERY_FUTURE(offshore_net_costs_delta_present_future_operation_and_maintenance_costs)
          )

- unit = euro
