# The operations and maintenance costs of the future offshore net, consisting of a fixed component only

- query = V(energy_power_hv_network_electricity,fixed_operation_and_maintenance_costs_per(:mw_input)) * QUERY_FUTURE(offshore_net_capacity_delta_present_future)


- unit = euro
