# The total costs of the network calculation

- query =
          SUM(
              QUERY_PRESENT(offshore_net_total_costs_present),
              QUERY_FUTURE(offshore_net_costs_delta_present_future)
          )

- unit = euro
