# Supply for heat network

- unit = PJ
- query =
    SUM(
        Q(energy_heater_for_heat_network_coal_in_heat_network_mekko),
        Q(energy_chp_ultra_supercritical_cofiring_coal_in_heat_network_mekko),
        Q(energy_chp_ultra_supercritical_lignite_in_heat_network_mekko)
    )