# All series of the mekko_of_primary_demand chart
- query =
    SUM(
        Q(energy_import_hydrogen_for_mekko),
        Q(energy_hydrogen_steam_methane_reformer_for_mekko),
        Q(energy_hydrogen_steam_methane_reformer_ccs_for_mekko),
        Q(energy_hydrogen_flexibility_p2g_electricity_for_mekko),
        Q(energy_hydrogen_electrolysis_solar_electricity_for_mekko),
        Q(energy_hydrogen_electrolysis_wind_electricity_for_mekko),
        Q(energy_hydrogen_biomass_gasification_ccs_for_mekko),
        Q(energy_hydrogen_biomass_gasification_for_mekko)
    )
- unit = PJ
