# All series of the mekko_of_primary_demand chart
- query =
    SUM(
        Q(agriculture_final_demand_hydrogen_for_mekko),
        Q(industry_final_demand_hydrogen_for_mekko),
        Q(industry_final_demand_for_chemical_fertilizers_hydrogen_non_energetic_for_mekko),
        Q(energy_power_plants_hydrogen_for_mekko),
        Q(energy_export_hydrogen_for_mekko),
        Q(losses_hydrogen_energetic_for_mekko),
        Q(transport_final_demand_hydrogen_for_mekko),
        Q(households_inidividual_hybrid_heat_pump_hydrogen_for_mekko),
        Q(industry_final_demand_for_chemical_other_hydrogen_non_energetic_for_mekko),
        Q(energy_heat_from_hydrogen_for_mekko),
        Q(energy_synthetic_products_from_hydrogen_for_mekko)
    )
- unit = PJ
