# All series of the mekko_of_primary_demand chart
- query =
    SUM(
        Q(solid_biomass_industry_in_mekko_of_primary_demand),
        Q(oil_industry_in_mekko_of_primary_demand ),
        Q(gas_industry_in_mekko_of_primary_demand),
        Q(uranium_industry_in_mekko_of_primary_demand),
        Q(coal_industry_in_mekko_of_primary_demand),
        Q(lignite_industry_in_mekko_of_primary_demand),
        Q(waste_industry_in_mekko_of_primary_demand),
        Q(bio_fuels_industry_in_mekko_of_primary_demand),
        Q(greengas_and_biogas_industry_in_mekko_of_primary_demand),
        Q(solid_biomass_households_in_mekko_of_primary_demand),
        Q(oil_households_in_mekko_of_primary_demand),
        Q(gas_households_in_mekko_of_primary_demand),
        Q(uranium_households_in_mekko_of_primary_demand),
        Q(coal_households_in_mekko_of_primary_demand),
        Q(lignite_households_in_mekko_of_primary_demand),
        Q(waste_households_in_mekko_of_primary_demand),
        Q(bio_fuels_households_in_mekko_of_primary_demand),
        Q(solid_biomass_buildings_in_mekko_of_primary_demand),
        Q(oil_transport_in_mekko_of_primary_demand),
        Q(gas_transport_in_mekko_of_primary_demand),
        Q(uranium_transport_in_mekko_of_primary_demand),
        Q(coal_transport_in_mekko_of_primary_demand),
        Q(lignite_transport_in_mekko_of_primary_demand),
        Q(waste_transport_in_mekko_of_primary_demand),
        Q(bio_fuels_transport_in_mekko_of_primary_demand),
        Q(greengas_and_biogas_transport_in_mekko_of_primary_demand),
        Q(greengas_and_biogas_households_in_mekko_of_primary_demand),
        Q(solid_biomass_transport_in_mekko_of_primary_demand),
        Q(oil_agriculture_in_mekko_of_primary_demand),
        Q(uranium_agriculture_in_mekko_of_primary_demand),
        Q(gas_agriculture_in_mekko_of_primary_demand),
        Q(coal_agriculture_in_mekko_of_primary_demand),
        Q(lignite_agriculture_in_mekko_of_primary_demand),
        Q(waste_agriculture_in_mekko_of_primary_demand),
        Q(bio_fuels_agriculture_in_mekko_of_primary_demand),
        Q(greengas_and_biogas_agriculture_in_mekko_of_primary_demand),
        Q(solid_biomass_agriculture_in_mekko_of_primary_demand),
        Q(oil_other_in_mekko_of_primary_demand),
        Q(gas_other_in_mekko_of_primary_demand),
        Q(uranium_other_in_mekko_of_primary_demand),
        Q(coal_other_in_mekko_of_primary_demand),
        Q(lignite_other_in_mekko_of_primary_demand),
        Q(waste_other_in_mekko_of_primary_demand),
        Q(bio_fuels_other_in_mekko_of_primary_demand),
        Q(greengas_and_biogas_other_in_mekko_of_primary_demand),
        Q(sustainable_electricity_industry_in_mekko_of_primary_demand),
        Q(sustainable_electricity_other_in_mekko_of_primary_demand),
        Q(sustainable_electricity_agriculture_in_mekko_of_primary_demand),
        Q(sustainable_electricity_transport_in_mekko_of_primary_demand),
        Q(sustainable_electricity_households_in_mekko_of_primary_demand),
        Q(imported_electricity_industry_in_mekko_of_primary_demand),
        Q(imported_electricity_households_in_mekko_of_primary_demand),
        Q(imported_electricity_agriculture_in_mekko_of_primary_demand),
        Q(imported_electricity_other_in_mekko_of_primary_demand),
        Q(imported_electricity_transport_in_mekko_of_primary_demand),
        Q(solid_biomass_other_in_mekko_of_primary_demand),
        Q(oil_buildings_in_mekko_of_primary_demand),
        Q(gas_buildings_in_mekko_of_primary_demand),
        Q(uranium_buildings_in_mekko_of_primary_demand),
        Q(coal_buildings_in_mekko_of_primary_demand),
        Q(lignite_buildings_in_mekko_of_primary_demand),
        Q(waste_buildings_in_mekko_of_primary_demand),
        Q(bio_fuels_buildings_in_mekko_of_primary_demand),
        Q(greengas_and_biogas_buildings_in_mekko_of_primary_demand),
        Q(sustainable_electricity_buildings_in_mekko_of_primary_demand),
        Q(imported_electricity_buildings_in_mekko_of_primary_demand),
        Q(lng_agriculture_in_mekko_of_primary_demand),
        Q(lng_buildings_in_mekko_of_primary_demand),
        Q(lng_households_in_mekko_of_primary_demand),
        Q(lng_industry_in_mekko_of_primary_demand),
        Q(lng_other_in_mekko_of_primary_demand),
        Q(lng_transport_in_mekko_of_primary_demand),
        Q(sustainable_electricity_export_and_curtailment_in_mekko_of_primary_demand),
        Q(imported_electricity_export_and_curtailment_in_mekko_of_primary_demand),
        Q(oil_export_and_curtailment_in_mekko_of_primary_demand),
        Q(gas_export_and_curtailment_in_mekko_of_primary_demand),
        Q(uranium_export_and_curtailment_in_mekko_of_primary_demand),
        Q(coal_export_and_curtailment_in_mekko_of_primary_demand),
        Q(lignite_export_and_curtailment_in_mekko_of_primary_demand),
        Q(waste_export_and_curtailment_in_mekko_of_primary_demand),
        Q(bio_fuels_export_and_curtailment_in_mekko_of_primary_demand),
        Q(greengas_and_biogas_export_and_curtailment_in_mekko_of_primary_demand),
        Q(solid_biomass_export_and_curtailment_in_mekko_of_primary_demand),
        Q(lng_export_and_curtailment_in_mekko_of_primary_demand),
        Q(solid_biomass_bunkers_in_mekko_of_primary_demand),
        Q(oil_bunkers_in_mekko_of_primary_demand),
        Q(gas_bunkers_in_mekko_of_primary_demand),
        Q(uranium_bunkers_in_mekko_of_primary_demand),
        Q(coal_bunkers_in_mekko_of_primary_demand),
        Q(lignite_bunkers_in_mekko_of_primary_demand),
        Q(waste_bunkers_in_mekko_of_primary_demand),
        Q(bio_fuels_bunkers_in_mekko_of_primary_demand),
        Q(greengas_and_biogas_bunkers_in_mekko_of_primary_demand),
        Q(sustainable_electricity_bunkers_in_mekko_of_primary_demand),
        Q(imported_electricity_bunkers_in_mekko_of_primary_demand),
        Q(lng_bunkers_in_mekko_of_primary_demand),
        Q(imported_hydrogen_industry_in_mekko_of_primary_demand),
        Q(imported_hydrogen_households_in_mekko_of_primary_demand),
        Q(imported_hydrogen_bunkers_in_mekko_of_primary_demand),
        Q(imported_hydrogen_agriculture_in_mekko_of_primary_demand),
        Q(imported_hydrogen_other_in_mekko_of_primary_demand),
        Q(imported_hydrogen_transport_in_mekko_of_primary_demand),
        Q(imported_hydrogen_buildings_in_mekko_of_primary_demand),
        Q(imported_hydrogen_export_and_curtailment_in_mekko_of_primary_demand),
        Q(renewable_heat_industry_in_mekko_of_primary_demand),
        Q(renewable_heat_households_in_mekko_of_primary_demand),
        Q(renewable_heat_bunkers_in_mekko_of_primary_demand),
        Q(renewable_heat_agriculture_in_mekko_of_primary_demand),
        Q(renewable_heat_other_in_mekko_of_primary_demand),
        Q(renewable_heat_transport_in_mekko_of_primary_demand),
        Q(renewable_heat_buildings_in_mekko_of_primary_demand),
        Q(renewable_heat_export_and_curtailment_in_mekko_of_primary_demand),
        Q(imported_heat_industry_in_mekko_of_primary_demand),
        Q(imported_heat_households_in_mekko_of_primary_demand),
        Q(imported_heat_bunkers_in_mekko_of_primary_demand),
        Q(imported_heat_agriculture_in_mekko_of_primary_demand),
        Q(imported_heat_other_in_mekko_of_primary_demand),
        Q(imported_heat_transport_in_mekko_of_primary_demand),
        Q(imported_heat_buildings_in_mekko_of_primary_demand),
        Q(imported_heat_export_and_curtailment_in_mekko_of_primary_demand),
        Q(imported_ammonia_industry_in_mekko_of_primary_demand),
        Q(imported_ammonia_households_in_mekko_of_primary_demand),
        Q(imported_ammonia_bunkers_in_mekko_of_primary_demand),
        Q(imported_ammonia_agriculture_in_mekko_of_primary_demand),
        Q(imported_ammonia_other_in_mekko_of_primary_demand),
        Q(imported_ammonia_transport_in_mekko_of_primary_demand),
        Q(imported_ammonia_buildings_in_mekko_of_primary_demand),
        Q(imported_ammonia_export_and_curtailment_in_mekko_of_primary_demand)
    ) * BILLIONS
- unit = MJ
