# Non-energetic final demand of the 'geothermal' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(aggregated_other_industry_other)
            ),
            "! energetic?"
          ),
          geothermal?
        ),
        value
      )
    ) / BILLIONS
