# Final demand of the 'heat' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(aggregated_other_industry_other)
          ),
          steam_hot_water?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(aggregated_other_industry_other)
          ),
          useable_heat?
        ),
        value
      )
    ) / BILLIONS
