# Final demand of the 'hydrogen' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(aggregated_other_industry_other)
          ),
          hydrogen?
        ),
        value
      )
    ) / BILLIONS
