# Final demand of the 'natural_gas_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(aggregated_other_industry_other)
          ),
          network_gas?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(aggregated_other_industry_other)
          ),
          lng?
        ),
        value
      )
    ) / BILLIONS
