# Use of carrier group 'biomass_products' in housholds heat

- unit = pj
- query =
    SUM(
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_biodiesel),
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_bio_ethanol),
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_wood_pellets)      
    ) / BILLIONS
