# Steam hot water supplied by central heat networks in agriculture
#
# OLD QUERY:
#
# - unit = PJ
# - query = 
#    DIVIDE(
#        SUM(
#            V(agriculture_final_demand_ht_central_steam_hot_water,demand),
#            V(agriculture_final_demand_mt_steam_hot_water, demand)
#        ),
#        BILLIONS
#    )

- unit = PJ
- query = 
    DIVIDE(
      SUM(V(
        FILTER(
          FILTER(
            EG(final_demand),"sector == :agriculture"
          ),
          "steam_hot_water? || useable_heat?"
        ),
        value
      ))
      - V(agriculture_heat_unused_steam_hot_water,demand),
      BILLIONS
    )
