# Use of carrier group 'coal_and_derivatives' in housholds heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_coal),
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_coal_gas)      
    ) / BILLIONS
