# Use of carrier group 'electricity' in housholds heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_electricity),
      V(agriculture_flexibility_p2h_hydrogen_electricity,input_of_electricity),
      V(agriculture_flexibility_p2h_network_gas_electricity,input_of_electricity)      
    ) / BILLIONS
