# Use of carrier group 'heat' in housholds heat

- unit = pj
- query =
    SUM(
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_steam_hot_water),
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_useable_heat)      
    ) / BILLIONS
