# Use of carrier group 'hydrogen' in agriculture

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_hydrogen),
      V(CHILDREN(V(agriculture_hydrogen_hybrid_heat)),input_of_hydrogen),
      V(CHILDREN(V(agriculture_network_gas_hybrid_heat)),input_of_hydrogen)    
    ) / BILLIONS
