# Use of carrier group 'solar' in housholds heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_solar_radiation),
      V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_solar_thermal)      
    ) / BILLIONS
