# including the green gas used in the gas burners

- unit = mj

SUM(
V(Q(households_hot_water_converters);input_of_biomass),
V(Q(households_hot_water_converters);input_of_biofuel),
V(Q(households_hot_water_converters);input_of_greengas),
V(Q(households_hot_water_converters);input_of_biodiesel),
V(Q(households_hot_water_converters);input_of_bio_ethanol),
V(Q(households_hot_water_converters);input_of_algae_diesel),
V(Q(households_hot_water_converters);input_of_biogas),
V(Q(households_hot_water_converters);input_of_natural_gas*sustainability_share)
)