# 

- unit = factor

SUM(
SUM(
V(cv_hot_water_households_energetic,
heatpump_boiler_households_energetic;
share_of_hot_water_devices_households_energetic
)
,
PRODUCT(
V(steam_hot_water_households_energetic;share_of_hot_water_devices_households_energetic),
V(micro_chp_hot_water_households_energetic;share_of_steam_hot_water_households_energetic)
),

PRODUCT(
V(steam_hot_water_households_energetic;share_of_hot_water_devices_households_energetic),
V(heatpump_boiler_using_city_heat_households_energetic;share_of_steam_hot_water_households_energetic)
)
)

)
