# Non-energetic final demand of the 'ambient' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand), "ambient_heat? || ambient_cold?"
          ),
          "!energetic?"
        ),
        value
      )
    ) / BILLIONS
