# Energetic final demand of the 'greengas' carrier group in industry (excl. ICT)

- unit = PJ
- query =
    PRODUCT(
      SUM(
        V(
          FILTER(
            FILTER(
              EG(final_demand), "network_gas? || compressed_network_gas?"
            ),
            "!energetic?"
          ),
          value
        ),
      ),
      Q(share_of_sustainable_gas_in_gas_network)
    ) / BILLIONS
