# Total cost of hydrogen production by industry transformation

- query =
    COALESCE_CURVE(nil,default=Q(production_costs_per_mwh_hydrogen_by_chemical_refineries_transformation),length = 8760)
            