# Total cost of hydrogen production from stored hydrogen in depleted gas field per MWh produced hydrogen

- query =
    COALESCE_CURVE(nil,default=Q(production_costs_per_mwh_hydrogen_by_storage_depleted_gas_field),length = 8760)
            