# Total cost of hydrogen production by autothermal reforming per kg produced hydrogen
# Energy density of h2 is 120.1 MJ per kg

- query = 
    COALESCE_CURVE(nil,default=Q(production_costs_per_mwh_hydrogen_by_autothermal_reformer_dispatchable),length = 8760)
            