# Total cost of hydrogen production from offshore wind per MWh produced hydrogen

- query =
    COALESCE_CURVE(nil,default=Q(production_costs_per_mwh_hydrogen_by_hybrid_offshore_wind_turbine),length = 8760)
            