# Total cost of hydrogen production by ammonia reforming per MWh produced hydrogen

- query =   
    COALESCE_CURVE(nil,default=Q(production_costs_per_mwh_industry_residual_hydrogen),length = 8760)
            