# Total cost of hydrogen production by biomass gasification + ccs per MWh produced hydrogen

- query =
    COALESCE_CURVE(nil,default=Q(production_costs_per_mwh_hydrogen_by_p2g),length = 8760)
            