# Total cost of hydrogen production by biomass gasification per MWh produced hydrogen

- query = 
    COALESCE_CURVE(nil,default=Q(production_costs_per_mwh_hydrogen_by_biomass_gasification),length = 8760)
            
