- query =
    SUM_CURVES(V(
      INTERSECTION(
        FILTER(ALL(),"hydrogen && (hydrogen.type == :consumer || hydrogen.type == :export)"),
        EXCLUDE(SECTOR(agriculture),G(electricity_production))
      ),
      hydrogen_input_curve
    ))
- unit = curve
