# This query obtains the node of methanol synthesis from dry biomass and retrieves
# the hydrogen input curve.

- query =
    SUM_CURVES(
      V(
        energy_production_methanol_synthesis_dry_biomass_ccs,
        hydrogen_input_curve
      )
    )
- unit = curve
