- query =
    SUM_CURVES(V(
      INTERSECTION(
        FILTER(ALL(),"hydrogen && (hydrogen.type == :consumer || hydrogen.type == :export)"),
        FILTER(
          INTERSECTION(SECTOR(industry), USE(energetic)),
          "electricity_output_conversion == 0.0 && steam_hot_water_output_conversion == 0.0"
        )
      ),
      hydrogen_input_curve
    ))
- unit = curve
