- query =
    SUM(
      Q(conversion_loss_crude_oil_to_crude_oil),
      Q(conversion_loss_crude_oil_to_diesel),
      Q(conversion_loss_crude_oil_to_gasoline),
      Q(conversion_loss_crude_oil_to_heavy_fuel_oil),
      Q(conversion_loss_crude_oil_to_kerosene),
      Q(conversion_loss_crude_oil_to_lpg),
      Q(conversion_loss_crude_oil_to_refinery_gas),
      Q(conversion_loss_diesel_to_diesel),
      Q(conversion_loss_gasoline_to_gasoline),
      Q(conversion_loss_kerosene_to_kerosene)
    )
- unit = PJ
