# Direct conversion input of imported LOHC for central hydrogen production

- query =
    DIVIDE(
      SUM(
        V(
          G(lohc_supply),
          "hydrogen_output_conversion / (1 - loss_output_conversion) * input_of_imported_lohc"
        )
      ), 
      BILLIONS
    )
- unit = PJ
