# Direct conversion input of hydrogen for central electricity production

- query = 
    DIVIDE(
      SUM(
        V(
          G(hydrogen_production),
          "hydrogen_output_conversion / (1 - (loss_output_conversion + residual_heat_output_conversion))  * input_of_electricity"
        )
      ), 
      BILLIONS
    )
- unit = PJ
