# Direct conversion input of compressed network gas for central hydrogen production

- query =
    DIVIDE(
      SUM(
        V(
          G(hydrogen_production),
          "hydrogen_output_conversion / (1 - loss_output_conversion) * input_of_compressed_network_gas"
        )
      ), 
      BILLIONS
    )
- unit = PJ
