# Direct conversion input of imported liquid hydrogen for central hydrogen production

- query =
    DIVIDE(
      SUM(
        V(
          G(liquid_hydrogen_supply),
          "hydrogen_output_conversion / (1 - loss_output_conversion) * input_of_imported_liquid_hydrogen"
        )
      ), 
      BILLIONS
    )
- unit = PJ
