# Direct conversion input of gas and gas derivatives waste for central hydrogen production

- query = 
    SUM(
      Q(conversion_from_natural_gas_to_hydrogen),
      Q(conversion_from_lng_to_hydrogen),
      PRODUCT(Q(conversion_from_network_gas_to_hydrogen),Q(share_of_natural_gas_in_gas_network)),
      PRODUCT(Q(conversion_from_compressed_network_gas_to_hydrogen),Q(share_of_natural_gas_in_gas_network))
    )
- unit = PJ
