# Direct conversion input of biomass products for central hydrogen production

- query =
    SUM(
      Q(conversion_from_green_gas_to_hydrogen),
      PRODUCT(Q(conversion_from_network_gas_to_hydrogen),Q(share_of_sustainable_gas_in_gas_network)),
      PRODUCT(Q(conversion_from_compressed_network_gas_to_hydrogen),Q(share_of_sustainable_gas_in_gas_network)),
      Q(conversion_from_biofuels_to_hydrogen)
    )
- unit = PJ
