# Direct conversion input of biomass products for central hydrogen production

- query =
    SUM(
      Q(conversion_from_biodiesel_to_hydrogen),
      Q(conversion_from_bio_ethanol_to_hydrogen),
      Q(conversion_from_bio_kerosene_to_hydrogen),
      Q(conversion_from_wood_pellets_to_hydrogen),
      Q(conversion_from_torrefied_biomass_pellets_to_hydrogen),
      Q(conversion_from_bio_lng_to_hydrogen),
      Q(conversion_from_bio_oil_to_hydrogen)
    )
- unit = PJ
