# Final demand of steam hot water of LT temperature

- unit = PJ
- query =
    DIVIDE(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(lt_heat)),"sector == :energy"
          ),
          steam_hot_water?
        ),
        value
      ),
      BILLIONS
    )
