# Returns the capacity of engine diesel power plants.
- query = 
        PRODUCT(
  		V(energy_power_engine_diesel,number_of_units),
  		V(energy_power_engine_diesel,electricity_output_capacity)	
  		)
- unit = MW

