- query =
    Q(electrolyser_onshore_revenue_in_flexible_demand_economic_performance_table)
    - Q(electrolyser_onshore_capex_in_flexible_demand_economic_performance_table)
    - Q(electrolyser_onshore_opex_in_flexible_demand_economic_performance_table)
- unit = EUR/MWh
