- query =
    Q(electrolyser_offshore_revenue_in_flexible_demand_economic_performance_table)
    - Q(electrolyser_offshore_capex_in_flexible_demand_economic_performance_table)
    - Q(electrolyser_offshore_opex_in_flexible_demand_economic_performance_table)
- unit = EUR/MWh
