- query =
    Q(p2h_boiler_food_revenue_in_power_plant_economic_performance_table)
    - Q(p2h_boiler_food_capex_in_power_plant_economic_performance_table)
    - Q(p2h_boiler_food_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
