- query =
    Q(p2h_heatpump_mt_revenue_in_power_plant_economic_performance_table)
    - Q(p2h_heatpump_mt_capex_in_power_plant_economic_performance_table)
    - Q(p2h_heatpump_mt_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
