- query =
    Q(p2h_boiler_refineries_revenue_in_power_plant_economic_performance_table)
    - Q(p2h_boiler_refineries_capex_in_power_plant_economic_performance_table)
    - Q(p2h_boiler_refineries_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
