# This gquery calculates the weighted average of revenue based on heat production of P2H technologies

- query =
    DIVIDE(
      SUM(
        V(
          agriculture_flexibility_p2h_network_gas_electricity,
          agriculture_flexibility_p2h_hydrogen_electricity,
          "output_of_useable_heat * revenue_per_mwh"
        )
      ),
      SUM(
        V(
          agriculture_flexibility_p2h_network_gas_electricity,
          agriculture_flexibility_p2h_hydrogen_electricity,
          output_of_useable_heat
        )
      )
    )
- unit = EUR/MWh
