- query =
    Q(p2h_boiler_mt_revenue_in_flexible_demand_economic_performance_table)
    - Q(p2h_boiler_mt_capex_in_flexible_demand_economic_performance_table)
    - Q(p2h_boiler_mt_opex_in_flexible_demand_economic_performance_table)
- unit = EUR/MWh
