# This gquery calculates capex of P2H technologies per MWh output

- query =
     DIVIDE(
      SUM(
        V(
          industry_chemicals_other_flexibility_p2h_network_gas_electricity,
          industry_chemicals_other_flexibility_p2h_hydrogen_electricity,
          capital_expenditures_per(:node)
        )
      ),
      SUM(
        V(
          industry_chemicals_other_flexibility_p2h_network_gas_electricity,
          industry_chemicals_other_flexibility_p2h_hydrogen_electricity,
          "output_of_useable_heat / MJ_PER_MWH"
        )
      )
    )
- unit = EUR/MWh
