- query =
    Q(p2h_boiler_agriculture_revenue_in_flexible_demand_economic_performance_table)
    - Q(p2h_boiler_agriculture_capex_in_flexible_demand_economic_performance_table)
    - Q(p2h_boiler_agriculture_opex_in_flexible_demand_economic_performance_table)
- unit = EUR/MWh
