- query =
    Q(p2h_heatpump_ht_revenue_in_power_plant_economic_performance_table)
    - Q(p2h_heatpump_ht_capex_in_power_plant_economic_performance_table)
    - Q(p2h_heatpump_ht_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
