- query =
    Q(p2h_heatpump_ht_revenue_in_flexible_demand_economic_performance_table)
    - Q(p2h_heatpump_ht_capex_in_flexible_demand_economic_performance_table)
    - Q(p2h_heatpump_ht_opex_in_flexible_demand_economic_performance_table)
- unit = EUR/MWh
