- query =
    Q(p2h_boiler_chemicals_revenue_in_power_plant_economic_performance_table)
    - Q(p2h_boiler_chemicals_capex_in_power_plant_economic_performance_table)
    - Q(p2h_boiler_chemicals_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
