- query =
    Q(p2h_boiler_paper_revenue_in_power_plant_economic_performance_table)
    - Q(p2h_boiler_paper_capex_in_power_plant_economic_performance_table)
    - Q(p2h_boiler_paper_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
