- query =
    Q(synthetic_kerosene_revenue_in_power_plant_economic_performance_table)
    - Q(synthetic_kerosene_capex_in_power_plant_economic_performance_table)
    - Q(synthetic_kerosene_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
