- query =
  {
    capacity:        Q(capacity_energy_imported_hydrogen_baseload_for_h2_chart),
    operating_costs: Q(costs_per_mwh_hydrogen_by_import),
    production:      V(energy_imported_hydrogen_baseload, output_of_hydrogen)
  }
