- query =
  {
    capacity:        Q(capacity_energy_hydrogen_storage_depleted_gas_field_for_h2_chart),
    operating_costs: Q(production_costs_per_mwh_hydrogen_by_storage_depleted_gas_field),
    production:      V(energy_hydrogen_storage_depleted_gas_field, output_of_hydrogen)
  }
