- query =
  {
    capacity:        Q(capacity_energy_hydrogen_storage_salt_cavern_for_h2_chart),
    operating_costs: Q(production_costs_per_mwh_hydrogen_by_storage_salt_cavern),
    production:      V(energy_hydrogen_storage_salt_cavern, output_of_hydrogen)
  }
