- query =
  {
    capacity:        Q(capacity_energy_imported_hydrogen_backup_for_h2_chart),
    operating_costs: Q(costs_per_mwh_hydrogen_by_import),
    production:      V(energy_imported_hydrogen_backup, output_of_hydrogen)
  }
