- query =
  {
    capacity:        Q(capacity_energy_hydrogen_liquid_hydrogen_regasifier_for_h2_chart),
    operating_costs: Q(production_costs_per_mwh_hydrogen_by_liquid_hydrogen_regasifier),
    production:      V(energy_hydrogen_liquid_hydrogen_regasifier, output_of_hydrogen)
  }
