- query =
  {
    capacity:        Q(capacity_energy_hydrogen_hybrid_wind_turbine_offshore_for_h2_chart),
    operating_costs: Q(production_costs_per_mwh_hydrogen_by_hybrid_offshore_wind_turbine),
    production:      V(energy_hydrogen_hybrid_electrolysis_wind_electricity, output_of_hydrogen)
  }
