- query =
  {
    capacity:        Q(capacity_energy_hydrogen_flexibility_p2g_electricity_for_h2_chart),
    operating_costs: Q(production_costs_per_mwh_hydrogen_by_p2g),
    production:      V(energy_hydrogen_flexibility_p2g_electricity, output_of_hydrogen)
  }
