- query =
  {
    capacity:        Q(capacity_energy_hydrogen_ammonia_reformer_dispatchable_for_h2_chart),
    operating_costs: Q(production_costs_per_mwh_hydrogen_by_ammonia_reformer_dispatchable)
  }
