- query =
  {
    capacity:        Q(capacity_energy_hydrogen_lohc_reformer_for_h2_chart),
    operating_costs: Q(production_costs_per_mwh_hydrogen_by_lohc_reformer),
    production:      V(energy_hydrogen_lohc_reformer, output_of_hydrogen)
  }
