- query =
  {
    capacity:        Q(capacity_energy_hydrogen_biomass_gassification_for_h2_chart),
    operating_costs: Q(production_costs_per_mwh_hydrogen_by_biomass_gasification),
    production:      V(energy_hydrogen_biomass_gasification, output_of_hydrogen)
  }
