# Returns the number of hybrid air water heat pumps for heating on hydrogen in buildings

- query = V(buildings_space_heater_hybrid_crude_oil_heatpump_air_water_electricity, number_of_units)
- unit = number
