# Returns the number of water water heat pumps with thermal storage for cooling in buildings

- query = V(buildings_cooling_collective_heatpump_water_water_ts_electricity, number_of_units)
- unit = number
