# Returns the number of hybrid air water heat pumps for hot water on hydrogen in households

- query = V(households_water_heater_hybrid_crude_oil_heatpump_air_water_electricity, number_of_units)
- unit = number
