# Returns the number of hybrid air water heat pumps for space heating on gas in households

- query = V(households_space_heater_hybrid_heatpump_air_water_electricity, number_of_units)
- unit = number
