# Final consumption from buildings, all carriers (energetic use only).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_buildings_energetic)
