- query = 
    DIVIDE(Q(total_electricity_produced), BILLIONS) + 
    DIVIDE(Q(energy_import_electricity), BILLIONS) + 
    DIVIDE(Q(energy_power_hv_network_shortage), BILLIONS) +     
    - Q(demand_in_source_of_electricity_production)
- unit = PJ
