- query =
    SUM(
      Q(electricity_stored_in_household_batteries),
      Q(electricity_stored_in_ev),
      Q(electricity_stored_in_pumped_storage),
      Q(electricity_converted_to_heat_industry),
      Q(electricity_converted_to_hydrogen),
      Q(electricity_exported),
      Q(electricity_curtailed),
      Q(losses_in_conversion_and_storage),
      Q(electricity_stored_in_mv_batteries),
      Q(electricity_stored_in_opac)
   )
- unit = PJ
