- query = 

    DIVIDE(
        Q(total_electricity_produced) + 
        V(energy_import_electricity, demand) + 
        V(energy_power_hv_network_shortage, demand), 
    BILLIONS) - Q(demand_in_source_of_electricity_production)
- unit = PJ
