- query = 
    SUM(
        Q(electricity_converted_to_gas),
        Q(electricity_converted_to_heat),
        Q(electricity_curtailed),
        Q(electricity_exported),
        Q(electricity_stored_in_batteries),
        Q(electricity_stored_in_EV),
        Q(losses_in_storage)
    )
- unit = PJ

