- query =
    SUM(
      Q(p2g_input_electricity_from_coal),
      Q(p2g_input_electricity_from_natural_gas),
      Q(p2g_input_electricity_from_fossil_oil),
      Q(p2g_input_electricity_from_uranium),
      Q(p2g_input_electricity_from_biomass),
      Q(p2g_input_electricity_from_wind),
      Q(p2g_input_electricity_from_hydro),
      Q(p2g_input_electricity_from_greengas),
      Q(p2g_input_electricity_from_geothermal),
      Q(p2g_input_electricity_from_waste),
      Q(p2g_input_electricity_from_solar),
      Q(p2g_input_electricity_from_import),
      Q(p2g_input_electricity_from_biogas),
      Q(p2g_input_electricity_from_hydrogen),
      Q(p2g_input_electricity_from_coal_gas)
    )
- unit = PJ
