# Direct conversion input of torrefied_biomass_pellets for central heat production

- query = 
    DIVIDE(
      SUM(
        V(
          G(ammonia_production),
          "ammonia_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_torrefied_biomass_pellets"
        )
      ), 
      BILLIONS
    )
- unit = PJ
