- query =
    SUM_CURVES(
      V(
        FILTER(
        ALL(),
        "merit_order && (merit_order.group == :agriculture_electricity)"
        ),
        "electricity_input_curve + hydrogen_input_curve + network_gas_input_curve + steam_hot_water_input_curve"
       )
     )

- unit = curve
