- query =
    SUM_CURVES(
      SUM_CURVES(
        V(
          FILTER(
          ALL(),
          "merit_order && (merit_order.group == :'weather/agriculture_heating')"
          ),
          "electricity_input_curve"
        )
      ),
      SUM_CURVES(
        V(
          FILTER(
          ALL(),
          "network_gas && (network_gas.profile == :'weather/agriculture_heating')"
          ),
          "network_gas_input_curve"
        )
      ),
      SUM_CURVES(
        V(
          FILTER(
          ALL(),
          "hydrogen && (hydrogen.profile == :'weather/agriculture_heating')"
          ),
          "hydrogen_input_curve"
        )
      ),
      SUM_CURVES(
        V(
          FILTER(
          ALL(),
          "heat_network && (heat_network.group == :'weather/agriculture_heating')"
          ),
          "steam_hot_water_input_curve"
        )
      )
    )
- unit = curve
