- query =
    SUM_CURVES(
      V(
        FILTER(
          ALL(),
          "merit_order && (merit_order.group == :bunkers_ships_electricity)"
        ),
        electricity_input_curve
       )
     )

- unit = curve
