- query = 
    SUM_CURVES(
      V(
        FILTER(
        ALL(),
        "merit_order && (merit_order.group == :bunkers_electric_aviation)"
        ), 
        electricity_input_curve
       )
     )
     
- unit = curve