- query = 
    SUM_CURVES(
      V(
        FILTER(
        ALL(),
        "hydrogen && (hydrogen.profile == :hydrogen_export)"
        ), 
        hydrogen_input_curve
       )
     )

- unit = curve