- query = 
    SUM_CURVES(
      V(
        FILTER(
        ALL(),
        "hydrogen && (hydrogen.profile == :hydrogen_import)"
        ), 
        hydrogen_output_curve
       )
     )

- unit = curve