- query = 
    SUM_CURVES(
        SUM_CURVES(
          V(
            FILTER(
            ALL(),
            "heat_network_lt && (heat_network_lt.group == :industry_refineries_heat)"
            ), 
            steam_hot_water_input_curve
           )
        ),
        SUM_CURVES(
          V(
            FILTER(
            ALL(),
            "heat_network_mt && (heat_network_mt.group == :industry_refineries_heat)"
            ), 
            steam_hot_water_input_curve
           )
        ),
        SUM_CURVES(
          V(
            FILTER(
            ALL(),
            "heat_network_ht && (heat_network_ht.group == :industry_refineries_heat)"
            ), 
            steam_hot_water_input_curve
           )
        ),
        SUM_CURVES(
          V(
            FILTER(
            ALL(),
            "merit_order && (merit_order.group == :industry_refineries_heat)"
            ), 
            electricity_input_curve
           )
        ),
        SUM_CURVES(
          V(
            FILTER(
            ALL(),
            "network_gas && (network_gas.profile == :industry_refineries_heat)"
            ), 
            network_gas_input_curve
           )
        ),
        SUM_CURVES(
          V(
            FILTER(
            ALL(),
            "hydrogen && (hydrogen.profile == :industry_refineries_heat)"
            ), 
            hydrogen_input_curve
           )
        )
    )

- unit = curve
