- query = 
    SUM_CURVES(
      V(
        FILTER(
        ALL(),
        "merit_order && (merit_order.group.to_s.gsub(/\s/, '') == 'dynamic:solar_pv')"
        ), 
        electricity_output_curve
       )
     )

- unit = curve