- query =
    SUM_CURVES(
      SUM_CURVES(
        V(
          FILTER(
          ALL(),
          "heat_network_lt && (heat_network_lt.group == :'weather/solar_thermal')"
          ), 
          steam_hot_water_output_curve
        )
      ),
      SUM_CURVES(
        V(
          FILTER(
          ALL(),
          "heat_network_mt && (heat_network_mt.group == :'weather/solar_thermal')"
          ), 
          steam_hot_water_output_curve
        )
      ),
      SUM_CURVES(
        V(
          FILTER(
          ALL(),
          "heat_network_ht && (heat_network_ht.group == :'weather/solar_thermal')"
          ), 
          steam_hot_water_output_curve
        )
      )
    )
- unit = curve
