- query =
    SUM_CURVES(
      V(
        FILTER(
        ALL(),
        "merit_order && (merit_order.group.to_s.gsub(/\s/, '') == 'dynamic:solar_pv_on_roof_households')"
        ),
        electricity_output_curve
       )
     )

- unit = curve
