- unit = PJ
- query = 
        present:
            SUM(
                Q(import_of_natural_gas),
                Q(import_of_propane),
                NEG(
                    Q(export_of_natural_gas)
                ),
                NEG(
                    Q(export_of_propane)
                )
            )