- query = 
    DIVIDE(
      V(households_new_houses_heating_savings_from_insulation,demand) + 
      V(households_new_houses_cooling_savings_from_insulation,demand),
      BILLIONS
    )
- unit = pj
