# Final demand of the 'geothermal' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(food_industry)
          ),
          geothermal?
        ),
        value
      )
    ) / BILLIONS
