# Non-energetic final demand of the 'oil_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(aggregated_other_industry_nl)
            ),
            "! energetic?"
          ),
          crude_oil?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(aggregated_other_industry_nl)
            ),
            "! energetic?"
          ),
          gasoline?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(aggregated_other_industry_nl)
            ),
            "! energetic?"
          ),
          diesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(aggregated_other_industry_nl)
            ),
            "! energetic?"
          ),
          lpg?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(aggregated_other_industry_nl)
            ),
            "! energetic?"
          ),
          kerosene?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(aggregated_other_industry_nl)
            ),
            "! energetic?"
          ),
          heavy_fuel_oil?
        ),
        value
      )
    ) / BILLIONS
