# Final demand of the 'solar' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(aggregated_other_industry_nl)
          ),
          solar_radiation?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(aggregated_other_industry_nl)
          ),
          solar_thermal?
        ),
        value
      )
    ) / BILLIONS
