# Final demand of the 'ambient' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(aggregated_other_industry_nl)
          ),
          ambient_heat?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(aggregated_other_industry_nl)
          ),
          ambient_cold?
        ),
        value
      )
    ) / BILLIONS
