# Use of carrier group 'waste' in residential district heat

- unit = pj
- query =
    SUM(
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_waste_mix),
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_non_biogenic_waste),
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_biogenic_waste)      
    ) / BILLIONS
