- query =
  SUM(
      Q(emissions_non_energetic_industry_chemical_co2),
      Q(emissions_non_energetic_industry_waste_management_co2),
      Q(emissions_non_energetic_agriculture_manure_co2),
      Q(emissions_non_energetic_other_industry_co2),
      Q(emissions_non_energetic_agriculture_soil_cultivation_co2),
      Q(industry_chemical_non_energetic_co2_emissions)
  )

- unit = T
