- query =
  SUM(
      Q(co2_sheet_agriculture_total_co2_emissions_only_energetic),
      Q(co2_sheet_buildings_households_total_co2_emissions_only_energetic),
      Q(co2_sheet_industry_energy_total_co2_emissions_only_energetic),
      Q(co2_sheet_transport_total_co2_emissions_only_energetic)
  )

- unit = T