- query =
  SUM(
      Q(emissions_energetic_agriculture_other_ghg),
      Q(emissions_energetic_buildings_other_ghg),
      Q(emissions_energetic_households_other_ghg),
      Q(emissions_energetic_industry_energy_other_ghg),
      Q(emissions_energetic_other_industry_other_ghg)
  )

- unit = T