- query =
  SUM(
      Q(emissions_non_energetic_industry_chemical_co2),
      Q(emissions_non_energetic_industry_waste_management_co2),
      Q(emissions_non_energetic_manure_co2),
      Q(emissions_non_energetic_other_industry_co2),
      Q(emissions_non_energetic_soil_cultivation_co2)
  )

- unit = T