- query =
  SUM(
      Q(emissions_non_energetic_industry_chemical_other_ghg),
      Q(emissions_non_energetic_industry_waste_management_other_ghg),
      Q(emissions_non_energetic_manure_other_ghg),
      Q(emissions_non_energetic_other_industry_other_ghg),
      Q(emissions_non_energetic_soil_cultivation_other_ghg)
  )

- unit = T