- query =
    SUM(
        Q(emissions_energetic_all_co2),
        Q(emissions_energetic_all_ghg),
        Q(emissions_non_energetic_all_co2),
        Q(emissions_non_energetic_all_ghg)
    )

- unit = T