# Final demand of biodiesel in trains, based on final demand for rail and share of diesel mix
# to trains

- query =
    PRODUCT(
      V(transport_final_demand_for_rail_biodiesel, demand),
      V(EDGE(transport_rail_mixer_diesel, transport_passenger_train_using_diesel_mix), parent_share)
    )
- unit = MJ
