IF(INPUT_VALUE(households_lighting_incandescent_share) > 45,
  "incandescent_lighting",
  IF(INPUT_VALUE(households_lighting_low_energy_light_bulb_share) > 45,
    "fluorescent_lighting",
    IF(INPUT_VALUE(households_lighting_light_emitting_diode_share) > 45,
      "led_lighting",
      "error"
    )
  )
)
