# Percentage of renewable energy used in a household

- query =
    Q(etflex_households_renewability_percentage_electricity_per_household) * Q(etflex_households_electricity_fraction) + 
    Q(etflex_households_renewability_percentage_heat_per_household) * Q(etflex_households_heat_fraction)
- unit = %
