# Fraction of final demand of electricity EXCLUDING use for heating

- query =
    DIVIDE(
      V(households_final_demand_electricity, demand) -
      V(households_final_demand_for_space_heating_electricity, demand) -
      V(households_final_demand_for_hot_water_electricity, demand),
      V(households_final_demand_electricity, demand) + 
      V(households_final_demand_for_space_heating_network_gas, demand) +
      V(households_final_demand_for_hot_water_network_gas, demand) 
    )
- unit = mj
