# calculates the final demand of gas in an average household by dividing the average
# kWh's of a household by 10 (which is about the amount of kWh's in 1 m3 gas )'

- query = V(households_final_demand_network_gas, demand) / AREA(number_households) / MJ_PER_KWH / 10
- unit = m3
