# Monthly energy bill

- unit = euro

SUM (
  V(households_final_demand_network_gas, "demand * weighted_carrier_cost_per_mj"),
  (V(households_final_demand_electricity, demand) - V(households_solar_pv_solar_radiation, output_of_electricity)) * Q(average_costs_of_produced_electricity)
) / AREA(number_households) / MONTHS_PER_YEAR

