
# Returns the capacity supercritical chp waste power plants with ccs.
- query = 
        PRODUCT(
  		V(energy_chp_supercritical_ccs_waste_mix,number_of_units),
  		V(energy_chp_supercritical_ccs_waste_mix,electricity_output_capacity)	
  		)
- unit = MW

