
# Returns the capacity supercritical chp mt waste power plants.
- query = 
        PRODUCT(
  		V(energy_chp_supercritical_mt_waste_mix,number_of_units),
  		V(energy_chp_supercritical_mt_waste_mix,electricity_output_capacity)	
  		)
- unit = MW

