# Use of carrier group 'electricity' in chemical industry heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(industry_useful_demand_for_chemical_other_useable_heat)),input_of_electricity)
    ) / BILLIONS
