# Use of carrier group 'heat' in chemical industry heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(industry_useful_demand_for_chemical_other_useable_heat_after_p2h)),input_of_steam_hot_water),
      V(CHILDREN(V(industry_useful_demand_for_chemical_other_useable_heat_after_p2h)),input_of_useable_heat)
    ) / BILLIONS
