# Use of carrier group 'natural_gas_and_derivatives' in chemical industry heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(industry_useful_demand_for_chemical_other_useable_heat_after_p2h)),input_of_network_gas),
      V(CHILDREN(V(industry_useful_demand_for_chemical_other_useable_heat_after_p2h)),input_of_lng)
    ) / BILLIONS
