# Output of steam_hot_water from sum of energy_chp_local_ht_wood_pellets_ccs_dispatchable_output_of_steam_hot_water and energy_chp_local_ht_wood_pellets_ccs_must_run_output_of_steam_hot_water

- query =
    SUM(
      Q(energy_chp_local_ht_wood_pellets_ccs_dispatchable_output_of_steam_hot_water),
      Q(energy_chp_local_ht_wood_pellets_ccs_must_run_output_of_steam_hot_water)
    )
- unit = PJ