# Final consumption from international transport - international navigation, all carriers (energetic and non-energetic use combined).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     All carriers
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_from_bunkers_international_navigation_total)
