# Returns the capacity of ultra supercritical cofiring oxyfuel ccs lignite power plants.
- query = 
        PRODUCT(
  		V(energy_chp_ultra_supercritical_cofiring_oxyfuel_ccs_lignite,number_of_units),
  		V(energy_chp_ultra_supercritical_cofiring_oxyfuel_ccs_lignite,electricity_output_capacity)	
  		)
- unit = MW
