# Returns the capacity of ultra supercritical cofiring lignite power plants.
- query = 
        PRODUCT(
  		V(energy_chp_ultra_supercritical_cofiring_lignite,number_of_units),
  		V(energy_chp_ultra_supercritical_cofiring_lignite,electricity_output_capacity)	
  		)
- unit = MW
