# Max emissions value of dataset-derived emissions

- unit = T
- query =
    MAX(
      Q(direct_emissions_static_emissions_molecule_nodes_max_value),
      Q(direct_emissions_static_emissions_bunkers)
    )
