# Max emissions value of dataset-derived emissions

- unit = T
- query =
    DIVIDE(
      MAX(
        MV(
          EXCLUDE(
            MG(direct_emissions),
            MV(MG(ccus_captured), molecules_other_utilisation_delayed_emitted_co2)
          ),
          lulucf_removals_non_energetic_co2,
          demand
        )
      ),
      THOUSANDS
    )
