# Max emissions value of international transport dataset-derived emissions
# Bunkers derived directly from emissions.csv since start year default is zero

- unit = T
- query =
    PRODUCT(
      EMISSIONS(emissions_sector, "International transport", other_ghg),
      THOUSANDS
    )
