
- unit = MT
- query =
    DIVIDE(
      SUM(
        MV(
          MSECTOR(emissions_subsector, "Indirect emissions"),
          direct_reporting_emissions_co2_production
        )
      ),
      BILLIONS
    )
