# Cost of bio kerosene in international transport

- unit = bln_euro
- query = DIVIDE(V(energy_distribution_bio_kerosene, weighted_carrier_cost_per_mj)*V(bunkers_final_demand_bio_kerosene,demand), BILLIONS)
