# Cost of coal in transport

- unit = bln_euro
- query =
    DIVIDE(
      V(energy_distribution_coal, weighted_carrier_cost_per_mj)*
      V(transport_final_demand_coal,demand),
      BILLIONS
    )
