# Cost of diesel in transport

- unit = bln_euro
- query =
    DIVIDE(
      V(energy_distribution_diesel, weighted_carrier_cost_per_mj)*
      V(transport_final_demand_diesel,demand),
      BILLIONS
    )
