# Cost of electricity in transport

- unit = bln_euro
- query =
    DIVIDE(
        Q(average_costs_of_produced_electricity)*
        V(transport_final_demand_electricity,demand),
        BILLIONS
      )
