# Cost of heavy fuel oil in international transport

- unit = bln_euro
- query =
    DIVIDE(
      V(energy_distribution_heavy_fuel_oil, weighted_carrier_cost_per_mj)*
      V(bunkers_final_demand_heavy_fuel_oil,demand),
      BILLIONS
    )
