# Cost of heavy fuel oil in domestic transport

- unit = bln_euro
- query =
    DIVIDE(
        V(transport_final_demand_heavy_fuel_oil,"demand * weighted_carrier_cost_per_mj"), 
        BILLIONS
    )
