# Cost of hydrogen in transport

- unit = bln_euro
- query =
    DIVIDE(
      V(energy_distribution_hydrogen, weighted_carrier_cost_per_mj)*
      V(transport_final_demand_hydrogen,demand),
      BILLIONS
    )
