# Cost of kerosene in domestic transport

- unit = bln_euro
- query =
    DIVIDE(
      V(energy_distribution_kerosene, weighted_carrier_cost_per_mj)*
      V(transport_final_demand_kerosene,demand),
      BILLIONS
    )
