# Cost of lng in international transport

- unit = bln_euro
- query =
    DIVIDE(
      V(energy_distribution_lng, weighted_carrier_cost_per_mj)*
      V(bunkers_final_demand_lng,demand),
      BILLIONS
    )
