# Cost of natural gas in transport

- unit = bln_euro
- query =
    DIVIDE(
      PRODUCT(
        V(transport_final_demand_for_road_compressed_network_gas,input_of_compressed_network_gas),
        Q(share_of_natural_gas_in_gas_network),
        V(energy_national_gas_network_natural_gas, weighted_carrier_cost_per_mj),
        ),
        BILLIONS
    )
