# Returns the capacity of ultra supercritical cofiring coal plants with ccsfor the sector energy.
- query = 
        PRODUCT(
  		V(energy_chp_ultra_supercritical_cofiring_coal,number_of_units),
  		V(energy_chp_ultra_supercritical_cofiring_coal,electricity_output_capacity)	
  		)
- unit = MW

