# Primary distribution pipeline costs are only taken into account for sources in the primary_heat_infrastructure group
# This group includes residual heat from industry and large-scale CHPs
# We only take into account infrastructure costs for households and buildings, so we multiply by their share in total peak demand

- query =
    households_buildings_peak_demand_in_kw = Q(households_buildings_district_heating_mt_demand_peak) * 1000.0;
    total_peak_demand_in_kw = Q(total_district_heating_mt_demand_peak) * 1000.0;
    households_buildings_share_in_total_peak = DIVIDE((households_buildings_peak_demand_in_kw), total_peak_demand_in_kw);
    peak_supply_on_primary_net_in_kw = Q(total_district_heating_mt_primary_net_supply_peak) * 1000.0;

    peak_supply_on_primary_net_in_kw * households_buildings_share_in_total_peak * AREA(heat_mt_primary_pipelines_investment_costs_per_kw)
- unit = euro