# Final consumption of geothermal in international transport (energetic use only).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     Geothermal -- geothermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_geothermal_in_international_transport_energetic)
