# Final consumption of electricity in international transport (energetic use only).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     Electricity -- electricity?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_electricity_in_international_transport_energetic)
