# Final consumption of heat in international transport (energetic use only).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_heat_in_international_transport_energetic)
