- query =
    MERIT_LOAD_CURVES(
      bunkers_flexibility_p2g_electricity,
      energy_hydrogen_flexibility_p2g_electricity,
      industry_chemicals_other_flexibility_p2h_electricity,
      industry_chemicals_refineries_flexibility_p2h_electricity,
      industry_other_paper_flexibility_p2h_electricity
    )
