- query =
    SUM_CURVES(V(
      industry_final_demand_for_other_non_specified_electricity,
      industry_useful_demand_for_other_paper_electricity,
      industry_other_paper_captured_co2_electricity,
      industry_other_paper_heater_electricity,
      industry_useful_demand_for_other_food_electricity,
      industry_other_food_captured_co2_electricity,
      industry_other_food_heater_electricity,
      industry_final_demand_for_other_ict_electricity,
      electricity_input_curve
    ))
- unit = curve
