- query =
    SUM_CURVES(V(
      energy_cokesoven_consumption_coal_gas,
      industry_final_demand_for_other_electricity,
      industry_final_demand_for_other_ict_electricity,
      electricity_input_curve
    ))
- unit = curve
