- query =
    SUM_CURVES(V(
      industry_final_demand_for_chemical_refineries_electricity,
      industry_useful_demand_for_chemical_fertilizers_electricity,
      industry_chemicals_fertilizers_captured_processes_co2_electricity,
      industry_chemicals_fertilizers_captured_combustion_co2_electricity,
      industry_final_demand_for_chemical_other_electricity,
      electricity_input_curve
    ))
- unit = curve
