- query =
    INVERT_CURVE(
      SUM_CURVES(
        V(
          industry_final_demand_for_other_dsr_load_shifting_electricity,
          electricity_output_curve
        )
      )
    )
- unit = curve
