- query =
    SUM_CURVES(V(
      bunkers_final_demand_electricity,
      energy_power_sector_own_use_electricity,
      other_final_demand_electricity,
      electricity_input_curve
    ))
- unit = curve
