# Direct conversion input of biomass products for biomass gasification with CCS


- query =
    DIVIDE(
      V(
        energy_hydrogen_biomass_gasification_ccs,
        input_of_torrefied_biomass_pellets
      ),
      BILLIONS
    ) + Q(greengas_for_biomass_gasification_ccs_conversion)
- unit = PJ
