# Direct conversion input of greengas for biomass gasification without CCS


- query =
    DIVIDE(
      V(
        energy_hydrogen_biomass_gasification,
        input_of_network_gas
      ),
      BILLIONS
    ) * Q(share_of_sustainable_gas_in_gas_network)
- unit = PJ
