# Query for scenario tools regional overview: direct conversion demand of hydrogen for synthetic kerosene production

- query =
    DIVIDE(
      SUM(
        V(Q(synthetic_fuels_kerosene_converters),
        input_of_hydrogen
        )
      ),
      BILLIONS
    )
- unit = PJ
