# Query for scenario tools regional overview: direct conversion demand of hydrogen for synthetic methanol production

- query =
    DIVIDE(
      V(energy_production_synthetic_methanol, input_of_hydrogen),
      BILLIONS
    )
- unit = PJ
