# Query for scenario tools regional overview: direct conversion demand of hydrogen for synthetic kerosene production

- query =
    DIVIDE(
      SUM(
        V(energy_production_synthetic_kerosene_dispatchable, input_of_hydrogen),
        V(energy_production_synthetic_kerosene_must_run, input_of_hydrogen)
      ),
      BILLIONS
    )
- unit = PJ
