# Direct conversion output of hydrogen from hydrogen production through ammonia reforming

- query =
    DIVIDE(
      V(
        energy_hydrogen_lohc_reformer,
        output_of_hydrogen
      ),
      BILLIONS
    )
- unit = PJ
