# Direct conversion input of natural gas for biomass gasification with CCS


- query =
    DIVIDE(
      V(
        energy_hydrogen_biomass_gasification_ccs,
        input_of_network_gas
      ),
      BILLIONS
    ) * Q(share_of_fossil_gas_in_gas_network)
- unit = PJ
