# Direct conversion input of natural gas for steam methane reforming with CCS


- query =
    DIVIDE(
      V(
        energy_hydrogen_steam_methane_reformer_ccs,
        input_of_natural_gas
      ),
      BILLIONS
    )
- unit = PJ
