# Direct conversion input of natural gas for biomass gasification with CCS


- query =
    DIVIDE(
      SUM(
        V(
          energy_hydrogen_biomass_gasification_ccs,
          input_of_network_gas
        ),
        PRODUCT(
          DIVIDE(
            V(energy_hydrogen_biomass_gasification_ccs, input_of_torrefied_biomass_pellets),
            1 - V(energy_torrefaction_wood, loss_output_conversion)
          ),
        V(energy_torrefaction_wood, network_gas_input_conversion)
        )
      ),
      BILLIONS
    ) * Q(share_of_fossil_gas_in_gas_network)
- unit = PJ
