- query =
    SUM(
    DIVIDE(
      SUM(
        V(
          G(hydrogen_production),
          input_of(
            crude_oil,
            diesel
          )
        )
      ),
      BILLIONS
    ),
    Q(gas_power_fuelmix_for_hydrogen_conversion) * V(energy_mixer_for_gas_power_fuel, crude_oil_input_conversion)
    )
- unit = PJ
