# Direct conversion output of hydrogen from hydrogen production through SMR with CCS

- query =
    DIVIDE(
      SUM(
        V(
          energy_hydrogen_steam_methane_reformer_ccs_must_run,
          output_of_hydrogen
        )
      ),
      BILLIONS
    )
- unit = PJ

