- query = 
		SUM(
			Q(chps_to_local_steam_hot_water_in_sankey_agriculture_chps),
			Q(chps_to_unused_steam_hot_water_in_sankey_agriculture_chps),
			Q(chps_to_local_electricity_in_sankey_agriculture),
			Q(chps_to_mv_grid_in_sankey_agriculture),
			Q(chps_to_conversion_losses_in_sankey_agriculture)
		)