# Total cost of greengas production by wet biomass gasification per MWh produced greengas

- unit = euro
- query =
    PRODUCT(
      DIVIDE(
        V(energy_greengas_gasification_wet_biomass, total_costs_per(:node)),
        DIVIDE(
          V(energy_greengas_gasification_wet_biomass, output_of_greengas),
          MJ_PER_MWH
        )
      ),
      Q(share_of_greengas_production_by_wet_biomass_gasification)
    )
