# Total cost of greengas production by biogas fermentation (including the upgrade) per MWh produced greengas

- unit = euro
- query =
    PRODUCT(
      DIVIDE(
        SUM(
          V(energy_biogas_fermentation_wet_biomass, total_costs_per(:node)) * V(LINK(energy_greengas_upgrade_biogas, energy_distribution_biogas), parent_share),
          V(energy_greengas_upgrade_biogas, fixed_costs_per(:node))
        ),
        DIVIDE(
          V(energy_greengas_upgrade_biogas, output_of_greengas),
          MJ_PER_MWH
        )
      ),
      Q(share_of_greengas_production_by_biogas_fermentation)
    )
