# Use of carrier group 'coal_and_derivatives' in residential district heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_coal),
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_lignite),
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_coal_gas),
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_cokes)      
    ) / BILLIONS
