# Use of carrier group 'natural_gas_and_derivatives' in residential district heat

- unit = pj
- query =
    SUM(
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_natural_gas),
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_lng),
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_network_gas),
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_gas_power_fuelmix),
      V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_compressed_network_gas)      
    ) / BILLIONS
