# Use of carrier group 'ambient' in buildings heating

- unit = PJ
- query =
    SUM(
      V(Q(individual_heating_converters_in_buildings),input_of_ambient_heat),
      V(Q(individual_heating_converters_in_buildings),input_of_ambient_cold)
    ) / BILLIONS
