# Use of carrier group 'coal_and_derivatives' in buildings heating

- unit = PJ
- query =
    SUM(
      V(Q(individual_heating_converters_in_buildings),input_of_coal),
      V(Q(individual_heating_converters_in_buildings),input_of_coal_gas)
    ) / BILLIONS
