# Use of carrier group 'geothermal' in buildings heating

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(buildings_useful_demand_for_space_heating_after_insulation)),input_of_geothermal)      
    ) / BILLIONS
