# Use of carrier group 'heat' in buildings heating

- unit = PJ
- query =
    SUM(
      V(Q(individual_heating_converters_in_buildings),input_of_steam_hot_water),
      V(Q(individual_heating_converters_in_buildings),input_of_useable_heat)
    ) / BILLIONS
