- query =
    DIVIDE(
      PRODUCT(
        Q(share_of_renewables_in_heat_produced_in_buildings),
        V(buildings_useful_demand_for_space_heating_after_insulation,demand)),
      BILLIONS
    )
- unit = pj
