# Use of carrier group 'natural_gas_and_derivatives' in buildings heating

- unit = PJ
- query =
    SUM(
      V(Q(individual_heating_converters_in_buildings),input_of_network_gas),
      V(Q(individual_heating_converters_in_buildings),input_of_lng)
    ) / BILLIONS
