# Use of carrier group 'oil_and_derivatives' in buildings heating

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(buildings_useful_demand_for_space_heating_after_insulation)),input_of_crude_oil),
      V(CHILDREN(V(buildings_useful_demand_for_space_heating_after_insulation)),input_of_gasoline),
      V(CHILDREN(V(buildings_useful_demand_for_space_heating_after_insulation)),input_of_diesel),
      V(CHILDREN(V(buildings_useful_demand_for_space_heating_after_insulation)),input_of_lpg),
      V(CHILDREN(V(buildings_useful_demand_for_space_heating_after_insulation)),input_of_kerosene),
      V(CHILDREN(V(buildings_useful_demand_for_space_heating_after_insulation)),input_of_heavy_fuel_oil)      
    ) / BILLIONS
