# Use of carrier group 'solar' in buildings heating

- unit = PJ
- query =
    SUM(
      V(Q(individual_heating_converters_in_buildings),input_of_solar_radiation),
      V(Q(individual_heating_converters_in_buildings),input_of_solar_thermal)
    ) / BILLIONS
