# Energetic final demand of the 'heat' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(refineries_industry)
            ),
            energetic?
          ),
          steam_hot_water?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(refineries_industry)
            ),
            energetic?
          ),
          useable_heat?
        ),
        value
      )
    ) / BILLIONS
