# Non-energetic final demand of the 'hydrogen' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(aggregated_chemical_industry)
            ),
            "! energetic?"
          ),
          hydrogen?
        ),
        value
      )
    ) / BILLIONS
