- query = 
    PRODUCT(
        DIVIDE(
            Q(land_use_solar_wind_solar_thermal_buildings_land_use_per_unit),
            MILLIONS
        ),
        Q(land_use_solar_wind_solar_thermal_buildings_number_of_units)
    )
- unit = km2