# Final consumption of ammonia in international transport - international aviation (energetic and non-energetic use combined).
#
# Sector:      International transport - International aviation -- EG(bunkers_international_aviation)
# Carrier:     Ammonia -- ammonia?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_bunkers_international_aviation_total)
