# The final demand in the industry sector.

- unit = MJ
- query =
    SUM(
      V(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :industry"
            ),
            energetic?
          ),
        value
      )      
    )