# Query for Sankey diagram: connection between biomass_products and industry

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),input_of(Q(carrier_group_biomass_products)))),BILLIONS)
			