# Query for Sankey diagram: connection between geo_solar_wind_water_ambient and other

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(other),G(final_demand_cbs)),input_of(Q(carrier_group_geo_solar_wind_water_ambient)))),BILLIONS)
			