# Query for Sankey diagram: connection between mixed_flows and industry

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),primary_demand_of(Q(carrier_group_mixed_flows)))),BILLIONS)
			