# Query for Sankey diagram: connection between non_renewable_waste and buildings

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(buildings),G(final_demand_cbs)),input_of(Q(carrier_group_non_renewable_waste)))),BILLIONS)
			