# Query for Sankey diagram: connection between non_renewable_waste and transport

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(transport),G(final_demand_cbs)),primary_demand_of(Q(carrier_group_non_renewable_waste)))),BILLIONS)
			