# Query for Sankey diagram: connection between nuclear and buildings

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(buildings),G(final_demand_cbs)),input_of(Q(carrier_group_nuclear)))),BILLIONS)
			