# Query for Sankey diagram: connection between oil_and_derivatives and households

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(final_demand_cbs)),input_of(Q(carrier_group_oil_and_derivatives)))),BILLIONS)
			