# Final demand of LPG in cars, based on final demand for road and share to cars

- query =
    PRODUCT(
      V(transport_final_demand_for_road_lpg, demand),
      V(EDGE(transport_final_demand_for_road_lpg, transport_car_using_lpg), parent_share)
    )
- unit = MJ
