# Final demand of hydrogen in cars, based on final demand for road and share to cars

- query =
    PRODUCT(
      V(transport_final_demand_for_road_hydrogen, demand),
      V(EDGE(transport_final_demand_for_road_hydrogen, transport_car_using_hydrogen), parent_share)
    )
- unit = MJ
