# Final demand of bio_ethanol in cars, based on final demand for road and share of gasoline mix
# to cars

- query =
    PRODUCT(
      V(transport_final_demand_for_road_bio_ethanol, demand),
      V(EDGE(transport_road_mixer_gasoline, transport_car_using_gasoline_mix), parent_share)
    )
- unit = MJ
