- query =
    SUM_CURVES(
      Q(electricity_production_inflexible_curve),
      Q(network_gas_production_inflexible_curve),
      Q(heat_network_production_inflexible_curve),
      Q(hydrogen_production_inflexible_curve)
    )
- unit = MJ