- query =
    SUM_CURVES(
      Q(electricity_demand_inflexible_curve),
      Q(network_gas_demand_inflexible_curve),
      Q(heat_network_demand_inflexible_curve),
      Q(hydrogen_demand_inflexible_curve)
    )
- unit = MJ