- query =
    yearly_diff = Q(all_time_resolved_carriers_diff_demand_production_inflexible_yearly_total);
    hourly_diff = yearly_diff / 8760.0;

    MAP(Q(all_time_resolved_carriers_demand_inflexible_curve), ->(value) { value + hourly_diff })
- unit = curve