- query =
    minimum_value = MIN(Q(all_time_resolved_carriers_cumulative_incl_correction_curve));

    MAP(Q(all_time_resolved_carriers_cumulative_incl_correction_curve), ->(value) { value - minimum_value })
- unit = curve