# Final demand of steam hot water and useable heat of LT temperature

- unit = PJ
- query =
    DIVIDE(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(lt_heat)),"sector == :energy"
          ),
          "steam_hot_water? || useable_heat?"
        ),
        value
      ),
      BILLIONS
    )
