# Energetic final demand of electricity in agriculture excluding heating

- unit = PJ
- query =
    SUM(
      DIVIDE(
        V(
          agriculture_final_demand_electricity,
          input_of_electricity),
        BILLIONS
      ),
      NEG(
        Q(agriculture_final_demand_for_electricity_in_space_heating)
        )
    )
