# Energetic final demand of electricity in agriculture heating

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          INTERSECTION(
            G(heat_production),
            SECTOR(agriculture)
          ),
          input_of_electricity
        )
      ),
      BILLIONS
    )
