# Final consumption of solar thermal in buildings (energetic use only).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     Solar thermal -- solar_thermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_solar_thermal_in_buildings_energetic)
