# Final consumption of methanol in buildings (energetic use only).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_methanol_in_buildings_energetic)
