- query =
    SUM_CURVES(
      V(bunkers_flexibility_p2g_electricity, electricity_output_curve),
      INVERT_CURVE(
        V(bunkers_flexibility_p2g_electricity, electricity_input_curve)
      )
    )

- unit = curve
