- query =
    SUM_CURVES(
      V(energy_heat_flexibility_p2h_boiler_electricity, electricity_output_curve),
      INVERT_CURVE(
        V(energy_heat_flexibility_p2h_boiler_electricity, electricity_input_curve)
      )
    )

- unit = curve
