- query =
    SUM_CURVES(
      V(energy_flexibility_hv_opac_electricity, electricity_output_curve),
      INVERT_CURVE(
        V(energy_flexibility_hv_opac_electricity, electricity_input_curve)
      )
    )
- unit = curve
