# This query consists of losses allocated from biomass to biomass product
# This query is explicitly used for the Sankey download
# Losses related to green gas share in network gas are added here, since the Sankey download
# doesn't contain the network gas carrier (only natural gas and green gas), in contrast
# with the Sankey chart.

- query =
    SUM(
      PRODUCT(
        Q(conversion_loss_network_gas_to_biomass_products),
        Q(share_of_sustainable_gas_in_gas_network)
      ),
      PRODUCT(
        Q(conversion_loss_greengas_to_network_gas),
        Q(share_of_sustainable_gas_in_gas_network)
      ),
      Q(conversion_loss_biomass_products_to_biomass_products_excl_network_gas)
    )
- unit = PJ
