# All electricity made by wind turbines and solar panels.
#
# the used queries are NOT dynamic!

- query =
    SUM
    (
    Q(electricity_produced_from_wind),
    Q(electricity_produced_from_solar)
    )
- unit = mj
- deprecated_key = electricity_from_wind_and_solar
