# primary_electricity_from_solar

- unit = MJ
- query =
    PRODUCT(
       SUM(
        V(G(final_demand_group), primary_demand_of_electricity)
         )
    ,
       DIVIDE
        (
        Q(electricity_produced_from_solar),
        Q(electricity_produced_from_wind_and_solar)
        )
    )
- deprecated_key = primary_electricity_from_solar
