# The share of coal_industry in the primary demand (excluding imported_electricity)

- query =
    DIVIDE(
    SUM(
      V(INTERSECTION(V(SECTOR(industry)),G(final_demand_cbs)), primary_demand_of_coal),
      V(INTERSECTION(V(SECTOR(industry)),G(final_demand_cbs)), primary_demand_of_lignite),
      V(INTERSECTION(V(SECTOR(industry)),G(final_demand_cbs)), primary_demand_of_coal_gas)
       )
    ,
    SUM(
      V(G(final_demand_cbs), primary_demand),
      NEG(SUM(
          V(G(final_demand_cbs), primary_demand_of_imported_electricity)
          ))
       )
    )
- unit = factor
