# The share of oil in the primary demand (excluding imported_electricity)

- query =
    DIVIDE(
      SUM(
        V(
          G(final_demand_cbs),
          primary_demand_of_carriers(crude_oil, gasoline, diesel, lpg, kerosene)
        ),
      ),
      SUM(
        V(G(final_demand_cbs), primary_demand),
        NEG(SUM(
          V(G(final_demand_cbs), primary_demand_of_imported_electricity)
        ))
      )
    )

- unit = factor
