# The share of sustainable_solar in the primary demand (excluding imported_electricity)

- query =
    DIVIDE(
    Q(primary_demand_of_electricity_assigned_to_solar)
    ,
    SUM(
      V(G(final_demand_group), primary_demand),
      NEG(SUM(
          V(G(final_demand_group), primary_demand_of_imported_electricity)
          ))
       )
    )
- unit = factor
