# The share of sustainable_biomass in the primary demand (excluding imported_electricity)
# Either primary_demand_of_waste can be removed, or the new carrier group can be queried instead.

- query =
    DIVIDE(
      SUM(V(
        G(final_demand_cbs),
        primary_demand_of_carriers(
          waste_mix,
          biogenic_waste,
          non_biogenic_waste,
          ambient_heat,
          ambient_cold,
          wood_pellets,
          greengas,
          biodiesel,
          bio_ethanol,
          bio_oil,
          biogas,
          electricity
        )
      )),
      SUM(
        V(G(final_demand_cbs), primary_demand),
        NEG(SUM(
          V(G(final_demand_cbs), primary_demand_of_imported_electricity)
        ))
      )
    )
- unit = factor
