# The share of gas in the primary demand (excluding imported_electricity)

- query =
    DIVIDE(
      SUM(
        V(G(final_demand_cbs), primary_demand_of_carriers(natural_gas, lng, network_gas))
      ),
      SUM(
        V(G(final_demand_cbs), primary_demand),
        NEG(SUM(
          V(G(final_demand_cbs), primary_demand_of_imported_electricity)
        ))
      )
    )

- unit = factor
