# The share of uranium_buildings in the primary demand (excluding imported_electricity)

- query =
    DIVIDE(
    SUM(
      V(INTERSECTION(V(SECTOR(households),SECTOR(buildings)),G(final_demand_group)), primary_demand_of_uranium_oxide)
       )
    ,
    SUM(
      V(G(final_demand_group), primary_demand),
      NEG(SUM(
          V(G(final_demand_group), primary_demand_of_imported_electricity)
          ))
       )
    )
- unit = factor
