# The actual co2 emitted in the area. This therefore includes emission because of export, but excludes CO2 for imported electricity.
# 
# TAKE NOTE: The "co2_emission_electricity_ex_import" only works correctly because imported electricity is not assigned CO2. When this changes, this query may have to be updated.

- unit = kg

SUM(
 Q(co2_emission_excl_electricity_import),
 Q(co2_emission_electricity_export)
)