# According to John Zwaal local solar PV should not be added to decentral capacity. The impact of it on the HS net is minimal, even when introduced on a very large scale.

- unit = mw

SUM(
 V(Q(plants_connected_to_mv_hv_transformer);delta_in_capacity_in_mw),
 V(chp_agri_agriculture_energetic;delta_in_capacity_in_mw)
)