# 

- unit = euro

SUM(
 DIVIDE(
  Q(pl_mv_t_net_investment_costs_total),V(mv_transport_network_energy;technical_lifetime)
 ),
 PRODUCT(
  DIVIDE(
   Q(pl_mv_t_net_investment_costs_total),2
  ),
  V(mv_transport_network_energy;wacc)
 ),
 Q(pl_mv_t_net_operational_costs_total)
 )

