- query = 
    PRODUCT(
        V(energy_hydrogen_electrolysis_solar_electricity, "input_capacity * number_of_units * hydrogen_output_conversion"),
        AREA(hydrogen_electrolysis_solar_pv_capacity_ratio)
    )
- unit = MW
