# Annual opex of outdoor heat infrastructure per household, 
# comprised of 
# 1) the maintenance costs of primary pipelines and distribution stations by share of household heat demand in the total district heating network;
# 2) the maintenance costs for distribution pipelines (used only by households and buildings) by share of household heat demand in the distribution network, and
# 3) the maintenance costs for connection pipelines (which are used only by households)

- unit = euro
- query = 
    DIVIDE(
      SUM(
        Q(households_mt_primary_pipelines_fixed_operation_and_maintenance_costs),
        Q(households_mt_distribution_stations_fixed_operation_and_maintenance_costs),
        Q(households_mt_distribution_pipelines_fixed_operation_and_maintenance_costs)
      ),
      V(households_space_heater_district_heating_mt_steam_hot_water, number_of_units)
    )
