# Final consumption of gaseous biofuels, all sectors (energetic use only).
#
# Sector:      All sectors
# Carrier:     Gaseous biofuels
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of gaseous biofuels in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_gaseous_biofuels_energetic)
