- unit = MJ
- query =
    PRODUCT(
     DIVIDE(
        V(Q(cooling_converters_in_buildings),input_of_ambient_cold).sum,
        V(Q(cooling_converters_in_buildings),demand).sum
     ),
     V(buildings_useful_demand_after_insulation_cooling,input_of_cooling)
    )
- deprecated_key = buildings_cooling_ambient
