- deprecated_key = buildings_cooling_ambient
# 

- unit = mj

PRODUCT(
 DIVIDE(
  SUM(
   V(Q(cooling_converters_in_buildings),input_of_ambient_cold)
  ),
  SUM(
   V(Q(cooling_converters_in_buildings),demand)
  )
 ),
V(cooling_buildings_energetic,input_of_cooling)
)