- query =
    SUM(
      V(Q(heating_converters_in_households),input_of_wood_pellets),
      V(Q(heating_converters_in_households),input_of_greengas),
      V(Q(heating_converters_in_households),input_of_biodiesel),
      V(Q(heating_converters_in_households),input_of_bio_ethanol),
      V(Q(heating_converters_in_households),input_of_biogas),
      V(households_collective_chp_wood_pellets,"steam_hot_water_output_conversion * input_of_wood_pellets"),
      V(households_collective_chp_biogas,"steam_hot_water_output_conversion * input_of_biogas")
    )
- unit = mj
