# the green gas share in the natual gas is added.

- unit = pj

DIVIDE(PRODUCT(DIVIDE(SUM(V(G(heat_production);input_of_wood_pellets + input_of_greengas),

PRODUCT(SUM(V(G(heat_production);input_of_network_gas)),Q(share_of_greengas_in_gas_network))

),SUM(V(G(heat_production);output_of_heat_and_cooling_carriers))),SUM(V(G(heat_production);output_of_heat_and_cooling_carriers))),BILLIONS)