# 

- deprecated_key = heatpumps_input_of_electricity
- unit = pj

DIVIDE(SUM(
V(
households_space_heater_heatpump_ground_water_electricity,
households_water_heater_district_heating_steam_hot_water,
heatpump_using_city_heat_households_energetic,
households_water_heater_heatpump_air_water_electricity,
agriculture_heatpump_water_water_ts_electricity,
households_collective_space_heater_heatpump_water_water_ts_electricity
,input_of_electricity)),BILLIONS)
