# 

- deprecated_key = centrally_produced_electricity_industry
- unit = mj

MAX(
	SUM(
  		V(industry_final_demand_electricity,demand),
  		NEG(
    		SUM(
      			V(industry_chp_combined_cycle_gas_power_fuelmix,energy_chp_combined_cycle_bio_oil,industry_chp_supercritical_wood_pellets,output_of_electricity)
    		)
  		)
	),
	0
)	
