- deprecated_key = electricity_for_heat_without_heatpumps
# 

- unit = pj

DIVIDE(SUM(V(electric_heater_buildings_energetic ,electric_boiler_households_energetic,electric_heater_households_energetic,input_of_electricity)),BILLIONS)