- unit = PJ
- query =
    V(
      households_space_heater_heatpump_ground_water_electricity,
      households_water_heater_district_heating_steam_hot_water,
      households_water_heater_heatpump_air_water_electricity,
      households_water_heater_heatpump_ground_water_electricity,
      agriculture_heatpump_water_water_ts_electricity,
      households_space_heater_heatpump_air_water_electricity,
      buildings_cooling_airconditioning_electricity,
      buildings_cooling_collective_heatpump_water_water_ts_electricity,
      buildings_cooling_collective_cooling_network_electricity,
      input_of_electricity
    ).sum/BILLIONS
- deprecated_key = heatpumps_input_of_electricity
