# 

- deprecated_key = centrally_produced_electricity_industry
- unit = mj

MAX(
	SUM(
  		V(electricity_industry_energetic,demand),
  		NEG(
    		SUM(
      			V(small_chp_industry_energetic,central_gas_chp_energy_energetic,biomass_chp_industry_energetic,output_of_electricity)
    		)
  		)
	),
	0
)	