- deprecated_key = electricity_for_heat_buildings
# 

- unit = mj

SUM(
  V(
    electric_heater_buildings_energetic,
    heatpump_ts_buildings_energetic,
    biomass_chp_buildings_energetic,
    gas_chp_buildings_energetic,
      input_of_electricity
  )
)