# excluding gas used for electricity production in the CHPs for hot water

- unit = MJ
- query =
    SUM(
      V(Q(hot_water_converters_in_households),demand),
      NEG(Q(gas_allocated_to_electricity_production_in_households_hot_water))
    )
- deprecated_key = total_input_for_hot_water
