# adjusted for the green gas in the gas

- unit = MJ
- query =
    SUM(
      V(Q(hot_water_converters_in_households),
      "input_of_coal + 
      input_of_crude_oil + 
      input_of_network_gas * (1.0 - sustainability_share) + 
      input_of_lng +
      input_of_diesel + 
      input_of_gasoline + 
      input_of_lignite "),
      NEG(Q(gas_allocated_to_electricity_production_in_households_hot_water) * V(energy_national_gas_network_natural_gas, "1.0 - sustainability_share"))
    )
- deprecated_key = households_hot_water_fossil
