# adjusted for the green gas used in the CHPs

- query =
    SUM(
      V(
        households_space_heater_micro_chp_network_gas,
        households_collective_chp_network_gas,
        "steam_hot_water_output_conversion * demand"
      ).sum,
      NEG(
        V(
          households_space_heater_micro_chp_network_gas,
          households_collective_chp_network_gas,
          "steam_hot_water_output_conversion * demand * sustainability_share"
        ).sum
      )
    )
- unit = mj
- deprecated_key = input_of_fossil_households_heating_chps
