# adjusted for the green gas used in the CHPs

- deprecated_key = input_of_fossil_households_heating_chps
- unit = mj

SUM(SUM(V(micro_CHP_production_households,
            collective_gas_chp_households_energetic;
           steam_hot_water_output_conversion * demand
           )
        ),
NEG(
SUM(V(micro_CHP_production_households,
            collective_gas_chp_households_energetic;
           steam_hot_water_output_conversion * demand * sustainability_share
           )
        )))