# The amount of gas that is allocated to the electricity production in the CHPs used in households for hot water.

- unit = mj

SUM(V(LINK(micro_chp_hot_water_households_energetic, national_gas_network_energy),value),
V(LINK(fuel_cell_chp_households_energetic, national_gas_network_energy),value))