# The amount of gas that is allocated to the electricity production in the CHPs used in households for heating.

- unit = mj

V(LINK(micro_chp_space_heating_households, national_gas_network_energy),value)