# The amount of gas that is allocated to the electricity production in the CHPs used in households for heating.

- query = V(LINK(households_space_heater_micro_chp_network_gas, energy_national_gas_network_natural_gas),value)
- unit = mj
