- deprecated_key = industry_other_heat


- unit = mj

MAX(
    SUM(
        V(industry_useful_demand_useable_heat,demand),
        NEG(
            SUM(
                V(industry_chp_combined_cycle_gas_power_fuelmix,energy_chp_combined_cycle_gas_power_fuelmix,industry_chp_supercritical_wood_pellets,output_of_heat_carriers)
            )
        )
    ),
    0
)
