- query =
    V(
      energy_distribution_lpg,
      energy_distribution_diesel,
      energy_distribution_gasoline,
      input_of_crude_oil
    ).sum
- unit = mj
- deprecated_key = oil_use_refinery
