# The total energetic biomass use in the final demand of industry, with the addition of share of green gas in the gas.

- unit = MJ
- query =
    SUM(
      V(INTERSECTION(INTERSECTION(SECTOR(industry),G(final_demand_group)),USE(energetic)),output_of_wood_pellets), 
      PRODUCT(V(energy_national_gas_network_natural_gas,sustainability_share),
      SUM(V(INTERSECTION(INTERSECTION(SECTOR(industry),G(final_demand_group)),USE(energetic)),output_of_network_gas)))
    )
- deprecated_key = biomass_heat_industry
