# Final consumption of electricity in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Electricity -- electricity?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_electricity_in_industry_ict_energetic)
