# Final consumption of hydrogen in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Hydrogen -- hydrogen? || liquid_hydrogen? || lohc?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_hydrogen_in_industry_ict_energetic)
