# Final consumption of heat in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_heat_in_industry_ict_energetic)
