# Final consumption from international transport, all carriers (energetic use only).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_international_transport_energetic)
