- unit = PJ
- query =
    SUM(
      Q(conversion_loss_non_biogenic_waste_to_pyrolysis_oil),
      Q(conversion_loss_non_biogenic_waste_to_diesel),
      Q(conversion_loss_non_biogenic_waste_to_naphtha),
      Q(conversion_loss_non_biogenic_waste_to_kerosene),
      Q(conversion_loss_non_biogenic_waste_to_heat_in_pyrolysis_oil)
    )
