# Energetic final demand of network gas in buildings excluding heating

- unit = PJ
- query = 
    SUM(
      Q(final_demand_of_greengas_in_buildings_space_heating_energetic),
      Q(final_demand_of_natural_gas_in_buildings_space_heating_energetic)
    )
