# Energetic final demand of the 'lng' carrier group in households appliances

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(appliances_households)), "lng?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
