# Energetic final demand of the 'natural_gas' carrier group in households appliances

- unit = PJ
- query =
    PRODUCT(
      SUM(
        SUM(
          V(
            FILTER(
              FILTER(
                INTERSECTION(EG(final_demand),EG(appliances_households)), "network_gas?"
              ),
              "energetic?"
            ),
            value
          )
        ),
        PRODUCT(
          SUM(
            V(
              FILTER(
                FILTER(
                  INTERSECTION(EG(final_demand),EG(appliances_households)), "compressed_network_gas?"
                ),
                "energetic?"
              ),
              value
            )
          ),
          Q(share_of_network_gas_in_compressed_network_gas)
        )
      ),
      Q(share_of_fossil_gas_in_gas_network)
    ) / BILLIONS
