# Energetic final demand of the 'biomass' carrier group in households appliances

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(appliances_households)), "biodiesel? || bio_ethanol? || wood_pellets? || bio_lng? || bio_kerosene? || bio_oil?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
