# Use of carrier group 'natural_gas_and_derivatives' in chemical industry heat

- unit = pj
- query =
    SUM(
      V(CHILDREN(V(industry_useful_demand_for_chemical_useable_heat)),input_of_network_gas)
    ) / BILLIONS
