- query = 
    SUM_CURVES(
      V(
        FILTER(
        ALL(),
        "merit_order && (merit_order.group == :electric_trucks)"
        ), 
        electricity_input_curve
       )
     )

- unit = curve
