- query = 
        NEG(
                SUM(
                        Q(emissions_molecules_other_utilisation_delayed_emitted),
                        Q(emissions_production_synthetic_methanol_emitted)
                )
        )



- unit = tonne