- deprecated_key = chart_coal_power_plants_investment_54_power_plants_468
#

- unit = mln_euro

future:UNIT(SUM(V(Q(electricity_producing_coal_converters),"initial_investment_costs_per(converter)*coal_input_conversion")),millions)
