- deprecated_key = chart_oil_power_plants_investment_54_power_plants_474
#

- unit = mln_euro

future:UNIT(SUM(V(Q(electricity_producing_oil_converters),"total_investment_over_lifetime_per(:converter)*crude_oil_input_conversion")),millions)
