- deprecated_key = chart_other_plants_investm_54_power_plants_499
#

- unit = mln_euro

future:UNIT(SUM(V(Q(electricity_producing_other_converters),total_investment_over_lifetime_per(:converter))),millions)
