- deprecated_key = chart_other_plants_capacity_54_power_plants_498
#

- unit = gj

future:DIVIDE(SUM(V(Q(electricity_producing_other_converters)," nominal_capacity_electricity_output_per_unit * number_of_units")),1000)