- deprecated_key = chart_wind_farms_investm_54_power_plants_489
#

- unit = mln_euro

future:UNIT(SUM(V(G(electricity_production),"total_initial_investment_per(:converter)*wind_input_conversion")),millions)
