# The total costs of the network calculation

- query =
          SUM(
              QUERY_FUTURE(lv_net_total_costs_future),
              QUERY_FUTURE(lv_mv_trafo_total_costs_future),
              QUERY_FUTURE(mv_net_total_costs_future),
              QUERY_FUTURE(mv_hv_trafo_total_costs_future),
              QUERY_FUTURE(hv_net_costs_future_annualised_costs),
              QUERY_FUTURE(interconnection_net_costs_future_annualised_costs),
              QUERY_FUTURE(offshore_net_costs_future_annualised_costs)
          )

- unit = euro
