# The total costs of the network calculation

- query =
          SUM(
              Q(total_costs_of_electricity_network_calculation),
              Q(gas_network_costs_annualised_costs)
          )

- unit = euro
