- unit = PJ
- query = DIVIDE(V(buildings_local_production_electricity,electricity_flexible_input_link_value),BILLIONS) * V(LINK(buildings_local_production_electricity, buildings_final_demand_electricity), parent_share)
