- deprecated_key = chart_chp_s_74_electricity_production_buildings_633
#

- unit = pj

DIVIDE(SUM(V(buildings_collective_chp_natural_gas,buildings_collective_chp_wood_pellets,output_of_electricity)),BILLIONS)
