# Returns the capacity of cofiring crude oil power plants.
- query = 
        PRODUCT(
  		V(energy_chp_ultra_supercritical_cofiring_crude_oil,number_of_units),
  		V(energy_chp_ultra_supercritical_cofiring_crude_oil,electricity_output_capacity)	
  		)
- unit = MW

