# Static queries created for holon, should not be used out of holon context
# Fitted by on Q(costs_infrastructure_heat) for bracket 5 (80% to 100% of residences on district heating) in nl2019

- query = 2493.17
- unit = euro/residence
