# Static queries created for holon, should not be used out of holon context
# Fitted by on Q(costs_infrastructure_heat) for bracket 2 (20% to 40% of residences on district heating) in nl2019

- query = 1413.76
- unit = euro/residence
