# Old query:
# 
# MAX(
#   PRODUCT(
#   Q( peak_load_delta_max_mv_transport_net ),
#   V( mv_transport_network_energy ; simult_wd )
#   ),
#   Q(peak_load_delta_on_mv_hv_transformer)
# )

- unit = mw

MAX(
  Q(peak_load_delta_demand_hv_mv_transformer),
  Q(peak_load_delta_supply_hv_mv_transformer)
)