# Final consumption of natural gas and gas products in industry ex. ict and refineries - fertilizers (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     Natural gas and gas products
# Use type:    Total
#
# Exception: includes the share of natural gas and gas products in network gas.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_natural_gas_and_gas_products_excl_network_gas_in_industry_fertilizers_total),
      Q(final_consumption_of_natural_gas_and_gas_products_in_network_gas_in_industry_fertilizers_total)
    )
