# Final consumption from buildings, all carriers (energetic and non-energetic use combined).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     All carriers
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(EG(final_demand), "sector == :buildings"),
          value
        )
      ),
      BILLIONS
    )
