# Final consumption of solid biofuels, all sectors (non-energetic use only).
#
# Sector:      All sectors
# Carrier:     Solid biofuels -- wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
