# Final consumption of gaseous biofuels in industry ict (energetic and non-energetic use combined).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Gaseous biofuels
# Use type:    Total
#
# Exception: includes the share of gaseous biofuels in network gas.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_gaseous_biofuels_excl_network_gas_in_industry_ict_total),
      Q(final_consumption_of_gaseous_biofuels_in_network_gas_in_industry_ict_total)
    )
