# Final consumption of methanol in industry refineries (energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(refineries_industry)), "methanol?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
