# Final consumption of ammonia in industry ex. ict and refineries - chemicals (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Chemicals -- EG(other_chemical_industry)
# Carrier:     Ammonia -- ammonia?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(other_chemical_industry)), "ammonia?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
