# Final consumption of solar thermal in industry ex. ict and refineries - fertilizers (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     Solar thermal -- solar_thermal?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(fertilizers_industry)), "solar_thermal?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
