# Final consumption of natural gas and gas products in industry ex. ict and refineries (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries -- sector == :industry minus EG(ict_industry), EG(refineries_industry)
# Carrier:     Natural gas and gas products
# Use type:    Total
#
# Exception: industry minus industry ict, industry refineries.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_natural_gas_and_gas_products_in_industry_total),
      NEG(Q(final_consumption_of_natural_gas_and_gas_products_in_industry_ict_total)),
      NEG(Q(final_consumption_of_natural_gas_and_gas_products_in_industry_refineries_total))
    )
