# Final consumption of geothermal in industry ex. ict and refineries - other (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Other -- EG(other_non_specified_industry)
# Carrier:     Geothermal -- geothermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(other_non_specified_industry)), "geothermal?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
