# Final consumption of natural gas and gas products excl. network gas in industry (energetic use only).
#
# Sector:      Industry -- sector == :industry
# Carrier:     Natural gas and gas products excl. network gas -- natural_gas? || propane? || lng?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :industry"),
              "natural_gas? || propane? || lng?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
