# Final consumption of coal and coal products in international transport - international aviation (energetic and non-energetic use combined).
#
# Sector:      International transport - International aviation -- EG(bunkers_international_aviation)
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_aviation)), "coal? || coal_gas? || cokes? || lignite?"),
          value
        )
      ),
      BILLIONS
    )
