# Final consumption of natural gas and gas products excl. network gas in industry ex. ict and refineries - food (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Food -- EG(food_industry)
# Carrier:     Natural gas and gas products excl. network gas -- natural_gas? || propane? || lng?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(food_industry)), "natural_gas? || propane? || lng?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
