# Final consumption from industry ex. ict and refineries - other metals, all carriers (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Other metals -- EG(other_metals_industry)
# Carrier:     All carriers
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          INTERSECTION(EG(final_demand), EG(other_metals_industry)),
          value
        )
      ),
      BILLIONS
    )
