# Final consumption of liquid biofuels, all sectors (non-energetic use only).
#
# Sector:      All sectors
# Carrier:     Liquid biofuels
# Use type:    Non-energetic -- !energetic?
#
# Exception: includes the biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_liquid_biofuels_in_national_transport_non_energetic),
      Q(final_consumption_of_liquid_biofuels_in_industry_non_energetic),
      Q(final_consumption_of_liquid_biofuels_in_other_non_energetic)
    )
