# Final consumption of ammonia in industry ex. ict and refineries (energetic use only).
#
# Sector:      Industry ex. ICT and refineries -- sector == :industry minus EG(ict_industry), EG(refineries_industry)
# Carrier:     Ammonia
# Use type:    Energetic -- energetic?
#
# Exception: industry minus industry ict, industry refineries.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_ammonia_in_industry_energetic),
      NEG(Q(final_consumption_of_ammonia_in_industry_ict_energetic)),
      NEG(Q(final_consumption_of_ammonia_in_industry_refineries_energetic))
    )
