# Final consumption of renewable waste in waste mix in industry ex. ict and refineries - chemicals (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Chemicals -- EG(other_chemical_industry)
# Carrier:     Renewable waste in waste mix
# Use type:    Total
#
# Waste mix times the share of renewable waste in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_waste_mix_in_industry_other_chemical_total),
      Q(share_of_biogenic_waste_in_waste_mix)
    )
