# Final consumption of non-renewable waste in waste mix in industry ex. ict and refineries - food (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Food -- EG(food_industry)
# Carrier:     Non-renewable waste in waste mix
# Use type:    Total
#
# Waste mix times the share of non-renewable waste in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_waste_mix_in_industry_food_total),
      Q(share_of_non_biogenic_waste_in_waste_mix)
    )
