# Final consumption of electricity in international transport - international aviation (energetic use only).
#
# Sector:      International transport - International aviation -- EG(bunkers_international_aviation)
# Carrier:     Electricity -- electricity?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_aviation)), "electricity?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
