# Final consumption of gaseous biofuels excl. network gas in industry refineries (energetic and non-energetic use combined).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Gaseous biofuels excl. network gas -- biogas? || greengas? || bio_lng?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(refineries_industry)), "biogas? || greengas? || bio_lng?"),
          value
        )
      ),
      BILLIONS
    )
