# Final consumption of coal and coal products in industry ex. ict and refineries - food (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Food -- EG(food_industry)
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(food_industry)), "coal? || coal_gas? || cokes? || lignite?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
