# Final consumption of gaseous biofuels excl. network gas in international transport - international aviation (energetic and non-energetic use combined).
#
# Sector:      International transport - International aviation -- EG(bunkers_international_aviation)
# Carrier:     Gaseous biofuels excl. network gas -- biogas? || greengas? || bio_lng?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_aviation)), "biogas? || greengas? || bio_lng?"),
          value
        )
      ),
      BILLIONS
    )
