# Final consumption of oil and oil products in buildings (energetic and non-energetic use combined).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     Oil and oil products
# Use type:    Total
#
# Exception: includes the non-biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_oil_and_oil_products_in_buildings_energetic)
    )
