# Final consumption of renewable waste in industry ex. ict and refineries - paper (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Paper -- EG(paper_industry)
# Carrier:     Renewable waste
# Use type:    Total
#
# Exception: includes the share of renewable waste in waste mix.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_renewable_waste_excl_waste_mix_in_industry_paper_total),
      Q(final_consumption_of_renewable_waste_in_waste_mix_in_industry_paper_total)
    )
