# Final consumption of non-renewable waste excl. waste mix in industry ex. ict and refineries - food (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Food -- EG(food_industry)
# Carrier:     Non-renewable waste excl. waste mix -- non_biogenic_waste?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(food_industry)), "non_biogenic_waste?"),
          value
        )
      ),
      BILLIONS
    )
