# Final consumption of gaseous biofuels in network gas in industry ex. ict and refineries - fertilizers (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     Gaseous biofuels in network gas
# Use type:    Non-energetic -- !energetic?
#
# Network gas times the share of gaseous biofuels in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_network_gas_in_industry_fertilizers_non_energetic),
      Q(share_of_sustainable_gas_in_gas_network)
    )
