# Final consumption of electricity in industry ex. ict and refineries - other (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Other -- EG(other_non_specified_industry)
# Carrier:     Electricity -- electricity?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(other_non_specified_industry)), "electricity?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
