# Final consumption of natural gas and gas products excl. network gas in industry ex. ict and refineries - other (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Other -- EG(other_non_specified_industry)
# Carrier:     Natural gas and gas products excl. network gas -- natural_gas? || propane? || lng?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(other_non_specified_industry)), "natural_gas? || propane? || lng?"),
          value
        )
      ),
      BILLIONS
    )
