# Final consumption of gaseous biofuels excl. network gas in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Gaseous biofuels excl. network gas -- biogas? || greengas? || bio_lng?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(ict_industry)), "biogas? || greengas? || bio_lng?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
