# Final consumption of waste mix in buildings (energetic and non-energetic use combined).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     Waste mix -- waste_mix?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :buildings"),
            "waste_mix?"
          ),
          value
        )
      ),
      BILLIONS
    )
