# Final consumption of gaseous biofuels in network gas in international transport (energetic use only).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     Gaseous biofuels in network gas
# Use type:    Energetic -- energetic?
#
# Network gas times the share of gaseous biofuels in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_network_gas_in_international_transport_energetic),
      Q(share_of_sustainable_gas_in_gas_network)
    )
