# Final consumption of solid biofuels in households (energetic and non-energetic use combined).
#
# Sector:      Households -- sector == :households
# Carrier:     Solid biofuels -- wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :households"),
            "wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?"
          ),
          value
        )
      ),
      BILLIONS
    )
