# Final consumption of geothermal in industry ex. ict and refineries - fertilizers (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     Geothermal -- geothermal?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(fertilizers_industry)), "geothermal?"),
          value
        )
      ),
      BILLIONS
    )
