# Final consumption of coal and coal products in buildings (energetic and non-energetic use combined).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :buildings"),
            "coal? || coal_gas? || cokes? || lignite?"
          ),
          value
        )
      ),
      BILLIONS
    )
