# Final consumption of geothermal in industry refineries (non-energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Geothermal -- geothermal?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(refineries_industry)), "geothermal?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
