# Final consumption of heat in industry ex. ict and refineries - food (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Food -- EG(food_industry)
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(food_industry)), "steam_hot_water? || useable_heat?"),
          value
        )
      ),
      BILLIONS
    )
