# Final consumption of coal and coal products in other (non-energetic use only).
#
# Sector:      Other -- sector == :other
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :other"),
              "coal? || coal_gas? || cokes? || lignite?"
            ),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
