# Final consumption of network gas in industry ict (energetic and non-energetic use combined).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Network gas -- network_gas? || compressed_network_gas?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(ict_industry)), "network_gas? || compressed_network_gas?"),
          value
        )
      ),
      BILLIONS
    )
