# Final consumption of gaseous biofuels in network gas in national transport (energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Gaseous biofuels in network gas
# Use type:    Energetic -- energetic?
#
# Network gas times the share of gaseous biofuels in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_network_gas_in_national_transport_energetic),
      Q(share_of_sustainable_gas_in_gas_network)
    )
