# Final consumption of waste mix in industry ex. ict and refineries - aluminium (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Aluminium -- EG(aluminium_industry)
# Carrier:     Waste mix -- waste_mix?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(aluminium_industry)), "waste_mix?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
