# Final consumption of liquid biofuels in households (energetic and non-energetic use combined).
#
# Sector:      Households -- sector == :households
# Carrier:     Liquid biofuels
# Use type:    Total
#
# Exception: includes the biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_liquid_biofuels_in_households_energetic)
    )
