# Final consumption of gaseous biofuels in network gas in buildings (energetic and non-energetic use combined).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     Gaseous biofuels in network gas
# Use type:    Total
#
# Network gas times the share of gaseous biofuels in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_network_gas_in_buildings_total),
      Q(share_of_sustainable_gas_in_gas_network)
    )
