# Final consumption of natural gas and gas products in network gas in energy (energetic use only).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Natural gas and gas products in network gas
# Use type:    Energetic -- energetic?
#
# Network gas times the share of natural gas and gas products in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_network_gas_in_energy_energetic),
      Q(share_of_fossil_gas_in_gas_network)
    )
