# Final consumption of renewable waste excl. waste mix in national transport (energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Renewable waste excl. waste mix -- biogenic_waste?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :transport"),
              "biogenic_waste?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
