# Final consumption of non-renewable waste in waste mix in international transport (energetic use only).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     Non-renewable waste in waste mix
# Use type:    Energetic -- energetic?
#
# Waste mix times the share of non-renewable waste in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_waste_mix_in_international_transport_energetic),
      Q(share_of_non_biogenic_waste_in_waste_mix)
    )
