# Final consumption of hydrogen in energy (energetic use only).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Hydrogen -- hydrogen? || liquid_hydrogen? || lohc?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :energy"),
              "hydrogen? || liquid_hydrogen? || lohc?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
