# Final consumption of methanol in industry ex. ict and refineries - food (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Food -- EG(food_industry)
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(food_industry)), "methanol?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
