# Final consumption from industry ex. ict and refineries - food, all carriers (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Food -- EG(food_industry)
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(food_industry)), "energetic?"),
          value
        )
      ),
      BILLIONS
    )
