# Final consumption of coal and coal products in international transport - international navigation (energetic use only).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_navigation)), "coal? || coal_gas? || cokes? || lignite?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
