# Final consumption of electricity in other (energetic and non-energetic use combined).
#
# Sector:      Other -- sector == :other
# Carrier:     Electricity -- electricity?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :other"),
            "electricity?"
          ),
          value
        )
      ),
      BILLIONS
    )
