# Final consumption of network gas in international transport - international navigation (energetic use only).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Network gas -- network_gas? || compressed_network_gas?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_navigation)), "network_gas? || compressed_network_gas?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
