# Final consumption from industry, all carriers (non-energetic use only).
#
# Sector:      Industry -- sector == :industry
# Carrier:     All carriers
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :industry"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
