# Final consumption of heat in energy (energetic use only).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :energy"),
              "steam_hot_water? || useable_heat?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
