# Final consumption of solid biofuels in other (non-energetic use only).
#
# Sector:      Other -- sector == :other
# Carrier:     Solid biofuels -- wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :other"),
              "wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?"
            ),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
