# Final consumption of solar thermal in buildings (energetic and non-energetic use combined).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     Solar thermal -- solar_thermal?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :buildings"),
            "solar_thermal?"
          ),
          value
        )
      ),
      BILLIONS
    )
