# Final consumption of non-renewable waste excl. waste mix in international transport - international aviation (energetic and non-energetic use combined).
#
# Sector:      International transport - International aviation -- EG(bunkers_international_aviation)
# Carrier:     Non-renewable waste excl. waste mix -- non_biogenic_waste?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_aviation)), "non_biogenic_waste?"),
          value
        )
      ),
      BILLIONS
    )
