# Final consumption of non-renewable waste in waste mix in industry ex. ict and refineries - other metals (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Other metals -- EG(other_metals_industry)
# Carrier:     Non-renewable waste in waste mix
# Use type:    Energetic -- energetic?
#
# Waste mix times the share of non-renewable waste in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_waste_mix_in_industry_other_metals_energetic),
      Q(share_of_non_biogenic_waste_in_waste_mix)
    )
