# Final consumption from national transport, all carriers (non-energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     All carriers
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :transport"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
