# Final consumption of ammonia, all sectors (non-energetic use only).
#
# Sector:      All sectors
# Carrier:     Ammonia -- ammonia?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "ammonia?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
