# Final consumption of ammonia in industry ex. ict and refineries - chemicals (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Chemicals -- EG(other_chemical_industry)
# Carrier:     Ammonia -- ammonia?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(other_chemical_industry)), "ammonia?"),
          value
        )
      ),
      BILLIONS
    )
