# Final consumption of gaseous biofuels in network gas in industry ex. ict and refineries - other metals (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Other metals -- EG(other_metals_industry)
# Carrier:     Gaseous biofuels in network gas
# Use type:    Energetic -- energetic?
#
# Network gas times the share of gaseous biofuels in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_network_gas_in_industry_other_metals_energetic),
      Q(share_of_sustainable_gas_in_gas_network)
    )
