# Final consumption of gaseous biofuels excl. network gas in national transport (non-energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Gaseous biofuels excl. network gas -- biogas? || greengas? || bio_lng?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :transport"),
              "biogas? || greengas? || bio_lng?"
            ),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
