# Final consumption of renewable waste excl. waste mix in other (non-energetic use only).
#
# Sector:      Other -- sector == :other
# Carrier:     Renewable waste excl. waste mix -- biogenic_waste?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :other"),
              "biogenic_waste?"
            ),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
