# Final consumption of non-renewable waste in industry ex. ict and refineries - fertilizers (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     Non-renewable waste
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of non-renewable waste in waste mix.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_non_renewable_waste_excl_waste_mix_in_industry_fertilizers_energetic),
      Q(final_consumption_of_non_renewable_waste_in_waste_mix_in_industry_fertilizers_energetic)
    )
