# Final consumption of liquid biofuels in industry ex. ict and refineries - other metals (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Other metals -- EG(other_metals_industry)
# Carrier:     Liquid biofuels -- biodiesel? || bio_ethanol? || bio_kerosene? || bio_oil? || bionaphtha? || biomethanol? || bio_pyrolysis_oil? || oily_biomass? + crude_oil? x Q(share_of_biogenic_in_industry_final_demand_crude_oil_energetic)
# Use type:    Energetic -- energetic?
#
# Exception: includes the biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(other_metals_industry)), "biodiesel? || bio_ethanol? || bio_kerosene? || bio_oil? || bionaphtha? || biomethanol? || bio_pyrolysis_oil? || oily_biomass?"),
            "energetic?"
          ),
          value
        ),
        PRODUCT(
          SUM(
            V(
              FILTER(
                FILTER(INTERSECTION(EG(final_demand), EG(other_metals_industry)), "crude_oil?"),
                "energetic?"
              ),
              value
            )
          ),
          Q(share_of_biogenic_in_industry_final_demand_crude_oil_energetic)
        )
      ),
      BILLIONS
    )
