# Final consumption of natural gas and gas products excl. network gas in energy (energetic and non-energetic use combined).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Natural gas and gas products excl. network gas -- natural_gas? || propane? || lng?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :energy"),
            "natural_gas? || propane? || lng?"
          ),
          value
        )
      ),
      BILLIONS
    )
