# Final consumption of coal and coal products in industry ict (energetic and non-energetic use combined).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(ict_industry)), "coal? || coal_gas? || cokes? || lignite?"),
          value
        )
      ),
      BILLIONS
    )
