# Final consumption of renewable waste excl. waste mix, all sectors (energetic use only).
#
# Sector:      All sectors
# Carrier:     Renewable waste excl. waste mix -- biogenic_waste?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "biogenic_waste?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
