# Final consumption of hydrogen in international transport (energetic use only).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     Hydrogen -- hydrogen? || liquid_hydrogen? || lohc?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :bunkers"),
              "hydrogen? || liquid_hydrogen? || lohc?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
