# Final consumption of methanol in other (non-energetic use only).
#
# Sector:      Other -- sector == :other
# Carrier:     Methanol -- methanol?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :other"),
              "methanol?"
            ),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
