# Final consumption of non-renewable waste excl. waste mix in industry refineries (energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Non-renewable waste excl. waste mix -- non_biogenic_waste?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(refineries_industry)), "non_biogenic_waste?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
