# Final consumption of renewable waste in waste mix in agriculture (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Renewable waste in waste mix
# Use type:    Energetic -- energetic?
#
# Waste mix times the share of renewable waste in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_waste_mix_in_agriculture_energetic),
      Q(share_of_biogenic_waste_in_waste_mix)
    )
