# Final consumption of network gas in energy (energetic use only).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Network gas -- network_gas? || compressed_network_gas?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :energy"),
              "network_gas? || compressed_network_gas?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
