# Final consumption of liquid biofuels in industry ex. ict and refineries - aluminium (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Aluminium -- EG(aluminium_industry)
# Carrier:     Liquid biofuels
# Use type:    Total
#
# Exception: includes the biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_liquid_biofuels_in_industry_aluminium_energetic)
    )
