# Final consumption of gaseous biofuels excl. network gas in industry refineries (non-energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Gaseous biofuels excl. network gas -- biogas? || greengas? || bio_lng?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(refineries_industry)), "biogas? || greengas? || bio_lng?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
