# Final consumption of methanol in national transport (energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :transport"),
              "methanol?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
