# Final consumption of gaseous biofuels excl. network gas in buildings (energetic use only).
#
# Sector:      Buildings -- sector == :buildings
# Carrier:     Gaseous biofuels excl. network gas -- biogas? || greengas? || bio_lng?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :buildings"),
              "biogas? || greengas? || bio_lng?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
