# Final consumption from agriculture, all carriers (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :agriculture"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
