# Final consumption of waste mix, all sectors (non-energetic use only).
#
# Sector:      All sectors
# Carrier:     Waste mix -- waste_mix?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "waste_mix?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
