# Final consumption from industry, all carriers (energetic and non-energetic use combined).
#
# Sector:      Industry -- sector == :industry
# Carrier:     All carriers
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(EG(final_demand), "sector == :industry"),
          value
        )
      ),
      BILLIONS
    )
