# Final consumption of geothermal in agriculture (energetic and non-energetic use combined).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Geothermal -- geothermal?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :agriculture"),
            "geothermal?"
          ),
          value
        )
      ),
      BILLIONS
    )
