# Final consumption of renewable waste excl. waste mix in international transport - international navigation (energetic use only).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Renewable waste excl. waste mix -- biogenic_waste?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_navigation)), "biogenic_waste?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
