# Final consumption of hydrogen, all sectors (energetic and non-energetic use combined).
#
# Sector:      All sectors
# Carrier:     Hydrogen -- hydrogen? || liquid_hydrogen? || lohc?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(EG(final_demand), "hydrogen? || liquid_hydrogen? || lohc?"),
          value
        )
      ),
      BILLIONS
    )
