# Final consumption of renewable waste excl. waste mix in industry refineries (energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Renewable waste excl. waste mix -- biogenic_waste?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(refineries_industry)), "biogenic_waste?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
