# Final consumption of methanol in industry ex. ict and refineries - steel (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Steel -- EG(steel_industry)
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(steel_industry)), "methanol?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
