# Final consumption of oil and oil products in national transport (energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Oil and oil products -- crude_oil? || gasoline? || diesel? || lpg? || kerosene? || heavy_fuel_oil? || naphtha? || refinery_gas? || pyrolysis_oil?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :transport"),
              "crude_oil? || gasoline? || diesel? || lpg? || kerosene? || heavy_fuel_oil? || naphtha? || refinery_gas? || pyrolysis_oil?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
