# Final consumption of heat in households (energetic use only).
#
# Sector:      Households -- sector == :households
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :households"),
              "steam_hot_water? || useable_heat?"
            ),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
