# Final consumption of network gas in industry ex. ict and refineries - fertilizers (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     Network gas -- network_gas? || compressed_network_gas?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(fertilizers_industry)), "network_gas? || compressed_network_gas?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
