# Final consumption of methanol in national transport (energetic and non-energetic use combined).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Methanol -- methanol?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :transport"),
            "methanol?"
          ),
          value
        )
      ),
      BILLIONS
    )
