# Final consumption of renewable waste in waste mix in industry (non-energetic use only).
#
# Sector:      Industry -- sector == :industry
# Carrier:     Renewable waste in waste mix
# Use type:    Non-energetic -- !energetic?
#
# Waste mix times the share of renewable waste in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_waste_mix_in_industry_non_energetic),
      Q(share_of_biogenic_waste_in_waste_mix)
    )
