# Final consumption of waste mix in industry ex. ict and refineries - chemicals (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Chemicals -- EG(other_chemical_industry)
# Carrier:     Waste mix -- waste_mix?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(other_chemical_industry)), "waste_mix?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
