# Final consumption of renewable waste excl. waste mix, all sectors (energetic and non-energetic use combined).
#
# Sector:      All sectors
# Carrier:     Renewable waste excl. waste mix -- biogenic_waste?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(EG(final_demand), "biogenic_waste?"),
          value
        )
      ),
      BILLIONS
    )
