# Final consumption of coal and coal products in industry ex. ict and refineries - fertilizers (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(fertilizers_industry)), "coal? || coal_gas? || cokes? || lignite?"),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
