# Final consumption of non-renewable waste in waste mix in households (energetic and non-energetic use combined).
#
# Sector:      Households -- sector == :households
# Carrier:     Non-renewable waste in waste mix
# Use type:    Total
#
# Waste mix times the share of non-renewable waste in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_waste_mix_in_households_total),
      Q(share_of_non_biogenic_waste_in_waste_mix)
    )
