# Final consumption of methanol in international transport - international navigation (energetic and non-energetic use combined).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Methanol -- methanol?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_navigation)), "methanol?"),
          value
        )
      ),
      BILLIONS
    )
