# Final consumption of natural gas and gas products in international transport (energetic use only).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     Natural gas and gas products
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of natural gas and gas products in network gas.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_natural_gas_and_gas_products_excl_network_gas_in_international_transport_energetic),
      Q(final_consumption_of_natural_gas_and_gas_products_in_network_gas_in_international_transport_energetic)
    )
