# Final consumption of methanol, all sectors (energetic use only).
#
# Sector:      All sectors
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "methanol?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
