# Final consumption of renewable waste in waste mix in energy (energetic and non-energetic use combined).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Renewable waste in waste mix
# Use type:    Total
#
# Waste mix times the share of renewable waste in it.

- unit = PJ
- query =
    PRODUCT(
      Q(final_consumption_of_waste_mix_in_energy_total),
      Q(share_of_biogenic_waste_in_waste_mix)
    )
