# Final consumption of solid biofuels in international transport - international navigation (energetic use only).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Solid biofuels -- wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_navigation)), "wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
