# Final consumption of solid biofuels in industry ex. ict and refineries - aluminium (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Aluminium -- EG(aluminium_industry)
# Carrier:     Solid biofuels -- wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(aluminium_industry)), "wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?"),
          value
        )
      ),
      BILLIONS
    )
