# Final consumption of network gas in industry ex. ict and refineries - chemicals (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Chemicals -- EG(other_chemical_industry)
# Carrier:     Network gas -- network_gas? || compressed_network_gas?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(other_chemical_industry)), "network_gas? || compressed_network_gas?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
