# Final consumption of renewable waste excl. waste mix in industry ex. ict and refineries - chemicals (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Chemicals -- EG(other_chemical_industry)
# Carrier:     Renewable waste excl. waste mix -- biogenic_waste?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(other_chemical_industry)), "biogenic_waste?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
