# Final consumption of gaseous biofuels in national transport (energetic and non-energetic use combined).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Gaseous biofuels
# Use type:    Total
#
# Exception: includes the share of gaseous biofuels in network gas.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_gaseous_biofuels_excl_network_gas_in_national_transport_total),
      Q(final_consumption_of_gaseous_biofuels_in_network_gas_in_national_transport_total)
    )
