# Final consumption of ammonia in energy (energetic and non-energetic use combined).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Ammonia -- ammonia?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :energy"),
            "ammonia?"
          ),
          value
        )
      ),
      BILLIONS
    )
