# Final consumption of non-renewable waste in international transport - international aviation (energetic use only).
#
# Sector:      International transport - International aviation -- EG(bunkers_international_aviation)
# Carrier:     Non-renewable waste
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of non-renewable waste in waste mix.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_non_renewable_waste_excl_waste_mix_in_bunkers_international_aviation_energetic),
      Q(final_consumption_of_non_renewable_waste_in_waste_mix_in_bunkers_international_aviation_energetic)
    )
