# Final consumption of network gas in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Network gas -- network_gas? || compressed_network_gas?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(ict_industry)), "network_gas? || compressed_network_gas?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
