# Final consumption from energy, all carriers (energetic use only).
#
# Sector:      Energy -- sector == :energy
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :energy"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
