# Final consumption of solar thermal in industry ex. ict and refineries - aluminium (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Aluminium -- EG(aluminium_industry)
# Carrier:     Solar thermal -- solar_thermal?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(aluminium_industry)), "solar_thermal?"),
          value
        )
      ),
      BILLIONS
    )
