# Final consumption of non-renewable waste excl. waste mix in international transport (energetic and non-energetic use combined).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     Non-renewable waste excl. waste mix -- non_biogenic_waste?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :bunkers"),
            "non_biogenic_waste?"
          ),
          value
        )
      ),
      BILLIONS
    )
