# Final consumption of ammonia in international transport - international navigation (energetic use only).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Ammonia -- ammonia?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(bunkers_international_navigation)), "ammonia?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
