# Final consumption of waste mix in agriculture (energetic and non-energetic use combined).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Waste mix -- waste_mix?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(EG(final_demand), "sector == :agriculture"),
            "waste_mix?"
          ),
          value
        )
      ),
      BILLIONS
    )
