# Final consumption of waste mix in industry refineries (energetic and non-energetic use combined).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Waste mix -- waste_mix?
# Use type:    Total

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(refineries_industry)), "waste_mix?"),
          value
        )
      ),
      BILLIONS
    )
