# Final consumption from industry refineries, all carriers (non-energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     All carriers
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(INTERSECTION(EG(final_demand), EG(refineries_industry)), "!energetic?"),
          value
        )
      ),
      BILLIONS
    )
