# Final consumption of oil and oil products in industry ex. ict and refineries - other metals (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Other metals -- EG(other_metals_industry)
# Carrier:     Oil and oil products -- gasoline? || diesel? || lpg? || kerosene? || heavy_fuel_oil? || naphtha? || refinery_gas? || pyrolysis_oil? + crude_oil? x Q(share_of_non_biogenic_in_industry_final_demand_crude_oil_energetic)
# Use type:    Energetic -- energetic?
#
# Exception: includes the non-biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(other_metals_industry)), "gasoline? || diesel? || lpg? || kerosene? || heavy_fuel_oil? || naphtha? || refinery_gas? || pyrolysis_oil?"),
            "energetic?"
          ),
          value
        ),
        PRODUCT(
          SUM(
            V(
              FILTER(
                FILTER(INTERSECTION(EG(final_demand), EG(other_metals_industry)), "crude_oil?"),
                "energetic?"
              ),
              value
            )
          ),
          Q(share_of_non_biogenic_in_industry_final_demand_crude_oil_energetic)
        )
      ),
      BILLIONS
    )
