# Final consumption of heat in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Heat -- steam_hot_water? || useable_heat?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(INTERSECTION(EG(final_demand), EG(ict_industry)), "steam_hot_water? || useable_heat?"),
            "energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
