# Final consumption of geothermal in industry (non-energetic use only).
#
# Sector:      Industry -- sector == :industry
# Carrier:     Geothermal -- geothermal?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(EG(final_demand), "sector == :industry"),
              "geothermal?"
            ),
            "!energetic?"
          ),
          value
        )
      ),
      BILLIONS
    )
