# Query for Sankey diagram: connection between biomass_products and households

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_households_appliances_energetic),
      Q(final_demand_of_biomass_products_in_households_cooking_energetic),
      Q(final_demand_of_biomass_products_in_households_cooling_energetic),
      Q(final_demand_of_biomass_products_in_households_lighting_energetic),
      Q(final_demand_of_greengas_in_households_appliances_energetic),
      Q(final_demand_of_greengas_in_households_cooking_energetic),
      Q(final_demand_of_greengas_in_households_cooling_energetic),
      Q(final_demand_of_greengas_in_households_lighting_energetic)
    )
