# Query for Sankey diagram: connection between biomass_products and bunkers

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_bunkers_energetic),
      Q(final_demand_of_greengas_in_bunkers_energetic)
    )
