# Query for Sankey diagram: connection between biomass_products and buildings

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_buildings_space_heating_energetic),
      Q(final_demand_of_greengas_in_buildings_space_heating_energetic)
    )
