# Query for Sankey diagram: connection between biomass_products and electricity

- unit = PJ
- query = DIVIDE(SUM(V(Q(electricity_producing_converters_sankey), primary_demand_of(non_biogenic_waste, greengas , biodiesel , bio_ethanol , bio_lng , bio_oil , biogas , bio_kerosene, torrefied_biomass_pellets , wood_pellets , biogenic_waste))),BILLIONS)
