# Query for Sankey diagram: connection between biomass_products and other

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_other_energetic),
      Q(final_demand_of_greengas_in_other_energetic)
    )
