# Query for Sankey download: connection between biomass_products and agriculture

- unit = PJ
- query = 
    SUM(
      Q(final_demand_of_biomass_products_in_agriculture_energetic),
      Q(final_demand_of_green_gas_in_agriculture_energetic)
    )
