# Query for Sankey download: connection between biomass_products and industry ICT

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_ict_industry_energetic),
      Q(final_demand_of_greengas_in_ict_industry_energetic),
    )
