# Query for Sankey diagram: connection between biomass_products and energy

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_energy_energetic),
      Q(final_demand_of_greengas_in_energy_energetic)
    )
