# Query for Sankey diagram: connection between central heat and conversion loss corrected for p2h central which is shown explicitly

- unit = PJ
- query = Q(central_heat_prod_to_conversion_loss_in_sankey) - Q(p2h_central_heat_to_conversion_loss_in_sankey)
