# Query for Sankey diagram: connection between central heat and conversion loss
# This includes negative 'losses' for heaters with efficiency > 100% (caused by LHV correction)

- unit = PJ
- query =
    DIVIDE(
      SUM(V(
        Q(central_heat_producing_converters_sankey), output_of_loss)),
        BILLIONS)
