# GroupforSankey: all central heat producing nodes excluding chps

- query =
    FILTER(G(heat_production),"electricity_output_conversion == 0.0 && steam_hot_water_output_conversion > 0.0")
- unit = nodes
