# Query for Sankey diagram: connection between central heat and other

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(other),G(final_demand_group)),USE(energetic)),"input_of_steam_hot_water")),BILLIONS) * Q(fraction_of_central_heaters_in_central_heat_sankey)
