# Query for Sankey diagram: connection between chp heat and energy

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(energy),G(final_demand_group)),USE(energetic)),"input_of_steam_hot_water")),BILLIONS) * Q(fraction_of_chps_in_central_heat_sankey)
