# Query for Sankey diagram: connection between electricity and industry corrected for p2h industry which is shown explicitly

- unit = PJ
- query = Q(electricity_prod_to_industry_in_sankey) - Q(electricity_prod_to_p2h_industry_in_sankey)
