# Query for Sankey diagram: connection between electricity and industry

- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(INTERSECTION(G(final_demand_group),USE(non_energetic)),"input_of_electricity")
        ),
    BILLIONS)
