# Query for Sankey diagram: connection between geo_ambient and central heat proudction corrected for p2h central heat which is shown explicitly as heat input

- query = Q(geo_ambient_to_central_heat_prod_in_sankey) - Q(geo_ambient_to_p2h_central_heat_in_sankey)
- unit = PJ
