# Query for Sankey diagram: connection between geo_ambient and hydrogen_production

- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(Q(electricity_producing_converters_sankey).select {|node| node.input_slots.detect { |slot| slot.carrier.geothermal? }}, primary_demand_of(electricity)),
            V(Q(electricity_producing_converters_sankey).select {|node| node.input_slots.detect { |slot| slot.carrier.ambient_heat? }}, primary_demand_of(electricity)),
            V(Q(electricity_producing_converters_sankey).select {|node| node.input_slots.detect { |slot| slot.carrier.ambient_cold? }}, primary_demand_of(electricity))
        ),
      BILLIONS)