# GroupforSankey

- query =
    V(
      FILTER(G(costs_production_dedicated_hydrogen_production), "hydrogen_output_conversion > 0"),
      energy_imported_hydrogen_backup,
      energy_imported_hydrogen_baseload
    )
- unit = nodes
