# Query for Sankey diagram: connection between ammonia and buildings

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(buildings),G(final_demand_group)), USE(energetic)), "input_of_ammonia")), BILLIONS)
