# Query for Sankey diagram: connection between ammonia and households

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(households),G(final_demand_group)), USE(energetic)), "input_of_ammonia")), BILLIONS)
