# Query for Sankey diagram: connection between imported electricity and hydrogen_production

- unit = PJ
- query = DIVIDE(SUM(V(Q(hydrogen_producing_converters_sankey), primary_demand_of(imported_electricity))),BILLIONS)
