# Query for Sankey diagram: connection between natural_gas and other

- unit = PJ
- query =
    DIVIDE(
      SUM(
        SUM(
          V(INTERSECTION(INTERSECTION(SECTOR(other),G(final_demand_group)),USE(energetic)),"input_of_natural_gas + input_of_lng + input_of_propane")
        ),
        SUM( 
          V(INTERSECTION(INTERSECTION(SECTOR(other),G(final_demand_group)),USE(energetic)),"input_of_compressed_network_gas + input_of_network_gas")
        ) * Q(share_of_fossil_gas_in_gas_network)
      ),
      BILLIONS
    )
