# Query for Sankey diagram: connection between solar and other

- unit = PJ
- query = DIVIDE(SUM(V(INTERSECTION(SECTOR(other),G(final_demand_group)),"input_of_solar_radiation + input_of_solar_thermal")),BILLIONS)
