# Query for Sankey diagram: connection between wind and electricity

- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(Q(electricity_producing_wind_converters), primary_demand_of(electricity))
        ),
        BILLIONS
    )
