# This query calculates the insulation costs for terraced houses and differentiates between costs
# for existing and new houses. The calculated costs are only updated for the future year, in the
# present year the insulation costs are assumed to be zero. This is done with this IF-statements
# `IF(GRAPH().future?, etc., etc.).

- unit = euro
- query =
    insulation_costs_existing_terraced_houses = INSULATION_COST(existing_terraced_houses, AREA(insulation_terraced_houses_start_value ), INPUT_VALUE(households_insulation_level_terraced_houses));
    insulation_costs_new_terraced_houses = INSULATION_COST(new_builds, terraced_houses, INPUT_VALUE(households_insulation_level_terraced_houses));
    present_number_of_terraced_houses = QUERY_PRESENT(-> { AREA(number_of_terraced_houses) });
    future_number_of_terraced_houses = DIVIDE(INPUT_VALUE(households_terraced_houses_share),100.0) * QUERY_FUTURE(-> { AREA(number_of_residences) });

    IF(
      GRAPH().future?,
      -> {
        IF(
          future_number_of_terraced_houses >= present_number_of_terraced_houses,
          -> { insulation_costs_existing_terraced_houses * present_number_of_terraced_houses + insulation_costs_new_terraced_houses * (future_number_of_terraced_houses - present_number_of_terraced_houses) },
          -> { insulation_costs_existing_terraced_houses * future_number_of_terraced_houses }
        )
      },
      0.0
    )
