# This query calculates the insulation costs for apartments and differentiates between costs
# for existing and new houses. The calculated costs are only updated for the future year, in the
# present year the insulation costs are assumed to be zero. This is done with this IF-statements
# `IF(GRAPH().future?, etc., etc.).

- unit = euro
- query =
    insulation_costs_existing_apartments = INSULATION_COST(existing_apartments, AREA(insulation_apartments_start_value ), INPUT_VALUE(households_insulation_level_apartments));
    insulation_costs_new_apartments = INSULATION_COST(new_builds, apartments, INPUT_VALUE(households_insulation_level_apartments));
    present_number_of_apartments = QUERY_PRESENT(-> { AREA(number_of_apartments) });
    future_number_of_apartments = DIVIDE(INPUT_VALUE(households_apartments_share),100.0) * QUERY_FUTURE(-> { AREA(number_of_residences) });

    IF(
      GRAPH().future?,
      -> {
        IF(
          future_number_of_apartments >= present_number_of_apartments,
          -> { insulation_costs_existing_apartments * present_number_of_apartments + insulation_costs_new_apartments * (future_number_of_apartments - present_number_of_apartments) },
          -> { insulation_costs_existing_apartments * future_number_of_apartments }
        )
      },
      0.0
    )
