# This query calculates the insulation costs for detached_houses_future
# The calculated costs are only updated for the future year, in the present year 
# the insulation costs are assumed to be zero. This is done with IF-statements.
# See https://docs.energytransitionmodel.com/main/insulation/#insulation-costs

- query =
    insulation_value_present =               QUERY_PRESENT(-> { AREA(typical_useful_demand_for_space_heating_detached_houses_future) });
    insulation_value_future =                QUERY_FUTURE(-> { AREA(typical_useful_demand_for_space_heating_detached_houses_future) });
    insulation_value_threshold_costs =       220.0;

    detached_houses_insulaton_costs_low =    DIVIDE(26000.0,(403.0 - insulation_value_treshold);
    detached_houses_insulaton_costs_high =   DIVIDE(26000.0,(insulation_value_treshold - 118.0);

    number_of_detached_houses_future =       V(households_useful_demand_for_space_heating_detached_houses_future, number_of_units);

    IF(
      GRAPH().future?,
      -> {
        PRODUCT(
          SUM(
            PRODUCT(
              detached_houses_insulaton_costs_low,
              MAX(MIN((insulation_value_present - insulation_value_threshold),(insulation_value_present - insulation_value_future)),0)
            ),
            PRODUCT(
              detached_houses_insulaton_costs_high,
              MAX((insulation_value_threshold - insulation_value_future),0)
            )
          ),
          number_of_detached_houses_future
        )
      },
      0.0
    )
- unit = euro
