# Costs of the insulation in old houses, new houses and builings.

- query =
    SUM(
      Q(costs_of_insulation_corner_houses),
      Q(costs_of_insulation_detached_houses),
      Q(costs_of_insulation_semi_detached_houses),
      Q(costs_of_insulation_terraced_houses),
      Q(costs_of_insulation_apartments)
    )
- unit = euro
- deprecated_key = insulation_costs
