#This query calculates the insulation costs for buildings and differentiates between costs
#for existing and new buildings. The calculated costs are only updated for the future year, in the
#present year the insulation costs are assumed to be zero. This is done with this IF-statements
# `IF(GRAPH().future?, etc., etc.).

- unit = euro
- query =
    insulation_costs_existing_buildings = INSULATION_COST(existing_buildings, AREA(insulation_buildings_start_value), INPUT_VALUE(buildings_insulation_level));
    insulation_costs_new_buildings = INSULATION_COST(new_builds, buildings, INPUT_VALUE(buildings_insulation_level));
    present_number_of_buildings = QUERY_PRESENT(-> { AREA(number_of_buildings) });
    future_number_of_buildings = QUERY_FUTURE(-> { AREA(number_of_buildings) });

    IF(
      GRAPH().future?,
      -> {
        IF(
          future_number_of_buildings >= present_number_of_buildings,
          -> { insulation_costs_existing_buildings * present_number_of_buildings + insulation_costs_new_buildings * (future_number_of_buildings - present_number_of_buildings) },
          -> { insulation_costs_existing_buildings * future_number_of_buildings }
        )
      },
      0.0
    )
