# Energetic final demand of the 'solar' carrier group in industry excl. ict

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_solar_in_industry_energetic),
      - Q(final_demand_of_solar_in_ict_industry_energetic)
    )
