- unit = MJ
- query =
    SUM(
      Q(kerosene_supply_synthetic_kerosene_must_run),
      Q(kerosene_supply_synthetic_kerosene_dispatchable),
      Q(kerosene_supply_bio_kerosene),
      Q(kerosene_supply_refineries),
      Q(kerosene_supply_transformation),
      Q(kerosene_supply_import)
    )
