- query =
    SUM(
      Q(industry_final_demand_steam_hot_water_in_industrial_heat_network_mekko),
      Q(industry_unused_local_production_steam_hot_water_in_industrial_heat_network_mekko),
      Q(industry_demand_chemical_fertilizers_transformation_heat_network_mekko),
      Q(industry_demand_chemical_other_transformation_heat_network_mekko),
      Q(industry_demand_chemical_refineries_transformation_heat_network_mekko)
    )
