- query = 
    SUM(
      Q(supply_of_greengas_gasification_dry_biomass_for_network_gas_mekko),
      Q(supply_of_greengas_gasification_wet_biomass_for_network_gas_mekko),
      Q(supply_of_greengas_upgrade_biogas_for_network_gas_mekko),
      Q(supply_of_lng_regasification_for_network_gas_mekko),
      Q(supply_of_natural_gas_extraction_for_network_gas_mekko),
      Q(supply_of_natural_gas_import_for_network_gas_mekko),
      Q(supply_of_propane_import_for_network_gas_mekko),
      Q(supply_of_industry_transformation_supply_for_network_gas_mekko)
    )
- unit = PJ
