- query = 
    SUM(
      Q(kerosene_demand_domestic_aviation),
      Q(kerosene_demand_international_aviation),
      Q(kerosene_demand_export),
      Q(kerosene_demand_agriculture),
      Q(kerosene_demand_buildings),
      Q(kerosene_demand_industry),
      Q(kerosene_demand_households),
      Q(kerosene_demand_bio_agriculture),
      Q(kerosene_demand_bio_buildings),
      Q(kerosene_demand_bio_industry),
      Q(kerosene_demand_bio_households)
    )
