- query =
    SUM(
      Q(supply_of_biomass_chp_for_electricity_network_mekko),
      Q(supply_of_biomass_power_for_electricity_network_mekko),
      Q(supply_of_power_shortage_for_electricity_network_mekko),
      Q(supply_of_coal_chp_for_electricity_network_mekko),
      Q(supply_of_coal_gas_chp_for_electricity_network_mekko),
      Q(supply_of_coal_gas_power_for_electricity_network_mekko),
      Q(supply_of_coal_power_for_electricity_network_mekko),
      Q(supply_of_gas_chp_for_electricity_network_mekko),
      Q(supply_of_gas_power_for_electricity_network_mekko),
      Q(supply_of_geothermal_power_for_electricity_network_mekko),
      Q(supply_of_hydro_for_electricity_network_mekko),
      Q(supply_of_hydrogen_power_for_electricity_network_mekko),
      Q(supply_of_import_for_electricity_network_mekko),
      Q(supply_of_lignite_chp_for_electricity_network_mekko),
      Q(supply_of_lignite_power_for_electricity_network_mekko),
      Q(supply_of_nuclear_power_for_electricity_network_mekko),
      Q(supply_of_oil_power_for_electricity_network_mekko),
      Q(supply_of_solar_csp_for_electricity_network_mekko),
      Q(supply_of_solar_pv_offshore_for_electricity_network_mekko),
      Q(supply_of_solar_pv_on_land_for_electricity_network_mekko),
      Q(supply_of_solar_pv_roof_for_electricity_network_mekko),
      Q(supply_of_waste_chp_for_electricity_network_mekko),
      Q(supply_of_waste_power_for_electricity_network_mekko),
      Q(supply_of_wind_offshore_for_electricity_network_mekko),
      Q(supply_of_wind_onshore_for_electricity_network_mekko),
      Q(supply_of_hydrogen_chp_for_electricity_network_mekko)
    )
- unit = PJ
