# This query functions both as the total demand and supply query.
# This is due to the fact that the local heat network for agriculture is based around the node agriculture_locally_available_steam_hot_water.
# All demand and supply is routed via this node.

- unit = MJ
- query =
    V(agriculture_locally_available_steam_hot_water, demand)
