- query = 
    SUM(
      Q(energy_heat_import_lt_steam_hot_water_for_heat_network_lt_mekko),
      Q(energy_heat_backup_burner_lt_network_gas_for_heat_network_lt_mekko),
      Q(residual_heat_in_lt_heat_network_for_heat_network_lt_mekko),
      Q(energy_heat_boiler_lt_electricity_for_heat_network_lt_mekko),
      Q(energy_heat_burner_lt_hydrogen_for_heat_network_lt_mekko),
      Q(energy_heat_heatpump_drink_water_water_ts_lt_electricity_for_heat_network_lt_mekko),
      Q(energy_heat_heatpump_surface_water_water_ts_lt_electricity_for_heat_network_lt_mekko),
      Q(energy_heat_heatpump_waste_water_water_ts_lt_electricity_for_heat_network_lt_mekko),
      Q(energy_heat_heatpump_water_water_lt_electricity_for_heat_network_lt_mekko),
      Q(energy_heat_solar_lt_solar_thermal_for_heat_network_lt_mekko),
      Q(energy_heat_well_shallow_lt_geothermal_for_heat_network_lt_mekko)
    )
- unit = PJ
