- unit = MJ
- query =
    SUM(
      Q(kerosene_demand_domestic_aviation),
      Q(bio_kerosene_demand_domestic_aviation),
      Q(kerosene_demand_international_aviation),
      Q(bio_kerosene_demand_international_aviation),
      Q(kerosene_demand_agriculture),
      Q(bio_kerosene_demand_agriculture),
      Q(kerosene_demand_buildings),
      Q(bio_kerosene_demand_buildings),
      Q(kerosene_demand_industry),
      Q(bio_kerosene_demand_industry),
      Q(kerosene_demand_households),
      Q(bio_kerosene_demand_households),
      Q(kerosene_demand_export),      
      Q(bio_kerosene_demand_export)
    )
