- query = 
    SUM(
      Q(co2_demand_export),
      Q(co2_demand_offshore_sequestration),
      Q(co2_demand_synthetic_kerosene),
      Q(co2_demand_synthetic_methanol),
      Q(co2_demand_other_utilisation_emitted),
      Q(co2_demand_other_utilisation_indefinitely)
    )
