- query =
    SUM(
      Q(demand_for_agriculture_final_demand_for_space_heating_for_electricity_network_mekko),
	    Q(demand_for_agriculture_final_demand_excl_space_heating_for_electricity_network_mekko),
      Q(demand_for_buildings_final_demand_excl_space_heating_for_electricity_network_mekko),
      Q(demand_for_buildings_final_demand_for_space_heating_for_electricity_network_mekko),
      Q(demand_for_energy_final_demand_for_electricity_network_mekko),
      Q(demand_for_households_final_demand_excl_space_heating_and_hot_water_for_electricity_network_mekko),
      Q(demand_for_households_final_demand_for_space_heating_and_hot_water_electricity_network_mekko),
      Q(demand_for_industry_final_demand_excl_ict_for_electricity_network_mekko),
      Q(demand_for_industry_final_demand_ict_for_electricity_network_mekko),
      Q(demand_for_international_transport_final_demand_for_electricity_network_mekko),
      Q(demand_for_national_transport_final_demand_for_electricity_network_mekko),
      Q(demand_for_other_final_demand_for_electricity_network_mekko),
      Q(demand_for_feedstock_final_demand_for_electricity_network_mekko),
      Q(demand_for_central_heating_for_electricity_network_mekko),
      Q(demand_for_curtailment_for_electricity_network_mekko),
      Q(demand_for_distribution_losses_for_electricity_network_mekko),
      Q(demand_for_electrolysis_for_electricity_network_mekko),
      Q(demand_for_export_for_electricity_network_mekko),
      Q(demand_for_industry_transformation_for_electricity_network_mekko),
      Q(demand_for_network_gas_compression_for_electricity_network_mekko),
      Q(demand_for_storage_losses_for_electricity_network_mekko),
      Q(demand_for_synthetic_fuel_production_for_electricity_network_mekko)
    )
- unit = PJ
