- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            ALL(),
             "network_gas && (network_gas.type == :producer || network_gas.type == :transformation || network_gas.type == :import)"
             ),
           "output_of_natural_gas + output_of_greengas"
        )
      ),
      BILLIONS
    )
- unit = PJ
