- unit = Mt
- query =
    SUM(
      Q(co2_supply_direct_air_capture),
      Q(co2_supply_energy_hydrogen),
      Q(co2_supply_energy_power),
      Q(co2_supply_import_backup),
      Q(co2_supply_import_baseload),
      Q(co2_supply_industry_fertilizers),
      Q(co2_supply_industry_food),
      Q(co2_supply_industry_paper),
      Q(co2_supply_industry_steel),
      Q(co2_supply_industry_refineries),
      Q(co2_supply_industry_chemical_other),
      Q(co2_supply_industry_external_coupling),
      Q(co2_supply_energy_fischer_tropsch),
      Q(co2_supply_energy_methanol_synthesis)
    )
