- unit = MJ
- query =
    SUM(
      Q(kerosene_supply_fischer_tropsch_synthetic_dispatchable),
      Q(kerosene_supply_fischer_tropsch_synthetic_must_run),
      Q(kerosene_supply_fischer_tropsch_non_biogenic_waste_ccs),
      Q(bio_kerosene_supply_fischer_tropsch_biogenic_waste_ccs),
      Q(bio_kerosene_supply_fischer_tropsch_dry_biomass_ccs),
      Q(bio_kerosene_supply_hvo),
      Q(bio_kerosene_supply_import),
      Q(bio_kerosene_supply_transformation),
      Q(kerosene_supply_refineries),
      Q(kerosene_supply_transformation),
      Q(kerosene_supply_import)
    )
