- query = 
    SUM(
      Q(final_demand_of_ht_heat_in_households_for_heat_network_ht_mekko),
      Q(final_demand_of_ht_heat_in_buildings_for_heat_network_ht_mekko),
      Q(final_demand_of_ht_heat_in_agriculture_for_heat_network_ht_mekko),
      Q(final_demand_of_ht_heat_in_energy_for_heat_network_ht_mekko),
      Q(final_demand_of_ht_heat_in_other_for_heat_network_ht_mekko),
      Q(losses_in_heat_network_ht_distribution_for_heat_network_ht_mekko),
      Q(losses_in_heat_network_ht_storage_for_heat_network_ht_mekko),
      Q(unused_heat_in_heat_network_ht_for_heat_network_ht_mekko)
    )
