- query = 
    SUM(
      Q(energy_heat_import_ht_steam_hot_water_for_heat_network_ht_mekko),
      Q(energy_heat_backup_burner_ht_network_gas_for_heat_network_ht_mekko),
      Q(residual_heat_in_heat_network_ht_for_heat_network_ht_mekko),
      Q(energy_chp_combined_cycle_ht_network_gas_for_heat_network_ht_mekko),
      Q(energy_chp_local_engine_ht_network_gas_for_heat_network_ht_mekko),
      Q(energy_chp_local_ht_wood_pellets_ccs_must_run_for_heat_network_ht_mekko),
      Q(energy_chp_local_ht_wood_pellets_ccs_dispatchable_for_heat_network_ht_mekko),
      Q(energy_chp_local_ht_wood_pellets_must_run_for_heat_network_ht_mekko),
      Q(energy_chp_local_ht_wood_pellets_dispatchable_for_heat_network_ht_mekko),
      Q(energy_chp_supercritical_ccs_ht_waste_mix_for_heat_network_ht_mekko),
      Q(energy_chp_supercritical_ht_waste_mix_for_heat_network_ht_mekko),
      Q(energy_chp_ultra_supercritical_cofiring_ht_coal_for_heat_network_ht_mekko),
      Q(energy_chp_ultra_supercritical_ht_coal_for_heat_network_ht_mekko),
      Q(energy_chp_ultra_supercritical_ht_lignite_for_heat_network_ht_mekko),
      Q(energy_heat_boiler_ht_electricity_for_heat_network_ht_mekko),
      Q(energy_heat_burner_ht_coal_for_heat_network_ht_mekko),
      Q(energy_heat_burner_ht_crude_oil_for_heat_network_ht_mekko),
      Q(energy_heat_burner_ht_hydrogen_for_heat_network_ht_mekko),
      Q(energy_heat_burner_ht_network_gas_for_heat_network_ht_mekko),
      Q(energy_heat_burner_ht_waste_mix_for_heat_network_ht_mekko),
      Q(energy_heat_burner_ht_wood_pellets_for_heat_network_ht_mekko),
      Q(energy_heat_flexibility_p2h_boiler_ht_electricity_for_heat_network_ht_mekko),
      Q(energy_heat_flexibility_p2h_heatpump_ht_electricity_for_heat_network_ht_mekko),
      Q(energy_heat_solar_ht_solar_thermal_for_heat_network_ht_mekko),
      Q(energy_heat_well_deep_ht_geothermal_for_heat_network_ht_mekko),
      Q(energy_chp_local_engine_ht_biogas_for_heat_network_ht_mekko),
      Q(energy_heat_heatpump_water_water_ht_electricity_for_heat_network_ht_mekko)
    )
