- query =
    DIVIDE(
      SUM(
        V(
          Q(time_resolved_network_gas_production_converters),
           "output_of_natural_gas + output_of_greengas + output_of_propane"
        )
      ),
      BILLIONS
    )
- unit = PJ
