# This query functions both as the total demand and supply query. 
# This is due to the fact that the ammonia mekko is based around the node energy_distribution_ammonia.
# All demand and supply is routed via this node.
- query = 
    V(energy_distribution_ammonia, demand)

