- query = 
    SUM(
      Q(demand_for_agriculture_final_demand_for_network_gas_mekko),
      Q(demand_for_bio_ethanol_for_network_gas_mekko),
      Q(demand_for_hvo_biokerosene_for_network_gas_mekko),
      Q(demand_for_buildings_final_demand_for_space_heating_for_network_gas_mekko),
      Q(demand_for_buildings_final_demand_excl_space_heating_for_network_gas_mekko),
      Q(demand_for_households_final_demand_for_space_heating_and_hot_water_network_gas_mekko),
      Q(demand_for_households_final_demand_excl_space_heating_and_hot_water_for_network_gas_mekko),
      Q(demand_for_industry_final_demand_for_network_gas_mekko),
      Q(demand_for_international_transport_final_demand_for_network_gas_mekko),
      Q(demand_for_national_transport_final_demand_for_network_gas_mekko),
      Q(demand_for_energy_final_demand_for_network_gas_mekko),
      Q(demand_for_other_final_demand_for_network_gas_mekko),
      Q(demand_for_feedstock_final_demand_for_network_gas_mekko),
      Q(demand_for_power_plants_for_network_gas_mekko),
      Q(demand_for_central_heating_for_network_gas_mekko),
      Q(demand_for_hydrogen_production_for_network_gas_mekko),
      Q(demand_for_industry_transformation_demand_for_network_gas_mekko),
      Q(demand_for_biomass_torrefaction_for_network_gas_mekko),
      Q(demand_for_greengas_export_network_gas_mekko),
      Q(demand_for_natural_gas_export_for_network_gas_mekko),
      Q(demand_for_distribution_losses_for_network_gas_mekko)
    )
- unit = PJ
