- unit = MJ
- query =
    SUM(
      Q(energy_chp_coal_gas_in_industrial_heat_network_mekko),
      Q(industry_chp_combined_cycle_gas_power_fuelmix_in_industrial_heat_network_mekko),
      Q(industry_chp_engine_gas_power_fuelmix_in_industrial_heat_network_mekko),
      Q(industry_chp_turbine_gas_power_fuelmix_in_industrial_heat_network_mekko),
      Q(industry_chp_ultra_supercritical_coal_in_industrial_heat_network_mekko),
      Q(industry_chp_wood_pellets_in_industrial_heat_network_mekko),
      Q(industry_chp_turbine_hydrogen_in_industrial_heat_network_mekko),
      Q(industry_heat_backup_burner_network_gas_in_industrial_heat_network_mekko),
      Q(industry_heat_burner_coal_in_industrial_heat_network_mekko),
      Q(industry_heat_burner_crude_oil_in_industrial_heat_network_mekko),
      Q(industry_heat_burner_lignite_in_industrial_heat_network_mekko),
      Q(industry_heat_well_geothermal_in_industrial_heat_network_mekko),
      Q(industry_heat_burner_hydrogen_in_industrial_heat_network_mekko)
    )
