- query =
    DIVIDE(
      SUM(
        Q(factsheet_supply_heat_from_rest_and_geothermal),
        - SUM(
            V(
            buildings_collective_geothermal,
            households_collective_geothermal,
            energy_heater_for_heat_network_geothermal,
            output_of_steam_hot_water
            ),
            V(agriculture_geothermal, output_of_useable_heat)
        )
      ),
      Q(factsheet_supply_heat_collective)
    ) * 100

- unit = %
