# CO2 from point sources needed for synthetic kerosene production
# Molar mass CO = 28 g/mol and CO2 = 44 g/mol

- unit = MT
- query =
    DIVIDE(
        DIVIDE(
            V(bunkers_p2l_point_source_CO2, demand),
            V(CARRIER(co), "mj_per_kg")
        ),
        (28/44) * BILLIONS
    )
