# CO2 from point sources needed for synthetic kerosene production

- unit = MT
- query =
    DIVIDE(
        DIVIDE(
            V(bunkers_p2l_point_source_CO, output_of_co),
            V(CARRIER(co), "mj_per_kg")
        ),
        BILLIONS
    )
