# Sums the final demand of lpg for all sectors

- unit = MJ
- query =
  SUM(
    V(agriculture_final_demand_lpg, input_of_lpg),
    V(buildings_final_demand_lpg, input_of_lpg),
    V(industry_final_demand_lpg, input_of_lpg),
    V(households_final_demand_lpg, input_of_lpg),
    V(transport_final_demand_lpg, input_of_lpg)
  )
