# Sums the final demand of kerosene for all sectors

- unit = MJ
- query =
  SUM(
    V(agriculture_final_demand_kerosene, input_of_kerosene),
    V(buildings_final_demand_kerosene, input_of_kerosene),
    V(industry_final_demand_kerosene, input_of_kerosene),
    V(households_final_demand_kerosene, input_of_kerosene),
    V(transport_final_demand_kerosene, input_of_kerosene),
    V(bunkers_final_demand_kerosene, input_of_kerosene)
  )
