# Final demand for all oil non-energetic in industry

- unit = MJ
- query =
    SUM(
      V(
        industry_final_demand_crude_oil_non_energetic,
        industry_final_demand_naphtha_non_energetic,
        demand
      )
    )
