# Final demand for all oil in industry

- unit = MJ
- query =
  SUM(
    V(industry_final_demand_crude_oil, output_of_crude_oil),
    V(industry_final_demand_crude_oil_non_energetic, output_of_crude_oil)
  )
