- query =
    SUM(
      NEG(Q(turk_sankey_conversion_coal_input)),
      NEG(Q(turk_sankey_final_demand_coal_input)),
      Q(turk_sankey_primary_demand_coal_output),
      NEG(Q(turk_sankey_loss_coal_to_coal))
    )
- unit = PJ