- query =
    SUM(
      NEG(Q(turk_sankey_conversion_liquid_hydrogen_input)),
      Q(turk_sankey_conversion_liquid_hydrogen_output),
      NEG(Q(turk_sankey_final_demand_liquid_hydrogen_input)),
      Q(turk_sankey_primary_demand_liquid_hydrogen_output)
    )
- unit = PJ