- query =
    SUM(
      NEG(Q(turk_sankey_conversion_hydrogen_input)),
      Q(turk_sankey_conversion_hydrogen_output),
      NEG(Q(turk_sankey_final_demand_hydrogen_input)),
      Q(turk_sankey_primary_demand_hydrogen_output),
      NEG(Q(conversion_loss_hydrogen_to_hydrogen))
    )
- unit = PJ

