- query =
    SUM(
      NEG(Q(turk_sankey_conversion_solar_thermal_input)),
      NEG(Q(turk_sankey_final_demand_solar_thermal_input)),
      Q(turk_sankey_primary_demand_solar_thermal_output)
    )
- unit = PJ