- query =
    SUM(
      NEG(Q(turk_sankey_conversion_geothermal_input)),
      NEG(Q(turk_sankey_final_demand_geothermal_input)),
      Q(turk_sankey_primary_demand_geothermal_output)
    )
- unit = PJ