- query =
    SUM(
      Q(turk_sankey_conversion_steam_hot_water_output),
      NEG(Q(turk_sankey_final_demand_steam_hot_water_input)),
      Q(turk_sankey_primary_demand_steam_hot_water_output),
      NEG(Q(turk_sankey_loss_steam_hot_water_to_steam_hot_water))
    )
- unit = PJ