- query =
    SUM(
      NEG(Q(turk_sankey_conversion_biomass_input)),
      Q(turk_sankey_conversion_biomass_output),
      NEG(Q(turk_sankey_final_demand_biomass_input)),
      Q(turk_sankey_primary_demand_biomass_output),
      NEG(Q(turk_sankey_loss_biomass_to_biomass))
    )
- unit = PJ