- query =
    SUM(
      NEG(Q(turk_sankey_conversion_natural_gas_input)),
      Q(turk_sankey_conversion_natural_gas_output),
      NEG(Q(turk_sankey_final_demand_natural_gas_input)),
      Q(turk_sankey_primary_demand_natural_gas_output),
      NEG(Q(conversion_loss_natural_gas_to_natural_gas))
    )
- unit = PJ