- query =
    SUM(
      NEG(Q(turk_sankey_conversion_electricity_input)),
      Q(turk_sankey_conversion_electricity_output),
      NEG(Q(turk_sankey_final_demand_electricity_input)),
      Q(turk_sankey_primary_demand_electricity_output),
      NEG(Q(conversion_loss_electricity_to_electricity))
    )
- unit = PJ

