- query =
    SUM(
      NEG(Q(turk_sankey_conversion_oil_input)),
      Q(turk_sankey_conversion_oil_output),
      NEG(Q(turk_sankey_final_demand_oil_input)),
      Q(turk_sankey_primary_demand_oil_output),
      NEG(Q(conversion_loss_oil_and_derivatives_to_oil_and_derivatives))
    )
- unit = PJ

