#


- unit = EUR

future:
DIVIDE(
    SUM(V(energy_power_wind_turbine_inland, energy_power_wind_turbine_coastal, energy_power_wind_turbine_offshore," variable_costs_per_mwh_input/electricity_output_conversion*installed_production_capacity_in_mw_electricity")),
    SUM(V(energy_power_wind_turbine_inland, energy_power_wind_turbine_coastal, energy_power_wind_turbine_offshore, installed_production_capacity_in_mw_electricity))
)
