# This determines the amount of heat from gas, minus which is produced with greengas

- unit = mj

SUM(
     V(gas_burner_industry_industry_energetic;output_of_heat_carriers),
     NEG(
             V(gas_burner_industry_industry_energetic;
                     output_of_heat_carriers * sustainability_share)
)
)