# 

- unit = pj

SUM(Q(industry_biomass_primary_demand),
Q(industry_oil_primary_demand),
Q(industry_uranium_primary_demand),
Q(industry_coal_primary_demand),
Q(industry_lignite_primary_demand),
Q(industry_waste_primary_demand),
Q(all_biofuels_industry_primary),
Q(industry_non_e_primary_demand),
Q(all_biofuels_energy_primary),
Q(industry_imported_e_primary_demand)
)