# Final consumption of geothermal in industry ex. ict and refineries - fertilizers (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     Geothermal -- geothermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_geothermal_in_industry_fertilizers_energetic)
