# Total heat produced in heat networks from biomass

- unit = PJ
- query =
    SUM(
        Q(heat_production_from_renewables_for_heat_networks),
        NEG(Q(heat_production_from_geothermal_and_ambient_for_heat_networks))
    )
