# Final consumption of natural gas and gas products, all sectors (energetic use only).
#
# Sector:      All sectors
# Carrier:     Natural gas and gas products
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of natural gas and gas products in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_natural_gas_and_gas_products_energetic)
