# This query calculates the required additional HV network as percentage of the current installed_production_capacity_in_mw_electricity
# < 100% means no additional capacity
# > 100% means additional capacity required

- query = 
    DIVIDE(
        Q(hv_net_capacity_future),
        Q(hv_net_capacity_present)
    ) * 100.0
- unit = %