# This query calculates the required additional HV network as percentage of the current installed_production_capacity_in_mw_electricity
# < 100% means no additional capacity
# > 100% means additional capacity required

- query = 
    AVG(
        Q(kpi_required_additional_hv_network_percentage),
        Q(kpi_required_additional_mv_network_percentage)
    )
- unit = %