# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(agriculture_chp_engine_biogas, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(agriculture_chp_biogas_revenue_in_power_plant_economic_performance_table) -  Q(agriculture_chp_biogas_capex_in_power_plant_economic_performance_table)  -  Q(agriculture_chp_biogas_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
