# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
    Q(battery_solar_pv_revenue_in_power_plant_economic_performance_table)
    - Q(battery_solar_pv_capex_in_power_plant_economic_performance_table)
    - Q(battery_solar_pv_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
