- query =
    Q(battery_wind_inland_revenue_in_power_plant_economic_performance_table)
    - Q(battery_wind_inland_capex_in_power_plant_economic_performance_table)
    - Q(battery_wind_inland_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
