# CAPEX of power plant, based on annual CAPEX calculations

- query =
   IF(
       V(energy_chp_local_engine_ht_biogas, output_of_electricity) == 0,
       -> { '-' },
       -> { V(energy_chp_local_engine_ht_biogas, capital_expenditures_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
