- query =
    Q(biogas_chp_mt_revenue_in_power_plant_economic_performance_table)
    - Q(biogas_chp_mt_capex_in_power_plant_economic_performance_table)
    - Q(biogas_chp_mt_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
