# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(buildings_solar_pv_solar_radiation, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(buildings_solar_pv_solar_radiation_revenue_in_power_plant_economic_performance_table) -  Q(buildings_solar_pv_solar_radiation_capex_in_power_plant_economic_performance_table)  -  Q(buildings_solar_pv_solar_radiation_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
