- query =
    Q(coal_pwd_revenue_in_power_plant_economic_performance_table)
    - Q(coal_pwd_capex_in_power_plant_economic_performance_table)
    - Q(coal_pwd_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
