# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(energy_chp_coal_gas, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(coal_gas_chp_revenue_in_power_plant_economic_performance_table) -  Q(coal_gas_chp_capex_in_power_plant_economic_performance_table)  -  Q(coal_gas_chp_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
