# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(energy_chp_ultra_supercritical_cofiring_mt_coal, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(coal_chp_pwd_cofiring_mt_revenue_in_power_plant_economic_performance_table) -  Q(coal_chp_pwd_cofiring_mt_capex_in_power_plant_economic_performance_table)  -  Q(coal_chp_pwd_cofiring_mt_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
