- query =
    Q(coal_igcc_revenue_in_power_plant_economic_performance_table)
    - Q(coal_igcc_capex_in_power_plant_economic_performance_table)
    - Q(coal_igcc_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
