# Revenue of power plant, based on hourly revenue calculations

- query =
   IF(
       V(energy_power_solar_pv_offshore, output_of_electricity) == 0,
       -> { '-' },
       -> { V(energy_power_solar_pv_offshore, revenue_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
