- query =
    Q(energy_power_solar_pv_offshore_revenue_in_power_plant_economic_performance_table)
    - Q(energy_power_solar_pv_offshore_capex_in_power_plant_economic_performance_table)
    - Q(energy_power_solar_pv_offshore_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
