- query =
    Q(energy_power_solar_pv_solar_radiation_revenue_in_power_plant_economic_performance_table)
    - Q(energy_power_solar_pv_solar_radiation_capex_in_power_plant_economic_performance_table)
    - Q(energy_power_solar_pv_solar_radiation_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
