# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
    Q(gas_ccgt_ccs_revenue_in_power_plant_economic_performance_table)
    - Q(gas_ccgt_ccs_capex_in_power_plant_economic_performance_table)
    - Q(gas_ccgt_ccs_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
