# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
    Q(hydrogen_ccgt_revenue_in_power_plant_economic_performance_table)
    - Q(hydrogen_ccgt_capex_in_power_plant_economic_performance_table)
    - Q(hydrogen_ccgt_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
