# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(energy_power_hydro_river, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(hydro_river_revenue_in_power_plant_economic_performance_table) -  Q(hydro_river_capex_in_power_plant_economic_performance_table)  -  Q(hydro_river_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
