- query =
    Q(hydro_mountain_revenue_in_power_plant_economic_performance_table)
    - Q(hydro_mountain_capex_in_power_plant_economic_performance_table)
    - Q(hydro_mountain_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
