- query =
    Q(industry_chp_coal_revenue_in_power_plant_economic_performance_table)
    - Q(industry_chp_coal_capex_in_power_plant_economic_performance_table)
    - Q(industry_chp_coal_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
