# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(industry_chp_turbine_hydrogen, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(industry_chp_hydrogen_turbine_revenue_in_power_plant_economic_performance_table) -  Q(industry_chp_hydrogen_turbine_capex_in_power_plant_economic_performance_table)  -  Q(industry_chp_hydrogen_turbine_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
