# Revenue of power plant, based on hourly revenue calculations

- query =
   IF(
       V(industry_chp_turbine_gas_power_fuelmix, output_of_electricity) == 0,
       -> { '-' },
       -> { V(industry_chp_turbine_gas_power_fuelmix, revenue_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
