# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(industry_chp_turbine_gas_power_fuelmix, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(industry_chp_gas_turbine_revenue_in_power_plant_economic_performance_table) -  Q(industry_chp_gas_turbine_capex_in_power_plant_economic_performance_table)  -  Q(industry_chp_gas_turbine_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
