- query =
    Q(industry_chp_gas_ccgt_revenue_in_power_plant_economic_performance_table)
    - Q(industry_chp_gas_ccgt_capex_in_power_plant_economic_performance_table)
    - Q(industry_chp_gas_ccgt_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
