- query =
    Q(industry_chp_wood_revenue_in_power_plant_economic_performance_table)
    - Q(industry_chp_wood_capex_in_power_plant_economic_performance_table)
    - Q(industry_chp_wood_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
