# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(industry_chp_engine_gas_power_fuelmix, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(industry_chp_gas_engine_revenue_in_power_plant_economic_performance_table) -  Q(industry_chp_gas_engine_capex_in_power_plant_economic_performance_table)  -  Q(industry_chp_gas_engine_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
