# Revenue of power plant, based on hourly revenue calculations

- query =
   IF(
       V(energy_chp_ultra_supercritical_ht_lignite, output_of_electricity) == 0,
       -> { '-' },
       -> { V(energy_chp_ultra_supercritical_ht_lignite, revenue_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
