# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(energy_chp_ultra_supercritical_ht_lignite, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(lignite_chp_ht_revenue_in_power_plant_economic_performance_table) -  Q(lignite_chp_ht_capex_in_power_plant_economic_performance_table)  -  Q(lignite_chp_ht_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
