# OPEX of power plant, based on annual OPEX calculations

- query =
   IF(
       V(energy_chp_ultra_supercritical_mt_lignite, output_of_electricity) == 0,
       -> { '-' },
       -> { V(energy_chp_ultra_supercritical_mt_lignite, operating_expenses_including_fuel_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
