# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
    Q(lignite_chp_mt_revenue_in_power_plant_economic_performance_table)
    - Q(lignite_chp_mt_capex_in_power_plant_economic_performance_table)
    - Q(lignite_chp_mt_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
