# Revenue of power plant, based on hourly revenue calculations

- query =
   IF(
       V(energy_power_nuclear_small_modular_reactor_uranium_oxide, output_of_electricity) == 0,
       -> { '-' },
       -> { V(energy_power_nuclear_small_modular_reactor_uranium_oxide, revenue_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
