- query =
    Q(nuclear_ii_revenue_in_power_plant_economic_performance_table)
    - Q(nuclear_ii_capex_in_power_plant_economic_performance_table)
    - Q(nuclear_ii_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
