# OPEX of power plant, based on annual OPEX calculations

- query =
   IF(
       V(energy_power_nuclear_gen3_uranium_oxide, output_of_electricity) == 0,
       -> { '-' },
       -> { V(energy_power_nuclear_gen3_uranium_oxide, operating_expenses_including_fuel_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
