# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(energy_power_nuclear_small_modular_reactor_uranium_oxide, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(nuclear_smr_revenue_in_power_plant_economic_performance_table) -  Q(nuclear_smr_capex_in_power_plant_economic_performance_table)  -  Q(nuclear_smr_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
