- query =
    Q(nuclear_smr_revenue_in_power_plant_economic_performance_table)
    - Q(nuclear_smr_capex_in_power_plant_economic_performance_table)
    - Q(nuclear_smr_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
