# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
    Q(nuclear_iii_revenue_in_power_plant_economic_performance_table)
    - Q(nuclear_iii_capex_in_power_plant_economic_performance_table)
    - Q(nuclear_iii_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
