# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
    Q(oil_plant_revenue_in_power_plant_economic_performance_table)
    - Q(oil_plant_capex_in_power_plant_economic_performance_table)
    - Q(oil_plant_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
