# Revenue of power plant, based on hourly revenue calculations

- query =
   IF(
       V(energy_power_supercritical_ccs_waste_mix, output_of_electricity) == 0,
       -> { '-' },
       -> { V(energy_power_supercritical_ccs_waste_mix, revenue_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
