# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(energy_chp_supercritical_ccs_ht_waste_mix, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(waste_chp_ccs_ht_revenue_in_power_plant_economic_performance_table) -  Q(waste_chp_ccs_ht_capex_in_power_plant_economic_performance_table)  -  Q(waste_chp_ccs_ht_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
