# CAPEX of power plant, based on annual CAPEX calculations

- query =
   IF(
       V(energy_chp_supercritical_mt_waste_mix, output_of_electricity) == 0,
       -> { '-' },
       -> { V(energy_chp_supercritical_mt_waste_mix, capital_expenditures_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
