- query =
    Q(waste_chp_ccs_mt_revenue_in_power_plant_economic_performance_table)
    - Q(waste_chp_ccs_mt_capex_in_power_plant_economic_performance_table)
    - Q(waste_chp_ccs_mt_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
