- query =
    Q(waste_power_revenue_in_power_plant_economic_performance_table)
    - Q(waste_power_capex_in_power_plant_economic_performance_table)
    - Q(waste_power_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
