# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
    Q(wood_pellets_chp_ccs_mt_dispatchable_revenue_in_power_plant_economic_performance_table)
    - Q(wood_pellets_chp_ccs_mt_dispatchable_capex_in_power_plant_economic_performance_table)
    - Q(wood_pellets_chp_ccs_mt_dispatchable_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
