- query =
    Q(wood_pellets_chp_ccs_ht_must_run_revenue_in_power_plant_economic_performance_table)
    - Q(wood_pellets_chp_ccs_ht_must_run_capex_in_power_plant_economic_performance_table)
    - Q(wood_pellets_chp_ccs_ht_must_run_opex_in_power_plant_economic_performance_table)
- unit = EUR/MWh
