# CAPEX of power plant, based on annual CAPEX calculations

- query =
   IF(
       V(energy_power_wood_pellets_dispatchable, output_of_electricity) == 0,
       -> { '-' },
       -> { V(energy_power_wood_pellets_dispatchable, capital_expenditures_per(:mwh_electricity)) }
   )
- unit = EUR/MWh
