# Profit of power plant, defined as revenue minus CAPEX and OPEX

- query =
  IF(
       V(energy_chp_local_ht_wood_pellets_dispatchable, output_of_electricity) == 0,
       -> { '-' },
       -> { Q(wood_pellets_chp_ht_dispatchable_revenue_in_power_plant_economic_performance_table) -  Q(wood_pellets_chp_ht_dispatchable_capex_in_power_plant_economic_performance_table)  -  Q(wood_pellets_chp_ht_dispatchable_opex_in_power_plant_economic_performance_table) } 
  )
- unit = EUR/MWh
