- unit = curve
- query = 
    SUM_CURVES(
      Q(industry_transformation_chemical_feritilizers_hydrogen_output_curve),
      Q(industry_transformation_chemical_other_hydrogen_output_curve),
      Q(industry_transformation_chemical_refineries_hydrogen_output_curve)
    )

