- query =
  DIVIDE(
    SUM(
      V(agriculture_chp_engine_biogas, capital_expenditures_excluding_ccs_per(:mw_electricity)),
      V(agriculture_chp_engine_biogas, operating_expenses_excluding_ccs_per(:mw_electricity))
    ),
    1000
  )
- unit = euro
