- query =
  DIVIDE(
    SUM(
      V(energy_flexibility_mv_batteries_electricity, capital_expenditures_excluding_ccs_per(:plant)),
      V(energy_flexibility_mv_batteries_electricity, operating_expenses_excluding_ccs_per(:plant))
    ),
    V(energy_flexibility_mv_batteries_electricity, "storage.volume")
  )
- unit = euro
