- query =
    DIVIDE(
      SUM(
        V(households_space_heater_combined_network_gas, capital_expenditures_excluding_ccs_per(:node)),
        V(households_space_heater_combined_network_gas, operating_expenses_excluding_ccs_per(:node))
      ),
      V(households_space_heater_combined_network_gas, "heat_output_capacity * number_of_units") * 1000
    )
- unit = euro
