- query =
  DIVIDE(
    SUM(
      V(energy_heat_heatpump_water_water_electricity, capital_expenditures_excluding_ccs_per(:mw_heat)),
      V(energy_heat_heatpump_water_water_electricity, operating_expenses_excluding_ccs_per(:mw_heat))
    ),
    1000
  )
- unit = euro
