- query =
    DIVIDE(
      SUM(
        V(energy_power_wind_turbine_inland, capital_expenditures_excluding_ccs_per(:mw_electricity)),
        V(energy_power_wind_turbine_inland, operating_expenses_excluding_ccs_per(:mw_electricity))
      ),
      1000
    )
- unit = euro
