- query =
    DIVIDE(
      SUM(
        V(households_space_heater_hybrid_heatpump_air_water_electricity, capital_expenditures_excluding_ccs_per(:mw_heat)),
        V(households_space_heater_hybrid_heatpump_air_water_electricity, operating_expenses_excluding_ccs_per(:mw_heat))
      ),
      1000
    )
- unit = euro
