- query =
  DIVIDE(
    SUM(
      V(energy_power_wind_turbine_inland, capital_expenditures_excluding_ccs_per(:node)),
      V(energy_power_wind_turbine_inland, operating_expenses_excluding_ccs_per(:node))
    ),
    V(energy_power_wind_turbine_inland, installed_production_capacity_in_mw_electricity) * 1000
  )
- unit = euro
