- query =
    DIVIDE(
      SUM(
        V(households_solar_pv_solar_radiation, capital_expenditures_excluding_ccs_per(:mw_electricity)),
        V(households_solar_pv_solar_radiation, operating_expenses_excluding_ccs_per(:mw_electricity))
      ),
      1000
    )
- unit = euro
