- query =
    DIVIDE(
      SUM(
        V(industry_other_paper_burner_network_gas, capital_expenditures_excluding_ccs_per(:mw_heat)),
        V(industry_other_paper_burner_network_gas, operating_expenses_excluding_ccs_per(:mw_heat))
      ),
      1000
    )
- unit = euro
