# Assuming linear depreciation, in line with ETM cost calculation

- query =
    PRODUCT(
      DIVIDE(
        Q(heat_infrastructure_lt_primary_pipelines_investment_costs),
        2.0),
      Q(heat_infrastructure_lt_primary_pipelines_wacc)
    )
- unit = euro
