### Heat loss per household HT
# Multiplies total loss of heat network with share of heat demand to households. Divided by number of units.

- query = V(energy_heat_distribution_ht_loss,demand)*V(households_final_demand_ht_steam_hot_water,demand)/V(energy_distribution_ht_steam_hot_water,demand)/V(households_space_heater_district_heating_ht_steam_hot_water,number_of_units)/THOUSANDS
- unit = GJ