# Max newly required capacity for the MV/LV transformers
# Compares the required capacity for 4 periods of the year

- unit = MW

MAX(
    Q(network_mv_lv_trafo_delta_peak_load_we),
    Q(network_mv_lv_trafo_delta_peak_load_wd),
    Q(network_mv_lv_trafo_delta_peak_load_se),
    Q(network_mv_lv_trafo_delta_peak_load_sd)
)
