# This Gquery calculates the additional peak load as a result of the electrical technologies that are installed in a scenario for a summer day
# This Gquery takes into account all technologies attached below MV/LV tranformer level (i.e. at the LV-network level)
# If the additional peak load in the future scenario is lower than in the present scenario, this Gquery returns 0.0

- query =
    MAX(
        QUERY_DELTA( -> {SUM(V(Q(network_lv_net_converters),"simult_sd*peak_load_in_mw")) })
                    *V(energy_power_lv_network_electricity,simult_sd)
        ,
        0.0
    )
- unit = MW
