#

- unit = MW

SUM(
    MAX(
        ABS(
            SUM(
                SUM(V(Q(network_lv_net_converters),"simult_wd*peak_load_in_mw"))
                        *V(energy_power_lv_network_electricity,simult_wd)
                ,
                V(energy_power_transformer_lv_mv_electricity, network_capacity_used_in_mw)
            )
        ),
        V(energy_power_transformer_lv_mv_electricity, network_capacity_available_in_mw)
    ),
    NEG(V(energy_power_transformer_lv_mv_electricity, network_capacity_available_in_mw))
)