# Required new MV/LV transformer capacity during a summer evening.
# Query takes into account all technologies attached below MV/LV tranformer level (i.e. at the LV-network level)
# Query sums the newly required capacities per technology (peak_laod_in_mw) and adds these to the currently used capacity on the network (network_capacity_used_in_mw)

- query =
    MAX(
        QUERY_DELTA( -> {SUM(V(Q(network_lv_net_converters),"simult_se*peak_load_in_mw")) })
                    *V(energy_power_lv_network_electricity,simult_se)
        ,
        0.0
    )
- unit = MW
