# Max newly required capacity for the MV/LV transformers
# Compares the required capacity for 4 periods of the year
# If the total required capacity DOES NOT exceeds the available capacity (network_capacity_available_in_mw), return 0
# If the total required capacity DOES exceed the available capacity return difference between required and available capacity

- query =
    SUM(
        MAX(
            Q(network_mv_lv_trafo_peak_load_we),
            Q(network_mv_lv_trafo_peak_load_wd),
            Q(network_mv_lv_trafo_peak_load_se),
            Q(network_mv_lv_trafo_peak_load_sd),
            V(energy_power_transformer_lv_mv_electricity, network_capacity_available_in_mw)
        ),
        NEG(V(energy_power_transformer_lv_mv_electricity, network_capacity_available_in_mw))
    )
- unit = MW
