# The amount of the heat from the central heat network which is used for households
# and produced by must-run sources

- query = 
    Q(households_heat_network_connection_steam_hot_water_in_heat_network_mekko) * Q(etmoses_must_run_fraction_of_heat_from_central_heat_network) * BILLIONS
    
- unit = MJ
