# Returns average O&M cost [EUR/MWh/year] of must_run sources in the central heat network

- query =
    V(
        Q(etmoses_average_fixed_operation_and_maintenance_cost_of_must_run_central_heat_network) / 
        Q(etmoses_heat_produced_by_must_run_central_heat_network)

- unit = EUR
