# Returns average marginal cost [EUR/Mwh] of must_run sources in the central heat network
# Weighted by installed capacity of the sources
# marginal cost for heat = variable_costs_per_typical_input * SECS_PER_HOUR / heat_output_conversion 
# produced_heat = output_of_steam_hot_water

- query =
    V(
        Q(etmoses_must_run_sources_central_heat_network), "variable_costs_per_typical_input * SECS_PER_HOUR / heat_output_conversion * output_of_steam_hot_water"
    ).sum / Q(etmoses_must_run_heat_from_central_heat_network)

- unit = EUR
