# The fraction of the heat from the central heat network which is used for buildings and households

- query = 
    Q(etmoses_buildings_fraction_of_central_heat_network) + Q(etmoses_households_fraction_of_central_heat_network)
    
- unit = factor