# Returns total demand for space heating to be assigned to buffers when
# importing a scenario into ETMoses.

- query =
    SUM(V(
      INTERSECTION(G(etmoses),G(merit_household_space_heating_producers)),
      output_of_useable_heat
    )) / BILLIONS

- unit = PJ
