# Returns total installed capacity of dispatchable sources in the central heat network
- query =
    V(
        Q(etmoses_dispatchable_sources_central_heat_network), "number_of_units * heat_output_capacity"
    ).sum

- unit = MW
