# The amount of the installed capacity from the central heat network which is used for households and buildings
# and produced by must-run sources

- query = 
    Q(etmoses_installed_capacity_of_dispatchable_central_heat_network) * Q(etmoses_buildings_and_households_fraction_of_central_heat_network)
    
- unit = MJ