# The must-run sources for the central heat network (heat is a by-product)

- query = 
    V(
        energy_chp_ultra_supercritical_lignite,
        energy_chp_combined_cycle_network_gas,
        energy_power_supercritical_waste_mix,
        energy_chp_ultra_supercritical_cofiring_coal,
        energy_chp_ultra_supercritical_coal,
        agriculture_unused_local_production_steam_hot_water,
        industry_unused_local_production_steam_hot_water,
        energy_chp_supercritical_waste_mix
    )
- unit = converters