# The fraction of the heat from the central heat network which is produced by must-run sources
# The quotient works because these sources provide heat exclusively to the heat network

- query = 
    V(Q(etmoses_must_run_sources_central_heat_network), output_of_steam_hot_water).sum / V(energy_heat_network_steam_hot_water, demand)

- unit = factor