# Returns total investment cost [EUR] of must-run sources in the central heat network

- query =
    V(
        Q(etmoses_must_run_sources_central_heat_network), "initial_investment"
    ).sum

- unit = EUR
