# The dispatchable sources for the central heat network

- query = 
    V(
        energy_heater_for_heat_network_crude_oil,
        energy_heater_for_heat_network_geothermal,
        energy_heater_for_heat_network_lignite,
        energy_heater_for_heat_network_wood_pellets,
        energy_heat_network_backup_heater_network_gas,
        energy_heater_for_heat_network_network_gas,
        energy_heater_for_heat_network_coal,
        energy_heater_for_heat_network_waste_mix
    )
- unit = converters