# Returns total heat provided from non-dispatchable sources in the central heat network
- query =
    V(
        Q(etmoses_must_run_sources_central_heat_network), output_of_steam_hot_water
    ).sum

- unit = MJ
