# Returns average O&M cost [EUR/MW/year] of dispatchable sources in the central heat network

- query =
    V(
        Q(etmoses_average_fixed_operation_and_maintenance_cost_of_dispatchable_central_heat_network) / 
        Q(etmoses_installed_capacity_of_dispatchable_central_heat_network)

- unit = EUR
