# Returns total demand for space heating to be assigned to buffers when
# importing a scenario into ETMoses.

- query =
    V(
      households_useful_demand_for_space_heating_after_insulation,
      demand
    ) / BILLIONS
- unit = PJ
