# Returns total investment cost [EUR] of dispatchable sources in the central heat network

- query =
    V(
        Q(etmoses_dispatchable_sources_central_heat_network), "initial_investment"
    ).sum / Q(etmoses_installed_capacity_of_dispatchable_central_heat_network)

- unit = EUR
