# Returns total demand for hot water to be assigned to buffers when importing a
# scenario into ETMoses.

- query = 
    (V(households_useful_demand_for_hot_water_after_solar_heater, demand) -
    V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_p2h)), output_of_useable_heat).sum +
    V(INTERSECTION(G(etmoses),CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_p2h))), output_of_useable_heat).sum) / BILLIONS

- unit = PJ
