# Returns the investment cost [EUR] of dispatchable sources in the central heat network
# which can be attributed to the household sector based on the fraction of the total heat which
# households take from the central heat network

- query =
    Q(etmoses_households_fraction_of_central_heat_network) * Q(etmoses_total_investment_cost_of_dispatchable_central_heat_network)

- unit = EUR
