# Final consumption of ammonia in national transport (energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Ammonia -- ammonia?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_national_transport_energetic)
