# Final consumption of ammonia in households (energetic use only).
#
# Sector:      Households -- sector == :households
# Carrier:     Ammonia -- ammonia?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_households_energetic)
