# Final consumption of ammonia in industry ex. ict and refineries - aluminium (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Aluminium -- EG(aluminium_industry)
# Carrier:     Ammonia -- ammonia?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_industry_aluminium_energetic)
