- query = 
		SUM(
			Q(wet_biomass_to_biogas_in_biomass_sankey),
			Q(wet_biomass_to_greengas_in_biomass_sankey),
			Q(wet_biomass_to_biofuels_in_biomass_sankey),
			Q(wet_biomass_to_export_in_biomass_sankey)
		)