- query = 
		SUM(
			Q(dry_biomass_to_greengas_in_biomass_sankey),
			Q(dry_biomass_to_electricity_prod_in_biomass_sankey),
			Q(dry_biomass_to_central_heat_prod_in_biomass_sankey),
			Q(dry_biomass_to_hydrogen_prod_in_biomass_sankey),
			Q(dry_biomass_to_households_in_biomass_sankey),
			Q(dry_biomass_to_buildings_in_biomass_sankey),
			Q(dry_biomass_to_transport_in_biomass_sankey),
			Q(dry_biomass_to_industry_in_biomass_sankey),
			Q(dry_biomass_to_agriculture_in_biomass_sankey),
			Q(dry_biomass_to_other_in_biomass_sankey),
			Q(dry_biomass_to_bunkers_in_biomass_sankey),
			Q(dry_biomass_to_export_in_biomass_sankey),
			Q(dry_biomass_to_losses_in_biomass_sankey),
			Q(dry_biomass_to_biofuels_in_biomass_sankey)
		)