- query = 
		SUM(
			Q(greengas_to_electricity_prod_in_biomass_sankey),
			Q(greengas_to_central_heat_prod_in_biomass_sankey),
			Q(greengas_to_hydrogen_prod_in_biomass_sankey),
			Q(greengas_to_households_in_biomass_sankey),
			Q(greengas_to_buildings_in_biomass_sankey),
			Q(greengas_to_transport_in_biomass_sankey),
			Q(greengas_to_industry_in_biomass_sankey),
			Q(greengas_to_agriculture_in_biomass_sankey),
			Q(greengas_to_other_in_biomass_sankey),
			Q(greengas_to_bunkers_in_biomass_sankey),
			Q(greengas_to_export_in_biomass_sankey),
			Q(greengas_to_losses_in_biomass_sankey)
		)