- query = 
		SUM(
			Q(biofuels_to_households_in_biomass_sankey),
			Q(biofuels_to_buildings_in_biomass_sankey),
			Q(biofuels_to_transport_in_biomass_sankey),
			Q(biofuels_to_industry_in_biomass_sankey),
			Q(biofuels_to_agriculture_in_biomass_sankey),
			Q(biofuels_to_bunkers_in_biomass_sankey),
			Q(biofuels_to_losses_in_biomass_sankey),
			Q(biofuels_to_non_biogenic_carriers_in_biomass_sankey)
		)