# LULUCF removals should be handled as negative CO2 emissions.
# For the other GHG direct_emissions_lulucf_other_ghg_1990, no separate handling is required for
# emissions/removals since per definition, other GHG in the LULUCF category can only be emissions.

- unit = MT
- query =
    DIVIDE(
      SUM(
        EMISSIONS(lulucf_emissions, non_energetic, co2, 1990),
        NEG(EMISSIONS(lulucf_removals, non_energetic, co2, 1990))
      ),
      THOUSANDS
    )
