# Final consumption of ammonia in industry ex. ict and refineries - fertilizers (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     Ammonia -- ammonia?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_industry_fertilizers_total)
