- query =
        SUM(
            V(industry_aluminium_production,
              industry_steel_production,
              industry_other_metals_production,
              primary_co2_emission)
            ) / THOUSANDS


- unit = T
