- query =
        SUM(
            V(CHILDREN(V(industry_aluminium_production)), primary_co2_emission).sum,
            V(CHILDREN(V(industry_steel_production)), primary_co2_emission).sum,
            V(CHILDREN(V(industry_other_metals_production)), primary_co2_emission).sum
            )

- unit = T
