- query =
        SUM(
            V(
              industry_final_demand_for_metal_electricity,
              industry_final_demand_for_metal_coal,
              industry_final_demand_for_metal_coal_gas,
              industry_final_demand_for_metal_network_gas,
              industry_final_demand_for_metal_wood_pellets,
              industry_final_demand_for_metal_crude_oil,
              industry_final_demand_for_metal_steam_hot_water,
              primary_co2_emission),
              - MV(industry_steel_captured_co2, demand)
        ) / THOUSANDS


- unit = T
