- query =
    SUM(
        Q(co2_sheet_industry_chemical_energetic_co2_emissions),
        Q(industry_chemical_non_energetic_co2_emissions),
        SUM(
            AREA(non_energetic_emissions_co2_chemical_industry),
            AREA(non_energetic_emissions_other_ghg_chemical_industry)
        ) * MILLIONS
    )

- unit = T
