- query =
    SUM(
        SUM(
            V(
                industry_final_demand_for_other_electricity,
                industry_final_demand_for_other_coal,
                industry_final_demand_for_other_network_gas,
                industry_final_demand_for_other_wood_pellets,
                industry_final_demand_for_other_crude_oil,
                industry_final_demand_for_other_steam_hot_water,
                industry_final_demand_for_other_ict_electricity,
                primary_co2_emission
                )
        ) / THOUSANDS,
        SUM(
            AREA(non_energetic_emissions_co2_other_industry),
            AREA(non_energetic_emissions_other_ghg_other_industry),
            AREA(energetic_emissions_other_ghg_industry)
            ) * MILLIONS
    )

- unit = T
