- query =
    SUM(
      Q(final_demand_of_heat_in_households_energetic),
      Q(final_demand_of_heat_in_buildings_energetic),
      Q(final_demand_of_heat_in_agriculture_energetic),
      Q(final_demand_of_heat_in_industry_energetic),
      Q(final_demand_of_heat_in_transport_energetic),
      Q(final_demand_of_heat_in_other_energetic),
      Q(final_demand_of_heat_in_energy_energetic),
      Q(final_demand_of_steam_hot_water_from_feedstock)
    )
- unit = PJ
