- query =
    SUM(
      Q(natural_gas_to_households_in_sankey),
      Q(natural_gas_to_buildings_in_sankey),
      Q(natural_gas_to_agriculture_in_sankey),
      Q(natural_gas_to_industry_in_sankey),
      Q(natural_gas_to_transport_in_sankey),
      Q(natural_gas_to_other_in_sankey),
      Q(natural_gas_to_energy_in_sankey),
      Q(natural_gas_to_bunkers_in_sankey),
      Q(natural_gas_to_feedstock_in_sankey)
    )
- unit = PJ
