# Energetic final demand of the 'natural_gas' carrier group in buildings lighting

- unit = PJ
- query =
    PRODUCT(
      SUM(
        V(
          FILTER(
            FILTER(
              INTERSECTION(EG(final_demand),EG(lighting_buildings)), "network_gas? || compressed_network_gas?"
            ),
            "energetic?"
          ),
          value
        ),
      ),
      Q(share_of_fossil_gas_in_gas_network)
    ) / BILLIONS
