# The delta (difference) between the low voltage net capacity in the present and the future.

- query = MAX(0, QUERY_FUTURE(lv_mv_trafo_capacity_future) - QUERY_PRESENT(lv_mv_trafo_capacity_present))

- unit = MW
