- query =
  SUM(Q(primary_co2_of_industry),
    V(energy_cokesoven_consumption_coal_gas, primary_co2_emission) / BILLIONS,
    V(energy_export_coal_gas, primary_co2_emission) / BILLIONS
  )
- unit = MT
