- query =
  DIVIDE(QUERY_FUTURE(-> {Q(dashboard_energy_demand_primary_of_final_plus_export_losses)}),
         QUERY_PRESENT(-> {Q(dashboard_energy_demand_primary_of_final_plus_export_losses)})
  ) - 1
- unit = %
