- query = 
  SUM(Q(primary_co2_of_energy), 
    NEG(V(energy_cokesoven_consumption_coal_gas, primary_co2_emission)) / BILLIONS, 
    NEG(V(energy_export_coal_gas, primary_co2_emission)) / BILLIONS
  )
- unit = MT
