- query =
    PRODUCT_CURVES(
        COALESCE_CURVE(nil,Q(share_of_natural_gas_in_gas_network)),
        SUM_CURVES(
            SUM_CURVES(V(Q(electricity_producing_network_gas_converters), electricity_output_curve)),
            PRODUCT_CURVES(
                SUM_CURVES(V(Q(electricity_producing_gas_power_fuelmix_converters), electricity_output_curve)),
                COALESCE_CURVE(nil,V(energy_mixer_for_gas_power_fuel, network_gas_input_conversion))
            )
        )
    )
- unit = curve
