- query = 
    SUM_CURVES(
        SUM_CURVES(V(Q(electricity_producing_coal_converters),electricity_output_curve)),
        SUM_CURVES(V(Q(electricity_producing_lignite_converters),electricity_output_curve))
    )
- unit = curve