- unit = PJ
- query =
    SUM(
      Q(final_demand_of_ambient_in_household_appliances_energetic),
      Q(final_demand_of_ammonia_in_household_appliances_energetic),
      Q(final_demand_of_biomass_products_in_household_appliances_energetic),
      Q(final_demand_of_coal_and_derivatives_in_household_appliances_energetic),
      Q(final_demand_of_electricity_in_household_appliances_energetic),
      Q(final_demand_of_geothermal_in_household_appliances_energetic),
      Q(final_demand_of_greengas_in_household_appliances_energetic),
      Q(final_demand_of_heat_in_household_appliances_energetic),
      Q(final_demand_of_hydrogen_in_household_appliances_energetic),
      Q(final_demand_of_lng_in_household_appliances_energetic),
      Q(final_demand_of_natural_gas_in_household_appliances_energetic),
      Q(final_demand_of_oil_and_derivatives_in_household_appliances_energetic),
      Q(final_demand_of_solar_in_household_appliances_energetic),
      Q(final_demand_of_ambient_in_household_cooking_energetic),
      Q(final_demand_of_ammonia_in_household_cooking_energetic),
      Q(final_demand_of_biomass_products_in_household_cooking_energetic),
      Q(final_demand_of_coal_and_derivatives_in_household_cooking_energetic),
      Q(final_demand_of_electricity_in_household_cooking_energetic),
      Q(final_demand_of_geothermal_in_household_cooking_energetic),
      Q(final_demand_of_greengas_in_household_cooking_energetic),
      Q(final_demand_of_heat_in_household_cooking_energetic),
      Q(final_demand_of_hydrogen_in_household_cooking_energetic),
      Q(final_demand_of_lng_in_household_cooking_energetic),
      Q(final_demand_of_natural_gas_in_household_cooking_energetic),
      Q(final_demand_of_oil_and_derivatives_in_household_cooking_energetic),
      Q(final_demand_of_solar_in_household_cooking_energetic),
      Q(final_demand_of_ambient_in_household_cooling_energetic),
      Q(final_demand_of_ammonia_in_household_cooling_energetic),
      Q(final_demand_of_biomass_products_in_household_cooling_energetic),
      Q(final_demand_of_coal_and_derivatives_in_household_cooling_energetic),
      Q(final_demand_of_electricity_in_household_cooling_energetic),
      Q(final_demand_of_geothermal_in_household_cooling_energetic),
      Q(final_demand_of_greengas_in_household_cooling_energetic),
      Q(final_demand_of_heat_in_household_cooling_energetic),
      Q(final_demand_of_hydrogen_in_household_cooling_energetic),
      Q(final_demand_of_lng_in_household_cooling_energetic),
      Q(final_demand_of_natural_gas_in_household_cooling_energetic),
      Q(final_demand_of_oil_and_derivatives_in_household_cooling_energetic),
      Q(final_demand_of_solar_in_household_cooling_energetic),
      Q(final_demand_of_ambient_in_household_hot_water_energetic),
      Q(final_demand_of_ammonia_in_household_hot_water_energetic),
      Q(final_demand_of_biomass_products_in_household_hot_water_energetic),
      Q(final_demand_of_coal_and_derivatives_in_household_hot_waterenergetic),
      Q(final_demand_of_electricity_in_household_hot_water_energetic),
      Q(final_demand_of_geothermal_in_household_hot_water_energetic),
      Q(final_demand_of_greengas_in_household_hot_water_energetic),
      Q(final_demand_of_heat_in_household_hot_water_energetic),
      Q(final_demand_of_hydrogen_in_household_hot_water_energetic),
      Q(final_demand_of_lng_in_household_hot_water_energetic),
      Q(final_demand_of_natural_gas_in_household_hot_water_energetic),
      Q(final_demand_of_oil_and_derivatives_in_household_hot_water_energetic),
      Q(final_demand_of_solar_in_household_hot_water_energetic),
      Q(final_demand_of_ambient_in_household_lighting_energetic),
      Q(final_demand_of_ammonia_in_household_lighting_energetic),
      Q(final_demand_of_biomass_products_in_household_lighting_energetic),
      Q(final_demand_of_coal_and_derivatives_in_household_lighting_energetic),
      Q(final_demand_of_electricity_in_household_lighting_energetic),
      Q(final_demand_of_geothermal_in_household_lighting_energetic),
      Q(final_demand_of_greengas_in_household_lighting_energetic),
      Q(final_demand_of_heat_in_household_lighting_energetic),
      Q(final_demand_of_hydrogen_in_household_lighting_energetic),
      Q(final_demand_of_lng_in_household_lighting_energetic),
      Q(final_demand_of_natural_gas_in_household_lighting_energetic),
      Q(final_demand_of_oil_and_derivatives_in_household_lighting_energetic),
      Q(final_demand_of_solar_in_household_lighting_energetic),
      Q(final_demand_of_ambient_in_household_space_heating_energetic),
      Q(final_demand_of_ammonia_in_household_space_heating_energetic),
      Q(final_demand_of_biomass_products_in_household_space_heating_energetic),
      Q(final_demand_of_coal_and_derivatives_in_household_space_heating_energetic),
      Q(final_demand_of_electricity_in_household_space_heating_energetic),
      Q(final_demand_of_geothermal_in_household_space_heating_energetic),
      Q(final_demand_of_greengas_in_household_space_heating_energetic),
      Q(final_demand_of_heat_in_household_space_heating_energetic),
      Q(final_demand_of_hydrogen_in_household_space_heating_energetic),
      Q(final_demand_of_lng_in_household_space_heating_energetic),
      Q(final_demand_of_natural_gas_in_household_space_heating_energetic),
      Q(final_demand_of_oil_and_derivatives_in_household_space_heating_energetic),
      Q(final_demand_of_solar_in_household_space_heating_energetic)
    )
