# investment costs of energy_power_supercritical_coal IF newly built (green field approach)
- unit = euro

present:V(energy_power_supercritical_coal, total_investment_over_lifetime_per(:converter)) / BILLIONS
