# investment costs of energy_power_combined_cycle_coal IF newly built (green field approach)
- unit = euro

QUERY_DELTA( -> { 
   V(energy_power_combined_cycle_coal,total_investment_over_lifetime_per(:converter)) 
}) / BILLIONS
