# investment costs of households_solar_pv_solar_radiation IF newly built (green field approach)
- unit = euro

QUERY_DELTA( -> { 
   V(households_solar_pv_solar_radiation,total_investment_over_lifetime_per(:converter)) 
}) / BILLIONS
