# investment costs of households_collective_chp_wood_pellets IF newly built (green field approach)
- unit = euro

present:V(households_collective_chp_wood_pellets, total_investment_over_lifetime_per(:converter)) / BILLIONS
