# investment costs of industry_chp_supercritical_wood_pellets IF newly built (green field approach)
- unit = euro

present:V(industry_chp_supercritical_wood_pellets, total_investment_over_lifetime_per(:converter)) / BILLIONS
