# Final consumption of geothermal in industry refineries (energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Geothermal -- geothermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_geothermal_in_industry_refineries_energetic)
