# Losses from network gas distribution and natural gas treatment

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          Q(time_resolved_network_gas_demand_converters),
          input_of_loss
        )
      ),
      BILLIONS
    )
