# Losses from network gas distribution and natural gas treatment

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(energy_distribution_network_gas_loss, demand),
        V(energy_treatment_natural_gas, output_of_loss)
      ),
      BILLIONS
    )
