# Final consumption of renewable waste in international transport - international aviation (energetic use only).
#
# Sector:      International transport - International aviation -- EG(bunkers_international_aviation)
# Carrier:     Renewable waste
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_renewable_waste_in_bunkers_international_aviation_energetic)
