# Non_energetic final demand in the refineries_industry sub-sector

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_refineries_industry_non_energetic),
      Q(final_demand_of_coal_and_derivatives_in_refineries_industry_non_energetic),
      Q(final_demand_of_electricity_in_refineries_industry_non_energetic),
      Q(final_demand_of_ambient_in_refineries_industry_non_energetic),
      Q(final_demand_of_solar_in_refineries_industry_non_energetic),
      Q(final_demand_of_geothermal_in_refineries_industry_non_energetic),
      Q(final_demand_of_heat_in_refineries_industry_non_energetic),
      Q(final_demand_of_hydrogen_in_refineries_industry_non_energetic),
      Q(final_demand_of_natural_gas_and_derivatives_in_refineries_industry_non_energetic),
      Q(final_demand_of_oil_and_derivatives_in_refineries_industry_non_energetic)
    )
