
- unit = PJ
- query =
    SUM(
      Q(output_of_fischer_tropsch_biogenic_waste),
      Q(output_of_fischer_tropsch_dry_biomass),
      Q(output_of_fischer_tropsch_non_biogenic_waste),
      Q(output_of_fischer_tropsch_synthetic_must_run)
    )
