
- unit = PJ
- query =
    DIVIDE(
      V(
        energy_production_fischer_tropsch_non_biogenic_waste_ccs,
        "output_of_diesel + output_of_naphtha + output_of_kerosene"
      ),
      BILLIONS
    )
