
- unit = PJ
- query =
    DIVIDE(
      V(
        energy_production_fischer_tropsch_dry_biomass_ccs,
        "output_of_biodiesel + output_of_bionaphtha + output_of_bio_kerosene"
      ),
      BILLIONS
    )
