# Final consumption of coal and coal products in industry refineries (non-energetic use only).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Coal and coal products -- coal? || coal_gas? || cokes? || lignite?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_coal_and_coal_products_in_industry_refineries_non_energetic)
