# Direct conversion input of coal and coal products for central electricity production

- query = 
    SUM(
      Q(coal_for_electricity_conversion),
      Q(coal_gas_for_electricity_conversion),
      Q(cokes_for_electricity_conversion),
      Q(lignite_for_electricity_conversion)
    )
- unit = PJ
