# Primary demand of carrier group 'electricity' for the curtailment converters

- unit = PJ
- query =
    SUM(
       V(energy_flexibility_curtailment_electricity, primary_demand_of_electricity),
       V(energy_battery_curtailed_solar_electricity, primary_demand_of_electricity),
       V(energy_battery_curtailed_wind_electricity, primary_demand_of_electricity)
    ) / BILLIONS
