- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(INTERSECTION(SECTOR(energy),G(final_demand_group)),primary_demand_of_biodiesel),
        V(INTERSECTION(SECTOR(energy),G(final_demand_group)),primary_demand_of_bio_ethanol),
        V(INTERSECTION(SECTOR(energy),G(final_demand_group)),primary_demand_of_bio_lng)
      ),
      BILLIONS
    )
- deprecated_key = all_biofuels_energy_primary
