# Primary demand of carrier group 'natural_gas_and_derivatives' for the export converter group

- unit = PJ
- query =
    SUM(
       V(G(energy_export), primary_demand_of_natural_gas),
       V(G(energy_export), primary_demand_of_compressed_network_gas),
       V(G(energy_export), primary_demand_of_lng)
    ) / BILLIONS
