# Primary demand of carrier group 'imported_liquid_hydrogen' for the export converter group

- unit = PJ
- query =
    SUM(
       V(G(energy_export), primary_demand_of_imported_liquid_hydrogen)
    ) / BILLIONS
