- query =
    DIVIDE(SUM(V(INTERSECTION(SECTOR(transport),G(final_demand_group)),"
    primary_demand_of_crude_oil + primary_demand_of_diesel + primary_demand_of_heavy_fuel_oil + primary_demand_of_gasoline + primary_demand_of_lpg + primary_demand_of_kerosene
    ")),BILLIONS)
- unit = pj
- deprecated_key = transport_oil_primary_demand
