# Primary demand of carrier group 'waste' for the curtailment converter

- unit = PJ
- query =
    SUM(
       V(energy_flexibility_curtailment_electricity, primary_demand_of_non_biogenic_waste),
       V(energy_flexibility_curtailment_electricity, primary_demand_of_biogenic_waste)
    ) / BILLIONS
