- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          energy_flexibility_curtailment_electricity,
          primary_demand_of(
            crude_oil,
            diesel,
            heavy_fuel_oil,
            gasoline,
            lpg,
            kerosene,
            naphtha,
            pyrolysis_oil
          )
        )
      ),
      BILLIONS
    )
