# Primary demand of carrier group 'imported_electricity' for the curtailment converter

- unit = PJ
- query =
    SUM(
       V(G(curtailment_group), primary_demand_of_imported_electricity)
    ) / BILLIONS
