- query =
    DIVIDE(
      V(
        INTERSECTION(SECTOR(buildings),G(final_demand_cbs)),
        primary_demand_of_electricity
      ).sum,
      BILLIONS
    )
- unit = pj
- deprecated_key = buildings_non_e_primary_demand
