# Primary demand of fossil carriers. Excludes uranium.
# Also excludes imported electricity, hydrogen and heat as it is ambiguous whether
# fossil sources have been used to produce this.

- unit = MJ
- query =
    Q(primary_demand_of_fossil) -
    Q(primary_demand_of_uranium_oxide) -
    Q(primary_demand_of_imported_electricity) -
    Q(primary_demand_of_imported_hydrogen) -
    Q(primary_demand_of_imported_heat)
