- deprecated_key = all_biofuels_other_primary
# 

- unit = pj

DIVIDE(SUM(
V(INTERSECTION(SECTOR(other),G(final_demand_cbs));primary_demand_of_biodiesel),
V(INTERSECTION(SECTOR(other),G(final_demand_cbs));primary_demand_of_biofuel),
V(INTERSECTION(SECTOR(other),G(final_demand_cbs));primary_demand_of_algae_diesel),
V(INTERSECTION(SECTOR(other),G(final_demand_cbs));primary_demand_of_bio_ethanol)),BILLIONS)