- query =
    DIVIDE(
      SUM(
        V(
          INTERSECTION(SECTOR(transport),G(final_demand_group)),"
          primary_demand_of_corn + primary_demand_of_manure + primary_demand_of_bio_oil + primary_demand_of_wood + primary_demand_of_wood_pellets + + primary_demand_of_torrified_biomass_pellets + primary_demand_of_bio_residues_for_firing")
        ),
      BILLIONS
    )
- unit = pj
- deprecated_key = transport_biomass_primary_demand
