- unit = PJ
- query =
    DIVIDE(
      V(INTERSECTION(SECTOR(households),G(final_demand_group)),primary_demand_of_electricity).sum,
      BILLIONS
    )
- deprecated_key = households_non_e_primary_demand
