- query =
    DIVIDE(
      V(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),INTERSECTION(SECTOR(energy),G(final_demand_cbs)),primary_demand_of_coal).sum,
      BILLIONS
    )
- unit = pj
- deprecated_key = industry_coal_primary_demand
