- unit = PJ
- query =
  DIVIDE(
    SUM(
      V(
        INTERSECTION(SECTOR(industry),G(final_demand_group)),
        primary_demand_of_coal
      )
    ),
    BILLIONS
  )
- deprecated_key = industry_coal_primary_demand
