- deprecated_key = other_biomass_primary_demand
# 

- unit = pj

DIVIDE(SUM(
V(INTERSECTION(SECTOR(other),G(final_demand_cbs));primary_demand_of_biomass),
V(INTERSECTION(SECTOR(other),G(final_demand_cbs));primary_demand_of_bio_oil)

),BILLIONS)