- unit = MJ
- query =
    SUM(
      V(G(final_demand_group),primary_demand_of_biodiesel),
      V(G(final_demand_group),primary_demand_of_bio_ethanol),
      V(G(final_demand_group),primary_demand_of_bio_kerosene),
      V(G(final_demand_group),primary_demand_of_bio_lng),
      V(G(final_demand_group),primary_demand_of_bio_oil)
    )
