- unit = MJ
- query =
    DIVIDE(
      SUM(
        V(
          INTERSECTION(SECTOR(industry,energy),G(final_demand_group)),"
          primary_demand_of_corn + primary_demand_of_manure + primary_demand_of_bio_oil + primary_demand_of_wood + primary_demand_of_wood_pellets + primary_demand_of_torrified_biomass_pellets + primary_demand_of_woody_biomass")
        ),
      BILLIONS
    )
- deprecated_key = industry_biomass_primary_demand
