- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(INTERSECTION(SECTOR(industry),G(final_demand_group)),primary_demand_of_electricity),
        V(INTERSECTION(SECTOR(energy),G(final_demand_group)),primary_demand_of_electricity)
      ),
      BILLIONS
    )
- deprecated_key = industry_non_e_primary_demand
