# Primary demand of liquid biomass products
# Includes biogenic carriers for final demand and primary feedstock oily biomass

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          primary_demand_of(
            biodiesel,
            bio_ethanol,
            bio_kerosene,
            bio_lng,
            bio_oil,
            bionaphtha,
            biomethanol,
            bio_pyrolysis_oil,
            oily_biomass
          )
        )
      ),
      BILLIONS
    )
