- query =
    DIVIDE(
      SUM(
        V(INTERSECTION(SECTOR(households),G(final_demand_group)),primary_demand_of_biodiesel),
        V(INTERSECTION(SECTOR(households),G(final_demand_group)),primary_demand_of_bio_ethanol)
      ),
      BILLIONS
    )
- unit = pj
- deprecated_key = all_biofuels_households_primary
