- unit = MJ
- query =
    SUM(
      V(
        G(final_demand_group),
        primary_demand_of(
          biodiesel,
          bio_ethanol,
          bio_kerosene,
          bio_lng,
          bio_oil,
          bionaphtha,
          biomethanol,
          bio_pyrolysis_oil,
          oily_biomass
        )
      )
    )
