# Primary demand of carrier group 'biomass_products' for the curtailment converter

- unit = PJ
- query =
    SUM(
       V(G(curtailment_group), primary_demand_of_biodiesel),
       V(G(curtailment_group), primary_demand_of_bio_ethanol),
       V(G(curtailment_group), primary_demand_of_bio_kerosene),
       V(G(curtailment_group), primary_demand_of_bio_lng),
       V(G(curtailment_group), primary_demand_of_bio_oil)
    ) / BILLIONS
