- unit = PJ
- query =
    DIVIDE(
      V(INTERSECTION(SECTOR(buildings),G(final_demand_group)),primary_demand_of_lignite).sum,
      BILLIONS
    )
- deprecated_key = buildings_lignite_primary_demand
