- deprecated_key = transport_biomass_primary_demand
# 

- unit = pj

DIVIDE(SUM(
V(INTERSECTION(SECTOR(transport),G(final_demand_cbs));primary_demand_of_biomass),
V(INTERSECTION(SECTOR(transport),G(final_demand_cbs));primary_demand_of_bio_oil)
),BILLIONS)