- unit = PJ
- query =
    SUM(
      V(G(final_demand_group),primary_demand_of_coal).sum ,
      V(G(final_demand_group),primary_demand_of_coal_gas).sum,
      V(G(final_demand_group),primary_demand_of_cokes).sum,
      V(G(final_demand_group),primary_demand_of_lignite).sum
    ) / BILLIONS
