- query =
    DIVIDE(
      V(INTERSECTION(SECTOR(other),G(final_demand_group)),primary_demand_of_imported_electricity).sum,
      BILLIONS
    )
- unit = pj
- deprecated_key = other_imported_e_primary_demand
