# Primary demand of carrier group 'waste' for the curtailment converter

- unit = PJ
- query =
    SUM(
       V(G(curtailment_group), primary_demand_of_non_biogenic_waste),
       V(G(curtailment_group), primary_demand_of_biogenic_waste)
    ) / BILLIONS
