# The amount of primary energy needed to produce the electricity that is exported.

- unit = MJ
- query = MAX(V(energy_export_electricity,primary_demand),0)
- deprecated_key = primary_demand_of_electricity_export
