# Primary demand of carrier group 'coal_and_derivatives' for the curtailment converter

- unit = PJ
- query =
    SUM(
       V(G(curtailment_group), primary_demand_of_coal),
       V(G(curtailment_group), primary_demand_of_coal_gas),
       V(G(curtailment_group), primary_demand_of_cokes)
    ) / BILLIONS
