- query =
    SUM(
      Q(primary_demand_of_biomass_from_agriculture),
      Q(primary_demand_of_crude_oil_from_agriculture),
      Q(primary_demand_of_uranium_from_agriculture),
      Q(primary_demand_of_coal_from_agriculture),
      Q(primary_demand_of_lignite_from_agriculture),
      Q(primary_demand_of_waste_from_agriculture),
      Q(primary_demand_of_electricity_from_agriculture),
      Q(primary_demand_of_biofuels_from_agriculture),
      Q(primary_demand_of_imported_electricity_from_agriculture)
    )
- unit = pj
- deprecated_key = agriculture_primary_demand_without_gas
