# Primary demand of carrier group 'biomass_products' for the export converter group

- unit = PJ
- query =
    SUM(
       V(G(curtailment_group), primary_demand_of_torrefied_biomass_pellets),
       V(G(curtailment_group), primary_demand_of_wood_pellets)
    ) / BILLIONS
