# Primary demand of carrier group 'imported_electricity' for the export converter group

- unit = PJ
- query =
    SUM(
       V(G(energy_export), primary_demand_of_imported_electricity)
    ) / BILLIONS
