- query =
    DIVIDE(
      V(
        INTERSECTION(SECTOR(buildings),G(final_demand_cbs)),
        "primary_demand_of_crude_oil + primary_demand_of_diesel + primary_demand_of_heavy_fuel_oil + primary_demand_of_gasoline + primary_demand_of_lpg + primary_demand_of_kerosene"
        ).sum,
      BILLIONS
    )
- unit = pj
- deprecated_key = buildings_oil_primary_demand
