- query =
    SUM(
      V(
        G(final_demand_group),
        "primary_demand_of_solar_thermal + primary_demand_of_biogenic_waste + primary_demand_of_non_biogenic_waste"
      )
    )
- unit = MJ
