# Final consumption from other, all carriers (energetic use only).
#
# Sector:      Other -- sector == :other
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_other_energetic)
