# Direct conversion output of steam hot water on LT heat network through biomass products

- query =
    SUM(
      Q(biogas_in_source_of_lt_heat_network_conversion),
      Q(wood_pellets_in_source_of_lt_heat_network_conversion),
      Q(torrefied_biomass_pellets_in_source_of_lt_heat_network_conversion),
      Q(greengas_in_source_of_lt_heat_network_conversion),
      PRODUCT(
        Q(waste_mix_in_source_of_lt_heat_network_conversion),
        Q(share_of_biogenic_waste_in_waste_mix)
      ),
      PRODUCT(
        Q(network_gas_in_source_of_lt_heat_network_conversion),
        Q(share_of_sustainable_gas_in_gas_network)
      )
    )
- unit = PJ
