# Direct conversion output of steam hot water on LT heat network through non biogenic waste

- query =
    SUM(
      PRODUCT(
        Q(waste_mix_in_source_of_lt_heat_network_conversion),
        Q(share_of_non_biogenic_waste_in_waste_mix)
      )
    )
- unit = PJ
