# Final consumption of electricity in international transport - international navigation (energetic and non-energetic use combined).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Electricity -- electricity?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_electricity_in_bunkers_international_navigation_total)
