# Percentage share of biogenic waste in total electricity production

- unit = factor
- query = DIVIDE(PRODUCT(Q(electricity_produced_from_waste), V(energy_distribution_waste_mix, sustainability_share)), Q(total_electricity_consumed))*100
