# Percentage of electricity produced from torrified_biomass_pellets in total electricity production

- unit = factor
- query = DIVIDE(Q(electricity_produced_from_torrified_biomass_pellets),Q(total_electricity_produced))*100
