# For the present and if time-resolved calculations are turned off
# the hourly input curves are not available. In that case
# we estimate peak demand by multiplying total demand (in MWh)
# by a 'peak demand factor'. This factor is based on NL2015 dataset by
# dividing the future supply peak in a blank scenario by the yearly supply
- query =
      estimated_peak_demand_factor = 0.000114;
      estimated_peak_demand_factor *
      SUM(
        V(
          FILTER(
            G(primary_heat_infrastructure), 
            "heat_network_ht"
          ),
          "output_of_steam_hot_water / MJ_PER_MWH"
        )
      )
- unit = MW