# As the Klimaatsector mapping does not distinguish between international aviation and navigation
# and the emissions of aviation and navigation are dependent on seperate ETM inputs,
# the ETM sector bunkers query is used instead of a dedicated Klimaatsector query.

- unit = MT
- query = Q(direct_emissions_bunkers_other_ghg_1990)
