- query =
    SUM(
      Q(heat_infrastructure_households_ht_indoor_investment_costs),
      Q(heat_infrastructure_buildings_ht_indoor_investment_costs),
      Q(heat_infrastructure_ht_exchanger_station_investment_costs),
      Q(heat_infrastructure_ht_sub_station_investment_costs),
      Q(heat_infrastructure_ht_distribution_pipelines_investment_costs),
      Q(heat_infrastructure_ht_connection_pipelines_investment_costs),
      Q(heat_infrastructure_ht_primary_pipelines_investment_costs)
    )
- unit = euro