- query =
    SUM(
      Q(heat_infrastructure_distribution_pipelines_annualised_costs),
      Q(heat_infrastructure_primary_pipelines_annualised_costs),
      Q(heat_infrastructure_distribution_stations_annualised_costs),
      Q(heat_infrastructure_indoor_annualised_costs)
    )
- unit = euro
