- query =
    SUM(
      V(G(costs_infrastructure_lohc), capital_expenditures_excluding_ccs_per(:node)),
      V(G(costs_infrastructure_lohc), operating_expenses_excluding_ccs_per(:node))
    )
    
- unit = euro