- query =
    SUM(
      Q(costs_infrastructure_natural_gas),
      Q(costs_infrastructure_hydrogen_carriers),
      Q(costs_infrastructure_electricity),
      Q(costs_infrastructure_heat),
      Q(costs_infrastructure_ammonia),
      Q(costs_infrastructure_oil_and_products)
    )
- unit = euro
