- query =
    SUM(
      Q(costs_infrastructure_network_gas),
      Q(costs_infrastructure_hydrogen),
      Q(costs_infrastructure_electricity),
      Q(costs_infrastructure_heat)
    )

- unit = euro