- query =
    SUM(
      Q(costs_infrastructure_network_gas),
      Q(costs_infrastructure_hydrogen),
      Q(costs_infrastructure_electricity),
      Q(costs_infrastructure_heat),
      Q(costs_infrastructure_ammonia),
      Q(costs_infrastructure_diesel),
      Q(costs_infrastructure_liquid_hydrogen),
      Q(costs_infrastructure_lng),
      Q(costs_infrastructure_lohc)
    )

- unit = euro