#!/usr/bin/env ruby

# XLS2YML
# =======
#
# This script converts the csv files generated by excel to a set of yml files
# to be used by etsource.
#
#   Usage:
#
#   xls2yml.rb [source]
#
# The source parameter is optional. If missing the script will use
# ETSOURCE/csv_files as excel export directory. If you specify the source
# parameter then it should be an existing directory.
# The script will output files in the main etsource directory. *Old files will be
# overwritten*.

require_relative 'lib/processor'
require_relative 'lib/excel_export'
require_relative 'lib/csv'
require_relative 'lib/converter_exporter'
require_relative 'lib/slot_exporter'
require 'term/ansicolor'
require 'fileutils'
include Term::ANSIColor

@etsource_root = File.expand_path("#{File.dirname(__FILE__)}/../..")
@source = ARGV[0] || "#{@etsource_root}/csv_files"
unless File.directory?(@source)
  puts "Missing CSV files directory!"
  exit
end
ETE::Processor.new(:source => @source, :dest => @etsource_root).export_all
