- query = 
    SUM(
      Q(conversion_loss_biomass_products_to_natural_gas_and_derivatives),
      Q(conversion_loss_electricity_to_compressed_network_gas),
      Q(conversion_loss_electricity_to_natural_gas_and_derivatives),
      Q(conversion_industry_residual_natural_gas),
      Q(conversion_loss_natural_gas_and_derivatives_to_natural_gas_and_derivatives),
      Q(conversion_loss_natural_gas_to_natural_gas),
      Q(conversion_loss_natural_gas_to_network_gas),
      Q(conversion_loss_network_gas_to_compressed_network_gas),
      Q(conversion_loss_crude_oil_to_refinery_gas),
      Q(conversion_loss_ammonia_to_hydrogen) 
    )
- unit = PJ
