- query = 
    SUM(
      Q(conversion_loss_electricity_to_hydrogen),
      Q(conversion_loss_hydrogen_to_hydrogen),
      Q(conversion_loss_natural_gas_and_derivatives_to_hydrogen),
      Q(conversion_loss_biomass_products_to_hydrogen),
      Q(conversion_loss_ammonia_to_hydrogen)
    )
- unit = PJ
