
- query = 
    SUM(
      Q(conversion_loss_electricity_to_hydrogen),
      Q(conversion_loss_hydrogen_to_hydrogen),
      Q(conversion_loss_natural_gas_and_derivatives_to_hydrogen),
      Q(conversion_loss_biomass_products_to_hydrogen),
      Q(conversion_loss_ammonia_to_hydrogen),
      Q(conversion_loss_lohc_to_hydrogen),
      Q(conversion_loss_liquid_hydrogen_to_hydrogen),
      V(energy_hydrogen_storage_depleted_gas_field, output_of_loss),
      V(energy_hydrogen_storage_salt_cavern, output_of_loss)
    )
- unit = PJ