- query = 
    SUM(
      Q(conversion_loss_greengas_to_network_gas),
      Q(conversion_loss_natural_gas_to_network_gas),
      Q(conversion_loss_network_gas_to_compressed_network_gas),
      Q(conversion_loss_electricity_to_compressed_network_gas)
    )
- unit = PJ
