- query = 
    SUM(
      Q(conversion_loss_biogas_to_electricity),
      Q(conversion_loss_biomass_products_to_electricity),
      Q(conversion_loss_torrefied_biomass_pellets_to_electricity),      
      Q(conversion_loss_wood_pellets_to_electricity),
      Q(conversion_loss_coal_and_derivatives_to_electricity),
      Q(conversion_loss_coal_gas_to_electricity),
      Q(conversion_loss_coal_to_electricity),
      Q(conversion_loss_lignite_to_electricity),
      Q(conversion_loss_hydrogen_to_electricity),
      Q(conversion_loss_natural_gas_and_derivatives_to_electricity),
      Q(conversion_loss_network_gas_to_electricity),
      Q(conversion_loss_crude_oil_to_electricity),
      Q(conversion_loss_diesel_to_electricity),
      Q(conversion_loss_oil_and_derivatives_to_electricity),
      Q(conversion_loss_uranium_to_electricity)
    )
- unit = PJ
