- unit = PJ
- query =
        SUM(
           Q(sankey_final_demand_of_biomass_products_in_industry_ict_energetic),
           Q(sankey_final_demand_of_biomass_products_in_industry_other_energetic)
           )
