
- unit = PJ
- query = 
    SUM(
        Q(sankey_final_demand_of_biomass_products_in_households_space_heating_and_hot_water_energetic),
        Q(sankey_final_demand_of_biomass_products_in_households_other_energetic)
        )