- query = 
    SUM(
      Q(conversion_loss_coal_and_derivatives_to_coal_and_derivatives),
      Q(conversion_loss_coal_to_coal_gas),
      Q(conversion_loss_coal_to_coal),
      Q(conversion_loss_cokes_to_coal_gas)
    )
- unit = PJ
