- query = 
    SUM(
      Q(conversion_loss_biomass_products_to_electricity),
      Q(conversion_loss_coal_and_derivatives_to_electricity),
      Q(conversion_loss_hydrogen_to_electricity),
      Q(conversion_loss_natural_gas_and_derivatives_to_electricity),
      Q(conversion_loss_oil_and_derivatives_to_electricity),
      Q(conversion_loss_uranium_to_electricity),
      Q(conversion_loss_electricity_to_electricity)
    )
- unit = PJ
