- query =
    SUM(
      Q(conversion_loss_biomass_products_to_natural_gas),
      Q(conversion_loss_electricity_to_natural_gas),
      Q(conversion_loss_hydrogen_to_methanol),
      Q(conversion_loss_natural_gas_and_derivatives_to_natural_gas),
      Q(conversion_loss_oil_and_derivatives_to_natural_gas),
      Q(conversion_loss_waste_mix_to_natural_gas),
      Q(conversion_loss_methanol_to_natural_gas),
      Q(conversion_loss_ammonia_to_natural_gas),
      Q(conversion_loss_not_defined_to_natural_gas_and_derivatives),
      Q(conversion_loss_steam_hot_water_to_natural_gas),
    )
- unit = PJ
