- query = 
    SUM(
      Q(conversion_loss_electricity_to_oil_and_derivatives),
      Q(conversion_loss_hydrogen_to_oil_and_derivatives),
      Q(conversion_loss_oil_and_derivatives_to_oil_and_derivatives)
    )
- unit = PJ
