- query =
    SUM(
      Q(conversion_loss_biofuels_to_electricity),
      Q(conversion_loss_electricity_to_biofuels),
      Q(conversion_loss_ammonia_to_biofuels),
      Q(conversion_loss_methanol_to_biofuels),
      Q(conversion_loss_waste_mix_to_biofuels),
      Q(conversion_loss_not_defined_to_biofuels),
      Q(conversion_loss_natural_gas_to_biofuels),
      Q(conversion_loss_biomass_products_to_biomass_products),
      Q(conversion_loss_network_gas_to_biofuels),
      Q(conversion_loss_hydrogen_to_biofuels)
    )
- unit = PJ

