- query = 
    SUM(
        Q(emissions_captured_hydrogen_autothermal_reformer),
        Q(emissions_captured_hydrogen_biomass_gasification),
         Q(emissions_captured_hydrogen_steam_methane_reformer)
    )
- unit = tonne