- query = 
    DIVIDE(
      V(industry_useful_demand_for_chemical_refineries_crude_oil_non_energetic, preset_demand),
      BILLIONS
    ) *
    (1 - V(OUTPUT_SLOTS(industry_refinery_transformation_crude_oil, loss), conversion))
- unit = PJ
