- query =
    SUM_CURVES(V(
      energy_heat_well_geothermal,
      energy_heat_heatpump_water_water_electricity,
      energy_heat_boiler_electricity,
      electricity_input_curve
    ))
- unit = curve
