- query =
    SUM_CURVES(
      V(
        EXCLUDE(
          INTERSECTION(SECTOR(energy),G(heat_production)),
          FILTER(ALL(),"merit_order && (merit_order.type == :flex)")
        ),
        electricity_input_curve
      )
    )
- unit = curve
