- query =
    SUM_CURVES(V(
      industry_final_demand_for_metal_other_metals_electricity,
      industry_final_demand_for_metal_aluminium_electricity,
      industry_steel_blastfurnace_bof,
      industry_steel_scrap_hbi_eaf,
      industry_steel_cyclonefurnace_bof,
      industry_steel_dri_network_gas,
      industry_steel_dri_hydrogen,
      industry_steel_blastfurnace_bof_captured_co2_electricity,
      industry_steel_cyclonefurnace_captured_bof_co2_electricity,
      industry_steel_dri_network_gas_eaf_captured_co2_electricity,
      industry_steel_external_coupling_node,
      industry_steel_external_coupling_node_captured_co2_electricity,
      electricity_input_curve
    ))
- unit = curve
