- query =
    SUM_CURVES(V(
      industry_aluminium_carbothermalreduction_electricity,
      industry_aluminium_electrolysis_bat_electricity,
      industry_aluminium_electrolysis_current_electricity,
      industry_other_metals_process_electricity,
      industry_steel_blastfurnace_bof,
      industry_steel_scrap_hbi_eaf,
      industry_steel_hisarna_bof,
      industry_steel_blastfurnace_captured_co2_electricity,
      industry_steel_hisarna_captured_co2_electricity,
      industry_steel_eaf_captured_co2_electricity,
      electricity_input_curve
    ))
- unit = curve
