- query =
    SUM_CURVES(V(
      industry_aluminium_carbothermalreduction_electricity,
      industry_aluminium_electrolysis_bat_electricity,
      industry_aluminium_electrolysis_current_electricity,
      industry_other_metals_process_electricity,
      industry_steel_blastfurnace_bat_consumption_useable_heat,
      industry_steel_blastfurnace_current_consumption_useable_heat,
      industry_steel_electricfurnace_electricity,
      industry_steel_hisarna_consumption_useable_heat,
      industry_steel_blastfurnace_captured_co2_electricity,
      industry_steel_hisarna_captured_co2_electricity,
      industry_steel_electricfurnace_captured_co2_electricity,
      electricity_input_curve
    ))
- unit = curve
