- query =
    SUM_CURVES(V(
      energy_compressor_network_gas,
      energy_offshore_sequestration_co2_electricity,
      energy_synthetic_products_electricity,
      electricity_input_curve
    ))
- unit = curve
