- query =
    SUM_CURVES(V(
      transport_bicycle_using_electricity,
      transport_bus_using_electricity,
      transport_freight_train_using_electricity,
      transport_motorcycle_using_electricity,
      transport_passenger_train_using_electricity,
      transport_tram_using_electricity,
      transport_truck_using_electricity,
      transport_plane_using_electricity,
      transport_van_using_electricity,
      transport_ship_using_electricity,
      electricity_input_curve
    ))
- unit = curve
