- unit = curve
- query =
      SUM_CURVES(V(
          FILTER(SECTOR(transport),"merit_order && (merit_order.level == :mv) && (merit_order.type == :consumer)"),
        	FILTER(SECTOR(bunkers),"merit_order && (merit_order.level == :mv) && (merit_order.type == :consumer)"),
        electricity_input_curve
        ))
