# This is a temporary query that I'm using to test some improvements to the network calculation

- unit = converters

V(
    industry_chp_combined_cycle_gas_power_fuelmix,
    industry_chp_supercritical_wood_pellets,
    energy_power_wind_turbine_inland,
    energy_power_wind_turbine_coastal,
    energy_power_hydro_river,
    energy_power_geothermal
)
