# This is a temporary query that I'm using to test some improvements to the network calculation

- unit = converters

V(
    airco_households_energetic,
    electric_heater_households_energetic,
    micro_chp_space_heating_households,
    heatpump_households_energetic,
    heatpump_addon_households_energetic,
    heatpump_cooling_households_energetic,
    heatpump_boiler_households_energetic,
    fuel_cell_chp_households_energetic,
    micro_chp_hot_water_households_energetic,
    electric_cars_transport_energetic,
    electric_trucks_transport_energetic,
    electric_boiler_households_energetic,
    local_solar_pv_grid_connected_energy_energetic
)