# This is a temporary query that I'm using to test some improvements to the network calculation

- unit = converters

V(
    small_chp_industry_energetic,
    biomass_chp_industry_energetic,
    wind_inland_energy,
    wind_coastal_energy,
    hydro_river_energy,
    geothermal_electricity_energy
)