# 

- unit = mw

PRODUCT(
   Q(network_mv_d_net_delta_peak_load_max),
   MAX(
      V(mv_distribution_network_energy_energetic,simult_we),
      V(mv_distribution_network_energy_energetic,simult_wd),
      V(mv_distribution_network_energy_energetic,simult_se),
      V(mv_distribution_network_energy_energetic,simult_sd)
   )
)