# 

- unit = mw

PRODUCT(
   Q(network_lv_net_delta_peak_load_max),
   MAX(
      V(lv_electricity_network_energy_energetic,simult_we),
      V(lv_electricity_network_energy_energetic,simult_wd),
      V(lv_electricity_network_energy_energetic,simult_se),
      V(lv_electricity_network_energy_energetic,simult_sd)
   )
)