# 

- unit = mw

PRODUCT(
   Q(network_lv_net_delta_peak_load_max),
   MAX(
      V(energy_power_lv_network_electricity,simult_we),
      V(energy_power_lv_network_electricity,simult_wd),
      V(energy_power_lv_network_electricity,simult_se),
      V(energy_power_lv_network_electricity,simult_sd)
   )
)
