# This is a temporary query that I'm using to test some improvements to the network calculation

- unit = converters

V(
    Q(household_coolers_in_network_calculation),
    Q(household_heaters_in_network_calculation),
    micro_chp_space_heating_households, 
    electric_cars_transport_energetic,
    electric_trucks_transport_energetic,
    electric_boiler_households_energetic,
    local_solar_pv_grid_connected_energy_energetic
)