# The biomass used in the other sector, plus the sustainable part of the fossil fuels.

- unit = mj

SUM(V(biomass_demand_other_energetic,demand),
SUM(
	V(coal_demand_other_energetic
	oil_demand_other_energetic,
	gas_demand_other_energetic,
	steam_hot_water_for_heat_other_energetic,"demand * sustainability_share")
  )
)

