# The final demand of electricity, plus distribution losses, but excluding distribution losses for export.

- unit = MJ
- query =
    SUM(
      V(GROUP(final_demand_group),input_of_electricity),
      V(GROUP(non_final_electricity_demand_converters),input_of_electricity),
      V(energy_power_hv_network_loss,demand),
      NEG(Q(distribution_losses_for_exported_electricity))
    )
