- query =
    DIVIDE(
      V(
        INTERSECTION(SECTOR(transport),G(final_demand_cbs)),
        "input_of_biodiesel + input_of_bio_ethanol"
      ).sum,
      BILLIONS
    )
- unit = pj
- deprecated_key = all_biofuels_transport_final
