# The final demand in the buildings sector.

- unit = MJ
- query =
  SUM(
    V(
      FILTER(
          FILTER(
            LG(final_demand),"sector == :buildings"
          ),
          energetic?
        ),
      value
    )
  )
