# sum of non_sustainable energy final demand

- unit = mj

SUM(
V(coal_demand_other_energetic,demand),
V(oil_demand_other_energetic,demand),
V(gas_demand_other_energetic,demand),
V(steam_hot_water_for_heat_other_energetic,demand))