# The final demand in the industry and energy sector.

- query =
    SUM(
      V(INTERSECTION(G(final_demand_cbs),SECTOR(industry)),demand),
      V(INTERSECTION(G(final_demand_cbs),SECTOR(energy)),demand)
    )
- unit = mj
