# Energetic final demand of electricity in industry excluding ict

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_electricity_in_industry),
      NEG(Q(industry_final_demand_for_electricity_in_ict))
    )
