- deprecated_key = pl_network_total_costs
# 

- unit = euro

SUM(
    PRODUCT(
        SUM(
            MAX(AREA(annual_infrastructure_cost_electricity),0),
            MAX(AREA(annual_infrastructure_cost_gas),0)
        ),
        MILLIONS
    ),
    Q(yearly_investment_costs_of_network)
)