- deprecated_key = pl_hv_net_operational_costs_total
# 

- unit = euro

PRODUCT(
    DIVIDE(
            V(energy_power_hv_network_electricity,"operation_and_maintenance_cost_fixed_per_mw_input*network_capacity_available_in_mw"),
            V(energy_power_transformer_mv_hv_electricity, network_capacity_available_in_mw)
        ),
    Q(network_hv_mv_trafo_delta_peak_load_max)
)
