# Costs for O&M of the MV-distribution network. Assumed to increase linearly with the newly required capacity

- query =
    PRODUCT(
        V(energy_power_mv_distribution_network_electricity, fixed_operation_and_maintenance_costs_per(:mw_input)),
        Q(network_mv_d_net_delta_peak_load_max)
    )
- unit = euro
- deprecated_key = pl_mv_d_net_operational_costs_total
