- deprecated_key = pl_hv_mv_trafo_investment_costs_total
# For the investment costs HV MV transformer, an extra 'if' statement is added (Q(peak_load_delta_on_mv_hv_transformer) ). For this transformer it is important to check which value is the largest:
# 1. Impact from demand technologies from LV grid
# 2. Impact from supply technologies attached to the HV MV transformer

- unit = euro

PRODUCT(
 Q(hv_mv_trafo_capacity_needed),
V(energy_power_transformer_mv_hv_electricity,network_expansion_costs_in_euro_per_mw)
)
