- deprecated_key = pl_mv_d_net_investment_costs_total
# 
#PRODUCT(
#  Q(mv_d_net_capacity_needed),
#  V(energy_power_mv_distribution_network_electricity,network_expansion_costs_in_euro_per_mw)
#)
- unit = euro

PRODUCT(
  Q(network_mv_d_net_delta_peak_load_max),
  V(energy_power_mv_distribution_network_electricity,network_expansion_costs_in_euro_per_mw)
)
