- deprecated_key = pl_mv_t_net_investment_costs_total
# 

- unit = euro

PRODUCT(
 Q(mv_t_net_capacity_needed),
V(energy_power_mv_transport_network_electricity,network_expansion_costs_in_euro_per_mw)
)
