- deprecated_key = pl_mv_lv_trafo_investment_costs_total
# SUM(
#   MAX(
#     SUM(
#       Q(peak_load_delta_max_lv_net), 
#       V(energy_power_lv_network_electricity, typical_capacity_effective_in_mj_s) 
#     ),
#     V(energy_power_lv_network_electricity,typical_capacity_gross_in_mj_s)
#   ),
#   NEG(
#     V(energy_power_lv_network_electricity,typical_capacity_gross_in_mj_s)
#   )
# )

- unit = euro

PRODUCT(
  Q(mv_lv_trafo_capacity_needed),
V(energy_power_transformer_lv_mv_electricity,network_expansion_costs_in_euro_per_mw)
)
