- deprecated_key = pl_hv_net_investment_costs_total
# First checks if the country is set to NL before it does the calculation.
# 
# The investment costs for the HV network are defined according a rule of thumb in which the costs (in MEur) are a percent of the installed capacity (in MW). The percentages are given by the hard numbers: 0.20 and 0.25
# 
# Additional HV network costs for 'stopcontact op zee' are also included.

- unit = euro

SUM(
    PRODUCT(
        IF(
            Q(hv_net_capacity_buffer_total_check),
            IF(
                Q(hv_net_capacity_buffer_decentral_check), 
                SUM(
                    PRODUCT(
                        Q(hv_net_delta_capacity_central),
                        0.20
                    ),
                    PRODUCT(
                        Q(hv_net_delta_capacity_decentral),
                        0.25 
                    )
                ),
                PRODUCT(
                    Q(hv_net_delta_capacity_total),
                    0.20
                )
            ),
            0
        ),
        MILLIONS
    ),
    Q(yearly_investment_costs_of_hv_net_wind_offshore)
)

