- deprecated_key = pl_lv_net_investment_costs_per_year
# 

- unit = euro

SUM(
 DIVIDE(
  Q(total_investment_costs_of_lv_net),V(lv_electricity_network_energy_energetic,technical_lifetime)
 ),
 PRODUCT(
  DIVIDE(
   Q(total_investment_costs_of_lv_net),2
  ),
  V(lv_electricity_network_energy_energetic,wacc)
 ),
 Q(operational_costs_of_lv_net)
 )
