- deprecated_key = pl_hv_grid_investment_costs_per_year
# First checks if the country is set to NL before it does the calculation.

- unit = euro

SUM(
     Q(total_investment_costs_of_hv_net) / V(energy_power_hv_network_electricity,technical_lifetime),
     Q(total_investment_costs_of_hv_net) / 2 * V(energy_power_hv_network_electricity,wacc),
     Q(operational_costs_of_hv_net)
)