- deprecated_key = pl_mv_grid_investment_costs_per_year
# 

- unit = euro

SUM(
    Q(yearly_investment_costs_of_mv_t_net),
    Q(yearly_investment_costs_of_mv_d_net),
    Q(yearly_investment_costs_of_hv_mv_trafo)
)