- deprecated_key = pl_hv_mv_trafo_investment_costs_per_year
# This is the sum of 3 costs: Depreciation, cost of capital, and o&m costs

- unit = euro

SUM(
 DIVIDE(
  Q(total_investment_costs_of_hv_mv_trafo),V(mv_hv_transformer_energy;technical_lifetime)
 ),
 PRODUCT(
  DIVIDE(
   Q(total_investment_costs_of_hv_mv_trafo),2
  ),
  V(mv_hv_transformer_energy;wacc)
 ),
 Q(operational_costs_of_hv_mv_trafo)
 )