- deprecated_key = pl_mv_d_net_investment_costs_per_year
# 

- unit = euro

SUM(
 DIVIDE(
  Q(total_investment_costs_of_mv_d_net),V(mv_distribution_network_energy_energetic;technical_lifetime)
 ),
 PRODUCT(
  DIVIDE(
   Q(total_investment_costs_of_mv_d_net),2
  ),
  V(mv_distribution_network_energy_energetic;wacc)
 ),
 Q(operational_costs_of_mv_d_net)
 )