- deprecated_key = pl_mv_lv_trafo_investment_costs_per_year
# 

- unit = euro

SUM(
 DIVIDE(
  Q(total_investment_costs_of_mv_lv_trafo),V(lv_mv_transformer_energy;technical_lifetime)
 ),
 PRODUCT(
  DIVIDE(
   Q(total_investment_costs_of_mv_lv_trafo),2
  ),
  V(lv_mv_transformer_energy;wacc)
 ),
 Q(operational_costs_of_mv_lv_trafo)
 )
