# Total costs calculated to yearly costs of the MV-distribution network
# Equal to the sum of the depreciation, cost of capital, and O&M costs

- query =
    SUM(
        Q(total_investment_costs_of_mv_d_net) / V(energy_power_mv_distribution_network_electricity,technical_lifetime),
        Q(total_investment_costs_of_mv_d_net) / 2 * V(energy_power_mv_distribution_network_electricity,wacc),
        Q(operational_costs_of_mv_d_net)
    )
- unit = euro
- deprecated_key = pl_mv_d_net_investment_costs_per_year
