# For the present and if time-resolved calculations are turned off
# there is no storage, so costs are zero
- query =
      IF(
          GRAPH().present? || AREA(use_merit_order_demands) == false,
          -> { 0.0 },
          -> { SUM(V(energy_heat_network_storage_mt_steam_hot_water, "steam_hot_water_output_curve * storage.cost_per_mwh")) }
      )
- unit = MW
