---
# Defines dynamic load profiles used by participants in the merit order.
# Visitors may decide how to mix the profiles with a slider in the front end.
#
# For example:
#
#   ev_demand:
#     type: interpolate
#     curves:
#       - electric_vehicle_1
#       - electric_vehicle_2
#       - electric_vehicle_3
#
# The user may use a slider to set area attribute "electric_vehicle_1_share" to
# 0.25, "electric_vehicle_2_share" to 0.3, and "electric_vehicle_3_share" to
# 0.45; ETEngine will craft a new "ev_demand" curve containing a mix of the
# three profiles with a share of 25%, 30%, and 45% respectively.
#
# In order for this profile to work, Atlas::Dataset must define the following
# attributes:
#
#   attribute :electric_vehicle_1_share, Float, default: 1.0
#   attribute :electric_vehicle_2_share, Float, default: 0.0
#   attribute :electric_vehicle_3_share, Float, default: 0.0
#   attribute :electric_vehicle_4_share, Float, default: 0.0
#   attribute :electric_vehicle_5_share, Float, default: 0.0
#
# The profile may be assigned to a merit order participant by assigning
# "dynamic: <profile_name>" to the node "merit.group" attribute. For example:
#
#   - merit.type = consumer
#   - merit.group = dynamic: ev_demand
#   - merit_order.level = lv
#
# Alternatively, rather than interpolating between two or more curves, you may
# define a single "baseline" curve and have ETEngine amplify the curve to the
# user-assigned full-load hours of the node. For example:
#
#   solar_pv:
#     type: amplify
#     curve: solar_pv_baseline

ev_demand:
  type: interpolate
  curves:
    - electric_vehicle_profile_1
    - electric_vehicle_profile_2
    - electric_vehicle_profile_3
    - electric_vehicle_profile_4
    - electric_vehicle_profile_5

solar_pv_on_roof_households:
  type: amplify
  curve: weather/solar_pv_on_roof_households

solar_pv_on_roof_buildings:
  type: amplify
  curve: weather/solar_pv_on_roof_buildings

solar_pv_on_land:
  type: amplify
  curve: weather/solar_pv_on_land

solar_pv_offshore:
  type: amplify
  curve: weather/solar_pv_offshore

wind_coastal:
  type: amplify
  curve: weather/wind_coastal_baseline

wind_inland:
  type: amplify
  curve: weather/wind_inland_baseline

wind_offshore:
  type: amplify
  curve: weather/wind_offshore_baseline
