# Defines the order in which flexibility items are prioritised in the merit
# order. "curtailment" should not be included; it is always the lowest-priority
# option.
#
# Flexibility technologies which participate in the merit order will usually
# have a config such as:
#
#   - merit_order.group = household_batteries
#   - merit_order.level = lv
#   - merit_order.subtype = storage
#   - merit_order.type = flex
#
# Note the "merit_order.type" which indicates the node is a flexible technology.
# The "merit_order.group" attribute should correspond to one of the values in
# this file.
---
- household_batteries
- mv_batteries
- electric_vehicle
- opac
- pumped_storage
- power_to_gas
- power_to_heat_industry
- power_to_heat_district_heating_boiler
- power_to_heat_district_heating_heatpump
- export
