# Defines the order in which dispatchable technologies are prioritised in the
# heat network. Each item in the list below should correspond to a node key.
---
- energy_heat_network_storage_lt_steam_hot_water
