# Defines the order in which dispatchable technologies are prioritised in the
# heat network. Each item in the list below should correspond to a node key.
---
- energy_heat_network_storage_ht_steam_hot_water
- energy_heat_boiler_ht_electricity
- energy_heat_burner_ht_coal
- energy_heat_burner_ht_crude_oil
- energy_heat_burner_ht_hydrogen
- energy_heat_burner_ht_network_gas
- energy_heat_burner_ht_waste_mix
- energy_heat_burner_ht_wood_pellets
- energy_heat_heatpump_water_water_ht_electricity
