# Defines the order in which dispatchable technologies are prioritised in the
# heat network. Each item in the list below should correspond to a node key.
---
- energy_heat_network_storage_mt_steam_hot_water
- energy_heat_burner_mt_waste_mix
- energy_heat_heatpump_water_water_mt_electricity
- energy_heat_burner_mt_coal
- energy_heat_burner_mt_network_gas
- energy_heat_burner_mt_wood_pellets
- energy_heat_burner_mt_crude_oil
- energy_heat_burner_mt_hydrogen
- energy_heat_boiler_mt_electricity
