# Dispatchable producers for hydrogen
- energy_hydrogen_storage_depleted_gas_field
- energy_hydrogen_storage_salt_cavern
- energy_hydrogen_ammonia_reformer_dispatchable
- energy_hydrogen_autothermal_reformer_dispatchable
- energy_hydrogen_steam_methane_reformer_dispatchable
