---
agriculture_non_specified_energetic_other_ghg:
  x: 1920
  "y": 6620
agriculture_non_specified_non_energetic_co2:
  x: 1920
  "y": 6680
agriculture_non_specified_non_energetic_other_ghg:
  x: 1920
  "y": 6740
buildings_non_specified_energetic_other_ghg:
  x: 1920
  "y": 6820
bunkers_international_aviation_energetic_other_ghg:
  x: 1920
  "y": 7100
bunkers_international_navigation_energetic_other_ghg:
  x: 1920
  "y": 7160
energy_ccus_non_energetic_co2:
  x: 1920
  "y": 2640
energy_chemical_fertilizers_transformation_external_coupling_node_co2:
  x: 1920
  "y": 2940
energy_chemical_other_transformation_external_coupling_node_co2:
  x: 1920
  "y": 2880
energy_chemical_refineries_transformation_external_coupling_node_co2:
  x: 1920
  "y": 2820
energy_chp_ht_wood_pellets_ccs_captured_co2:
  x: 2220
  "y": 0
energy_chp_ht_wood_pellets_ccs_co2:
  x: 2620
  "y": 0
energy_chp_ht_wood_pellets_ccs_dispatchable_co2:
  x: 2940
  "y": 60
energy_chp_ht_wood_pellets_ccs_emitted_co2:
  x: 2220
  "y": 60
energy_chp_ht_wood_pellets_ccs_must_run_co2:
  x: 2940
  "y": 0
energy_chp_mt_wood_pellets_ccs_captured_co2:
  x: 2220
  "y": 120
energy_chp_mt_wood_pellets_ccs_co2:
  x: 2620
  "y": 120
energy_chp_mt_wood_pellets_ccs_dispatchable_co2:
  x: 2940
  "y": 180
energy_chp_mt_wood_pellets_ccs_emitted_co2:
  x: 2220
  "y": 180
energy_chp_mt_wood_pellets_ccs_must_run_co2:
  x: 2940
  "y": 120
energy_chp_supercritical_ccs_ht_waste_mix_captured_co2:
  x: 2220
  "y": 1020
energy_chp_supercritical_ccs_ht_waste_mix_co2:
  x: 2620
  "y": 1020
energy_chp_supercritical_ccs_ht_waste_mix_emitted_co2:
  x: 2220
  "y": 1080
energy_chp_supercritical_ccs_mt_waste_mix_captured_co2:
  x: 2220
  "y": 900
energy_chp_supercritical_ccs_mt_waste_mix_co2:
  x: 2620
  "y": 900
energy_chp_supercritical_ccs_mt_waste_mix_emitted_co2:
  x: 2220
  "y": 960
energy_electricity_and_heat_production_energetic_other_ghg:
  x: 1920
  "y": 2400
energy_fuels_production_energetic_other_ghg:
  x: 1920
  "y": 2460
energy_fugitive_emissions_non_energetic_co2:
  x: 1920
  "y": 2520
energy_fugitive_emissions_non_energetic_other_ghg:
  x: 1920
  "y": 2580
energy_hydrogen_autothermal_reformer_ccs_captured_co2:
  x: 2220
  "y": 1520
energy_hydrogen_autothermal_reformer_ccs_emitted_co2:
  x: 2220
  "y": 1580
energy_hydrogen_autothermal_reformer_ccs_must_run_co2:
  x: 2620
  "y": 1520
energy_hydrogen_biomass_gasification_ccs_captured_co2:
  x: 2220
  "y": 1400
energy_hydrogen_biomass_gasification_ccs_co2:
  x: 2620
  "y": 1400
energy_hydrogen_biomass_gasification_ccs_emitted_co2:
  x: 2220
  "y": 1460
energy_hydrogen_captured_co2:
  x: 1920
  "y": 1400
energy_hydrogen_production_non_energetic_other_ghg:
  x: 1920
  "y": 2760
energy_hydrogen_steam_methane_reformer_ccs_captured_co2:
  x: 2220
  "y": 1280
energy_hydrogen_steam_methane_reformer_ccs_emitted_co2:
  x: 2220
  "y": 1340
energy_hydrogen_steam_methane_reformer_ccs_must_run_co2:
  x: 2620
  "y": 1280
energy_methanol_production_coal_gas_co:
  x: 1920
  "y": 3120
energy_methanol_production_non_energetic_other_ghg:
  x: 1920
  "y": 2700
energy_power_captured_co2:
  x: 1920
  "y": 440
energy_power_combined_cycle_ccs_coal_captured_co2:
  x: 2220
  "y": 380
energy_power_combined_cycle_ccs_coal_co2:
  x: 2620
  "y": 380
energy_power_combined_cycle_ccs_coal_emitted_co2:
  x: 2220
  "y": 440
energy_power_combined_cycle_ccs_network_gas_dispatchable_captured_co2:
  x: 2220
  "y": 500
energy_power_combined_cycle_ccs_network_gas_dispatchable_co2:
  x: 2620
  "y": 500
energy_power_combined_cycle_ccs_network_gas_dispatchable_emitted_co2:
  x: 2220
  "y": 560
energy_power_supercritical_ccs_waste_mix_captured_co2:
  x: 2220
  "y": 1140
energy_power_supercritical_ccs_waste_mix_co2:
  x: 2620
  "y": 1140
energy_power_supercritical_ccs_waste_mix_emitted_co2:
  x: 2220
  "y": 1200
energy_power_ultra_supercritical_ccs_coal_captured_co2:
  x: 2220
  "y": 640
energy_power_ultra_supercritical_ccs_coal_co2:
  x: 2620
  "y": 640
energy_power_ultra_supercritical_ccs_coal_emitted_co2:
  x: 2220
  "y": 700
energy_power_ultra_supercritical_oxyfuel_ccs_lignite_captured_co2:
  x: 2220
  "y": 780
energy_power_ultra_supercritical_oxyfuel_ccs_lignite_co2:
  x: 2620
  "y": 780
energy_power_ultra_supercritical_oxyfuel_ccs_lignite_emitted_co2:
  x: 2220
  "y": 840
energy_power_wood_pellets_ccs_captured_co2:
  x: 2220
  "y": 260
energy_power_wood_pellets_ccs_co2:
  x: 2620
  "y": 260
energy_power_wood_pellets_ccs_dispatchable_co2:
  x: 2940
  "y": 260
energy_power_wood_pellets_ccs_emitted_co2:
  x: 2220
  "y": 320
energy_power_wood_pellets_ccs_must_run_co2:
  x: 2940
  "y": 320
energy_production_fischer_tropsch_biogenic_waste_ccs_captured_co2:
  x: 2220
  "y": 1780
energy_production_fischer_tropsch_biogenic_waste_ccs_co2:
  x: 2620
  "y": 1780
energy_production_fischer_tropsch_biogenic_waste_ccs_emitted_co2:
  x: 2220
  "y": 1840
energy_production_fischer_tropsch_captured_co2:
  x: 1920
  "y": 1780
energy_production_fischer_tropsch_dry_biomass_ccs_captured_co2:
  x: 2220
  "y": 1900
energy_production_fischer_tropsch_dry_biomass_ccs_co2:
  x: 2620
  "y": 1900
energy_production_fischer_tropsch_dry_biomass_ccs_emitted_co2:
  x: 2220
  "y": 1960
energy_production_fischer_tropsch_non_biogenic_waste_ccs_captured_co2:
  x: 2220
  "y": 1660
energy_production_fischer_tropsch_non_biogenic_waste_ccs_co2:
  x: 2620
  "y": 1660
energy_production_fischer_tropsch_non_biogenic_waste_ccs_emitted_co2:
  x: 2220
  "y": 1720
energy_production_methanol_synthesis_biogenic_waste_ccs_captured_co2:
  x: 2220
  "y": 2020
energy_production_methanol_synthesis_biogenic_waste_ccs_co2:
  x: 2620
  "y": 2020
energy_production_methanol_synthesis_biogenic_waste_ccs_emitted_co2:
  x: 2220
  "y": 2080
energy_production_methanol_synthesis_captured_co2:
  x: 1920
  "y": 2140
energy_production_methanol_synthesis_dry_biomass_ccs_captured_co2:
  x: 2220
  "y": 2140
energy_production_methanol_synthesis_dry_biomass_ccs_co2:
  x: 2620
  "y": 2140
energy_production_methanol_synthesis_dry_biomass_ccs_emitted_co2:
  x: 2220
  "y": 2200
energy_production_methanol_synthesis_non_biogenic_waste_ccs_captured_co2:
  x: 2220
  "y": 2260
energy_production_methanol_synthesis_non_biogenic_waste_ccs_co2:
  x: 2620
  "y": 2260
energy_production_methanol_synthesis_non_biogenic_waste_ccs_emitted_co2:
  x: 2220
  "y": 2320
households_non_specified_energetic_other_ghg:
  x: 1920
  "y": 6460
industry_aluminium_non_energetic_co2:
  x: 1920
  "y": 5640
industry_aluminium_non_energetic_other_ghg:
  x: 1920
  "y": 5700
industry_chemical_other_capture_potential_co2:
  x: 2500
  "y": 4380
industry_chemical_other_captured_co2:
  x: 1920
  "y": 4380
industry_chemical_other_combustion_co2:
  x: 2940
  "y": 4380
industry_chemical_other_emitted_co2:
  x: 1920
  "y": 4540
industry_chemicals_fertilizers_capture_potential_combustion_co2:
  x: 2500
  "y": 3880
industry_chemicals_fertilizers_capture_potential_processes_co2:
  x: 2500
  "y": 4120
industry_chemicals_fertilizers_captured_co2:
  x: 1920
  "y": 3880
industry_chemicals_fertilizers_captured_combustion_co2:
  x: 2220
  "y": 3880
industry_chemicals_fertilizers_captured_processes_co2:
  x: 2220
  "y": 4120
industry_chemicals_fertilizers_combustion_co2:
  x: 2940
  "y": 3880
industry_chemicals_fertilizers_emitted_co2:
  x: 1920
  "y": 4240
industry_chemicals_fertilizers_processes_co2:
  x: 2940
  "y": 4120
industry_chemicals_non_energetic_co2:
  x: 1920
  "y": 5940
industry_chemicals_non_energetic_other_ghg:
  x: 1920
  "y": 6000
industry_chemicals_refineries_capture_potential_co2:
  x: 2500
  "y": 3580
industry_chemicals_refineries_captured_co2:
  x: 1920
  "y": 3580
industry_chemicals_refineries_combustion_co2:
  x: 2940
  "y": 3580
industry_chemicals_refineries_emitted_co2:
  x: 1920
  "y": 3740
industry_external_coupling_node_captured_co2:
  x: 1920
  "y": 3060
industry_fertilizers_non_energetic_other_ghg:
  x: 1920
  "y": 5880
industry_final_demand_for_chemical_fertilizers_coal_co2:
  x: 3440
  "y": 3940
industry_final_demand_for_chemical_fertilizers_crude_oil_co2:
  x: 3440
  "y": 4000
industry_final_demand_for_chemical_fertilizers_network_gas_co2:
  x: 3440
  "y": 3880
industry_final_demand_for_chemical_fertilizers_network_gas_non_energetic_co2:
  x: 3440
  "y": 4120
industry_final_demand_for_chemical_fertilizers_wood_pellets_co2:
  x: 3440
  "y": 4060
industry_final_demand_for_chemical_other_coal_co2:
  x: 3440
  "y": 4380
industry_final_demand_for_chemical_other_crude_oil_co2:
  x: 3440
  "y": 4440
industry_final_demand_for_chemical_other_network_gas_co2:
  x: 3440
  "y": 4500
industry_final_demand_for_chemical_other_wood_pellets_co2:
  x: 3440
  "y": 4560
industry_final_demand_for_chemical_refineries_coal_co2:
  x: 3440
  "y": 3580
industry_final_demand_for_chemical_refineries_crude_oil_co2:
  x: 3440
  "y": 3640
industry_final_demand_for_chemical_refineries_network_gas_co2:
  x: 3440
  "y": 3700
industry_final_demand_for_chemical_refineries_wood_pellets_co2:
  x: 3440
  "y": 3760
industry_final_demand_for_other_food_coal_co2:
  x: 3440
  "y": 5040
industry_final_demand_for_other_food_crude_oil_co2:
  x: 3440
  "y": 5100
industry_final_demand_for_other_food_network_gas_co2:
  x: 3440
  "y": 5160
industry_final_demand_for_other_food_wood_pellets_co2:
  x: 3440
  "y": 5220
industry_final_demand_for_other_paper_coal_co2:
  x: 3440
  "y": 4720
industry_final_demand_for_other_paper_crude_oil_co2:
  x: 3440
  "y": 4780
industry_final_demand_for_other_paper_network_gas_co2:
  x: 3440
  "y": 4840
industry_final_demand_for_other_paper_wood_pellets_co2:
  x: 3440
  "y": 4900
industry_food_non_energetic_co2:
  x: 1920
  "y": 6180
industry_food_non_energetic_other_ghg:
  x: 1920
  "y": 6240
industry_non_specified_energetic_other_ghg:
  x: 1920
  "y": 5460
industry_other_food_capture_potential_co2:
  x: 2500
  "y": 5040
industry_other_food_captured_co2:
  x: 1920
  "y": 5040
industry_other_food_combustion_co2:
  x: 2940
  "y": 5040
industry_other_food_emitted_co2:
  x: 1920
  "y": 5220
industry_other_metals_non_energetic_co2:
  x: 1920
  "y": 5760
industry_other_metals_non_energetic_other_ghg:
  x: 1920
  "y": 5820
industry_other_non_energetic_co2:
  x: 1920
  "y": 6300
industry_other_non_energetic_other_ghg:
  x: 1920
  "y": 6360
industry_other_paper_capture_potential_co2:
  x: 2500
  "y": 4720
industry_other_paper_captured_co2:
  x: 1920
  "y": 4720
industry_other_paper_combustion_co2:
  x: 2940
  "y": 4720
industry_other_paper_emitted_co2:
  x: 1920
  "y": 4900
industry_paper_non_energetic_co2:
  x: 1920
  "y": 6060
industry_paper_non_energetic_other_ghg:
  x: 1920
  "y": 6120
industry_refineries_energetic_other_ghg:
  x: 1920
  "y": 5340
industry_refineries_non_energetic_other_ghg:
  x: 1920
  "y": 5400
industry_steel_blastfurnace_bof_capture_potential_co2:
  x: 2500
  "y": 3180
industry_steel_blastfurnace_bof_captured_co2:
  x: 2220
  "y": 3180
industry_steel_blastfurnace_bof_co2:
  x: 2940
  "y": 3180
industry_steel_captured_co2:
  x: 1920
  "y": 3180
industry_steel_cyclonefurnace_bof_capture_potential_co2:
  x: 2500
  "y": 3240
industry_steel_cyclonefurnace_bof_captured_co2:
  x: 2220
  "y": 3240
industry_steel_cyclonefurnace_bof_co2:
  x: 2940
  "y": 3240
industry_steel_dri_network_gas_capture_potential_co2:
  x: 2500
  "y": 3300
industry_steel_dri_network_gas_captured_co2:
  x: 2220
  "y": 3300
industry_steel_dri_network_gas_co2:
  x: 2940
  "y": 3300
industry_steel_emitted_co2:
  x: 1920
  "y": 3500
industry_steel_external_coupling_node_capture_potential_co2:
  x: 2500
  "y": 3360
industry_steel_external_coupling_node_captured_co2:
  x: 2220
  "y": 3360
industry_steel_external_coupling_node_co2:
  x: 2940
  "y": 3360
industry_steel_non_energetic_co2:
  x: 1920
  "y": 5520
industry_steel_non_energetic_other_ghg:
  x: 1920
  "y": 5580
lulucf_emissions_non_energetic_co2:
  x: 1920
  "y": 7440
lulucf_emissions_non_energetic_other_ghg:
  x: 1920
  "y": 7500
lulucf_removals_non_energetic_co2:
  x: 1920
  "y": 7380
molecules_direct_air_capture_co2:
  x: 1920
  "y": 200
molecules_distribution_after_transport_co2:
  x: 860
  "y": 440
molecules_distribution_before_transport_co2:
  x: 1440
  "y": 440
molecules_export_co2:
  x: 1140
  "y": 280
molecules_import_co2_backup:
  x: 1920
  "y": 260
molecules_import_co2_baseload:
  x: 1920
  "y": 320
molecules_offshore_sequestration_co2:
  x: 360
  "y": 600
molecules_other_utilisation_co2:
  x: 360
  "y": 680
molecules_other_utilisation_delayed_emitted_co2:
  x: 40
  "y": 640
molecules_other_utilisation_delayed_indefinitely_co2:
  x: 40
  "y": 720
molecules_production_fischer_tropsch_synthetic_dispatchable_co2:
  x: 360
  "y": 900
molecules_production_fischer_tropsch_synthetic_must_run_co2:
  x: 360
  "y": 820
molecules_production_methanol_synthesis_synthetic_co2:
  x: 360
  "y": 500
molecules_production_methanol_synthesis_synthetic_emitted_co2:
  x: 40
  "y": 480
molecules_production_methanol_synthesis_synthetic_utilised_co2:
  x: 40
  "y": 540
molecules_transport_pipelines_co2:
  x: 1140
  "y": 380
molecules_transport_ships_co2:
  x: 1140
  "y": 480
other_indirect_emissions_non_energetic_co2:
  x: 1920
  "y": 7020
other_non_specified_energetic_other_ghg:
  x: 1920
  "y": 6960
other_other_transportation_energetic_other_ghg:
  x: 1920
  "y": 6900
transport_non_specified_energetic_other_ghg:
  x: 1920
  "y": 6540
waste_non_specified_non_energetic_co2:
  x: 1920
  "y": 7240
waste_non_specified_non_energetic_other_ghg:
  x: 1920
  "y": 7300
