# Configuration for a simple CSV file which contains residual loads based on queries.
# Each curve is output in a column, with each row containing a value for the hour.
---
- name: Electricty imbalance (MW)
  query: electricity_imbalance_inflexible_curve

- name: Heat network imbalance (MW)
  query: heat_network_imbalance_inflexible_curve

- name: Network gas imbalance (cumulative) (MW)
  query: network_gas_imbalance_cumulative_curve

- name: Hydrogen imbalance (MW)
  query: hydrogen_imbalance_inflexible_curve

- name: Network gas imbalance (smoothed) (MW)
  query: network_gas_imbalance_inflexible_smoothed_curve

- name: Hydrogen imblanace (smoothed) (MW)
  query: hydrogen_imbalance_inflexible_smoothed_curve
