# Final demand of electricity in motorcycles, based on final demand for road and share to motorcycles

- query =
    PRODUCT(
      V(transport_final_demand_for_road_electricity, demand),
      V(EDGE(transport_final_demand_for_road_electricity, transport_motorcycle_using_electricity), parent_share)
    )
- unit = MJ
