- query =
    DIVIDE(
      SUM(
        V(
          Q(power_plants_biogas),
          Q(power_plants_wood_pellets),
          output_of_electricity
        )
      ),
      BILLIONS
    )
- unit = PJ
