# Output of electricity from energy_chp_local_ht_wood_pellets_ccs_dispatchable

- query =
    DIVIDE(
      V(energy_chp_local_ht_wood_pellets_ccs_dispatchable, output_of_electricity),
      BILLIONS
    )
- unit = PJ
