# Output of electricity from energy_chp_local_mt_wood_pellets_must_run

- query =
    DIVIDE(
      V(energy_chp_local_mt_wood_pellets_must_run, output_of_electricity),
      BILLIONS
    )
- unit = PJ
