# Output of electricity from energy_power_combined_cycle_ccs_network_gas

- query =
    DIVIDE(
      V(energy_power_combined_cycle_ccs_network_gas, output_of_electricity),
      BILLIONS
    )
- unit = PJ
