# Output of electricity from energy_chp_ultra_supercritical_mt_lignite

- query =
    DIVIDE(
      V(energy_chp_ultra_supercritical_mt_lignite, output_of_electricity),
      BILLIONS
    )
- unit = PJ
