# Output of electricity from energy_chp_combined_cycle_mt_network_gas

- query =
    DIVIDE(
      V(energy_chp_combined_cycle_mt_network_gas, output_of_electricity),
      BILLIONS
    )
- unit = PJ
