# Output of electricity from energy_chp_local_ht_wood_pellets_must_run

- query =
    DIVIDE(
      V(energy_chp_local_ht_wood_pelenergy_chp_local_ht_wood_pellets_must_runlets_dispatchable, output_of_electricity),
      BILLIONS
    )
- unit = PJ
