# Output of electricity from energy_interconnector_12_imported_electricity

- query =
    DIVIDE(
      V(energy_interconnector_12_imported_electricity, output_of_electricity),
      BILLIONS
    )
- unit = PJ
