# Special conversion for biomass_products to network_gas

- query =
    SUM(
      Q(conversion_from_biodiesel_to_network_gas),
      Q(conversion_from_bio_ethanol_to_network_gas),
      Q(conversion_from_bio_kerosene_to_network_gas),
      Q(conversion_from_wood_pellets_to_network_gas),
      Q(conversion_from_bio_lng_to_network_gas),
      Q(conversion_from_greengas_to_network_gas),
      Q(conversion_from_torrefied_biomass_pellets_to_network_gas)
    )
- unit = PJ
