# Special conversion for coal_and_coal_products to network_gas

- query = 
    SUM(
      Q(conversion_from_coal_to_network_gas),
      Q(conversion_from_coal_gas_to_network_gas),
      Q(conversion_from_cokes_to_network_gas),
      Q(conversion_from_lignite_to_network_gas)
    )
- unit = PJ
