- unit = PJ
- query =
    DIVIDE(
    SUM(
    Q(electricity_produced_from_torrified_biomass_pellets),
    Q(electricity_produced_from_wood_pellets),
    Q(electricity_produced_from_bio_oil)
    )
    ,BILLIONS)
