require 'bundler'
Bundler.require(:test)

Atlas.data_dir = File.expand_path(File.dirname(__FILE__) + '/..')
I18n.enforce_available_locales = true

# A matcher which asserts the validity of a document, providing a summary of
# the validation failures if it isn't.
RSpec::Matchers.define :be_valid do
  diffable

  failure_message do |actual|
    identify_as = (@document && @document.key.inspect) || actual
    "expected that #{identify_as} would be valid"
  end

  match do |document|
    if document.valid?
      true
    else
      # Setting @actual allows "diffable" to provide meaningful messages.
      @document = document
      @actual   = document.errors.messages
      @expected = {}

      expect(document.errors.messages).to eql({})
    end
  end
end

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # Disable RSpec's output capturing, allowing `puts` to show in the terminal.
  config.before(:suite) do
    $stdout.sync = true # Ensure immediate flushing of output
  end

  config.before(:each) do
    allow($stdout).to receive(:write).and_call_original
  end

  # Existing configurations...
  config.expect_with(:rspec) { |c| c.syntax = :expect }
  config.filter_run :focus
  config.run_all_when_everything_filtered = true
  config.order = 'random'
end