# frozen_string_literal: true

require 'spec_helper'

REQUIRED_INPUTS = %i[
  external_coupling_biogenic_waste_max_demand
  external_coupling_energy_chp_supercritical_ccs_waste_mix_captured_co2
  external_coupling_energy_chp_supercritical_waste_mix_capacity
  external_coupling_energy_chp_supercritical_waste_mix_electrical_efficiency
  external_coupling_energy_chp_supercritical_waste_mix_heat_efficiency
  external_coupling_energy_distribution_coal_gas_chemical_feedstock_share
  external_coupling_energy_distribution_coal_gas_energy_production_share
  external_coupling_energy_production_synthetic_kerosene_demand
  external_coupling_energy_production_synthetic_methanol_demand
  external_coupling_industry_chemical_fertilizers_burner_coal_share
  external_coupling_industry_chemical_fertilizers_burner_crude_oil_share
  external_coupling_industry_chemical_fertilizers_burner_hydrogen_share
  external_coupling_industry_chemical_fertilizers_burner_network_gas_share
  external_coupling_industry_chemical_fertilizers_burner_wood_pellets_share
  external_coupling_industry_chemical_fertilizers_combustion_ccus_capture_potential
  external_coupling_industry_chemical_fertilizers_combustion_ccus_captured_co2
  external_coupling_industry_chemical_fertilizers_combustion_ccus_electricity_use
  external_coupling_industry_chemical_fertilizers_electricity
  external_coupling_industry_chemical_fertilizers_non_energetic_coal_share
  external_coupling_industry_chemical_fertilizers_non_energetic_crude_oil_share
  external_coupling_industry_chemical_fertilizers_non_energetic_hydrogen_share
  external_coupling_industry_chemical_fertilizers_non_energetic_network_gas_share
  external_coupling_industry_chemical_fertilizers_non_energetic_wood_pellets_share
  external_coupling_industry_chemical_fertilizers_p2h_capacity
  external_coupling_industry_chemical_fertilizers_p2h_wtp
  external_coupling_industry_chemical_fertilizers_processes_ccus_capture_potential
  external_coupling_industry_chemical_fertilizers_processes_ccus_captured_co2
  external_coupling_industry_chemical_fertilizers_processes_ccus_electricity_use
  external_coupling_industry_chemical_fertilizers_residual_heat_fixed_om_costs
  external_coupling_industry_chemical_fertilizers_residual_heat_flue_gasses_share
  external_coupling_industry_chemical_fertilizers_residual_heat_investment_costs
  external_coupling_industry_chemical_fertilizers_residual_heat_processes_share
  external_coupling_industry_chemical_fertilizers_residual_heat_technical_lifetime
  external_coupling_industry_chemical_fertilizers_residual_heat_wacc
  external_coupling_industry_chemical_fertilizers_steam_hot_water_share
  external_coupling_industry_chemical_fertilizers_total_excluding_electricity
  external_coupling_industry_chemical_fertilizers_total_useable_heat_share
  external_coupling_industry_chemical_other_burner_coal_share
  external_coupling_industry_chemical_other_burner_crude_oil_share
  external_coupling_industry_chemical_other_burner_hydrogen_share
  external_coupling_industry_chemical_other_burner_network_gas_share
  external_coupling_industry_chemical_other_burner_wood_pellets_share
  external_coupling_industry_chemical_other_ccus_capture_potential
  external_coupling_industry_chemical_other_ccus_captured_co2
  external_coupling_industry_chemical_other_ccus_electricity_use
  external_coupling_industry_chemical_other_electricity
  external_coupling_industry_chemical_other_heater_electricity_share
  external_coupling_industry_chemical_other_heatpump_water_water_electricity_share
  external_coupling_industry_chemical_other_non_energetic_coal_share
  external_coupling_industry_chemical_other_non_energetic_crude_oil_share
  external_coupling_industry_chemical_other_non_energetic_hydrogen_share
  external_coupling_industry_chemical_other_non_energetic_network_gas_share
  external_coupling_industry_chemical_other_non_energetic_wood_pellets_share
  external_coupling_industry_chemical_other_p2h_capacity
  external_coupling_industry_chemical_other_p2h_wtp
  external_coupling_industry_chemical_other_residual_heat_fixed_om_costs
  external_coupling_industry_chemical_other_residual_heat_flue_gasses_share
  external_coupling_industry_chemical_other_residual_heat_investment_costs
  external_coupling_industry_chemical_other_residual_heat_processes_share
  external_coupling_industry_chemical_other_residual_heat_technical_lifetime
  external_coupling_industry_chemical_other_residual_heat_wacc
  external_coupling_industry_chemical_other_steam_hot_water_share
  external_coupling_industry_chemical_other_steam_recompression_electricity_share
  external_coupling_industry_chemical_other_total_non_energetic
  external_coupling_industry_chemical_other_useable_heat
  external_coupling_industry_chemical_refineries_burner_coal_share
  external_coupling_industry_chemical_refineries_burner_crude_oil_share
  external_coupling_industry_chemical_refineries_burner_hydrogen_share
  external_coupling_industry_chemical_refineries_burner_network_gas_share
  external_coupling_industry_chemical_refineries_burner_wood_pellets_share
  external_coupling_industry_chemical_refineries_ccus_capture_potential
  external_coupling_industry_chemical_refineries_ccus_captured_co2
  external_coupling_industry_chemical_refineries_ccus_electricity_use
  external_coupling_industry_chemical_refineries_electricity
  external_coupling_industry_chemical_refineries_p2h_capacity
  external_coupling_industry_chemical_refineries_p2h_wtp
  external_coupling_industry_chemical_refineries_residual_heat_fixed_om_costs
  external_coupling_industry_chemical_refineries_residual_heat_flue_gasses_share
  external_coupling_industry_chemical_refineries_residual_heat_investment_costs
  external_coupling_industry_chemical_refineries_residual_heat_processes_share
  external_coupling_industry_chemical_refineries_residual_heat_technical_lifetime
  external_coupling_industry_chemical_refineries_residual_heat_wacc
  external_coupling_industry_chemical_refineries_steam_hot_water_share
  external_coupling_industry_chemical_refineries_total_non_energetic
  external_coupling_industry_chemical_refineries_transformation_crude_oil_output_share
  external_coupling_industry_chemical_refineries_transformation_diesel_output_share
  external_coupling_industry_chemical_refineries_transformation_gasoline_output_share
  external_coupling_industry_chemical_refineries_transformation_heavy_fuel_oil_output_share
  external_coupling_industry_chemical_refineries_transformation_kerosene_output_share
  external_coupling_industry_chemical_refineries_transformation_loss_output_share
  external_coupling_industry_chemical_refineries_transformation_lpg_output_share
  external_coupling_industry_chemical_refineries_transformation_refinery_gas_output_share
  external_coupling_industry_chemical_refineries_useable_heat
  external_coupling_industry_metal_steel_blastfurnace_bof_share
  external_coupling_industry_metal_steel_ccus_capture_potential
  external_coupling_industry_metal_steel_ccus_captured_co2
  external_coupling_industry_metal_steel_ccus_electricity_use
  external_coupling_industry_metal_steel_cyclonefurnace_bof_share
  external_coupling_industry_metal_steel_dri_hydrogen_share
  external_coupling_industry_metal_steel_dri_network_gas_share
  external_coupling_industry_metal_steel_efficiency
  external_coupling_industry_metal_steel_energetic_coal_gas_share
  external_coupling_industry_metal_steel_energetic_coal_share
  external_coupling_industry_metal_steel_energetic_cokes_share
  external_coupling_industry_metal_steel_energetic_crude_oil_share
  external_coupling_industry_metal_steel_energetic_electricity_share
  external_coupling_industry_metal_steel_energetic_hydrogen_share
  external_coupling_industry_metal_steel_energetic_network_gas_share
  external_coupling_industry_metal_steel_energetic_steam_hot_water_share
  external_coupling_industry_metal_steel_energetic_wood_pellets_share
  external_coupling_industry_metal_steel_external_coupling_share
  external_coupling_industry_metal_steel_fixed_om_costs
  external_coupling_industry_metal_steel_investment_costs
  external_coupling_industry_metal_steel_scrap_hbi_eaf_share
  external_coupling_industry_metal_steel_technical_lifetime
  external_coupling_industry_metal_steel_total_demand
  external_coupling_industry_metal_steel_wacc
  external_coupling_industry_other_ict_residual_heat_fixed_om_costs
  external_coupling_industry_other_ict_residual_heat_investment_costs
  external_coupling_industry_other_ict_residual_heat_technical_lifetime
  external_coupling_industry_other_ict_residual_heat_wacc
  external_coupling_molecules_other_utilisation_demand
  external_coupling_non_biogenic_waste_max_demand
  external_coupling_waste_mix_biogenic_waste_share
  external_coupling_waste_mix_non_biogenic_waste_share
]

REQUIRED_GQUERIES = %i[
]

RSpec.describe 'Validate presence of' do
  def presence_error(type, key)
    <<~ERROR
      Expected there to be #{type} called "#{key}".

      No such document was found. If the removal was intentional, one or more
      external ETM users may need to be notified of the change. If the removal
      was accidental, please add the document back to ETSource.
    ERROR
  end

  REQUIRED_INPUTS.each do |key|
    it "#{key} input" do
      expect(Atlas::Input.exists?(key)).to be(true), presence_error('an input', key)
    end
  end

  REQUIRED_GQUERIES.each do |key|
    it "#{key} gquery" do
      expect(Atlas::Gquery.exists?(key)).to be(true), presence_error('a query', key)
    end
  end
end
