# The average CO2 emission per MJ electricity produced by plants directly fed by the "Coal distribution" converters, given in KG per MJ.
# 
# This value can be used to determine the attribute of foreign_coal_electricity if exported or imported.

- unit = kg

DIVIDE(
   SUM(V(Q(electricity_producing_converters_coalbiomasslignite);primary_co2_emission)),
   SUM(V(Q(electricity_producing_converters_coalbiomasslignite);output_of_electricity))
)