# The average CO2 emission per MJ electricity produced by gas plants, given in KG per MJ. This value can be used to determine the attribute of foreign_coal_electricity if exported or imported.

- unit = kg

DIVIDE(
   SUM(V(Q(electricity_producing_converters_oil);primary_co2_emission)),
   SUM(V(Q(electricity_producing_converters_oil);output_of_electricity))
)