# co2_primary_emission_of_final_demand / co2_emission in 1990 - 1

- unit = factor

SUM(
  DIVIDE(
    SUM( V( G(final_demand_cbs); primary_co2_emission ) ),
    PRODUCT( AREA( co2_emission_1990 ), BILLIONS )
  ),
  -1
)