# This query retrieves the technical lifetime used in calculating the depreciation costs. The query is used in the ETM costs export.

- unit = year
- query =
    V(energy_distribution_ht_steam_hot_water,technical_lifetime)