- unit = PJ
- query = DIVIDE(SUM(V(buildings_lighting_standard_fluorescent_electricity,buildings_lighting_efficient_fluorescent_electricity,buildings_lighting_led_electricity,input_of_electricity)),BILLIONS)
