- query =
    SUM(
      Q(heat_infrastructure_households_mt_indoor_investment_costs),
      Q(heat_infrastructure_buildings_mt_indoor_investment_costs),
      Q(heat_infrastructure_mt_exchanger_station_investment_costs),
      Q(heat_infrastructure_mt_sub_station_investment_costs),
      Q(heat_infrastructure_mt_distribution_pipelines_investment_costs),
      Q(heat_infrastructure_mt_connection_pipelines_investment_costs),
      Q(heat_infrastructure_mt_primary_pipelines_investment_costs)
    )
- unit = euro