- query =
    SUM(
      Q(heat_infrastructure_mt_distribution_pipelines_annualised_costs),
      Q(heat_infrastructure_mt_primary_pipelines_annualised_costs),
      Q(heat_infrastructure_mt_distribution_stations_annualised_costs),
      Q(heat_infrastructure_mt_indoor_annualised_costs),
      Q(heat_infrastructure_mt_storage_annualised_costs)
      )
- unit = euro
