# Final consumption of non-renewable waste in industry ex. ict and refineries - chemicals (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Chemicals -- EG(other_chemical_industry)
# Carrier:     Non-renewable waste
# Use type:    Non-energetic -- !energetic?
#
# Exception: includes the share of non-renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_non_renewable_waste_in_industry_other_chemical_non_energetic)
