# Final consumption of electricity in industry ex. ict and refineries - chemicals (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Chemicals -- EG(other_chemical_industry)
# Carrier:     Electricity -- electricity?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_electricity_in_industry_other_chemical_non_energetic)
