:environment_air_ambient_cold:
  :co2_free: 0.0
environment_air_ambient_cold-(ambient_cold): {conversion: 1.0}
(ambient_cold)-environment_air_ambient_cold: {conversion: 1.0}

:environment_air_ambient_heat:
  :co2_free: 0.0
environment_air_ambient_heat-(ambient_heat): {conversion: 1.0}
(ambient_heat)-environment_air_ambient_heat: {conversion: 1.0}

:environment_air_wind:
  :co2_free: 0.0
environment_air_wind-(wind): {conversion: 1.0}
(wind)-environment_air_wind: {conversion: 1.0}

:environment_earth_ambient_cold:
  :co2_free: 0.0
environment_earth_ambient_cold-(ambient_cold): {conversion: 1.0}
(ambient_cold)-environment_earth_ambient_cold: {conversion: 1.0}

:environment_earth_ambient_heat:
  :co2_free: 0.0
environment_earth_ambient_heat-(ambient_heat): {conversion: 1.0}
(ambient_heat)-environment_earth_ambient_heat: {conversion: 1.0}

:environment_earth_geothermal:
  :co2_free: 0.0
environment_earth_geothermal-(geothermal): {conversion: 1.0}
(geothermal)-environment_earth_geothermal: {conversion: 1.0}

:environment_sun_solar_radiation:
  :co2_free: 0.0
environment_sun_solar_radiation-(solar_radiation): {conversion: 1.0}
(solar_radiation)-environment_sun_solar_radiation: {conversion: 1.0}

:environment_sun_solar_thermal:
  :co2_free: 0.0
environment_sun_solar_thermal-(solar_thermal): {conversion: 1.0}
(solar_thermal)-environment_sun_solar_thermal: {conversion: 1.0}

:environment_water_ambient_cold:
  :co2_free: 0.0
environment_water_ambient_cold-(ambient_cold): {conversion: 1.0}
(ambient_cold)-environment_water_ambient_cold: {conversion: 1.0}

:environment_water_water:
  :co2_free: 0.0
environment_water_water-(water): {conversion: 1.0}
(water)-environment_water_water: {conversion: 1.0}
