# Bio-footprint of sugar_beets in export

- unit = km2
- query =
    V(G(energy_export), demand_of_bio_resources_including_abroad_of(sugar_beets)).sum / V(CARRIER(sugar_beets), typical_production_per_km2)
