# Primary demand of carrier group 'dry_biomass' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_bio_resource_dry_biomass_in_export) + Q(bio_footprint_of_bio_resource_dry_biomass_in_curtailment)
