# Bio-footprint of wheat in curtailment

- unit = km2
- query =
    V(energy_flexibility_curtailment_electricity, demand_of_bio_resources_including_abroad_of(wheat)) / V(CARRIER(wheat), typical_production_per_km2)
