# Bio-footprint of waste_fats in export

- unit = km2
- query =
    V(G(energy_export), demand_of_bio_resources_including_abroad_of(waste_fats)).sum / V(CARRIER(waste_fats), typical_production_per_km2)
