# Bio-footprint of rapeseed in curtailment

- unit = km2
- query =
    V(energy_flexibility_curtailment_electricity, demand_of_bio_resources_including_abroad_of(rapeseed)) / V(CARRIER(rapeseed), typical_production_per_km2)
