# Bio-footprint of sugar_cane in export

- unit = km2
- query =
    V(G(energy_export), demand_of_bio_resources_including_abroad_of(sugar_cane)).sum / V(CARRIER(sugar_cane), typical_production_per_km2)
