# Bio-footprint of dry_biomass in export

- unit = km2
- query =
    V(G(energy_export), demand_of_bio_resources_including_abroad_of(dry_biomass)).sum / V(CARRIER(dry_biomass), typical_production_per_km2)
