# Primary demand of carrier group 'sugar_cane' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_bio_resource_sugar_cane_in_export) + Q(bio_footprint_of_bio_resource_sugar_cane_in_curtailment)
