# Primary demand of carrier group 'wheat' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_bio_resource_wheat_in_export) + Q(bio_footprint_of_bio_resource_wheat_in_curtailment)
