# Primary demand of carrier group 'waste_fats' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_bio_resource_waste_fats_in_export) + Q(bio_footprint_of_bio_resource_waste_fats_in_curtailment)
