# Bio-footprint of dry_biomass in curtailment

- unit = km2
- query =
    V(energy_flexibility_curtailment_electricity, demand_of_bio_resources_including_abroad_of(dry_biomass)) / V(CARRIER(dry_biomass), typical_production_per_km2)
