# Bio-footprint of bio-resource dry_biomass in industry sector

- unit = km2
- query =
    Q(demand_of_bio_resource_dry_biomass_in_industry)* BILLIONS / V(CARRIER(dry_biomass), typical_production_per_km2)
