# Bio-footprint of bio-resource woody_biomass in agriculture sector

- unit = km2
- query =
    Q(demand_of_bio_resource_woody_biomass_in_agriculture)* BILLIONS / V(CARRIER(woody_biomass), typical_production_per_km2)
