# Bio-footprint of bio-resource sugar_beets in agriculture sector

- unit = km2
- query =
    Q(demand_of_bio_resource_sugar_beets_in_agriculture)* BILLIONS / V(CARRIER(sugar_beets), typical_production_per_km2)
