# Bio-footprint of bio-resource waste_fats in agriculture sector

- unit = km2
- query =
    Q(demand_of_bio_resource_waste_fats_in_agriculture).sum / V(CARRIER(waste_fats), typical_production_per_km2)
