# Bio-footprint of bio-resource biogenic_waste in buildings sector

- unit = km2
- query =
    Q(demand_of_bio_resource_biogenic_waste_in_buildings).sum / V(CARRIER(biogenic_waste), typical_production_per_km2)
