# Bio-footprint of bio-resource sugar_cane in transport sector

- unit = km2
- query =
    Q(demand_of_bio_resource_sugar_cane_in_transport)* BILLIONS / V(CARRIER(sugar_cane), typical_production_per_km2)
