- deprecated_key = chart_oil_power_plants_investment_54_power_plants_474
# 

- unit = mln_euro

future:UNIT(SUM(V(Q(electricity_producing_oil_converters),"initial_investment_costs_per(converter)*crude_oil_input_conversion")),millions)