# Energetic final demand of the 'coal_and_derivatives' carrier group in buildings space_heating

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_coal_and_derivatives_in_buildings_space_heating_energetic)
    )
