# Energetic final demand of the 'oil_and_derivatives' carrier group in buildings appliances, cooling and lighting

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_oil_and_derivatives_in_buildings_appliances_energetic),
      Q(final_demand_of_oil_and_derivatives_in_buildings_cooling_energetic),
      Q(final_demand_of_oil_and_derivatives_in_buildings_lighting_energetic)
    )
