# Final consumption from industry ex. ict and refineries - steel, all carriers (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Steel -- EG(steel_industry)
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_industry_steel_energetic)
