- deprecated_key = pl_hv_net_delta_capacity_decentral
# According to John Zwaal local solar PV should not be added to decentral capacity. The impact of it on the HS net is minimal, even when introduced on a very large scale.

- unit = mw

SUM(
 V(Q(units_connected_to_mv_hv_transformer),delta_in_capacity_in_mw),
 V(agriculture_chp_engine_gas_power_fuelmix,delta_in_capacity_in_mw)
)
