- deprecated_key = pl_hv_net_delta_capacity_central
# Explanation current query:
# First MAX( - Looks at POSITIVE deltas in capacity that require net expansion
# Second MAX( - Calculates maximum import/export in MW. Subtracts 4200MW, which is current import/export capacity
# 61959/100000 is capacity factor.

- unit = mw

SUM(
   MAX(
      SUM(  
         V(Q(high_voltage_electricity_production),delta_in_capacity_in_mw)
      ),
     0
   ),
   MAX(
     SUM(
       MAX(
         V(energy_export_electricity,"demand/3600/8760/61959*100000"),
         V(energy_import_electricity,"demand/3600/8760/61959*100000")
       ),
       NEG(4200)
     ),
     0
   )
)
