# Total final demand of steam hot water and useable heat of MT temperature. Used in scenario reports.

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_mt_heat_in_agriculture),
      Q(final_demand_of_mt_heat_in_buildings),
      Q(final_demand_of_mt_heat_in_bunkers),
      Q(final_demand_of_mt_heat_in_energy),
      Q(final_demand_of_mt_heat_in_households),
      Q(final_demand_of_mt_heat_in_industry),
      Q(final_demand_of_mt_heat_in_other),
      Q(final_demand_of_mt_heat_in_transport)
    )