# Explanation current query:
# First MAX( - Looks at POSITIVE deltas in capacity that require net expansion
# Second MAX( - Looks if either the import or export of electricity is larger than the available capacity. If not returns zero
# 
# With the old query (below) if the delta in capacity of the high voltage electricity production is negative, then lots of import is possible. However this is incorrect, since interconnections need to be built regardless, meaning infrastructure costs.
# 
# Old query:
# 
# SUM(
#    V(Q(high_voltage_electricity_production);delta_in_capacity_in_mj_s),
#    V(interconnection_energy;typical_capacity_gross_in_mj_s*number_of_plants_future-4200)
# )
# 
# 
# ======
# 61959*100000=  the capacity factor

- unit = mw

SUM(
   MAX(
      SUM(  
         V(Q(high_voltage_electricity_production);delta_in_capacity_in_mw)
      ),
     0
   ),
   MAX(
     V(interconnection_energy;demand/3600/8760/61959*100000-4200),
     V(interconnection_energy;demand/3600/8760/61959*100000*-1-4200),
     0
   )
)
