# Combination of the micro CHP for hot water, the production unit and the backup burner.

- unit = converters

V(micro_chp_hot_water_households_energetic,
micro_CHP_production_households,
micro_CHP_backup_burner_households)