# Final consumption of non-renewable waste in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Non-renewable waste
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of non-renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_non_renewable_waste_in_industry_ict_energetic)
