# Final consumption of methanol in national transport (energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_methanol_in_national_transport_energetic)
