# Final consumption of methanol in agriculture (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_methanol_in_agriculture_energetic)
