# Final consumption of methanol in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_methanol_in_industry_ict_energetic)
