# Final demand of non-biogenic oil and derivatives in industry (energetic use)

- unit = PJ
- query =
    PRODUCT(
      Q(final_demand_of_oil_and_derivatives_in_industry_energetic),
      Q(share_of_non_biogenic_in_industry_final_demand_crude_oil_energetic)
    )
