# Direct conversion input of non biogenic waste for central electricity production

- query = 
    PRODUCT(
      Q(waste_mix_for_electricity_conversion),
      Q(share_of_non_biogenic_waste_in_waste_mix)
    )
- unit = PJ
