# Direct conversion input of imported hydrogen for central hydrogen production

- query =
    DIVIDE(
      SUM(
        V(
          G(hydrogen_production),
          "hydrogen_output_conversion / (1 - loss_output_conversion) * input_of_residual_hydrogen"
        )
      ), 
      BILLIONS
    )
- unit = PJ
