# Direct conversion input of non biogenic waste for central electricity production

- query = 
    DIVIDE(
      SUM(
        V(
          G(hydrogen_production),
          "hydrogen_output_conversion / (1 - loss_output_conversion) * input_of_biodiesel"
        )
      ), 
      BILLIONS
    )
- unit = PJ
