# Direct conversion input of crude oil for central hydrogen production

- query =
    DIVIDE(
      SUM(
        V(
          G(oil_and_oil_products_production),
          "oil_and_oil_products_output_conversion / (1 - loss_output_conversion) * input_of_crude_oil"
        )
      ), 
      BILLIONS
    )
- unit = PJ
