# Calculates the future total costs of electricity input for power-to-heat

- query =
    SUM(
      PRODUCT_CURVES(
        SUM_CURVES(V(INTERSECTION(G(p2h),G(other_chemical_industry)), electricity_input_curve)),
        V(CARRIER(electricity), cost_curve)
      )
    )
- unit = EUR