# Final consumption of liquid biofuels in industry ict (energetic use only).
#
# Sector:      Industry ICT -- EG(ict_industry)
# Carrier:     Liquid biofuels -- biodiesel? || bio_ethanol? || bio_kerosene? || bio_oil? || bionaphtha? || biomethanol? || bio_pyrolysis_oil? || oily_biomass? + crude_oil? x Q(share_of_biogenic_in_industry_final_demand_crude_oil_energetic)
# Use type:    Energetic -- energetic?
#
# Exception: includes the biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    Q(final_consumption_of_liquid_biofuels_in_industry_ict_energetic)
