# Total CO2 emissions incl. indirect emissions, LULUCF and international transport for 1990

- unit = mt
- query =
    SUM(
      Q(direct_emissions_energy_co2_1990),
      Q(direct_emissions_industry_co2_1990),
      Q(direct_emissions_transport_co2_1990),
      Q(direct_emissions_buildings_co2_1990),
      Q(direct_emissions_households_co2_1990),
      Q(direct_emissions_agriculture_co2_1990),
      Q(direct_emissions_other_co2_1990),
      Q(direct_emissions_lulucf_co2_1990),
      Q(direct_emissions_waste_co2_1990),
      Q(direct_emissions_bunkers_co2_1990)
    )
