# The installed production capacity in wood pellets chp dispatchable

- unit = MW
- query =
    SUM(
        Q(merit_order_wood_pellets_chp_ht_dispatchable_capacity_in_merit_order_table),
        Q(merit_order_wood_pellets_chp_mt_dispatchable_capacity_in_merit_order_table)
    )
