# The installed production capacity in lignite chp

- unit = MW
- query =
    SUM(
        Q(merit_order_lignite_chp_mt_capacity_in_merit_order_table),
        Q(merit_order_lignite_chp_ht_capacity_in_merit_order_table)
    )
