# The installed production capacity in biogas chp

- unit = MW
- query =
    SUM(
        Q(merit_order_biogas_chp_ht_capacity_in_merit_order_table),
        Q(merit_order_biogas_chp_mt_capacity_in_merit_order_table)
    )

