# The installed production capacity in waste chp ccs

- unit = MW
- query =
    SUM(
        Q(merit_order_waste_chp_ccs_ht_capacity_in_merit_order_table),
        Q(merit_order_waste_chp_ccs_mt_capacity_in_merit_order_table)
    )
