# The installed production capacity in wood pellets chp must run

- unit = MW
- query =
    SUM(
        Q(merit_order_wood_pellets_chp_ht_must_run_capacity_in_merit_order_table),
        Q(merit_order_wood_pellets_chp_mt_must_run_capacity_in_merit_order_table)
    )
