# The installed production capacity in coal chp pwd cofiring

- unit = MW
- query =
    SUM(
        Q(merit_order_coal_chp_pwd_cofiring_mt_capacity_in_merit_order_table),
        Q(merit_order_coal_chp_pwd_cofiring_ht_capacity_in_merit_order_table)
    )
