# The installed production capacity in gas chp engine

- unit = MW
- query =
    SUM(
        Q(merit_order_gas_chp_engine_mt_capacity_in_merit_order_table),
        Q(merit_order_gas_chp_engine_ht_capacity_in_merit_order_table)
    )
