# The installed production capacity in gas chp ccgt

- unit = MW
- query =
    SUM(
        Q(merit_order_gas_chp_ccgt_ht_capacity_in_merit_order_table),
        Q(merit_order_gas_chp_ccgt_mt_capacity_in_merit_order_table)
    )
