# The installed production capacity in wood pellets chp ccs dispatchable

- unit = MW
- query =
    SUM(
        Q(merit_order_wood_pellets_chp_ccs_ht_dispatchable_capacity_in_merit_order_table),
        Q(merit_order_wood_pellets_chp_ccs_mt_dispatchable_capacity_in_merit_order_table)
    )
