# Final consumption of geothermal, all sectors (non-energetic use only).
#
# Sector:      All sectors
# Carrier:     Geothermal -- geothermal?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_geothermal_non_energetic)
