
- unit = PJ
- query =
    DIVIDE(
      V(
        energy_production_pyrolysis_oil_fractionation_bio_pyrolysis_oil,
        "output_of_biodiesel + output_of_bionaphtha"
      ),
      BILLIONS
    )
