# Returns the capacity of supercritical coal plants with ccsfor the sector energy.
- query = 
        PRODUCT(
  		V(energy_power_supercritical_coal,number_of_units),
  		V(energy_power_supercritical_coal,electricity_output_capacity)	
  		)
- unit = MW

