# Returns the capacity of  supercritical cofiring coal plants for the sector energy.
- query = 
        PRODUCT(
  		V(energy_power_ultra_supercritical_cofiring_coal,number_of_units),
  		V(energy_power_ultra_supercritical_cofiring_coal,electricity_output_capacity)	
  		)
- unit = MW

