# Returns the capacity of ultra combined cycle coal plants with ccsfor the sector energy.
- query = 
        PRODUCT(
  		V(energy_chp_ultra_combined_cycle_coal,number_of_units),
  		V(energy_chp_ultra_combined_cycle_coal,electricity_output_capacity)	
  		)
- unit = MW

