# Returns the capacity of combined cycle ccs coal plants with ccs for the sector energy.
- query = 
        PRODUCT(
  		V(energy_power_combined_cycle_ccs_coal,number_of_units),
  		V(energy_power_combined_cycle_ccs_coal,electricity_output_capacity)	
  		)
- unit = MW

