- query = 
    SUM(
        Q(useful_demand_apartments_1985_2004),
        Q(useful_demand_detached_houses_1985_2004),
        Q(useful_demand_semi_detached_houses_1985_2004),
        Q(useful_demand_terraced_houses_1985_2004)
        )

- unit = PJ

