# Energetic final demand of the 'hydrogen' carrier group in households space_heating

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(space_heating_households)), "hydrogen?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
