# Energetic final demand of the 'biomass' carrier group in households space_heating

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(space_heating_households)), "biodiesel? || bio_ethanol? || wood_pellets? || bio_lng?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
