# Primary demand of carrier group 'wood' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_wood_in_export) + Q(bio_footprint_of_wood_in_curtailment)
