# Bio-footprint of bio_oil in households sector

- unit = km2
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(households)), primary_demand_of_bio_oil
    ).sum / V(CARRIER(bio_oil), typical_production_per_km2)
