# Primary demand of carrier group 'greengas' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_greengas_in_export) + Q(bio_footprint_of_greengas_in_curtailment)
