# Primary demand of carrier group 'manure' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_manure_in_export) + Q(bio_footprint_of_manure_in_curtailment)
