# Bio-footprint of manure in other sector

- unit = km2
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(other)), primary_demand_of_manure
    ).sum / V(CARRIER(manure), typical_production_per_km2)
