# Bio-footprint of wood_pellets in industry sector

- unit = km2
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(industry)), primary_demand_of_wood_pellets
    ).sum / V(CARRIER(wood_pellets), typical_production_per_km2)
