# Bio-footprint of greengas in households sector

- unit = km2
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(households)), primary_demand_of_greengas
    ).sum / V(CARRIER(greengas), typical_production_per_km2)
