# Bio-footprint of bio_kerosene in energy sector

- unit = km2
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(energy)), primary_demand_of_bio_kerosene
    ).sum / V(CARRIER(bio_kerosene), typical_production_per_km2)
