# Primary demand of carrier group 'wood_pellets' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_wood_pellets_in_export) + Q(bio_footprint_of_wood_pellets_in_curtailment)
