# Bio-footprint of biogenic_waste in curtailment

- unit = km2
- query =
    V(energy_flexibility_curtailment_electricity, primary_demand_of_biogenic_waste) / V(CARRIER(biogenic_waste), typical_production_per_km2)
