# Bio-footprint of wood_pellets in curtailment

- unit = km2
- query =
    V(energy_flexibility_curtailment_electricity, primary_demand_of_wood_pellets) / V(CARRIER(wood_pellets), typical_production_per_km2)
