# Bio-footprint of biogas in agriculture sector

- unit = km2
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(agriculture)), primary_demand_of_biogas
    ).sum / V(CARRIER(biogas), typical_production_per_km2)
