# Bio-footprint of bio_kerosene in curtailment

- unit = km2
- query =
    V(energy_flexibility_curtailment_electricity, primary_demand_of_bio_kerosene) / V(CARRIER(bio_kerosene), typical_production_per_km2)
