# Bio-footprint of greengas in agriculture sector

- unit = km2
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(agriculture)), primary_demand_of_greengas
    ).sum / V(CARRIER(greengas), typical_production_per_km2)
