# Primary demand of carrier group 'biogenic_waste' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_biogenic_waste_in_export) + Q(bio_footprint_of_biogenic_waste_in_curtailment)
