# Bio-footprint of torrified_biomass_pellets in export

- unit = km2
- query =
    V(G(energy_export), primary_demand_of_torrified_biomass_pellets).sum / V(CARRIER(torrified_biomass_pellets), typical_production_per_km2)
