# Primary demand of carrier group 'biogas' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_biogas_in_export) + Q(bio_footprint_of_biogas_in_curtailment)
