# Bio-footprint of torrified_biomass_pellets in curtailment

- unit = km2
- query =
    V(energy_flexibility_curtailment_electricity, primary_demand_of_torrified_biomass_pellets) / V(CARRIER(torrified_biomass_pellets), typical_production_per_km2)
