# Primary demand of carrier group 'bio_oil' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_bio_oil_in_export) + Q(bio_footprint_of_bio_oil_in_curtailment)
