# Bio-footprint of wood in transport sector

- unit = km2
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(transport)), primary_demand_of_wood
    ).sum / V(CARRIER(wood), typical_production_per_km2)
