# Bio-footprint of biodiesel in industry sector

- unit = km2
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(industry)), primary_demand_of_biodiesel
    ).sum / V(CARRIER(biodiesel), typical_production_per_km2)
