# Primary demand of carrier group 'corn' for the export converter group and curtailment converter

- unit = PJ
- query =
    Q(bio_footprint_of_corn_in_export) + Q(bio_footprint_of_corn_in_curtailment)
