- unit = PJ
- query =
    DIVIDE(
        SUM(
           V(
               CHILDREN(
                   V(transport_useful_demand_freight_trains)
               ),demand
           )
        ), BILLIONS
    )
