- unit = PJ
- query =
    DIVIDE(
        SUM(
           V(
               CHILDREN(
                   V(transport_useful_demand_vans)
               ),demand
           )
        ), BILLIONS
    )
