- query =
    MAX(
      SUM(
        Q(total_produced_electricity_in_source_of_heat_and_electricity_in_industry),
        - Q(chp_electricity_in_source_of_heat_and_electricity_in_industry)
      ),
      0
    )
- unit = pj
