- unit = PJ
- query =
    V(
      industry_heat_backup_burner_network_gas,
      industry_heat_burner_crude_oil,
      industry_heat_well_geothermal,
      industry_heat_burner_coal,
      industry_heat_burner_lignite,
      output_of_heat_carriers
    ).sum / BILLIONS
