- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(industry_aluminium_production)), input_of_useable_heat),
      V(CHILDREN(V(industry_other_metals_production)), input_of_useable_heat),
      V(CHILDREN(V(industry_steel_production)), input_of_useable_heat),
      V(industry_useful_demand_for_chemical_fertilizers_useable_heat, demand),
      V(industry_useful_demand_for_chemical_other_useable_heat, demand),
      V(industry_useful_demand_for_chemical_refineries_useable_heat, demand),
      V(industry_useful_demand_for_other_construction_useable_heat, demand),
      V(industry_useful_demand_for_other_food_useable_heat, demand),
      V(industry_useful_demand_for_other_machinery_useable_heat, demand),
      V(industry_useful_demand_for_other_minerals_useable_heat, demand),
      V(industry_useful_demand_for_other_mining_useable_heat, demand),
      V(industry_useful_demand_for_other_non_specified_useable_heat, demand),
      V(industry_useful_demand_for_other_paper_useable_heat, demand),
      V(industry_useful_demand_for_other_textile_useable_heat, demand),
      V(industry_useful_demand_for_other_transport_equipment_useable_heat, demand),
      V(industry_useful_demand_for_other_wood_products_useable_heat, demand)
    ) / BILLIONS
