- query =
    SUM(
      Q(heat_infrastructure_mt_main_distribution_pipelines_fixed_operation_and_maintenance_costs),
      Q(heat_infrastructure_mt_connection_pipelines_fixed_operation_and_maintenance_costs)
    )
- unit = euro