# Investment costs for this part of the heat network. Also used in the ETM costs export.

- query =
        SUM(
          Q(heat_infrastructure_mt_main_distribution_pipelines_investment_costs),
          Q(heat_infrastructure_mt_connection_pipelines_investment_costs)
          )
- unit = euro
