# Final demand of the 'geothermal' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            EG(final_demand),EG(refineries_industry)
          ),
          geothermal?
        ),
        value
      )
    ) / BILLIONS
