
- unit = MJ
- query =
    SUM(
      V(industry_final_demand_for_chemical_fertilizers_hydrogen, input_of_hydrogen),
      V(industry_final_demand_for_chemical_fertilizers_hydrogen_non_energetic, input_of_hydrogen)
    )
