# Energetic final demand of refinery gas

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              INTERSECTION(
                EG(final_demand),EG(refineries_industry)
              ),
              energetic?
            ),
            "refinery_gas?"
          ),
          value
        )
      ),
      BILLIONS
    )
