# Final consumption of solar thermal in households (energetic use only).
#
# Sector:      Households -- sector == :households
# Carrier:     Solar thermal -- solar_thermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_solar_thermal_in_households_energetic)
