# Hard-coded this for the 10 MW off-shore turbines that Over Morgen uses (ETM uses 3 MW)
- query =
    SUM(
        V(energy_power_wind_turbine_offshore, energy_hydrogen_wind_turbine_offshore, "number_of_units / 3.333333333333333")
    )

- unit = #
