# Hard-coded this for the 10 MW off-shore turbines that Over Morgen uses (ETM uses 3 MW)
- query =
    Q(factsheet_supply_electricity_from_other) * 3.0 / (V(energy_power_wind_turbine_offshore, typical_electricity_production_per_unit) * 10.0)

- unit = #