# Energetic final demand of the 'electricity' carrier group in buildings cooling

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(cooling_buildings)), "electricity?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
