# Capex for distribution pipelines for households.

- unit = euro
- query =
    SUM(
      Q(households_ht_distribution_pipelines_capital_costs),
      Q(households_ht_distribution_pipelines_depreciation_costs)
    )
