# This query retrieves the capex for insulation. The query is used in the ETM costs export.

- unit = euro
- query =
    DIVIDE(Q(costs_of_insulation_detached_houses_1965_1984),         V(households_useful_demand_for_space_heating_detached_houses_1965_1984,technical_lifetime))
    
