# Selects the heat output capacity of dispatchable waste heat sources using the heat network producing waste converters query.

- query =
    SUM(
      V(
        Q(
          heat_network_flexible_producing_waste_converters
        ),
        "input_capacity * steam_hot_water_output_conversion * number_of_units"
      )
    )
- unit = MW