# Energetic final demand of the 'natural_gas' carrier group in buildings space_heating

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_natural_gas_in_buildings_space_heating_energetic),
      Q(final_demand_of_lng_in_buildings_space_heating_energetic)
    )
