# Energetic final demand of the 'biomass_products' carrier group in buildings appliances, cooling and lighting

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_buildings_appliances_energetic),
      Q(final_demand_of_biomass_products_in_buildings_cooling_energetic),
      Q(final_demand_of_biomass_products_in_buildings_lighting_energetic),
      Q(final_demand_of_greengas_in_buildings_appliances_energetic),
      Q(final_demand_of_greengas_in_buildings_cooling_energetic),
      Q(final_demand_of_greengas_in_buildings_lighting_energetic)
    )
