# 

- deprecated_key = demand_plants_connected_to_mv_distribution_net
- unit = converters

V(
  agriculture_heatpump_water_water_ts_electricity,
  households_space_heater_collective_heatpump_water_water_ts_electricity,
  households_cooling_collective_heatpump_water_water_ts_electricity,
  buildings_space_heater_collective_heatpump_water_water_ts_electricity,
  buildings_cooling_collective_heatpump_water_water_ts_electricity,
  buildings_cooling_airconditioning,
  buildings_space_heater_electricity
)
