# 

- deprecated_key = demand_plants_connected_to_mv_distribution_net
- unit = converters

V(
  agriculture_heatpump_water_water_ts_electricity,
  households_collective_space_heater_heatpump_water_water_ts_electricity,
  households_collective_cooling_heatpump_water_water_ts_electricity,
  buildings_collective_space_heater_heatpump_water_water_ts_electricity,
  buildings_collective_cooling_heatpump_water_water_ts_electricity,
  buildings_airconditioning,
  buildings_space_heater_electricity
)
