
# 

- unit = converters

V(
  coal_pwd_energy,
  coal_pwd_ccs_energy,
  coal_conv_energy,
  coal_lignite_energy,
  coal_oxyfuel_ccs_energy,
  coal_igcc_energy,
  coal_igcc_ccs_energy,
  oil_plant_energy,
  gas_conv_energy_energetic,
  gas_ccgt_energy,
  nuclear_iii_energy,
  wind_offshore_energy,
  co_firing_coal_energy,
  hydro_mount_energy,
  coal_chp_energy,
  ccgt_ccs_energy
)