- deprecated_key = hh_heaters
# This will be the query once the graph is updated.
# 
# 
# 
# V(
#   heatpump_households_energetic,
#   electric_heater_households_energetic,
#   heatpump_addon_households_energetic
# )

- unit = converters

V(
  heatpump_households_energetic,  
  electric_heater_households_energetic,
  heatpump_addon_households_energetic
)
