- deprecated_key = hh_heaters
# This will be the query once the graph is updated.
# 
# 
# 
# V(
#   households_space_heater_heatpump_ground_water_electricity,
#   households_space_heater_electricity,
#   households_space_heater_heatpump_add_on_electricity
# )

- unit = converters

V(
  households_space_heater_heatpump_ground_water_electricity,  
  households_space_heater_electricity,
  households_space_heater_heatpump_add_on_electricity
)
