# Electricity technologies attached to the HV/MV transformer: decentral production technologies and large industrial CHPs
# Used in the network impact calculation for the HV-network and HV/MV transformer

- query =
    V(
      energy_power_geothermal,
      energy_power_hydro_river,
      energy_power_wind_turbine_coastal,
      energy_power_wind_turbine_inland,
      industry_chp_turbine_gas_power_fuelmix
    )
- unit = converters
