# Electricity technologies attached to the HV/MV transformer: decentral production technologies and large industrial CHPs
# Used in the network impact calculation for the HV-network and HV/MV transformer

- unit = converters

V(
    industry_chp_combined_cycle_gas_power_fuelmix,
    industry_chp_supercritical_wood_pellets,
    energy_power_wind_turbine_inland,
    energy_power_wind_turbine_coastal,
    energy_power_hydro_river,
    energy_power_geothermal
)
