# Electricity technologies found in buildings, agriculture, and other, as well as collective units used in households

- unit = converters

V(
    other_chp_engine_gas_power_fuelmix,
    agriculture_chp_engine_natural_gas,
    agriculture_heatpump_water_water_ts_electricity,
    households_collective_chp_network_gas,
    households_collective_chp_wood_pellets,
    buildings_space_heater_electricity,
    buildings_collective_chp_natural_gas,
    buildings_collective_chp_wood_pellets,
    buildings_space_heater_collective_heatpump_water_water_ts_electricity,
    buildings_cooling_collective_heatpump_water_water_ts_electricity,
    buildings_cooling_airconditioning,
    buildings_solar_pv_solar_radiation
)
