# Electricity technologies found in households (excluding large collective units) as well as electric vehicles

- query =
    V(
    buildings_solar_pv_solar_radiation,
    households_cooling_airconditioning_electricity,
    households_cooling_heatpump_air_water_electricity,
    households_cooling_heatpump_ground_water_electricity,
    households_solar_pv_solar_radiation,
    households_space_heater_micro_chp_network_gas,
    households_water_heater_fuel_cell_chp_network_gas,
    households_water_heater_micro_chp_network_gas,
    transport_truck_using_electricity
    )
- unit = converters
