- query =
    DIVIDE(
      SUM(
        Q(total_electricity_produced),
        V(energy_power_hv_network_shortage, demand),
        V(energy_import_electricity, demand)
      ),
      BILLIONS
    )
