- query =
    SUM(
      Q(solar_to_network_in_sankey),
      Q(wind_to_network_in_sankey),
      Q(biomass_waste_greengas_to_network_in_sankey),
      Q(other_renewables_to_network_in_sankey),
      Q(hydrogen_to_network_in_sankey),
      Q(fossil_to_network_in_sankey),
      Q(nuclear_to_network_in_sankey),
      Q(import1_to_network_in_sankey),
      Q(import2_to_network_in_sankey),
      Q(import3_to_network_in_sankey),
      Q(import4_to_network_in_sankey),
      Q(import5_to_network_in_sankey),
      Q(import6_to_network_in_sankey)
    )