- query =
    SUM(
      Q(heat_infrastructure_lt_distribution_stations_depreciation_costs),
      Q(heat_infrastructure_lt_distribution_stations_capital_costs),
      Q(heat_infrastructure_lt_sub_station_yearly_maintenance_costs),
      Q(heat_infrastructure_lt_exchanger_station_yearly_maintenance_costs)
      )
- unit = euro