# 

- unit = pj

DIVIDE(PRODUCT(V(heating_buildings_energetic;demand),V(heating_offices_current_insulation_buildings_energetic;useable_heat_share_input_link_share),Q(buildings_share_of_heat_offices)),BILLIONS)