# This query calculates the co2 emission for electricity and hydrogen export

- query = 
    SUM(
      V(energy_export_electricity,primary_co2_emission),
      V(energy_export_hydrogen_baseload,primary_co2_emission),
      V(energy_export_hydrogen_backup,primary_co2_emission),
      V(energy_export_liquid_hydrogen_baseload,primary_co2_emission),
      V(energy_export_lohc_baseload,primary_co2_emission),
      V(energy_export_ammonia_backup,primary_co2_emission),
      V(energy_export_ammonia_baseload,primary_co2_emission)
      )
    
- unit = kg
