# Includes non_energetic emissions from the fertilizer industry (SMR), non-energetic hydrogen final
# demand and non-energetic ammonia final demand via co2_emissions_primary group.
# Included non-energetic final demand of industry sector with group co2_emissions_refinery_products, corrected with free_co2_factor
# which is required with the co2_emissions_refinery_products method.

- unit = mt
- query =
    DIVIDE(
      SUM(
        V(
          INTERSECTION(
            INTERSECTION(
              G(co2_emissions_primary),
              SECTOR(industry)),
            USE(non_energetic)),
          primary_co2_emission
        ),
        V(
          INTERSECTION(
            INTERSECTION(
              G(co2_emissions_refinery_products),
              SECTOR(industry)
            ),
            USE(non_energetic)),
          "demand * weighted_carrier_co2_per_mj * (1 - free_co2_factor)"
        ),
        NEG(
          SUM(
            MV(
              MG(captured_non_energetic_emissions_industry),
              demand
            )
          )
        )
      ),
      BILLIONS
    )
