# CO2 of carrier group 'crude_oil'

- unit = tonne
- query =
    SUM(
      V(G(co2_emissions_primary),primary_demand_of_crude_oil).sum * V(CARRIER(crude_oil), co2_per_mj),
      V(G(co2_emissions_refinery_products),"demand * weighted_carrier_co2_per_mj")
    ) / THOUSANDS