# How much Mt CO2 is emitted yearly by the transport sector
# Used in transportation education module

- query =
    DIVIDE(
      SUM(
        V(
          INTERSECTION(G(co2_emissions_primary), SECTOR(transport)),
          primary_co2_emission
        ),
        V(
          INTERSECTION(G(co2_emissions_refinery_products), SECTOR(transport)),
          "demand * weighted_carrier_co2_per_mj"
        )
      ),
      BILLIONS
    )
- unit = mt
