# Total net CO2 emissions

- query =
    SUM(
      Q(primary_co2_emission_of_agriculture),
      Q(primary_co2_emission_of_buildings),
      Q(primary_co2_emission_of_bunkers),
      Q(primary_co2_emission_of_energy),
      Q(primary_co2_emission_of_households),
      Q(primary_co2_emission_of_industry),
      Q(primary_co2_emission_of_non_energetic),
      Q(primary_co2_emission_of_delayed_emissions),
      Q(primary_co2_emission_of_other),
      Q(primary_co2_emission_of_transport)
    )
- unit = mt
