# The average CO2 emission per MJ electricity produced by waste plants, given in KG per MJ. This value can be used to determine the attribute of foreign_waste_electricity if exported or imported.

- unit = factor

DIVIDE(
   SUM(V(Q(electricity_producing_converters_waste);sustainability_share * demand)),
   SUM(V(Q(electricity_producing_converters_waste);demand))
)