# The average CO2 emission per MJ electricity produced by nuclear plants, given in KG per MJ. This value can be used to determine the attribute of foreign_nuclear_electricity if exported or imported.

- unit = factor

DIVIDE(
   SUM(V(Q(electricity_producing_converters_uranium);sustainability_share * demand)),
   SUM(V(Q(electricity_producing_converters_uranium);demand))
)
