# Direct conversion input of lignite for central heat production

- query =
    DIVIDE(
      SUM(
        V(
          G(heat_production),
          "steam_hot_water_output_conversion / (1 - loss_output_conversion) * input_of_lignite"
        )
      ), 
      BILLIONS
    )
- unit = PJ
