# Direct conversion input of oil and oil products for central heat production

- query = 
    SUM(
      Q(conversion_from_crude_oil_to_heat),
      Q(conversion_from_gasoline_to_heat),
      Q(conversion_from_diesel_to_heat),
      Q(conversion_from_lpg_to_heat),
      Q(conversion_from_kerosene_to_heat),
      Q(conversion_from_heavy_fuel_oil_to_heat),
    )
- unit = PJ
