# Direct conversion input of non bio ethanol for central heat production

- query = 
    DIVIDE(
      SUM(
        V(
          G(heat_production),
          "steam_hot_water_output_conversion / (1 - loss_output_conversion) * input_of_bio_ethanol"
        )
      ), 
      BILLIONS
    )
- unit = PJ
