# Direct conversion input of network gas for central heat production

- query =
    SUM(
      DIVIDE(
        SUM(
          V(
            G(heat_production),
            "steam_hot_water_output_conversion / (steam_hot_water_output_conversion + electricity_output_conversion) * input_of_network_gas"
          ),
        ),
        BILLIONS
      ),
        PRODUCT(
            Q(conversion_from_gas_power_fuelmix_to_heat),
            V(energy_mixer_for_gas_power_fuel, network_gas_input_conversion)
          ),
        Q(conversion_from_compressed_network_gas_to_heat)
      )
- unit = PJ
