# Direct conversion input of network gas for central heat production

- query =
    SUM(
      DIVIDE(
        SUM(
          V(
            INTERSECTION(G(heat_production),G(electricity_production)),
            "steam_hot_water_output_conversion / (1 - loss_output_conversion) * input_of_network_gas"
          ),
          V(
            FILTER(
            EXCLUDE(G(heat_production),G(electricity_production)),
            "steam_hot_water_output_conversion > 0.0"),
            "input_of_network_gas"
          ),
        ),
        BILLIONS
      ),
        PRODUCT(
            Q(conversion_from_gas_power_fuelmix_to_heat),
            V(energy_mixer_for_gas_power_fuel, network_gas_input_conversion)
          ),
        Q(conversion_from_compressed_network_gas_to_heat)
      )
- unit = PJ
