# Direct conversion input of coal and coal products for central heat production

- query = 
    SUM(
      Q(conversion_from_coal_to_heat),
      Q(conversion_from_coal_gas_to_heat),
      Q(conversion_from_cokes_to_heat),
      Q(conversion_from_lignite_to_heat)
    )
- unit = PJ
