# Direct conversion input of biomass for central heat production

- query =
    SUM(
      Q(conversion_from_biodiesel_to_heat),
      Q(conversion_from_bio_ethanol_to_heat),
      Q(conversion_from_bio_kerosene_to_heat),
      Q(conversion_from_bio_oil_to_heat),
      Q(conversion_from_wood_pellets_to_heat),
      Q(conversion_from_bio_lng_to_heat),
      PRODUCT(
        Q(conversion_from_gas_power_fuelmix_to_heat),
        V(energy_mixer_for_gas_power_fuel, bio_oil_input_conversion)
      ),
      Q(conversion_from_bio_pyrolysis_unused_steam_hot_water_to_heat)
    )
- unit = PJ
