# Unused steam hot water from pyrolysis to heat

- query =
    DIVIDE(
      V(
        energy_production_pyrolysis_locally_available_steam_hot_water_unused,
        demand
      ),
      BILLIONS
    )
- unit = PJ
