# Direct conversion input of biomass for crude oil production

- query = 
    DIVIDE(
      SUM( 
        V(industry_final_demand_crude_oil_non_energetic,primary_demand_of_sustainable),
        V(industry_final_demand_crude_oil,primary_demand_of_sustainable)
      ),
      BILLIONS
    )

- unit = PJ
