# Use of carrier group 'ambient' in other industry heat

- unit = pj
- query =
    SUM(
      V(CHILDREN(V(industry_useful_demand_useable_heat)),input_of_ambient_heat),
      V(CHILDREN(V(industry_useful_demand_useable_heat)),input_of_ambient_cold)
    ) / BILLIONS
