# Use of carrier group 'coal_and_derivatives' in other industry heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(industry_useful_demand_useable_heat)),input_of_coal),
      V(CHILDREN(V(industry_useful_demand_useable_heat)),input_of_coal_gas)
    ) / BILLIONS
