# Group for employment project

- query =
    V(
      buildings_chp_engine_biogas,
      buildings_collective_geothermal,
      buildings_collective_chp_network_gas,
      buildings_collective_chp_wood_pellets,
      buildings_cooling_airconditioning_electricity,
      buildings_cooling_collective_heatpump_water_water_ts_electricity,
      buildings_cooling_heatpump_air_water_network_gas,
      buildings_solar_pv_solar_radiation,
      buildings_space_heater_coal,
      buildings_space_heater_collective_heatpump_water_water_ts_electricity,
      buildings_space_heater_crude_oil,
      buildings_space_heater_electricity,
      buildings_space_heater_heatpump_air_water_network_gas,
      buildings_space_heater_network_gas,
      buildings_space_heater_solar_thermal,
      buildings_space_heater_wood_pellets,
      energy_chp_combined_cycle_network_gas,
      energy_chp_ultra_supercritical_coal,
      energy_chp_ultra_supercritical_cofiring_coal,
      energy_chp_ultra_supercritical_lignite,
      energy_power_combined_cycle_ccs_coal,
      energy_power_combined_cycle_ccs_network_gas,
      energy_power_combined_cycle_coal,
      energy_power_combined_cycle_network_gas,
      energy_power_engine_network_gas,
      energy_power_geothermal,
      energy_power_nuclear_gen3_uranium_oxide,
      energy_power_solar_pv_solar_radiation,
      energy_power_supercritical_coal,
      energy_power_supercritical_waste_mix,
      energy_power_turbine_network_gas,
      energy_power_ultra_supercritical_ccs_coal,
      energy_power_ultra_supercritical_coal,
      energy_power_ultra_supercritical_cofiring_coal,
      energy_power_ultra_supercritical_crude_oil,
      energy_power_ultra_supercritical_network_gas,
      energy_power_ultra_supercritical_lignite,
      energy_power_ultra_supercritical_oxyfuel_ccs_lignite,
      energy_power_wind_turbine_coastal,
      energy_power_wind_turbine_inland,
      energy_power_wind_turbine_offshore,
      households_collective_geothermal,
      households_collective_chp_biogas,
      households_collective_chp_network_gas,
      households_collective_chp_wood_pellets,
      households_cooling_airconditioning_electricity,
      households_cooling_heatpump_air_water_electricity,
      households_cooling_heatpump_ground_water_electricity,
      households_solar_pv_solar_radiation,
      households_space_heater_coal,
      households_space_heater_heatpump_air_water_electricity,
      households_space_heater_combined_network_gas,
      households_space_heater_crude_oil,
      households_space_heater_electricity,
      households_space_heater_heatpump_add_on_electricity,
      households_space_heater_heatpump_ground_water_electricity,
      households_space_heater_micro_chp_network_gas,
      households_space_heater_network_gas,
      households_space_heater_wood_pellets,
      households_water_heater_coal,
      households_water_heater_combined_network_gas,
      households_water_heater_crude_oil,
      households_water_heater_fuel_cell_chp_network_gas,
      households_water_heater_heatpump_air_water_electricity,
      households_water_heater_heatpump_ground_water_electricity,
      households_water_heater_micro_chp_network_gas,
      households_water_heater_network_gas,
      households_water_heater_resistive_electricity,
      households_water_heater_solar_thermal,
      households_water_heater_wood_pellets
    )
- unit = converters
