# The total man-years spent in NL on insulation of old houses.

- unit = man_years
- query = 
    AREA(old_houses_insulation_employment_constant) * Q(costs_of_insulation_old_residences) / AREA(man_hours_per_man_year)