# The total man-year spent in NL on removal.

- query =
    PRODUCT(
    	DIVIDE(
    		SUM(
    			V(Q(employment_converters),"(hours_remov_nl*number_of_units).to_f/technical_lifetime")
    		),
    		AREA(man_hours_per_man_year)
    	),
    	AREA(economic_multiplier)
    )
- unit = man_years
