# The total man-years spent in NL on insulation.

- unit = man_years
- query =
    PRODUCT(
        SUM(
        Q(insulation_all_houses_employment),
        Q(insulation_buildings_employment)
	   ),
	   AREA(economic_multiplier)
    ) / V(households_space_heating_savings_from_insulation, technical_lifetime)
