# Direct conversion input of biomass_products for biofuels
#

- query =
    SUM(
      Q(conversion_from_biogenic_waste_to_biofuels),
      Q(conversion_from_oily_biomass_to_biofuels),
      Q(conversion_from_dry_biomass_to_biofuels),
      Q(conversion_from_wet_biomass_to_biofuels)
    )  
- unit = PJ
