- query =
    SUM_CURVES(
      Q(energy_power_wind_turbine_offshore_output_curve),
      Q(energy_power_solar_pv_offshore_output_curve),
      Q(energy_power_hybrid_wind_turbine_offshore_output_curve)
    )
- unit = curve
