# Carrier group of biomass products

- query = CARRIER(greengas, biodiesel, bio_ethanol, bio_oil, biogas, torrified_biomass_pellets, wood_pellets, corn, manure, bio_residues_for_firing, biogenic_waste)
- unit =
