# Carrier group of biomass products

- query = CARRIER(greengas, biodiesel, bio_ethanol, bio_oil, biogas, torrified_biomass_pellets, wood_pellets, corn, manure, woody_biomass, biogenic_waste)
- unit =
