# Apartment blocks require indoor investment costs
# These costs depend on whether an apartment block has a collective heating system ('block heating')
# Or individual heating per apartment

- query =
      apartments_with_block_heating =  Q(apartments_with_lt_district_heating) * AREA(heat_share_of_apartments_with_block_heating);

      apartments_with_block_heating * AREA(heat_infrastructure_households_lt_indoor_investment_costs_apartments_with_block_heating_eur)
- unit = euro
