- deprecated_key = chart_collective_chp_s_5_electricity_production_households_625
#

- unit = pj

DIVIDE(SUM(V(households_collective_chp_network_gas,households_collective_chp_wood_pellets,output_of_electricity)),BILLIONS)
