# Used for the network investment needed popup
# Temporarily set this gquery to 1, because Q(yearly_investment_costs_of_lv_grid),
# Q(yearly_investment_costs_of_mv_grid) and Q(yearly_investment_costs_of_hv_grid) are
# gqueries from the old network calculation. These need to be updated with new ones. 

- query = 1
#    GREATER(
#        SUM(
#            Q(yearly_investment_costs_of_lv_grid),
#            Q(yearly_investment_costs_of_mv_grid),
#            Q(yearly_investment_costs_of_hv_grid)
#        ),
#        0
#    )
- unit = boolean
- deprecated_key = pl_network_investment_needed_check
