# The total related CO2 of all the imported electricity is calculated here.

- query =
    PRODUCT(
      V(CARRIER(imported_electricity), co2_conversion_per_mj),
      MJ_PER_KWH * THOUSANDS
    )
- unit = gCO2/kWh
- deprecated_key = co2_emission_electricity_import
