# import - export: so import is positive and export negative

- query =
    SUM(
     Q(co2_emissions_of_imported_electricity),
     NEG(Q(co2_emissions_of_exported_electricity))
    )
- unit = kg
- deprecated_key = co2_emission_electricity_net_import_export
