# Take note: The imported electricity is not included in
# co2_emissions_of_final_demand_excluding_imported_electricity because it is
# assigned no CO2 emission as primary carrier. This is standard, because CO2
# emissions are not standard calculated for import yet!

- query = V(G(final_demand_cbs),primary_co2_emission).sum
- unit = kg
- deprecated_key = co2_emission_excl_electricity_import
