# This query calculates the co2 emission for electricity and hydrogen export

- query = V(energy_export_electricity,primary_co2_emission)
- unit = kg
- deprecated_key = co2_emission_electricity_export