- query =
    SUM(
      (INPUT_VALUE(bunkers_allocated_percentage_shipping) / 100.0) * AREA(co2_emission_1990_marine_bunkers),
      (INPUT_VALUE(bunkers_allocated_percentage_aviation) / 100.0) * AREA(co2_emission_1990_aviation_bunkers)
    )
- unit = kg
