- deprecated_key = co2_emission_excl_electricity_import
# This is standard, because CO2 emissions are not standard calculated for import yet!

- unit = kg

SUM(V(
  G(final_demand_cbs);primary_co2_emission
))