- unit = tonne
- query =
    SUM(
      V(industry_final_demand_coal, "weighted_carrier_co2_per_mj * demand * free_co2_factor"),
      V(industry_final_demand_crude_oil, "weighted_carrier_co2_per_mj * demand * free_co2_factor"),
      V(industry_final_demand_network_gas, "weighted_carrier_co2_per_mj * demand * free_co2_factor"),
      V(industry_final_demand_wood_pellets, "weighted_carrier_co2_per_mj * demand * free_co2_factor"),
      V(industry_final_demand_coal_gas, "weighted_carrier_co2_per_mj * demand * free_co2_factor"),
      V(industry_chp_combined_cycle_gas_power_fuelmix, "weighted_carrier_co2_per_mj * demand * free_co2_factor"),
      V(industry_chp_engine_gas_power_fuelmix, "weighted_carrier_co2_per_mj * demand * free_co2_factor"),
      V(industry_chp_turbine_gas_power_fuelmix, "weighted_carrier_co2_per_mj * demand * free_co2_factor"),
      V(industry_chp_ultra_supercritical_coal, "weighted_carrier_co2_per_mj * demand * free_co2_factor"),
      V(energy_steel_hisarna_transformation_coal, "weighted_carrier_co2_per_mj * demand * free_co2_factor")
    ) / THOUSANDS
