- query =
    SUM(
      V(industry_final_demand_for_chemical_fertilizers_network_gas_non_energetic,industry_final_demand_for_chemical_fertilizers_hydrogen_non_energetic,
      primary_co2_emission)
    ) / THOUSANDS
- unit = T
