# CO2 of carrier group 'imported_electricity' for the export converter group

- unit = tonne
- query =
        imported_electricity = G(energy_export).select { |node| node.query.input_of_imported_electricity > 0 };

        SUM(
            V(imported_electricity, "imported_electricity_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")
        ) / THOUSANDS
    