# CO2 of carrier group 'natural_gas_and_derivatives' in transport

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(transport)).select {|node| node.output_slots.detect { |slot| slot.carrier.network_gas? }}, primary_co2_emission)      
    ) / THOUSANDS
