# CO2 of carrier group 'electricity' in buildings

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(buildings)).select {|node| node.slots.detect { |slot| slot.carrier.electricity? }}, primary_co2_emission)      
    ) / THOUSANDS
