# CO2 of carrier group 'solar' in other

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(other)).select {|node| node.output_slots.detect { |slot| slot.carrier.solar_radiation? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),SECTOR(other)).select {|node| node.output_slots.detect { |slot| slot.carrier.solar_thermal? }}, primary_co2_emission)      
    ) / THOUSANDS
