# CO2 of carrier group 'oil_and_derivatives' in industry

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(co2_emissions_primary),SECTOR(industry)).select {|node| node.input_slots.detect { |slot| slot.carrier.crude_oil? }}, "crude_oil_input_conversion * primary_co2_emission"),
      SUM(
        V( INTERSECTION(G(co2_emissions_refinery_products), SECTOR(industry)), "demand * weighted_carrier_co2_per_mj")
      )
    ) / THOUSANDS