# CO2 of carrier group 'waste' in curtailment converter

- unit = tonne
- query =
    SUM(
      V(V(energy_flexibility_curtailment_electricity).select {|node| node.input_slots.detect { |slot| slot.carrier.waste_mix? }}, "waste_mix_input_conversion * primary_co2_emission"),
      V(V(energy_flexibility_curtailment_electricity).select {|node| node.input_slots.detect { |slot| slot.carrier.non_biogenic_waste? }}, "non_biogenic_waste_input_conversion * primary_co2_emission"),
      V(V(energy_flexibility_curtailment_electricity).select {|node| node.input_slots.detect { |slot| slot.carrier.biogenic_waste? }}, "biogenic_waste_input_conversion * primary_co2_emission")
    ) / THOUSANDS
