# CO2 of carrier group 'hydrogen' in buildings

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(co2_emissions_primary),SECTOR(buildings)).select {|node| node.input_slots.detect { |slot| slot.carrier.hydrogen? }}, "hydrogen_input_conversion * primary_co2_emission")
    ) / THOUSANDS
