# CO2 of carrier group 'electricity' in households

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(co2_emissions_primary),SECTOR(households)).select {|node| node.input_slots.detect { |slot| slot.carrier.electricity? }}, "electricity_input_conversion * primary_co2_emission")
    ) / THOUSANDS
