# CO2 of industry sector; the CO2 of the industry sector is reduced by CO and CO2 that is captured and
# turned into synthetic kerosene

- unit = kg
- query =
    SUM(
      SUM(
        V(INTERSECTION(G(final_demand_group),SECTOR(industry)), primary_co2_emission)
      ) / BILLIONS,
      NEG(
        MIN(
          Q(point_source_co_used),
          Q(point_source_co_available)
        ) * INPUT_VALUE(flexibility_p2l_co2_reduction_industry) / 100.0 * 44 / 28
      ),
      NEG(
        MIN(
          Q(point_source_co2_used),
          Q(point_source_co2_available)
        ) * INPUT_VALUE(flexibility_p2l_co2_reduction_industry) / 100.0
      )
    )
