# CO2 of carrier group 'ambient' in buildings

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(buildings)).select {|node| node.slots.detect { |slot| slot.carrier.ambient_heat? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),SECTOR(buildings)).select {|node| node.slots.detect { |slot| slot.carrier.ambient_cold? }}, primary_co2_emission)      
    ) / THOUSANDS
