# CO2 of carrier group 'nuclear' in curtailment converter

- unit = tonne
- query =
    SUM(
      V(V(energy_flexibility_curtailment_electricity).select {|node| node.input_slots.detect { |slot| slot.carrier.uranium_oxide? }}, "uranium_oxide_input_conversion * primary_co2_emission")
    ) / THOUSANDS
