# How much Mt CO2 is emitted yearly by the buildings sector 
# Used in education module about the future home, heat and insulation

- query = V( INTERSECTION(G(final_demand_group), SECTOR(buildings)), primary_co2_emission).sum / BILLIONS
- unit = mt