# CO2 of carrier group 'geothermal' for the export converter group

- unit = tonne
- query =
        geothermal = G(energy_export).select { |node| node.query.input_of_geothermal > 0 };

        SUM(
            V(geothermal, "geothermal_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")
        ) / THOUSANDS
    