# CO2 of carrier group 'ambient' in agriculture

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(agriculture)).select {|node| node.input_slots.detect { |slot| slot.carrier.ambient_heat? }}, "ambient_heat_input_conversion * primary_co2_emission"),
      V(INTERSECTION(G(final_demand_group),SECTOR(agriculture)).select {|node| node.input_slots.detect { |slot| slot.carrier.ambient_cold? }}, "ambient_cold_input_conversion * primary_co2_emission")      
    ) / THOUSANDS
