# CO2 of carrier group 'solar' for the export converter group

- unit = tonne
- query =
        solar_radiation = G(energy_export).select { |node| node.query.input_of_solar_radiation > 0 };
        solar_thermal = G(energy_export).select { |node| node.query.input_of_solar_thermal > 0 };

        SUM(
            V(solar_radiation, "solar_radiation_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(solar_thermal, "solar_thermal_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")
        ) / THOUSANDS
    