# Primary CO2 of final demand for oil, gas and coal

- unit = tonne
- query =
    SUM(
        Q(primary_co2_of_oil_and_derivatives),
        Q(primary_co2_of_natural_gas_and_derivatives),
        Q(primary_co2_of_coal_and_derivatives)
    )