# CO2 of carrier group 'natural_gas_and_derivatives' for the export converter group

- unit = tonne
- query =
        natural_gas = G(energy_export).select { |node| node.query.input_of_natural_gas > 0 };
        lng = G(energy_export).select { |node| node.query.input_of_lng > 0 };
        network_gas = G(energy_export).select { |node| node.query.input_of_network_gas > 0 };
        gas_power_fuelmix = G(energy_export).select { |node| node.query.input_of_gas_power_fuelmix > 0 };
        compressed_network_gas = G(energy_export).select { |node| node.query.input_of_compressed_network_gas > 0 };

        SUM(
            V(natural_gas, "natural_gas_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(lng, "lng_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(network_gas, "network_gas_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(gas_power_fuelmix, "gas_power_fuelmix_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(compressed_network_gas, "compressed_network_gas_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")
        ) / THOUSANDS
    