# How much Mt CO2 is emitted yearly by the transport sector
# Used in transportation education module

- query = V( INTERSECTION(G(final_demand_cbs), SECTOR(transport)), primary_co2_emission).sum / 1000000000
- unit = mt