# CO2 of carrier group 'electricity' in energy

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(energy)).select {|node| node.input_slots.detect { |slot| slot.carrier.electricity? }}, "electricity_input_conversion * primary_co2_emission")      
    ) / THOUSANDS
