# CO2 of carrier group 'waste' for the export converter group

- unit = tonne
- query =
        waste_mix = G(energy_export).select { |node| node.query.input_of_waste_mix > 0 };
        non_biogenic_waste = G(energy_export).select { |node| node.query.input_of_non_biogenic_waste > 0 };
        biogenic_waste = G(energy_export).select { |node| node.query.input_of_biogenic_waste > 0 };

        SUM(
            V(waste_mix, "waste_mix_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(non_biogenic_waste, "non_biogenic_waste_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(biogenic_waste, "biogenic_waste_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")
        ) / THOUSANDS
    