# Primary CO2 of carrier group 'solar' for the export converter group and curtailment converter

- unit = tonne
- query =
    Q(primary_co2_of_solar_in_export) + Q(primary_co2_of_solar_in_curtailment)
