# CO2 of carrier group 'coal_and_derivatives' for the export converter group

- unit = tonne
- query =
        coal = G(energy_export).select { |node| node.query.input_of_coal > 0 };
        lignite = G(energy_export).select { |node| node.query.input_of_lignite > 0 };
        coal_gas = G(energy_export).select { |node| node.query.input_of_coal_gas > 0 };
        cokes = G(energy_export).select { |node| node.query.input_of_cokes > 0 };

        SUM(
            V(coal, "coal_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(lignite, "lignite_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(coal_gas, "coal_gas_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(cokes, "cokes_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")
        ) / THOUSANDS
    