# CO2 of carrier group 'electricity' for the export converter group

- unit = tonne
- query =
        electricity = G(energy_export).select { |node| node.query.input_of_electricity > 0 };

        SUM(
            V(electricity, "electricity_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")
        ) / THOUSANDS
    