# Primary CO2 of carrier group 'ambient' for the export converter group and curtailment converter

- unit = tonne
- query =
    Q(primary_co2_of_ambient_in_export) + Q(primary_co2_of_ambient_in_curtailment)
