# CO2 of carrier group 'nuclear' for the export converter group

- unit = tonne
- query =
        uranium_oxide = G(energy_export).select { |node| node.query.input_of_uranium_oxide > 0 };

        SUM(
            V(uranium_oxide, "uranium_oxide_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")
        ) / THOUSANDS
    