# CO2 of carrier group 'biomass_products' in buildings

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(buildings)).select {|node| node.slots.detect { |slot| slot.carrier.biodiesel? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),SECTOR(buildings)).select {|node| node.slots.detect { |slot| slot.carrier.bio_ethanol? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),SECTOR(buildings)).select {|node| node.slots.detect { |slot| slot.carrier.wood_pellets? }}, primary_co2_emission)      
    ) / THOUSANDS
