# CO2 of carrier group 'oil_and_derivatives' in households

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(households)).select {|node| node.output_slots.detect { |slot| slot.carrier.crude_oil? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),SECTOR(households)).select {|node| node.output_slots.detect { |slot| slot.carrier.gasoline? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),SECTOR(households)).select {|node| node.output_slots.detect { |slot| slot.carrier.diesel? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),SECTOR(households)).select {|node| node.output_slots.detect { |slot| slot.carrier.lpg? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),SECTOR(households)).select {|node| node.output_slots.detect { |slot| slot.carrier.kerosene? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),SECTOR(households)).select {|node| node.output_slots.detect { |slot| slot.carrier.heavy_fuel_oil? }}, primary_co2_emission)      
    ) / THOUSANDS
