# CO2 of carrier group 'geothermal' in energy

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(energy)).select {|node| node.slots.detect { |slot| slot.carrier.geothermal? }}, primary_co2_emission)      
    ) / THOUSANDS
