# CO2 of carrier group 'solar' in transport

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),SECTOR(transport)).select {|node| node.input_slots.detect { |slot| slot.carrier.solar_radiation? }}, "solar_radiation_input_conversion * primary_co2_emission"),
      V(INTERSECTION(G(final_demand_group),SECTOR(transport)).select {|node| node.input_slots.detect { |slot| slot.carrier.solar_thermal? }}, "solar_thermal_input_conversion * primary_co2_emission")      
    ) / THOUSANDS
