# CO2 of carrier group 'heat' for the export converter group

- unit = tonne
- query =
        steam_hot_water = G(energy_export).select { |node| node.query.input_of_steam_hot_water > 0 };
        useable_heat = G(energy_export).select { |node| node.query.input_of_useable_heat > 0 };

        SUM(
            V(steam_hot_water, "steam_hot_water_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
            V(useable_heat, "useable_heat_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")
        ) / THOUSANDS
    