# Returns the produced electricity from hybrid offshore wind to curtailment.

- unit = PJ
- query =
    DIVIDE(
      V(energy_power_hybrid_curtailed_electricity, input_of_electricity),
      BILLIONS
    )
