# investment costs of agriculture_burner_hydrogen IF newly built (green field approach)

- query =
    QUERY_DELTA( -> {
       V(agriculture_burner_hydrogen,total_investment_over_lifetime_per(:converter))
    }) / BILLIONS
- unit = euro
