# investment costs of buildings_space_heater_heatpump_air_water_electricity IF newly built (green field approach)

- query = present:V(buildings_space_heater_heatpump_air_water_electricity, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
