# investment costs of buildings_space_heater_electricity IF newly built (green field approach)

- query = future:V(buildings_space_heater_electricity, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
