# investment costs of bunkers_kerosene_production_p2l IF newly built (green field approach)

- query = future:V(bunkers_kerosene_production_p2l, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
