# investment costs of bunkers_kerosene_production_p2l IF newly built (green field approach)

- query =
    QUERY_DELTA( -> {
       V(bunkers_kerosene_production_p2l,total_investment_over_lifetime_per(:converter))
    }) / BILLIONS
- unit = euro
