# investment costs of energy_flexibility_hv_opac_electricity IF newly built (green field approach)

- query = present:V(energy_flexibility_hv_opac_electricity, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
