# investment costs of energy_heat_solar_thermal IF newly built (green field approach)

- query = future:V(energy_heat_solar_thermal, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
