# investment costs of energy_heat_boiler_electricity IF newly built (green field approach)

- query = present:V(energy_heat_boiler_electricity, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
