# investment costs of energy_chp_local_wood_pellets IF newly built (green field approach)

- query = future:V(energy_chp_local_wood_pellets, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
