# investment costs of energy_production_synthetic_kerosene IF newly built (green field approach)

- query = future:V(energy_production_synthetic_kerosene, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
