# investment costs of energy_chp_local_engine_biogas IF newly built (green field approach)

- query = future:V(energy_chp_local_engine_biogas, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
