# investment costs of energy_power_wind_turbine_inland IF newly built (green field approach)

- query = future:V(energy_power_wind_turbine_inland, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
