# investment costs of energy_production_synthetic_kerosene_must_run IF newly built (green field approach)

- query = future:V(energy_production_synthetic_kerosene_must_run, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
