# investment costs of energy_heat_burner_hydrogen IF newly built (green field approach)

- query = present:V(energy_heat_burner_hydrogen, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
