# investment costs of households_collective_geothermal IF newly built (green field approach)

- query = future:V(households_collective_geothermal, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
