# investment costs of industry_chemicals_other_heatpump_water_water_electricity IF newly built (green field approach)

- query = present:V(industry_chemicals_other_heatpump_water_water_electricity, total_investment_over_lifetime_per(:converter)) / BILLIONS
- unit = euro
