# investment costs of industry_steel_hisarna_bof_captured_co2 IF newly built (green field approach)

- query = present:MV(industry_steel_hisarna_bof_captured_co2, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
