# investment costs of industry_chemicals_refineries_flexibility_p2h_network_gas_electricity IF newly built (green field approach)

- query = present:V(industry_chemicals_refineries_flexibility_p2h_network_gas_electricity, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
