# investment costs of industry_steel_electricfurnace_captured_co2 IF newly built (green field approach)

- query =
    QUERY_DELTA( -> {
       MV(industry_steel_electricfurnace_captured_co2,total_investment_over_lifetime_per(:node))
    }) / BILLIONS
- unit = euro
