# investment costs of industry_heat_backup_burner_network_gas IF newly built (green field approach)

- query = future:V(industry_heat_backup_burner_network_gas, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
