# investment costs of industry_chemicals_fertilizers_captured_processes_co2 IF newly built (green field approach)

- query = present:MV(industry_chemicals_fertilizers_captured_processes_co2, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
