# investment costs of molecules_offshore_sequestration_co2 IF newly built (green field approach)

- query =
    QUERY_DELTA( -> {
       MV(molecules_offshore_sequestration_co2,total_investment_over_lifetime_per(:node))
    }) / BILLIONS
- unit = euro
