# investment costs of molecules_direct_air_capture_co2 IF newly built (green field approach)

- query = future:MV(molecules_direct_air_capture_co2, total_investment_over_lifetime_per(:node)) / BILLIONS
- unit = euro
