# Input of electricity from energy_interconnector_9_exported_electricity

- query =
    DIVIDE(
      V(energy_interconnector_9_exported_electricity, input_of_electricity),
      BILLIONS
    )
- unit = PJ
