# Input of electricity from energy_heat_well_shallow_heatpump_mt_geothermal

- query =
    DIVIDE(
      V(energy_heat_well_shallow_heatpump_mt_geothermal, input_of_electricity),
      BILLIONS
    )
- unit = PJ
