# Input of electricity from energy_heat_heatpump_waste_water_water_ts_mt_electricity

- query =
    DIVIDE(
      V(energy_heat_heatpump_waste_water_water_ts_mt_electricity, input_of_electricity),
      BILLIONS
    )
- unit = PJ
