# Final consumption of non-renewable waste in industry ex. ict and refineries - other (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Other -- EG(other_non_specified_industry)
# Carrier:     Non-renewable waste
# Use type:    Total
#
# Exception: includes the share of non-renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_non_renewable_waste_in_industry_other_non_specified_total)
