# Max newly required capacity for the HV/MV transformers

- unit = MW

MAX(
    Q(network_hv_mv_trafo_delta_peak_load_we),
    Q(network_hv_mv_trafo_delta_peak_load_wd),
    Q(network_hv_mv_trafo_delta_peak_load_se),
    Q(network_hv_mv_trafo_delta_peak_load_sd)
)