# Max newly required capacity for the HV/MV transformers
# Compares the required capacity for 4 periods of the year

- query =
    MAX(
        V(energy_power_transformer_mv_hv_electricity,       required_additional_network_capacity_in_mw(Q(network_hv_mv_trafo_peak_load_sd))),
        V(energy_power_transformer_mv_hv_electricity,       required_additional_network_capacity_in_mw(Q(network_hv_mv_trafo_peak_load_se))),
        V(energy_power_transformer_mv_hv_electricity,       required_additional_network_capacity_in_mw(Q(network_hv_mv_trafo_peak_load_wd))),
        V(energy_power_transformer_mv_hv_electricity,       required_additional_network_capacity_in_mw(Q(network_hv_mv_trafo_peak_load_we)))    
    )
- unit = MW
