# Final consumption of gaseous biofuels in industry ex. ict and refineries - food (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Food -- EG(food_industry)
# Carrier:     Gaseous biofuels
# Use type:    Total
#
# Exception: includes the share of gaseous biofuels in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_gaseous_biofuels_in_industry_food_total)
