# Non-nergetic final demand of the 'oil_and_derivatives' carrier group 

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(
            FILTER(
              FILTER(
                EG(final_demand),"sector == :other"
              ),
              ! energetic?
            ),
            "crude_oil? ||  gasoline? ||  diesel? ||  lpg? || kerosene? || heavy_fuel_oil? || bio_oil? || bio_kerosene?"
          ),
          value
        )
      ),
      BILLIONS
    )
      