# The delta (difference) between the present and the future costs of the low voltage net.

- query =
          SUM(
              QUERY_FUTURE(lv_net_costs_delta_present_future_capex),
              QUERY_FUTURE(lv_net_costs_delta_present_future_opex)
          )

- unit = euro
