# The capital costs of the future lv net

- query =
          SUM(
              QUERY_FUTURE(lv_net_costs_delta_present_future_investment_costs) / 2.0 * Q(lv_net_costs_delta_present_future_wacc)
          )

- unit = euro
