# The capital costs of the future lv net

- query =
          SUM(
              QUERY_FUTURE(lv_net_total_investment_costs) / 2.0 * V(energy_power_lv_network_electricity,wacc)
          )

- unit = euro
