# The operations and maintenance costs of the future lv net, consisting of a fixed component only

- query = V(energy_power_lv_network_electricity,fixed_operation_and_maintenance_costs_per(:mw_input)) * QUERY_FUTURE(lv_net_capacity_delta_present_future)

- unit = euro
