# The depreciation costs of the future lv net

- query =
          SUM(
              QUERY_FUTURE(lv_net_costs_delta_present_future_investment_costs) / Q(lv_net_costs_delta_present_future_technical_lifetime)
          )

- unit = euro
