# The delta (difference) between the present and the future costs of the low voltage net.

- query =
          SUM(
              QUERY_FUTURE(lv_net_additional_CAPEX),
              QUERY_FUTURE(lv_net_additional_OPEX)
          )

- unit = euro
