# The CAPEX of the future lv net

- query =
          SUM(
              QUERY_FUTURE(lv_net_additional_capital_costs),
              QUERY_FUTURE(lv_net_additional_depreciation_costs)
          )

- unit = euro
