# Import of coal and derivatives

- query =
    DIVIDE(
      SUM(
        V(
          G(energy_export),
          output_of(
            ammonia
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
