# Import of coal and derivatives

- query =
    present:DIVIDE(
      SUM(
        V(
          G(energy_import),
          output_of(
            hydrogen_gaseous
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
