# The primary co2 of final demand heat

- unit = tonne
- query =
    SUM(
      V(
        FILTER(G(co2_emissions_primary), "steam_hot_water_input_conversion > 0"),
        "steam_hot_water_input_conversion * primary_co2_emission"
      )
    ) / THOUSANDS
