# The primary co2 of final demand coal and derivatives

- unit = tonne
- query =
  SUM(
    V(G(co2_emissions_primary).select {|node| node.input_slots.detect { |slot| slot.carrier.coal? }}, "coal_input_conversion * primary_co2_emission"),
    V(G(co2_emissions_primary).select {|node| node.input_slots.detect { |slot| slot.carrier.coal_gas? }}, "coal_gas_input_conversion * primary_co2_emission")
  ) / THOUSANDS
