# The primary co2 of final demand hydrogen

- unit = tonne
- query =
    SUM(
      V(
        FILTER(G(co2_emissions_primary), "hydrogen_input_conversion > 0"),
        "hydrogen_input_conversion * primary_co2_emission"
      )
    ) / THOUSANDS
