# The primary co2 of final demand electricity

- unit = tonne
- query =
    SUM(
      V(
        FILTER(G(co2_emissions_primary), "electricity_input_conversion > 0"),
        "electricity_input_conversion * primary_co2_emission"
      )
    ) / THOUSANDS
