# The primary co2 of final demand natural gas and derivatives

- unit = tonne
- query =
  SUM(
    V(
      FILTER(G(co2_emissions_primary), "network_gas_input_conversion > 0"),
      "network_gas_input_conversion * primary_co2_emission"
    ),
    V(
      FILTER(G(co2_emissions_primary), "compressed_network_gas_input_conversion > 0"),
      "compressed_network_gas_input_conversion * primary_co2_emission"
    ),
    V(
      FILTER(G(co2_emissions_primary), "lng_input_conversion > 0"),
      "lng_input_conversion * primary_co2_emission"
    )
  ) / THOUSANDS
