# The primary co2 of final demand oil and derivatives

- unit = tonne
- query =
  SUM(
    V(
      FILTER(G(co2_emissions_primary), "crude_oil_input_conversion > 0"),
      "crude_oil_input_conversion * primary_co2_emission"
    ),
    SUM(
      V(G(co2_emissions_refinery_products), "demand * weighted_carrier_co2_per_mj")
    )
  ) / THOUSANDS
