# The primary co2 of final demand hydrogen

- unit = tonne
- query = V(INTERSECTION(G(final_demand_group),USE(energetic)).select {|node| node.input_slots.detect { |slot| slot.carrier.hydrogen? }}, primary_co2_emission).sum / THOUSANDS
