# Direct conversion input of coal and coal products for central heat production

- query = 
    SUM(
      Q(coal_for_heat_conversion),
      Q(coal_gas_for_heat_conversion),
      Q(cokes_for_heat_conversion),
      Q(lignite_for_heat_conversion)
    )
- unit = PJ
