# 

- unit = factor

SUM(
Q(dependency_share_biomass),
Q(dependency_share_bio_diesel),
Q(dependency_share_bio_ethanol),
Q(dependency_share_biofuel),
Q(dependency_share_greengas),
Q(dependency_share_bio_oil),
Q(dependency_share_waste),
Q(dependency_share_algue_diesel)
)
