# Final consumption of liquid biofuels in industry (non-energetic use only).
#
# Sector:      Industry -- sector == :industry
# Carrier:     Liquid biofuels -- biodiesel? || bio_ethanol? || bio_kerosene? || bio_oil? || bionaphtha? || biomethanol? || bio_pyrolysis_oil? || oily_biomass? + crude_oil? x Q(share_of_biogenic_in_industry_final_demand_crude_oil_non_energetic)
# Use type:    Non-energetic -- !energetic?
#
# Exception: includes the biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    Q(final_consumption_of_liquid_biofuels_in_industry_non_energetic)
