# Final consumption of non-renewable waste in industry (non-energetic use only).
#
# Sector:      Industry -- sector == :industry
# Carrier:     Non-renewable waste
# Use type:    Non-energetic -- !energetic?
#
# Exception: includes the share of non-renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_non_renewable_waste_in_industry_non_energetic)
