### Calculates future transit flows
# The transit flow of a carrier is generally equal to the baseload export volume, because the baseload export creates a corresponding forced import volume.
# The only exception occurs when the system already produces excess volume of that carrier. 
# The baseload export is then partially fulfilled by the excess production. The import flow is therefore lower than the baseload export.
# In that case, a transit flow equals the import volume, 
# since either baseload > backup (forcing an import volume to make up the difference) 
# or baseload <= backup (meaning import equals 0, i.e. no transit flow).

- unit = PJ
- query =
    future:
    transit_volume_in_mj = 
        IF(
            V(energy_export_heavy_fuel_oil_baseload, demand) > V(energy_import_heavy_fuel_oil, demand),
            V(energy_import_heavy_fuel_oil, demand),
            V(energy_export_heavy_fuel_oil_baseload, demand)
        );

    DIVIDE(
    	transit_volume_in_mj,
        BILLIONS
    )
