# Total emissions including all IPCC categories

- unit = MT
- query =
    SUM(
      Q(direct_emissions_ipcc_1a1_co2),
      Q(direct_emissions_ipcc_1a2_co2),
      Q(direct_emissions_ipcc_1a3_co2),
      Q(direct_emissions_ipcc_1a4a_co2),
      Q(direct_emissions_ipcc_1a4b_co2),
      Q(direct_emissions_ipcc_1a4c_co2),
      Q(direct_emissions_ipcc_1a5_co2),
      Q(direct_emissions_ipcc_1b_co2),
      Q(direct_emissions_ipcc_1c_co2),
      Q(direct_emissions_ipcc_1d1_co2),
      Q(direct_emissions_ipcc_2_co2),
      Q(direct_emissions_ipcc_3_co2),
      Q(direct_emissions_ipcc_4_co2),
      Q(direct_emissions_ipcc_5_co2),
      Q(direct_emissions_ipcc_ind_co2_co2)
    )
