# This query is a renamed copy of the query below, used to force the dropdown query selection in the hourly_solar_pv_curtailment chart

- query = Q(energy_power_solar_pv_offshore_curtailed_electricity_output_curve)
- unit = curve
