# This query is a renamed copy of the query below, used to force the dropdown query selection in the hourly_solar_pv_curtailment chart

- query = Q(energy_battery_curtailed_solar_electricity_input)
- unit = curve
