- query = 
        SUM(
            Q(emissions_captured_energy_chp_ht_wood_pellets),
            Q(emissions_captured_energy_chp_mt_wood_pellets),
            Q(emissions_captured_energy_power_wood_pellets),
            Q(emissions_captured_hydrogen_biomass_gasification)
        )
- unit = tonne