- query = 
        SUM(
            Q(emissions_captured_total),
            NEG(
                SUM(
                Q(emissions_captured_import_co2_total)
                )
            )
        )
- unit = tonne