# This sums the present coal gas produced by the blast furnace and cokesoven.

- query = 
    present:SUM(
      V(
        energy_blastfurnace_transformation_cokes,
        energy_cokesoven_transformation_coal,
        output_of_coal_gas
      )
    )
- unit = MJ