# This sums the coal gas used for final demand and own use of the blast furnace and cokesoven.

- query =
    SUM(
      V(
        industry_final_demand_coal_gas,
        input_of_coal_gas
      )
    )
- unit = MJ
