# Final consumption of solid biofuels in industry ex. ict and refineries - paper (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Paper -- EG(paper_industry)
# Carrier:     Solid biofuels -- wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_solid_biofuels_in_industry_paper_energetic)
