# Final consumption of solid biofuels in agriculture (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Solid biofuels -- wood_pellets? || torrefied_biomass_pellets? || wet_biomass? || dry_biomass?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_solid_biofuels_in_agriculture_energetic)
