# 

- unit = factor

PRODUCT(
V(gas_boiler_households_energetic;share_of_dedicated_hot_water_households_energetic),
V(dedicated_hot_water_households_energetic;share_of_hot_water_devices_households_energetic)
)