# 

- deprecated_key = chart_cooking_from_electricity_67_final_energy_demand_596
- unit = pj

DIVIDE(
	SUM(
		V(households_cooker_halogen_electricity,households_cooker_resistive_electricity,households_cooker_induction_electricity,
			input_of_electricity))
	,BILLIONS)
