# Percentage of electricity produced from torrefied_biomass_pellets in total electricity production

- unit = factor
- query = DIVIDE(Q(electricity_produced_from_torrefied_biomass_pellets),Q(total_electricity_consumed))*100
