- query =
    SUM(
      Q(heat_infrastructure_mt_primary_pipelines_depreciation_costs),
      Q(heat_infrastructure_mt_primary_pipelines_capital_costs),
      Q(heat_infrastructure_mt_primary_pipelines_yearly_maintenance_costs)
      )
- unit = euro