# Use of rapeseed in industry sector

- unit = PJ
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(industry)), demand_of_bio_resources_including_abroad_of(rapeseed)
    ).sum / BILLIONS
