# Primary demand of carrier group 'wood' for the curtailment converter

- unit = PJ
- query =
    V(energy_flexibility_curtailment_electricity, demand_of_bio_resources_including_abroad_of(wood)) / BILLIONS
