# Use of sugar_cane in households sector

- unit = PJ
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(households)), demand_of_bio_resources_including_abroad_of(sugar_cane)
    ).sum / BILLIONS
