# Primary demand of carrier group 'biogenic_waste' for the export converter group

- unit = PJ
- query =
    V(G(energy_export), demand_of_bio_resources_including_abroad_of(biogenic_waste)).sum / BILLIONS
