# Use of woody_biomass in households sector

- unit = PJ
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(households)), demand_of_bio_resources_including_abroad_of(woody_biomass)
    ).sum / BILLIONS
