- unit = MJ
- query =
    SUM(
      V(industry_steel_blastfurnace_captured_co2_electricity, demand),
      V(industry_steel_hisarna_captured_co2_electricity, demand),
      V(industry_steel_eaf_captured_co2_electricity, demand)
      )
