# Energy use of carbon capture for power plants can be calculated by comparing the difference between typical)typical_input_capacity
# in efficiency of a plant with and without CCS. The difference times the demand of the
# CCS node gives the additional energy required
- unit = MJ
- query =
    relative_input_without_ccs = V(energy_chp_local_mt_wood_pellets_must_run, typical_input_capacity);
    relative_input_with_ccs = V(energy_chp_local_mt_wood_pellets_ccs_must_run, typical_input_capacity);
    diff_eff = 1- (relative_input_without_ccs/relative_input_with_ccs);
    V(energy_chp_local_mt_wood_pellets_ccs_must_run, demand) * diff_eff
