# Energy use of carbon capture for hydrogen plants can be calculated by comparing the
# difference in efficiency of a plant with and without CCS. The difference times the
# demand of the CCS node gives the additional energy required
- unit = MJ
- query =
    eff_without_ccs = V(energy_hydrogen_biomass_gasification, hydrogen_output_conversion);
    eff_with_ccs = V(energy_hydrogen_biomass_gasification_ccs, hydrogen_output_conversion);
    diff_eff = eff_without_ccs - eff_with_ccs;
    V(energy_hydrogen_biomass_gasification_ccs, demand) * diff_eff
