- unit = MJ
- query =
    SUM(
      V(industry_steel_blastfurnace_bof_captured_co2_electricity, demand),
      V(industry_steel_cyclonefurnace_bof_captured_co2_electricity, demand),
      V(industry_steel_dri_network_gas_captured_co2_electricity, demand)
      )
