- unit = MJ
- query =
    SUM(
      V(industry_chemicals_fertilizers_captured_processes_co2_electricity, demand),
      V(industry_chemicals_fertilizers_captured_combustion_co2_electricity, demand)
      )
