# The delta (difference) between the present and the future costs of the high voltage net.

- query =
          SUM(
              QUERY_FUTURE(hv_net_capex),
              QUERY_FUTURE(hv_net_opex)
          )

- unit = euro
