# The CAPEX of the future hv net

- query =
          SUM(
              QUERY_FUTURE(hv_net_additional_capital_costs),
              QUERY_FUTURE(hv_net_additional_depreciation_costs)
          )

- unit = euro
