# The OPEX of the future hv net, consisting of operation and maintenance costs

- query =
          SUM(
              QUERY_FUTURE(hv_net_costs_delta_present_future_fixed_operation_and_maintenance_costs)
          )

- unit = euro
