# Energetic final demand of network gas in households excluding heating

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_natural_gas_in_households_appliances_energetic),
      Q(final_demand_of_natural_gas_in_households_cooling_energetic),
      Q(final_demand_of_natural_gas_in_households_lighting_energetic),
      Q(final_demand_of_natural_gas_in_households_cooking_energetic),
      Q(final_demand_of_greengas_in_households_appliances_energetic),
      Q(final_demand_of_greengas_in_households_cooling_energetic),
      Q(final_demand_of_greengas_in_households_lighting_energetic),
      Q(final_demand_of_greengas_in_households_cooking_energetic)
    )
