# CAPEX and OPEX of the costs in powerplants ex fuels ex CCUS.

- query =
          SUM(
              V(G(costs_production_other), capital_expenditures_excluding_ccs_per(:node)),
              V(G(costs_production_other), operating_expenses_excluding_ccs_per(:node))
              )


- unit = euro
