- query =
    SUM(
      Q(costs_production_power_plants),
      Q(costs_production_chp_plants),
      Q(costs_production_heat_plants),
      Q(costs_production_dedicated_hydrogen_production),
      Q(costs_production_biomass),
      Q(costs_production_other)
    )

- unit = euro