# Returns the converters which produce electricity using gas. It works by looking to converters directly fed by the "national gas network" and "energy_sector_gas_mixer" converter that have output of electricity.

- unit = converters

V(
  FILTER(
    V(
      PARENTS(V(energy_sector_gas_mixer_energy)),
      PARENTS(V(national_gas_network_energy   ))
      )
   ;electricity_output_conversion && electricity_output_conversion > 0)
  )