# Production costs of network gas include production of greengas and regasification of lng, including CCUS costs

- query = 
    SUM(
      V(G(costs_production_biomass), capital_expenditures_excluding_ccs_per(:node)),
      V(G(costs_production_biomass), capital_expenditures_ccs_per(:node)),
      V(G(costs_production_biomass), operating_expenses_excluding_ccs_per(:node)),
      V(G(costs_production_biomass), operating_expenses_ccs_per(:node)),
      V(energy_regasification_lng, capital_expenditures_excluding_ccs_per(:node)),
      V(energy_regasification_lng, capital_expenditures_ccs_per(:node)),
      V(energy_regasification_lng, operating_expenses_excluding_ccs_per(:node)),
      V(energy_regasification_lng, operating_expenses_ccs_per(:node))
    )
    
- unit = euro