# Flexibility costs for heat consist of p2h and heat storage installations

- query = 
    SUM(
      Q(costs_storage_and_conversion_p2h),
      Q(costs_storage_and_conversion_storage_heat)
    )
- unit = euro