# Flexibility costs for hydrogen consist of p2g and hydrogen storage installations

- query = 
    SUM(
      Q(costs_storage_and_conversion_p2g),
      Q(costs_storage_and_conversion_storage_hydrogen)
    )
- unit = euro