# Final consumption of methanol, all sectors (energetic use only).
#
# Sector:      All sectors
# Carrier:     Methanol -- methanol?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_methanol_energetic)
