- query = 
    V(INTERSECTION(USE(energetic),G(final_demand_group)),"input_of_wood_pellets + input_of_bio_ethanol + input_of_biodiesel + input_of_bio_kerosene + input_of_bio_lng + input_of_biomethanol + input_of_bio_oil + input_of_bionaphtha").sum

- unit = MJ