- query = 
    SUM_CURVES(
      PRODUCT_CURVES(
        V(energy_chemical_fertilizers_transformation_external_coupling_node, network_gas_output_curve),
        COALESCE_CURVE(nil, default = Q(share_of_greengas_in_network_gas_industry_transformation_chemical_fertilizers))
        ),
      PRODUCT_CURVES(
        V(energy_chemical_other_transformation_external_coupling_node, network_gas_output_curve),
        COALESCE_CURVE(nil, default = Q(share_of_greengas_in_network_gas_industry_transformation_chemical_other))
        ),
      PRODUCT_CURVES(
        V(energy_chemical_refineries_transformation_external_coupling_node, network_gas_output_curve),
        COALESCE_CURVE(nil, default = Q(share_of_greengas_in_network_gas_industry_transformation_chemical_refineries))
        )  
      )
    
- unit = curve
