- query =
    SUM(
       V(
          households_water_heater_solar_thermal,
          buildings_space_heater_solar_thermal,
          households_space_heater_heatpump_pvt_electricity,
          households_water_heater_heatpump_pvt_electricity,
          output_of_useable_heat
        )
    )
- unit = MJ
