- query =
    households_buildings_peak_demand_in_kw = Q(households_buildings_district_heating_ht_demand_peak) * 1000.0;

    households_buildings_peak_demand_in_kw * AREA(heat_ht_sub_station_investment_costs_eur_per_kw)
- unit = euro