# Take note: The imported electricity is not included in
# co2_emissions_of_final_demand_excluding_imported_electricity because it is
# assigned no CO2 emission as primary carrier.

- unit = PJ
- query = V(G(final_demand_group),primary_co2_emission).sum / BILLIONS
