# Includes 'delayed' emissions in molecules_other_utilisation_co2 node

- unit = mt
- query =
    DIVIDE(
        MV(
          molecules_other_utilisation_delayed_emitted_co2,
          demand),
      BILLIONS
    )
