# CO2 of energy sector. Includes emissions of CCU. Emissions captured by DAC are deducted
# Sequestered emissions are not deducted as we already deduct captured emissions from industry,
# power and h2 production and from energy (DAC)

- query = Q(primary_co2_emission_of_energy)
- unit = mt
