# Within the co2_emissions_refinery_products the node industry_final_demand_methanol_non_energetic is queried. 
# This node should actually be in query : primary_co2_of_non_energetic.
# This node's primary CO2 emissions will at the moment always be 0 since its free_co2_factor is 1 (no C atoms will be released in non-energetic use of methanol). 
# For now, there is no situation where we have nodes with group co2_emissions_refinery_products with non-energetic use where primary CO2 emissions should be taken into account.

- unit = mt
- query =
    DIVIDE(
      SUM(
        V(
          INTERSECTION(
            INTERSECTION(
              G(co2_emissions_primary),
              SECTOR(industry)),
            USE(energetic)),
          primary_co2_emission),
        V(
          INTERSECTION(
            G(co2_emissions_refinery_products),
            SECTOR(industry)),
          "demand * weighted_carrier_co2_per_mj"),
        NEG(
          SUM(
            MV(
              MG(captured_energetic_emissions_industry),
              demand)
            )
          )
        ),
      BILLIONS)