- unit = mt
- query =
    SUM(
      V( INTERSECTION(G(co2_emissions_primary), SECTOR(bunkers)), primary_co2_emission),
      V( INTERSECTION(G(co2_emissions_refinery_products), SECTOR(bunkers)), "demand * weighted_carrier_co2_per_mj")
    ) / BILLIONS
