# CO2 of other sector

- query =
    SUM(
      V( INTERSECTION(G(co2_emissions_primary), SECTOR(other)), primary_co2_emission),
      V( INTERSECTION(G(co2_emissions_refinery_products), SECTOR(other)), "demand * weighted_carrier_co2_per_mj")
    )
       / BILLIONS
- unit = mt
