# Includes non_energetic emissions from the fertilizer industry (SMR), non-energetic hydrogen final
# demand and non-energetic ammonia final demand. More non_energetic emissions may be added in the
# future. Non-energetic final demand of group co2_emissions_refinery_products in the industry sector
# is not (yet) included in this query, which currently only consists of non-energetic methanol final
# demand. Since its free_co2_factor is 1.0, this doesn't affect the results.

- unit = mt
- query = Q(primary_co2_emission_of_non_energetic)
