# Total net CO2 emissions

- query =
    SUM(
      Q(primary_co2_of_agriculture),
      Q(primary_co2_of_buildings),
      Q(primary_co2_of_bunkers),
      Q(primary_co2_of_energy),
      Q(primary_co2_of_households),
      Q(primary_co2_of_industry),
      Q(primary_co2_of_non_energetic_and_delayed_emissions),
      Q(primary_co2_of_other),
      Q(primary_co2_of_transport)
    )
- unit = mt
