# The share of transport in the final demand, as shown in the sidebar in demand.

- query =
    100 * DIVIDE(
     SUM(Q(final_demand_from_transport),Q(final_demand_from_bunkers)),
     Q(final_demand)
    )
- unit = factor
