# This query returns the additional costs made for the added green gas.
# It is used in the total cost calculation.

- unit = euro

PRODUCT(
   V(national_gas_network_energy;input_of_greengas),
       SUM(V(CARRIER(greengas);cost_per_mj),
       NEG(V(CARRIER(natural_gas);cost_per_mj))
   )
)
