# Fixed. Before the costs per MWh were calculated.
#
# Deleted this :
#
# PRODUCT(
#   SECS_PER_HOUR,

- query =
    DIVIDE(
      V(G(electricity_production),total_costs_per(:converter)).sum,
      V(G(electricity_production),output_of_electricity).sum
    )
- unit = euro
- deprecated_key = avg_total_cost_for_electricity_production_per_mj
