# Calculates the average total cost per mj for all electricity production.
#
- query =
    DIVIDE(
      V(G(electricity_production),total_costs_per(:converter)).sum,
      V(G(electricity_production),output_of_electricity).sum
    )
- unit = euro / mj
