- deprecated_key = insulation_costs
# Costs of the insulation in old houses, new houses and builings.

- unit = euro

SUM(V(V(extra_insulation_savings_households_energetic
   ,heating_savings_insulation_new_households_energetic
    ,insulation_savings_buildings_energetic);"
    demand * costs_per_mj

"))