# unit = euro/MWh

- query =
    DIVIDE(
        V(energy_hydrogen_transport_pipelines, fixed_costs_per(:plant)),
        V(energy_hydrogen_transport_pipelines, "typical_input_capacity * full_load_hours")
    )
- unit = euro
