# Cost of the exported electricity

- deprecated_key = cost_electricity_export
- unit = euro

PRODUCT(
  Q(costs_of_produced_electricity),
  INVERSE(SUM(V(GROUP(electricity_production);output_of_electricity)))
  ,
  V(electricity_export_energy;demand)
)