# This query calculates the insulation costs for semi detached houses and differentiates between costs
# for existing and new houses. The calculated costs are only updated for the future year, in the
# present year the insulation costs are assumed to be zero. This is done with this IF-statements
# `IF(GRAPH().future?, etc., etc.).

- unit = euro
- query =
    insulation_costs_existing_semi_detached_houses = INSULATION_COST(existing_semi_detached_houses, AREA(insulation_semi_detached_houses_start_value ), INPUT_VALUE(households_insulation_level_semi_detached_houses));
    insulation_costs_new_semi_detached_houses = INSULATION_COST(new_builds, semi_detached_houses, INPUT_VALUE(households_insulation_level_semi_detached_houses));
    present_number_of_semi_detached_houses = QUERY_PRESENT(-> { AREA(number_of_semi_detached_houses) });
    future_number_of_semi_detached_houses = DIVIDE(INPUT_VALUE(households_semi_detached_houses_share),100.0) * QUERY_FUTURE(-> { AREA(number_of_residences) });

    IF(
      GRAPH().future?,
      -> {
        IF(
          future_number_of_semi_detached_houses >= present_number_of_semi_detached_houses,
          -> { insulation_costs_existing_semi_detached_houses * present_number_of_semi_detached_houses + insulation_costs_new_semi_detached_houses * (future_number_of_semi_detached_houses - present_number_of_semi_detached_houses) },
          -> { insulation_costs_existing_semi_detached_houses * future_number_of_semi_detached_houses }
        )
      },
      0.0
    )
