- deprecated_key = electricity_operation_and_maintenance_cost
# The total operation_and_maintenance_cost for electricity production.

- unit = euro

SUM(
  V(G(electricity_production), operation_and_maintenance_cost_fixed),  V(G(electricity_production), operation_and_maintenance_cost_variable_total)
)