- unit = euro

- query =
    V(buildings_heating_savings_from_insulation_useable_heat, initial_investment) / AREA(technical_lifetime_insulation)+(V(buildings_heating_savings_from_insulation_useable_heat, initial_investment) / 2 * 0.06)