# Return total cost of all electric cars

- query =
    SUM(
      V(transport_car_using_electricity, total_costs_per(:converter)),
      V(transport_car_using_hydrogen, total_costs_per(:converter))
    )
- unit = euro
