- deprecated_key = cost_refinery
# As of may 4, the costs are now minimum 0, so the query cannot return a negative value.

- unit = euro

MAX(
 SUM(
  PRODUCT( V(CARRIER(lpg), cost_per_mj), V(energy_production_lpg, output_of_lpg) ),
  PRODUCT( V(CARRIER(diesel), cost_per_mj), V(energy_production_diesel, output_of_diesel) ),
  PRODUCT( V(CARRIER(gasoline), cost_per_mj), V(energy_production_gasoline, output_of_gasoline) ),
  NEG( PRODUCT( V(CARRIER(crude_oil), cost_per_mj), Q(oil_demand_of_gasoline_diesel_and_lpg_production) ) )
 ),
 0
)
