# Multiplies the imported heat with the average heat production cost of the imported heat

- query = PRODUCT(V(CARRIER(imported_heat), cost_per_mj), V(energy_import_heat, demand))

- unit = euro
- deprecated_key = cost_heat_import
