# The total operation_and_maintenance_cost for electricity production.

- query =
    SUM(
      V(G(electricity_production), fixed_operation_and_maintenance_costs_per(:node)),
      V(G(electricity_production), variable_operation_and_maintenance_costs_per(:node))
    )
- unit = euro
- deprecated_key = electricity_operation_and_maintenance_cost
