# The total cost_of_capital for electricity production.

- query = V(G(electricity_production), cost_of_capital_per(:converter)).sum
- unit = euro
- deprecated_key = electricity_cost_of_capital_total
