# Multiplies the imported electricity with the average electricity production cost of the imported electricity.

- query = PRODUCT(V(CARRIER(imported_electricity), cost_per_mj), V(energy_import_electricity, demand))

- unit = euro
- deprecated_key = cost_electricity_import
