- deprecated_key = cost_fuels_grid_losses
# 

- unit = euro

SUM(
   V(national_gas_network_energy; output_of_loss * weighted_carrier_cost_per_mj )
   ,
   V(oil_distribution_energy; output_of_loss * weighted_carrier_cost_per_mj )
)