# Total cost of flexibility options P2P and P2H.
# Cost of P2P in EV is already covered by the additional costs of EV
# Cost of P2G is included in hydrogen costs

- query =
    SUM(
      V(G(cost_flexibility), total_costs_per(:converter))
    )
- unit = euro