- unit = euro

- query =
    (V(households_old_houses_heating_savings_from_insulation, initial_investment) / AREA(technical_lifetime_insulation)) + (V(households_old_houses_heating_savings_from_insulation, initial_investment) / 2 * 0.04)