- deprecated_key = cost_torrefaction
# With torrefaction coal is replaced by biomass. Additional costs are 20% of the biomass price. 
# 
# Therefore costs of torrefacted biocoal per mj are calculated by taking 120% of the biomass price minus the coal prices. converted into biocoal.

- unit = euro

PRODUCT(
        V(torrefaction_energy;output_of_biocoal)
        ,
        SUM(
            V(CARRIER(biomass);cost_per_mj *12/10)
            ,
            NEG(V(CARRIER(coal);cost_per_mj))
            )
)