# Total yearly costs of traditional heat and heat pumps.
# Also imported heat costs are included.
# A correction has been implemented for the double counting of technologies
# in cooling and heating of households
# (see https://github.com/quintel/etsource/issues/225)

- query =
    SUM(
      V(
        G(cost_traditional_heat),
        G(cost_heat_pumps),
        total_costs_per(:converter)
      ),
      Q(costs_of_imported_heat),
      Q(dashboard_total_cost_correction),
      Q(hydrogen_heat_correction)
    )
- unit = euro
- deprecated_key = cost_heat_production_new
