# unit = euro/MWh

- query =
    DIVIDE(
        V(energy_hydrogen_distribution_compressed_trucks, fixed_costs_per(:plant)),
        V(energy_hydrogen_distribution_compressed_trucks, "typical_input_capacity * full_load_hours")
    )
- unit = euro
