# Cost of the exported electricity

- deprecated_key = cost_electricity_export
- unit = euro

PRODUCT(
  Q(costs_of_produced_electricity),
  INVERSE(SUM(V(GROUP(electricity_production),output_of_electricity)))
  ,
  V(energy_export_electricity,demand)
)
