# Return total cost of all electric cars

- query =
    SUM(
      V(transport_car_using_electricity, fixed_costs_per(:node)),
      V(transport_car_using_hydrogen, fixed_costs_per(:node))
    )
- unit = euro
