# Total cost of flexibility options P2P, P2G and P2H.
# Cost of P2P in EV is already covered by the additional costs of EV

- query =
    SUM(
      V(G(flexibility), total_costs_per(:converter))
    )
- unit = euro