# Should be in to be created Prices table.
# 01/12/2017, Running month average
#- query = V(1.172)
# after fuel price update 2017, remove lines 4, 5, 6 and uncomment lines 2 and 3
# 22/11/2013, Running month average
- query = V(1.0965)
- unit = $
