# investment costs of %s IF newly built (green field approach)

- query = SUM(Q(agriculture_burner_crude_oil_future_in_investment_cost_table),Q(agriculture_burner_network_gas_future_in_investment_cost_table),Q(agriculture_burner_wood_pellets_future_in_investment_cost_table),Q(agriculture_geothermal_future_in_investment_cost_table),Q(agriculture_heatpump_water_water_ts_electricity_future_in_investment_cost_table),Q(agriculture_burner_hydrogen_future_in_investment_cost_table),Q(agriculture_chp_engine_network_gas_future_in_investment_cost_table),Q(agriculture_chp_engine_biogas_future_in_investment_cost_table))
- unit = mln_euro
