# Sums up the costs.

- query =
    SUM(
        Q(costs_building_and_installations),
        Q(costs_carriers),
        Q(costs_production),
        Q(costs_storage_and_conversion),
        Q(costs_infrastructure),
        Q(costs_co2)
        )
- unit = euro
- deprecated_key = cost_total