# investment costs of %s IF newly built (green field approach)

- query = SUM(
              Q(households_space_heater_coal_future_in_investment_cost_table),
              Q(households_space_heater_combined_network_gas_future_in_investment_cost_table),
              Q(households_space_heater_crude_oil_future_in_investment_cost_table),
              Q(households_space_heater_electricity_future_in_investment_cost_table),
              Q(households_space_heater_heatpump_air_water_electricity_future_in_investment_cost_table),
              Q(households_space_heater_heatpump_ground_water_electricity_future_in_investment_cost_table),
              Q(households_space_heater_hybrid_heatpump_air_water_electricity_future_in_investment_cost_table),
              Q(households_space_heater_network_gas_future_in_investment_cost_table),
              Q(households_space_heater_wood_pellets_future_in_investment_cost_table),
              Q(households_water_heater_network_gas_future_in_investment_cost_table),
              Q(households_water_heater_resistive_electricity_future_in_investment_cost_table),
              Q(households_water_heater_wood_pellets_future_in_investment_cost_table),
              Q(households_water_heater_crude_oil_future_in_investment_cost_table),
              Q(households_water_heater_coal_future_in_investment_cost_table),
              Q(households_space_heater_solar_thermal_future_in_investment_cost_table),
              Q(households_solar_pv_solar_radiation_future_in_investment_cost_table),
              Q(households_cooling_airconditioning_electricity_future_in_investment_cost_table),
              Q(households_heat_network_connection_steam_hot_water_future_in_investment_cost_table),
              Q(households_space_heater_district_heating_steam_hot_water_future_in_investment_cost_table),
              Q(households_flexibility_p2p_electricity_future_in_investment_cost_table)
              )
- unit = mln_euro