- query = 
		SUM(
			Q(coal_and_derivatives_to_ht_network_in_sankey_heat_networks),
			Q(natural_gas_and_derivatives_to_ht_network_in_sankey_heat_networks),
			Q(crude_oil_and_derivatives_to_ht_network_in_sankey_heat_networks),
			Q(electricity_to_ht_network_in_sankey_heat_networks),
			Q(hydrogen_to_ht_network_in_sankey_heat_networks),
			Q(ammonia_to_ht_network_in_sankey_heat_networks),
			Q(biomass_products_to_ht_network_in_sankey_heat_networks),
			Q(non_biogenic_waste_to_ht_network_in_sankey_heat_networks),
			Q(solar_thermal_to_ht_network_in_sankey_heat_networks),
			Q(geothermal_to_ht_network_in_sankey_heat_networks),
			Q(ambient_heat_to_ht_network_in_sankey_heat_networks),
			Q(imported_heat_to_ht_network_in_sankey_heat_networks),
			Q(residual_heat_to_ht_network_in_sankey_heat_networks)
		)