# Energetic final demand of the 'electricity' carrier group

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),LG(chemical)
            ),
            energetic?
          ),
          electricity?
        ),
        value
      )
    ) / BILLIONS
