# Final consumption of electricity in agriculture (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Electricity -- electricity?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_electricity_in_agriculture_energetic)
