# Final consumption of natural gas and gas products in agriculture (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Natural gas and gas products
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of natural gas and gas products in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_natural_gas_and_gas_products_in_agriculture_energetic)
