# Final consumption of gaseous biofuels in agriculture (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Gaseous biofuels
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of gaseous biofuels in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_gaseous_biofuels_in_agriculture_energetic)
