# Final consumption of renewable waste in agriculture (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Renewable waste
# Use type:    Energetic -- energetic?
#
# Exception: includes the share of renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_renewable_waste_in_agriculture_energetic)
