# Final consumption of solar thermal in agriculture (energetic use only).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Solar thermal -- solar_thermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_solar_thermal_in_agriculture_energetic)
