# The primary co2 of final demand natural gas and derivatives

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),USE(energetic)).select {|node| node.input_slots.detect { |slot| slot.carrier.network_gas? }}, primary_co2_emission),
      V(INTERSECTION(G(final_demand_group),USE(energetic)).select {|node| node.input_slots.detect { |slot| slot.carrier.lng? }}, primary_co2_emission)
    ) / THOUSANDS
