# Final consumption of hydrogen in industry (energetic use only).
#
# Sector:      Industry -- sector == :industry
# Carrier:     Hydrogen -- hydrogen? || liquid_hydrogen? || lohc?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_hydrogen_in_industry_energetic)
