- deprecated_key = chart_ambient_cold_66_cooling_demand_592
# 

- unit = pj

DIVIDE(PRODUCT(DIVIDE(Q(households_cooling_ambient),SUM(V(Q(households_cooling_converters);demand))),V(cooling_demand_households_energetic;input_of_cooling)),BILLIONS)