- deprecated_key = chart_ambient_heat_65_hot_water_demand_588
# 

- unit = pj

DIVIDE(PRODUCT(DIVIDE(Q(ambient_heat_used_for_hot_water_in_households),Q(energy_used_for_hot_water_in_households)),V(hot_water_demand_households_energetic;input_of_hot_water)),BILLIONS)