- deprecated_key = chart_ambient_heat_65_hot_water_demand_588
# 

- unit = pj

DIVIDE(PRODUCT(DIVIDE(Q(households_hot_water_ambient),Q(total_input_for_hot_water)),V(hot_water_demand_households_energetic;input_of_hot_water)),BILLIONS)