- deprecated_key = chart_biomass_industry_50_final_energy_demand_352
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(final_demand_cbs));input_of_biomass),V(INTERSECTION(SECTOR(energy),G(final_demand_cbs));input_of_biomass)),BILLIONS)