- deprecated_key = chart_biomass_plants_investm_54_power_plants_494
# 

- unit = mln_euro

future:UNIT(SUM(V(Q(electricity_producing_wood_pellets_converters);initial_investment_total*wood_pellets_input_conversion));millions)