- deprecated_key = chart_biomass_plants_capacity_54_power_plants_493
# 

- unit = gj

future:DIVIDE(SUM(V(Q(electricity_producing_biomass_converters); nominal_capacity_electricity_output_per_unit * number_of_units * biomass_input_conversion)),1000)