- deprecated_key = chart_biomass_agriculture_50_final_energy_demand_709
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(agriculture),G(final_demand_cbs));input_of_biomass + input_of_wood + input_of_wood_pellets)),BILLIONS)