- deprecated_key = chart_biomass_buildings_50_final_energy_demand_389
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(buildings),G(final_demand_cbs));input_of_biomass + input_of_wood + input_of_wood_pellets)),BILLIONS)