- deprecated_key = chart_chp_s_74_electricity_production_buildings_633
# 

- unit = pj

DIVIDE(SUM(V(gas_chp_buildings_energetic,coal_chp_buildings_energetic,biomass_chp_buildings_energetic;output_of_electricity)),BILLIONS)