- deprecated_key = chart_chp_s_74_electricity_production_buildings_633
# 

- unit = pj

DIVIDE(SUM(V(buildings_collective_chp_gas_power_fuelmix,buildings_collective_chp_wood_pellets,output_of_electricity)),BILLIONS)
