- deprecated_key = chart_cleaning_2_electricity_demand_7
# 

- unit = pj

DIVIDE(SUM(V(dishwasher_households_energetic,vacuum_cleaner_households_energetic,washing_machine_households_energetic,clothes_dryer_households_energetic;input_of_electricity)),BILLIONS)