- deprecated_key = chart_cleaning_2_electricity_demand_7
# 

- unit = pj

DIVIDE(SUM(V(households_dishwasher_electricity,households_vacuum_cleaner_electricity,households_washing_machine_electricity,households_clothes_dryer_electricity,input_of_electricity)),BILLIONS)
