- deprecated_key = chart_coal_industry_50_final_energy_demand_356
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),input_of_coal),V(INTERSECTION(SECTOR(energy),G(final_demand_cbs)),input_of_coal)),BILLIONS)