- deprecated_key = chart_collective_chp_s_5_electricity_production_households_625
# 

- unit = pj

DIVIDE(SUM(V(collective_coal_chp_households_energetic,collective_gas_chp_households_energetic,collective_biomass_chp_households_energetic;output_of_electricity)),BILLIONS)