- deprecated_key = chart_cooking_from_electricity_67_final_energy_demand_596
# 

- unit = pj

DIVIDE(SUM(V(halogen_stove_households_energetic,electric_stove_households_energetic,induction_stove_households_energetic;input_of_electricity)),BILLIONS)