- deprecated_key = chart_current_cost_gas_network_60_annual_cost_of_infrastructure_564
# AREA(annual_infrastructure_cost_gas) contains the costs in million euros. Here we want base units

- unit = euro

PRODUCT(
    MAX(
        AREA(annual_infrastructure_cost_gas),
        0
    ),
    MILLIONS
)