- deprecated_key = chart_diesel_43_transport_320
# 

- unit = pj

DIVIDE(SUM(V(diesel_import_export_transport;demand),V(diesel_production_transport;input_of_crude_oil),V(ships_oil_demand_transport_energetic;input_of_crude_oil)),BILLIONS)