- deprecated_key = chart_electricity_demand_69_heat_demand_with_insulation_607
# 

- unit = pj

DIVIDE(SUM(V(electricity_without_heating_buildings_energetic,demand),Q(electricity_used_for_heating_in_buildings)),BILLIONS)