# 

- deprecated_key = chart_electricity_6_final_energy_demand_236
- unit = pj

DIVIDE(SUM(V(electricity_households_energetic,micro_CHP_production_households,gasheatpump_households_energetic;output_of_electricity)),BILLIONS)