- deprecated_key = chart_electricity_demand_excluding_heating_58_heat_demand_with_insulation_532
# 

- unit = pj

DIVIDE(
	SUM(
		V(electricity_excl_heating_demand_households_energetic,demand),
		NEG(
			Q(cooling_from_electricity_in_households))),BILLIONS)
