- deprecated_key = chart_electricity_demand_68_heat_and_electricity_demand_610
# 

- unit = pj

DIVIDE(SUM(V(electricity_without_heating_buildings_energetic;demand),NEG(Q(electricity_used_for_cooling_in_buildings))),BILLIONS)