- deprecated_key = chart_electricity_demand_68_heat_and_electricity_demand_610
# 

- unit = pj

DIVIDE(
	SUM(
		V(final_demand_for_lighting_electricity_buildings_energetic,demand),
		V(final_demand_for_appliances_electricity_buildings_energetic,demand)
	),
	BILLIONS
)
