- deprecated_key = chart_electric_vehicles_51_centrally_produced_electricity_demand_361
# 

- unit = pj

DIVIDE(SUM(V(electric_cars_transport_energetic,electric_trucks_transport_energetic,input_of_electricity)),BILLIONS)