# This used to be a stored policy. Now it makes use of the new MIXED function
# It's used by the energy imports goal chart
# stored:policy_net_energy_import
- deprecated_key = chart_energy_import_100_38_dependence_306
- unit = factor

MIXED(Q(net_import_of_energy),Q(policy_goal_net_energy_import_target_value))
