# 

- deprecated_key = chart_fuel_trucks_b_23_final_energy_demand_205
- unit = pj

DIVIDE(SUM(V(truck_kms_demand_transport_energetic;final_demand),NEG(Q(electricity_trucks_in_use_of_final_demand_in_transport))),BILLIONS)