# 

- deprecated_key = chart_fuel_cars_b_23_final_energy_demand_204
- unit = pj

DIVIDE(SUM(V(V(compressed_gas_cars_transport_energetic),V(diesel_cars_transport_energetic),V(gasoline_cars_transport_energetic),V(lpg_cars_transport_energetic);final_demand)),BILLIONS)