- deprecated_key = chart_fuel_trucks_b_23_final_energy_demand_205
# 

- unit = pj

DIVIDE(SUM(V(diesel_trucks_transport_energetic,gasoline_trucks_transport_energetic,compressed_gas_trucks_transport_energetic;final_demand)),BILLIONS)