- deprecated_key = chart_gas_plants_investm_54_power_plants_479
# 

- unit = mln_euro

future:UNIT(SUM(V(Q(electricity_producing_gas_converters);initial_investment_total*gas_power_fuelmix_input_conversion));millions)