- deprecated_key = chart_gas_households_50_final_energy_demand_373
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(households),G(final_demand_cbs));input_of_natural_gas),SUM(V(INTERSECTION(SECTOR(households),G(final_demand_cbs));input_of_greengas))),BILLIONS)