- deprecated_key = chart_gas_industry_52_primary_energy_use_411
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),INTERSECTION(SECTOR(energy),G(final_demand_cbs)),primary_demand_of_natural_gas)),BILLIONS)