- deprecated_key = chart_gas_other_50_final_energy_demand_400
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(other),G(final_demand_cbs));input_of_natural_gas),V(INTERSECTION(SECTOR(other),G(final_demand_cbs));input_of_greengas)),BILLIONS)