- deprecated_key = chart_heat_from_biomass_59_heat_demand_bezier_540
# 

- unit = pj

DIVIDE(PRODUCT(DIVIDE(Q(households_heating_final_demand_biomass),Q(households_heating_final_demand_total)),V(heating_demand_households_energetic;demand)),BILLIONS)