- deprecated_key = chart_heat_demand_other_buildings_69_heat_demand_with_insulation_640
# 

- unit = pj

DIVIDE(PRODUCT(V(heating_buildings_energetic;demand),Q(buildings_share_of_heat_other)),BILLIONS)