- deprecated_key = chart_heat_from_electricity_59_heat_demand_bezier_541
# 

- unit = pj

DIVIDE(SUM(PRODUCT(DIVIDE(Q(electricity_used_for_heating_in_households),Q(energy_used_for_heating_in_households)),V(heating_demand_households_energetic,demand))),BILLIONS)