# 

- deprecated_key = chart_heat_from_fossil_fuels_56_heat_demand_519
- unit = pj


DIVIDE(
  PRODUCT(
    Q(share_of_fossil_fuels_in_heat_produced_in_households),
    V(heating_demand_households_energetic;demand)),
  BILLIONS
)

