- deprecated_key = chart_heat_demand_including_electric_heating_58_heat_demand_with_insulation_524
# 

- unit = pj

DIVIDE(V(households_useful_demand_for_space_heating_after_insulation,demand),BILLIONS)
