- deprecated_key = chart_heat_from_fossil_fuels_59_heat_demand_bezier_542
# 

- unit = pj

DIVIDE(PRODUCT(DIVIDE(Q(fossil_energy_used_for_heating_in_households),Q(energy_used_for_heating_in_households)),V(households_useful_demand_for_space_heating_after_insulation_solar_heater_and_add_on,demand)),BILLIONS)
