- deprecated_key = chart_heat_demand_schools_69_heat_demand_with_insulation_639
# 

- unit = pj

DIVIDE(PRODUCT(V(heating_buildings_energetic;demand),V(heating_schools_current_insulation_buildings_energetic;useable_heat_flexible_input_link_share),Q(share_of_schools_in_heat_demand_in_buildings)),BILLIONS)