- deprecated_key = chart_heat_from_fossil_fuels_70_heat_demand_614
# 

- unit = pj

DIVIDE(PRODUCT(DIVIDE(Q(buildings_heating_final_demand_fossil),Q(buildings_heating_final_demand_total)),V(heating_buildings_energetic;input_of_useable_heat)),BILLIONS)