# 

- unit = pj
- deprecated_key = chart_heat_from_fossil_fuels_70_heat_demand_614

DIVIDE(PRODUCT(DIVIDE(Q(fossil_energy_used_for_heating_in_buildings),Q(energy_used_for_heating_in_buildings)),V(heating_buildings_energetic;input_of_useable_heat)),BILLIONS)