- deprecated_key = chart_heat_demand_other_buildings_68_heat_and_electricity_demand_637
# 

- unit = pj

DIVIDE(PRODUCT(V(heating_buildings_energetic;demand),Q(buildings_share_of_heat_other)),BILLIONS)