- deprecated_key = chart_high_voltage_network_60_annual_cost_of_infrastructure_550
# Q(yearly_investment_costs_of_hv_grid) currently returns costs in millions. Here it is converted to base units

- unit = eur

PRODUCT(
    Q(yearly_investment_costs_of_hv_grid),
    MILLIONS
)