# 

- unit = pj

DIVIDE(
	PRODUCT(
		DIVIDE(
			V(heatpump_boiler_using_city_heat_households_energetic,demand)
			,
			Q(energy_used_for_hot_water_in_households))
		,V(hot_water_demand_households_energetic,input_of_hot_water)
	),BILLIONS)