- deprecated_key = chart_hot_water_from_electricity_65_hot_water_demand_590
# 

- unit = pj

DIVIDE(PRODUCT(DIVIDE(Q(households_hot_water_electricity),Q(total_input_for_hot_water)),V(hot_water_demand_households_energetic;input_of_hot_water)),BILLIONS)