# 

- deprecated_key = chart_hot_water_from_fossil_fuels_65_hot_water_demand_591
- unit = pj

DIVIDE(
	PRODUCT(
		DIVIDE(
			SUM(
				Q(fossil_energy_used_for_hot_water_in_households),
				NEG(Q(gas_allocated_to_electricity_production_in_households_hot_water))),
			Q(energy_used_for_hot_water_in_households)),
		V(hot_water_demand_households_energetic;input_of_hot_water)
		),
	BILLIONS)