- deprecated_key = chart_hot_water_from_biomass_65_hot_water_demand_589
# 

- unit = pj

DIVIDE(PRODUCT(DIVIDE(Q(households_hot_water_biomass),Q(total_input_for_hot_water)),V(hot_water_demand_households_energetic;input_of_hot_water)),BILLIONS)