- deprecated_key = cost_chart_solar_plant_investment
# 

- unit = mln_euro

future:PRODUCT(SUM(V(solar_pv_central_production_energy_energetic,initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))