- deprecated_key = cost_chart_solar_pv_investment
# 

- unit = mln_euro

future:PRODUCT(SUM(V(local_solar_pv_grid_connected_energy_energetic;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))