- deprecated_key = cost_chart_solar_plant_investment
# 

- unit = mln_euro

future:PRODUCT(SUM(V(energy_power_solar_pv_solar_radiation,initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))
