- deprecated_key = chart_lighting_51_centrally_produced_electricity_demand_366
# 

- unit = pj

DIVIDE(SUM(V(electricity_for_lighting_households_energetic,lighting_buildings_energetic;demand)),BILLIONS)