- deprecated_key = chart_low_voltage_network_60_annual_cost_of_infrastructure_552
# Q(yearly_investment_costs_of_lv_grid) returns million euros. Here we convert to base units

- unit = euro

Q(yearly_investment_costs_of_lv_grid)