#


- unit = EUR

future:
DIVIDE(
    SUM(V(local_solar_pv_grid_connected_energy_energetic, solar_pv_central_production_energy_energetic, solar_panels_buildings_energetic; variable_costs_per_mwh_input/electricity_output_conversion*installed_production_capacity_in_mw_electricity)),
    SUM(V(local_solar_pv_grid_connected_energy_energetic, solar_pv_central_production_energy_energetic, solar_panels_buildings_energetic; installed_production_capacity_in_mw_electricity))
)