- deprecated_key = chart_micro_chp_5_electricity_production_households_29
# 

- unit = pj

DIVIDE(SUM(V(micro_chp_space_heating_households, micro_chp_hot_water_households_energetic;output_of_electricity)),BILLIONS)