- deprecated_key = chart_micro_chp_53_comparison_of_gas_use_501
# 

- unit = pj

future:DIVIDE(SUM(V(micro_CHP_production_households,micro_CHP_backup_burner_households;input_of_natural_gas)),BILLIONS)