- deprecated_key = chart_natural_gas_industry_55_gas_vs_other_primary_energy_724
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),INTERSECTION(SECTOR(energy),G(final_demand_cbs));primary_demand_of_natural_gas)),BILLIONS)