- deprecated_key = chart_non_energetic_use_31_final_energy_demand_261
# 

- unit = pj

DIVIDE(SUM(V(gas_other_non_energetic;output_of_network_gas),V(coal_other_non_energetic;output_of_coal),V(oil_other_non_energetic;output_of_crude_oil)),BILLIONS)