- deprecated_key = chart_non_energetic_other_27_final_energy_demand_239
# 

- unit = pj

DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),USE(non_energetic)),demand - output_of_crude_oil)),BILLIONS)