# 

- unit = pj

DIVIDE(SUM(V(gas_other_non_energetic;output_of_natural_gas),V(coal_other_non_energetic;output_of_coal),V(oil_other_non_energetic;output_of_crude_oil),V(biofuel_other_non_energetic;output_of_biofuel)),BILLIONS)