- deprecated_key = chart_non_energetic_oil_27_final_energy_demand_238
# 

- unit = pj

DIVIDE(SUM(V(INTERSECTION(INTERSECTION(SECTOR(industry),G(final_demand_cbs)),USE(non_energetic));output_of_crude_oil)),BILLIONS)