- deprecated_key = chart_nuclear_plants_54_power_plants_480
# 

- unit = pj

present:UNIT(SUM(V(Q(electricity_producing_nuclear_converters);output_of_electricity*uranium_oxide_input_conversion));billions)