- deprecated_key = chart_oil_power_plants_prod_54_power_plants_472
# 

- unit = pj

future:UNIT(SUM(V(Q(electricity_producing_oil_converters),"output_of_electricity*crude_oil_input_conversion")),billions)