- deprecated_key = chart_oil_industry_50_final_energy_demand_353
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(final_demand_cbs));input_of_crude_oil),V(INTERSECTION(SECTOR(energy),G(final_demand_cbs));input_of_crude_oil)),BILLIONS)