- deprecated_key = chart_oil_power_plants_capacity_54_power_plants_473
# 

- unit = gj

future:DIVIDE(SUM(V(Q(electricity_producing_oil_converters);" nominal_capacity_electricity_output_per_unit * number_of_units * crude_oil_input_conversion")),1000)