- deprecated_key = chart_oil_power_plants_54_power_plants_469
# 

- unit = pj

present:UNIT(SUM(V(Q(electricity_producing_oil_converters);"output_of_electricity*crude_oil_input_conversion"));billions)