- deprecated_key = chart_operation_maintenance_cost_103_split_converter_costs_844
# 

- unit = bln_euro

DIVIDE(SUM(
  V(city_heating_network_energy_energetic ; operation_and_maintenance_cost_fixed),  V(city_heating_network_energy_energetic ; operation_and_maintenance_cost_variable_total)
),BILLIONS)