- deprecated_key = chart_other_heat_63_decentral_production_568
# 

- unit = pj

DIVIDE(SUM(V(heat_demand_other_other_energetic;demand),NEG(V(chp_other_other_energetic;output_of_heat_carriers))),BILLIONS)