- deprecated_key = chart_other_heat_62_decentral_production_572
# 

- unit = pj

DIVIDE(
    MAX(
        SUM(
            V(heating_demand_agriculture_energetic;demand),
            NEG(
                V(chp_agri_agriculture_energetic;output_of_heat_carriers)
            )
        ),
        0
    ),
    BILLIONS
)