# 

- deprecated_key = chart_demand_policy_5_electricity_production_households_629
- unit = pj

present:DIVIDE(SUM(V(electricity_households_energetic,demand),NEG(V(electricity_households_energetic,electricity_inversedflexible_input_link_value))),BILLIONS)