- deprecated_key = chart_demand_policy_74_electricity_production_buildings_635
# 

- unit = pj

present:DIVIDE(SUM(V(electricity_without_heating_buildings_energetic;demand),Q(electricity_for_heat_buildings)),BILLIONS)