# The minimum available electricity production capacity used for Security of Supply calculation


- unit = MW

present:SUM(
  V(G(electricity_production);installed_production_capacity_in_mw_electricity*availability)
)