# Used to be a stored policy
- deprecated_key = chart_pv_100_36_targeted_area_use_for_solar_power_301
- unit = km2

MIXED(
 Q(share_of_designated_area_used_for_central_solar_pv),
 PRODUCT(DIVIDE( 
  Q(policy_goal_land_for_solar_panels_target_value),
  AREA(land_available_for_solar)
 ),100)
)