- deprecated_key = chart_solar_panels_51_centrally_produced_electricity_demand_407
# 

- unit = pj

NEG(DIVIDE(SUM(V(local_solar_pv_grid_connected_energy_energetic,solar_panels_buildings_energetic,output_of_electricity)),BILLIONS))