- deprecated_key = chart_total_plants_prod_future_54_power_plants_527
# 

- unit = pj

future:UNIT(SUM(V(Q(electricity_producing_converters); typical_electricity_production_per_unit * number_of_units));billions)