- deprecated_key = chart_uranium_value_47_energy_dependence_332
# 

- unit = pj

present:DIVIDE(
SUM(
	V(G(energy_import);output_of_uranium),
	NEG(V(G(energy_export);input_of_uranium))
	)
,BILLIONS)