- deprecated_key = chart_waste_industry_50_final_energy_demand_368
# 

- unit = pj

future:DIVIDE(SUM(V(INTERSECTION(SECTOR(industry),G(final_demand_cbs));input_of_waste),V(INTERSECTION(SECTOR(energy),G(final_demand_cbs));input_of_waste)),BILLIONS)