- deprecated_key = chart_waste_other_50_final_energy_demand_404
# 

- unit = pj

future:DIVIDE(V(INTERSECTION(INTERSECTION(SECTOR(energy),G(heat_production)), G(electricity_production)),input_of_waste_mix),BILLIONS)