- deprecated_key = chart_wind_farms_capacity_54_power_plants_488
# 

- unit = gj

future:DIVIDE(SUM(V(G(electricity_production); nominal_capacity_electricity_output_per_unit * number_of_units * wind_input_conversion)),1000)