- deprecated_key = chart_with_im_export_2010_54_power_plants_786
# 

- unit = mt

present:DIVIDE(SUM(Q(co2_emissions_within_area),Q(co2_emissions_of_imported_electricity_minus_exported_electricty)),BILLIONS)