- query =
  V(
    GRAPH(),
    group_of_excess_events((1..24).to_a, [
      :energy_flexibility_curtailment_electricity,
      :energy_export_electricity,
      :households_flexibility_p2h_electricity,
      :energy_flexibility_p2g_electricity,
      :transport_car_using_electricity,
      :households_flexibility_p2p_electricity
    ])
  )
