# Note that kerosene and naphtha are intentionally left out here, since flows of
# pyrolysis oil fractionation are otherwise queried.
# Steam hot water is modelled internally here and should not be part
# of steam hot water loss in sankey download

- unit = PJ
- query =
    SUM(
      Q(conversion_loss_steam_hot_water_to_crude_oil),
      Q(conversion_loss_steam_hot_water_to_heavy_fuel_oil),
      Q(conversion_loss_steam_hot_water_to_lpg),
      Q(conversion_loss_steam_hot_water_to_refinery_gas)
    )
