# Energetic final demand of the 'natural_gas_and_derivatives' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          network_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          compressed_network_gas?
        ),
        value
      )
    )
