# Energetic final demand of the 'renewable_heat' carrier group

- unit = MJ
- query =
    SUM(
      Q(final_demand_of_renewable_heat_in_energy),
      Q(final_demand_of_renewable_heat_in_other)
    )
