# Energetic final demand of the 'oil_and_derivatives' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          crude_oil?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          gasoline?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          diesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          lpg?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          kerosene?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          heavy_fuel_oil?
        ),
        value
      )
    )
