# Energetic final demand of the 'natural_gas_and_derivatives' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          network_gas?
        ),
        value
      ) * V(energy_national_gas_network_natural_gas,natural_gas_input_conversion),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          lng?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :agriculture"
            ),
            energetic?
          ),
          compressed_network_gas?
        ),
        value
      ) * V(energy_national_gas_network_natural_gas,natural_gas_input_conversion)
    )
