# Energetic final demand of the 'solid_biofuels' carrier group

- unit = MJ
- query =
    SUM(
      Q(final_demand_of_solid_biofuels_in_energy),
      Q(final_demand_of_solid_biofuels_in_other)
    )
