# Energetic final demand of the 'renewable heat' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :bunkers"
            ),
            energetic?
          ),
          steam_hot_water?
        ),
        "sustainability_share * value"
      )
    )
