# Energetic final demand of the 'liquid_biofuels' carrier group

- unit = MJ
- query =
    SUM(
      Q(final_demand_of_liquid_biofuels_in_energy),
      Q(final_demand_of_liquid_biofuels_in_other)
    )
