# Energetic final demand of the 'renewable electricity' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              LG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          electricity?
        ),
        "sustainability_share * value"
      )
    )
