# Energetic final demand of the 'oil_and_derivatives' carrier group
# The applied query differs from the other per sector per carrier queries
# This is a quick fix to align total final demand of oil and derivatives in the per sector per carrier queries
# with the per carrier queries

- unit = MJ
- query =
    SUM(
      V(
        INTERSECTION(G(final_demand_group), SECTOR(buildings)),
        input_of(
          kerosene,
          lpg,
          diesel,
          gasoline,
          crude_oil
        )
      )
    )
