# Energetic final demand of the 'solid_biofuels' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :households"
            ),
            energetic?
          ),
          wood_pellets?
        ),
        value
      )
    )
