# Energetic final demand of the 'renewable heat' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :industry"
            ),
            energetic?
          ),
          "steam_hot_water? || useable_heat?"
        ),
        "sustainability_share * value"
      )
    )
