# Energetic final demand of the 'coal_and_derivatives' carrier group

- unit = MJ
- query =
    SUM(
      Q(myc_final_demand_of_coal_and_derivatives_in_energy),
      Q(myc_final_demand_of_coal_and_derivatives_in_other)
    )
