# Energetic final demand of the 'electricity' carrier group

- query =
    SUM(
      Q(myc_final_demand_of_electricity_in_energy),
      Q(myc_final_demand_of_electricity_in_other)
    )
- unit = MJ
