# Energetic final demand of the 'fossil heat' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :buildings"
            ),
            energetic?
          ),
          "steam_hot_water? || useable_heat?"
        ),
        "(1 - sustainability_share) * value"
      )
    )
