# Energetic final demand of the 'liquid_biofuels' carrier group
# The applied query differs from the other per sector per carrier queries
# This is a quick fix to align total final demand of biofuels in the per sector per carrier queries
# with the per carrier queries

- unit = MJ
- query =
    SUM(
      V(
        INTERSECTION(G(final_demand_group), SECTOR(other)),
        input_of(
          bio_kerosene,
          bio_lng,
          bio_ethanol,
          biodiesel,
          bio_oil
        )
      )
    )
