# Energetic final demand of the 'liquid_biofuels' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :other"
            ),
            energetic?
          ),
          biodiesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :other"
            ),
            energetic?
          ),
          bio_ethanol?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :other"
            ),
            energetic?
          ),
          bio_kerosene?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :other"
            ),
            energetic?
          ),
          bio_lng?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :other"
            ),
            energetic?
          ),
          bio_oil?
        ),
        value
      )
    )
