# Energetic final demand of the 'fossil heat' carrier group

- unit = MJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :households"
            ),
            energetic?
          ),
          steam_hot_water?
        ),
        "(1 - sustainability_share) * value"
      )
    )
