# Direct conversion input of hydrogen for central electricity production

- query = 
    DIVIDE(
      SUM(
        V(
          G(electricity_production),
          "electricity_output_conversion / (1 - loss_output_conversion) * input_of_hydrogen"
        )
      ), 
      BILLIONS
    )
- unit = PJ
