# Direct conversion input of gas power fuelmix for central electricity production

- query =
    DIVIDE(
      SUM(
        V(
          G(electricity_production),
          "electricity_output_conversion / (1 - loss_output_conversion) * input_of_gas_power_fuelmix"
        )
      ), 
      BILLIONS
    )
- unit = PJ
