# Direct conversion input of biogenic waste for central electricity production

- query = 
    PRODUCT(
      Q(conversion_from_waste_mix_to_electricity),
      Q(share_of_biogenic_waste_in_waste_mix)
    )
- unit = PJ
