# Direct conversion input of wind for central electricity production
# For renewable energy carriers the output of electricity is taken by convention

- query = 
      DIVIDE(
        SUM(
          V(
            FILTER(G(electricity_production),"wind_input_conversion > 0.0"),
            output_of_electricity
          )
        ), 
        BILLIONS
      )
    
- unit = PJ
