# Direct conversion input of biomass products for central electricity production

- query =
    SUM(
      Q(conversion_from_biodiesel_to_electricity),
      Q(conversion_from_bio_ethanol_to_electricity),
      Q(conversion_from_bio_kerosene_to_electricity),
      Q(conversion_from_wood_pellets_to_electricity),
      Q(conversion_from_bio_lng_to_electricity),
      Q(conversion_from_bio_oil_to_electricity)
    )
- unit = PJ
