# Direct conversion input of coal and coal products for central electricity production

- query = 
    SUM(
      Q(conversion_from_coal_to_electricity),
      Q(conversion_from_coal_gas_to_electricity),
      Q(conversion_from_cokes_to_electricity),
      Q(conversion_from_lignite_to_electricity)
    )
- unit = PJ
