# Direct conversion input of wind for central electricity production
# For renewable energy carriers the output of electricity is taken by convention

- query = 
    SUM(
      DIVIDE(
        SUM(
          V(
            FILTER(G(electricity_production),"wind_input_conversion > 0.0"),
            output_of_electricity
          )
        ), 
        BILLIONS
      ),
      DIVIDE(
        SUM(
          V(
            FILTER(G(costs_production_dedicated_hydrogen_production),"wind_input_conversion > 0.0"),
            output_of_electricity
          )
        ), 
        BILLIONS
      )
    )
- unit = PJ
