# Direct conversion input of non biodiesel for central electricity production

- query = 
    DIVIDE(
      SUM(
        V(
          G(electricity_production),
          "electricity_output_conversion / (1 - loss_output_conversion) * input_of_biodiesel"
        )
      ), 
      BILLIONS
    )
- unit = PJ
