# Direct conversion input of oil and oil products for central electricity production

- query = 
    SUM(
      Q(conversion_from_crude_oil_to_electricity),
      Q(conversion_from_gasoline_to_electricity),
      Q(conversion_from_diesel_to_electricity),
      Q(conversion_from_lpg_to_electricity),
      Q(conversion_from_kerosene_to_electricity),
      Q(conversion_from_heavy_fuel_oil_to_electricity),
      PRODUCT(
        Q(conversion_from_gas_power_fuelmix_to_electricity),
        V(energy_mixer_for_gas_power_fuel, crude_oil_input_conversion)
      )
    )
- unit = PJ
