- query =  
        DIVIDE(
            SUM(
                V(
                    FILTER(G(costs_production_dedicated_hydrogen_production),"wind_input_conversion > 0.0"),
                    output_of_electricity
                )
            ), 
        BILLIONS
      ) 
- unit = PJ