# Direct conversion input of waste mix for central electricity production

- query =
    DIVIDE(
      SUM(
        V(
          G(electricity_production),
          "electricity_output_conversion / (1 - loss_output_conversion) * input_of_waste_mix"
        )
      ), 
      BILLIONS
    )
- unit = PJ
