- query =
    SUM(
      Q(heat_infrastructure_ht_distribution_pipelines_annualised_costs),
      Q(heat_infrastructure_ht_primary_pipelines_annualised_costs),
      Q(heat_infrastructure_ht_distribution_stations_annualised_costs),
      Q(heat_infrastructure_ht_indoor_annualised_costs)
    )
- unit = euro