# Output of steam_hot_water from energy_heat_heatpump_drink_water_water_ts_mt_electricity

- query =
    DIVIDE(
      V(energy_heat_heatpump_drink_water_water_ts_mt_electricity, output_of_steam_hot_water),
      BILLIONS
    )
- unit = PJ
