# Investment costs of the lt heat delivery systems for households.
# Investment costs are currently calculated only for buildings connected to a heat network

- unit = euro
- query =
    SUM(
        Q(households_lt_heat_delivery_system_costs_ground_level_houses),
        Q(households_lt_heat_delivery_system_costs_apartments)
    )