# Depreciation costs of the lt heat delivery systems for households.
# The lt heat delivery system is assumed to have the same technical lifetime as the lt heating network.

- unit = year
- query =
        V(energy_distribution_lt_steam_hot_water,technical_lifetime)