# Total investment costs of ht heat delivery systems in ground level houses.
# It is assumed that all residences in the ht heating network have ht heat delivery systems.

- unit = euro
- query =
    number_of_residences_in_ht_heating_network = V(households_space_heater_district_heating_ht_steam_hot_water,number_of_units);
    number_of_ground_level_houses = Q(number_of_detached_houses) + Q(number_of_semi_detached_houses) + Q(number_of_terraced_houses);
    share_of_ground_level_houses_in_residences = 
        DIVIDE(
            number_of_ground_level_houses,
            Q(number_of_residences)
        );
    number_of_ground_level_houses_with_ht_heat_delivery_systems =
        PRODUCT(
            number_of_residences_in_ht_heating_network,
            share_of_ground_level_houses_in_residences
        );
    
    PRODUCT(
        number_of_ground_level_houses_with_ht_heat_delivery_systems,
        AREA(households_ht_heat_delivery_system_costs_ground_level_houses_eur_per_connection)
    )
