- query =
    DIVIDE(
      SUM(
        V(energy_hydrogen_storage_depleted_gas_field, output_of_loss),
        V(energy_hydrogen_storage_salt_cavern, output_of_loss)
      ), 
      BILLIONS
    )
- unit = PJ