- unit = PJ
- query =
    SUM(
      Q(conversion_loss_hydrogen_to_bio_kerosene),
      Q(conversion_loss_hydrogen_to_biodiesel),
      Q(conversion_loss_hydrogen_to_bionaphtha),
      Q(conversion_loss_hydrogen_to_bio_ethanol)
    )
