- unit = PJ
- query =
    SUM(
      Q(conversion_loss_hydrogen_to_crude_oil),
      Q(conversion_loss_hydrogen_to_diesel),
      Q(conversion_loss_hydrogen_to_gasoline),
      Q(conversion_loss_hydrogen_to_heavy_fuel_oil),
      Q(conversion_loss_hydrogen_to_kerosene),
      Q(conversion_loss_hydrogen_to_lpg),
      Q(conversion_loss_hydrogen_to_naphtha),
      Q(conversion_loss_hydrogen_to_refinery_gas),
      Q(conversion_loss_hydrogen_to_fractionation_pyrolysis_oil)
    )
