# Loss of bio_pyrolysis_oil fractionation process from hydrogen input
# Loss associated with steam hot water production from hydrogen burner is included manually

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          FILTER(G(sankey_conversion_group),"bio_kerosene_output_conversion > 0.0 && hydrogen_input_conversion > 0.0"),
          "bio_kerosene_output_conversion * hydrogen_input_conversion / (1 - (loss_output_conversion + residual_heat_output_conversion)) * (output_of_loss + output_of_residual_heat)"
        ),
        PRODUCT(
          V(
            energy_production_fractionation_bio_pyrolysis_oil,
            "bio_kerosene_output_conversion * steam_hot_water_input_conversion / (1 - (loss_output_conversion + residual_heat_output_conversion)) * (output_of_loss + output_of_residual_heat)"
          ),
          V(EDGE(energy_production_fractionation_bio_pyrolysis_oil_burner_hydrogen,energy_production_bio_pyrolysis_locally_available_steam_hot_water),share)
        )
      ),
      BILLIONS
    )
