# Final consumption from industry ex. ict and refineries - aluminium, all carriers (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Aluminium -- EG(aluminium_industry)
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_industry_aluminium_energetic)
