# Final demand of the 'monetized_heat' carrier group

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(chemical_industry)
          ),
          steam_hot_water?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(chemical_industry)
          ),
          useable_heat?
        ),
        value
      )
    ) / BILLIONS
