# Final demand of the 'coal_and_derivatives' carrier group

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(other_industry)
          ),
          coal?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(other_industry)
          ),
          coal_gas?
        ),
        value
      )
    ) / BILLIONS
