# Final demand of the 'biomass_products' carrier group

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(chemical)
          ),
          biodiesel?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(chemical)
          ),
          bio_ethanol?
        ),
        value
      ),
      V(
        FILTER(
          INTERSECTION(
            LG(final_demand),LG(chemical)
          ),
          wood_pellets?
        ),
        value
      )
    ) / BILLIONS
