# Non_energetic final demand in the metal_industry sub-sector

- unit = pj
- query =
    SUM(
      Q(final_demand_of_biomass_products_in_metal_industry_non_energetic),
      Q(final_demand_of_coal_and_derivatives_in_metal_industry_non_energetic),
      Q(final_demand_of_electricity_in_metal_industry_non_energetic),
      Q(final_demand_of_environment_in_metal_industry_non_energetic),
      Q(final_demand_of_heat_in_metal_industry_non_energetic),
      Q(final_demand_of_natural_gas_and_derivatives_in_metal_industry_non_energetic),
      Q(final_demand_of_oil_and_derivatives_in_metal_industry_non_energetic)
    )
