# Non-energetic final demand of the 'environment' carrier group

- unit = pj
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(chemical)
            ),
            "not energetic?"
          ),
          ambient_heat?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(chemical)
            ),
            "not energetic?"
          ),
          ambient_cold?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(chemical)
            ),
            "not energetic?"
          ),
          solar_radiation?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(chemical)
            ),
            "not energetic?"
          ),
          solar_thermal?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              LG(final_demand),LG(chemical)
            ),
            "not energetic?"
          ),
          geothermal?
        ),
        value
      )
    ) / BILLIONS
