# Use of carrier group 'heat' in chemical industry heat

- unit = pj
- query =
    SUM(
      V(CHILDREN(V(industry_useful_demand_for_chemical_useable_heat)),input_of_steam_hot_water),
      V(CHILDREN(V(industry_useful_demand_for_chemical_useable_heat)),input_of_useable_heat)
    ) / BILLIONS
