- query =
    DIVIDE(
      SUM(
        V(
          energy_heat_solar_ht_solar_thermal,
          energy_heat_solar_mt_solar_thermal,
          energy_heat_solar_lt_solar_thermal,
          output_of_steam_hot_water
        )
      ),
      Q(factsheet_supply_heat_collective)
    ) * 100
- unit = %
