- query =
    SUM(
        V(energy_heat_burner_hydrogen,
          energy_heat_burner_network_gas,
          energy_heat_burner_wood_pellets,
          energy_heat_burner_crude_oil,
          energy_heat_burner_coal,
          energy_heat_burner_waste_mix,
          energy_heat_backup_burner_network_gas,
          industry_heat_burner_lignite,
          industry_heat_burner_coal,
          industry_heat_burner_crude_oil,
          industry_heat_backup_burner_network_gas,
          output_of_steam_hot_water)
    ) / Q(factsheet_supply_heat_collective) * 100.0

- unit = %
