- query =
          SUM(
              V(
              industry_heat_well_geothermal,
              energy_heat_well_deep_ht_geothermal,
              energy_heat_well_deep_mt_geothermal,
              energy_heat_well_shallow_heatpump_mt_geothermal,
              energy_heat_well_shallow_lt_geothermal,
              output_of_steam_hot_water
              ),
              V(agriculture_geothermal, output_of_useable_heat)
          )

- unit = MJ
