# Final demand of the 'coal_and_derivatives' carrier group

- unit = MJ
- query =
    SUM(
      V(G(final_demand_group), input_of_coal),
      V(G(final_demand_group), input_of_coal_gas),
      V(G(final_demand_group), input_of_cokes)
    )
