# Final demand of the 'natural_gas_and_derivatives' (excl. green gas) carrier group

- unit = MJ
- query =
    SUM( V(INTERSECTION(G(final_demand_group),USE(energetic)), input_of_network_gas).sum *
    V(energy_national_gas_network_natural_gas,natural_gas_input_conversion),
    V(INTERSECTION(G(final_demand_group),USE(energetic)), input_of_compressed_network_gas).sum *
    V(energy_national_gas_network_natural_gas,natural_gas_input_conversion),
    V(INTERSECTION(G(final_demand_group),USE(energetic)), input_of_lng).sum )
