# Final demand of liquid biomass products

- unit = MJ
- query =
    SUM(
      V(INTERSECTION(G(final_demand_group),USE(energetic)), input_of_bio_kerosene),
      V(INTERSECTION(G(final_demand_group),USE(energetic)), input_of_bio_lng),
      V(INTERSECTION(G(final_demand_group),USE(energetic)), input_of_bio_ethanol),
      V(INTERSECTION(G(final_demand_group),USE(energetic)), input_of_biodiesel),
      V(INTERSECTION(G(final_demand_group),USE(energetic)), input_of_bio_oil)
    )
