# Final demand of the 'oil_and_derivatives' carrier group

- unit = MJ
- query =
    SUM(
      V(G(final_demand_group), input_of_heavy_fuel_oil),
      V(G(final_demand_group), input_of_kerosene),
      V(G(final_demand_group), input_of_lpg),
      V(G(final_demand_group), input_of_diesel),
      V(G(final_demand_group), input_of_gasoline),
      V(G(final_demand_group), input_of_crude_oil)
    )
