
# Returns the capacity of coastal wind turbines for power production.
- query = 
        PRODUCT(
  		V(energy_power_wind_turbine_coastal,number_of_units),
  		V(energy_power_wind_turbine_coastal,electricity_output_capacity)	
  		)
- unit = MW


