# Use of carrier group 'ambient' in housholds heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater)),input_of_ambient_heat),
      V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater)),input_of_ambient_cold)
    ) / BILLIONS
