# Use of carrier group 'biomass_products' in housholds heat

- unit = PJ
- query =
    SUM(
      V(Q(heating_converters_in_households), input_of_biodiesel),
      V(Q(heating_converters_in_households), input_of_bio_ethanol),
      V(Q(heating_converters_in_households), input_of_wood_pellets),
      V(Q(heating_converters_in_households), input_of_bio_lng)
    ) / BILLIONS
