# Use of carrier group 'biomass_products' in housholds heat

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater_and_add_on)),input_of_biodiesel),
      V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater_and_add_on)),input_of_bio_ethanol),
      V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater_and_add_on)),input_of_wood_pellets),
      V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater_and_add_on)),input_of_bio_lng)
    ) / BILLIONS
