# Use of carrier group 'coal_and_derivatives' in housholds heat

- unit = PJ
- query =
    SUM(
      V(Q(heating_converters_in_households), input_of_coal),
      V(Q(heating_converters_in_households), input_of_coal_gas),
    ) / BILLIONS
