# Use of carrier group 'electricity' in housholds heat

- unit = pj
- query =
    SUM(
      V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater_and_add_on)),input_of_electricity)      
    ) / BILLIONS
