# Use of carrier group 'heat' in housholds heat

- unit = PJ
- query =
    SUM(
      V(Q(heating_converters_in_households), input_of_steam_hot_water),
      V(Q(heating_converters_in_households), input_of_useable_heat)
    ) / BILLIONS
