# Use of carrier group 'network_gas' in households heat

- query = 
    SUM(
      Q(final_demand_of_natural_gas_in_households_space_heating_energetic),
      Q(final_demand_of_greengas_in_households_space_heating_energetic),
    )
- unit = PJ
