# Use of carrier group 'solar' in housholds heat

- unit = PJ
- query =
    SUM(
      V(Q(heating_converters_in_households), input_of_solar_radiation),
      V(Q(heating_converters_in_households), input_of_solar_thermal)
    ) / BILLIONS
