# Total other GHG emissions for 1990 incl. indirect emissions (indirecte emissies), land
# use (landgebruik), international transport

- unit = MT
- query =
    SUM(
      Q(direct_emissions_klimaattafel_elektriciteit_other_ghg_1990),
      Q(direct_emissions_klimaattafel_industrie_other_ghg_1990),
      Q(direct_emissions_klimaattafel_mobiliteit_other_ghg_1990),
      Q(direct_emissions_klimaattafel_gebouwde_omgeving_other_ghg_1990),
      Q(direct_emissions_klimaattafel_landbouw_other_ghg_1990),
      Q(direct_emissions_klimaattafel_landgebruik_other_ghg_1990),
      Q(direct_emissions_klimaattafel_indirecte_emissies_other_ghg_1990),
      Q(direct_emissions_klimaattafel_internationaal_transport_other_ghg_1990)
    )
