# Energetic final demand of the 'electricity' carrier group in households space_heating and hot_water

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_electricity_in_households_space_heating_energetic),
      Q(final_demand_of_electricity_in_households_hot_water_energetic)
    )
