# Energetic final demand of the 'natural_gas' carrier group in households appliances, cooking, cooling and lighting

- unit = PJ
- query =
    SUM(
      Q(natural_gas_to_households_appliances_in_sankey),
      Q(natural_gas_to_households_cooking_in_sankey),
      Q(natural_gas_to_households_cooling_in_sankey),
      Q(natural_gas_to_households_lighting_in_sankey),
      Q(final_demand_of_lng_in_households_appliances_energetic),
      Q(final_demand_of_lng_in_households_cooking_energetic),
      Q(final_demand_of_lng_in_households_cooling_energetic),
      Q(final_demand_of_lng_in_households_lighting_energetic)
    )
