# Energetic final demand of the 'natural_gas' carrier group in households space_heating and hot_water

- unit = PJ
- query =
    SUM(
      Q(natural_gas_to_households_space_heating_in_sankey),
      Q(natural_gas_to_households_hot_water_in_sankey),
      Q(final_demand_of_lng_in_households_space_heating_energetic),
      Q(final_demand_of_lng_in_households_hot_water_energetic)
    )
