# Energetic final demand of the 'oil_and_derivatives' carrier group in households space_heating and hot_water

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_oil_and_derivatives_in_households_space_heating_energetic),
      Q(final_demand_of_oil_and_derivatives_in_households_hot_water_energetic)
    )
