# Depreciation costs of main distribution pipelines for households, 
# based on the distribution pipelines investment costs by share of household heat demand in the distribution network (used by households and buildings),
# and the connection pipelines investment costs (connection pipelines are used by households only).

- unit = euro
- query =
    demand_share_of_households_in_distribution_network = 
      DIVIDE(
        V(households_final_demand_ht_steam_hot_water,demand),
        SUM(
          V(households_final_demand_ht_steam_hot_water,demand),
          V(buildings_final_demand_ht_steam_hot_water,demand),
        )
      );

      households_ht_distribution_pipelines_investment_costs =
        PRODUCT(
          Q(heat_infrastructure_ht_distribution_pipelines_investment_costs),
          demand_share_of_households_in_distribution_network
        );
      
    households_ht_total_distribution_pipelines_investment_costs = 
      SUM(
        households_ht_distribution_pipelines_investment_costs,
        Q(heat_infrastructure_ht_connection_pipelines_investment_costs)
      );

    DIVIDE(
      households_ht_total_distribution_pipelines_investment_costs,
      V(energy_distribution_ht_steam_hot_water,technical_lifetime)
    )