
# Energetic final demand of electricity in agriculture excluding heating

- unit = PJ
- query =
    DIVIDE(
        V(agriculture_useful_demand_electricity
          input_of_electricity),
      BILLIONS
    )


