# Outputs the nodes that generate heat from drinking water for lt and mt heat networks

- query =
    INTERSECTION(
        PARENTS(V(energy_production_drink_water_ambient_heat)),
        SECTOR(energy)
    )
- unit = nodes