# Retrieves the region's potential for aquathermal surface water, if it exists

- query = 
    IF(
        AREA(has_aquathermal_potential_for_surface_water),
        AREA(aquathermal_potential_for_surface_water),
        0
    )
- unit = PJ