# Retrieves the region's potential for aquathermal drinking water, if it exists

- query = 
    IF(
        AREA(has_aquathermal_potential_for_drink_water),
        AREA(aquathermal_potential_for_drink_water),
        0
    )
- unit = PJ