# Retrieves the region's potential for aquathermal waste water, if it exists

- query = 
    IF(
        AREA(has_aquathermal_potential_for_waste_water),
        AREA(aquathermal_potential_for_waste_water),
        0
    )
- unit = PJ