# Returns the capacity of geothermal power plants.
- query = 
        PRODUCT(
  		V(energy_power_geothermal,number_of_units),
  		V(energy_power_geothermal,electricity_output_capacity)	
  		)
- unit = MW





