# Direct conversion input of bio_kerosene for natural_gas production

- query =
    DIVIDE(
      SUM(
        V(
          G(natural_gas_production),
          "greengas_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_bio_kerosene"
        )
      ),
      BILLIONS
    )
- unit = PJ
