- query = 
    SUM(
        Q(useful_demand_apartments_1965_1984),
        Q(useful_demand_detached_houses_1965_1984),
        Q(useful_demand_semi_detached_houses_1965_1984),
        Q(useful_demand_terraced_houses_1965_1984)
        )

- unit = PJ

