# Returns the costs for transit flows of heavy fuel oil
- query = 
    transit_costs_heavy_fuel_oil_eur_per_mj = 0.0001;
    PRODUCT(V(energy_export_heavy_fuel_oil_baseload,demand), transit_costs_heavy_fuel_oil_eur_per_mj)
- unit = euro