# Returns the costs for transit flows of lignite
- query = 
    transit_costs_lignite_eur_per_mj = 0.0001;
    PRODUCT(V(energy_export_lignite_baseload,demand), transit_costs_lignite_eur_per_mj)
- unit = euro