# Returns the costs for transit flows of ammonia
- query = 
    transit_costs_ammonia_eur_per_mj = 0.0001;
    PRODUCT(V(energy_export_ammonia_baseload,demand), transit_costs_ammonia_eur_per_mj)
- unit = euro