# Returns the costs for transit flows of hydrogen
- query = 
    transit_costs_hydrogen_eur_per_mj = 0.0001;
    PRODUCT(V(energy_export_hydrogen_baseload,demand), transit_costs_hydrogen_eur_per_mj)
- unit = euro