# Returns the costs for transit flows of crude oil
- query = 
    transit_costs_crude_oil_eur_per_mj = 0.0001;
    PRODUCT(V(energy_export_crude_oil_baseload,demand), transit_costs_crude_oil_eur_per_mj)
- unit = euro