# Percentage of final demand of solar in renewability

- unit = factor
- query =
    100 * SUM(
        V(INTERSECTION(G(final_demand_group),USE(energetic)), "sustainability_share * demand_of_solar_radiation"),
        V(INTERSECTION(G(final_demand_group),USE(energetic)), "sustainability_share * demand_of_solar_thermal")
    ) / 
    SUM(
        V(INTERSECTION(G(final_demand_group),USE(energetic)), demand),
        Q(ambient_heat_pumped_by_heat_pumps),
        Q(geothermal_own_use_in_sectors)
    )
