# Investment costs for this part of the heat network. Also used in the ETM costs export.

- query =
    SUM(
      Q(heat_infrastructure_lt_exchanger_station_investment_costs),
      Q(heat_infrastructure_lt_sub_station_investment_costs)
      )
- unit = euro
