# Energetic final demand of the 'electricity' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              EG(final_demand),EG(food_industry)
            ),
            energetic?
          ),
          electricity?
        ),
        value
      )
    ) / BILLIONS
