# Non-energetic final demand of the 'natural_gas_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              EG(final_demand),EG(ict_industry)
            ),
            "! energetic?"
          ),
          network_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              EG(final_demand),EG(ict_industry)
            ),
            "! energetic?"
          ),
          compressed_network_gas?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              EG(final_demand),EG(ict_industry)
            ),
            "! energetic?"
          ),
          lng?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              EG(final_demand),EG(ict_industry)
            ),
            "! energetic?"
          ),
          propane?
        ),
        value
      )
    ) / BILLIONS
