# Energetic final demand of the 'methanol' carrier group in industry ict

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(ict_industry)), "methanol?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
