# Non-energetic final demand of the 'waste_mix' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          INTERSECTION(
            EG(final_demand),EG(other_non_specified_industry)
          ),
          waste_mix?
        ),
        value
      )
    ) / BILLIONS
