# Max value is double of the number of units or the demand divided by typical production

- query =
    MAX(
    PRODUCT(V(agriculture_chp_supercritical_wood_pellets,number_of_units),2),
    PRODUCT(DIVIDE(V(agriculture_useful_demand_electricity,demand),V(agriculture_chp_supercritical_wood_pellets, typical_electricity_production_per_unit)),2)
    )
- unit = #
