# Max value is one unit or the demand divided by typical production

- query =
    MAX(
    1.0,
    PRODUCT(DIVIDE(V(agriculture_useful_demand_electricity,demand),V(agriculture_chp_engine_network_gas, maximum_yearly_electricity_production_per_unit)),2)
    )
- unit = #
- deprecated_key = max_value_chp_agri
