# Max value is 1 unit or the demand divided by typical production

- query =
    MAX(
    1.0,
    PRODUCT(DIVIDE(V(agriculture_useful_demand_electricity,demand),V(agriculture_chp_engine_biogas, maximum_yearly_electricity_production_per_unit)),2)
    )
- unit = #
