- deprecated_key = max_value_chp_other
# Max value is double of the number of plants or the demand divided by typical production

- unit = #

MAX(
PRODUCT(V(chp_other_other_energetic;number_of_units),2)
,
DIVIDE(V(electricity_demand_other_energetic;demand*99),V(chp_other_other_energetic; typical_electricity_production_per_unit*50))
)