# Potential of residual heat from P2G electrolyser hydrogen production

- unit = PJ
- query =
    DIVIDE(
      V(energy_hydrogen_flexibility_p2g_potential_residual_heat,input_of_residual_heat),
      BILLIONS
    )

