# Potential of residual heat from the fertilizer industry

- unit = PJ
- query =
    DIVIDE(
      V(industry_chemicals_fertilizers_potential_residual_heat, input_of_residual_heat),
      BILLIONS
    )
