# Final consumption of geothermal in industry ex. ict and refineries - chemicals (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Chemicals -- EG(other_chemical_industry)
# Carrier:     Geothermal -- geothermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_geothermal_in_industry_other_chemical_energetic)
