# This gives the installed capacity of solar and wind power

- query =
    V(
      Q(electricity_producing_solar_converters),
      Q(electricity_producing_wind_converters),
      installed_production_capacity_in_mw_electricity
    ).sum / THOUSANDS
- unit = gw
