- unit = PJ
- query = 
      DIVIDE(
        SUM(
          V(
            FILTER(
              SECTOR(bunkers),
              "hydrogen && (hydrogen.type == :consumer)"
              ),
            input_of_hydrogen)
        ),
        BILLIONS
    )
