- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(EDGE(energy_power_turbine_hydrogen,energy_hydrogen_after_distribution), demand),
            V(EDGE(energy_power_combined_cycle_hydrogen,energy_hydrogen_after_distribution), demand)
        ),
        BILLIONS
    )
