- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          energy_production_hvo_biodiesel,
          energy_production_hvo_bio_kerosene,
          input_of_hydrogen
        )
      ),
      BILLIONS
    )
