- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(EDGE(energy_power_turbine_hydrogen,energy_distribution_hydrogen_after_transport), demand),
            V(EDGE(energy_power_combined_cycle_hydrogen,energy_distribution_hydrogen_after_transport), demand)
        ),
        BILLIONS
    )
