- unit = PJ
- query = 
    DIVIDE(
        SUM(
            V(energy_transport_hydrogen_pipelines,output_of_loss),
            V(energy_transport_hydrogen_compressed_trucks,output_of_loss)
        ),BILLIONS
    )
