- unit = PJ
- query = 
    DIVIDE(
        SUM(
            V(energy_hydrogen_transport_pipelines,output_of_loss),
            V(energy_hydrogen_distribution_compressed_trucks,output_of_loss)
        ),BILLIONS
    )
