# Returns the produced electricity using biocoal.
# 
# It works by looking to converters directly fed by the "biocoal distribution" converter that have output of electricity.

- unit = mj

SUM(
  V(
     Q(electricity_producing_converters_biocoal)
     ;output_of_electricity * biocoal_input_conversion
    )
   )


