- query =
    FILTER(
      FILTER(
        G(heat_production),"heat_network_lt"
      ),
      "biodiesel_input_conversion > 0.0 || bio_ethanol_input_conversion > 0.0 || wood_pellets_input_conversion > 0.0 || bio_lng_input_conversion > 0.0"
    )
- unit = nodes
