- query =
    FILTER(
      FILTER(
        G(heat_production),"heat_network_lt"
      ),
      "coal_input_conversion > 0.0 || coal_gas_input_conversion > 0.0 || lignite_input_conversion > 0.0"
    )
- unit = nodes
