- deprecated_key = pl_mv_t_net_delta_capacity_max
# No technologies connected to mv-t net therefore delta capacity max is equal to impact on mv-d net * simult 

- unit = mw

PRODUCT(
  Q(mv_d_net_delta_capacity_max),
  V( mv_distribution_network_energy_energetic , simult_wd )
)