- query =
    SUM(
      INPUT_VALUE(households_demolished_before_1945),
      INPUT_VALUE(households_demolished_1945_1964),
      INPUT_VALUE(households_demolished_1965_1984),
      INPUT_VALUE(households_demolished_1985_2004),
      INPUT_VALUE(households_demolished_2005_present)
    )
- unit = #
