- query =
    EXCLUDE(
        EXCLUDE(
            INTERSECTION(
                G(other_industry),G(useful_demand)
            ),
            G(food_industry)),
        G(paper_industry)
    )
- unit = converters
