- query =
    V(
      households_cooling_heatpump_ground_water_electricity,
      households_cooling_heatpump_air_water_electricity,
      households_cooling_airconditioning_electricity
    )
- unit = converters
- deprecated_key = households_cooling_converters
