- deprecated_key = gas_plants
# 

- unit = converters

V(
  gas_conv_energy_energetic,
  gas_ccgt_energy,
  small_chp_industry_energetic,
  central_gas_chp_energy_energetic,
  micro_chp_space_heating_households,
  collective_gas_chp_households_energetic,
  gas_chp_buildings_energetic,
  chp_agri_agriculture_energetic,
  chp_other_other_energetic,
  ccgt_ccs_energy,
  fuel_cell_chp_households_energetic
)
  