# Returns the converters which produce electricity using oil products

- query = 
    FILTER(G(electricity_production), "crude_oil_input_conversion > 0") + 
    FILTER(G(electricity_production), "diesel_input_conversion > 0")
- unit = converters
- deprecated_key = electricity_producing_converters_oil
