# Returns the converters which produce electricity using oil. It works by looking to converters directly fed by the "oil_distribution_energy" converter that have output of electricity.

- deprecated_key = electricity_producing_converters_oil
- unit = converters

FILTER(G(electricity_production), crude_oil_input_conversion > 0)