- deprecated_key = coal_plants
# 

- unit = converters

V(
  coal_pwd_energy,
  coal_pwd_ccs_energy,
  coal_conv_energy,
  coal_lignite_energy,
  coal_oxyfuel_ccs_energy,
  coal_igcc_energy,
  coal_igcc_ccs_energy,
  coal_chp_energy,
  lignite_chp_energy
)