# Returns the converters which produce electricity using wood_pellets. It works by looking to converters directly fed by the "wood_pellets_distribution" converter that have output of electricity.

- query = FILTER(G(electricity_production), "wood_pellets_input_conversion > 0")
- unit = converters
