- deprecated_key = other_plants
# 

- unit = converters

V(
  waste_incinerator_energy_energetic,
  solar_pv_central_production_energy_energetic,
  solar_csp_energy,
  hydro_river_energy,
  hydro_mount_energy,
  geothermal_electricity_energy,
  blue_energy_energy,
  local_solar_pv_grid_connected_energy_energetic,
  local_solar_pv_not_grid_connected_energy_energetic,
  solar_panels_buildings_energetic
)