# All plants including

- query =
    V(
      Q(electricity_producing_coal_incl_coal_gas_converters),
      Q(electricity_producing_lignite_converters),
      Q(electricity_producing_oil_converters),
      Q(electricity_producing_gas_converters),
      Q(electricity_producing_nuclear_converters),
      Q(electricity_producing_wind_converters),
      Q(electricity_producing_wood_pellets_converters),
      Q(electricity_producing_other_converters)
    )
- unit = nodes
- deprecated_key = all_plants
