- unit = converters
- query =
  EXCLUDE(
    G(energy_export),
    V(
      energy_export_heavy_fuel_oil,
      energy_export_kerosene,
      energy_export_gasoline,
      energy_export_diesel,
      energy_export_lpg
    )
  )
