- deprecated_key = buildings_heating_converters
# 

- unit = converters

V(
gas_fired_heater_buildings_energetic,
electric_heater_buildings_energetic,
solarthermic_buildings_energetic,
gasheatpump_ts_buildings_energetic,
wood_pellets_fired_heater_buildings_energetic,
heatpump_ts_buildings_energetic,
oil_heater_buildings_energetic,
coal_heater_buildings_energetic,
gas_chp_buildings_energetic,
coal_chp_buildings_energetic,
biomass_chp_buildings_energetic,
local_heat_network_buildings_energetic
)
