- query =
    V(
      EXCLUDE(
        CHILDREN(CHILDREN(V(buildings_useful_demand_for_space_heating_after_insulation_and_solar_thermal))),
        V(buildings_space_heater_deficit)
      ),
      buildings_space_heater_solar_thermal
    )
- unit = converters
- deprecated_key = buildings_heating_converters
