- query =
    V(
      FILTER(
        ALL(),
        "fever && (fever.group == :buildings_space_heating && fever.type == :producer)"
      ),
      buildings_space_heater_solar_thermal
    )
- unit = nodes
