- query =
    EXCLUDE(
      CHILDREN(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation))),
      V(households_space_heater_deficit)
    )
- unit = nodes
- deprecated_key = households_heating_converters
