- deprecated_key = micro_chp
# Combination of the micro CHP for hot water, the production unit and the backup burner.

- unit = converters

V(micro_chp_hot_water_households_energetic,
micro_chp_space_heating_households)