# Combination of the micro CHP for hot water, the production unit and the backup burner.

- query =
    V(
      households_water_heater_micro_chp_network_gas,
      households_space_heater_micro_chp_network_gas
    )
- unit = converters
- deprecated_key = micro_chp
