- query =
    V(
      energy_battery_curtailed_solar_electricity,
      energy_battery_curtailed_wind_electricity,
      energy_battery_solar_electricity,
      energy_battery_unused_electricity,
      energy_battery_wind_electricity,
      energy_blastfurnace_transformation_cokes,
      energy_chp_coal_gas,
      energy_chp_combined_cycle_network_gas,
      energy_chp_local_engine_biogas,
      energy_chp_local_engine_network_gas,
      energy_chp_local_wood_pellets,
      energy_chp_supercritical_ccs_waste_mix,
      energy_chp_supercritical_waste_mix,
      energy_chp_ultra_supercritical_coal,
      energy_chp_ultra_supercritical_cofiring_coal,
      energy_chp_ultra_supercritical_lignite,
      energy_cokesoven_transformation_coal,
      energy_compressor_network_gas,
      energy_distribution_ammonia,
      energy_distribution_bio_ethanol,
      energy_distribution_bio_kerosene,
      energy_distribution_bio_lng,
      energy_distribution_bio_oil,
      energy_distribution_biodiesel,
      energy_distribution_biogas,
      energy_distribution_biogenic_waste,
      energy_distribution_coal,
      energy_distribution_coal_gas,
      energy_distribution_cokes,
      energy_distribution_crude_oil,
      energy_distribution_crude_oil_loss,
      energy_distribution_diesel,
      energy_distribution_dry_biomass,
      energy_distribution_gasoline,
      energy_distribution_greengas,
      energy_distribution_heavy_fuel_oil,
      energy_distribution_hydrogen_after_transport,
      energy_distribution_hydrogen_before_transport,
      energy_distribution_imported_heat,
      energy_distribution_kerosene,
      energy_distribution_lignite,
      energy_distribution_lng,
      energy_distribution_lpg,
      energy_distribution_network_gas_loss,
      energy_distribution_non_biogenic_waste,
      energy_distribution_oily_biomass,
      energy_distribution_steam_hot_water,
      energy_distribution_torrefied_biomass_pellets,
      energy_distribution_uranium_oxide,
      energy_distribution_waste_mix,
      energy_distribution_wet_biomass,
      energy_distribution_wood_pellets,
      energy_flexibility_curtailment_electricity,
      energy_flexibility_flow_batteries_electricity,
      energy_flexibility_hv_opac_electricity,
      energy_flexibility_mv_batteries_electricity,
      energy_flexibility_pumped_storage_electricity,
      energy_flexibility_solar_batteries_electricity,
      energy_flexibility_wind_batteries_electricity,
      energy_greengas_upgrade_biogas,
      energy_heat_backup_burner_network_gas,
      energy_heat_burner_coal,
      energy_heat_burner_crude_oil,
      energy_heat_burner_hydrogen,
      energy_heat_burner_network_gas,
      energy_heat_burner_waste_mix,
      energy_heat_burner_wood_pellets,
      energy_heat_distribution_loss,
      energy_heat_flexibility_p2h_boiler_electricity,
      energy_heat_flexibility_p2h_heatpump_electricity,
      energy_heat_heatpump_water_water_electricity,
      energy_heat_import_steam_hot_water,
      energy_heat_industry_chemicals_fertilizers_residual_heat,
      energy_heat_industry_chemicals_other_residual_heat,
      energy_heat_industry_chemicals_refineries_residual_heat,
      energy_heat_industry_other_ict_residual_heat,
      energy_heat_network_storage,
      energy_heat_unused_steam_hot_water,
      energy_heat_well_geothermal,
      energy_hydrogen_ammonia_reformer,
      energy_hydrogen_autothermal_reformer,
      energy_hydrogen_autothermal_reformer_ccs,
      energy_hydrogen_biomass_gasification,
      energy_hydrogen_biomass_gasification_ccs,
      energy_hydrogen_curtailed_electricity,
      energy_hydrogen_electrolysis_solar_electricity,
      energy_hydrogen_electrolysis_wind_electricity,
      energy_hydrogen_flexibility_p2g_electricity,
      energy_hydrogen_steam_methane_reformer,
      energy_hydrogen_steam_methane_reformer_ccs,
      energy_hydrogen_storage,
      energy_imported_ammonia_backup,
      energy_imported_ammonia_baseload,
      energy_imported_hydrogen_backup,
      energy_imported_hydrogen_baseload,
      energy_interconnector_10_exported_electricity,
      energy_interconnector_10_imported_electricity,
      energy_interconnector_11_exported_electricity,
      energy_interconnector_11_imported_electricity,
      energy_interconnector_12_exported_electricity,
      energy_interconnector_12_imported_electricity,
      energy_interconnector_1_exported_electricity,
      energy_interconnector_1_imported_electricity,
      energy_interconnector_2_exported_electricity,
      energy_interconnector_2_imported_electricity,
      energy_interconnector_3_exported_electricity,
      energy_interconnector_3_imported_electricity,
      energy_interconnector_4_exported_electricity,
      energy_interconnector_4_imported_electricity,
      energy_interconnector_5_exported_electricity,
      energy_interconnector_5_imported_electricity,
      energy_interconnector_6_exported_electricity,
      energy_interconnector_6_imported_electricity,
      energy_interconnector_7_exported_electricity,
      energy_interconnector_7_imported_electricity,
      energy_interconnector_8_exported_electricity,
      energy_interconnector_8_imported_electricity,
      energy_interconnector_9_exported_electricity,
      energy_interconnector_9_imported_electricity,
      energy_methanol_production_coal_gas,
      energy_mixer_for_gas_power_fuel,
      energy_national_gas_network_natural_gas,
      energy_network_gas_storage,
      energy_power_combined_cycle_ccs_coal,
      energy_power_combined_cycle_ccs_network_gas,
      energy_power_combined_cycle_coal,
      energy_power_combined_cycle_coal_gas,
      energy_power_combined_cycle_hydrogen,
      energy_power_combined_cycle_network_gas,
      energy_power_engine_diesel,
      energy_power_engine_network_gas,
      energy_power_hv_network_electricity,
      energy_power_hv_network_loss,
      energy_power_hv_network_shortage,
      energy_power_lv_network_electricity,
      energy_power_mv_distribution_network_electricity,
      energy_power_mv_transport_network_electricity,
      energy_power_nuclear_gen2_uranium_oxide,
      energy_power_nuclear_gen3_uranium_oxide,
      energy_power_nuclear_small_modular_reactor_uranium_oxide,
      energy_power_supercritical_ccs_waste_mix,
      energy_power_supercritical_coal,
      energy_power_supercritical_waste_mix,
      energy_power_transformer_lv_mv_electricity,
      energy_power_transformer_mv_hv_electricity,
      energy_power_turbine_hydrogen,
      energy_power_turbine_network_gas,
      energy_power_ultra_supercritical_ccs_coal,
      energy_power_ultra_supercritical_coal,
      energy_power_ultra_supercritical_cofiring_coal,
      energy_power_ultra_supercritical_crude_oil,
      energy_power_ultra_supercritical_lignite,
      energy_power_ultra_supercritical_network_gas,
      energy_power_ultra_supercritical_oxyfuel_ccs_lignite,
      energy_production_aggregator_steam_hot_water,
      energy_production_synthetic_kerosene,
      energy_production_synthetic_kerosene_electricity,
      energy_production_synthetic_kerosene_hydrogen_non_energetic,
      energy_regasification_lng,
      energy_synthetic_products_electricity,
      energy_synthetic_products_hydrogen_non_energetic,
      energy_transmission_steam_hot_water,
      energy_transport_hydrogen_compressed_trucks,
      energy_transport_hydrogen_loss,
      energy_transport_hydrogen_pipelines,
      energy_treatment_natural_gas,
      agriculture_locally_available_steam_hot_water,
      agriculture_locally_available_electricity,
      agriculture_chp_engine_network_gas_dispatchable,
      agriculture_chp_engine_network_gas_must_run,
      agriculture_chp_engine_biogas,
      agriculture_chp_wood_pellets,
      agriculture_heat_backup_burner_network_gas,
      buildings_local_production_electricity,
      industry_locally_available_steam_hot_water,
      industry_locally_available_electricity,
      industry_chp_turbine_hydrogen,
      industry_chp_engine_gas_power_fuelmix,
      industry_chp_turbine_gas_power_fuelmix,
      industry_chp_ultra_supercritical_coal,
      industry_chp_combined_cycle_gas_power_fuelmix,
      industry_chp_wood_pellets,
      industry_heat_burner_lignite,
      industry_heat_burner_coal,
      industry_heat_well_geothermal,
      industry_heat_burner_crude_oil,
      industry_heat_backup_burner_network_gas,
      industry_heat_burner_hydrogen,
      industry_locally_available_crude_oil_non_energetic_for_chemical,
      industry_locally_available_refinery_gas_for_chemical,
      industry_refinery_transformation_crude_oil,
      industry_useful_demand_for_chemical_refineries_crude_oil_non_energetic
    )
- unit = nodes
