# Nodes that constitute heat_network supply. Includes nodes which participate as producers in time-resolved heat_network.

- query =
    FILTER(
      ALL(),
      "heat_network_mt && (heat_network_mt.type == :producer)"
    )
- unit = nodes
