# Nodes that constitute inflexible heat_network_mt supply. Includes nodes which participate as time-resolved volatile and must-run heat_network producers and export.

- query =
    EXCLUDE(
      FILTER(
        ALL(),
        "heat_network_mt && (heat_network_mt.subtype == :must_run)"
      ),
      FILTER(
        ALL(),
        "merit_order && (merit_order.subtype == :dispatchable || merit_order.type ==:flex)"
      )
    )
- unit = nodes
