# Nodes that constitute inflexible heat_network supply. Includes nodes which participate as time-resolved volatile and must-run heat_network producers and import.

- query =
    FILTER(
      ALL(),
      "heat_network_mt && (heat_network_mt.subtype == :must_run)"
    )
- unit = nodes
