# Nodes that constitute hydrogen demand. Includes nodes which participate as consumers in time-resolved hydrogen and export.

- query =
    FILTER(
      ALL(),
      "hydrogen && (hydrogen.type == :consumer)"
    )
- unit = nodes
