# Nodes that constitute inflexible network_gas demand. Includes nodes which participate as inflexible consumers in time-resolved network_gas and export.

- query =
    FILTER(
      ALL(),
      "network_gas && (network_gas.type == :consumer || network_gas.type == :export)"
    )
- unit = nodes
