# Nodes that constitute flexible heat_network supply. Includes nodes which participate as time-resolved flexible heat_network producers and storage.

- query =
    EXCLUDE(
      FILTER(
        ALL(),
        "heat_network_mt && (heat_network.type == :producer || heat_network_mt.subtype == :heat_storage)"
      ),
      FILTER(
        ALL(),
        "heat_network_mt && (heat_network_mt.subtype == :must_run)"
      )
    )
- unit = nodes
