# Nodes that constitute inflexible hydrogen supply. Includes nodes which participate as time-resolved inflexible hydrogen production and import.

- query =
    FILTER(
      ALL(),
      "hydrogen && (hydrogen.type == :producer || hydrogen.type == :import)"
    )
- unit = nodes
