# Nodes that constitute inflexible network_gas demand. Includes nodes which participate as inflexible consumers in time-resolved network_gas and export. Excludes all flexible nodes.

- query =
    EXCLUDE(
      FILTER(
        ALL(),
        "network_gas && (network_gas.type == :consumer || network_gas.type == :export)"
      ),
      V(
        INTERSECTION(
          FILTER(
            ALL(),
            "network_gas && (network_gas.type == :consumer)"
          ),
          FILTER(
            ALL(),
            "merit_order && (merit_order.subtype == :dispatchable)"
          )
        ),
        INTERSECTION(
          FILTER(
            ALL(),
            "network_gas && (network_gas.type == :consumer)"
          ),
          FILTER(
            ALL(),
            "heat_network && (heat_network.subtype == :dispatchable)"
          )
        ),
        energy_heat_backup_burner_network_gas,
        industry_heat_backup_burner_network_gas,
        FILTER(
          ALL(),
          "network_gas && (network_gas.type == :storage)"
        )
      )
    )
- unit = nodes