# Nodes that constitute flexible network_gas supply. Includes nodes which participate in time-resolved network_gas storage.

- query =
    FILTER(
      ALL(),
      "network_gas && (network_gas.type == :storage)"
    )
- unit = nodes