# Nodes that constitute inflexible hydrogen supply. Includes nodes which participate as time-resolved inflexible hydrogen production and import.

- query =
    EXCLUDE(
      FILTER(
        ALL(),
        "hydrogen && (hydrogen.type == :producer || hydrogen.type == :import)"
      ),
      FILTER(
        ALL(),
        "merit_order && (merit_order.subtype == :power_to_gas)"
      )
    )
- unit = nodes
