# Nodes that constitute flexible network_gas demand. Includes nodes which participate as flexible consumers in time-resolved network_gas and storage.

- query =
    FILTER(
      ALL(),
      "network_gas && (network_gas.type == :storage)"
    )
- unit = nodes
