# Nodes that constitute heat_network supply. Includes nodes which participate as producers in time-resolved heat_network.

- query =
    FILTER(
      ALL(),
      "heat_network_lt && (heat_network_lt.type == :producer)"
    )
- unit = nodes
