# Nodes that constitute flexible hydrogen demand. Includes nodes which participate as time-resolved flexible storage.

- query =
    FILTER(
      ALL(),"hydrogen && (hydrogen.type == :storage)"
    )
- unit = nodes
