# Nodes that constitute flexible heat_network supply. Includes nodes which participate as time-resolved flexible heat_network producers and storage.

- query =
    EXCLUDE(
      FILTER(
        ALL(),
        "
          (heat_network_ht && (heat_network_ht.type == :producer || heat_network_ht.subtype == :heat_storage)) ||
          (heat_network_mt && (heat_network_mt.type == :producer || heat_network_mt.subtype == :heat_storage)) ||
          (heat_network_lt && (heat_network_lt.type == :producer || heat_network_lt.subtype == :heat_storage))
        "
      ),
      FILTER(
        ALL(),
        "
          (heat_network_ht && (heat_network_ht.subtype == :must_run)) ||
          (heat_network_mt && (heat_network_mt.subtype == :must_run)) ||
          (heat_network_lt && (heat_network_lt.subtype == :must_run))
        "
      )
    )
- unit = nodes
