# Nodes that constitute hydrogen supply. Includes nodes which participate as producers in time-resolved hydrogen and import.

- query =
    FILTER(
      ALL(),
      "hydrogen && (hydrogen.type == :producer || hydrogen.type == :flex)"
    )
- unit = nodes
