# Nodes that constitute inflexible heat_network demand. Includes nodes which participate as time-resolved inflexible heat_network consumers.

- query =
    FILTER(
      ALL(),
      "
        (heat_network_ht && (heat_network_ht.type == :consumer)) ||
        (heat_network_mt && (heat_network_mt.type == :consumer)) ||
        (heat_network_lt && (heat_network_lt.type == :consumer))
      "
    )
- unit = nodes
