# Nodes that constitute heat_network demand. Includes nodes which participate as consumers and flex in time-resolved heat_network.

- query =
    FILTER(
      ALL(),
      "heat_network_lt && (heat_network_lt.type == :consumer)"
    )
- unit = nodes
