# Energetic demand of biodiesel for shipping transport

- query = 
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              EG(final_demand),EG(shipping_transport)
            ),
            energetic?
          ),
          biodiesel?
        ),
        value
      )
    )
- unit = MJ
