# Returns the capacity of ultra supercritical ht lignite plants with for the sector energy.
- query = 
        PRODUCT(
  		V(energy_chp_ultra_supercritical_ht_lignite,number_of_units),
  		V(energy_chp_ultra_supercritical_ht_lignite,electricity_output_capacity)	
  		)
- unit = MW
