- query =
    SUM_CURVES(
      V(energy_chp_ultra_supercritical_cofiring_ht_coal, electricity_output_curve),
      V(energy_chp_ultra_supercritical_cofiring_mt_coal, electricity_output_curve)
    )
- unit = curve
