- query =
    SUM_CURVES(
      V(energy_chp_ultra_supercritical_ht_lignite, electricity_output_curve),
      V(energy_chp_ultra_supercritical_mt_lignite, electricity_output_curve)
    )
- unit = curve
