- query =
    SUM_CURVES(
      V(energy_chp_local_ht_wood_pellets, electricity_output_curve),
      V(energy_chp_local_mt_wood_pellets, electricity_output_curve),
      V(energy_chp_local_ht_biomass_electricity_only,electricity_output_curve)
    )
- unit = curve
