- query =
    [MERIT_LOAD_CURVES(:industry_chemicals_other_flexibility_p2h_electricity),MERIT_LOAD_CURVES(:industry_chemicals_refineries_flexibility_p2h_electricity),MERIT_LOAD_CURVES(:industry_other_food_flexibility_p2h_electricity),MERIT_LOAD_CURVES(:industry_other_paper_flexibility_p2h_electricity)].transpose.map {|x| x.reduce(:+)}