# Energetic final demand of the 'ammonia' carrier group in households appliances, cooking, cooling and lighting

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_ammonia_in_households_appliances_energetic),
      Q(final_demand_of_ammonia_in_households_cooking_energetic),
      Q(final_demand_of_ammonia_in_households_cooling_energetic),
      Q(final_demand_of_ammonia_in_households_lighting_energetic)
    )
