# Energetic final demand of the 'coal_and_derivatives' carrier group in households appliances, cooking, cooling and lighting

- unit = PJ
- query =
    SUM(
      Q(final_demand_of_coal_and_derivatives_in_households_appliances_energetic),
      Q(final_demand_of_coal_and_derivatives_in_households_cooking_energetic),
      Q(final_demand_of_coal_and_derivatives_in_households_cooling_energetic),
      Q(final_demand_of_coal_and_derivatives_in_households_lighting_energetic)
    )
