# This query calculates the insulation costs for semi_detached_houses_1985_2004
# The calculated costs are only updated for the future year, in the present year 
# the insulation costs are assumed to be zero. This is done with IF-statements.
# See https://docs.energytransitionmodel.com/main/insulation/#insulation-costs

- query =
    insulation_value_present =                    QUERY_PRESENT(-> { AREA(typical_useful_demand_for_space_heating_semi_detached_houses_1985_2004) });
    insulation_value_future =                     QUERY_FUTURE(-> { AREA(typical_useful_demand_for_space_heating_semi_detached_houses_1985_2004) });
    insulation_value_threshold =                  220.0;

    semi_detached_houses_insulaton_costs_low =    DIVIDE(10300.0,(403.0 - insulation_value_threshold));
    semi_detached_houses_insulaton_costs_high =   DIVIDE(24800.0,(insulation_value_threshold - 118.0));

    number_of_semi_detached_houses_1985_2004 =    V(households_useful_demand_for_space_heating_semi_detached_houses_1985_2004, number_of_units);

    IF(
      GRAPH().future?,
      -> {
        PRODUCT(
          SUM(
            PRODUCT(
              semi_detached_houses_insulaton_costs_low,
              MAX(MIN((insulation_value_present - insulation_value_threshold),(insulation_value_present - insulation_value_future)),0)
            ),
            PRODUCT(
              semi_detached_houses_insulaton_costs_high,
              MAX(MIN((insulation_value_threshold - insulation_value_future),(insulation_value_present - insulation_value_future)),0)
            )
          ),
          number_of_semi_detached_houses_1985_2004
        )
      },
      0.0
    )
- unit = euro
