- query =
    DIVIDE(
      SUM(Q(hourly_demand_for_space_heating_terraced_houses_1965_1984)) -
      SUM(Q(hourly_production_for_space_heating_terraced_houses_1965_1984)),
      THOUSANDS
    )
- unit = GJ
