- query =
    PRODUCT(
      DIVIDE(
        SUM(Q(hourly_demand_for_space_heating_terraced_houses_1985_2004)) -
        SUM(Q(hourly_production_for_space_heating_terraced_houses_1985_2004)),
        THOUSANDS
      ),
      MJ_PER_MWH
    )
- unit = GJ
