- query =
    PRODUCT(
      DIVIDE(
        SUM(Q(hourly_demand_for_space_heating_semi_detached_houses_2005_present)) -
        SUM(Q(hourly_production_for_space_heating_semi_detached_houses_2005_present)),
        THOUSANDS
      ),
      MJ_PER_MWH
    )
- unit = GJ
