- query =
    DIVIDE(
      SUM(Q(hourly_demand_for_space_heating_terraced_houses_future)) -
      SUM(Q(hourly_production_for_space_heating_terraced_houses_future)),
      THOUSANDS
    )
- unit = GJ
