- query =
    DIVIDE(
      SUM(Q(hourly_demand_for_space_heating_apartments_2005_present)) -
      SUM(Q(hourly_production_for_space_heating_apartments_2005_present)),
      THOUSANDS
    )
- unit = GJ
