- query =
    DIVIDE(
      SUM(Q(hourly_demand_for_space_heating_detached_houses_future)) -
      SUM(Q(hourly_production_for_space_heating_detached_houses_future)),
      SUM(Q(hourly_demand_for_space_heating_detached_houses_future))
    ) * 100.0
- unit = %
