# Total investment costs for all electricity production units
# These costs are corrected for the amount of electricity produced domestically.
# When electricity is imported or exported, the average costs are used to calculate the total investment costs to fill demand. 

- unit = bln_euro

DIVIDE(
  SUM(V(G(electricity_production),initial_investment_costs_per(converter))),
  Q(share_of_electricity_generated_domestically)  
)
