- query =
    SUM_CURVES(V(
      INTERSECTION(
        FILTER(ALL(),"input_of_network_gas > 0"),
        EXCLUDE(INTERSECTION(G(heat_production),SECTOR(energy)),G(electricity_production))
      ),
      network_gas_input_curve
    ))
- unit = curve
