# Final consumption of oil and oil products in industry refineries (energetic and non-energetic use combined).
#
# Sector:      Industry Refineries -- EG(refineries_industry)
# Carrier:     Oil and oil products
# Use type:    Total
#
# Exception: includes the non-biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    Q(final_consumption_of_oil_and_oil_products_in_industry_refineries_total)
