# The capital costs of the future mv-hv transformers

- query =
          SUM(
              QUERY_FUTURE(mv_hv_trafo_total_investment_costs) / 2.0 * V(energy_power_mv_distribution_network_electricity,wacc)
          )

- unit = euro
