# The depreciation costs of the future mv-hv transformers

- query =
          SUM(
              QUERY_FUTURE(mv_hv_trafo_costs_delta_present_future_investment_costs) / V(energy_power_mv_distribution_network_electricity,technical_lifetime)
          )

- unit = euro
