# The OPEX of the future mv-hv transformers, consisting of operation and maintenance costs

- query =
          SUM(
              QUERY_FUTURE(mv_hv_trafo_operation_and_maintenance_costs)
          )

- unit = euro
