# The CAPEX of the future mv-hv transformers

- query =
          SUM(
              QUERY_FUTURE(mv_hv_trafo_costs_delta_present_future_capital_costs),
              QUERY_FUTURE(mv_hv_trafo_costs_delta_present_future_depreciation_costs)
          )

- unit = euro
