# The delta (difference) between the present and the future costs of the mv-hv transformers

- query =
          SUM(
              QUERY_FUTURE(mv_hv_trafo_CAPEX),
              QUERY_FUTURE(mv_hv_trafo_OPEX)
          )

- unit = euro
