# The delta (difference) between the present and the future costs of the mv-hv transformers

- query =
          SUM(
              QUERY_FUTURE(mv_hv_trafo_capex),
              QUERY_FUTURE(mv_hv_trafo_opex)
          )

- unit = euro
