# Final consumption of ammonia in industry ex. ict and refineries - paper (energetic and non-energetic use combined).
#
# Sector:      Industry ex. ICT and refineries - Paper -- EG(paper_industry)
# Carrier:     Ammonia -- ammonia?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_industry_paper_total)
