# Final consumption of ammonia in energy (energetic and non-energetic use combined).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Ammonia -- ammonia?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_energy_total)
