# Final consumption of ammonia in international transport (energetic and non-energetic use combined).
#
# Sector:      International transport -- sector == :bunkers
# Carrier:     Ammonia -- ammonia?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_international_transport_total)
