# Final consumption of ammonia in national transport (energetic and non-energetic use combined).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Ammonia -- ammonia?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_national_transport_total)
