# Final consumption of ammonia in agriculture (energetic and non-energetic use combined).
#
# Sector:      Agriculture -- sector == :agriculture
# Carrier:     Ammonia -- ammonia?
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_agriculture_total)
