# The delta (difference) between the present and the future costs of the low voltage net.

- query = QUERY_FUTURE(mv_hv_trafo_capacity_delta_present_future) * INPUT_VALUE(costs_infrastructure_electricity_mv_hv_trafo)

- unit = euro
