# The costs of the future hv net

- query = QUERY_PRESENT(mv_hv_trafo_total_costs_present) + QUERY_FUTURE(mv_hv_trafo_capacity_steps_built) * QUERY_FUTURE(mv_hv_trafo_costs_per_capacity_step)

- unit = euro
