# Electricity production after curtailment of 'energy_power_solar_pv_offshore'

- unit = PJ
- query =
    SUM(
      V(energy_power_solar_pv_offshore, output_of_electricity),
      PRODUCT(SUM(V(energy_power_solar_pv_offshore, curtailment_output_curve)), MJ_PER_MWH)
    ) / BILLIONS
