# Peak power before curtailment of 'energy_power_solar_pv_offshore'

- unit = MW
- query =
    SUM(
      MAX(Q(energy_power_solar_pv_offshore_electricity_output_curve)),
      MAX(Q(energy_power_solar_pv_offshore_curtailed_electricity_output_curve))
    )
