- query = 
    MAX(
      SUM_CURVES(
        SUM_CURVES(V(
          households_solar_pv_solar_radiation,
          buildings_solar_pv_solar_radiation,
          energy_power_solar_pv_solar_radiation,
          curtailment_output_curve
        )),
        V(
          energy_battery_curtailed_solar_electricity,
          electricity_input_curve
        ))
    )
- unit = MW
