- query = 
    SUM(
      Q(households_flexibility_p2p_electricity_volume),
      Q(transport_car_using_electricity_volume),
      Q(households_flexibility_p2h_electricity_volume),
      Q(industry_flexibility_p2h_electricity_volume)
    )
- unit = MWh
