- query =
    SUM(
      Q(households_flexibility_p2p_electricity_output),
      Q(transport_car_using_electricity_output),
      Q(households_flexibility_p2h_electricity_output),
      Q(energy_hydrogen_flexibility_p2g_electricity_output),
      Q(bunkers_flexibility_p2g_electricity_output),
      Q(industry_flexibility_p2h_electricity_output),
      Q(energy_export_electricity_output),
      Q(energy_curtailment_electricity_output),
      Q(losses_in_storage)
    )
- unit = PJ
