- query =
    SUM(
      Q(households_flexibility_p2p_electricity_input),
      Q(transport_car_using_electricity_input),
      Q(households_flexibility_p2h_electricity_input),
      Q(energy_hydrogen_flexibility_p2g_electricity_input),
      Q(bunkers_flexibility_p2g_electricity_input),
      Q(industry_flexibility_p2h_electricity_input),
      Q(energy_export_electricity_input),
      Q(energy_curtailment_electricity_input)
    )
- unit = PJ
