- query = SUM(
            Q(households_flexibility_p2p_demand),
            Q(transport_car_using_electricity_demand),
            Q(households_flexibility_p2h_demand),
            Q(energy_flexibility_p2g_electricity_demand),
            Q(energy_export_electricity_demand),
            Q(energy_curtailment_electricity_demand),
            Q(losses_in_storage)
          )
- unit = PJ
