- query = SUM(
            Q(households_flexibility_p2p_capacity),
            Q(transport_car_using_electricity_capacity),
            Q(households_flexibility_p2h_capacity),
            Q(energy_flexibility_p2g_electricity_capacity),
            Q(energy_export_electricity_capacity)
          )
- unit = MW
