- query =
    SUM(
      Q(households_flexibility_p2p_electricity_capacity),
      Q(transport_car_using_electricity_capacity),
      Q(energy_hydrogen_flexibility_p2g_electricity_capacity),
      Q(energy_flexibility_pumped_storage_electricity_capacity),
      Q(energy_flexibility_opac_electricity_capacity),
      Q(energy_flexibility_mv_batteries_electricity_capacity),
      Q(energy_heat_flexibility_p2h_boiler_electricity_capacity),
      Q(energy_heat_flexibility_p2h_heatpump_electricity_capacity),
      Q(industry_flexibility_p2h_electricity_capacity),
      Q(energy_interconnector_1_exported_electricity_capacity),
      Q(energy_interconnector_2_exported_electricity_capacity),
      Q(energy_interconnector_3_exported_electricity_capacity),
      Q(energy_interconnector_4_exported_electricity_capacity),
      Q(energy_interconnector_5_exported_electricity_capacity),
      Q(energy_interconnector_6_exported_electricity_capacity)
    )
- unit = MW
