- query =
    SUM(
      Q(households_flexibility_p2p_electricity_output),
      Q(transport_car_using_electricity_output),
      Q(energy_hydrogen_flexibility_p2g_electricity_output),
      Q(energy_flexibility_pumped_storage_electricity_output),
      Q(energy_flexibility_opac_electricity_output),
      Q(energy_flexibility_mv_batteries_electricity_output),
      Q(energy_heat_flexibility_p2h_boiler_electricity_output),
      Q(energy_heat_flexibility_p2h_heatpump_electricity_output),
      Q(industry_flexibility_p2h_electricity_output),
      Q(losses_in_conversion_and_storage),
      Q(energy_flexibility_load_shifting_chemical_industry_electricity_output),
      Q(energy_flexibility_load_shifting_metal_industry_electricity_output),
      Q(energy_flexibility_load_shifting_other_industry_electricity_output),
      Q(energy_flexibility_load_shifting_other_ict_industry_electricity_output)
    )
- unit = PJ
