- query = SUM(
            Q(households_flexibility_p2p_usage_twh),
            Q(transport_car_using_electricity_usage_twh),
            Q(households_flexibility_p2h_usage_twh),
            Q(energy_flexibility_p2g_electricity_usage_twh),
            Q(energy_export_electricity_usage_twh),
            Q(energy_curtailment_electricity_usage_twh),
            Q(losses_in_storage_twh)
          )
- unit = MWh
