- query = 
    MAX(
      SUM_CURVES(V(
        industry_chemicals_fertilizers_flexibility_p2h_network_gas_electricity,
        industry_chemicals_fertilizers_flexibility_p2h_hydrogen_electricity,
        electricity_input_curve
      ))
    )
- unit = MW
