- query = 
    SUM(
        V(industry_chemicals_refineries_flexibility_p2h_electricity, "number_of_units * storage.volume"),
        V(industry_chemicals_other_flexibility_p2h_electricity, "number_of_units * storage.volume"),
        V(industry_other_food_flexibility_p2h_electricity, "number_of_units * storage.volume"),
        V(industry_other_paper_flexibility_p2h_electricity, "number_of_units * storage.volume")
    )
- unit = MWh

