- query =
    SUM(
      V(
        industry_chemicals_other_flexibility_p2h_network_gas_electricity,
        industry_chemicals_other_flexibility_p2h_hydrogen_electricity, 
        output_of_useable_heat
      )
    ) / BILLIONS
- unit = PJ
