- query = 
    SUM(
        V(industry_chemicals_refineries_flexibility_p2h_electricity, full_load_hours),
        V(industry_chemicals_other_flexibility_p2h_electricity, full_load_hours),
        V(industry_other_food_flexibility_p2h_electricity, full_load_hours),
        V(industry_other_paper_flexibility_p2h_electricity, full_load_hours)
    )
- unit = hours

