- query =
    SUM(
      V(
        industry_other_paper_flexibility_p2h_network_gas_electricity,
        industry_other_paper_flexibility_p2h_hydrogen_electricity, 
        "number_of_units * input_capacity"
      )
    )
- unit = MW
