- query =
    SUM(
      V(
        industry_other_food_flexibility_p2h_network_gas_electricity,
        industry_other_food_flexibility_p2h_hydrogen_electricity, 
        input_of_electricity
      )
    ) / BILLIONS
- unit = PJ
