# This gquery includes all losses related to storage and conversion of electricity by flexible demand technologies

- query =
    SUM(
      Q(losses_in_conversion),
      Q(losses_in_storage)
    )
- unit = PJ
