# This gquery includes all losses in electricity storage technologies
# This includes conversion losses, unused electricity and decayed electricity

- query =
    SUM(
      Q(households_flexibility_p2p_electricity_losses),
      Q(transport_car_flexibility_p2p_electricity_losses),
      Q(energy_flexibility_mv_batteries_electricity_losses),
      Q(energy_flexibility_hv_opac_electricity_losses),
      Q(energy_flexibility_pumped_storage_electricity_losses),
      Q(energy_flexibility_flow_batteries_electricity_losses)
    ) / BILLIONS
- unit = PJ
