# This gquery includes all losses in electricity storage technologies
# This includes conversion losses, unused electricity and decayed electricity
# Excluded are the energy_flexibility_wind_batteries_electricity and energy_flexibility_solar_batteries_electricity
# This is because these nodes are only shown as the resulting output to the grid

- query = Q(electricity_storage_losses)
- unit = PJ
