- deprecated_key = chart_other_heat_63_decentral_production_568
#

- unit = pj

DIVIDE(
    MAX(
        SUM(
            V(other_useful_demand_useable_heat,demand),
            NEG(
                V(other_chp_engine_network_gas,output_of_heat_carriers)
            )
        ),
        0
    ),
    BILLIONS
)
