# Peak power before curtailment of 'buildings_solar_pv_solar_radiation'

- unit = MW
- query =
    SUM(
      MAX(Q(buildings_solar_pv_electricity_output_curve)),
      MAX(Q(buildings_solar_pv_curtailed_electricity_output_curve))
    )
