# Electricity production after curtailment of 'energy_power_solar_pv_solar_radiation'

- unit = PJ
- query =
    SUM(
      V(energy_power_solar_pv_solar_radiation, output_of_electricity),
      PRODUCT(SUM(V(energy_power_solar_pv_solar_radiation, curtailment_output_curve)), MJ_PER_MWH)
    ) / BILLIONS
