# The future capacity of the offshore network

- query = 
    future:SUM(
      V(energy_power_wind_turbine_offshore, "electricity_output_capacity * number_of_units"),
      V(energy_power_solar_pv_offshore, "electricity_output_capacity * number_of_units"),
      V(energy_power_hybrid_to_offshore_network_electricity, electricity_output_capacity)
    )

- unit = MW
