- query =
    SUM(
      Q(p2h_central_heat_to_central_heat_in_sankey),
      Q(chp_in_source_of_central_heat_production),
      Q(electricity_excl_p2h_in_source_of_central_heat_production),
      Q(hydrogen_in_source_of_central_heat_production),
      Q(coal_and_derivatives_in_source_of_central_heat_production),
      Q(oil_and_derivatives_in_source_of_central_heat_production),
      Q(natural_gas_in_source_of_central_heat_production),
      Q(biomass_products_in_source_of_central_heat_production),
      Q(solar_thermal_in_source_of_central_heat_production),
      Q(geothermal_in_source_of_central_heat_production),
      Q(ambient_heat_excl_p2h_in_source_of_central_heat_production),
      Q(residual_heat_for_central_heat_conversion)
    )
- unit = PJ