- query =
    SUM(
      Q(conversion_loss_electricity_to_hydrogen),
      Q(conversion_loss_electricity_to_steam_hot_water),
      Q(conversion_loss_electricity_to_oil_and_derivatives),
      Q(conversion_loss_electricity_to_natural_gas_and_derivatives),
      Q(conversion_loss_electricity_to_biomass_products),
      Q(conversion_loss_electricity_to_electricity),
      Q(conversion_loss_hydrogen_to_electricity),
      Q(conversion_loss_hydrogen_to_steam_hot_water),
      Q(conversion_loss_hydrogen_to_oil_and_derivatives),
      Q(conversion_loss_hydrogen_to_hydrogen),
      Q(conversion_loss_uranium_to_electricity),
      Q(conversion_loss_coal_and_derivatives_to_electricity),
      Q(conversion_loss_coal_and_derivatives_to_steam_hot_water),
      Q(conversion_loss_coal_and_derivatives_to_coal_and_derivatives),
      Q(conversion_loss_oil_and_derivatives_to_electricity),
      Q(conversion_loss_oil_and_derivatives_to_steam_hot_water),
      Q(conversion_loss_oil_and_derivatives_to_oil_and_derivatives),
      Q(conversion_loss_natural_gas_and_derivatives_to_electricity),
      Q(conversion_loss_natural_gas_and_derivatives_to_steam_hot_water),
      Q(conversion_loss_natural_gas_and_derivatives_to_hydrogen),
      Q(conversion_loss_natural_gas_and_derivatives_to_biomass_products),
      Q(conversion_loss_natural_gas_and_derivatives_to_natural_gas_and_derivatives),
      Q(conversion_loss_biomass_products_to_electricity),
      Q(conversion_loss_biomass_products_to_steam_hot_water),
      Q(conversion_loss_biomass_products_to_hydrogen),
      Q(conversion_loss_biomass_products_to_natural_gas_and_derivatives),
      Q(conversion_loss_biomass_products_to_biomass_products),
      Q(conversion_loss_ammonia_to_hydrogen),
      Q(conversion_loss_lohc_to_hydrogen),
      Q(conversion_loss_liquid_hydrogen_to_hydrogen)
    )
- unit = PJ