- query =
    SUM(
      Q(gas_for_electricity_conversion),
      Q(natural_gas_to_central_heat_prod_in_sankey),
      Q(natural_gas_for_steam_methane_reformer_conversion),
      Q(natural_gas_for_steam_methane_reformer_ccs_conversion),
      Q(natural_gas_for_autothermal_reformer_conversion),
      Q(natural_gas_for_autothermal_reformer_ccs_conversion),
      Q(natural_gas_for_biomass_gasification_conversion),
      Q(natural_gas_for_biomass_gasification_ccs_conversion)
    )
- unit = PJ