- query =
    SUM(
      Q(sankey_final_demand_of_biomass_products_in_households_space_heating_and_hot_water_energetic),
      Q(sankey_final_demand_of_biomass_products_in_households_other_energetic),
      Q(sankey_final_demand_of_biomass_products_in_buildings_space_heating_energetic),
      Q(sankey_final_demand_of_biomass_products_in_buildings_other_energetic),
      Q(biomass_products_to_agriculture_in_sankey),
      Q(sankey_final_demand_of_biomass_products_in_industry_other_energetic),
      Q(sankey_final_demand_of_biomass_products_in_industry_ict_energetic),
      Q(biomass_products_to_transport_in_sankey),
      Q(biomass_products_to_bunkers_in_sankey),
      Q(biomass_products_to_export_in_sankey),
      Q(biomass_products_to_other_in_sankey),
      Q(biomass_products_to_energy_in_sankey),
      Q(biomass_products_to_feedstock_in_sankey)
    )
- unit = PJ