# Use of carrier group 'ambient' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(Q(hot_water_converters_in_households), input_of_ambient_heat),
      V(Q(hot_water_converters_in_households), input_of_ambient_cold)
    ) / BILLIONS
