# Use of carrier group 'ambient' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_p2h)),input_of_ambient_heat),
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_p2h)),input_of_ambient_cold)      
    ) / BILLIONS
