# Use of carrier group 'biomass_products' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(Q(hot_water_converters_in_households), input_of_biodiesel),
      V(Q(hot_water_converters_in_households), input_of_bio_ethanol),
      V(Q(hot_water_converters_in_households), input_of_wood_pellets),
      V(Q(hot_water_converters_in_households), input_of_bio_lng)
    ) / BILLIONS

