# Use of carrier group 'coal_and_derivatives' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(Q(hot_water_converters_in_households), input_of_coal),
      V(Q(hot_water_converters_in_households), input_of_coal_gas)
    ) / BILLIONS

