# Use of carrier group 'heat' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(Q(hot_water_converters_in_households), input_of_steam_hot_water),
      V(Q(hot_water_converters_in_households), input_of_useable_heat)
    ) / BILLIONS
