# Use of carrier group 'heat' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_p2h)),input_of_steam_hot_water),
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_p2h)),input_of_useable_heat)      
    ) / BILLIONS
