# Use of carrier group 'natural_gas_and_derivatives' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(Q(hot_water_converters_in_households), input_of_network_gas),
      V(Q(hot_water_converters_in_households), input_of_lng)
    ) / BILLIONS
