# Use of carrier group 'natural_gas_and_derivatives' in housholds hot water

- unit = pj
- query =
    SUM(
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_add_on)),input_of_network_gas)      
    ) / BILLIONS
