# Use of carrier group 'network_gas' in households hot water

- query = 
    SUM(
      Q(final_demand_of_natural_gas_in_households_hot_water_energetic),
      Q(final_demand_of_greengas_in_households_hot_water_energetic),
    )
- unit = PJ
