# Use of carrier group 'oil_and_derivatives' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(Q(hot_water_converters_in_households), input_of_crude_oil),
      V(Q(hot_water_converters_in_households), input_of_gasoline),
      V(Q(hot_water_converters_in_households), input_of_diesel),
      V(Q(hot_water_converters_in_households), input_of_lpg),
      V(Q(hot_water_converters_in_households), input_of_kerosene),
      V(Q(hot_water_converters_in_households), input_of_heavy_fuel_oil)
    ) / BILLIONS
