# Use of carrier group 'oil_and_derivatives' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_add_on)),input_of_crude_oil),
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_add_on)),input_of_gasoline),
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_add_on)),input_of_diesel),
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_add_on)),input_of_lpg),
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_add_on)),input_of_kerosene),
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_add_on)),input_of_heavy_fuel_oil)      
    ) / BILLIONS
