# Use of carrier group 'solar' in housholds hot water

- unit = PJ
- query =
    SUM(
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_add_on)),input_of_solar_radiation),
      V(CHILDREN(V(households_useful_demand_for_hot_water_after_solar_heater_and_add_on)),input_of_solar_thermal)      
    ) / BILLIONS
