- query =
    SUM(
      PRODUCT(
        Q(conversion_loss_network_gas_to_hydrogen),
        Q(share_of_sustainable_gas_in_gas_network)
      ),
      Q(conversion_loss_torrefied_biomass_pellets_to_hydrogen)
    )
- unit = PJ
