- query =
    DIVIDE(
      SUM(
        V(
          FILTER(G(sankey_conversion_group),"steam_hot_water_output_conversion > 0.0 && wood_pellets_input_conversion > 0.0"),
          "steam_hot_water_output_conversion * wood_pellets_input_conversion / (1 - loss_output_conversion) * output_of_loss"
        )
      ), 
      BILLIONS
    )
- unit = PJ
