- query =
    DIVIDE(
      SUM(
        V(
          FILTER(G(sankey_conversion_group),"bio_ethanol_output_conversion > 0.0 && bio_ethanol_input_conversion > 0.0"),
          "bio_ethanol_output_conversion * bio_ethanol_input_conversion / (1 - loss_output_conversion) * output_of_loss"
        )
      ), 
      BILLIONS
    )
- unit = PJ
