- query =
    DIVIDE(
      SUM(
        V(
          FILTER(G(sankey_conversion_group),"greengas_output_conversion > 0.0 && biogas_input_conversion > 0.0"),
          "greengas_output_conversion * biogas_input_conversion / (1 - loss_output_conversion) * output_of_loss"
        )
      ), 
      BILLIONS
    )
- unit = PJ
