- query =
    SUM(
      PRODUCT(
        Q(conversion_loss_network_gas_to_electricity),
        Q(share_of_sustainable_gas_in_gas_network)
      ),
      PRODUCT(
        Q(conversion_loss_gas_power_fuelmix_to_electricity),
        V(energy_mixer_for_gas_power_fuel, bio_oil_input_conversion)
      ),
      Q(conversion_loss_biogas_to_electricity),
      Q(conversion_loss_wood_pellets_to_electricity),
      Q(conversion_loss_waste_mix_to_electricity),
      Q(conversion_loss_torrefied_biomass_pellets_to_electricity)
    )
- unit = PJ
