# Final consumption of ammonia, all sectors (non-energetic use only).
#
# Sector:      All sectors
# Carrier:     Ammonia -- ammonia?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_non_energetic)
