- unit = PJ
- query =
          SUM(V(
              households_final_demand_for_cooling_network_gas,
              households_final_demand_for_cooling_electricity,
              demand
            )) / BILLIONS
