- query = 
    SUM(   
      Q(turk_sankey_0_to_1_biomass_products_to_hydrogen),
      Q(turk_sankey_0_to_1_natural_gas_to_hydrogen),
      Q(turk_sankey_0_to_1_imported_hydrogen_to_hydrogen),
      Q(turk_sankey_0_to_1_imported_liquid_hydrogen_to_hydrogen),
      Q(turk_sankey_0_to_1_imported_lohc_to_hydrogen),
      Q(turk_sankey_0_to_1_ammonia_to_hydrogen),
      Q(turk_sankey_0_to_1_residual_hydrogen_to_hydrogen),
      Q(turk_sankey_1_to_1_electricity_to_hydrogen),
      Q(turk_sankey_1_to_1_oil_and_oil_products_to_hydrogen)
    )


- unit = PJ