- query = 
    SUM(   
      Q(turk_sankey_1_to_1_electricity_to_heat),
      Q(turk_sankey_1_to_1_electricity_to_hydrogen),
      Q(turk_sankey_1_to_1_electricity_to_oil_and_oil_products),  
      Q(turk_sankey_1_to_2_electricity_to_agriculture),
      Q(turk_sankey_1_to_2_electricity_to_households),
      Q(turk_sankey_1_to_2_electricity_to_buildings),
      Q(turk_sankey_1_to_2_electricity_to_transport),
      Q(turk_sankey_1_to_2_electricity_to_industry),
      Q(turk_sankey_1_to_2_electricity_to_energy),
      Q(turk_sankey_1_to_2_electricity_to_other),
      Q(turk_sankey_1_to_2_electricity_to_bunkers),
      Q(turk_sankey_1_to_2_electricity_to_feedstock),
      Q(turk_sankey_1_to_2_electricity_to_export),
      Q(turk_sankey_1_to_2_electricity_to_loss)
    )


- unit = PJ