- unit = MT
- query =
    DIVIDE(
      SUM(
        MV(
          other_indirect_emissions_non_energetic_co2,
          direct_reporting_emissions_total_ghg_emissions
        )
      ),
      BILLIONS
    )
