- unit = MT
- query =
    DIVIDE(
      SUM(
        MV(
          MG(emissions_other_indirect_emissions),
          direct_reporting_emissions_total_ghg_emissions
        )
      ),
      BILLIONS
    )
