- query =
    DIVIDE(
      SUM(
        Q(co2_sheet_agriculture_total_co2_emissions_energetic),
        Q(co2_sheet_buildings_households_total_co2_emissions_energetic),
        Q(co2_sheet_industry_energy_total_co2_emissions_energetic),
        Q(co2_sheet_transport_total_co2_emissions_energetic),
        Q(emissions_energetic_agriculture_other_ghg),
        Q(emissions_energetic_buildings_other_ghg),
        Q(emissions_energetic_households_other_ghg),
        Q(emissions_energetic_energy_other_ghg),
        Q(emissions_energetic_industry_other_ghg),
        Q(emissions_energetic_transport_other_ghg)
      ),
      SUM(
        Q(co2_sheet_agriculture_total_emissions),
        Q(co2_sheet_industry_energy_total_emissions),
        Q(co2_sheet_transport_total_emissions),
        Q(co2_sheet_buildings_households_total_emissions),
        Q(co2_sheet_indirect_delayed_emissions)
      )
    ) * 100
- unit = %