- query =
    DIVIDE(
      SUM(
        Q(emissions_energetic_all_co2),
        Q(emissions_energetic_all_other_ghg)
      ),
      SUM(
        Q(co2_sheet_agriculture_total_emissions),
        Q(co2_sheet_industry_energy_total_emissions),
        Q(co2_sheet_transport_total_emissions),
        Q(co2_sheet_buildings_households_total_emissions),
        Q(co2_sheet_indirect_delayed_emissions)
      )
    ) * 100
- unit = %
