# Total other GHG emissions incl. indirect emissions, LULUCF and international transport

- unit = MT
- query =
    SUM(
      Q(direct_emissions_energy_other_ghg),
      Q(direct_emissions_industry_other_ghg),
      Q(direct_emissions_transport_other_ghg),
      Q(direct_emissions_buildings_other_ghg),
      Q(direct_emissions_households_other_ghg),
      Q(direct_emissions_agriculture_other_ghg),
      Q(direct_emissions_other_other_ghg),
      Q(direct_emissions_lulucf_other_ghg),
      Q(direct_emissions_waste_other_ghg),
      Q(direct_emissions_bunkers_other_ghg)
    )
