# There is no land use included in the Node Source Analysis for solar thermal heaters. The land use of pv panels are used to make an estimation.
- unit = km2
- query =
    PRODUCT(
        V(households_water_heater_solar_thermal,number_of_units),
        V(households_water_heater_solar_thermal,land_use_per_unit)
    )
