- unit = PJ
- query = 
    SUM(
      Q(electricity_stored_in_electric_cars),
      Q(electricity_stored_in_electric_busses),
      Q(electricity_stored_in_electric_trucks),
      Q(electricity_stored_in_electric_vans)
    )
