- unit = PJ
- query = 
    SUM(
      V(
        energy_hydrogen_flexibility_p2g_electricity,
        energy_hydrogen_hybrid_electrolysis_wind_electricity,
        "hydrogen_output_conversion * demand"
      )
    ) / BILLIONS
