- unit = PJ
- query = 
    SUM(
      V(households_flexibility_p2p_electricity, "loss_output_conversion * demand"),
      V(households_flexibility_p2h_electricity, "loss_output_conversion * demand")
    )
