# Returns the capacity of dispatchable network gas chp's for the sector agriculture.
- query = 
        PRODUCT(
  		V(agriculture_chp_engine_network_gas_dispatchable,number_of_units),
  		V(agriculture_chp_engine_network_gas_dispatchable,electricity_output_capacity)	
  		)
- unit = MW

