- deprecated_key = chart_electric_vehicles_51_centrally_produced_electricity_demand_361
# 

- unit = pj

SUM(
    QUERY_FUTURE( -> { DIVIDE(SUM(V(transport_car_using_electricity,transport_truck_using_electricity,input_of_electricity)),BILLIONS) } ),
    NEG(
        QUERY_PRESENT( -> { DIVIDE(SUM(V(transport_car_using_electricity,transport_truck_using_electricity,input_of_electricity)),BILLIONS) } )
    )
)