- deprecated_key = chart_geothermal_51_centrally_produced_electricity_demand_364
# 

- unit = pj

QUERY_FUTURE( -> { DIVIDE(V(agriculture_geothermal,input_of_electricity),BILLIONS) } )
-
QUERY_PRESENT( -> { DIVIDE(V(agriculture_geothermal,input_of_electricity),BILLIONS) } )