- deprecated_key = chart_heatpumps_51_centrally_produced_electricity_demand_363
# 

- unit = pj

SUM(
    QUERY_FUTURE( -> { Q(electricity_used_in_heatpumps) } ),
    NEG(
        QUERY_PRESENT( -> { Q(electricity_used_in_heatpumps) } )
    )
)