- query = 
		SUM(
			Q(coal_and_derivatives_to_electricity_prod_in_sankey),
			Q(oil_and_derivatives_to_electricity_prod_in_sankey),
			Q(natural_gas_to_electricity_prod_in_sankey),
			Q(solar_to_electricity_prod_in_sankey),
			Q(wind_to_electricity_prod_in_sankey),
			Q(biomass_products_to_electricity_prod_in_sankey),
			Q(geo_ambient_to_electricity_prod_in_sankey),
			Q(nuclear_to_electricity_prod_in_sankey),
			Q(imported_electricity_to_electricity_prod_in_sankey),
			Q(imported_hydrogen_to_electricity_prod_in_sankey),
			Q(water_to_electricity_prod_in_sankey),
			Q(hydrogen_prod_to_electricity_prod_in_sankey),
			Q(p2p_to_electricity_prod_in_sankey)
		)