- query = 
		SUM(
			Q(coal_and_derivatives_to_hydrogen_prod_in_sankey),
			Q(oil_and_derivatives_to_hydrogen_prod_in_sankey),
			Q(natural_gas_to_hydrogen_prod_in_sankey),
			Q(solar_to_hydrogen_prod_in_sankey),
			Q(wind_to_hydrogen_prod_in_sankey),
			Q(biomass_products_to_hydrogen_prod_in_sankey),
			Q(geo_ambient_to_hydrogen_prod_in_sankey),
			Q(nuclear_to_hydrogen_prod_in_sankey),
			Q(imported_electricity_to_hydrogen_prod_in_sankey),
			Q(hydrogen_import_to_hydrogen_prod_in_sankey),
			Q(imported_ammonia_to_hydrogen_prod_in_sankey),
			Q(water_to_hydrogen_prod_in_sankey),
			Q(industry_to_hydrogen_prod_in_sankey),
			Q(p2g_to_hydrogen_prod_in_sankey)
		)