- query = 
		SUM(
			Q(electricity_prod_to_industry_in_sankey),
			Q(chp_heat_prod_to_industry_in_sankey),
			Q(hydrogen_prod_to_industry_in_sankey),
			Q(central_heat_prod_to_industry_in_sankey),
			Q(p2h_to_industry_in_sankey),
			Q(coal_and_derivatives_to_industry_in_sankey),
			Q(oil_and_derivatives_to_industry_in_sankey),
			Q(natural_gas_to_industry_in_sankey),
			Q(solar_to_industry_in_sankey),
			Q(wind_to_industry_in_sankey),
			Q(biomass_products_to_industry_in_sankey),
			Q(imported_ammonia_to_industry_in_sankey),
			Q(geo_ambient_to_industry_in_sankey)
		)