# Final consumption of methanol in national transport (non-energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Methanol -- methanol?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_methanol_in_national_transport_non_energetic)
