# Final consumption of natural gas and gas products in international transport - international navigation (energetic and non-energetic use combined).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Natural gas and gas products
# Use type:    Total
#
# Exception: includes the share of natural gas and gas products in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_natural_gas_and_gas_products_in_bunkers_international_navigation_total)
