# Final consumption of gaseous biofuels in international transport - international navigation (energetic and non-energetic use combined).
#
# Sector:      International transport - International navigation -- EG(bunkers_international_navigation)
# Carrier:     Gaseous biofuels
# Use type:    Total
#
# Exception: includes the share of gaseous biofuels in network gas.

- unit = PJ
- query =
    Q(final_consumption_of_gaseous_biofuels_in_bunkers_international_navigation_total)
