require_relative 'trollop'
require_relative 'processor'
require_relative 'excel_export'
require_relative 'excel_area_export'
require_relative 'csv'
require_relative 'converter_exporter'
require 'zip/zip'

class Xls2yml
  def initialize
    @etsource_root = File.expand_path("#{File.dirname(__FILE__)}/../../..")
    setup_cli
    parse_args
    run
    clean_up
  end

  def setup_cli
    opts = Trollop::options do
      version 'xls2yml 0.0.3'
      banner <<-EOS

XLS2YML
=======

This script converts the csv files generated by excel to a set of yml files
to be used by etsource.

  Usage:

  xls2etsource.rb [source]

The source parameter is optional. If missing the script will use ETSOURCE/csv_files
as excel export directory. If you specify the source parameter then it should be a
zip file or an existing directory.
The script will output files in the main etsource directory. *Old files will be overwritten*.

      EOS
    end
  end

  def parse_args
    @source = ARGV[0] || "#{@etsource_root}/csv_files"
    unless File.directory?(@source)
      @zip_root = expand_zip(@source)
      # The zip file usually contains a subfolder, let's return that
      @source = Dir.glob("#{@zip_root}/*/")[0]
    end
  end

  def run
    ETE::Processor.new(:source => @source, :dest => @etsource_root).export_all
  end

  # Returns the expanded files directory root
  #
  def expand_zip(zipfile)
    destination = "tmp_#{Time.new.to_i}"
    Zip::ZipFile.open(zipfile) do |zip|
      zip.each do |f|
        path = File.join(destination, f.name)
        FileUtils.mkdir_p(File.dirname(path))
        zip.extract(f, path) unless File.exist?(path)
      end
    end
    destination
  rescue
    puts "Error uncompressing the zip file"
    FileUtils.rm_rf(destination)
    exit
  end

  def clean_up
    FileUtils.rm_rf @zip_root if @zip_root
  end
end
