# Energetic final demand of the 'lng' carrier group in buildings space_heating

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(space_heating_buildings)), "lng?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
