# This returns the costs of energy used in households per year.

- unit = euro

PRODUCT(
              SUM(DIVIDE(SUM(Q(costs_heating_households),Q(costs_electricity_households)),AREA(number_households)),
                     Q(energy_tax_households),Q(fixed_energy_costs_per_household)),
             SUM(1,Q(tax_rate))
             )

