# Returns the capacity of solar radiation pv's for the sector buildings.
- query = 
        PRODUCT(
  		V(buildings_solar_pv_solar_radiation,number_of_units),
  		V(buildings_solar_pv_solar_radiation,electricity_output_capacity)	
  		)
- unit = MW

