# Does not include EV electricity demand for transport which is included in a separate curve:
#
# * EV:  lv_ev_load_curve

- query =
    SUM_CURVES(
      V(G(lv_net_flexibility), electricity_input_curve)
    )
- unit = curve
