- query =
    SUM_CURVES(V(
      households_appliances_clothes_dryer_electricity,
      households_appliances_computer_media_electricity,
      households_appliances_dishwasher_electricity,
      households_appliances_fridge_freezer_electricity,
      households_appliances_other_electricity,
      households_appliances_television_electricity,
      households_appliances_vacuum_cleaner_electricity,
      households_appliances_washing_machine_electricity,
      electricity_input_curve
    ))
