- query =
    SUM_CURVES(V(
      households_cooker_halogen_electricity,
      households_cooker_induction_electricity,
      households_cooker_resistive_electricity,
      electricity_input_curve
    ))
