- query =
    SUM_CURVES(V(
      households_cooling_airconditioning_electricity,
      households_cooling_heatpump_air_water_electricity,
      households_cooling_heatpump_ground_water_electricity,
      households_cooling_heatpump_surface_water_water_ts_electricity,
      electricity_input_curve
    ))
- unit = curve
