- query =
    MERIT_LOAD_CURVES(
      households_cooling_airconditioning_electricity,
      households_cooling_heatpump_air_water_electricity,
      households_cooling_heatpump_ground_water_electricity
    )
