- query =
    SUM_CURVES(
      V(households_final_demand_for_hot_water_electricity, electricity_input_curve),
      V(households_flexibility_p2h_electricity, electricity_output_curve)
    )
- unit = curve
