- query =
    SUM_CURVES(V(
      households_lighting_efficient_fluorescent_electricity,
      households_lighting_incandescent_electricity,
      households_lighting_led_electricity,
      electricity_input_curve
    ))
