- query =
    SUM(
      Q(total_primary_demand_of_solar_electricity),
      Q(total_primary_demand_of_wind_offshore_electricity),
      Q(total_primary_demand_of_wind_inland_electricity),
      Q(total_primary_demand_of_wind_coastal_electricity),
      Q(imported_electricity_to_electricity_prod_in_sankey),
      Q(water_to_electricity_prod_in_sankey),
      Q(geothermal_in_source_of_electricity_production)
    )
- unit = PJ
