- query =
    SUM(
      Q(sankey_final_demand_of_geothermal_in_households_space_heating_and_hot_water_energetic),
      Q(sankey_final_demand_of_geothermal_in_households_other_energetic),
      Q(sankey_final_demand_of_geothermal_in_buildings_space_heating_energetic),
      Q(sankey_final_demand_of_geothermal_in_buildings_other_energetic),
      Q(final_demand_of_geothermal_in_agriculture_energetic),
      Q(sankey_final_demand_of_geothermal_in_industry_other_energetic),
      Q(sankey_final_demand_of_geothermal_in_industry_ict_energetic),
      Q(final_demand_of_geothermal_in_transport_energetic),
      Q(final_demand_of_geothermal_in_bunkers_energetic),
      Q(final_demand_of_geothermal_in_other_energetic),
      Q(final_demand_of_geothermal_in_energy_energetic),
      Q(final_demand_of_geothermal_non_energetic)
    )
- unit = PJ
