- query =
    SUM(
      Q(electricity_for_steam_methane_reformer_hydrogen_conversion),
      Q(electricity_for_steam_methane_reformer_ccs_hydrogen_conversion),
      Q(electricity_for_autothermal_reformer_hydrogen_conversion),
      Q(electricity_for_autothermal_reformer_ccs_hydrogen_conversion),
      Q(electricity_prod_to_p2g_in_sankey),
      Q(wind_to_hydrogen_prod_in_sankey),
      Q(solar_to_hydrogen_prod_in_sankey),
      Q(electricity_prod_to_p2h_central_heat_in_sankey),
      Q(electricity_prod_to_central_heat_prod_excl_p2h_in_sankey),
      Q(electricity_for_synthetic_kerosene_conversion)
    )
- unit = PJ
