- query =
    SUM(
      Q(p2g_to_hydrogen_prod_in_sankey),
      Q(direct_electrolysis_wind_in_source_of_hydrogen_production),
      Q(direct_electrolysis_solar_in_source_of_hydrogen_production),
      Q(steam_methane_reformer_in_source_of_hydrogen_production),
      Q(steam_methane_reformer_ccs_in_source_of_hydrogen_production),
      Q(autothermal_reformer_in_source_of_hydrogen_production),
      Q(autothermal_reformer_ccs_in_source_of_hydrogen_production),
      Q(ammonia_reformer_in_source_of_hydrogen_production),
      Q(lohc_reformer_in_source_of_hydrogen_production),
      Q(liquid_hydrogen_regasifier_in_source_of_hydrogen_production),
      Q(biomass_gasification_in_source_of_hydrogen_production),
      Q(biomass_gasification_ccs_in_source_of_hydrogen_production),
      Q(conversion_industry_residual_hydrogen)
    )
- unit = PJ
