- query =
    SUM(
      Q(sankey_final_demand_of_electricity_in_households_space_heating_and_hot_water_energetic),
      Q(sankey_final_demand_of_electricity_in_households_other_energetic),
      Q(sankey_final_demand_of_electricity_in_buildings_space_heating_energetic),
      Q(sankey_final_demand_of_electricity_in_buildings_other_energetic),
      Q(electricity_prod_to_agriculture_in_sankey),
      Q(sankey_final_demand_of_electricity_in_industry_other_excl_p2h_energetic),
      Q(sankey_final_demand_of_electricity_in_industry_ict_energetic),
      Q(sankey_final_demand_of_electricity_in_industry_p2h_energetic),
      Q(electricity_prod_to_transport_in_sankey),
      Q(electricity_prod_to_bunkers_in_sankey),
      Q(electricity_prod_to_export_in_sankey),
      Q(electricity_prod_to_other_in_sankey),
      Q(electricity_prod_to_energy_in_sankey),
      Q(electricity_prod_to_feedstock_in_sankey)
    )
- unit = PJ
