- query =
    SUM(
      Q(biomass_products_for_biomass_gasification_conversion),
      Q(biomass_products_for_biomass_gasification_ccs_conversion),
      Q(biomass_products_for_electricity_conversion),
      Q(biomass_products_to_central_heat_prod_in_sankey)
    )
- unit = PJ
