# CO2 of carrier group 'electricity' in other

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(INTERSECTION(G(final_demand_group),SECTOR(other)),USE(energetic)).select {|node| node.input_slots.detect { |slot| slot.carrier.electricity? }}, "primary_co2_emission")
    ) / THOUSANDS
