# CO2 of carrier group 'heat' in households

- unit = tonne
- query =
    SUM(
      V(INTERSECTION(INTERSECTION(G(final_demand_group),SECTOR(households)),USE(energetic)).select {|node| node.input_slots.detect { |slot| slot.carrier.steam_hot_water? }}, "primary_co2_emission")
    ) / THOUSANDS
