- query =
    SUM(
      Q(heat_infrastructure_indoor_depreciation_costs),
      Q(heat_infrastructure_indoor_capital_costs),
      Q(heat_infrastructure_households_indoor_pipelines_yearly_maintenance_costs),
      Q(heat_infrastructure_buildings_indoor_pipelines_yearly_maintenance_costs)
      )
- unit = euro