# Assuming linear depreciation, in line with ETM cost calculation

- query =
    PRODUCT(
      DIVIDE(
        Q(heat_infrastructure_primary_pipelines_investment_costs),
        2.0),
      V(energy_distribution_ht_steam_hot_water, wacc)
    )
- unit = euro
