- query =
    SUM(
      Q(heat_infrastructure_distribution_stations_depreciation_costs),
      Q(heat_infrastructure_distribution_stations_capital_costs),
      Q(heat_infrastructure_sub_station_yearly_maintenance_costs),
      Q(heat_infrastructure_exchanger_station_yearly_maintenance_costs)
      )
- unit = euro