# Assuming linear depreciation, in line with ETM cost calculation

- query =
    DIVIDE(
      Q(heat_infrastructure_primary_pipelines_investment_costs),
      V(energy_distribution_ht_steam_hot_water, technical_lifetime)
      )
- unit = euro
