# Final consumption from industry ex. ict and refineries - fertilizers, all carriers (non-energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Fertilizers -- EG(fertilizers_industry)
# Carrier:     All carriers
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_from_industry_fertilizers_non_energetic)
