# Final consumption from households, all carriers (energetic and non-energetic use combined).
#
# Sector:      Households -- sector == :households
# Carrier:     All carriers
# Use type:    Total

- unit = PJ
- query =
    Q(final_consumption_from_households_total)
