# Returns the capacity of ultra supercritical mt lignite plants with ccsfor the sector energy.
- query = 
        PRODUCT(
  		V(energy_chp_ultra_supercritical_mt_lignite,number_of_units),
  		V(energy_chp_ultra_supercritical_mt_lignite,electricity_output_capacity)	
  		)
- unit = MW
