# Maximum LV-network required capacity

- query =
    MAX(
        Q(network_lv_net_peak_load_sd),
        Q(network_lv_net_peak_load_se),
        Q(network_lv_net_peak_load_wd),
        Q(network_lv_net_peak_load_we)
    )
- unit = MW
