# Final consumption from industry ex. ict and refineries - other metals, all carriers (energetic use only).
#
# Sector:      Industry ex. ICT and refineries - Other metals -- EG(other_metals_industry)
# Carrier:     All carriers
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_from_industry_other_metals_energetic)
