# Production nodes for liquid fuels production

- query =
    V(
      Q(liquid_biofuels_producers),
      energy_production_wood_pellets,
      energy_torrefaction_wood,
      energy_biogas_fermentation_wet_biomass,
      energy_greengas_gasification_wet_biomass,
      energy_greengas_gasification_dry_biomass,
      energy_greengas_upgrade_biogas
    )
- unit = nodes
