# Energetic final demand of the 'greengas' carrier group in households lighting

- unit = PJ
- query =
    PRODUCT(
      SUM(
        V(
          FILTER(
            FILTER(
              INTERSECTION(EG(final_demand),EG(lighting_households)), "network_gas? || compressed_network_gas?"
            ),
            "energetic?"
          ),
          value
        ),
      ),
      Q(share_of_sustainable_gas_in_gas_network)
    ) / BILLIONS
