# Energetic final demand of the 'hydrogen' carrier group in households lighting

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(lighting_households)), "hydrogen?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
