- unit = PJ
- query =
    (
    V(industry_steel_production, final_demand)
    +V(energy_steel_blastfurnace_current_transformation_cokes, output_of_loss)
    +V(energy_steel_blastfurnace_bat_transformation_cokes, output_of_loss)
    +V(energy_steel_hisarna_transformation_coal, output_of_loss)
    )/BILLIONS
