### Future space requirements of oil and products
# Returns future space requirements of imported oil and products that are part of the transit flows in ha

- query = 
    space_requirement_costs_crude_oil_ha_per_mj = 0.00001;
    space_requirement_costs_diesel_ha_per_mj = 0.00002;
    space_requirement_costs_gasoline_ha_per_mj = 0.00003;
    space_requirement_costs_heavy_fuel_oil_ha_per_mj = 0.00004;
    space_requirement_costs_kerosene_ha_per_mj = 0.00005;
    space_requirement_costs_lpg_ha_per_mj = 0.00006;
    SUM(
        PRODUCT(V(energy_export_crude_oil_baseload, demand), space_requirement_costs_crude_oil_ha_per_mj),
        PRODUCT(V(energy_export_diesel_baseload, demand), space_requirement_costs_diesel_ha_per_mj),
        PRODUCT(V(energy_export_gasoline_baseload, demand), space_requirement_costs_gasoline_ha_per_mj),
        PRODUCT(V(energy_export_heavy_fuel_oil_baseload, demand), space_requirement_costs_heavy_fuel_oil_ha_per_mj),
        PRODUCT(V(energy_export_kerosene_baseload, demand), space_requirement_costs_kerosene_ha_per_mj),
        PRODUCT(V(energy_export_lpg_baseload, demand), space_requirement_costs_lpg_ha_per_mj)
    )
- unit = ha