### Imported volume of diesel
# Returns total imported volume of all oil-related products in PJ

- query = 
    DIVIDE(
        SUM(
            V(energy_import_diesel, demand),
        ),
        BILLIONS
    )
- unit = PJ