### Exported volume of LOHC (transit flow)
# Returns user-defined exported volume of LOHC in PJ. This export and correspondingly forced import make up the transit flow of this carrier.

- query = 
    DIVIDE(
        V(energy_export_lohc_baseload, demand),
        BILLIONS
    )
- unit = PJ