### Exported volume of LNG (transit flow)
# Returns user-defined exported volume of LNG in PJ. This export and correspondingly forced import make up the transit flow of this carrier.

- query = 
    DIVIDE(
        V(energy_export_lng_baseload, demand),
        BILLIONS
    )
- unit = PJ