# Exported volume of LOHC (transit flow)
# Returns total exported volume of LOHC in PJ. The difference between export and import makes up the transit flow of this carrier.

- query = 
    DIVIDE(
      V(energy_export_lohc_baseload, demand),
      BILLIONS
    )
- unit = PJ
