### Future space requirements of liquid hydrogen
# Returns future space requirements of imported liquid hydrogen that is part of the transit flow in ha

- query = 
    space_requirement_costs_liquid_hydrogen_ha_per_mj = 0.00001;
    PRODUCT(
        V(energy_export_liquid_hydrogen_baseload, demand), 
        space_requirement_costs_liquid_hydrogen_ha_per_mj
    )
- unit = ha