### Future space requirements of LOHC
# Returns future space requirements of imported LOHC that is part of the transit flows in kn^2. 
# Query relies on land_use_per_unit which is km^2 per PJ for this node.

- query = 
        PRODUCT(
                V(energy_import_lohc,land_use_per_unit),
                DIVIDE(V(energy_import_lohc,demand),BILLIONS))
- unit = km^2