### Exported volume of oil and products (transit flow)
# Returns total exported volume of oil and products in PJ. The difference between export and import makes up the transit flow of this group of carriers.

- query = 
    DIVIDE(
        SUM(
            V(energy_export_crude_oil_baseload, energy_export_crude_oil_backup, demand),
            V(energy_export_diesel_baseload, energy_export_diesel_backup, demand),
            V(energy_export_gasoline_baseload, energy_export_gasoline_backup, demand),
            V(energy_export_heavy_fuel_oil_baseload, energy_export_heavy_fuel_oil_backup, demand),
            V(energy_export_kerosene_baseload, energy_export_kerosene_backup, demand),
            V(energy_export_lpg_baseload, energy_export_lpg_backup, demand),
        ),
        BILLIONS
    )
- unit = PJ