### Exported volume of liquid hydrogen (transit flow)
# Returns user-defined exported volume of liquid hydrogen in PJ. This export and correspondingly forced import make up the transit flow of this carrier.

- query = 
    DIVIDE(
        V(energy_export_liquid_hydrogen_baseload, demand),
        BILLIONS
    )
- unit = PJ