# Exported volume of ammonia (transit flow)
# Returns total exported volume of ammonia in PJ. The difference between export and import makes up the transit flow of this carrier.

- query = 
    DIVIDE(
      SUM(V(energy_export_ammonia_baseload, energy_export_ammonia_backup, demand)),
      BILLIONS
    )
- unit = PJ
