### Future space requirements of ammonia
# Returns future space requirements of imported ammonia that is part of the transit flow in ha

- query = 
    space_requirement_costs_ammonia_ha_per_mj = 0.00001;
    PRODUCT(
        V(energy_export_ammonia_baseload, demand), 
        space_requirement_costs_ammonia_ha_per_mj
    )
- unit = ha