### Exported volume of ammonia (transit flow)
# Returns user-defined exported volume of ammonia in PJ. This export and correspondingly forced import make up the transit flow of this carrier.

- query = 
    DIVIDE(
        V(energy_export_ammonia_baseload, demand),
        BILLIONS
    )
- unit = PJ