### Future space requirements of LNG
# Returns future space requirements of imported LNG that is part of the transit flows in km^2. 


- query = 
        PRODUCT(
                V(energy_import_lng,land_use_per_unit),
                V(energy_import_lng,number_of_units)
        )
- unit = km^2