### Future space requirements of LOHC
# Returns future space requirements of imported LOHC that is part of the transit flow in ha

- query = 
    space_requirement_costs_lohc_ha_per_mj = 0.00001;
    PRODUCT(
        V(energy_export_lohc_baseload, demand), 
        space_requirement_costs_lohc_ha_per_mj
    )
- unit = ha