### Future space requirements of diesel
# Returns future space requirements of imported diesel that is part of the transit flows in kn^2. 
# Query relies on land_use_per_unit which is km^2 per PJ for this node.

- query = 
        PRODUCT(
                V(energy_import_diesel,land_use_per_unit),
                V(energy_import_diesel,number_of_units)
        )
- unit = km^2