# Exported volume of LNG (transit flow)
# Returns total exported volume of LNG in PJ. The difference between export and import makes up the transit flow of this carrier.

- query = 
    DIVIDE(
      V(energy_export_lng_baseload, demand),
      BILLIONS
    )
- unit = PJ
