# Final consumption of electricity in national transport (energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Electricity -- electricity?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_electricity_in_national_transport_energetic)
