# Final consumption of electricity in other (energetic use only).
#
# Sector:      Other -- sector == :other
# Carrier:     Electricity -- electricity?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_electricity_in_other_energetic)
