# Total GHG emissions Klimaatsector categories excl. indirect emissions (indirecte emissies),
# LULUCF (landgebruik) and international transport (internationaal transport)

- unit = MT
- query = Q(direct_emissions_klimaattafel_total_ghg_excl_indirecte_emissies_landgebruik_internationaal_transport)
