# Mechanical turk query for 1990 other GHG emissions
# Sums all other_ghg values for 1990 from emissions.csv
# Bunkers is handled separately as the result depends on the set input for bunkers

- unit = mt
- query =
    SUM(
      DIVIDE(
        SUM(
          EMISSIONS(agriculture_non_specified, energetic, other_ghg, 1990),
          EMISSIONS(agriculture_non_specified, non_energetic, other_ghg, 1990),
          EMISSIONS(buildings_non_specified, energetic, other_ghg, 1990),
          EMISSIONS(energy_electricity_and_heat_production, energetic, other_ghg, 1990),
          EMISSIONS(energy_fuels_production, energetic, other_ghg, 1990),
          EMISSIONS(energy_fugitive_emissions, non_energetic, other_ghg, 1990),
          EMISSIONS(energy_hydrogen_production, non_energetic, other_ghg, 1990),
          EMISSIONS(energy_methanol_production, non_energetic, other_ghg, 1990),
          EMISSIONS(households_non_specified, energetic, other_ghg, 1990),
          EMISSIONS(industry_aluminium, non_energetic, other_ghg, 1990),
          EMISSIONS(industry_chemicals, non_energetic, other_ghg, 1990),
          EMISSIONS(industry_fertilizers, non_energetic, other_ghg, 1990),
          EMISSIONS(industry_food, non_energetic, other_ghg, 1990),
          EMISSIONS(industry_non_specified, energetic, other_ghg, 1990),
          EMISSIONS(industry_other_metals, non_energetic, other_ghg, 1990),
          EMISSIONS(industry_other, non_energetic, other_ghg, 1990),
          EMISSIONS(industry_paper, non_energetic, other_ghg, 1990),
          EMISSIONS(industry_refineries, energetic, other_ghg, 1990),
          EMISSIONS(industry_refineries, non_energetic, other_ghg, 1990),
          EMISSIONS(industry_steel, non_energetic, other_ghg, 1990),
          EMISSIONS(lulucf_emissions, non_energetic, other_ghg, 1990),
          EMISSIONS(other_non_specified, energetic, other_ghg, 1990),
          EMISSIONS(other_other_transportation, energetic, other_ghg, 1990),
          EMISSIONS(transport_non_specified, energetic, other_ghg, 1990),
          EMISSIONS(waste_non_specified, non_energetic, other_ghg, 1990)
        ),
        THOUSANDS
      ),
      Q(direct_emissions_bunkers_other_ghg_1990)
    )
