- query =
    SUM(
      Q(gas_in_co2_of_electricity_production),
      Q(oil_in_co2_of_electricity_production),
      Q(lignite_in_co2_of_electricity_production),
      Q(coal_in_co2_of_electricity_production),
      Q(waste_in_co2_of_electricity_production),
      Q(hydrogen_in_co2_of_electricity_production)
    )
- unit = mt
