- query =
    [
      MERIT_LOAD_CURVES(:buildings_cooling_collective_heatpump_water_water_ts_electricity),
      MERIT_LOAD_CURVES(:buildings_cooling_airconditioning_electricity)
    ].transpose.map {|x| x.reduce(:+)}
