- query =
    SUM_CURVES(
      Q(merit_household_appliances_demand),
      Q(merit_household_cooling_demand),
      Q(merit_household_cooking_demand),
      Q(merit_household_lighting_demand)
    )
- unit = curve