- query =
    SUM_CURVES(
      Q(merit_households_appliances_demand),
      Q(merit_households_cooling_demand),
      Q(merit_households_cooking_demand),
      Q(merit_households_lighting_demand)
    )
- unit = curve