# - query = MERIT_LOAD_CURVES(industry_final_demand_for_other_electricity)
- query =
    [
      MERIT_LOAD_CURVES(industry_final_demand_for_other_electricity),
      MERIT_LOAD_CURVES(industry_final_demand_for_other_ict_electricity)
    ].transpose.map {|x| x.reduce(:+)}
