- query =
    [
      MERIT_LOAD_CURVES(:households_cooker_induction_electricity),
      MERIT_LOAD_CURVES(:households_cooker_resistive_electricity),
      MERIT_LOAD_CURVES(:households_cooker_halogen_electricity)
    ].transpose.map {|x| x.reduce(:+)}
