# Energetic final demand of the 'oil_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand), "crude_oil? || gasoline? || diesel? || lpg? || kerosene? || heavy_fuel_oil?"
          ),
          energetic?
        ),
        value
      )
    ) / BILLIONS
