# Final demand of steam hot water of MT temperature

- unit = PJ
- query =
    DIVIDE(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(mt_heat)),"sector == :bunkers"
          ),
          steam_hot_water?
        ),
        value
      ),
      BILLIONS
    )
