- deprecated_key = policy_goal_co2_emission_reached
# 

- unit = boolean

LESS_OR_EQUAL(
  UNIT(Q(total_co2_emissions),billions),
  PRODUCT(
    SUM(1, DIVIDE(V(GOAL(co2_emission),user_value),100)),
    AREA(co2_emission_1990)
  )
)