- unit = PJ
- query =
    future:
    DIVIDE(
        V(G(energy_import),"output_of_natural_gas + output_of_network_gas").sum -
        V(G(energy_export),"input_of_natural_gas + input_of_network_gas").sum
    ,BILLIONS)
