# Query for Sankey diagram: connection between fossil and electricity network

- unit = PJ
- query =
    SUM(
        Q(oil_in_source_of_electricity_production),
        Q(gas_in_source_of_electricity_production),
        Q(coal_in_source_of_electricity_production),
        Q(coal_gas_in_source_of_electricity_production)
    )
