# Query for Sankey diagram: connection between electricity network and other electricity demand

- unit = PJ
- query =
    SUM(
      Q(electricity_prod_to_other_in_sankey),
      Q(electricity_prod_to_central_heat_prod_in_sankey),
      Q(electricity_prod_to_energy_in_sankey),
      Q(electricity_prod_to_feedstock_in_sankey),
      DIVIDE(V(energy_compressor_network_gas,input_of_electricity),BILLIONS),
      DIVIDE(V(energy_production_synthetic_kerosene_electricity, input_of_electricity),BILLIONS)
    )
