# Query for Sankey diagram: connection between electricity network and P2G offshore

- query = DIVIDE(V(energy_hydrogen_hybrid_electrolysis_wind_electricity,input_of_electricity),BILLIONS)
- unit = PJ