# Query for Sankey diagram: connection between electricity network and flexibility

- unit = PJ
- query =
    SUM(
        Q(electricity_prod_to_p2g_in_sankey),
        Q(electricity_prod_to_p2h_in_sankey),
        Q(electricity_curtailed)
    )
