# Query for Sankey diagram: connection between other_renewables and electricity network

- unit = PJ
- query =
    SUM(
        Q(geothermal_in_source_of_electricity_production),
        Q(hydro_in_source_of_electricity_production)
    )
