- query =
    SUM(V(energy_distribution_wood_pellets, demand),
        V(energy_distribution_torrefied_biomass_pellets, demand),
        - V(INTERSECTION(G(final_demand_group), USE(non_energetic)),
        "input_of_wood_pellets").sum
        )

- unit = MJ
