- query =
    SUM(
       V( industry_heat_well_geothermal,
          energy_heat_well_geothermal,
          energy_chp_supercritical_mt_waste_mix,
          energy_chp_supercritical_ht_waste_mix,
          energy_chp_supercritical_ccs_mt_waste_mix,
          energy_chp_supercritical_ccs_ht_waste_mix,
          energy_chp_combined_cycle_mt_network_gas,
          energy_chp_combined_cycle_ht_network_gas,
          energy_chp_ultra_supercritical_mt_coal,
          energy_chp_ultra_supercritical_ht_coal,
          energy_chp_ultra_supercritical_cofiring_mt_coal,
          energy_chp_ultra_supercritical_cofiring_ht_coal,
          energy_chp_ultra_supercritical_mt_lignite,
          energy_chp_ultra_supercritical_ht_lignite,
          energy_chp_local_mt_wood_pellets,
          energy_chp_local_ht_wood_pellets,
          energy_chp_local_engine_mt_biogas,
          energy_chp_local_engine_ht_biogas,
          energy_chp_local_engine_mt_network_gas,
          energy_chp_local_engine_ht_network_gas,
          industry_chp_engine_gas_power_fuelmix,
          industry_chp_turbine_gas_power_fuelmix,
          industry_chp_ultra_supercritical_coal,
          industry_chp_combined_cycle_gas_power_fuelmix,
          industry_chp_wood_pellets,
          energy_heat_production_lt_residual_heat,
          energy_heat_production_mt_residual_heat,
          energy_heat_production_ht_residual_heat,
          energy_heat_import_lt_steam_hot_water,
          energy_heat_import_mt_steam_hot_water,
          energy_heat_import_ht_steam_hot_water,
       output_of_steam_hot_water),
       V(agriculture_geothermal, output_of_useable_heat)
    )

- unit = MJ
