- query =
    SUM(
      PRODUCT(
        (V(energy_national_gas_network_natural_gas, demand) -
        V(INTERSECTION(G(final_demand_group), USE(non_energetic)),
        "input_of_network_gas").sum),
        (1.0 - Q(share_of_sustainable_gas_in_gas_network))
      ),
      V(energy_treatment_natural_gas, output_of_loss),
      V(energy_import_lpg, demand),
      V(transport_final_demand_lng, demand),
      V(bunkers_final_demand_lng, demand)
    )
- unit = MJ
