- query =
    PRODUCT(
        (V(energy_national_gas_network_natural_gas, demand) -
        V(INTERSECTION(G(final_demand_group), USE(non_energetic)),
        "input_of_network_gas").sum),
        Q(share_of_greengas_in_gas_network)
    ) +
    V(G(costs_production_chp_plants),input_of_biogas).sum

- unit = MJ