- query =
     {
    :coal_heater => V(households_water_heater_coal,share_of_households_useful_demand_for_hot_water_after_solar_heater),
    :gas_combined_heater => V(households_water_heater_combined_network_gas,share_of_households_useful_demand_for_hot_water_after_solar_heater),
    :oil_heater => V(households_water_heater_crude_oil,share_of_households_useful_demand_for_hot_water_after_solar_heater),
    :district_heater => V(households_water_heater_district_heating_steam_hot_water,share_of_households_useful_demand_for_hot_water_after_solar_heater),
    :electric_heater => V(households_water_heater_electricity,share_of_households_useful_demand_for_hot_water_after_solar_heater),
    :air_heat_pump => V(households_water_heater_heatpump_air_water_electricity,share_of_households_useful_demand_for_hot_water_after_solar_heater),
    :ground_heat_pump => V(households_water_heater_heatpump_ground_water_electricity,share_of_households_useful_demand_for_hot_water_after_solar_heater),
    :hybrid_heat_pump => V(households_water_heater_hybrid_heatpump_air_water_electricity,share_of_households_useful_demand_for_hot_water_after_solar_heater),
    :gas_heater => V(households_water_heater_network_gas,share_of_households_useful_demand_for_hot_water_after_solar_heater),
    :wood_pellet_heater => V(households_water_heater_wood_pellets,share_of_households_useful_demand_for_hot_water_after_solar_heater)
    }.sort_by { |name, share| share }.to_a.last[1]