# Bio-footprint of greengas as a percentage of total areable land

- query =
    V(G(final_demand_group), primary_demand_of_greengas
    ).sum / V(CARRIER(greengas), typical_production_per_km2) / AREA(areable_land)