- query =
    PRODUCT(
      DIVIDE(
        SUM(V(GROUP(dispatchable_production), "installed_production_capacity_in_mw_electricity")),
        SUM(V(FILTER(mo_converters, "profitability == :profitable"), "installed_production_capacity_in_mw_electricity"))
      ),
      100
    )
