- unit = MT
- query =
    DIVIDE(
        SUM(
            MV(molecules_production_fischer_tropsch_synthetic_must_run_co2, demand),
            MV(molecules_production_fischer_tropsch_synthetic_dispatchable_co2, demand)
        ),
        BILLIONS
    )
    
