# Final consumption of hydrogen in national transport (non-energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Hydrogen -- hydrogen? || liquid_hydrogen? || lohc?
# Use type:    Non-energetic -- !energetic?

- unit = PJ
- query =
    Q(final_consumption_of_hydrogen_in_national_transport_non_energetic)
