# Final consumption of non-renewable waste in national transport (non-energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Non-renewable waste
# Use type:    Non-energetic -- !energetic?
#
# Exception: includes the share of non-renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_non_renewable_waste_in_national_transport_non_energetic)
