# Direct conversion input of hydro_electricity for central heat production

- query = 
    DIVIDE(
      SUM(
        V(
          G(methanol_production),
          "methanol_output_conversion / (1 - loss_output_conversion - residual_heat_input_conversion) * input_of_hydro_electricity"
        )
      ), 
      BILLIONS
    )
- unit = PJ
