# Special conversion for gas_and_gas_derivatives to methanol

- query = 
    SUM(
      Q(conversion_from_natural_gas_to_methanol),
      Q(conversion_from_compressed_network_gas_to_methanol),
      Q(conversion_from_lng_to_methanol)
    )
- unit = PJ
