# Query for scenario tools regional overview: direct conversion demand of coal for electricity production

- query =
    DIVIDE(
      SUM(
        V(
          Q(electricity_producing_converters_sankey),
          input_of(
            coal,
            coal_gas,
            lignite,
            cokes
          )
        )
      ),
      BILLIONS
    )
- unit = PJ
