# Final consumption of geothermal in national transport (energetic use only).
#
# Sector:      National transport -- sector == :transport
# Carrier:     Geothermal -- geothermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_geothermal_in_national_transport_energetic)
