# Mechanical turk query: sum of the final consumption of coal and coal products over all sectors (energetic and non-energetic use combined).
# The result should equal final_consumption_of_coal_and_coal_products_total.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_coal_and_coal_products_in_agriculture_total),
      Q(final_consumption_of_coal_and_coal_products_in_energy_total),
      Q(final_consumption_of_coal_and_coal_products_in_households_total),
      Q(final_consumption_of_coal_and_coal_products_in_buildings_total),
      Q(final_consumption_of_coal_and_coal_products_in_national_transport_total),
      Q(final_consumption_of_coal_and_coal_products_in_international_transport_total),
      Q(final_consumption_of_coal_and_coal_products_in_other_total),
      Q(final_consumption_of_coal_and_coal_products_in_industry_total)
    )
