# Mechanical turk query: sum of the final consumption per carrier in industry fertilizers (non-energetic use only).
# The carrier exceptions (network_gas, waste_mix, crude oil mix) are incorporated in the carrier
# groups, so the result should equal
# final_consumption_from_industry_fertilizers_non_energetic.

- unit = PJ
- query =
    SUM(
      Q(final_consumption_of_ammonia_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_coal_and_coal_products_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_electricity_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_gaseous_biofuels_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_geothermal_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_heat_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_hydrogen_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_liquid_biofuels_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_methanol_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_natural_gas_and_gas_products_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_non_renewable_waste_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_oil_and_oil_products_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_renewable_waste_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_solar_thermal_in_industry_fertilizers_non_energetic),
      Q(final_consumption_of_solid_biofuels_in_industry_fertilizers_non_energetic)
    )
