# Energetic final demand of the 'ambient' carrier group in households cooling

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(EG(final_demand),EG(cooling_households)), "ambient_heat? || ambient_cold?"
          ),
          "energetic?"
        ),
        value
      )
    ) / BILLIONS
