# Non-energetic final demand of the 'solar' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            EG(final_demand), "solar_radiation?"
          ),
          "!energetic?"
        ),
        value
      )
    ) / BILLIONS
