# Final demand of the 'solar' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :bunkers"
            ),
            energetic?
          ),
          solar_radiation?
        ),
        value
      )
    ) / BILLIONS
