# The CO2 emissions of bunkering are added to the emissions of 1990 with the percentage
# that is set by the international transport sliders.

- query =
    PRODUCT(
      DIVIDE(
          QUERY_FUTURE(policy_total_energy_cost),
          QUERY_PRESENT(policy_total_energy_cost)
      ) - 1.0,
      100
    )
