- query =
    SUM(
      INPUT_VALUE(households_insulation_level_old_houses) - AREA(insulation_level_old_houses_min),
      INPUT_VALUE(households_insulation_level_new_houses) - AREA(insulation_level_new_houses_min)
    )
- unit = m^2K/W
