# All demands for heating and cooling in households

- query =
    SUM(
        V(buildings_final_demand_for_space_heating_coal, demand),
        V(buildings_final_demand_for_space_heating_crude_oil, demand),
        V(buildings_final_demand_for_space_heating_network_gas, demand),
        V(buildings_final_demand_for_space_heating_wood_pellets, demand),
        V(buildings_final_demand_for_space_heating_electricity, demand),
        V(buildings_final_demand_for_space_heating_steam_hot_water, demand),
        V(buildings_final_demand_for_cooling_network_gas, demand),
        V(buildings_final_demand_for_cooling_electricity, demand)
    )

- unit = MJ
