- query =
    SUM(
        V(households_final_demand_for_cooking_network_gas, demand),
        V(households_final_demand_for_cooking_wood_pellets, demand),
        V(households_final_demand_for_cooking_electricity, demand)
    )

- unit = MJ
