#Used for an IF statement, if hydrogen is used in a scenario this network node is > 0

- query =
          SUM(V(
                bunkers_useful_demand_planes,
                bunkers_useful_demand_ships,
                demand
                ))

- unit = MJ
