# The CO2 emissions of bunkering are added to the emissions of 1990 with the percentage
# that is set by the international transport sliders.

- query =
      DIVIDE(
        SUM(
            Q(co2_sheet_non_energy_emissions_agriculture),
            Q(co2_sheet_non_energy_emissions_built_environment),
            Q(co2_sheet_non_energy_emissions_transport),
            Q(co2_sheet_non_energy_emissions_industry)
        ),
        SUM(
            Q(co2_sheet_agriculture_total_co2_emissions),
            Q(co2_sheet_buildings_households_total_co2_emissions),
            Q(co2_sheet_industry_energy_total_co2_emissions),
            Q(co2_sheet_transport_total_co2_emissions)
            )
      )
