# Energetic demand of hydrogen for freight shipping transport

- query = 
    SUM(
      V(
        FILTER(
          FILTER(
            INTERSECTION(
              EG(final_demand),EG(freight_transport),EG(shipping_transport)
            ),
            energetic?
          ),
          hydrogen?
        ),
        value
      )
    )
- unit = MJ
