# Returns the capacity of turbine hydrogen power plants
- query = 
        PRODUCT(
  		V(energy_power_turbine_hydrogen,number_of_units),
  		V(energy_power_turbine_hydrogen,electricity_output_capacity)	
  		)
- unit = MW


