- query =
        SUM(
            V(transport_useful_demand_passenger_trains,
              transport_useful_demand_trams,
              transport_useful_demand_freight_trains,
              primary_co2_emission)
          ) / THOUSANDS


- unit = T
