- query =
    SUM(
      V(
        bunkers_plane_using_electricity,
        bunkers_plane_using_hydrogen,
        primary_co2_emission
      ),
      V(
        bunkers_plane_using_kerosene_mix,
        "demand * weighted_carrier_co2_per_mj"
      )
    ) / THOUSANDS
- unit = T

