- query =
          SUM(V(
                transport_useful_demand_cars,
                transport_useful_demand_motorcycles,
                transport_useful_demand_bicycles,
                primary_co2_emission
          )) / THOUSANDS

- unit = T
