- query =
          SUM(V(
                transport_useful_demand_busses,
                transport_useful_demand_passenger_trains,
                transport_useful_demand_trams,
                primary_co2_emission
          )) / THOUSANDS

- unit = T
