- query =
        SUM(
            V(CHILDREN(V(transport_useful_demand_passenger_trains)), primary_co2_emission).sum,
            V(CHILDREN(V(transport_useful_demand_trams)), primary_co2_emission).sum,
            V(CHILDREN(V(transport_useful_demand_freight_trains)), primary_co2_emission).sum
          )

- unit = T
