- query =
    SUM(
      V(
        bunkers_ship_using_lng_mix,
        bunkers_ship_using_hydrogen,
        bunkers_ship_using_ammonia,
        bunkers_ship_using_electricity,
        primary_co2_emission
      ),
      V(
        bunkers_ship_using_heavy_fuel_oil,
        bunkers_ship_using_methanol_mix,
        "demand * weighted_carrier_co2_per_mj"
      )
    ) / THOUSANDS
- unit = T
