# 

- unit = mj

SUM(V(
  biomass_burner_agri_agriculture_energetic,
  bio_oil_chp_industry_energetic,
  biomass_chp_industry_energetic,
  biomass_burner_industry_industry_energetic,
  greengas_burner_industry_industry_energetic, 
  biomass_burner_other_other_energetic,
  heater_on_greengas_households_energetic,
  heater_on_biomass_households_energetic;
    output_of_heat_carriers
))