# 

- unit = converters

V(
  gas_conv_energy_energetic,
  large_chp_industry_energetic,
  coal_pwd_energy,
  coal_pwd_ccs_energy,
  coal_conv_energy,
  coal_lignite_energy,
  coal_oxyfuel_ccs_energy,
  coal_igcc_energy,
  coal_igcc_ccs_energy,
  oil_plant_energy,
  gas_ccgt_energy,
  nuclear_iii_energy,
  wind_offshore_energy,
  co_firing_coal_energy,
  co_firing_gas_energy,
  hydro_mount_energy,
  blue_energy_energy,
  nuclear_conv_energy_energetic,
  ccgt_ccs_energy,
  lignite_chp_energy,
  oil_chp_energy,
  coal_chp_energy
)