# Use of dry_biomass in buildings sector

- unit = PJ
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(buildings)), demand_of_bio_resources_including_abroad_of(dry_biomass)
    ).sum / BILLIONS
