# Use of oily_biomass in energy sector

- unit = PJ
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(energy)), demand_of_bio_resources_including_abroad_of(oily_biomass)
    ).sum / BILLIONS
