# Primary demand of carrier group 'oily_biomass' for the export converter group

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(energy_export_bio_oil_products_backup, demand),
        V(energy_export_bio_kerosene_backup, demand),
        V(energy_ecport_biodiesel_backup,demand)
      ),
      BILLIONS
    )
