# Use of biogenic_waste in transport sector

- unit = PJ
- query =
    V(
        INTERSECTION(G(final_demand_group),SECTOR(transport)), demand_of_bio_resources_including_abroad_of(biogenic_waste)
    ).sum / BILLIONS
