# Primary demand of carrier group 'oily_biomass' for the export converter group

- unit = PJ
- query =
      DIVIDE(
        SUM(
          V(energy_export_oily_biomass, demand),
          V(energy_export_bio_oil_products, demand)
          ),
          BILLIONS
        )