# Primary demand of carrier group 'oily_biomass' for the export converter group and curtailment converter

- unit = PJ
- query =
    SUM(
        Q(demand_of_bio_resource_oily_biomass_from_curtailment),
        Q(demand_of_bio_resource_oily_biomass_from_export)
    )
