# Use of oily_biomass in industry sector

- unit = PJ
- query =
    DIVIDE(
      SUM(
        V(
          INTERSECTION(
            G(final_demand_group),
            SECTOR(industry)
          ),
          G(industry_transformation),
          demand_of_bio_resources_including_abroad_of(oily_biomass)
        )
      ),
      BILLIONS
    )
