# fraction of electricity in heating for agriculture.

- query =
    DIVIDE(
      SUM(V(CHILDREN(V(agriculture_useful_demand_useable_heat)),input_of_electricity)),
      SUM(V(CHILDREN(V(agriculture_useful_demand_useable_heat)),demand))
    )
- unit = #
