- deprecated_key = share_of_renewable_electricity
# 

- unit = factor

DIVIDE(
  SUM(V( G(electricity_production); output_of_electricity * sustainability_share)),
  SUM(V( G(electricity_production); output_of_electricity))
)