# The share of energetic network gas in aggregated other industry

- query =
    DIVIDE(
        Q(final_demand_of_natural_gas_and_derivatives_in_aggregated_other_industry_energetic),
        Q(final_demand_of_aggregated_other_industry_energetic)
    ) 
- unit = factor
