# The share of heat from district heating in the supply of household heat demand

- query =
    DIVIDE(
    	V(Q(heating_converters_in_households),input_of_steam_hot_water).sum,
     	Q(energy_used_for_heating_in_households)
    )
- unit = factor
