# The share of energetic electricity in aggregated other industry

- query =
    DIVIDE(
        Q(final_demand_of_electricity_in_aggregated_other_industry_energetic),
        Q(final_demand_of_aggregated_other_industry_energetic)
    )
- unit = factor
