# The share of the original demand for heat, that has been prevented by installing extra insulation

- unit = factor

V(extra_insulation_savings_households_energetic,share_of_heating_demand_with_current_insulation_households_energetic)