# The share of non-energetic coal and coal gas in aggregated other industry

- query =
    DIVIDE(
        Q(final_demand_of_coal_and_coal_gas_in_other_non_specified_industry_non_energetic),
        Q(final_demand_of_other_non_specified_industry_non_energetic)
    )
- unit = factor
