# Returns how much of the hot water demand of households is provided by P2H

- query = V(households_useful_demand_for_hot_water_for_houses_with_p2h, share_of_households_useful_demand_for_hot_water_after_solar_heater)
- unit = factor

