# This query calculates the input share of electricity for the hybrid heat pump

- query = V(households_space_heater_hybrid_heatpump_air_water_electrcity, electricity_input_conversion)
- unit = factor
