# The share of non-energetic cokes in aggregated other industry

- query =
    DIVIDE(
        Q(final_demand_of_cokes_in_other_non_specified_industry_non_energetic),
        Q(final_demand_of_other_non_specified_industry_non_energetic)
    )
- unit = factor
