# This query calculates the input share of network gas for the hybrid heat pump

- query = present:V(households_space_heater_hybrid_heatpump_air_water_electrcity, network_gas_input_conversion)
- unit = factor
