# The share of heat from district heating in the supply of household heat demand

- unit = factor

DIVIDE(
	SUM(V(CHILDREN(V(heating_demand_households_energetic));input_of_steam_hot_water)),
 	Q(energy_used_for_heating_in_households)
	)