# Returns how much of the hot water demand of households is provided by combined network gas-powered water heaters

- query = V(households_water_heater_combined_network_gas,share_of_households_useful_demand_hot_water)
- unit = factor
