# Returns how much of the hot water demand of households is provided by solar water heaters

- query = V(households_water_heater_solar_thermal,share_of_households_useful_demand_hot_water)
- unit = factor
