# Returns how much of the hot water demand of households is provided by coal-powered heaters

- query = V(households_water_heater_coal,share_of_households_useful_demand_for_hot_water_after_solar_heater_and_add_on)
- unit = factor
