# The share of non-energetic network gas in aggregated other industry

- query =
    DIVIDE(
        Q(final_demand_of_natural_gas_and_derivatives_in_other_non_specified_industry_non_energetic),
        Q(final_demand_of_other_non_specified_industry_non_energetic)
    ) 
- unit = factor
