# The share of electricity in the supply of household heat demand, including the greengas in the natural gas

- query =
    DIVIDE(
    	V(Q(heating_converters_in_households),input_of_electricity).sum,
     	Q(energy_used_for_heating_in_households)
    )
- unit = factor
- deprecated_key = heating_households_electricity_share
