# The share of energetic crude oil in aggregated other industry

- query =
    DIVIDE(
        Q(final_demand_of_biomass_products_in_aggregated_other_industry_nl_energetic),
        Q(final_demand_of_aggregated_other_industry_energetic)
    )
- unit = factor
