# This query calculates the renewability of households space heating using the same definition (at July 20, 2012) as the dashboard renewability.
# It can be used for diagnostic purposes. E.g. When I apply more insulation, why does my overal renewability go down?
# Note: there is one exception: all gas input of micro CHP is included instead of only the portion attributable to space heating.
# In future work this should be improved.

- query =
    DIVIDE(
      SUM(V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater_and_add_on)), "sustainability_share * demand"))
      + V(households_water_heater_solar_thermal, "sustainability_share * demand")
        *
        Q(share_from_households_water_heater_solar_thermal_to_households_useful_demand_for_space_heating_after_insulation_for_houses_with_solar_heater)
      + V(households_space_heater_heatpump_add_on_electricity, "sustainability_share * demand")
        *
        Q(share_from_households_space_heater_heatpump_add_on_electricity_to_households_useful_demand_for_space_heating_after_insulation_for_houses_with_add_on)
    ,
      SUM(V(CHILDREN(V(households_useful_demand_for_space_heating_after_insulation_and_solar_heater_and_add_on)), "demand"))
      + V(households_water_heater_solar_thermal, "demand")
        *
        Q(share_from_households_water_heater_solar_thermal_to_households_useful_demand_for_space_heating_after_insulation_for_houses_with_solar_heater)
      + V(households_space_heater_heatpump_add_on_electricity, "demand")
        *
        Q(share_from_households_space_heater_heatpump_add_on_electricity_to_households_useful_demand_for_space_heating_after_insulation_for_houses_with_add_on)
    )
- unit = factor
