# Returns how much of the heat demand of households is provided by heat pumps

- query = V(households_space_heater_heatpump_ground_water_electricity,share_of_households_useful_demand_for_space_heating_after_insulation_and_solar_heater_and_add_on)
- unit = factor
