# Share of renewable electricity in the total amount of electricity produced

- unit = factor

DIVIDE(
  SUM(V( G(electricity_production); output_of_electricity * sustainability_share)),
  SUM(V( G(electricity_production); output_of_electricity))
)