# The share of energetic hydrogen in aggregated other industry

- query =
    DIVIDE(
        Q(final_demand_of_hydrogen_in_aggregated_other_industry_energetic),
        Q(final_demand_of_aggregated_other_industry_energetic)
    )
- unit = factor
