- query =
    DIVIDE(
      Q(dashboard_total_curtailment),
      SUM(
        Q(electricity_produced_from_inflexible_converters),
        Q(electricity_curtailment_solar_pv_input)
      )
    )
- unit = %
