# Final consumption of renewable waste, all sectors (energetic and non-energetic use combined).
#
# Sector:      All sectors
# Carrier:     Renewable waste
# Use type:    Total
#
# Exception: includes the share of renewable waste in waste mix.

- unit = PJ
- query =
    Q(final_consumption_of_renewable_waste_total)
