# The depreciation costs of the future mv net

- query =
          SUM(
              QUERY_FUTURE(mv_net_costs_delta_present_future_investment_costs) / V(energy_power_mv_distribution_network_electricity,technical_lifetime)
          )

- unit = euro
