# The delta (difference) between the present and the future costs of the medium voltage net.

- query =
          SUM(
              QUERY_FUTURE(mv_net_CAPEX),
              QUERY_FUTURE(mv_net_OPEX)
          )

- unit = euro
