# The costs of the future mv net

- query =
          SUM(
              QUERY_FUTURE(mv_net_additional_capital_costs),
              QUERY_FUTURE(mv_net_additional_depreciation_costs)
          )

- unit = euro
