# The OPEX of the future mv net, consisting of operation and maintenance costs

- query =
          SUM(
              QUERY_FUTURE(mv_net_additional_operation_and_maintenance_costs)
          )

- unit = euro
