# The capital costs of the future mv net

- query =
          SUM(
              QUERY_FUTURE(mv_net_costs_delta_present_future_investment_costs) / 2.0 * Q(mv_net_costs_delta_present_future_wacc)
          )

- unit = euro
