# Assuming linear depreciation, in line with ETM cost calculation

- query =
    PRODUCT(
      DIVIDE(
        Q(heat_infrastructure_ht_indoor_investment_costs),
        2.0),
      Q(heat_infrastructure_ht_indoor_wacc)
    )
- unit = euro
