# Ground level houses also require indoor investment costs.
# Ground level houses include corner houses, detached and semi-detached houses and terraced houses.

- query =
      number_of_ground_level_houses = AREA(number_of_corner_houses) + AREA(number_of_detached_houses) + AREA(number_of_semi_detached_houses) + AREA(number_of_terraced_houses);
      ground_level_houses_with_district_heating = number_of_ground_level_houses * V(households_space_heater_district_heating_ht_steam_hot_water_aggregator,share_of_households_useful_demand_for_space_heating_after_insulation);

      ground_level_houses_with_district_heating * AREA(heat_infrastructure_households_ht_indoor_investment_costs_ground_level_houses_eur)
- unit = euro
