
- unit = curve
- query = 
    PRODUCT_CURVES(
        Q(energy_imported_hydrogen_backup_hydrogen_output_curve),
        COALESCE_CURVE(nil,default=Q(costs_per_mwh_hydrogen_by_import),length = 8760)
            )
    
