
- unit = curve
- query = 
    PRODUCT_CURVES(
        Q(production_costs_per_mwh_curve_hydrogen_offshore_hybrid_wind_turbine),
        DIVIDE_CURVES(
            Q(energy_hydrogen_electrolysis_hybrid_wind_electricity_hydrogen_output_curve),
            Q(hydrogen_production_curve)    
        )
    )
