
- unit = curve
- query = 
    PRODUCT_CURVES(
        Q(production_costs_per_mwh_curve_hydrogen_autothermal_reformer_ccs_must_run),
        DIVIDE_CURVES(
            Q(energy_hydrogen_autothermal_reformer_ccs_must_run_hydrogen_output_curve),
            Q(hydrogen_production_curve)    
        )
    )

