
- unit = curve
- query = 
    PRODUCT_CURVES(
        Q(production_costs_per_mwh_curve_hydrogen_ammonia_reformer_dispatchable),
        DIVIDE_CURVES(
            Q(energy_hydrogen_ammonia_reformer_dispatchable_hydrogen_output_curve),
            Q(hydrogen_production_curve)    
        )
    )
