
- unit = curve
- query = 
    PRODUCT_CURVES(
        Q(energy_hydrogen_electrolysis_wind_electricity_hydrogen_output_curve),
        COALESCE_CURVE(nil,default=Q(production_costs_per_mwh_hydrogen_by_offshore_wind_turbine),length = 8760)
            )
    
