
- unit = curve
- query = 
    PRODUCT_CURVES(
        Q(industry_residual_hydrogen_hydrogen_output_curve),
        COALESCE_CURVE(nil,default=Q(production_costs_per_mwh_industry_residual_hydrogen),length = 8760)
            )
    
