# Selects the electricity input capacity of power-to-heat technologies for district heating using the p2h node group. Capacity of demand technologies is considered negative for the installed flexible capacities chart.

- query =
    PRODUCT(
      -1,
      SUM(
        V(
          FILTER(
            G(p2h),
            "heat_network"
          ),
          "input_capacity * number_of_units"
        )
      )
    )
- unit = MW