# Selects the electricity output capacity of dispatchable oil power plants using the electricity producing oil converters query.

- query =
    SUM(
      V(
        Q(
          electricity_producing_oil_converters
        ),
        "input_capacity * electricity_output_conversion * number_of_units"
      )
    )
- unit = MW