# Selects the electricity output capacity of dispatchable hydro power plants.

- query =
    SUM(
      V(
        FILTER(
          ALL(),
          "merit_order && (merit_order.subtype == :dispatchable) && water_input_conversion > 0"
        ),
        "input_capacity * electricity_output_conversion * number_of_units"
      )
    )
- unit = MW
