# Selects the electricity output capacity of dispatchable wood pellets power plants using the electricity producing wood pellets converters query. Co-firing of wood pellets is allocated to the capacity (bio)coal power plants.

- query =
    PRODUCT(
      -1,
      Q(energy_flexibility_synthetic_kerosene_electricity_capacity)
    )
- unit = MW