- query =
    SUM_CURVES(
        V(
          households_solar_pv_solar_radiation,
          buildings_solar_pv_solar_radiation,
          energy_power_solar_pv_solar_radiation,
          curtailment_output_curve,
          energy_flexibility_curtailment_electricity,
          electricity_input_curve
        )
    )
- unit = curve