# Final consumption of oil and oil products, all sectors (energetic use only).
#
# Sector:      All sectors
# Carrier:     Oil and oil products
# Use type:    Energetic -- energetic?
#
# Exception: includes the non-biogenic share of crude oil in agriculture, buildings, households, industry.

- unit = PJ
- query =
    Q(final_consumption_of_oil_and_oil_products_energetic)
