- unit = curve
- query = 
    SUM_CURVES(
        V(energy_heat_well_deep_mt_geothermal, steam_hot_water_output_curve),
        V(energy_heat_well_shallow_heatpump_mt_geothermal, steam_hot_water_output_curve)
    )
