- unit = curve
- query =
    SUM_CURVES(
      V(energy_heat_industry_chemicals_other_mt_residual_heat,steam_hot_water_output_curve),
      V(energy_heat_industry_chemicals_refineries_mt_residual_heat,steam_hot_water_output_curve),
      V(energy_heat_industry_chemicals_fertilizers_mt_residual_heat,steam_hot_water_output_curve),
      V(energy_heat_industry_other_ict_mt_residual_heat,steam_hot_water_output_curve)
    )
