# Apartment blocks require indoor investment costs
# These costs depend on whether an apartment block has a collective heating system ('block heating')
# Or individual heating per apartment

- query =
      apartments_with_district_heating = AREA(number_of_apartments) * V(households_space_heater_district_heating_mt_steam_hot_water_aggregator,share_of_households_useful_demand_for_space_heating_after_insulation);
      apartments_without_block_heating = apartments_with_district_heating * (1 - AREA(heat_share_of_apartments_with_block_heating));

      apartments_without_block_heating * AREA(heat_infrastructure_households_mt_indoor_investment_costs_apartments_without_block_heating_eur)
- unit = euro
