# Assuming linear depreciation, in line with ETM cost calculation

- query =
    DIVIDE(
      SUM(
          Q(heat_infrastructure_households_mt_indoor_investment_costs),
          Q(heat_infrastructure_buildings_mt_indoor_investment_costs),
         ),
      V(energy_distribution_mt_steam_hot_water, technical_lifetime)
      )
- unit = euro
