# Investment costs for this part of the heat network. Also used in the ETM costs export.

- query =
    SUM(
      Q(heat_infrastructure_households_mt_indoor_investment_costs),
      Q(heat_infrastructure_buildings_mt_indoor_investment_costs),
      )
- unit = euro
