# Ground level houses also require indoor investment costs.
# Ground level houses include corner houses, detached and semi-detached houses and terraced houses.

- query =
      Q(ground_level_houses_with_mt_district_heating) * AREA(heat_infrastructure_households_mt_indoor_investment_costs_ground_level_houses_eur)
- unit = euro
