- query = SUM(V(FILTER(INTERSECTION(SECTOR(industry), G(final_demand_group)), "electricity_input_conversion == 0"), primary_demand_of(coal,coal_gas,cokes,compressed_network_gas,crude_oil,diesel,heavy_fuel_oil,gasoline,kerosene,lignite,lng,lpg,natural_gas,refinery_gas)))

- unit = MJ
