- query =
          SUM(V(households_collective_chp_network_gas, demand),
              V(households_collective_burner_network_gas, demand),
              V(buildings_collective_burner_network_gas, demand),
              V(buildings_collective_chp_network_gas, demand),
              V(energy_heater_for_heat_network_network_gas, demand),
              V(agriculture_chp_engine_network_gas, demand)
              ) *  Q(share_of_sustainable_gas_in_gas_network)

- unit = MJ
