- query =
          SUM(V(
                energy_chp_local_engine_network_gas,
                energy_heat_backup_burner_network_gas,
                energy_heat_burner_network_gas,
                demand
                )
              ) * (1 - Q(share_of_sustainable_gas_in_gas_network))

- unit = MJ
