- query =
          Q(factsheet_supply_gas_from_fossil) -
          SUM(
              Q(factsheet_demand_gas_from_fossil_individual),
              Q(factsheet_demand_gas_from_fossil_collective),
              Q(factsheet_demand_gas_from_fossil_industry),
              Q(factsheet_demand_gas_from_fossil_transport)
              )

- unit = MJ
