- query =
      SUM(
          V(households_collective_heatpump_water_water_electricity, input_of_electricity),
          V(households_collective_geothermal, input_of_electricity),
          V(buildings_collective_heatpump_water_water_electricity, input_of_electricity),
          V(buildings_collective_geothermal, input_of_electricity)
          )

- unit = MJ
