- query =
    SUM(
      V(
        FILTER(
          FILTER(
            FILTER(
              EG(final_demand),"sector == :industry"
            ),
            energetic?
          ),
          network_gas?
        ),
        value
      )
    ) * Q(share_of_sustainable_gas_in_gas_network)

- unit = MJ
