- query =
          SUM(
              V(
                INTERSECTION(G(heat_production),SECTOR(energy)), "input_of_wood_pellets + input_of_torrefied_biomass_pellets"
                )
              )

- unit = MJ
