- query =
          SUM(
              V(energy_import_lpg, demand),
              V(transport_final_demand_lng, demand),
              V(bunkers_final_demand_lng, demand)
              )

- unit = MJ
