# Total cost of hydrogen production by biomass gasification per MWh produced hydrogen

- query =
    DIVIDE(
        V(energy_hydrogen_biomass_gasification, total_costs_per(:node)),
        DIVIDE(
            V(energy_hydrogen_biomass_gasification, output_of_hydrogen),
            MJ_PER_MWH
        )
    )
