# Total cost of hydrogen production by biomass gasification + ccs per kg produced hydrogen
# Energy density of h2 is 120.1 MJ per kg

- query =
    IF(
        V(energy_hydrogen_flexibility_p2g_electricity, output_of_hydrogen) == 0,
        0.0,
        -> {
            DIVIDE(
                V(energy_hydrogen_flexibility_p2g_electricity, total_costs_per(:converter)),
                DIVIDE(
                    V(energy_hydrogen_flexibility_p2g_electricity, output_of_hydrogen),
                    120.1
                )
            )
        }
    )
