# Total cost of hydrogen production from solar pv park per MWh produced hydrogen

- query =
    DIVIDE(
        SUM(
            V(energy_hydrogen_electrolysis_solar_electricity, total_costs_per(:node)),
            V(energy_hydrogen_solar_pv_solar_radiation, total_costs_per(:node))
        ),
        DIVIDE(
            V(energy_hydrogen_electrolysis_solar_electricity, output_of_hydrogen),
            MJ_PER_MWH
        )
    )
