# Total cost of hydrogen production by biomass gasification + ccs per MWh produced hydrogen

- query =
    IF(
        V(energy_hydrogen_flexibility_p2g_electricity, output_of_hydrogen) == 0,
        0.0,
        -> {
            DIVIDE(
                V(energy_hydrogen_flexibility_p2g_electricity, total_costs_per(:node)),
                DIVIDE(
                    V(energy_hydrogen_flexibility_p2g_electricity, output_of_hydrogen),
                    MJ_PER_MWH
                )
            )
        }
    )
