# Total cost of hydrogen production from stored hydrogen in salt cavern per MWh produced hydrogen

- query =
    DIVIDE(
        SUM(
            V(energy_hydrogen_storage_salt_cavern, capital_expenditures_excluding_ccs_per(:node)),
            V(energy_hydrogen_storage_salt_cavern, operating_expenses_excluding_ccs_per(:node))
        ),
        DIVIDE(
            V(energy_hydrogen_storage_salt_cavern, output_of_hydrogen),
            MJ_PER_MWH
        )
    )
