# Total cost of hydrogen production by autothermal reforming + ccs per kg produced hydrogen
# Energy density of h2 is 120.1 MJ per kg

- query =
    DIVIDE(
        V(energy_hydrogen_autothermal_reformer_ccs, total_costs_per(:node)),
        DIVIDE(
            V(energy_hydrogen_autothermal_reformer_ccs, output_of_hydrogen),
            3600
        )
    )
