# Total cost of hydrogen production by autothermal reforming per kg produced hydrogen
# Energy density of h2 is 120.1 MJ per kg

- query =
    DIVIDE(
        V(energy_hydrogen_autothermal_reformer, total_costs_per(:node)),
        DIVIDE(
            V(energy_hydrogen_autothermal_reformer, output_of_hydrogen),
            MJ_PER_MWH
        )
    )
