# Returns the capacity of wood_pellets chp's for the sector agriculture.
- query = 
        PRODUCT(
  		V(agriculture_chp_engine_wood_pellets,number_of_units),
  		V(agriculture_chp_engine_wood_pellets,electricity_output_capacity)	
  		)
- unit = MW

