# bcm = billion cubic meters
# In ETM all energy flows are in lower heating value (LHV), therefore we have to use the LHV caloric value
# to calculate the volume
# LHV caloric values = 31.65 MJ / m3

- unit = bcm
- query = Q(natural_gas_to_electricity_prod_in_sankey) / 31.65
