# Final consumption of ammonia in energy (energetic use only).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Ammonia -- ammonia?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_ammonia_in_energy_energetic)
