# Final consumption of geothermal in energy (energetic use only).
#
# Sector:      Energy -- sector == :energy
# Carrier:     Geothermal -- geothermal?
# Use type:    Energetic -- energetic?

- unit = PJ
- query =
    Q(final_consumption_of_geothermal_in_energy_energetic)
