
# Returns the capacity of inland wind turbines for power production.
- query = 
        PRODUCT(
  		V(energy_power_wind_turbine_inland,number_of_units),
  		V(energy_power_wind_turbine_inland,electricity_output_capacity)	
  		)
- unit = MW


