- deprecated_key = ambient_heat_use
# The total use of all ambient heat in the model 'left' of final demand.
# 
# Here, we should build something that calculates the ambient heat that is used only 'left' of the final demand for the renewability calculation, so the ambient heat is not counted double.
# 
# This dynamic solution is not possible yet, but should be fixed when it is.

- unit = mj

SUM(V(
heatpump_boiler_households_energetic,
heat_pump_with_chs_households_energetic,
heatpump_households_energetic,
gasheatpump_households_energetic,
heat_pump_with_CHS_agri_agriculture_energetic,
geothermal_agri_agriculture_energetic,
heatpump_addon_households_energetic,
gasheatpump_ts_buildings_energetic,
heatpump_ts_buildings_energetic;
input_of_ambient_heat)
)