- deprecated_key = households_heating_final_demand_ambient
# 

- unit = mj

SUM(
V(Q(households_heating_converters);input_of_ambient_heat),
V(Q(households_heating_converters);input_of_solar_radiation),
V(collective_geothermal_households_energetic;input_of_steam_hot_water)
)