- deprecated_key = buildings_heating_final_demand_biomass
# The green gas in the natural gas is included as well.

- unit = mj

SUM(
V(Q(heating_converters_in_buildings);input_of_biomass),
V(Q(heating_converters_in_buildings);input_of_biofuel),
V(Q(heating_converters_in_buildings);input_of_greengas),
V(Q(heating_converters_in_buildings);input_of_biodiesel),
V(Q(heating_converters_in_buildings);input_of_bio_ethanol),
V(Q(heating_converters_in_buildings);input_of_algae_diesel),
V(Q(heating_converters_in_buildings);input_of_biogas),
PRODUCT(Q(share_of_greengas_in_gas_network),SUM(V(Q(heating_converters_in_buildings);input_of_natural_gas)))
)