# The biomass gas used in for cooking, including the green gas used in the gasmix.

- deprecated_key = cooking_biomass_households
- unit = mj

SUM(V(biomass_cooking_households_energetic;input_of_biomass),
V(gas_stove_households_energetic;input_of_natural_gas * sustainability_share))
