- deprecated_key = cooking_gas_households
# The natural gas used in for cooking, including the greengas in the mix.

- unit = mj

SUM(V(gas_stove_households_energetic;input_of_natural_gas),
NEG(V(gas_stove_households_energetic;input_of_natural_gas*sustainability_share))
)