- deprecated_key = households_cooling_converters
# 

- unit = converters

V(
heatpump_cooling_households_energetic,
gasheatpump_cooling_households_energetic,
heatpump_ts_cooling_households_energetic,
airco_households_energetic
)
