# The total operation_and_maintenance_cost for electricity production.

- unit = euro

SUM(
  V(G(heat_production); operation_and_maintenance_cost_fixed),  V(G(heat_production); operation_and_maintenance_cost_variable_total)
)