- deprecated_key = electricity_export_losses
# This is the loss of the energy export.

- unit = mj

SUM(
         PRODUCT(
                         V(electricity_export_energy;demand)
                         ,
                         INVERSE(V(hv_electricity_network_energy;
                             electricity_output_conversion))
                           )
         ,
         NEG(V(electricity_export_energy;demand)  )
         )