- deprecated_key = all_plants
# All plants including

- unit = converters

V(
  Q(coal_plants),
  Q(oil_plants),
  Q(gas_plants),
  Q(nuclear_plants),
  Q(wind_plants),
  Q(biomass_plants),
  Q(other_plants)
)