- deprecated_key = total_input_for_hot_water
# 

- unit = mj

SUM(
 SUM(V(Q(households_hot_water_converters);demand)),
 V(fuel_cell_chp_households_energetic;steam_hot_water_output_conversion * input_of_natural_gas),
 V(micro_chp_hot_water_households_energetic;steam_hot_water_output_conversion * input_of_natural_gas)
)