- deprecated_key = households_heating_final_demand_total
# 

- unit = mj

SUM(
 SUM(V(Q(households_heating_converters);demand)),
 Q(input_of_fossil_households_heating_chps),
 V(collective_biomass_chp_households_energetic;steam_hot_water_output_conversion * demand)
)