- deprecated_key = households_heating_final_demand_total
# 

- unit = mj

SUM(
 SUM(V(Q(heating_converters_in_households);demand)),
 Q(fossil_energy_used_for_heating_in_household_chps),
 V(collective_biomass_chp_households_energetic;steam_hot_water_output_conversion * demand)
)