- deprecated_key = households_hot_water_fossil
# adjusted for the green gas in the gas

- unit = mj

SUM(
V(Q(households_hot_water_converters);input_of_coal),
V(Q(households_hot_water_converters);input_of_crude_oil),
V(Q(households_hot_water_converters);input_of_natural_gas),
NEG(SUM(V(Q(households_hot_water_converters);input_of_natural_gas*sustainability_share))),
V(Q(households_hot_water_converters);input_of_diesel),
V(Q(households_hot_water_converters);input_of_gasoline),
V(Q(households_hot_water_converters);input_of_lignite),
V(hot_water_fuel_cell_households_energetic;demand),
V(micro_chp_hot_water_households_energetic;steam_hot_water_output_conversion * input_of_natural_gas)
)