- deprecated_key = heat_and_cold_production_fossil
# the green gas is deducted.

- unit = pj

DIVIDE(PRODUCT(DIVIDE(SUM(V(G(heat_production);input_of_fossil_carriers)

,NEG(PRODUCT(SUM(V(G(heat_production);input_of_natural_gas)),Q(greengas_share)))

),SUM(V(G(heat_production);demand))),SUM(V(G(heat_production);output_of_heat_and_cooling_carriers))),BILLIONS)