- deprecated_key = households_heating_converters
# 

- unit = converters

V(
heat_pump_with_chs_households_energetic,
electric_heater_households_energetic,
solar_panel_for_heating_households_energetic,
micro_CHP_production_households,
city_heating_network_energy_energetic,
heatpump_households_energetic,
heatpump_addon_households_energetic,
collective_geothermal_households_energetic,
heater_on_biomass_households_energetic,
heater_on_coal_households_energetic,
heater_on_oil_households_energetic,
gasheatpump_households_energetic,
central_heating_households_energetic,
gas_fired_heater_households_energetic
)