- deprecated_key = heat_from_biomass_industry
# Heat produced from biomass, including the heat from greengas in the gas burner.

- unit = mj

SUM(V(biomass_burner_industry_industry_energetic,greengas_burner_industry_industry_energetic;output_of_heat_carriers), V(gas_burner_industry_industry_energetic;
                     output_of_heat_carriers * sustainability_share))