- deprecated_key = heat_from_biomass_buildings
# The % biomass * the total usable heat.

- unit = mj

PRODUCT(DIVIDE(Q(biomass_derivatives_used_for_heating_in_buildings),Q(energy_used_for_heating_in_buildings)),V(heating_buildings_energetic;input_of_useable_heat))