- deprecated_key = other_primary_demand_without_gas
# 

- unit = pj

SUM(
Q(other_biomass_primary_demand),
Q(other_oil_primary_demand),
Q(other_uranium_primary_demand),
Q(other_coal_primary_demand),
Q(other_lignite_primary_demand),
Q(other_waste_primary_demand),
Q(all_biofuels_other_primary),
Q(other_non_e_primary_demand),
Q(other_imported_e_primary_demand)
)