- deprecated_key = agriculture_primary_demand_without_gas
# 

- unit = pj

SUM(
Q(agriculture_biomass_primary_demand),
Q(agriculture_oil_primary_demand),
Q(agriculture_uranium_primary_demand),
Q(agriculture_coal_primary_demand),
Q(agriculture_lignite_primary_demand),
Q(agriculture_waste_primary_demand),
Q(agriculture_non_e_primary_demand),
Q(all_biofuels_agriculture_primary),
Q(agriculture_imported_e_primary_demand)
)