- deprecated_key = input_of_biomass_households_heating_chps
# 

- unit = mj

SUM(V(micro_CHP_production_households,
            collective_coal_chp_households_energetic,
            collective_gas_chp_households_energetic;
           steam_hot_water_output_conversion * demand * sustainability_share
           ))