# including the green gas used in the gas burners

- unit = mj

SUM(
V(Q(hot_water_converters_in_households);input_of_biomass input_of_ambient_heat + input_of_solar_thermal + input_of_solar_radiation + input_of_biofuel + input_of_greengas + input_of_biodiesel + input_of_bio_ethanol + input_of_algae_diesel + input_of_biogas ),
V(Q(hot_water_converters_in_households);input_of_natural_gas*sustainability_share)
)