- deprecated_key = buildings_share_of_heat_schools
# 

- unit = factor

DIVIDE(V(heating_schools_current_insulation_buildings_energetic;demand),V(heat_demand_before_recirculation_buildings_energetic;demand))