# Takes the impact of the lower voltage level supply technologies and adds impact of supply technologies attached to mv_d net 

- unit = mw

SUM(
  PRODUCT(
    Q(lv_net_delta_capacity_supply),
    V(lv_electricity_network_energy_energetic ; simult_wd),
    V(lv_mv_transformer_energy ; simult_wd)
    ),
  Q(peak_load_delta_supply_units_connected_to_mv_distribution_net)
)