- unit = PJ
- query =
    DIVIDE(
    SUM(
    	V(households_cooker_halogen_electricity,households_cooker_resistive_electricity,households_cooker_induction_electricity,
    		input_of_electricity))
    ,BILLIONS)
