- query =
    SUM(
      Q(heat_infrastructure_households_indoor_pipelines_yearly_maintenance_costs),
      Q(heat_infrastructure_buildings_indoor_pipelines_yearly_maintenance_costs),
      Q(heat_infrastructure_exchanger_station_yearly_maintenance_costs),
      Q(heat_infrastructure_sub_station_yearly_maintenance_costs),
      Q(heat_infrastructure_distribution_pipelines_yearly_maintenance_costs),
      Q(heat_infrastructure_connection_pipelines_yearly_maintenance_costs),
      Q(heat_infrastructure_primary_pipelines_yearly_maintenance_costs)
    )
- unit = euro